
language: ruby
rvm: 2.3.3
sudo: false

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
