DQMCore: dqm4hep::core::TiXmlHandle Class Reference
dqm4hep::core::TiXmlHandle Class Reference
A TiXmlHandle is a class that wraps a node pointer with null checks; this is an incredibly useful thing.
#include <tinyxml.h>
Public Member Functions
TiXmlHandle (TiXmlNode *_node)
Create a handle from any node (at any depth of the tree.) This can be a null pointer.
TiXmlHandle (const TiXmlHandle &ref)
Copy constructor.
TiXmlHandle & operator= (const TiXmlHandle &ref)
TiXmlHandle FirstChild () const
Return a handle to the first child node.
TiXmlHandle FirstChild (const char *value) const
Return a handle to the first child node with the given name.
TiXmlHandle FirstChildElement () const
Return a handle to the first child element.
TiXmlHandle FirstChildElement (const char *value) const
Return a handle to the first child element with the given name.
TiXmlHandle Child (const char *value, int count) const
Return a handle to the "index" child with the given name.
TiXmlHandle Child (int count) const
Return a handle to the "index" child.
TiXmlHandle ChildElement (const char *value, int count) const
Return a handle to the "index" child element with the given name.
TiXmlHandle ChildElement (int count) const
Return a handle to the "index" child element.
TiXmlHandle FirstChild (const std::string &_value) const
TiXmlHandle FirstChildElement (const std::string &_value) const
TiXmlHandle Child (const std::string &_value, int index) const
TiXmlHandle ChildElement (const std::string &_value, int index) const
TiXmlNode * ToNode () const
Return the handle as a TiXmlNode.
TiXmlElement * ToElement () const
Return the handle as a TiXmlElement.
TiXmlText * ToText () const
Return the handle as a TiXmlText.
TiXmlUnknown * ToUnknown () const
Return the handle as a TiXmlUnknown.
TiXmlNode * Node () const
TiXmlElement * Element () const
TiXmlText * Text () const
TiXmlUnknown * Unknown () const
Private Attributes
TiXmlNode * node = {nullptr}
Detailed Description
A TiXmlHandle is a class that wraps a node pointer with null checks; this is an incredibly useful thing.
Note that TiXmlHandle is not part of the TinyXml DOM structure. It is a separate utility class.
Take an example:
 <Document>
         <Element attributeA = "valueA">
                 <Child attributeB = "value1" />
                 <Child attributeB = "value2" />
         </Element>
 <Document>
Assuming you want the value of "attributeB" in the 2nd "Child" element, it's very easy to write a lot of code that looks like:
 TiXmlElement* root = document.FirstChildElement( "Document" );
 if ( root )
 {
         TiXmlElement* element = root->FirstChildElement( "Element" );
         if ( element )
         {
                 TiXmlElement* child = element->FirstChildElement( "Child" );
                 if ( child )
                 {
                         TiXmlElement* child2 = child->NextSiblingElement( "Child" );
                         if ( child2 )
{
                                 // Finally do something useful.
And that doesn't even cover "else" cases. TiXmlHandle addresses the verbosity of such code. A TiXmlHandle checks for null pointers so it is perfectly safe and correct to use:
 TiXmlHandle docHandle( &document );
 TiXmlElement* child2 = docHandle.FirstChild( "Document" ).FirstChild( "Element" ).Child( "Child", 1
).ToElement();
 if ( child2 )
 {
         // do something useful
Which is MUCH more concise and useful.
It is also safe to copy handles - internally they are nothing more than node pointers.
 TiXmlHandle handleCopy = handle;
What they should not be used for is iteration:
 int i=0;
 while ( true )
 {
         TiXmlElement* child = docHandle.FirstChild( "Document" ).FirstChild( "Element" ).Child( "Child", i
).ToElement();
         if ( !child )
                 break;
         // do something
         ++i;
 }
It seems reasonable, but it is in fact two embedded while loops. The Child method is a linear walk to find the element, so this code would iterate much more than it needs to. Instead, prefer:
 TiXmlElement* child = docHandle.FirstChild( "Document" ).FirstChild( "Element" ).FirstChild( "Child"
).ToElement();
 for( child; child; child=child->NextSiblingElement() )
 {
         // do something
 }
Definition at line 1806 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::core::TiXmlHandle::TiXmlHandle (TiXmlNode * _node) inline
Create a handle from any node (at any depth of the tree.) This can be a null pointer.
Definition at line 1809 of file tinyxml.h.
References node.
Referenced by Child(), ChildElement(), FirstChild(), and FirstChildElement().
{
         this->node = _node;
       }
dqm4hep::core::TiXmlHandle::TiXmlHandle (const TiXmlHandle & ref) inline
Copy constructor.
Definition at line 1813 of file tinyxml.h.
References node.
{
         this->node = ref.node;
       }
Member Function Documentation
TiXmlHandle dqm4hep::core::TiXmlHandle::Child (const char * value, int count) const
Return a handle to the "index" child with the given name.
The first child is 0, the second 1, etc.
Definition at line 1373 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChild(), node, and TiXmlHandle().
Referenced by Child().
{
       if (node != nullptr) {
         int i;
         TiXmlNode *child = node->FirstChild(value);
         for (i = 0; (child != nullptr) && i < count; child = child->NextSibling(value), ++i) {
           // nothing
         }
         if (child != nullptr)
           return TiXmlHandle(child);
       }
       return TiXmlHandle(nullptr);
     }
TiXmlHandle dqm4hep::core::TiXmlHandle::Child (int count) const
Return a handle to the "index" child.
The first child is 0, the second 1, etc.
Definition at line 1360 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChild(), node, and TiXmlHandle().
{
       if (node != nullptr) {
         int i;
         TiXmlNode *child = node->FirstChild();
         for (i = 0; (child != nullptr) && i < count; child = child->NextSibling(), ++i) {
           // nothing
         }
         if (child != nullptr)
           return TiXmlHandle(child);
       }
       return TiXmlHandle(nullptr);
     }
TiXmlHandle dqm4hep::core::TiXmlHandle::Child (const std::string & _value, int index) const inline
Definition at line 1857 of file tinyxml.h.
References Child().
{
         return Child(_value.c_str(), index);
       }
TiXmlHandle dqm4hep::core::TiXmlHandle::ChildElement (const char * value, int count) const
Return a handle to the "index" child element with the given name.
The first child element is 0, the second 1, etc. Note that only TiXmlElements are indexed: other types are not counted.
Definition at line 1399 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChildElement(), node, and TiXmlHandle().
Referenced by ChildElement().
{
       if (node != nullptr) {
         int i;
         TiXmlElement *child = node->FirstChildElement(value);
         for (i = 0; (child != nullptr) && i < count; child = child->NextSiblingElement(value), ++i) {
           // nothing
         }
         if (child != nullptr)
           return TiXmlHandle(child);
       }
       return TiXmlHandle(nullptr);
     }
TiXmlHandle dqm4hep::core::TiXmlHandle::ChildElement (int count) const
Return a handle to the "index" child element.
The first child element is 0, the second 1, etc. Note that only TiXmlElements are indexed: other types are not counted.
Definition at line 1386 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChildElement(), node, and TiXmlHandle().
{
       if (node != nullptr) {
         int i;
         TiXmlElement *child = node->FirstChildElement();
         for (i = 0; (child != nullptr) && i < count; child = child->NextSiblingElement(), ++i) {
           // nothing
         }
         if (child != nullptr)
           return TiXmlHandle(child);
       }
       return TiXmlHandle(nullptr);
     }
TiXmlHandle dqm4hep::core::TiXmlHandle::ChildElement (const std::string & _value, int index) const inline
Definition at line 1860 of file tinyxml.h.
References ChildElement().
{
         return ChildElement(_value.c_str(), index);
       }
TiXmlElement* dqm4hep::core::TiXmlHandle::Element () const inline
Deprecated:
use ToElement. Return the handle as a TiXmlElement. This may return null.
Definition at line 1895 of file tinyxml.h.
References ToElement().
Referenced by dqm4hep::core::XmlHelper::read2DVectorOfValues(), dqm4hep::core::XmlHelper::readParameter(), dqm4hep::core::XmlHelper::readParameters(), dqm4hep::core::XmlHelper::readValue(), and dqm4hep::core::XmlHelper::readVectorOfValues().
{
         return ToElement();
       }
TiXmlHandle dqm4hep::core::TiXmlHandle::FirstChild () const
Return a handle to the first child node.
Definition at line 1324 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChild(), node, and TiXmlHandle().
Referenced by FirstChild(), dqm4hep::core::XmlHelper::read2DVectorOfValues(), dqm4hep::core::XmlHelper::readParameter(), dqm4hep::core::XmlHelper::readParameters(), dqm4hep::core::XmlHelper::readValue(), and dqm4hep::core::XmlHelper::readVectorOfValues().
{
       if (node != nullptr) {
         TiXmlNode *child = node->FirstChild();
         if (child != nullptr)
           return TiXmlHandle(child);
       }
       return TiXmlHandle(nullptr);
     }
TiXmlHandle dqm4hep::core::TiXmlHandle::FirstChild (const char * value) const
Return a handle to the first child node with the given name.
Definition at line 1333 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChild(), node, and TiXmlHandle().
{
       if (node != nullptr) {
         TiXmlNode *child = node->FirstChild(value);
         if (child != nullptr)
           return TiXmlHandle(child);
       }
       return TiXmlHandle(nullptr);
     }
TiXmlHandle dqm4hep::core::TiXmlHandle::FirstChild (const std::string & _value) const inline
Definition at line 1850 of file tinyxml.h.
References FirstChild().
{
         return FirstChild(_value.c_str());
       }
TiXmlHandle dqm4hep::core::TiXmlHandle::FirstChildElement () const
Return a handle to the first child element.
Definition at line 1342 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChildElement(), node, and TiXmlHandle().
Referenced by FirstChildElement().
{
       if (node != nullptr) {
         TiXmlElement *child = node->FirstChildElement();
         if (child != nullptr)
           return TiXmlHandle(child);
       }
       return TiXmlHandle(nullptr);
     }
TiXmlHandle dqm4hep::core::TiXmlHandle::FirstChildElement (const char * value) const
Return a handle to the first child element with the given name.
Definition at line 1351 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChildElement(), node, and TiXmlHandle().
{
       if (node != nullptr) {
         TiXmlElement *child = node->FirstChildElement(value);
         if (child != nullptr)
           return TiXmlHandle(child);
       }
       return TiXmlHandle(nullptr);
     }
TiXmlHandle dqm4hep::core::TiXmlHandle::FirstChildElement (const std::string & _value) const inline
Definition at line 1853 of file tinyxml.h.
References FirstChildElement().
{
         return FirstChildElement(_value.c_str());
       }
TiXmlNode* dqm4hep::core::TiXmlHandle::Node () const inline
Deprecated:
use ToNode. Return the handle as a TiXmlNode. This may return null.
Definition at line 1889 of file tinyxml.h.
References ToNode().
{
         return ToNode();
       }
TiXmlHandle& dqm4hep::core::TiXmlHandle::operator= (const TiXmlHandle & ref) inline
Definition at line 1816 of file tinyxml.h.
References node.
{
         this->node = ref.node;
         return *this;
       }
TiXmlText* dqm4hep::core::TiXmlHandle::Text () const inline
Deprecated:
use ToText() Return the handle as a TiXmlText. This may return null.
Definition at line 1901 of file tinyxml.h.
References ToText().
{
         return ToText();
       }
TiXmlElement* dqm4hep::core::TiXmlHandle::ToElement () const inline
Return the handle as a TiXmlElement.
This may return null.
Definition at line 1872 of file tinyxml.h.
References node, and dqm4hep::core::TiXmlNode::ToElement().
Referenced by Element().
{
         return (((node != nullptr) && (node->ToElement() != nullptr)) ? node->ToElement() : nullptr);
       }
TiXmlNode* dqm4hep::core::TiXmlHandle::ToNode () const inline
Return the handle as a TiXmlNode.
This may return null.
Definition at line 1867 of file tinyxml.h.
References node.
Referenced by Node().
{
         return node;
       }
TiXmlText* dqm4hep::core::TiXmlHandle::ToText () const inline
Return the handle as a TiXmlText.
This may return null.
Definition at line 1877 of file tinyxml.h.
References node, and dqm4hep::core::TiXmlNode::ToText().
Referenced by Text().
{
         return (((node != nullptr) && (node->ToText() != nullptr)) ? node->ToText() : nullptr);
       }
TiXmlUnknown* dqm4hep::core::TiXmlHandle::ToUnknown () const inline
Return the handle as a TiXmlUnknown.
This may return null.
Definition at line 1882 of file tinyxml.h.
References node, and dqm4hep::core::TiXmlNode::ToUnknown().
Referenced by Unknown().
{
         return (((node != nullptr) && (node->ToUnknown() != nullptr)) ? node->ToUnknown() : nullptr);
       }
TiXmlUnknown* dqm4hep::core::TiXmlHandle::Unknown () const inline
Deprecated:
use ToUnknown() Return the handle as a TiXmlUnknown. This may return null.
Definition at line 1907 of file tinyxml.h.
References ToUnknown().
{
         return ToUnknown();
       }
Member Data Documentation
TiXmlNode* dqm4hep::core::TiXmlHandle::node = {nullptr} private
Definition at line 1912 of file tinyxml.h.
Referenced by Child(), ChildElement(), FirstChild(), FirstChildElement(), operator=(), TiXmlHandle(), ToElement(), ToNode(), ToText(), and ToUnknown().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc