DQMCore: dqm4hep::core::ExactRefCompareTest Class Reference
dqm4hep::core::ExactRefCompareTest Class Reference
ExactRefCompareTest class Compare the monitor element to its reference.
Classes
class Factory
Public Member Functions
ExactRefCompareTest (const std::string &name)
~ExactRefCompareTest () override=default
StatusCode readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override
Read the settings from the xml handle.
void userRun (MonitorElementPtr monitorElement, QualityTestReport &report) override
Runs a quality test on the given monitor element and return a quality estimate.
Public Member Functions inherited from dqm4hep::core::QualityTest
QualityTest (const std::string &type, const std::string &name)
Constructor.
virtual ~QualityTest ()
Destructor.
const std::string & type () const
Get the quality test type.
const std::string & name () const
Get the quality test name (unique identifier)
const std::string & description () const
Get the quality test description.
void run (MonitorElementPtr monitorElement, QualityTestReport &report)
Perform the quality test result and fill the quality test report.
virtual StatusCode init ()
Initialize the quality test.
virtual bool enoughStatistics (MonitorElementPtr monitorElement) const
Whether the monitor element has enough statistics to perform the qtest.
void setLimits (float warning, float error)
Set the warning and error limits on quality test result.
float warningLimit () const
Get the warning limit.
float errorLimit () const
Get the error limit.
Private Member Functions
void doHistogramTest (MonitorElementPtr monitorElement, QualityTestReport &report)
void doGraph1DTest (MonitorElementPtr monitorElement, QualityTestReport &report)
void doGraph2DTest (MonitorElementPtr monitorElement, QualityTestReport &report)
void doIsEqualTest (MonitorElementPtr monitorElement, QualityTestReport &report)
Private Attributes
bool m_compareUnderflow
bool m_compareOverflow
Additional Inherited Members
Static Public Member Functions inherited from dqm4hep::core::QualityTest
static float defaultWarningLimit ()
Get the default warning limit.
static float defaultErrorLimit ()
Get the default error limit.
Protected Member Functions inherited from dqm4hep::core::QualityTest
void fillBasicInfo (MonitorElementPtr monitorElement, QualityTestReport &report) const
Fill basic info in the qtest report.
Protected Attributes inherited from dqm4hep::core::QualityTest
std::string m_description
Quality test description.
Static Protected Attributes inherited from dqm4hep::core::QualityTest
static float m_defaultWarningLimit = 0.8
static float m_defaultErrorLimit = 0.5
Detailed Description
ExactRefCompareTest class Compare the monitor element to its reference.
Look for an strict equality in terms of object content For TH1 case (and all derived):
same number of bins
same bin content, bin by bin
if underflow option is set, check underflow bin equality
if overflow option is set, check overflow bin equality For TGraph, TGraph2D cases:
check for all point equality (to floating point precision) For any other TObject type:
use the method TObject::IsEqual() to assert equality
Definition at line 61 of file ExactRefCompareTest.cc.
Constructor & Destructor Documentation
dqm4hep::core::ExactRefCompareTest::ExactRefCompareTest (const std::string & name)
Definition at line 96 of file ExactRefCompareTest.cc.
References dqm4hep::core::QualityTest::m_description.
Referenced by dqm4hep::core::ExactRefCompareTest::Factory::createQualityTest().
         : QualityTest("ExactRefCompare", name),
         m_compareUnderflow(true),
         m_compareOverflow(true) {
       m_description = std::string("Compare the monitor element to its reference. ") +
       "Look for an strict equality in terms of object content.\n" +
       "For TH1 case (and all derived): \n" +
       "  - same number of bins\n" +
       "  - same bin content, bin by bin" +
       "  - if underflow option is set, check underflow bin equality" +
       "  - if overflow option is set, check overflow bin equality" +
       "For TGraph, TGraph2D cases:" +
       "  - check for all point equality (to floating point precision)" +
       "For any other TObject type:" +
       "  - use the method TObject::IsEqual() to assert equality";
     }
dqm4hep::core::ExactRefCompareTest::~ExactRefCompareTest () override default
Member Function Documentation
void dqm4hep::core::ExactRefCompareTest::doGraph1DTest (MonitorElementPtr monitorElement, QualityTestReport & report) private
Definition at line 232 of file ExactRefCompareTest.cc.
References dqm4hep::core::QualityTest::errorLimit(), dqm4hep::core::QualityTestReport::m_extraInfos, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, and dqm4hep::core::typeToString().
Referenced by userRun().
{
       TGraph *graph = monitorElement->objectTo<TGraph>();
       TGraph *reference = monitorElement->referenceTo<TGraph>();
       const unsigned int nPoints(graph->GetN());
       const unsigned int nPointsRef(reference->GetN());
       if(nPoints != nPointsRef) {
         report.m_message = "Graph and reference do not have the same number of points";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       unsigned int nDifferentPoints(0);
       for(Int_t point = 0 ; point < nPoints ; ++point) {
         Double_t x, y, xRef, yRef;
         graph->GetPoint(point, x, y);
         reference->GetPoint(point, xRef, yRef);
         const bool xAreDifferent(!(fabs(x-xRef) < std::numeric_limits<Double_t>::epsilon()));
         const bool yAreDifferent(!(fabs(y-yRef) < std::numeric_limits<Double_t>::epsilon()));
         if(xAreDifferent || yAreDifferent) {
           ++nDifferentPoints;
         }
       }
       if(nDifferentPoints != 0) {
         report.m_message = "Graph and reference are different (difference = " + typeToString(nDifferentPoints) + ")";
         report.m_quality = this->errorLimit() * (static_cast<float>(nPoints) - static_cast<float>(nDifferentPoints)) / static_cast<float>(nPoints);
       }
       else {
         report.m_message = "Graph and reference are equal !";
         report.m_quality = 1.f;
       }
       report.m_extraInfos["nDifferences"] = nDifferentPoints;
     }
void dqm4hep::core::ExactRefCompareTest::doGraph2DTest (MonitorElementPtr monitorElement, QualityTestReport & report) private
Definition at line 274 of file ExactRefCompareTest.cc.
References dqm4hep::core::QualityTest::errorLimit(), dqm4hep::core::QualityTestReport::m_extraInfos, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, and dqm4hep::core::typeToString().
Referenced by userRun().
{
       TGraph2D *graph = monitorElement->objectTo<TGraph2D>();
       TGraph2D *reference = monitorElement->referenceTo<TGraph2D>();
       const unsigned int nPoints(graph->GetN());
       const unsigned int nPointsRef(reference->GetN());
       if(nPoints != nPointsRef) {
         report.m_message = "Graph and reference do not have the same number of points";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       unsigned int nDifferentPoints(0);
       for(Int_t point = 0 ; point < nPoints ; ++point) {
         const Double_t x = graph->GetX()[point];
         const Double_t y = graph->GetY()[point];
         const Double_t z = graph->GetZ()[point];
         const Double_t xRef = reference->GetX()[point];
         const Double_t yRef = reference->GetY()[point];
         const Double_t zRef = reference->GetZ()[point];
         const bool xAreDifferent(!(fabs(x-xRef) < std::numeric_limits<Double_t>::epsilon()));
         const bool yAreDifferent(!(fabs(y-yRef) < std::numeric_limits<Double_t>::epsilon()));
         const bool zAreDifferent(!(fabs(z-zRef) < std::numeric_limits<Double_t>::epsilon()));
         if(xAreDifferent || yAreDifferent || zAreDifferent) {
           ++nDifferentPoints;
         }
       }
       if(nDifferentPoints != 0) {
         report.m_message = "Graph and reference are different (difference = " + typeToString(nDifferentPoints) + ")";
         report.m_quality = this->errorLimit() * (static_cast<float>(nPoints) - static_cast<float>(nDifferentPoints)) / static_cast<float>(nPoints);
       }
       else {
         report.m_message = "Graph and reference are equal !";
         report.m_quality = 1.f;
       }
       report.m_extraInfos["nDifferences"] = nDifferentPoints;
     }
void dqm4hep::core::ExactRefCompareTest::doHistogramTest (MonitorElementPtr monitorElement, QualityTestReport & report) private
Definition at line 171 of file ExactRefCompareTest.cc.
References dqm4hep::core::QualityTest::errorLimit(), m_compareOverflow, m_compareUnderflow, dqm4hep::core::QualityTestReport::m_extraInfos, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, and dqm4hep::core::typeToString().
Referenced by userRun().
{
       TH1 *histogram = monitorElement->objectTo<TH1>();
       TH1 *reference = monitorElement->referenceTo<TH1>();
       int nBins(0), nBinsRef(0);
       if(histogram->GetDimension() == 1) {
         nBins = histogram->GetNbinsX();
         nBinsRef = reference->GetNbinsX();
       }
       else if(histogram->GetDimension() == 2) {
         nBins = histogram->GetNbinsX() * histogram->GetNbinsY();
         nBinsRef = reference->GetNbinsX() * reference->GetNbinsY();
       }
       else if(histogram->GetDimension() == 3) {
         nBins = histogram->GetNbinsX() * histogram->GetNbinsY() * histogram->GetNbinsZ();
         nBinsRef = reference->GetNbinsX() * reference->GetNbinsY() * reference->GetNbinsZ();
       }
       else {
         report.m_message = "Histogram with invalid dimension (dim = " + typeToString(histogram->GetDimension()) + ") !";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       if(nBins != nBinsRef) {
         report.m_message = "Histogram and reference do not have the same number of bins";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       const int firstBin = m_compareUnderflow ? 0 : 1;
       const int lastBin = m_compareOverflow ? nBins : nBins+1;
       unsigned int nDifferentBins(0);
       for(auto bin = firstBin ; bin <= lastBin ; ++bin) {
         const Double_t binContent(histogram->GetBinContent(bin));
         const Double_t binContentRef(reference->GetBinContent(bin));
         const bool binsAreDifferent(!(fabs(binContent-binContentRef) < std::numeric_limits<Double_t>::epsilon()));
         if(binsAreDifferent) {
           ++nDifferentBins;
         }
       }
       if(nDifferentBins != 0) {
         report.m_message = "Histogram and reference are different (difference = " + typeToString(nDifferentBins) + ")";
         // Quality estimate as the percentage of different points.
         // This factor is scaled to the error limit to make sure the quality flag is set to ERROR
         report.m_quality = this->errorLimit() * (static_cast<float>(nBins) - static_cast<float>(nDifferentBins)) / static_cast<float>(nBins);
       }
       else {
         report.m_message = "Histogram and reference are equal !";
         report.m_quality = 1.f;
       }
       report.m_extraInfos["nDifferences"] = nDifferentBins;
     }
void dqm4hep::core::ExactRefCompareTest::doIsEqualTest (MonitorElementPtr monitorElement, QualityTestReport & report) private
Definition at line 320 of file ExactRefCompareTest.cc.
References dqm4hep::core::QualityTestReport::m_extraInfos, dqm4hep::core::QualityTestReport::m_message, and dqm4hep::core::QualityTestReport::m_quality.
Referenced by userRun().
{
       TObject *object = monitorElement->object();
       TObject *reference = monitorElement->reference();
       const bool equal(object->IsEqual(reference));
       if(!equal) {
         report.m_message = "Object and reference are different (using TObject::IsEqual(ref)).";
         report.m_quality = 0.f; // FIXME: a bit hard no ? ...
       }
       else {
         report.m_message = "Object and reference are equal (using TObject::IsEqual(ref))";
         report.m_quality = 1.f;
       }
       report.m_extraInfos["nDifferences"] = 1;
     }
StatusCode dqm4hep::core::ExactRefCompareTest::readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override virtual
Read the settings from the xml handle.
Implements dqm4hep::core::QualityTest.
Definition at line 115 of file ExactRefCompareTest.cc.
References m_compareOverflow, m_compareUnderflow, dqm4hep::core::XmlHelper::readParameter(), and RETURN_RESULT_IF_AND_IF.
{
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle, "CompareOverflow", m_compareOverflow));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle, "CompareUnderflow", m_compareUnderflow));
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::ExactRefCompareTest::userRun (MonitorElementPtr monitorElement, QualityTestReport & report) override virtual
Runs a quality test on the given monitor element and return a quality estimate.
Implements dqm4hep::core::QualityTest.
Definition at line 125 of file ExactRefCompareTest.cc.
References doGraph1DTest(), doGraph2DTest(), doHistogramTest(), doIsEqualTest(), dqm4hep::core::QualityTestReport::m_message, and dqm4hep::core::QualityTestReport::m_quality.
{
       const bool hasObject = (monitorElement->object() != nullptr);
       const bool hasReference = (monitorElement->reference() != nullptr);
       if (!hasObject) {
         report.m_message = "No object attached to monitor element";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_INVALID_PTR);
       }
       if (!hasReference) {
         report.m_message = "No reference attached to monitor element";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_INVALID_PTR);
       }
       const std::string objectClass(monitorElement->object()->ClassName());
       const std::string referenceClass(monitorElement->reference()->ClassName());
       const bool isHistogram = monitorElement->object()->InheritsFrom("TH1");
       const bool isGraph1D = monitorElement->object()->InheritsFrom("TGraph");
       const bool isGraph2D = monitorElement->object()->InheritsFrom("TGraph2D");
       const bool sameType = (objectClass == referenceClass);
       if(!sameType) {
         report.m_message = "Objet and reference do not have the same type";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       if (isHistogram) {
         this->doHistogramTest(monitorElement, report);
       }
       else if(isGraph1D) {
         this->doGraph1DTest(monitorElement, report);
       }
       else if(isGraph2D) {
         this->doGraph2DTest(monitorElement, report);
       }
       else {
         this->doIsEqualTest(monitorElement, report);
       }
     }
Member Data Documentation
bool dqm4hep::core::ExactRefCompareTest::m_compareOverflow private
Definition at line 81 of file ExactRefCompareTest.cc.
Referenced by doHistogramTest(), and readSettings().
bool dqm4hep::core::ExactRefCompareTest::m_compareUnderflow private
Definition at line 80 of file ExactRefCompareTest.cc.
Referenced by doHistogramTest(), and readSettings().
The documentation for this class was generated from the following file:
ExactRefCompareTest.cc