DQMCore: dqm4hep::core::TiXmlAttribute Class Reference
dqm4hep::core::TiXmlAttribute Class Reference
An attribute is a name-value pair.
#include <tinyxml.h>
Public Member Functions
TiXmlAttribute ()
Construct an empty attribute.
TiXmlAttribute (const std::string &_name, const std::string &_value)
std::string constructor.
TiXmlAttribute (const char *_name, const char *_value)
Construct an attribute with a name and value.
const char * Name () const
Return the name of this attribute.
const char * Value () const
Return the value of this attribute.
const std::string & ValueStr () const
Return the value of this attribute.
int IntValue () const
Return the value of this attribute, converted to an integer.
double DoubleValue () const
Return the value of this attribute, converted to a double.
const TIXML_STRING & NameTStr () const
int QueryIntValue (int *ival) const
QueryIntValue examines the value string.
int QueryDoubleValue (double *dval) const
QueryDoubleValue examines the value string. See QueryIntValue().
void SetName (const char *_name)
Set the name of this attribute.
void SetValue (const char *_value)
Set the value.
void SetIntValue (int _value)
Set the value from an integer.
void SetDoubleValue (double _value)
Set the value from a double.
void SetName (const std::string &_name)
STL std::string form.
void SetValue (const std::string &_value)
STL std::string form.
const TiXmlAttribute * Next () const
Get the next sibling attribute in the DOM. Returns null at end.
TiXmlAttribute * Next ()
const TiXmlAttribute * Previous () const
Get the previous sibling attribute in the DOM. Returns null at beginning.
TiXmlAttribute * Previous ()
bool operator== (const TiXmlAttribute &rhs) const
bool operator< (const TiXmlAttribute &rhs) const
bool operator> (const TiXmlAttribute &rhs) const
const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding) override
void Print (FILE *cfile, int depth) const override
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
void Print (FILE *cfile, int depth, TIXML_STRING *str) const
void SetDocument (TiXmlDocument *doc)
Public Member Functions inherited from dqm4hep::core::TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()=default
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Private Member Functions
TiXmlAttribute (const TiXmlAttribute &)
void operator= (const TiXmlAttribute &base)
Private Attributes
TiXmlDocument * document = {nullptr}
TIXML_STRING name = {}
TIXML_STRING value = {}
TiXmlAttribute * prev = {nullptr}
TiXmlAttribute * next = {nullptr}
Friends
class TiXmlAttributeSet
Additional Inherited Members
Public Types inherited from dqm4hep::core::TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_PARSING_ELEMENT,
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES, TIXML_ERROR_PARSING_EMPTY,
TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT, TIXML_ERROR_PARSING_DECLARATION,
TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA, TIXML_ERROR_DOCUMENT_TOP_ONLY,
TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from dqm4hep::core::TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *outString)
Expands entities in a string.
Static Public Attributes inherited from dqm4hep::core::TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from dqm4hep::core::TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *p, TIXML_STRING *text, bool trimWhiteSpace, const char *endTag, bool caseInsensitive, TiXmlEncoding encoding)
static const char * GetEntity (const char *p, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *tag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from dqm4hep::core::TiXmlBase
TiXmlCursor location = {}
void * userData = {nullptr}
Field containing a generic user pointer.
Static Protected Attributes inherited from dqm4hep::core::TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
An attribute is a name-value pair.
Elements have an arbitrary number of attributes, each with a unique name.
Note
The attributes are not TiXmlNodes, since they are not part of the tinyXML document object model. There are other suggested ways to look at this problem.
Definition at line 869 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::core::TiXmlAttribute::TiXmlAttribute () inline
Construct an empty attribute.
Definition at line 874 of file tinyxml.h.
References document, next, and prev.
                        : TiXmlBase() {
         document = nullptr;
         prev = next = nullptr;
       }
dqm4hep::core::TiXmlAttribute::TiXmlAttribute (const std::string & _name, const std::string & _value) inline
std::string constructor.
Definition at line 881 of file tinyxml.h.
{
         name = _name;
         value = _value;
         document = nullptr;
         prev = next = nullptr;
       }
dqm4hep::core::TiXmlAttribute::TiXmlAttribute (const char * _name, const char * _value) inline
Construct an attribute with a name and value.
Definition at line 890 of file tinyxml.h.
References document, name, next, prev, and value.
{
         name = _name;
         value = _value;
         document = nullptr;
         prev = next = nullptr;
       }
dqm4hep::core::TiXmlAttribute::TiXmlAttribute (const TiXmlAttribute &) private
Member Function Documentation
double dqm4hep::core::TiXmlAttribute::DoubleValue () const
Return the value of this attribute, converted to a double.
Definition at line 1028 of file tinyxml.cc.
References value.
{
       return atof(value.c_str());
     }
int dqm4hep::core::TiXmlAttribute::IntValue () const
Return the value of this attribute, converted to an integer.
Definition at line 1024 of file tinyxml.cc.
References value.
{
       return atoi(value.c_str());
     }
const char* dqm4hep::core::TiXmlAttribute::Name () const inline
Return the name of this attribute.
Definition at line 897 of file tinyxml.h.
References name.
Referenced by dqm4hep::core::TiXmlAttributeSet::Add(), and dqm4hep::core::TiXmlElement::CopyTo().
const TIXML_STRING& dqm4hep::core::TiXmlAttribute::NameTStr () const inline
Definition at line 912 of file tinyxml.h.
References name.
{
         return name;
       }
const TiXmlAttribute * dqm4hep::core::TiXmlAttribute::Next () const
Get the next sibling attribute in the DOM. Returns null at end.
Definition at line 925 of file tinyxml.cc.
References name, next, and value.
Referenced by dqm4hep::core::TiXmlElement::CopyTo(), dqm4hep::core::TiXmlElement::Print(), dqm4hep::core::XMLParser::resolveConstantsInElement(), dqm4hep::core::XMLParser::resolveForLoop(), and dqm4hep::core::TiXmlPrinter::VisitEnter().
{
       // We are using knowledge of the sentinel. The sentinel
       // have a value or name.
       if (next->value.empty() && next->name.empty())
         return nullptr;
       return next;
     }
TiXmlAttribute* dqm4hep::core::TiXmlAttribute::Next () inline
Definition at line 952 of file tinyxml.h.
{
         return const_cast<TiXmlAttribute *>((const_cast<const TiXmlAttribute *>(this))->Next());
       }
bool dqm4hep::core::TiXmlAttribute::operator< (const TiXmlAttribute & rhs) const inline
Definition at line 965 of file tinyxml.h.
References name.
{
         return name < rhs.name;
       }
void dqm4hep::core::TiXmlAttribute::operator= (const TiXmlAttribute & base) private
bool dqm4hep::core::TiXmlAttribute::operator== (const TiXmlAttribute & rhs) const inline
Definition at line 962 of file tinyxml.h.
References name.
{
         return rhs.name == name;
       }
bool dqm4hep::core::TiXmlAttribute::operator> (const TiXmlAttribute & rhs) const inline
Definition at line 968 of file tinyxml.h.
References name.
{
         return name > rhs.name;
       }
const char * dqm4hep::core::TiXmlAttribute::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) override virtual
Implements dqm4hep::core::TiXmlBase.
Definition at line 1210 of file tinyxmlparser.cc.
References dqm4hep::core::TiXmlParsingData::Cursor(), dqm4hep::core::TiXmlBase::IsWhiteSpace(), dqm4hep::core::TiXmlBase::location, name, dqm4hep::core::TiXmlBase::ReadName(), dqm4hep::core::TiXmlBase::ReadText(), dqm4hep::core::TiXmlDocument::SetError(), dqm4hep::core::TiXmlBase::SkipWhiteSpace(), dqm4hep::core::TiXmlParsingData::Stamp(), dqm4hep::core::TiXmlBase::TIXML_ERROR_READING_ATTRIBUTES, and value.
Referenced by dqm4hep::core::TiXmlDeclaration::Parse().
{
       p = SkipWhiteSpace(p, encoding);
       if ((p == nullptr) || (*p == 0))
         return nullptr;
       if (data != nullptr) {
         data->Stamp(p, encoding);
         location = data->Cursor();
       }
       // Read the name, the '=' and the value.
       const char *pErr = p;
       p = ReadName(p, &name, encoding);
       if ((p == nullptr) || (*p == 0)) {
         if (document != nullptr)
           document->SetError(TIXML_ERROR_READING_ATTRIBUTES, pErr, data, encoding);
         return nullptr;
       }
       p = SkipWhiteSpace(p, encoding);
       if ((p == nullptr) || (*p == 0) || *p != '=') {
         if (document != nullptr)
           document->SetError(TIXML_ERROR_READING_ATTRIBUTES, p, data, encoding);
         return nullptr;
       }
       ++p; // skip '='
       p = SkipWhiteSpace(p, encoding);
       if ((p == nullptr) || (*p == 0)) {
         if (document != nullptr)
           document->SetError(TIXML_ERROR_READING_ATTRIBUTES, p, data, encoding);
         return nullptr;
       }
       const char *end;
       const char SINGLE_QUOTE = '\'';
       const char DOUBLE_QUOTE = '\"';
       if (*p == SINGLE_QUOTE) {
         ++p;
         end = "\'"; // single quote in string
         p = ReadText(p, &value, false, end, false, encoding);
       } else if (*p == DOUBLE_QUOTE) {
         ++p;
         end = "\""; // double quote in string
         p = ReadText(p, &value, false, end, false, encoding);
       } else {
         // All attribute values should be in single or double quotes.
         // But this is such a common error that the parser will try
         // its best, even without them.
         value = "";
         while ((p != nullptr) && (*p != 0) // existence
                && !IsWhiteSpace(*p)        // whitespace
                && *p != '/' && *p != '>')  // tag end
         {
           if (*p == SINGLE_QUOTE || *p == DOUBLE_QUOTE) {
             // [ 1451649 ] Attribute values with trailing quotes not handled correctly
             // We did not have an opening quote but seem to have a
             // closing one. Give up and throw an error.
             if (document != nullptr)
               document->SetError(TIXML_ERROR_READING_ATTRIBUTES, p, data, encoding);
             return nullptr;
           }
           value += *p;
           ++p;
         }
       }
       return p;
     }
const TiXmlAttribute * dqm4hep::core::TiXmlAttribute::Previous () const
Get the previous sibling attribute in the DOM. Returns null at beginning.
Definition at line 944 of file tinyxml.cc.
References name, prev, and value.
{
       // We are using knowledge of the sentinel. The sentinel
       // have a value or name.
       if (prev->value.empty() && prev->name.empty())
         return nullptr;
       return prev;
     }
TiXmlAttribute* dqm4hep::core::TiXmlAttribute::Previous () inline
Definition at line 958 of file tinyxml.h.
{
         return const_cast<TiXmlAttribute *>((const_cast<const TiXmlAttribute *>(this))->Previous());
       }
void dqm4hep::core::TiXmlAttribute::Print (FILE * cfile, int depth) const inline override virtual
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements dqm4hep::core::TiXmlBase.
Definition at line 978 of file tinyxml.h.
{
         Print(cfile, depth, nullptr);
       }
void dqm4hep::core::TiXmlAttribute::Print (FILE * cfile, int depth, TIXML_STRING * str) const
Definition at line 963 of file tinyxml.cc.
References dqm4hep::core::TiXmlBase::EncodeString(), TIXML_STRING, and value.
{
       TIXML_STRING n, v;
       EncodeString(name, &n);
       EncodeString(value, &v);
       if (value.find('\"') == TIXML_STRING::npos) {
         if (cfile != nullptr) {
           fprintf(cfile, "%s=\"%s\"", n.c_str(), v.c_str());
         }
         if (str != nullptr) {
           (*str) += n;
           (*str) += "=\"";
           (*str) += v;
           (*str) += "\"";
         }
       } else {
         if (cfile != nullptr) {
           fprintf(cfile, "%s='%s'", n.c_str(), v.c_str());
         }
         if (str != nullptr) {
           (*str) += n;
           (*str) += "='";
           (*str) += v;
           (*str) += "'";
         }
       }
     }
int dqm4hep::core::TiXmlAttribute::QueryDoubleValue (double * dval) const
QueryDoubleValue examines the value string. See QueryIntValue().
Definition at line 998 of file tinyxml.cc.
References TIXML_SSCANF, dqm4hep::core::TIXML_SUCCESS, dqm4hep::core::TIXML_WRONG_TYPE, and value.
Referenced by dqm4hep::core::TiXmlElement::Attribute(), and dqm4hep::core::TiXmlElement::QueryDoubleAttribute().
{
       if (TIXML_SSCANF(value.c_str(), "%lf", dval) == 1)
         return TIXML_SUCCESS;
       return TIXML_WRONG_TYPE;
     }
int dqm4hep::core::TiXmlAttribute::QueryIntValue (int * ival) const
QueryIntValue examines the value string.
It is an alternative to the IntValue() method with richer error checking. If the value is an integer, it is stored in 'value' and the call returns TIXML_SUCCESS. If it is not an integer, it returns TIXML_WRONG_TYPE.
A specialized but useful call. Note that for success it returns 0, which is the opposite of almost all other TinyXml calls.
Definition at line 992 of file tinyxml.cc.
References TIXML_SSCANF, dqm4hep::core::TIXML_SUCCESS, dqm4hep::core::TIXML_WRONG_TYPE, and value.
Referenced by dqm4hep::core::TiXmlElement::Attribute(), and dqm4hep::core::TiXmlElement::QueryIntAttribute().
{
       if (TIXML_SSCANF(value.c_str(), "%d", ival) == 1)
         return TIXML_SUCCESS;
       return TIXML_WRONG_TYPE;
     }
void dqm4hep::core::TiXmlAttribute::SetDocument (TiXmlDocument * doc) inline
Definition at line 985 of file tinyxml.h.
References document.
{
         document = doc;
       }
void dqm4hep::core::TiXmlAttribute::SetDoubleValue (double _value)
Set the value from a double.
Definition at line 1014 of file tinyxml.cc.
References SetValue(), and TIXML_SNPRINTF.
Referenced by dqm4hep::core::TiXmlElement::SetDoubleAttribute().
{
       char buf[256];
 #if defined(TIXML_SNPRINTF)
       TIXML_SNPRINTF(buf, sizeof(buf), "%g", _value);
 #else
       sprintf(buf, "%g", _value);
 #endif
       SetValue(buf);
     }
void dqm4hep::core::TiXmlAttribute::SetIntValue (int _value)
Set the value from an integer.
Definition at line 1004 of file tinyxml.cc.
References SetValue(), and TIXML_SNPRINTF.
Referenced by dqm4hep::core::TiXmlElement::SetAttribute().
{
       char buf[64];
 #if defined(TIXML_SNPRINTF)
       TIXML_SNPRINTF(buf, sizeof(buf), "%d", _value);
 #else
       sprintf(buf, "%d", _value);
 #endif
       SetValue(buf);
     }
void dqm4hep::core::TiXmlAttribute::SetName (const char * _name) inline
Set the name of this attribute.
Definition at line 929 of file tinyxml.h.
References name.
Referenced by dqm4hep::core::TiXmlAttributeSet::FindOrCreate().
void dqm4hep::core::TiXmlAttribute::SetName (const std::string & _name) inline
STL std::string form.
Definition at line 941 of file tinyxml.h.
{
         name = _name;
       }
void dqm4hep::core::TiXmlAttribute::SetValue (const char * _value) inline
Set the value.
Definition at line 932 of file tinyxml.h.
References value.
Referenced by dqm4hep::core::TiXmlElement::SetAttribute(), SetDoubleValue(), and SetIntValue().
void dqm4hep::core::TiXmlAttribute::SetValue (const std::string & _value) inline
STL std::string form.
Definition at line 945 of file tinyxml.h.
References value.
{
         value = _value;
       }
const char* dqm4hep::core::TiXmlAttribute::Value () const inline
Return the value of this attribute.
Definition at line 900 of file tinyxml.h.
References value.
Referenced by dqm4hep::core::TiXmlElement::Attribute(), dqm4hep::core::TiXmlElement::CopyTo(), and dqm4hep::core::TiXmlDeclaration::Parse().
const std::string& dqm4hep::core::TiXmlAttribute::ValueStr () const inline
Return the value of this attribute.
Definition at line 904 of file tinyxml.h.
References value.
Referenced by dqm4hep::core::TiXmlElement::QueryValueAttribute().
Friends And Related Function Documentation
friend class TiXmlAttributeSet friend
Definition at line 870 of file tinyxml.h.
Member Data Documentation
TiXmlDocument* dqm4hep::core::TiXmlAttribute::document = {nullptr} private
Definition at line 993 of file tinyxml.h.
Referenced by SetDocument(), and TiXmlAttribute().
TIXML_STRING dqm4hep::core::TiXmlAttribute::name = {} private
Definition at line 994 of file tinyxml.h.
Referenced by Name(), NameTStr(), Next(), operator<(), operator==(), operator>(), Parse(), Previous(), SetName(), and TiXmlAttribute().
TiXmlAttribute* dqm4hep::core::TiXmlAttribute::next = {nullptr} private
Definition at line 997 of file tinyxml.h.
Referenced by dqm4hep::core::TiXmlAttributeSet::Add(), dqm4hep::core::TiXmlAttributeSet::Find(), dqm4hep::core::TiXmlAttributeSet::First(), Next(), dqm4hep::core::TiXmlAttributeSet::Remove(), TiXmlAttribute(), dqm4hep::core::TiXmlAttributeSet::TiXmlAttributeSet(), and dqm4hep::core::TiXmlAttributeSet::~TiXmlAttributeSet().
TiXmlAttribute* dqm4hep::core::TiXmlAttribute::prev = {nullptr} private
Definition at line 996 of file tinyxml.h.
Referenced by dqm4hep::core::TiXmlAttributeSet::Add(), dqm4hep::core::TiXmlAttributeSet::Last(), Previous(), dqm4hep::core::TiXmlAttributeSet::Remove(), TiXmlAttribute(), dqm4hep::core::TiXmlAttributeSet::TiXmlAttributeSet(), and dqm4hep::core::TiXmlAttributeSet::~TiXmlAttributeSet().
TIXML_STRING dqm4hep::core::TiXmlAttribute::value = {} private
Definition at line 995 of file tinyxml.h.
Referenced by DoubleValue(), IntValue(), Next(), Parse(), Previous(), Print(), QueryDoubleValue(), QueryIntValue(), SetValue(), TiXmlAttribute(), Value(), and ValueStr().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc