DQMCore: dqm4hep::core::Directory< T > Class Template Reference
dqm4hep::core::Directory< T > Class Template Reference
Directory class.
#include <Archiver.h>
Public Types
typedef std::shared_ptr< T > ObjectPtr
typedef std::vector< ObjectPtr > ObjectList
typedef std::shared_ptr
< Directory< T > > DirectoryPtr
typedef std::vector< DirectoryPtr > DirectoryList
Public Member Functions
~Directory ()
Destructor.
DirectoryPtr mkdir (const std::string &dirName)
Create a new directory.
const std::string & name () const
Returns the directory name.
DirectoryPtr parent () const
Returns the parent directory.
const DirectoryList & subdirs () const
Get the sub directory list.
bool hasChild (const std::string &dirName) const
Whether the directory contains the sub dir.
StatusCode find (const std::string &dirName, DirectoryPtr &directory) const
Find the sub directory by name.
StatusCode add (ObjectPtr object)
Add an object to the directory.
template<typename F >
ObjectPtr find (F function) const
Find a monitor element with a given name in the directory.
bool containsObject (const ObjectPtr &object) const
Whether the directory contains the monitor element (search by ptr compare)
template<typename F >
bool contains (F function) const
Whether the directory contains the monitor element (search by name compare)
StatusCode remove (ObjectPtr object)
Remove the monitor element from the directory.
template<typename F >
StatusCode remove (F function)
Remove the monitor element from the directory.
const ObjectList & contents () const
Get the monitor element list.
StatusCode rmdir (const std::string &dirName)
Remove the directory and its contents.
void clear ()
Clear the directory.
Path fullPath () const
Get the full path name of the directory.
bool isRoot () const
Whether the directory is a root directory.
bool isEmpty () const
Whether the directory is empty.
template<typename F >
Directory< T >::ObjectPtr find (F function) const
Static Public Member Functions
static DirectoryPtr make_shared ()
Factory method for simple constructor.
static DirectoryPtr make_shared (const std::string &name, DirectoryPtr parent=nullptr)
Factory method for constructor with name and parent directory.
Private Member Functions
Directory ()
Default constructor.
Directory (const std::string &name, DirectoryPtr parentDir=nullptr)
Constructor with name and parent dir.
Private Attributes
std::string m_name
DirectoryPtr m_parent
DirectoryList m_subdirs
ObjectList m_contents
Detailed Description
template<typename T>
class dqm4hep::core::Directory< T >
Directory class.
A directory is the owner of its sub-directories. Unit owning depends on how the method are called (default : not owner)
This interface doesn't allow moving sub-directories
Definition at line 44 of file Archiver.h.
Member Typedef Documentation
template<typename T> typedef std::vector<DirectoryPtr> dqm4hep::core::Directory< T >::DirectoryList
Definition at line 56 of file Directory.h.
template<typename T> typedef std::shared_ptr<Directory<T> > dqm4hep::core::Directory< T >::DirectoryPtr
Definition at line 55 of file Directory.h.
template<typename T> typedef std::vector<ObjectPtr> dqm4hep::core::Directory< T >::ObjectList
Definition at line 54 of file Directory.h.
template<typename T> typedef std::shared_ptr<T> dqm4hep::core::Directory< T >::ObjectPtr
Definition at line 53 of file Directory.h.
Constructor & Destructor Documentation
template<typename T > dqm4hep::core::Directory< T >::~Directory () inline
Destructor.
Delete the subdirectories but not the contents
Definition at line 207 of file Directory.h.
     {
       this->clear();
     }
template<typename T > dqm4hep::core::Directory< T >::Directory () inline private
Default constructor.
Definition at line 183 of file Directory.h.
                                    :
       m_name(""),
       m_parent(nullptr),
       m_subdirs(),
       m_contents()
     {
       /* nop */
     }
template<typename T > dqm4hep::core::Directory< T >::Directory (const std::string & name, DirectoryPtr parentDir = nullptr) inline private
Constructor with name and parent dir.
Definition at line 195 of file Directory.h.
                                                                              :
       m_name(name),
       m_parent(parent),
       m_subdirs(),
       m_contents()
     {
       /* nop */
     }
Member Function Documentation
template<typename T > StatusCode dqm4hep::core::Directory< T >::add (ObjectPtr object) inline
Add an object to the directory.
Definition at line 300 of file Directory.h.
     {
       if(nullptr == object)
         return STATUS_CODE_INVALID_PTR;
       if(this->containsObject(object))
         return STATUS_CODE_ALREADY_PRESENT;
       m_contents.push_back(object);
       return STATUS_CODE_SUCCESS;
     }
template<typename T > void dqm4hep::core::Directory< T >::clear () inline
Clear the directory.
The operation is done recursively
Definition at line 422 of file Directory.h.
     {
       for(auto iter = m_subdirs.begin(), endIter = m_subdirs.end() ; endIter != iter ; ++iter)
         (*iter)->clear();
       m_subdirs.clear();
       m_contents.clear();
     }
template<typename T > template<typename F > bool dqm4hep::core::Directory< T >::contains (F function) const inline
Whether the directory contains the monitor element (search by name compare)
Definition at line 345 of file Directory.h.
     {
       for(auto iter = m_contents.begin(), endIter = m_contents.end() ; endIter != iter ; ++iter)
         if(function(*iter))
           return true;
       return false;
     }
template<typename T > bool dqm4hep::core::Directory< T >::containsObject (const ObjectPtr & object) const inline
Whether the directory contains the monitor element (search by ptr compare)
Definition at line 329 of file Directory.h.
     {
       if(nullptr == object)
         return false;
       for(auto iter = m_contents.begin(), endIter = m_contents.end() ; endIter != iter ; ++iter)
         if(object == *iter)
           return true;
       return false;
     }
template<typename T > const Directory< T >::ObjectList & dqm4hep::core::Directory< T >::contents () const inline
Get the monitor element list.
Definition at line 395 of file Directory.h.
     {
       return m_contents;
     }
template<typename T > StatusCode dqm4hep::core::Directory< T >::find (const std::string & dirName, DirectoryPtr & directory) const inline
Find the sub directory by name.
Definition at line 279 of file Directory.h.
     {
       directory = nullptr;
       for(auto iter = m_subdirs.begin(), endIter = m_subdirs.end() ; endIter != iter ; ++iter)
       {
         auto dir = *iter;
         if(dir->name() == dirName)
         {
           directory = dir;
           return STATUS_CODE_SUCCESS;
         }
       }
       return STATUS_CODE_NOT_FOUND;
     }
template<typename T> template<typename F > ObjectPtr dqm4hep::core::Directory< T >::find (F function) const
Find a monitor element with a given name in the directory.
template<typename T> template<typename F > Directory<T>::ObjectPtr dqm4hep::core::Directory< T >::find (F function) const inline
Definition at line 317 of file Directory.h.
     {
       for(auto iter = m_contents.begin(), endIter = m_contents.end() ; endIter != iter ; ++iter)
         if(function(*iter))
           return *iter;
       return ObjectPtr();
     }
template<typename T > Path dqm4hep::core::Directory< T >::fullPath () const inline
Get the full path name of the directory.
Definition at line 434 of file Directory.h.
     {
       Path fullPath = this->name();
       DirectoryPtr dir = const_cast<Directory<T>*>(this)->shared_from_this();
       while(1)
       {
         DirectoryPtr parentDir = dir->parent();
         if(nullptr != parentDir)
         {
           fullPath = parentDir->name() + fullPath;
           dir = parentDir;
         }
         else
         {
           fullPath = Path("/") + fullPath;
           break;
         }
       }
       return fullPath;
     }
template<typename T > bool dqm4hep::core::Directory< T >::hasChild (const std::string & dirName) const inline
Whether the directory contains the sub dir.
Definition at line 260 of file Directory.h.
References dqm4hep::core::containsSpecialCharacters().
     {
       if(dirName.find("/") != std::string::npos || dqm4hep::core::containsSpecialCharacters(dirName) || dirName.empty())
         return false;
       for(auto iter = m_subdirs.begin(), endIter = m_subdirs.end() ; endIter != iter ; ++iter)
       {
         auto directory = *iter;
         if(directory->name() == dirName)
           return true;
       }
       return false;
     }
template<typename T > bool dqm4hep::core::Directory< T >::isEmpty () const inline
Whether the directory is empty.
Definition at line 469 of file Directory.h.
     {
       return (m_subdirs.empty() && m_contents.empty());
     }
template<typename T > bool dqm4hep::core::Directory< T >::isRoot () const inline
Whether the directory is a root directory.
Definition at line 461 of file Directory.h.
     {
       return (nullptr == m_parent);
     }
template<typename T > Directory< T >::DirectoryPtr dqm4hep::core::Directory< T >::make_shared () inline static
Factory method for simple constructor.
Definition at line 167 of file Directory.h.
Referenced by dqm4hep::core::Directory< T >::mkdir().
     {
       return std::shared_ptr<Directory<T>>(new Directory<T>());
     }
template<typename T > Directory< T >::DirectoryPtr dqm4hep::core::Directory< T >::make_shared (const std::string & name, DirectoryPtr parent = nullptr) inline static
Factory method for constructor with name and parent directory.
Definition at line 175 of file Directory.h.
     {
       return std::shared_ptr<Directory<T>>(new Directory<T>(name, parent));
     }
template<typename T > Directory< T >::DirectoryPtr dqm4hep::core::Directory< T >::mkdir (const std::string & dirName) inline
Create a new directory.
Definition at line 239 of file Directory.h.
References dqm4hep::core::containsSpecialCharacters(), and dqm4hep::core::Directory< T >::make_shared().
     {
       DirectoryPtr directory;
       this->find(dirName, directory);
       if(nullptr != directory)
         return directory;
       if(dirName.find("/") != std::string::npos || dqm4hep::core::containsSpecialCharacters(dirName) || dirName.empty())
         return nullptr;
       auto newDirectory = Directory<T>::make_shared(dirName, this->shared_from_this());
       m_subdirs.push_back(newDirectory);
       return newDirectory;
     }
template<typename T > const std::string & dqm4hep::core::Directory< T >::name () const inline
Returns the directory name.
Definition at line 215 of file Directory.h.
     {
       return m_name;
     }
template<typename T > Directory< T >::DirectoryPtr dqm4hep::core::Directory< T >::parent () const inline
Returns the parent directory.
Definition at line 223 of file Directory.h.
     {
       return m_parent;
     }
template<typename T > StatusCode dqm4hep::core::Directory< T >::remove (ObjectPtr object) inline
Remove the monitor element from the directory.
Definition at line 357 of file Directory.h.
     {
       if(nullptr == object)
         return STATUS_CODE_INVALID_PTR;
       for(auto iter = m_contents.begin(), endIter = m_contents.end() ; endIter != iter ; ++iter)
       {
         if(object == *iter)
         {
           m_contents.erase(iter);
           return STATUS_CODE_SUCCESS;
         }
       }
       return STATUS_CODE_NOT_FOUND;
     }
template<typename T > template<typename F > StatusCode dqm4hep::core::Directory< T >::remove (F function) inline
Remove the monitor element from the directory.
Definition at line 378 of file Directory.h.
     {
       for(auto iter = m_contents.begin(), endIter = m_contents.end() ; endIter != iter ; ++iter)
       {
         if(function(*iter))
         {
           m_contents.erase(iter);
           return STATUS_CODE_SUCCESS;
         }
       }
       return STATUS_CODE_NOT_FOUND;
     }
template<typename T > StatusCode dqm4hep::core::Directory< T >::rmdir (const std::string & dirName) inline
Remove the directory and its contents.
Definition at line 403 of file Directory.h.
     {
       for(auto iter = m_subdirs.begin(), endIter = m_subdirs.end() ; endIter != iter ; ++iter)
       {
         DirectoryPtr dir = *iter;
         if(dir->name() == dirName)
         {
           m_subdirs.erase(iter);
           return STATUS_CODE_SUCCESS;
         }
       }
       return STATUS_CODE_NOT_FOUND;
     }
template<typename T > const Directory< T >::DirectoryList & dqm4hep::core::Directory< T >::subdirs () const inline
Get the sub directory list.
Definition at line 231 of file Directory.h.
     {
       return m_subdirs;
     }
Member Data Documentation
template<typename T> ObjectList dqm4hep::core::Directory< T >::m_contents private
Definition at line 160 of file Directory.h.
template<typename T> std::string dqm4hep::core::Directory< T >::m_name private
Definition at line 157 of file Directory.h.
template<typename T> DirectoryPtr dqm4hep::core::Directory< T >::m_parent private
Definition at line 158 of file Directory.h.
template<typename T> DirectoryList dqm4hep::core::Directory< T >::m_subdirs private
Definition at line 159 of file Directory.h.
The documentation for this class was generated from the following files:
Archiver.h
Directory.h