DQMCore: nlohmann::detail::parser< BasicJsonType > Class Template Reference
nlohmann::detail::parser< BasicJsonType > Class Template Reference
syntax analysis
#include <json.h>
Public Types
enum parse_event_t : uint8_t {
parse_event_t::object_start, parse_event_t::object_end, parse_event_t::array_start, parse_event_t::array_end,
parse_event_t::key, parse_event_t::value
}
using parser_callback_t = std::function< bool(int depth, parse_event_t event, BasicJsonType &parsed)>
Public Member Functions
parser (detail::input_adapter_t adapter, const parser_callback_t cb=nullptr, const bool allow_exceptions_=true)
a parser reading from an input adapter
void parse (const bool strict, BasicJsonType &result)
public parser interface
bool accept (const bool strict=true)
public accept interface
Private Types
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using lexer_t = lexer< BasicJsonType >
using token_type = typename lexer_t::token_type
Private Member Functions
void parse_internal (bool keep, BasicJsonType &result)
the actual parser
bool accept_internal ()
the actual acceptor
token_type get_token ()
get next token from lexer
bool expect (token_type t)
void throw_exception () const
Private Attributes
int depth = 0
current level of recursion
const parser_callback_t callback = nullptr
callback function
token_type last_token = token_type::uninitialized
the type of the last read token
lexer_t m_lexer
the lexer
bool errored = false
whether a syntax error occurred
token_type expected = token_type::uninitialized
possible reason for the syntax error
const bool allow_exceptions = true
whether to throw exceptions in case of errors
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::parser< BasicJsonType >
syntax analysis
This class implements a recursive decent parser.
Definition at line 2886 of file json.h.
Member Typedef Documentation
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::lexer_t = lexer<BasicJsonType> private
Definition at line 2890 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t private
Definition at line 2889 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t private
Definition at line 2887 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t private
Definition at line 2888 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::parser_callback_t = std::function<bool(int depth, parse_event_t event, BasicJsonType &parsed)>
Definition at line 2909 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::token_type = typename lexer_t::token_type private
Definition at line 2891 of file json.h.
Member Enumeration Documentation
template<typename BasicJsonType > enum nlohmann::detail::parser::parse_event_t : uint8_t strong
Enumerator
object_start
the parser read { and started to process a JSON object
object_end
the parser read } and finished processing a JSON object
array_start
the parser read [ and started to process a JSON array
array_end
the parser read ] and finished processing a JSON array
key
the parser read a key of a value in an object
value
the parser finished reading a JSON value
Definition at line 2894 of file json.h.
                                : uint8_t {
         object_start,
         object_end,
         array_start,
         array_end,
         key,
         value
       };
Constructor & Destructor Documentation
template<typename BasicJsonType > nlohmann::detail::parser< BasicJsonType >::parser (detail::input_adapter_t adapter, const parser_callback_t cb = nullptr, const bool allow_exceptions_ = true) inline explicit
a parser reading from an input adapter
Definition at line 2912 of file json.h.
           : callback(cb), m_lexer(adapter), allow_exceptions(allow_exceptions_) {
       }
Member Function Documentation
template<typename BasicJsonType > bool nlohmann::detail::parser< BasicJsonType >::accept (const bool strict = true) inline
public accept interface
Parameters
[in] strict whether to expect the last token to be EOF
Returns
whether the input is a proper JSON text
Definition at line 2959 of file json.h.
References nlohmann::detail::parser< BasicJsonType >::accept_internal(), and nlohmann::detail::parser< BasicJsonType >::get_token().
{
         // read first token
         get_token();
         if (not accept_internal()) {
           return false;
         }
         // strict => last token must be EOF
         return not strict or (get_token() == token_type::end_of_input);
       }
template<typename BasicJsonType > bool nlohmann::detail::parser< BasicJsonType >::accept_internal () inline private
the actual acceptor
Invariant
1. The last token is not yet processed. Therefore, the caller of this function must make sure a token has been read.
When this function returns, the last token is processed. That is, the last read character was already considered.
This invariant makes sure that no token needs to be "unput".
Definition at line 3218 of file json.h.
References nlohmann::detail::lexer< BasicJsonType >::get_number_float(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::parser< BasicJsonType >::last_token, and nlohmann::detail::parser< BasicJsonType >::m_lexer.
Referenced by nlohmann::detail::parser< BasicJsonType >::accept().
{
         switch (last_token) {
         case token_type::begin_object: {
           // read next token
           get_token();
           // closing } -> we are done
           if (last_token == token_type::end_object) {
             return true;
           }
           // parse values
           while (true) {
             // parse key
             if (last_token != token_type::value_string) {
               return false;
             }
             // parse separator (:)
             get_token();
             if (last_token != token_type::name_separator) {
               return false;
             }
             // parse value
             get_token();
             if (not accept_internal()) {
               return false;
             }
             // comma -> next value
             get_token();
             if (last_token == token_type::value_separator) {
               get_token();
               continue;
             }
             // closing }
             return (last_token == token_type::end_object);
           }
         }
         case token_type::begin_array: {
           // read next token
           get_token();
           // closing ] -> we are done
           if (last_token == token_type::end_array) {
             return true;
           }
           // parse values
           while (true) {
             // parse value
             if (not accept_internal()) {
               return false;
             }
             // comma -> next value
             get_token();
             if (last_token == token_type::value_separator) {
               get_token();
               continue;
             }
             // closing ]
             return (last_token == token_type::end_array);
           }
         }
         case token_type::value_float: {
           // reject infinity or NAN
           return std::isfinite(m_lexer.get_number_float());
         }
         case token_type::literal_false:
         case token_type::literal_null:
         case token_type::literal_true:
         case token_type::value_integer:
         case token_type::value_string:
         case token_type::value_unsigned:
           return true;
         default: // the last token was unexpected
           return false;
         }
       }
template<typename BasicJsonType > bool nlohmann::detail::parser< BasicJsonType >::expect (token_type t) inline private
Exceptions
parse_error.101 if expected token did not occur
Definition at line 3314 of file json.h.
References nlohmann::detail::parser< BasicJsonType >::allow_exceptions, nlohmann::detail::parser< BasicJsonType >::errored, nlohmann::detail::parser< BasicJsonType >::expected, JSON_UNLIKELY, nlohmann::detail::parser< BasicJsonType >::last_token, and nlohmann::detail::parser< BasicJsonType >::throw_exception().
Referenced by nlohmann::detail::parser< BasicJsonType >::parse(), and nlohmann::detail::parser< BasicJsonType >::parse_internal().
{
         if (JSON_UNLIKELY(t != last_token)) {
           errored = true;
           expected = t;
           if (allow_exceptions) {
             throw_exception();
           } else {
             return false;
           }
         }
         return true;
       }
template<typename BasicJsonType > token_type nlohmann::detail::parser< BasicJsonType >::get_token () inline private
get next token from lexer
Definition at line 3307 of file json.h.
References nlohmann::detail::parser< BasicJsonType >::last_token, nlohmann::detail::parser< BasicJsonType >::m_lexer, and nlohmann::detail::lexer< BasicJsonType >::scan().
Referenced by nlohmann::detail::parser< BasicJsonType >::accept(), nlohmann::detail::parser< BasicJsonType >::accept_internal(), nlohmann::detail::parser< BasicJsonType >::parse(), and nlohmann::detail::parser< BasicJsonType >::parse_internal().
{
         return (last_token = m_lexer.scan());
       }
template<typename BasicJsonType > void nlohmann::detail::parser< BasicJsonType >::parse (const bool strict, BasicJsonType & result) inline
public parser interface
Parameters
[in] strict whether to expect the last token to be EOF
[in,out] result parsed JSON value
Exceptions
parse_error.101 in case of an unexpected token
parse_error.102 if to_unicode fails or surrogate error
parse_error.103 if to_unicode fails
Definition at line 2927 of file json.h.
References nlohmann::detail::discarded, nlohmann::detail::parser< BasicJsonType >::errored, nlohmann::detail::parser< BasicJsonType >::expect(), nlohmann::detail::parser< BasicJsonType >::get_token(), and nlohmann::detail::parser< BasicJsonType >::parse_internal().
{
         // read first token
         get_token();
         parse_internal(true, result);
         result.assert_invariant();
         // in strict mode, input must be completely read
         if (strict) {
           get_token();
           expect(token_type::end_of_input);
         }
         // in case of an error, return discarded value
         if (errored) {
           result = value_t::discarded;
           return;
         }
         // set top-level value to null if it was discarded by the callback
         // function
         if (result.is_discarded()) {
           result = nullptr;
         }
       }
template<typename BasicJsonType > void nlohmann::detail::parser< BasicJsonType >::parse_internal (bool keep, BasicJsonType & result) inline private
the actual parser
Exceptions
parse_error.101 in case of an unexpected token
parse_error.102 if to_unicode fails or surrogate error
parse_error.103 if to_unicode fails
Definition at line 2978 of file json.h.
References nlohmann::detail::parser< BasicJsonType >::allow_exceptions, nlohmann::detail::array, nlohmann::detail::parser< BasicJsonType >::array_end, nlohmann::detail::parser< BasicJsonType >::array_start, nlohmann::detail::boolean, nlohmann::detail::parser< BasicJsonType >::callback, nlohmann::detail::out_of_range::create(), nlohmann::detail::parser< BasicJsonType >::depth, nlohmann::detail::discarded, nlohmann::detail::parser< BasicJsonType >::errored, nlohmann::detail::parser< BasicJsonType >::expect(), nlohmann::detail::lexer< BasicJsonType >::get_number_float(), nlohmann::detail::lexer< BasicJsonType >::get_number_integer(), nlohmann::detail::lexer< BasicJsonType >::get_number_unsigned(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), JSON_THROW, JSON_UNLIKELY, nlohmann::detail::parser< BasicJsonType >::key, nlohmann::detail::parser< BasicJsonType >::last_token, nlohmann::detail::parser< BasicJsonType >::m_lexer, nlohmann::detail::lexer< BasicJsonType >::move_string(), nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, nlohmann::detail::parser< BasicJsonType >::object_end, nlohmann::detail::parser< BasicJsonType >::object_start, nlohmann::detail::string, and nlohmann::detail::parser< BasicJsonType >::value.
Referenced by nlohmann::detail::parser< BasicJsonType >::parse().
{
         // never parse after a parse error was detected
         assert(not errored);
         // start with a discarded value
         if (not result.is_discarded()) {
           result.m_value.destroy(result.m_type);
           result.m_type = value_t::discarded;
         }
         switch (last_token) {
         case token_type::begin_object: {
           if (keep) {
             if (callback) {
               keep = callback(depth++, parse_event_t::object_start, result);
             }
             if (not callback or keep) {
               // explicitly set result to object to cope with {}
               result.m_type = value_t::object;
               result.m_value = value_t::object;
             }
           }
           // read next token
           get_token();
           // closing } -> we are done
           if (last_token == token_type::end_object) {
             if (keep and callback and not callback(--depth, parse_event_t::object_end, result)) {
               result.m_value.destroy(result.m_type);
               result.m_type = value_t::discarded;
             }
             break;
           }
           // parse values
           std::string key;
           BasicJsonType value;
           while (true) {
             // store key
             if (not expect(token_type::value_string)) {
               return;
             }
             key = m_lexer.move_string();
             bool keep_tag = false;
             if (keep) {
               if (callback) {
                 BasicJsonType k(key);
                 keep_tag = callback(depth, parse_event_t::key, k);
               } else {
                 keep_tag = true;
               }
             }
             // parse separator (:)
             get_token();
             if (not expect(token_type::name_separator)) {
               return;
             }
             // parse and add value
             get_token();
             value.m_value.destroy(value.m_type);
             value.m_type = value_t::discarded;
             parse_internal(keep, value);
             if (JSON_UNLIKELY(errored)) {
               return;
             }
             if (keep and keep_tag and not value.is_discarded()) {
               result.m_value.object->emplace(std::move(key), std::move(value));
             }
             // comma -> next value
             get_token();
             if (last_token == token_type::value_separator) {
               get_token();
               continue;
             }
             // closing }
             if (not expect(token_type::end_object)) {
               return;
             }
             break;
           }
           if (keep and callback and not callback(--depth, parse_event_t::object_end, result)) {
             result.m_value.destroy(result.m_type);
             result.m_type = value_t::discarded;
           }
           break;
         }
         case token_type::begin_array: {
           if (keep) {
             if (callback) {
               keep = callback(depth++, parse_event_t::array_start, result);
             }
             if (not callback or keep) {
               // explicitly set result to array to cope with []
               result.m_type = value_t::array;
               result.m_value = value_t::array;
             }
           }
           // read next token
           get_token();
           // closing ] -> we are done
           if (last_token == token_type::end_array) {
             if (callback and not callback(--depth, parse_event_t::array_end, result)) {
               result.m_value.destroy(result.m_type);
               result.m_type = value_t::discarded;
             }
             break;
           }
           // parse values
           BasicJsonType value;
           while (true) {
             // parse value
             value.m_value.destroy(value.m_type);
             value.m_type = value_t::discarded;
             parse_internal(keep, value);
             if (JSON_UNLIKELY(errored)) {
               return;
             }
             if (keep and not value.is_discarded()) {
               result.m_value.array->push_back(std::move(value));
             }
             // comma -> next value
             get_token();
             if (last_token == token_type::value_separator) {
               get_token();
               continue;
             }
             // closing ]
             if (not expect(token_type::end_array)) {
               return;
             }
             break;
           }
           if (keep and callback and not callback(--depth, parse_event_t::array_end, result)) {
             result.m_value.destroy(result.m_type);
             result.m_type = value_t::discarded;
           }
           break;
         }
         case token_type::literal_null: {
           result.m_type = value_t::null;
           break;
         }
         case token_type::value_string: {
           result.m_type = value_t::string;
           result.m_value = m_lexer.move_string();
           break;
         }
         case token_type::literal_true: {
           result.m_type = value_t::boolean;
           result.m_value = true;
           break;
         }
         case token_type::literal_false: {
           result.m_type = value_t::boolean;
           result.m_value = false;
           break;
         }
         case token_type::value_unsigned: {
           result.m_type = value_t::number_unsigned;
           result.m_value = m_lexer.get_number_unsigned();
           break;
         }
         case token_type::value_integer: {
           result.m_type = value_t::number_integer;
           result.m_value = m_lexer.get_number_integer();
           break;
         }
         case token_type::value_float: {
           result.m_type = value_t::number_float;
           result.m_value = m_lexer.get_number_float();
           // throw in case of infinity or NAN
           if (JSON_UNLIKELY(not std::isfinite(result.m_value.number_float))) {
             if (allow_exceptions) {
               JSON_THROW(out_of_range::create(406, "number overflow parsing '" + m_lexer.get_token_string() + "'"));
             }
             expect(token_type::uninitialized);
           }
           break;
         }
         case token_type::parse_error: {
           // using "uninitialized" to avoid "expected" message
           if (not expect(token_type::uninitialized)) {
             return;
           }
           break; // LCOV_EXCL_LINE
         }
         default: {
           // the last token was unexpected; we expected a value
           if (not expect(token_type::literal_or_value)) {
             return;
           }
           break; // LCOV_EXCL_LINE
         }
         }
         if (keep and callback and not callback(depth, parse_event_t::value, result)) {
           result.m_type = value_t::discarded;
         }
       }
template<typename BasicJsonType > void nlohmann::detail::parser< BasicJsonType >::throw_exception () const inline private
Definition at line 3328 of file json.h.
References nlohmann::detail::parse_error::create(), nlohmann::detail::parser< BasicJsonType >::expected, nlohmann::detail::lexer< BasicJsonType >::get_error_message(), nlohmann::detail::lexer< BasicJsonType >::get_position(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), JSON_THROW, nlohmann::detail::parser< BasicJsonType >::last_token, nlohmann::detail::parser< BasicJsonType >::m_lexer, nlohmann::detail::string, and nlohmann::detail::lexer< BasicJsonType >::token_type_name().
Referenced by nlohmann::detail::parser< BasicJsonType >::expect().
{
         std::string error_msg = "syntax error - ";
         if (last_token == token_type::parse_error) {
           error_msg += std::string(m_lexer.get_error_message()) + "; last read: '" + m_lexer.get_token_string() + "'";
         } else {
           error_msg += "unexpected " + std::string(lexer_t::token_type_name(last_token));
         }
         if (expected != token_type::uninitialized) {
           error_msg += "; expected " + std::string(lexer_t::token_type_name(expected));
         }
         JSON_THROW(parse_error::create(101, m_lexer.get_position(), error_msg));
       }
Member Data Documentation
template<typename BasicJsonType > const bool nlohmann::detail::parser< BasicJsonType >::allow_exceptions = true private
whether to throw exceptions in case of errors
Definition at line 3357 of file json.h.
Referenced by nlohmann::detail::parser< BasicJsonType >::expect(), and nlohmann::detail::parser< BasicJsonType >::parse_internal().
template<typename BasicJsonType > const parser_callback_t nlohmann::detail::parser< BasicJsonType >::callback = nullptr private
callback function
Definition at line 3347 of file json.h.
Referenced by nlohmann::detail::parser< BasicJsonType >::parse_internal().
template<typename BasicJsonType > int nlohmann::detail::parser< BasicJsonType >::depth = 0 private
current level of recursion
Definition at line 3345 of file json.h.
Referenced by nlohmann::detail::parser< BasicJsonType >::parse_internal().
template<typename BasicJsonType > bool nlohmann::detail::parser< BasicJsonType >::errored = false private
whether a syntax error occurred
Definition at line 3353 of file json.h.
Referenced by nlohmann::detail::parser< BasicJsonType >::expect(), nlohmann::detail::parser< BasicJsonType >::parse(), and nlohmann::detail::parser< BasicJsonType >::parse_internal().
template<typename BasicJsonType > token_type nlohmann::detail::parser< BasicJsonType >::expected = token_type::uninitialized private
possible reason for the syntax error
Definition at line 3355 of file json.h.
Referenced by nlohmann::detail::parser< BasicJsonType >::expect(), and nlohmann::detail::parser< BasicJsonType >::throw_exception().
template<typename BasicJsonType > token_type nlohmann::detail::parser< BasicJsonType >::last_token = token_type::uninitialized private
the type of the last read token
Definition at line 3349 of file json.h.
Referenced by nlohmann::detail::parser< BasicJsonType >::accept_internal(), nlohmann::detail::parser< BasicJsonType >::expect(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::parser< BasicJsonType >::parse_internal(), and nlohmann::detail::parser< BasicJsonType >::throw_exception().
template<typename BasicJsonType > lexer_t nlohmann::detail::parser< BasicJsonType >::m_lexer private
the lexer
Definition at line 3351 of file json.h.
Referenced by nlohmann::detail::parser< BasicJsonType >::accept_internal(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::parser< BasicJsonType >::parse_internal(), and nlohmann::detail::parser< BasicJsonType >::throw_exception().
The documentation for this class was generated from the following file:
json.h