DQMCore: dqm4hep::core::Storage< T > Class Template Reference
dqm4hep::core::Storage< T > Class Template Reference
#include <Archiver.h>
Public Types
typedef Directory< T >
::DirectoryPtr DirectoryPtr
typedef Directory< T >::ObjectPtr ObjectPtr
typedef Directory< T >::ObjectList ObjectList
typedef Directory< T >
::DirectoryList DirectoryList
Public Member Functions
Storage ()
~Storage ()
StatusCode mkdir (const std::string &dirName)
void cd ()
StatusCode cd (const std::string &dirName)
bool dirExists (const std::string &dirName) const
const std::string & pwd () const
StatusCode goUp ()
StatusCode rmdir (const std::string &dirName)
StatusCode find (const std::string &dirName, DirectoryPtr &directory) const
DirectoryPtr root () const
DirectoryPtr current () const
StatusCode add (ObjectPtr object)
StatusCode add (const std::string &dirName, ObjectPtr object)
StatusCode add (ObjectPtr object, std::string &fullPath)
StatusCode add (const std::string &dirName, ObjectPtr object, std::string &fullPath)
template<typename F >
StatusCode remove (F function)
template<typename F >
StatusCode remove (const std::string &dirName, F function)
template<typename F >
ObjectPtr findObject (F function) const
template<typename F >
ObjectPtr findObject (const std::string &dirName, F function) const
bool containsObject (const ObjectPtr &object) const
bool containsObject (const std::string &dirName, const ObjectPtr &object) const
template<typename F >
void iterate (F function) const
template<typename U >
void getObjects (std::vector< std::shared_ptr< U >> &objectList) const
void clear ()
template<typename F >
void dump (F function) const
template<typename F >
Storage< T >::ObjectPtr findObject (F function) const
template<typename F >
Storage< T >::ObjectPtr findObject (const std::string &dirName, F function) const
Private Member Functions
template<typename F >
bool iterate (const DirectoryPtr &directory, F function) const
template<typename F >
void dump (const DirectoryPtr &directory, F function) const
Private Attributes
DirectoryPtr m_rootDirectory
DirectoryPtr m_currentDirectory
Detailed Description
template<typename T>
class dqm4hep::core::Storage< T >
Definition at line 45 of file Archiver.h.
Member Typedef Documentation
template<typename T> typedef Directory<T>::DirectoryList dqm4hep::core::Storage< T >::DirectoryList
Definition at line 46 of file Storage.h.
template<typename T> typedef Directory<T>::DirectoryPtr dqm4hep::core::Storage< T >::DirectoryPtr
Definition at line 43 of file Storage.h.
template<typename T> typedef Directory<T>::ObjectList dqm4hep::core::Storage< T >::ObjectList
Definition at line 45 of file Storage.h.
template<typename T> typedef Directory<T>::ObjectPtr dqm4hep::core::Storage< T >::ObjectPtr
Definition at line 44 of file Storage.h.
Constructor & Destructor Documentation
template<typename T > dqm4hep::core::Storage< T >::Storage () inline
Definition at line 98 of file Storage.h.
                                : m_rootDirectory(Directory<T>::make_shared("")), m_currentDirectory(m_rootDirectory) {
     }
template<typename T > dqm4hep::core::Storage< T >::~Storage () inline default
Member Function Documentation
template<typename T > StatusCode dqm4hep::core::Storage< T >::add (ObjectPtr object) inline
Definition at line 312 of file Storage.h.
{
       return m_currentDirectory->add(object);
     }
template<typename T > StatusCode dqm4hep::core::Storage< T >::add (const std::string & dirName, ObjectPtr object) inline
Definition at line 319 of file Storage.h.
References RETURN_RESULT_IF.
{
       DirectoryPtr directory = nullptr;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->mkdir(dirName));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->find(dirName, directory));
       return directory->add(object);
     }
template<typename T > StatusCode dqm4hep::core::Storage< T >::add (ObjectPtr object, std::string & fullPath) inline
Definition at line 329 of file Storage.h.
References RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_currentDirectory->add(object));
       fullPath = m_currentDirectory->fullPath().getPath();
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::Storage< T >::add (const std::string & dirName, ObjectPtr object, std::string & fullPath) inline
Definition at line 338 of file Storage.h.
References RETURN_RESULT_IF.
{
       DirectoryPtr directory = nullptr;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->mkdir(dirName));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->find(dirName, directory));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, directory->add(object));
       fullPath = directory->fullPath().getPath();
       return STATUS_CODE_SUCCESS;
     }
template<typename T > void dqm4hep::core::Storage< T >::cd () inline
Definition at line 149 of file Storage.h.
{
       m_currentDirectory = m_rootDirectory;
     }
template<typename T > StatusCode dqm4hep::core::Storage< T >::cd (const std::string & dirName) inline
Definition at line 156 of file Storage.h.
References dqm4hep::core::Path::getSplitPath(), dqm4hep::core::Path::isRelative(), dqm4hep::core::Path::isValid(), and RETURN_RESULT_IF.
{
       // go back to sub dir
       if (dirName.empty()) {
         this->cd();
         return STATUS_CODE_SUCCESS;
       }
       Path path(dirName);
       if (!path.isValid())
         return STATUS_CODE_INVALID_PARAMETER;
       DirectoryPtr directory = !path.isRelative() ? m_rootDirectory : m_currentDirectory;
       StringVector directoryList = path.getSplitPath();
       for (auto iter = directoryList.begin(), endIter = directoryList.end(); endIter != iter; ++iter) {
         std::string dname = *iter;
         if (dname == ".")
           continue;
         if (dname == "..") {
           if (directory == m_rootDirectory)
             return STATUS_CODE_FAILURE;
           directory = directory->parent();
           continue;
         }
         // navigate forward
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, directory->find(dname, directory));
       }
       if (nullptr == directory)
         return STATUS_CODE_FAILURE;
       m_currentDirectory = directory;
       return STATUS_CODE_SUCCESS;
     }
template<typename T > void dqm4hep::core::Storage< T >::clear () inline
Definition at line 447 of file Storage.h.
{
       m_rootDirectory->clear();
       m_currentDirectory = m_rootDirectory;
     }
template<typename T > bool dqm4hep::core::Storage< T >::containsObject (const ObjectPtr & object) const inline
Definition at line 389 of file Storage.h.
{
       return m_currentDirectory->containsObject(object);
     }
template<typename T > bool dqm4hep::core::Storage< T >::containsObject (const std::string & dirName, const ObjectPtr & object) const inline
Definition at line 396 of file Storage.h.
{
       DirectoryPtr directory = NULL;
       if (this->find(dirName, directory))
         return false;
       return directory->containsObject(object);
     }
template<typename T > Storage< T >::DirectoryPtr dqm4hep::core::Storage< T >::current () const inline
Definition at line 305 of file Storage.h.
{
       return m_currentDirectory;
     }
template<typename T > bool dqm4hep::core::Storage< T >::dirExists (const std::string & dirName) const inline
Definition at line 200 of file Storage.h.
{
       DirectoryPtr directory = nullptr;
       return (this->find(dirName, directory) == STATUS_CODE_SUCCESS);
     }
template<typename T > template<typename F > void dqm4hep::core::Storage< T >::dump (F function) const inline
Definition at line 456 of file Storage.h.
{
       dump(m_rootDirectory, function);
     }
template<typename T > template<typename F > void dqm4hep::core::Storage< T >::dump (const DirectoryPtr & directory, F function) const inline private
Definition at line 464 of file Storage.h.
References dqm_info.
{
       int nParents = directory->nParents();
       dqm_info( "{0}+ {1}", std::string(nParents*2, ' '), directory->isRoot() ? "/" : directory->name()+"/" );
       for(auto obj : directory->contents()) {
         std::string objectStr = function(obj);
         dqm_info( "{0}|- {1}", std::string(nParents*2, ' '), objectStr );
       }
       for(auto dir : directory->subdirs()) {
         dump(dir, function);
       }
     }
template<typename T > StatusCode dqm4hep::core::Storage< T >::find (const std::string & dirName, DirectoryPtr & directory) const inline
Definition at line 254 of file Storage.h.
References dqm4hep::core::Path::getSplitPath(), dqm4hep::core::Path::isRelative(), and dqm4hep::core::Path::isValid().
{
       directory = nullptr;
       // go back to sub dir
       if (dirName.empty() || dirName == "." || dirName == "./") {
         directory = m_currentDirectory;
         return STATUS_CODE_SUCCESS;
       }
       Path path(dirName);
       if (!path.isValid())
         return STATUS_CODE_INVALID_PARAMETER;
       directory = !path.isRelative() ? m_rootDirectory : m_currentDirectory;
       StringVector directoryList = path.getSplitPath();
       for (auto iter = directoryList.begin(), endIter = directoryList.end(); endIter != iter; ++iter) {
         std::string dname = *iter;
         if (dname == ".")
           continue;
         if (dname == "..") {
           if (directory == m_rootDirectory)
             return STATUS_CODE_FAILURE;
           directory = directory->parent();
           continue;
         }
         // navigate forward
         StatusCode statusCode = directory->find(dname, directory);
         if (statusCode != STATUS_CODE_SUCCESS)
           return statusCode;
       }
       return STATUS_CODE_SUCCESS;
     }
template<typename T> template<typename F > ObjectPtr dqm4hep::core::Storage< T >::findObject (F function) const
template<typename T> template<typename F > ObjectPtr dqm4hep::core::Storage< T >::findObject (const std::string & dirName, F function) const
template<typename T> template<typename F > Storage<T>::ObjectPtr dqm4hep::core::Storage< T >::findObject (F function) const inline
Definition at line 369 of file Storage.h.
{
       return m_currentDirectory->find(function);
     }
template<typename T> template<typename F > Storage<T>::ObjectPtr dqm4hep::core::Storage< T >::findObject (const std::string & dirName, F function) const inline
Definition at line 377 of file Storage.h.
{
       DirectoryPtr directory;
       if (this->find(dirName, directory))
         return nullptr;
       return directory->find(function);
     }
template<typename T > template<typename U > void dqm4hep::core::Storage< T >::getObjects (std::vector< std::shared_ptr< U >> & objectList) const inline
Definition at line 437 of file Storage.h.
{
       this->iterate([&](const DirectoryPtr &/*directory*/, ObjectPtr object) {
         objectList.push_back(std::dynamic_pointer_cast<U>(object));
         return true;
       });
     }
template<typename T > StatusCode dqm4hep::core::Storage< T >::goUp () inline
Definition at line 215 of file Storage.h.
{
       if (m_currentDirectory->isRoot())
         return STATUS_CODE_UNCHANGED;
       m_currentDirectory = m_currentDirectory->parent();
       return STATUS_CODE_SUCCESS;
     }
template<typename T > template<typename F > void dqm4hep::core::Storage< T >::iterate (F function) const inline
Definition at line 429 of file Storage.h.
{
       this->iterate(m_rootDirectory, function);
     }
template<typename T > template<typename F > bool dqm4hep::core::Storage< T >::iterate (const DirectoryPtr & directory, F function) const inline private
Definition at line 409 of file Storage.h.
{
       auto contents(directory->contents());
       for (auto &obj : contents)
         if (!function(directory, obj))
           return false;
       auto subdirs(directory->subdirs());
       for (const auto &dir : subdirs)
         if (!this->iterate(dir, function))
           return false;
       return true;
     }
template<typename T > StatusCode dqm4hep::core::Storage< T >::mkdir (const std::string & dirName) inline
Definition at line 109 of file Storage.h.
References dqm4hep::core::Path::getSplitPath(), dqm4hep::core::Path::isRelative(), dqm4hep::core::Path::isValid(), and RETURN_RESULT_IF.
{
       if (dirName.empty())
         return STATUS_CODE_INVALID_PARAMETER;
       Path path(dirName);
       if (!path.isValid())
         return STATUS_CODE_INVALID_PARAMETER;
       DirectoryPtr directory = !path.isRelative() ? m_rootDirectory : m_currentDirectory;
       StringVector directoryList = path.getSplitPath();
       for (auto iter = directoryList.begin(), endIter = directoryList.end(); endIter != iter; ++iter) {
         std::string dname = *iter;
         if (dname == ".")
           continue;
         if (dname == "..") {
           if (directory == m_rootDirectory)
             return STATUS_CODE_FAILURE;
           directory = directory->parent();
           continue;
         }
         // if sub dir doesn't exists, create it
         if (!directory->hasChild(dname))
           directory->mkdir(dname);
         // navigate forward
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, directory->find(dname, directory));
       }
       return STATUS_CODE_SUCCESS;
     }
template<typename T > const std::string & dqm4hep::core::Storage< T >::pwd () const inline
Definition at line 208 of file Storage.h.
{
       return m_currentDirectory->name();
     }
template<typename T > template<typename F > StatusCode dqm4hep::core::Storage< T >::remove (F function) inline
Definition at line 351 of file Storage.h.
{
       return m_currentDirectory->remove(function);
     }
template<typename T > template<typename F > StatusCode dqm4hep::core::Storage< T >::remove (const std::string & dirName, F function) inline
Definition at line 359 of file Storage.h.
References RETURN_RESULT_IF.
{
       DirectoryPtr directory = nullptr;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->find(dirName, directory));
       return directory->remove(function);
     }
template<typename T > StatusCode dqm4hep::core::Storage< T >::rmdir (const std::string & dirName) inline
Definition at line 227 of file Storage.h.
References RETURN_RESULT_IF.
{
       if (dirName.empty())
         return STATUS_CODE_NOT_ALLOWED;
       DirectoryPtr directory = nullptr;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->find(dirName, directory));
       if (directory == m_rootDirectory)
         return STATUS_CODE_NOT_ALLOWED;
       std::string fullPathDirName = directory->fullPath().getPath();
       std::string currentFullPathDirName = m_currentDirectory->fullPath().getPath();
       size_t pos = currentFullPathDirName.find(fullPathDirName);
       // this mean that the directory that we try
       // to remove is a parent of the current one.
       if (pos == 0 || pos != std::string::npos)
         return STATUS_CODE_FAILURE;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, directory->parent()->rmdir(directory->name()));
       return STATUS_CODE_SUCCESS;
     }
template<typename T > Storage< T >::DirectoryPtr dqm4hep::core::Storage< T >::root () const inline
Definition at line 298 of file Storage.h.
Referenced by dqm4hep::core::Archiver::archive(), and dqm4hep::core::Archiver::archiveWithReferences().
{
       return m_rootDirectory;
     }
Member Data Documentation
template<typename T> DirectoryPtr dqm4hep::core::Storage< T >::m_currentDirectory private
Definition at line 91 of file Storage.h.
template<typename T> DirectoryPtr dqm4hep::core::Storage< T >::m_rootDirectory private
Definition at line 90 of file Storage.h.
The documentation for this class was generated from the following files:
Archiver.h
Storage.h