DQMCore: nlohmann::detail::iter_impl< BasicJsonType > Class Template Reference
nlohmann::detail::iter_impl< BasicJsonType > Class Template Reference
a template for a bidirectional iterator for the basic_json class
#include <json.h>
Public Types
using iterator_category = std::bidirectional_iterator_tag
The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17.
using value_type = typename BasicJsonType::value_type
the type of the values when the iterator is dereferenced
using difference_type = typename BasicJsonType::difference_type
a type to represent differences between iterators
using pointer = typename std::conditional< std::is_const< BasicJsonType >::value, typename BasicJsonType::const_pointer, typename BasicJsonType::pointer >::type
defines a pointer to the type iterated over (value_type)
using reference = typename std::conditional< std::is_const< BasicJsonType >::value, typename BasicJsonType::const_reference, typename BasicJsonType::reference >::type
defines a reference to the type iterated over (value_type)
Public Member Functions
iter_impl ()=default
default constructor
iter_impl (pointer object) noexcept
constructor for a given JSON instance
iter_impl (const iter_impl< typename std::remove_const< BasicJsonType >::type > &other) noexcept
converting constructor
iter_impl & operator= (const iter_impl< typename std::remove_const< BasicJsonType >::type > &other) noexcept
converting assignment
reference operator* () const
return a reference to the value pointed to by the iterator
pointer operator-> () const
dereference the iterator
iter_impl const operator++ (int)
post-increment (it++)
iter_impl & operator++ ()
pre-increment (++it)
iter_impl const operator-- (int)
post-decrement (it–)
iter_impl & operator-- ()
pre-decrement (–it)
bool operator== (const iter_impl &other) const
comparison: equal
bool operator!= (const iter_impl &other) const
comparison: not equal
bool operator< (const iter_impl &other) const
comparison: smaller
bool operator<= (const iter_impl &other) const
comparison: less than or equal
bool operator> (const iter_impl &other) const
comparison: greater than
bool operator>= (const iter_impl &other) const
comparison: greater than or equal
iter_impl & operator+= (difference_type i)
add to iterator
iter_impl & operator-= (difference_type i)
subtract from iterator
iter_impl operator+ (difference_type i) const
add to iterator
iter_impl operator- (difference_type i) const
subtract from iterator
difference_type operator- (const iter_impl &other) const
return difference
reference operator[] (difference_type n) const
access to successor
object_t::key_type key () const
return the key of an object iterator
reference value () const
return the value of an iterator
Private Types
using object_t = typename BasicJsonType::object_t
using array_t = typename BasicJsonType::array_t
Private Member Functions
void set_begin () noexcept
set the iterator to the first value
void set_end () noexcept
set the iterator past the last value
Private Attributes
friend BasicJsonType
friend iteration_proxy< iter_impl >
pointer m_object = nullptr
associated JSON instance
internal_iterator< typename
std::remove_const
< BasicJsonType >::type > m_it = {}
the actual iterator of the associated instance
Friends
iter_impl operator+ (difference_type i, const iter_impl &it)
addition of distance and iterator
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::iter_impl< BasicJsonType >
a template for a bidirectional iterator for the basic_json class
This class implements a both iterators (iterator and const_iterator) for the basic_json class.
Note
An iterator is called initialized when a pointer to a JSON value has been set (e.g., by a constructor or a copy assignment). If the iterator is default-constructed, it is uninitialized and most methods are undefined. The library uses assertions to detect calls on uninitialized iterators.**
The class satisfies the following concept requirements:
BidirectionalIterator: The iterator that can be moved can be moved in both directions (i.e. incremented and decremented).
Since
version 1.0.0, simplified in version 2.0.9, change to bidirectional iterators in version 3.0.0 (see https://github.com/nlohmann/json/issues/593)
Definition at line 3534 of file json.h.
Member Typedef Documentation
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::array_t = typename BasicJsonType::array_t private
Definition at line 3543 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::difference_type = typename BasicJsonType::difference_type
a type to represent differences between iterators
Definition at line 3559 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::iterator_category = std::bidirectional_iterator_tag
The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17.
The C++ Standard has never required user-defined iterators to derive from std::iterator. A user-defined iterator should provide publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators.
Definition at line 3554 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::object_t = typename BasicJsonType::object_t private
Definition at line 3542 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::pointer = typename std::conditional<std::is_const<BasicJsonType>::value, typename BasicJsonType::const_pointer, typename BasicJsonType::pointer>::type
defines a pointer to the type iterated over (value_type)
Definition at line 3563 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::reference = typename std::conditional<std::is_const<BasicJsonType>::value, typename BasicJsonType::const_reference, typename BasicJsonType::reference>::type
defines a reference to the type iterated over (value_type)
Definition at line 3567 of file json.h.
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::value_type = typename BasicJsonType::value_type
the type of the values when the iterator is dereferenced
Definition at line 3557 of file json.h.
Constructor & Destructor Documentation
template<typename BasicJsonType > iter_impl< typename std::conditional< std::is_const< BasicJsonType >::value, typename std::remove_const< BasicJsonType >::type, const BasicJsonType >::type > () default
default constructor
allow basic_json to access private members
Definition at line 3538 of file json.h.
template<typename BasicJsonType > nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (pointer object) inline explicit noexcept
constructor for a given JSON instance
Parameters
[in] object pointer to a JSON object for this iterator
Precondition
object != nullptr
Postcondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3578 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
                                                   : m_object(object) {
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object: {
           m_it.object_iterator = typename object_t::iterator();
           break;
         }
         case value_t::array: {
           m_it.array_iterator = typename array_t::iterator();
           break;
         }
         default: {
           m_it.primitive_iterator = primitive_iterator_t();
           break;
         }
         }
       }
template<typename BasicJsonType > nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (const iter_impl< typename std::remove_const< BasicJsonType >::type > & other) inline noexcept
converting constructor
Note
The conventional copy constructor and copy assignment are implicitly defined. Combined with the following converting constructor and assignment, they support: (1) copy from iterator to iterator, (2) copy from const iterator to const iterator, and (3) conversion from iterator to const iterator. However conversion from const iterator to iterator is not defined.
Parameters
[in] other non-const iterator to copy from
Note
It is not checked whether other is initialized.
Definition at line 3613 of file json.h.
           : m_object(other.m_object),
             m_it(other.m_it) {
       }
Member Function Documentation
template<typename BasicJsonType > object_t::key_type nlohmann::detail::iter_impl< BasicJsonType >::key () const inline
return the key of an object iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 4014 of file json.h.
References nlohmann::detail::invalid_iterator::create(), JSON_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, and nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator.
{
         assert(m_object != nullptr);
         if (JSON_LIKELY(m_object->is_object())) {
           return m_it.object_iterator->first;
         }
         JSON_THROW(invalid_iterator::create(207, "cannot use key() for non-object iterators"));
       }
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator!= (const iter_impl< BasicJsonType > & other) const inline
comparison: not equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3849 of file json.h.
References nlohmann::detail::iter_impl< BasicJsonType >::operator==().
{
         return not operator==(other);
       }
template<typename BasicJsonType > reference nlohmann::detail::iter_impl< BasicJsonType >::operator* () const inline
return a reference to the value pointed to by the iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3692 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::is_begin(), JSON_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::null, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::value().
{
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object: {
           assert(m_it.object_iterator != m_object->m_value.object->end());
           return m_it.object_iterator->second;
         }
         case value_t::array: {
           assert(m_it.array_iterator != m_object->m_value.array->end());
           return *m_it.array_iterator;
         }
         case value_t::null:
           JSON_THROW(invalid_iterator::create(214, "cannot get value"));
         default: {
           if (JSON_LIKELY(m_it.primitive_iterator.is_begin())) {
             return *m_object;
           }
           JSON_THROW(invalid_iterator::create(214, "cannot get value"));
         }
         }
       }
template<typename BasicJsonType > iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator+ (difference_type i) const inline
add to iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3938 of file json.h.
{
         auto result = *this;
         result += i;
         return result;
       }
template<typename BasicJsonType > iter_impl const nlohmann::detail::iter_impl< BasicJsonType >::operator++ (int) inline
post-increment (it++)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3751 of file json.h.
{
         auto result = *this;
         ++(*this);
         return result;
       }
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator++ () inline
pre-increment (++it)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3761 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
{
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object: {
           std::advance(m_it.object_iterator, 1);
           break;
         }
         case value_t::array: {
           std::advance(m_it.array_iterator, 1);
           break;
         }
         default: {
           ++m_it.primitive_iterator;
           break;
         }
         }
         return *this;
       }
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator+= (difference_type i) inline
add to iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3905 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator-=().
{
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object:
           JSON_THROW(invalid_iterator::create(209, "cannot use offsets with object iterators"));
         case value_t::array: {
           std::advance(m_it.array_iterator, i);
           break;
         }
         default: {
           m_it.primitive_iterator += i;
           break;
         }
         }
         return *this;
       }
template<typename BasicJsonType > iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator- (difference_type i) const inline
subtract from iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3958 of file json.h.
{
         auto result = *this;
         result -= i;
         return result;
       }
template<typename BasicJsonType > difference_type nlohmann::detail::iter_impl< BasicJsonType >::operator- (const iter_impl< BasicJsonType > & other) const inline
return difference
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3968 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
{
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object:
           JSON_THROW(invalid_iterator::create(209, "cannot use offsets with object iterators"));
         case value_t::array:
           return m_it.array_iterator - other.m_it.array_iterator;
         default:
           return m_it.primitive_iterator - other.m_it.primitive_iterator;
         }
       }
template<typename BasicJsonType > iter_impl const nlohmann::detail::iter_impl< BasicJsonType >::operator-- (int) inline
post-decrement (it–)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3788 of file json.h.
{
         auto result = *this;
         --(*this);
         return result;
       }
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator-- () inline
pre-decrement (–it)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3798 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
{
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object: {
           std::advance(m_it.object_iterator, -1);
           break;
         }
         case value_t::array: {
           std::advance(m_it.array_iterator, -1);
           break;
         }
         default: {
           --m_it.primitive_iterator;
           break;
         }
         }
         return *this;
       }
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator-= (difference_type i) inline
subtract from iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3930 of file json.h.
References nlohmann::detail::iter_impl< BasicJsonType >::operator+=().
{
         return operator+=(-i);
       }
template<typename BasicJsonType > pointer nlohmann::detail::iter_impl< BasicJsonType >::operator-> () const inline
dereference the iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3723 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::is_begin(), JSON_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
{
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object: {
           assert(m_it.object_iterator != m_object->m_value.object->end());
           return &(m_it.object_iterator->second);
         }
         case value_t::array: {
           assert(m_it.array_iterator != m_object->m_value.array->end());
           return &*m_it.array_iterator;
         }
         default: {
           if (JSON_LIKELY(m_it.primitive_iterator.is_begin())) {
             return m_object;
           }
           JSON_THROW(invalid_iterator::create(214, "cannot get value"));
         }
         }
       }
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator< (const iter_impl< BasicJsonType > & other) const inline
comparison: smaller
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3857 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), JSON_THROW, JSON_UNLIKELY, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator>=().
{
         // if objects are not the same, the comparison is undefined
         if (JSON_UNLIKELY(m_object != other.m_object)) {
           JSON_THROW(invalid_iterator::create(212, "cannot compare iterators of different containers"));
         }
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object:
           JSON_THROW(invalid_iterator::create(213, "cannot compare order of object iterators"));
         case value_t::array:
           return (m_it.array_iterator < other.m_it.array_iterator);
         default:
           return (m_it.primitive_iterator < other.m_it.primitive_iterator);
         }
       }
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator<= (const iter_impl< BasicJsonType > & other) const inline
comparison: less than or equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3881 of file json.h.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator>().
{
         return not other.operator<(*this);
       }
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator= (const iter_impl< typename std::remove_const< BasicJsonType >::type > & other) inline noexcept
converting assignment
Parameters
[in,out] other non-const iterator to copy from
Returns
const/non-const iterator
Note
It is not checked whether other is initialized.
Definition at line 3624 of file json.h.
References nlohmann::detail::iter_impl< BasicJsonType >::m_it, and nlohmann::detail::iter_impl< BasicJsonType >::m_object.
{
         m_object = other.m_object;
         m_it = other.m_it;
         return *this;
       }
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator== (const iter_impl< BasicJsonType > & other) const inline
comparison: equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3825 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), JSON_THROW, JSON_UNLIKELY, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator!=().
{
         // if objects are not the same, the comparison is undefined
         if (JSON_UNLIKELY(m_object != other.m_object)) {
           JSON_THROW(invalid_iterator::create(212, "cannot compare iterators of different containers"));
         }
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object:
           return (m_it.object_iterator == other.m_it.object_iterator);
         case value_t::array:
           return (m_it.array_iterator == other.m_it.array_iterator);
         default:
           return (m_it.primitive_iterator == other.m_it.primitive_iterator);
         }
       }
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator> (const iter_impl< BasicJsonType > & other) const inline
comparison: greater than
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3889 of file json.h.
References nlohmann::detail::iter_impl< BasicJsonType >::operator<=().
{
         return not operator<=(other);
       }
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator>= (const iter_impl< BasicJsonType > & other) const inline
comparison: greater than or equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3897 of file json.h.
References nlohmann::detail::iter_impl< BasicJsonType >::operator<().
{
         return not operator<(other);
       }
template<typename BasicJsonType > reference nlohmann::detail::iter_impl< BasicJsonType >::operator[] (difference_type n) const inline
access to successor
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3987 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::get_value(), JSON_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::null, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
{
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object:
           JSON_THROW(invalid_iterator::create(208, "cannot use operator[] for object iterators"));
         case value_t::array:
           return *std::next(m_it.array_iterator, n);
         case value_t::null:
           JSON_THROW(invalid_iterator::create(214, "cannot get value"));
         default: {
           if (JSON_LIKELY(m_it.primitive_iterator.get_value() == -n)) {
             return *m_object;
           }
           JSON_THROW(invalid_iterator::create(214, "cannot get value"));
         }
         }
       }
template<typename BasicJsonType > void nlohmann::detail::iter_impl< BasicJsonType >::set_begin () inline private noexcept
set the iterator to the first value
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3635 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::null, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator, nlohmann::detail::primitive_iterator_t::set_begin(), and nlohmann::detail::primitive_iterator_t::set_end().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::begin(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::cbegin().
{
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object: {
           m_it.object_iterator = m_object->m_value.object->begin();
           break;
         }
         case value_t::array: {
           m_it.array_iterator = m_object->m_value.array->begin();
           break;
         }
         case value_t::null: {
           // set to end so begin()==end() is true: null is empty
           m_it.primitive_iterator.set_end();
           break;
         }
         default: {
           m_it.primitive_iterator.set_begin();
           break;
         }
         }
       }
template<typename BasicJsonType > void nlohmann::detail::iter_impl< BasicJsonType >::set_end () inline private noexcept
set the iterator past the last value
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3666 of file json.h.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator, and nlohmann::detail::primitive_iterator_t::set_end().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::cend(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::end().
{
         assert(m_object != nullptr);
         switch (m_object->m_type) {
         case value_t::object: {
           m_it.object_iterator = m_object->m_value.object->end();
           break;
         }
         case value_t::array: {
           m_it.array_iterator = m_object->m_value.array->end();
           break;
         }
         default: {
           m_it.primitive_iterator.set_end();
           break;
         }
         }
       }
template<typename BasicJsonType > reference nlohmann::detail::iter_impl< BasicJsonType >::value () const inline
return the value of an iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 4028 of file json.h.
References nlohmann::detail::iter_impl< BasicJsonType >::operator*().
{
         return operator*();
       }
Friends And Related Function Documentation
template<typename BasicJsonType > iter_impl operator+ (difference_type i, const iter_impl< BasicJsonType > & it) friend
addition of distance and iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 3948 of file json.h.
{
         auto result = it;
         result += i;
         return result;
       }
Member Data Documentation
template<typename BasicJsonType > friend nlohmann::detail::iter_impl< BasicJsonType >::BasicJsonType private
Definition at line 3539 of file json.h.
template<typename BasicJsonType > friend nlohmann::detail::iter_impl< BasicJsonType >::iteration_proxy< iter_impl > private
Definition at line 3540 of file json.h.
template<typename BasicJsonType > internal_iterator<typename std::remove_const<BasicJsonType>::type> nlohmann::detail::iter_impl< BasicJsonType >::m_it = {} private
the actual iterator of the associated instance
Definition at line 4036 of file json.h.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert(), nlohmann::detail::iter_impl< BasicJsonType >::iter_impl(), nlohmann::detail::iter_impl< BasicJsonType >::key(), nlohmann::detail::iter_impl< BasicJsonType >::operator*(), nlohmann::detail::iter_impl< BasicJsonType >::operator++(), nlohmann::detail::iter_impl< BasicJsonType >::operator+=(), nlohmann::detail::iter_impl< BasicJsonType >::operator-(), nlohmann::detail::iter_impl< BasicJsonType >::operator--(), nlohmann::detail::iter_impl< BasicJsonType >::operator->(), nlohmann::detail::iter_impl< BasicJsonType >::operator<(), nlohmann::detail::iter_impl< BasicJsonType >::operator=(), nlohmann::detail::iter_impl< BasicJsonType >::operator==(), nlohmann::detail::iter_impl< BasicJsonType >::operator[](), nlohmann::detail::iter_impl< BasicJsonType >::set_begin(), and nlohmann::detail::iter_impl< BasicJsonType >::set_end().
template<typename BasicJsonType > pointer nlohmann::detail::iter_impl< BasicJsonType >::m_object = nullptr private
associated JSON instance
Definition at line 4034 of file json.h.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert(), nlohmann::detail::iter_impl< BasicJsonType >::iter_impl(), nlohmann::detail::iter_impl< BasicJsonType >::key(), nlohmann::detail::iter_impl< BasicJsonType >::operator*(), nlohmann::detail::iter_impl< BasicJsonType >::operator++(), nlohmann::detail::iter_impl< BasicJsonType >::operator+=(), nlohmann::detail::iter_impl< BasicJsonType >::operator-(), nlohmann::detail::iter_impl< BasicJsonType >::operator--(), nlohmann::detail::iter_impl< BasicJsonType >::operator->(), nlohmann::detail::iter_impl< BasicJsonType >::operator<(), nlohmann::detail::iter_impl< BasicJsonType >::operator=(), nlohmann::detail::iter_impl< BasicJsonType >::operator==(), nlohmann::detail::iter_impl< BasicJsonType >::operator[](), nlohmann::detail::iter_impl< BasicJsonType >::set_begin(), nlohmann::detail::iter_impl< BasicJsonType >::set_end(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::update().
The documentation for this class was generated from the following file:
json.h