DQMCore: dqm4hep::core::RootStyle Class Reference
dqm4hep::core::RootStyle Class Reference
RootStyle class.
#include <RootStyle.h>
Classes
class Theme
Theme class Builtin themes for customizing monitor element.
Public Member Functions
RootStyle ()=default
RootStyle (const RootStyle &)=default
RootStyle & operator= (const RootStyle &)=default
~RootStyle ()=default
void applyTo (TObject *object) const
Apply current style to target object.
StatusCode fromXml (const TiXmlHandle &handle)
Read the style properties from the xml handle.
Static Public Member Functions
static int stringToColor (const std::string &colorStr)
Get the ROOT color from string.
static StatusCode builtinStyle (const std::string &theme, RootStyle &objectStyle, RootStyle &referenceStyle)
Get a builtin style for monitor object and reference from builtin themes.
Public Attributes
int m_markerStyle = {1}
The ROOT marker style.
int m_markerColor = {1}
The ROOT marker color.
int m_markerSize = {1}
The ROOT marker size.
int m_lineStyle = {1}
The ROOT line style.
int m_lineColor = {1}
The ROOT line color.
int m_lineWidth = {1}
The ROOT line width.
int m_fillStyle = {0}
The ROOT fill style.
int m_fillColor = {0}
The ROOT fill color.
Private Member Functions
StatusCode readColor (const TiXmlHandle &handle, const std::string &name, int &color)
Read color from the xml handle.
Detailed Description
RootStyle class.
Class holding marker, line and fill attribute. Provide convinience methods for settings attributes to monitor element (object or reference). Some builtin themes are provided:
"default" : plain black and dashed red
"thick" : same as default with larger marker size and line width
"polar" : blue-ish colors
"sunrise" : red-ish colors
"forest" : green-ish colors
To be used as:
RootStyle objStyle, refStyle;
RootStyle::builtinStyle(RootStyle::Theme::SUNRISE, objStyle, refStyle);
Definition at line 60 of file RootStyle.h.
Constructor & Destructor Documentation
dqm4hep::core::RootStyle::RootStyle () default
Referenced by builtinStyle().
dqm4hep::core::RootStyle::RootStyle (const RootStyle &) default
dqm4hep::core::RootStyle::~RootStyle () default
Member Function Documentation
void dqm4hep::core::RootStyle::applyTo (TObject * object) const
Apply current style to target object.
Parameters
object the object to apply style
Definition at line 45 of file RootStyle.cc.
References m_fillColor, m_fillStyle, m_lineColor, m_lineStyle, m_lineWidth, m_markerColor, m_markerSize, and m_markerStyle.
Referenced by dqm4hep::core::MonitorElementManager::attachReference(), dqm4hep::core::MonitorElementManager::bookHisto(), dqm4hep::core::MonitorElementManager::bookMonitorElement(), dqm4hep::core::MonitorElementManager::bookObject(), dqm4hep::core::MonitorElementManager::bookScalar(), and dqm4hep::core::MonitorElementManager::readMonitorElement().
{
       if(nullptr == object) {
         return;
       }
       TAttMarker *markerAtt = dynamic_cast<TAttMarker*>(object);
       if(nullptr != markerAtt) {
         markerAtt->SetMarkerColor(m_markerColor);
         markerAtt->SetMarkerStyle(m_markerStyle);
         markerAtt->SetMarkerSize(m_markerSize);
       }
       TAttLine *lineAtt = dynamic_cast<TAttLine*>(object);
       if(nullptr != lineAtt) {
         lineAtt->SetLineColor(m_lineColor);
         lineAtt->SetLineStyle(m_lineStyle);
         lineAtt->SetLineWidth(m_lineWidth);
       }
       TAttFill *fillAtt = dynamic_cast<TAttFill*>(object);
       if(nullptr != fillAtt) {
         fillAtt->SetFillColor(m_fillColor);
         fillAtt->SetFillStyle(m_fillStyle);
       }
     }
StatusCode dqm4hep::core::RootStyle::builtinStyle (const std::string & theme, RootStyle & objectStyle, RootStyle & referenceStyle) static
Get a builtin style for monitor object and reference from builtin themes.
Parameters
theme the theme among the builtins
objectStyle the object style to receive
referenceStyle the reference style to receive
Definition at line 116 of file RootStyle.cc.
References dqm4hep::core::RootStyle::Theme::DEFAULT, dqm4hep::core::RootStyle::Theme::FOREST, m_fillColor, m_fillStyle, m_lineColor, m_lineStyle, m_lineWidth, m_markerColor, m_markerSize, dqm4hep::core::RootStyle::Theme::POLAR, RootStyle(), dqm4hep::core::RootStyle::Theme::SUNRISE, and dqm4hep::core::RootStyle::Theme::THICK.
{
       objectStyle = RootStyle();
       referenceStyle = RootStyle();
       if(theme == RootStyle::Theme::DEFAULT) {
         referenceStyle.m_markerColor = kRed;
         referenceStyle.m_lineColor = kRed;
         referenceStyle.m_fillColor = kRed;
         referenceStyle.m_lineStyle = 7;
         referenceStyle.m_fillStyle = 3244;
         return STATUS_CODE_SUCCESS;
       }
       else if(theme == RootStyle::Theme::THICK) {
         objectStyle.m_markerSize = 2;
         objectStyle.m_lineWidth = 2;
         referenceStyle.m_markerSize = 2;
         referenceStyle.m_lineWidth = 1;
         referenceStyle.m_markerColor = kRed;
         referenceStyle.m_lineColor = kRed;
         referenceStyle.m_fillColor = kRed;
         referenceStyle.m_lineStyle = 7;
         referenceStyle.m_fillStyle = 3244;
         return STATUS_CODE_SUCCESS;
       }
       else if(theme == RootStyle::Theme::POLAR) {
         objectStyle.m_markerSize = 2;
         objectStyle.m_lineWidth = 2;
         objectStyle.m_markerColor = kBlue;
         objectStyle.m_lineColor = kBlue;
         objectStyle.m_lineColor = kBlue;
         referenceStyle.m_markerSize = 2;
         referenceStyle.m_lineWidth = 1;
         referenceStyle.m_markerColor = kCyan+1;
         referenceStyle.m_lineColor = kCyan+1;
         referenceStyle.m_fillColor = kCyan+1;
         referenceStyle.m_lineStyle = 7;
         referenceStyle.m_fillStyle = 3244;
         return STATUS_CODE_SUCCESS;
       }
       else if(theme == RootStyle::Theme::SUNRISE) {
         objectStyle.m_markerSize = 2;
         objectStyle.m_lineWidth = 2;
         objectStyle.m_markerColor = kRed+1;
         objectStyle.m_lineColor = kRed+1;
         objectStyle.m_lineColor = kRed+1;
         referenceStyle.m_markerSize = 2;
         referenceStyle.m_lineWidth = 1;
         referenceStyle.m_markerColor = kOrange+7;
         referenceStyle.m_lineColor = kOrange+7;
         referenceStyle.m_fillColor = kOrange+7;
         referenceStyle.m_lineStyle = 7;
         referenceStyle.m_fillStyle = 3244;
         return STATUS_CODE_SUCCESS;
       }
       else if(theme == RootStyle::Theme::FOREST) {
         objectStyle.m_markerSize = 2;
         objectStyle.m_lineWidth = 2;
         objectStyle.m_markerColor = kGreen+1;
         objectStyle.m_lineColor = kGreen+1;
         objectStyle.m_lineColor = kGreen+1;
         referenceStyle.m_markerSize = 2;
         referenceStyle.m_lineWidth = 1;
         referenceStyle.m_markerColor = kOrange-7;
         referenceStyle.m_lineColor = kOrange-7;
         referenceStyle.m_fillColor = kOrange-7;
         referenceStyle.m_lineStyle = 7;
         referenceStyle.m_fillStyle = 3244;
         return STATUS_CODE_SUCCESS;
       }
       return STATUS_CODE_NOT_FOUND;
     }
StatusCode dqm4hep::core::RootStyle::fromXml (const TiXmlHandle & handle)
Read the style properties from the xml handle.
Parameters
handle the xml input handle
Definition at line 81 of file RootStyle.cc.
References m_fillColor, m_fillStyle, m_lineColor, m_lineStyle, m_lineWidth, m_markerColor, m_markerSize, m_markerStyle, readColor(), dqm4hep::core::XmlHelper::readParameter(), and RETURN_RESULT_IF_AND_IF.
{
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "MarkerStyle", m_markerStyle));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, RootStyle::readColor(handle,
         "MarkerColor", m_markerColor));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "MarkerSize", m_markerSize));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "LineStyle", m_lineStyle));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, RootStyle::readColor(handle,
         "LineColor", m_lineColor));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "LineWidth", m_lineWidth));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "FillStyle", m_fillStyle));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, RootStyle::readColor(handle,
         "FillColor", m_fillColor));
       return STATUS_CODE_SUCCESS;
     }
RootStyle& dqm4hep::core::RootStyle::operator= (const RootStyle &) default
StatusCode dqm4hep::core::RootStyle::readColor (const TiXmlHandle & handle, const std::string & name, int & color) private
Read color from the xml handle.
Parameters
handle the xml input handle
name the parameter name to read
color the color to receive
Definition at line 103 of file RootStyle.cc.
References dqm4hep::core::XmlHelper::readParameter(), RETURN_RESULT_IF, and stringToColor().
Referenced by fromXml().
{
       std::string colorStr;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(handle,
         name, colorStr));
       color = RootStyle::stringToColor(colorStr);
       if(color < 0) {
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
int dqm4hep::core::RootStyle::stringToColor (const std::string & colorStr) static
Get the ROOT color from string.
Returns -1 on fail
Parameters
colorStr the color as string (i.e "kBlack")
Definition at line 70 of file RootStyle.cc.
References ROOT_COLOR_TABLE, ROOT_COLOR_TO_COLOR, and dqm4hep::core::stringToType().
Referenced by readColor().
{
       int color = -1;
       if(!stringToType(str, color)) {
         ROOT_COLOR_TABLE(ROOT_COLOR_TO_COLOR)
         return -1;
       }
       return color;
     }
Member Data Documentation
int dqm4hep::core::RootStyle::m_fillColor = {0}
The ROOT fill color.
Definition at line 141 of file RootStyle.h.
Referenced by applyTo(), builtinStyle(), and fromXml().
int dqm4hep::core::RootStyle::m_fillStyle = {0}
The ROOT fill style.
Definition at line 139 of file RootStyle.h.
Referenced by applyTo(), builtinStyle(), and fromXml().
int dqm4hep::core::RootStyle::m_lineColor = {1}
The ROOT line color.
Definition at line 135 of file RootStyle.h.
Referenced by applyTo(), builtinStyle(), and fromXml().
int dqm4hep::core::RootStyle::m_lineStyle = {1}
The ROOT line style.
Definition at line 133 of file RootStyle.h.
Referenced by applyTo(), builtinStyle(), and fromXml().
int dqm4hep::core::RootStyle::m_lineWidth = {1}
The ROOT line width.
Definition at line 137 of file RootStyle.h.
Referenced by applyTo(), builtinStyle(), and fromXml().
int dqm4hep::core::RootStyle::m_markerColor = {1}
The ROOT marker color.
Definition at line 129 of file RootStyle.h.
Referenced by applyTo(), builtinStyle(), and fromXml().
int dqm4hep::core::RootStyle::m_markerSize = {1}
The ROOT marker size.
Definition at line 131 of file RootStyle.h.
Referenced by applyTo(), builtinStyle(), and fromXml().
int dqm4hep::core::RootStyle::m_markerStyle = {1}
The ROOT marker style.
Definition at line 127 of file RootStyle.h.
Referenced by applyTo(), and fromXml().
The documentation for this class was generated from the following files:
RootStyle.h
RootStyle.cc