DQMCore: dqm4hep::core::TiXmlAttributeSet Class Reference
dqm4hep::core::TiXmlAttributeSet Class Reference
#include <tinyxml.h>
Public Member Functions
TiXmlAttributeSet ()
~TiXmlAttributeSet ()
void Add (TiXmlAttribute *addMe)
void Remove (TiXmlAttribute *removeMe)
const TiXmlAttribute * First () const
TiXmlAttribute * First ()
const TiXmlAttribute * Last () const
TiXmlAttribute * Last ()
TiXmlAttribute * Find (const char *name) const
TiXmlAttribute * FindOrCreate (const char *_name)
TiXmlAttribute * Find (const std::string &name) const
TiXmlAttribute * FindOrCreate (const std::string &_name)
Private Member Functions
TiXmlAttributeSet (const TiXmlAttributeSet &)
void operator= (const TiXmlAttributeSet &)
Private Attributes
TiXmlAttribute sentinel = {}
Detailed Description
Definition at line 1012 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::core::TiXmlAttributeSet::TiXmlAttributeSet ()
Definition at line 1216 of file tinyxml.cc.
References dqm4hep::core::TiXmlAttribute::next, dqm4hep::core::TiXmlAttribute::prev, and sentinel.
{
       sentinel.next = &sentinel;
       sentinel.prev = &sentinel;
     }
dqm4hep::core::TiXmlAttributeSet::~TiXmlAttributeSet ()
Definition at line 1221 of file tinyxml.cc.
References dqm4hep::core::TiXmlAttribute::next, dqm4hep::core::TiXmlAttribute::prev, and sentinel.
{
       assert(sentinel.next == &sentinel);
       assert(sentinel.prev == &sentinel);
     }
dqm4hep::core::TiXmlAttributeSet::TiXmlAttributeSet (const TiXmlAttributeSet &) private
Member Function Documentation
void dqm4hep::core::TiXmlAttributeSet::Add (TiXmlAttribute * addMe)
Definition at line 1226 of file tinyxml.cc.
References Find(), dqm4hep::core::TiXmlAttribute::Name(), dqm4hep::core::TiXmlAttribute::next, dqm4hep::core::TiXmlAttribute::prev, sentinel, and TIXML_STRING.
Referenced by FindOrCreate(), and dqm4hep::core::TiXmlElement::Parse().
{
 #ifdef TIXML_USE_STL
       assert(!Find(TIXML_STRING(addMe->Name()))); // Shouldn't be multiply adding to the set.
 #else
       assert(!Find(addMe->Name())); // Shouldn't be multiply adding to the set.
 #endif
       addMe->next = &sentinel;
       addMe->prev = sentinel.prev;
       sentinel.prev->next = addMe;
       sentinel.prev = addMe;
     }
TiXmlAttribute * dqm4hep::core::TiXmlAttributeSet::Find (const char * name) const
Definition at line 1275 of file tinyxml.cc.
References dqm4hep::core::TiXmlAttribute::next, and sentinel.
Referenced by Add(), dqm4hep::core::TiXmlElement::Attribute(), FindOrCreate(), dqm4hep::core::TiXmlElement::Parse(), dqm4hep::core::TiXmlElement::QueryDoubleAttribute(), dqm4hep::core::TiXmlElement::QueryIntAttribute(), dqm4hep::core::TiXmlElement::QueryValueAttribute(), and dqm4hep::core::TiXmlElement::RemoveAttribute().
{
       for (TiXmlAttribute *node = sentinel.next; node != &sentinel; node = node->next) {
         if (strcmp(node->name.c_str(), name) == 0)
           return node;
       }
       return nullptr;
     }
TiXmlAttribute* dqm4hep::core::TiXmlAttributeSet::Find (const std::string & name) const
TiXmlAttribute * dqm4hep::core::TiXmlAttributeSet::FindOrCreate (const char * _name)
Definition at line 1283 of file tinyxml.cc.
References Add(), Find(), and dqm4hep::core::TiXmlAttribute::SetName().
Referenced by dqm4hep::core::TiXmlElement::SetAttribute(), and dqm4hep::core::TiXmlElement::SetDoubleAttribute().
{
       TiXmlAttribute *attrib = Find(_name);
       if (attrib == nullptr) {
         attrib = new TiXmlAttribute();
         Add(attrib);
         attrib->SetName(_name);
       }
       return attrib;
     }
TiXmlAttribute* dqm4hep::core::TiXmlAttributeSet::FindOrCreate (const std::string & _name)
const TiXmlAttribute* dqm4hep::core::TiXmlAttributeSet::First () const inline
Definition at line 1020 of file tinyxml.h.
References dqm4hep::core::TiXmlAttribute::next, and sentinel.
Referenced by dqm4hep::core::TiXmlElement::Accept(), dqm4hep::core::TiXmlElement::ClearThis(), dqm4hep::core::TiXmlElement::CopyTo(), dqm4hep::core::TiXmlElement::FirstAttribute(), and dqm4hep::core::TiXmlElement::Print().
{
         return (sentinel.next == &sentinel) ? nullptr : sentinel.next;
       }
TiXmlAttribute* dqm4hep::core::TiXmlAttributeSet::First () inline
Definition at line 1023 of file tinyxml.h.
References dqm4hep::core::TiXmlAttribute::next, and sentinel.
{
         return (sentinel.next == &sentinel) ? nullptr : sentinel.next;
       }
const TiXmlAttribute* dqm4hep::core::TiXmlAttributeSet::Last () const inline
Definition at line 1026 of file tinyxml.h.
References dqm4hep::core::TiXmlAttribute::prev, and sentinel.
Referenced by dqm4hep::core::TiXmlElement::LastAttribute().
{
         return (sentinel.prev == &sentinel) ? nullptr : sentinel.prev;
       }
TiXmlAttribute* dqm4hep::core::TiXmlAttributeSet::Last () inline
Definition at line 1029 of file tinyxml.h.
References dqm4hep::core::TiXmlAttribute::prev, and sentinel.
{
         return (sentinel.prev == &sentinel) ? nullptr : sentinel.prev;
       }
void dqm4hep::core::TiXmlAttributeSet::operator= (const TiXmlAttributeSet &) private
void dqm4hep::core::TiXmlAttributeSet::Remove (TiXmlAttribute * removeMe)
Definition at line 1240 of file tinyxml.cc.
References dqm4hep::core::TiXmlAttribute::next, dqm4hep::core::TiXmlAttribute::prev, and sentinel.
Referenced by dqm4hep::core::TiXmlElement::ClearThis(), and dqm4hep::core::TiXmlElement::RemoveAttribute().
{
       TiXmlAttribute *node;
       for (node = sentinel.next; node != &sentinel; node = node->next) {
         if (node == removeMe) {
           node->prev->next = node->next;
           node->next->prev = node->prev;
           node->next = nullptr;
           node->prev = nullptr;
           return;
         }
       }
       assert(0); // we tried to remove a non-linked attribute.
     }
Member Data Documentation
TiXmlAttribute dqm4hep::core::TiXmlAttributeSet::sentinel = {} private
Definition at line 1047 of file tinyxml.h.
Referenced by Add(), Find(), First(), Last(), Remove(), TiXmlAttributeSet(), and ~TiXmlAttributeSet().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc