DQMCore: dqm4hep::core::MeanWithinExpectedTest Class Reference
dqm4hep::core::MeanWithinExpectedTest Class Reference
MeanWithinExpectedTest class.
Classes
class Factory
Public Member Functions
MeanWithinExpectedTest (const std::string &name)
~MeanWithinExpectedTest () override=default
StatusCode readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override
Read the settings from the xml handle.
void userRun (MonitorElementPtr monitorElement, QualityTestReport &report) override
Runs a quality test on the given monitor element and return a quality estimate.
Public Member Functions inherited from dqm4hep::core::QualityTest
QualityTest (const std::string &type, const std::string &name)
Constructor.
virtual ~QualityTest ()
Destructor.
const std::string & type () const
Get the quality test type.
const std::string & name () const
Get the quality test name (unique identifier)
const std::string & description () const
Get the quality test description.
void run (MonitorElementPtr monitorElement, QualityTestReport &report)
Perform the quality test result and fill the quality test report.
virtual StatusCode init ()
Initialize the quality test.
virtual bool enoughStatistics (MonitorElementPtr monitorElement) const
Whether the monitor element has enough statistics to perform the qtest.
void setLimits (float warning, float error)
Set the warning and error limits on quality test result.
float warningLimit () const
Get the warning limit.
float errorLimit () const
Get the error limit.
Protected Attributes
float m_expectedMean
float m_meanDeviationLower
float m_meanDeviationUpper
Protected Attributes inherited from dqm4hep::core::QualityTest
std::string m_description
Quality test description.
Additional Inherited Members
Static Public Member Functions inherited from dqm4hep::core::QualityTest
static float defaultWarningLimit ()
Get the default warning limit.
static float defaultErrorLimit ()
Get the default error limit.
Protected Member Functions inherited from dqm4hep::core::QualityTest
void fillBasicInfo (MonitorElementPtr monitorElement, QualityTestReport &report) const
Fill basic info in the qtest report.
Static Protected Attributes inherited from dqm4hep::core::QualityTest
static float m_defaultWarningLimit = 0.8
static float m_defaultErrorLimit = 0.5
Detailed Description
MeanWithinExpectedTest class.
Definition at line 47 of file MeanWithinExpectedTest.cc.
Constructor & Destructor Documentation
dqm4hep::core::MeanWithinExpectedTest::MeanWithinExpectedTest (const std::string & name)
Definition at line 77 of file MeanWithinExpectedTest.cc.
References dqm4hep::core::QualityTest::m_description.
Referenced by dqm4hep::core::MeanWithinExpectedTest::Factory::createQualityTest().
         : QualityTest("MeanWithinExpected", name),
           m_expectedMean(0.f),
           m_meanDeviationLower(0.f),
           m_meanDeviationUpper(0.f) {
       m_description = "Test if the mean of the histogram if contained in the expected user range. The quality is "
                       "defined as the probability to be close to mean : 1 at the mean, 0 infinitely far from the mean "
                       "(using TMath::Prob(chi2,1))";
     }
dqm4hep::core::MeanWithinExpectedTest::~MeanWithinExpectedTest () override default
Member Function Documentation
StatusCode dqm4hep::core::MeanWithinExpectedTest::readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override virtual
Read the settings from the xml handle.
Implements dqm4hep::core::QualityTest.
Definition at line 89 of file MeanWithinExpectedTest.cc.
References m_expectedMean, m_meanDeviationLower, m_meanDeviationUpper, dqm4hep::core::XmlHelper::readParameter(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(xmlHandle, "ExpectedMean", m_expectedMean));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=,
                        XmlHelper::readParameter(xmlHandle, "MeanDeviationLower", m_meanDeviationLower,
                                                 [this](const float &value) { return value < this->m_expectedMean; }));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=,
                        XmlHelper::readParameter(xmlHandle, "MeanDeviationUpper", m_meanDeviationUpper,
                                                 [this](const float &value) { return value > this->m_expectedMean; }));
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::MeanWithinExpectedTest::userRun (MonitorElementPtr monitorElement, QualityTestReport & report) override virtual
Runs a quality test on the given monitor element and return a quality estimate.
Implements dqm4hep::core::QualityTest.
Definition at line 105 of file MeanWithinExpectedTest.cc.
References m_expectedMean, m_meanDeviationLower, m_meanDeviationUpper, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, and dqm4hep::core::typeToString().
{
       TH1 *pHistogram = monitorElement->objectTo<TH1>();
       if (nullptr == pHistogram) {
         report.m_message = "ROOT monitor object is not a TH1 object !";
         throw StatusCodeException(STATUS_CODE_INVALID_PTR);
       }
       const float mean(pHistogram->GetMean());
       const float range(fabs(m_meanDeviationUpper - m_meanDeviationLower));
       if (m_meanDeviationLower < mean && mean < m_meanDeviationUpper) {
         report.m_message =
             "Within expected range: expected " + typeToString(m_expectedMean) + ", got " + typeToString(mean);
       }
       else {
         report.m_message =
             "Out of expected range: expected " + typeToString(m_expectedMean) + ", got " + typeToString(mean);
       }
       const float chi = (mean - m_expectedMean) / range;
       report.m_quality = TMath::Prob(chi * chi, 1);
     }
Member Data Documentation
float dqm4hep::core::MeanWithinExpectedTest::m_expectedMean protected
Definition at line 60 of file MeanWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
float dqm4hep::core::MeanWithinExpectedTest::m_meanDeviationLower protected
Definition at line 61 of file MeanWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
float dqm4hep::core::MeanWithinExpectedTest::m_meanDeviationUpper protected
Definition at line 62 of file MeanWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
The documentation for this class was generated from the following file:
MeanWithinExpectedTest.cc