DQMCore: dqm4hep::core::MonitorElementStreamer Class Reference
dqm4hep::core::MonitorElementStreamer Class Reference
MonitorElementStreamer class.
#include <MonitorElementStreamer.h>
Public Member Functions
MonitorElementStreamer ()=default
Default constructor.
~MonitorElementStreamer ()=default
Default destructor.
template<typename T >
StatusCode writeMonitorElement (std::shared_ptr< T > monitorElement, xdrstream::IODevice *device)
Write a monitor element using an xdrstream device.
template<typename T >
StatusCode readMonitorElement (std::shared_ptr< T > &monitorElement, xdrstream::IODevice *device)
Read a monitor element using an xdrstream device.
template<typename T >
StatusCode writeMonitorElements (const std::vector< std::shared_ptr< T >> &elements, xdrstream::IODevice *device)
Write a list of monitor elements using an xdrstream device.
template<typename T >
StatusCode readMonitorElements (std::vector< std::shared_ptr< T >> &elements, xdrstream::IODevice *device)
Read a list of monitor elements using an xdrstream device.
template<typename T >
StatusCode writeMonitorElements (const std::map< std::string, std::vector< std::shared_ptr< T >>> &elements, xdrstream::IODevice *device)
Write a map of monitor elements using an xdrstream device.
template<typename T >
StatusCode readMonitorElements (std::map< std::string, std::vector< std::shared_ptr< T >>> &elements, xdrstream::IODevice *device)
Read a map of monitor elements using an xdrstream device.
Detailed Description
MonitorElementStreamer class.
Definition at line 47 of file MonitorElementStreamer.h.
Constructor & Destructor Documentation
dqm4hep::core::MonitorElementStreamer::MonitorElementStreamer () default
Default constructor.
dqm4hep::core::MonitorElementStreamer::~MonitorElementStreamer () default
Default destructor.
Member Function Documentation
template<typename T > StatusCode dqm4hep::core::MonitorElementStreamer::readMonitorElement (std::shared_ptr< T > & monitorElement, xdrstream::IODevice * device) inline
Read a monitor element using an xdrstream device.
Parameters
monitorElement a shared pointer on a monitor element or sub-class of it
device the xdrstream device to read with
Definition at line 129 of file MonitorElementStreamer.h.
References dqm_error, and RETURN_RESULT_IF.
Referenced by readMonitorElements().
{
       if(nullptr == device) {
         dqm_error( "Couldn't read monitor element from device: nullptr !" );
         return STATUS_CODE_INVALID_PTR;
       }
       std::shared_ptr<T> tmp = T::make_shared();
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, tmp->fromDevice(device));
       monitorElement = tmp;
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementStreamer::readMonitorElements (std::vector< std::shared_ptr< T >> & elements, xdrstream::IODevice * device) inline
Read a list of monitor elements using an xdrstream device.
Parameters
elements a vector of monitor elements to receive
device the xdrstream device to read with
Definition at line 166 of file MonitorElementStreamer.h.
References readMonitorElement(), and XDRSTREAM_SUCCESS_RESTORE.
Referenced by readMonitorElements().
{
       auto pos = device->getPosition();
       unsigned int nToRead = 0;
       XDRSTREAM_SUCCESS_RESTORE(device->read(&nToRead), pos);
       for(unsigned int i=0 ; i<nToRead ; ++i) {
         std::shared_ptr<T> element;
         StatusCode readCode = readMonitorElement(element, device);
         if(readCode != STATUS_CODE_SUCCESS) {
           device->seek(pos);
           return readCode;
         }
         elements.push_back(element);
       }
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementStreamer::readMonitorElements (std::map< std::string, std::vector< std::shared_ptr< T >>> & elements, xdrstream::IODevice * device) inline
Read a map of monitor elements using an xdrstream device.
Parameters
elements a map of monitor element vector to receive
device the xdrstream device to read with
Definition at line 203 of file MonitorElementStreamer.h.
References readMonitorElements(), and XDRSTREAM_SUCCESS_RESTORE.
{
       auto pos = device->getPosition();
       unsigned int nToRead = 0;
       XDRSTREAM_SUCCESS_RESTORE(device->read(&nToRead), pos);
       for(unsigned int i=0 ; i<nToRead ; ++i) {
         std::string key;
         XDRSTREAM_SUCCESS_RESTORE(device->read(&key), pos);
         std::vector<std::shared_ptr<T>> elements;
         StatusCode readCode = readMonitorElements(elements, device);
         if(readCode != STATUS_CODE_SUCCESS) {
           device->seek(pos);
           return readCode;
         }
         elementMap[key] = elements;
       }
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementStreamer::writeMonitorElement (std::shared_ptr< T > monitorElement, xdrstream::IODevice * device) inline
Write a monitor element using an xdrstream device.
Parameters
monitorElement a shared pointer on a monitor element or sub-class of it
device the xdrstream device to write with
Definition at line 118 of file MonitorElementStreamer.h.
References dqm_error.
Referenced by writeMonitorElements().
{
       if(nullptr == monitorElement or nullptr == device) {
         dqm_error( "Couldn't write monitor element to device: nullptr !" );
         return STATUS_CODE_INVALID_PTR;
       }
       return monitorElement->toDevice(device);
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementStreamer::writeMonitorElements (const std::vector< std::shared_ptr< T >> & elements, xdrstream::IODevice * device) inline
Write a list of monitor elements using an xdrstream device.
Parameters
elements a vector of monitor elements to write
device the xdrstream device to write with
Definition at line 143 of file MonitorElementStreamer.h.
References writeMonitorElement(), and XDRSTREAM_SUCCESS_RESTORE.
Referenced by writeMonitorElements().
{
       auto pos = device->getPosition();
       unsigned int nWritten = 0;
       XDRSTREAM_SUCCESS_RESTORE(device->write(&nWritten), pos);
       for(auto element : elements) {
         StatusCode writeCode = writeMonitorElement(element, device);
         if(writeCode != STATUS_CODE_SUCCESS) {
           device->seek(pos);
           return writeCode;
         }
         nWritten++;
       }
       // write the actual number of written monitor element at start position
       auto endPos = device->getPosition();
       device->seek(pos);
       XDRSTREAM_SUCCESS_RESTORE(device->write(&nWritten), pos);
       device->seek(endPos);
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementStreamer::writeMonitorElements (const std::map< std::string, std::vector< std::shared_ptr< T >>> & elements, xdrstream::IODevice * device) inline
Write a map of monitor elements using an xdrstream device.
Parameters
elements a map of monitor element vector to write
device the xdrstream device to write with
Definition at line 185 of file MonitorElementStreamer.h.
References writeMonitorElements(), and XDRSTREAM_SUCCESS_RESTORE.
{
       auto pos = device->getPosition();
       unsigned int nWritten = elements.size();
       XDRSTREAM_SUCCESS_RESTORE(device->write(&nWritten), pos);
       for(auto &iter : elements) {
         XDRSTREAM_SUCCESS_RESTORE(device->write(&iter.first), pos);
         StatusCode writeCode = writeMonitorElements(iter.second, device);
         if(writeCode != STATUS_CODE_SUCCESS) {
           device->seek(pos);
           return writeCode;
         }
       }
       return STATUS_CODE_SUCCESS;
     }
The documentation for this class was generated from the following file:
MonitorElementStreamer.h