DQMCore: dqm4hep::core::PluginManager Class Reference
dqm4hep::core::PluginManager Class Reference
PluginManager class.
#include <PluginManager.h>
Public Member Functions
StatusCode loadLibraries ()
Load shared libraries from the environment variable 4HEP_PLUGIN_DLL.
StatusCode loadLibraries (const StringVector &libraryNameList)
Load the shared libraries.
StatusCode loadLibrary (const std::string &libraryName)
Load the shared library.
const Plugin * getPlugin (const std::string &pluginName) const
Get the plug-in by name.
template<typename T >
std::shared_ptr< T > create (const std::string &pluginName) const
Get the plug-in clone.
bool isPluginRegistered (const std::string &pluginName) const
Whether the plug-in is registered within the plug-in manager.
StringVector pluginNames () const
Get the plug-in name list.
template<typename T >
StringVector pluginNamesMatchingType () const
Get the plugin name list matching the type T.
void dump () const
Dump registered plugin via logging.
Public Member Functions inherited from dqm4hep::core::Singleton< PluginManager >
Singleton ()
Constructor.
~Singleton ()
Destructor.
Private Types
typedef std::map< const
std::string, Plugin * > PluginMap
Private Member Functions
PluginManager ()=default
Default constructor.
~PluginManager ()
Destructor.
StatusCode registerPlugin (Plugin *pPlugin)
Register the plug-in.
Private Attributes
PluginMap m_pluginMap = {}
The map of registered plugins.
std::vector< void * > m_dlLibraries = {}
The list of loaded libraries.
Friends
class Singleton< PluginManager >
class Plugin
Additional Inherited Members
Static Public Member Functions inherited from dqm4hep::core::Singleton< PluginManager >
static PluginManager * instance ()
Return a unique instance of the class.
static void kill ()
Kill the unique instance of the class.
Static Protected Attributes inherited from dqm4hep::core::Singleton< PluginManager >
static PluginManager * m_pInstance
The unique instance of the class.
Detailed Description
PluginManager class.
Responsible for loading shared libraries that contains Plugin instances
Definition at line 68 of file PluginManager.h.
Member Typedef Documentation
typedef std::map<const std::string, Plugin *> dqm4hep::core::PluginManager::PluginMap private
Definition at line 72 of file PluginManager.h.
Constructor & Destructor Documentation
dqm4hep::core::PluginManager::PluginManager () private default
Default constructor.
dqm4hep::core::PluginManager::~PluginManager () private
Destructor.
Definition at line 39 of file PluginManager.cc.
References m_dlLibraries, and m_pluginMap.
{
       // No memory clean here, as the plugin instances are static
       m_pluginMap.clear();
       for (auto iter : m_dlLibraries) {
         (void) dlclose(iter);
       }
       m_dlLibraries.clear();
     }
Member Function Documentation
template<typename T > std::shared_ptr< T > dqm4hep::core::PluginManager::create (const std::string & pluginName) const inline
Get the plug-in clone.
A new plug-in instance is allocated and returned to the user. Ownership of the plug-in transfered to the caller.
Definition at line 136 of file PluginManager.h.
References dqm4hep::core::Plugin::create(), and getPlugin().
Referenced by dqm4hep::core::MonitorElementManager::MonitorElementManager(), dqm4hep::core::EventStreamer::readEvent(), and dqm4hep::core::EventStreamer::writeEvent().
{
       const Plugin *pPlugin = this->getPlugin(pluginName);
       if (!pPlugin)
         return std::shared_ptr<T>();
       Plugin *pClass = pPlugin->create();
       if (nullptr == pClass)
         return std::shared_ptr<T>();
       return std::shared_ptr<T>(dynamic_cast<T *>(pClass));
     }
void dqm4hep::core::PluginManager::dump () const
Dump registered plugin via logging.
Definition at line 168 of file PluginManager.cc.
References dqm_info, and m_pluginMap.
{
       dqm_info("******************************************************");
       dqm_info("******** Plugin manager -- Registered plugins ********");
       for (auto plugin : m_pluginMap) {
         dqm_info("** Plugin [class={0}] : {1}", plugin.second->pluginName(), plugin.second->className());
       }
       dqm_info("******************************************************");
     }
const Plugin * dqm4hep::core::PluginManager::getPlugin (const std::string & pluginName) const
Get the plug-in by name.
Definition at line 116 of file PluginManager.cc.
References isPluginRegistered(), and m_pluginMap.
Referenced by create().
{
       if (!isPluginRegistered(pluginName))
         return nullptr;
       return m_pluginMap.find(pluginName)->second;
     }
bool dqm4hep::core::PluginManager::isPluginRegistered (const std::string & pluginName) const
Whether the plug-in is registered within the plug-in manager.
Definition at line 125 of file PluginManager.cc.
References m_pluginMap.
Referenced by getPlugin(), and registerPlugin().
{
       return (m_pluginMap.find(pluginName) != m_pluginMap.end());
     }
StatusCode dqm4hep::core::PluginManager::loadLibraries ()
Load shared libraries from the environment variable 4HEP_PLUGIN_DLL.
Definition at line 51 of file PluginManager.cc.
References dqm_debug, and dqm4hep::core::tokenize().
{
       // get the environment plug-in dll variable
       char *pPluginDllEnv = getenv("DQM4HEP_PLUGIN_DLL");
       if (pPluginDllEnv == nullptr) {
         dqm_debug("Environment variable DQM4HEP_PLUGIN_DLL not found ! \n"
                   "Set it before loading shared libraries. \n"
                   "Example : export DQM4HEP_PLUGIN_DLL=libPlugin1.so:libPlugin2.so");
         return STATUS_CODE_SUCCESS;
       }
       // split the string into a list
       std::string libraryConcatenateList(pPluginDllEnv);
       StringVector libraryList;
       dqm4hep::core::tokenize(libraryConcatenateList, libraryList, ":");
       // load the shared libraries
       return this->loadLibraries(libraryList);
     }
StatusCode dqm4hep::core::PluginManager::loadLibraries (const StringVector & libraryNameList)
Load the shared libraries.
Definition at line 75 of file PluginManager.cc.
References loadLibrary(), and RETURN_RESULT_IF.
{
       for (auto iter = libraryNameList.begin(), endIter = libraryNameList.end(); endIter != iter; ++iter) {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->loadLibrary(*iter));
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::PluginManager::loadLibrary (const std::string & libraryName)
Load the shared library.
Definition at line 85 of file PluginManager.cc.
References dqm_error, dqm_info, and m_dlLibraries.
Referenced by loadLibraries().
{
       size_t idx = libraryName.find_last_of("/");
       // the library basename, i.e. /path/to/libBlah.so --> libBlah.so
       std::string libBaseName(libraryName.substr(idx + 1));
       char *real_path = realpath(libraryName.c_str(), nullptr);
       if (nullptr != real_path) {
         dqm_info("<!-- Loading shared library : {0} ({1})-->", real_path, libBaseName);
         // use real_path
         free(real_path);
       } else {
         dqm_info("<!-- Loading shared library : {0} ({1})-->", libraryName, libBaseName);
       }
       void *pLibPointer = dlopen(libraryName.c_str(), RTLD_LAZY | RTLD_GLOBAL | RTLD_NODELETE);
       if (pLibPointer == nullptr) {
         dqm_error("<!-- ERROR loading shared library : {0}\n    ->    {1} -->", libraryName, dlerror());
         return STATUS_CODE_FAILURE;
       }
       m_dlLibraries.push_back(pLibPointer);
       return STATUS_CODE_SUCCESS;
     }
StringVector dqm4hep::core::PluginManager::pluginNames () const
Get the plug-in name list.
Definition at line 131 of file PluginManager.cc.
References m_pluginMap.
{
       StringVector pluginNameList;
       for (auto iter = m_pluginMap.begin(), endIter = m_pluginMap.end(); endIter != iter; ++iter) {
         pluginNameList.push_back(iter->first);
       }
       return pluginNameList;
     }
template<typename T > StringVector dqm4hep::core::PluginManager::pluginNamesMatchingType () const inline
Get the plugin name list matching the type T.
Definition at line 153 of file PluginManager.h.
References m_pluginMap.
Referenced by dqm4hep::core::MonitorElementManager::MonitorElementManager().
{
       StringVector names;
       for (auto plugin : m_pluginMap) {
         const Plugin *pPlugin(plugin.second);
         if (nullptr != dynamic_cast<const T *>(pPlugin))
           names.push_back(plugin.first);
       }
       return names;
     }
StatusCode dqm4hep::core::PluginManager::registerPlugin (Plugin * pPlugin) private
Register the plug-in.
Only available by plug-ins themselves
Definition at line 143 of file PluginManager.cc.
References isPluginRegistered(), m_pluginMap, and dqm4hep::core::Plugin::pluginName().
Referenced by dqm4hep::core::Plugin::registerMe().
{
       // null ptr case
       if (nullptr == pPlugin)
         return STATUS_CODE_INVALID_PTR;
       // check if the plug is already registered
       if (isPluginRegistered(pPlugin->pluginName())) {
         delete pPlugin;
         pPlugin = nullptr;
         return STATUS_CODE_ALREADY_PRESENT;
       }
       // try to register it
       if (!m_pluginMap.insert(PluginMap::value_type(pPlugin->pluginName(), pPlugin)).second) {
         delete pPlugin;
         pPlugin = nullptr;
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
Friends And Related Function Documentation
friend class Plugin friend
Definition at line 70 of file PluginManager.h.
friend class Singleton< PluginManager > friend
Definition at line 69 of file PluginManager.h.
Member Data Documentation
std::vector<void*> dqm4hep::core::PluginManager::m_dlLibraries = {} private
The list of loaded libraries.
Definition at line 129 of file PluginManager.h.
Referenced by loadLibrary(), and ~PluginManager().
PluginMap dqm4hep::core::PluginManager::m_pluginMap = {} private
The map of registered plugins.
Definition at line 128 of file PluginManager.h.
Referenced by dump(), getPlugin(), isPluginRegistered(), pluginNames(), pluginNamesMatchingType(), registerPlugin(), and ~PluginManager().
The documentation for this class was generated from the following files:
PluginManager.h
PluginManager.cc