DQMCore: dqm4hep::core::EventStreamer Class Reference
dqm4hep::core::EventStreamer Class Reference
#include <EventStreamer.h>
Public Member Functions
EventStreamer ()=default
Default constructor.
~EventStreamer ()=default
Default destructor.
StatusCode writeEvent (EventPtr event, xdrstream::IODevice *device)
Write an event using an xdrstream device.
StatusCode readEvent (EventPtr &event, xdrstream::IODevice *pDevice)
Read an event using an xdrstream device.
Private Attributes
std::string m_streamerName = {""}
The current event streamer name in use.
EventStreamerPluginPtr m_streamer = {nullptr}
The current event streamer in use.
Detailed Description
Definition at line 45 of file EventStreamer.h.
Constructor & Destructor Documentation
dqm4hep::core::EventStreamer::EventStreamer () default
Default constructor.
dqm4hep::core::EventStreamer::~EventStreamer () default
Default destructor.
Member Function Documentation
StatusCode dqm4hep::core::EventStreamer::readEvent (EventPtr & event, xdrstream::IODevice * pDevice)
Read an event using an xdrstream device.
The streamer info is read from the buffer and the streamer if allocated from the plugin manager.
Parameters
event the event to read
device the xdrstream device to read with
Definition at line 65 of file EventStreamer.cc.
References dqm4hep::core::PluginManager::create(), dqm_error, dqm4hep::core::Singleton< PluginManager >::instance(), m_streamer, m_streamerName, and RETURN_RESULT_IF.
{
       // consistency check
       if (nullptr == device)
         return STATUS_CODE_INVALID_PARAMETER;
       // read streamer name
       std::string streamerName;
       if (!XDR_TESTBIT(device->read(&streamerName), xdrstream::XDR_SUCCESS))
         return STATUS_CODE_FAILURE;
       // setup event streamer
       if(not m_streamer or m_streamerName != streamerName) {
         m_streamer = nullptr;
         m_streamer = PluginManager::instance()->create<EventStreamerPlugin>(streamerName);
         if(not m_streamer) {
           dqm_error( "EventStreamer::readEvent: streamer '{0}' not registered in plugin manager !", streamerName );
           return STATUS_CODE_FAILURE;
         }
         m_streamerName = streamerName;
       }
       // read user event data
       event = m_streamer->createEvent();
       event->setStreamerName(m_streamerName);
       // write base event data
       if (!XDR_TESTBIT(event->readBase(device), xdrstream::XDR_SUCCESS))
         return STATUS_CODE_FAILURE;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_streamer->read(event, device));
       event->setEventSize(device->getPosition());
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::EventStreamer::writeEvent (EventPtr event, xdrstream::IODevice * device)
Write an event using an xdrstream device.
The streamer info is taken from Event::getStreamerName() and from the plugin manager.
Parameters
event the event to write
device the xdrstream device to write with
Definition at line 37 of file EventStreamer.cc.
References dqm4hep::core::PluginManager::create(), dqm_error, dqm4hep::core::Singleton< PluginManager >::instance(), m_streamer, m_streamerName, and RETURN_RESULT_IF.
{
       // consistency check
       if (nullptr == event or nullptr == device)
         return STATUS_CODE_INVALID_PARAMETER;
       // setup event streamer
       std::string streamerName = event->getStreamerName();
       if(not m_streamer or m_streamerName != streamerName) {
         m_streamer = nullptr;
         m_streamer = PluginManager::instance()->create<EventStreamerPlugin>(streamerName);
         if(not m_streamer) {
           dqm_error( "EventStreamer::writeEvent: streamer '{0}' not registered in plugin manager !", streamerName );
           return STATUS_CODE_FAILURE;
         }
         m_streamerName = streamerName;
       }
       // write streamer name
       if (!XDR_TESTBIT(device->write(&m_streamerName), xdrstream::XDR_SUCCESS))
         return STATUS_CODE_FAILURE;
       // write base event data
       if (!XDR_TESTBIT(event->writeBase(device), xdrstream::XDR_SUCCESS))
         return STATUS_CODE_FAILURE;
       // write user event data
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_streamer->write(event, device));
       return STATUS_CODE_SUCCESS;
     }
Member Data Documentation
EventStreamerPluginPtr dqm4hep::core::EventStreamer::m_streamer = {nullptr} private
The current event streamer in use.
Definition at line 79 of file EventStreamer.h.
Referenced by readEvent(), and writeEvent().
std::string dqm4hep::core::EventStreamer::m_streamerName = {""} private
The current event streamer name in use.
Definition at line 78 of file EventStreamer.h.
Referenced by readEvent(), and writeEvent().
The documentation for this class was generated from the following files:
EventStreamer.h
EventStreamer.cc