DQMCore: dqm4hep::core Namespace Reference
dqm4hep::core Namespace Reference
Classes
class TScalarObject
TScalarObject class.
class TObjectXMLAllocator
TObjectXMLAllocator class.
class DefaultXMLAllocator
TXMLDefaultAllocator class for all ROOT class with default constructor.
class TH1XMLAllocator
TH1XMLAllocator class for all TH1 types.
class TH2XMLAllocator
TH2XMLAllocator class for all TH2 types.
class TH3XMLAllocator
TH3XMLAllocator class for all TH3 types.
class THStackXMLAllocator
THStackXMLAllocator class for all THStack type.
class TH2PolyXMLAllocator
THStackXMLAllocator class for all TH2Poly type.
class TProfileXMLAllocator
TProfileXMLAllocator class for all TProfile type.
class TProfile2DXMLAllocator
TProfile2DXMLAllocator class for all TProfile2D type.
class TScalarXMLAllocator
TScalarXMLAllocator class for all scalar types.
class AnalysisHelper
analysis helper class
class Directory
Directory class.
class Storage
class Archiver
Archiver class.
class ArchiverSelector
ArchiverSelector class Helper class to select monitor elements while archiving It is a combinaison of selector functions.
class DBInterface
DBInterface class.
class Event
Event class.
class EventBase
EventBase interface.
class EventStreamer
class EventStreamerPlugin
EventStreamerPlugin class.
class GenericEvent
GenericEvent class.
class type
type traits class helper
class time
time helper class
struct CpuStats
CpuStats struct.
struct MemoryStats
MemoryStats struct All units in Mb.
struct ProcessStats
ProcessStats struct All memory units in Mb.
struct INetworkStats
INetworkStats struct.
class Logger
class MonitorElement
MonitorElement class.
class TDynamicGraph
TDynamicGraph class.
class MonitorElementManager
MonitorElementManager class.
class MonitorElementStreamer
MonitorElementStreamer class.
class Path
Path class.
class Plugin
Plugin class.
class PluginManager
PluginManager class.
class PtrHandler
PtrHandler template class.
class QualityTestReport
QualityTestReport class Hanlde the result of a quality test.
class QReportStorage
QReportStorage class.
class QualityTest
QualityTest class.
class QualityTestFactory
QualityTestFactory class.
class RootStyle
RootStyle class.
class Run
Run class.
class SignalBase
SignalBase class (internal) Base class for emitting signals.
class SignalBase< void >
SignalBase specialization (internal) No argument in callback function.
class SignalT
SignalT class (internal)
class SignalT< T, void >
class SignalT< void, Args...>
SPECIALIZATION - PURE FUNCTION + ARGS.
class SignalT< void, void >
class Signal
Signal class.
class Singleton
Singleton class.
class StatusCodeException
StatusCodeException class.
class StreamingHelper
class TiXmlString
class TiXmlOutStream
struct TiXmlCursor
class TiXmlVisitor
Implements the interface to the "Visitor pattern" (see the Accept() method.) If you call the Accept() method, it requires being passed a TiXmlVisitor class to handle callbacks.
class TiXmlBase
TiXmlBase is a base class for every class in TinyXml.
class TiXmlNode
The parent class for everything in the Document Object Model.
class TiXmlAttribute
An attribute is a name-value pair.
class TiXmlAttributeSet
class TiXmlElement
The element is a container class.
class TiXmlComment
An XML comment.
class TiXmlText
XML text.
class TiXmlDeclaration
In correct XML the declaration is the first entry in the file.
class TiXmlUnknown
Any tag that tinyXml doesn't recognize is saved as an unknown.
class TiXmlDocument
Always the top level node.
class TiXmlHandle
A TiXmlHandle is a class that wraps a node pointer with null checks; this is an incredibly useful thing.
class TiXmlPrinter
Print to memory functionality.
class Version
Version class.
class XmlHelper
XmlHelper class.
class XMLParser
XMLParser class.
class ExactRefCompareTest
ExactRefCompareTest class Compare the monitor element to its reference.
class FitParamInRangeTest
FitParamInRangeTest class.
class GenericEventStreamer
GenericEventStreamer class.
class GenericEventXMLReader
GenericEventXMLReader class Read an XML and read GenericEvent events from it.
class PropertyWithinExpectedTest
PropertyWithinExpectedTest class.
class RootEventStreamer
RootEventStreamer class.
class TiXmlParsingData
Typedefs
typedef time::clock TimeClock
typedef time::point TimePoint
typedef time::duration TimeDuration
typedef type< Event >::ptr EventPtr
typedef type< Event >::ptr_deque EventQueue
typedef type
< EventStreamerPlugin >::ptr EventStreamerPluginPtr
typedef type< Plugin >::ptr PluginPtr
typedef char dqm_char
typedef uint8_t dqm_uchar
typedef int16_t dqm_short
typedef uint16_t dqm_ushort
typedef int16_t dqm_short_int
typedef uint16_t dqm_ushort_int
typedef int64_t dqm_lint
typedef uint64_t dqm_ulint
typedef float dqm_real
typedef float dqm_float
typedef double dqm_double
typedef long dqm_long
typedef long long dqm_long_long
typedef bool dqm_bool
typedef int64_t dqm_int
typedef uint64_t dqm_uint
typedef long unsigned int dqm_stat
typedef std::vector< int > IntVector
typedef std::vector< unsigned int > UIntVector
typedef std::vector< float > FloatVector
typedef std::vector< double > DoubleVector
typedef std::vector< std::string > StringVector
typedef std::set< std::string > StringSet
typedef std::map< std::string,
std::string > ParameterMap
typedef std::pair< std::string,
std::string > StringPair
typedef std::map< std::string,
std::string > StringMap
typedef type< MonitorElement >::ptr MonitorElementPtr
typedef type< MonitorElement >
::ptr_vector MonitorElementList
typedef type< MonitorElement >
::str_ptr_map MonitorElementMap
typedef type< Directory
< MonitorElement > >::ptr MonitorElementDir
typedef QualityTest QTest
typedef QualityTestReport QReport
typedef type< QTest >::ptr QTestPtr
typedef type< QReport >::str_map QReportMap
typedef std::map< StringPair,
QReportMap > QReportContainer
typedef type< QTest >::str_ptr_map QTestMap
typedef type< Storage
< MonitorElement > >::ptr MeStoragePtr
typedef std::map< std::string,
INetworkStats > NetworkStats
using json = nlohmann::json
typedef TScalarObject< int > TScalarInt
typedef TScalarObject< float > TScalarReal
typedef TScalarObject< float > TScalarFloat
typedef TScalarObject< double > TScalarDouble
typedef TScalarObject< short > TScalarShort
typedef TScalarObject< long > TScalarLong
typedef TScalarObject< Long64_t > TScalarLong64_t
typedef TScalarObject
< std::string > TScalarString
typedef
ExactRefCompareTest::Factory ExactRefCompareTestFactory
typedef
FitParamInRangeTest::Factory FitParamInRangeTestFactory
typedef
PropertyWithinExpectedTest::Factory PropertyWithinExpectedTestFactory
Enumerations
enum EventType {
UNKNOWN_EVENT = 0, RAW_DATA_EVENT = 1, RECONSTRUCTED_EVENT = 2, PHYSICS_EVENT = 3,
CUSTOM_EVENT = 4
}
EventType enumerator.
enum QualityFlag {
UNDEFINED, INVALID, INSUFFICENT_STAT, SUCCESS,
WARNING, ERROR
}
enum StatusCode { NUMBER_OF_STATUS_CODES }
StatusCode enumerator.
enum { TIXML_SUCCESS, TIXML_NO_ATTRIBUTE, TIXML_WRONG_TYPE }
enum TiXmlEncoding { TIXML_ENCODING_UNKNOWN, TIXML_ENCODING_UTF8, TIXML_ENCODING_LEGACY }
Functions
template<class T >
bool stringToType (const std::string &s, T &t)
Convert std::string to a type.
template<class T >
std::string typeToString (const T &t)
Convert type to std::string.
template<>
bool stringToType (const std::string &s, std::string &t)
template<>
std::string typeToString (const std::string &t)
void screenSplash ()
Screen splash of DQM4HEP.
template<typename T >
void tokenize (const std::string &inputString, std::vector< T > &tokens, const std::string &delimiter=" ")
Tokenize string with delimiter.
template<>
void tokenize (const std::string &inputString, StringVector &tokens, const std::string &delimiter)
Tokenize string with delimiter.
bool wildcardMatch (const std::string &testString, const std::string &wildcardString, bool caseSensitive=true)
Whether the test string matches the wildcard expression.
std::string & replaceAll (std::string &subject, const std::string &search, const std::string &replace)
Replaces all occurences in the spcified string.
DEPRECATED (void timeToHMS(std::time_t t, std::string &timeStr))
Convert time_t to hour, minutes and seconds.
DEPRECATED (TimePoint now())
Get the current time (unit seconds)
DEPRECATED (void sleep(const TimeDuration &duration))
Sleep for the specified time duration.
StringVector getSpecialCharacterList ()
Get the special character list that are to be avoided in some strings.
bool containsSpecialCharacters (const std::string &str)
Whether the string contains a special character.
void fillHostInfo (StringMap &info)
Fill host info (uname result + host name).
template<>
bool stringToType (const std::string &s, bool &t)
Specialization for booleans.
int pid ()
Get the current process id.
void cpuStats (CpuStats &stats, dqm_int sampleTime=1)
Get some memory stats.
void memStats (MemoryStats &stats)
Get some memory stats.
void procStats (ProcessStats &stats)
Get stats from current process.
void netStats (NetworkStats &stats, dqm_int sampleTime=1)
Get some network stats.
Path operator+ (const Path &lhs, const Path &rhs)
std::ostream & operator<< (std::ostream &out, const Path &path)
bool operator== (const Path &lhs, const Path &rhs)
template<typename T >
bool operator== (const PtrHandler< T > &lhs, const PtrHandler< T > &rhs)
template<typename T >
bool operator== (const T *lhs, const PtrHandler< T > &rhs)
template<typename T >
bool operator== (const PtrHandler< T > &lhs, const T *rhs)
template<typename T >
bool operator!= (const PtrHandler< T > &lhs, const PtrHandler< T > &rhs)
template<typename T >
bool operator!= (const T *lhs, const PtrHandler< T > &rhs)
template<typename T >
bool operator!= (const PtrHandler< T > &lhs, const T *rhs)
template<typename S >
bool operator== (std::nullptr_t lhs, const PtrHandler< S > &rhs)
template<typename S >
bool operator== (const PtrHandler< S > &lhs, std::nullptr_t rhs)
template<typename S >
bool operator!= (std::nullptr_t lhs, const PtrHandler< S > &rhs)
template<typename S >
bool operator!= (const PtrHandler< S > &lhs, std::nullptr_t rhs)
std::ostream & operator<< (std::ostream &out, const Run &run)
std::string statusCodeToString (const StatusCode statusCode)
bool operator== (const TiXmlString &a, const TiXmlString &b)
bool operator< (const TiXmlString &a, const TiXmlString &b)
bool operator!= (const TiXmlString &a, const TiXmlString &b)
bool operator> (const TiXmlString &a, const TiXmlString &b)
bool operator<= (const TiXmlString &a, const TiXmlString &b)
bool operator>= (const TiXmlString &a, const TiXmlString &b)
bool operator== (const TiXmlString &a, const char *b)
bool operator== (const char *a, const TiXmlString &b)
bool operator!= (const TiXmlString &a, const char *b)
bool operator!= (const char *a, const TiXmlString &b)
TiXmlString operator+ (const TiXmlString &a, const TiXmlString &b)
TiXmlString operator+ (const TiXmlString &a, const char *b)
TiXmlString operator+ (const char *a, const TiXmlString &b)
bool operator< (const Version &lhs, const Version &rhs)
bool operator<= (const Version &lhs, const Version &rhs)
bool operator> (const Version &lhs, const Version &rhs)
bool operator>= (const Version &lhs, const Version &rhs)
bool operator== (const Version &lhs, const Version &rhs)
bool operator!= (const Version &lhs, const Version &rhs)
void timeToHMS (std::time_t t, std::string &timeStr)
TimePoint now ()
void sleep (const TimeDuration &duration)
DQM_PLUGIN_DECL (ExactRefCompareTestFactory,"ExactRefCompareTest")
DQM_PLUGIN_DECL (FitParamInRangeTestFactory,"FitParamInRangeTest")
DQM_PLUGIN_DECL (GenericEventStreamer,"GenericEventStreamer")
DQM_PLUGIN_DECL (GenericEventXMLReader,"GenericEventXMLReader")
DQM_PLUGIN_DECL (PropertyWithinExpectedTestFactory,"PropertyWithinExpectedTest")
DQM_PLUGIN_DECL (RootEventStreamer,"RootEventStreamer")
FILE * TiXmlFOpen (const char *filename, const char *mode)
Variables
const int TIXML_MAJOR_VERSION = 2
const int TIXML_MINOR_VERSION = 6
const int TIXML_PATCH_VERSION = 1
const TiXmlEncoding TIXML_DEFAULT_ENCODING = TIXML_ENCODING_UNKNOWN
const unsigned char TIXML_UTF_LEAD_0 = 0xefU
const unsigned char TIXML_UTF_LEAD_1 = 0xbbU
const unsigned char TIXML_UTF_LEAD_2 = 0xbfU
Typedef Documentation
typedef std::vector<double> dqm4hep::core::DoubleVector
Definition at line 311 of file Internal.h.
typedef bool dqm4hep::core::dqm_bool
Definition at line 302 of file Internal.h.
typedef char dqm4hep::core::dqm_char
Definition at line 289 of file Internal.h.
typedef double dqm4hep::core::dqm_double
Definition at line 299 of file Internal.h.
typedef float dqm4hep::core::dqm_float
Definition at line 298 of file Internal.h.
typedef int64_t dqm4hep::core::dqm_int
Definition at line 303 of file Internal.h.
typedef int64_t dqm4hep::core::dqm_lint
Definition at line 295 of file Internal.h.
typedef long dqm4hep::core::dqm_long
Definition at line 300 of file Internal.h.
typedef long long dqm4hep::core::dqm_long_long
Definition at line 301 of file Internal.h.
typedef float dqm4hep::core::dqm_real
Definition at line 297 of file Internal.h.
typedef int16_t dqm4hep::core::dqm_short
Definition at line 291 of file Internal.h.
typedef int16_t dqm4hep::core::dqm_short_int
Definition at line 293 of file Internal.h.
typedef long unsigned int dqm4hep::core::dqm_stat
Definition at line 305 of file Internal.h.
typedef uint8_t dqm4hep::core::dqm_uchar
Definition at line 290 of file Internal.h.
typedef uint64_t dqm4hep::core::dqm_uint
Definition at line 304 of file Internal.h.
typedef uint64_t dqm4hep::core::dqm_ulint
Definition at line 296 of file Internal.h.
typedef uint16_t dqm4hep::core::dqm_ushort
Definition at line 292 of file Internal.h.
typedef uint16_t dqm4hep::core::dqm_ushort_int
Definition at line 294 of file Internal.h.
typedef type<Event>::ptr dqm4hep::core::EventPtr
Definition at line 281 of file Internal.h.
typedef type<Event>::ptr_deque dqm4hep::core::EventQueue
Definition at line 282 of file Internal.h.
typedef type<EventStreamerPlugin>::ptr dqm4hep::core::EventStreamerPluginPtr
Definition at line 283 of file Internal.h.
typedef ExactRefCompareTest::Factory dqm4hep::core::ExactRefCompareTestFactory
Definition at line 84 of file ExactRefCompareTest.cc.
typedef FitParamInRangeTest::Factory dqm4hep::core::FitParamInRangeTestFactory
Definition at line 185 of file FitParamInRangeTest.cc.
typedef std::vector<float> dqm4hep::core::FloatVector
Definition at line 310 of file Internal.h.
typedef std::vector<int> dqm4hep::core::IntVector
Definition at line 308 of file Internal.h.
using dqm4hep::core::json = typedef nlohmann::json
Definition at line 15489 of file json.h.
typedef type<Storage<MonitorElement> >::ptr dqm4hep::core::MeStoragePtr
Definition at line 329 of file Internal.h.
typedef type<Directory<MonitorElement> >::ptr dqm4hep::core::MonitorElementDir
Definition at line 322 of file Internal.h.
typedef type<MonitorElement>::ptr_vector dqm4hep::core::MonitorElementList
Definition at line 320 of file Internal.h.
typedef type<MonitorElement>::str_ptr_map dqm4hep::core::MonitorElementMap
Definition at line 321 of file Internal.h.
typedef type<MonitorElement>::ptr dqm4hep::core::MonitorElementPtr
Definition at line 319 of file Internal.h.
typedef std::map<std::string, INetworkStats> dqm4hep::core::NetworkStats
Definition at line 682 of file Internal.h.
typedef std::map<std::string, std::string> dqm4hep::core::ParameterMap
Definition at line 314 of file Internal.h.
typedef type<Plugin>::ptr dqm4hep::core::PluginPtr
Definition at line 286 of file Internal.h.
typedef PropertyWithinExpectedTest::Factory dqm4hep::core::PropertyWithinExpectedTestFactory
Definition at line 71 of file PropertyWithinExpectedTest.cc.
typedef QualityTestReport dqm4hep::core::QReport
Definition at line 324 of file Internal.h.
typedef std::map<StringPair, QReportMap> dqm4hep::core::QReportContainer
Definition at line 327 of file Internal.h.
typedef type<QReport>::str_map dqm4hep::core::QReportMap
Definition at line 326 of file Internal.h.
typedef QualityTest dqm4hep::core::QTest
Definition at line 323 of file Internal.h.
typedef type<QTest>::str_ptr_map dqm4hep::core::QTestMap
Definition at line 328 of file Internal.h.
typedef type<QTest>::ptr dqm4hep::core::QTestPtr
Definition at line 325 of file Internal.h.
typedef std::map<std::string, std::string> dqm4hep::core::StringMap
Definition at line 316 of file Internal.h.
typedef std::pair<std::string, std::string> dqm4hep::core::StringPair
Definition at line 315 of file Internal.h.
typedef std::set<std::string> dqm4hep::core::StringSet
Definition at line 313 of file Internal.h.
typedef std::vector<std::string> dqm4hep::core::StringVector
Definition at line 312 of file Internal.h.
typedef time::clock dqm4hep::core::TimeClock
Definition at line 275 of file Internal.h.
typedef time::duration dqm4hep::core::TimeDuration
Definition at line 277 of file Internal.h.
typedef time::point dqm4hep::core::TimePoint
Definition at line 276 of file Internal.h.
typedef TScalarObject<double> dqm4hep::core::TScalarDouble
Definition at line 434 of file MonitorElement.h.
typedef TScalarObject<float> dqm4hep::core::TScalarFloat
Definition at line 433 of file MonitorElement.h.
typedef TScalarObject<int> dqm4hep::core::TScalarInt
Definition at line 431 of file MonitorElement.h.
typedef TScalarObject<long> dqm4hep::core::TScalarLong
Definition at line 436 of file MonitorElement.h.
typedef TScalarObject<Long64_t> dqm4hep::core::TScalarLong64_t
Definition at line 437 of file MonitorElement.h.
typedef TScalarObject<float> dqm4hep::core::TScalarReal
Definition at line 432 of file MonitorElement.h.
typedef TScalarObject<short> dqm4hep::core::TScalarShort
Definition at line 435 of file MonitorElement.h.
typedef TScalarObject<std::string> dqm4hep::core::TScalarString
Definition at line 438 of file MonitorElement.h.
typedef std::vector<unsigned int> dqm4hep::core::UIntVector
Definition at line 309 of file Internal.h.
Enumeration Type Documentation
anonymous enum
Enumerator
TIXML_SUCCESS
TIXML_NO_ATTRIBUTE
TIXML_WRONG_TYPE
Definition at line 178 of file tinyxml.h.
 { TIXML_SUCCESS, TIXML_NO_ATTRIBUTE, TIXML_WRONG_TYPE };
enum dqm4hep::core::EventType
EventType enumerator.
Enumerator
UNKNOWN_EVENT
RAW_DATA_EVENT
RECONSTRUCTED_EVENT
PHYSICS_EVENT
CUSTOM_EVENT
Definition at line 46 of file Event.h.
                    {
       UNKNOWN_EVENT = 0,
       RAW_DATA_EVENT = 1,
       RECONSTRUCTED_EVENT = 2,
       PHYSICS_EVENT = 3,
       CUSTOM_EVENT = 4
     };
enum dqm4hep::core::QualityFlag
Enumerator
UNDEFINED
INVALID
INSUFFICENT_STAT
SUCCESS
WARNING
ERROR
Definition at line 44 of file QualityTest.h.
                      {
       UNDEFINED,
       INVALID,
       INSUFFICENT_STAT,
       SUCCESS,
       WARNING,
       ERROR
     };
enum dqm4hep::core::StatusCode
StatusCode enumerator.
Enumerator
NUMBER_OF_STATUS_CODES
Definition at line 139 of file StatusCodes.h.
                     {
       STATUS_CODE_TABLE(GET_ENUM_ENTRY)
       NUMBER_OF_STATUS_CODES
     };
enum dqm4hep::core::TiXmlEncoding
Enumerator
TIXML_ENCODING_UNKNOWN
TIXML_ENCODING_UTF8
TIXML_ENCODING_LEGACY
Definition at line 181 of file tinyxml.h.
 { TIXML_ENCODING_UNKNOWN, TIXML_ENCODING_UTF8, TIXML_ENCODING_LEGACY };
Function Documentation
bool dqm4hep::core::containsSpecialCharacters (const std::string & str) inline
Whether the string contains a special character.
Definition at line 529 of file Internal.h.
References getSpecialCharacterList().
Referenced by dqm4hep::core::Directory< T >::hasChild(), dqm4hep::core::Path::isValid(), and dqm4hep::core::Directory< T >::mkdir().
{
       StringVector specialCharacterList = dqm4hep::core::getSpecialCharacterList();
       for (auto iter = specialCharacterList.begin(), endIter = specialCharacterList.end(); endIter != iter; ++iter) {
         if (str.find(*iter) != std::string::npos)
           return true;
       }
       return false;
     }
void dqm4hep::core::cpuStats (CpuStats & stats, dqm_int sampleTime = 1)
Get some memory stats.
Parameters
object the CpuStats object to receive
Definition at line 786 of file Internal.cc.
{
 #if defined(__APPLE__)
       darwinCpuStats(stats, sampleTime);
 #elif defined(__linux__)
       linuxCpuStats(stats, sampleTime);
 #elif defined(_WIN32)
       winCpuStats(stats, sampleTime);
 #else
 #error "Unrecognized OS plateform (not windows, linux, OSX or unix) !"
 #endif
     }
dqm4hep::core::DEPRECATED (void timeToHMSstd::time_t t, std::string &timeStr)
Convert time_t to hour, minutes and seconds.
Convert TimePoint to time_tConvert time_t to TimePointConvert time_t to string format as "HOURSh MINUTESm SECONDSs"
dqm4hep::core::DEPRECATED (TimePoint now())
Get the current time (unit seconds)
dqm4hep::core::DEPRECATED (void sleepconst TimeDuration &duration)
Sleep for the specified time duration.
dqm4hep::core::DQM_PLUGIN_DECL (GenericEventStreamer , "GenericEventStreamer")
dqm4hep::core::DQM_PLUGIN_DECL (RootEventStreamer , "RootEventStreamer")
dqm4hep::core::DQM_PLUGIN_DECL (PropertyWithinExpectedTestFactory , "PropertyWithinExpectedTest")
dqm4hep::core::DQM_PLUGIN_DECL (GenericEventXMLReader , "GenericEventXMLReader")
dqm4hep::core::DQM_PLUGIN_DECL (ExactRefCompareTestFactory , "ExactRefCompareTest")
dqm4hep::core::DQM_PLUGIN_DECL (FitParamInRangeTestFactory , "FitParamInRangeTest")
void dqm4hep::core::fillHostInfo (StringMap & info) inline
Fill host info (uname result + host name).
See Key for available keys
Definition at line 544 of file Internal.h.
{
       // uname
       struct utsname unameStruct;
       uname(&unameStruct);
       // host name
       char host[256];
       gethostname(host, 256);
       info["system"] = unameStruct.sysname;
       info["node"] = unameStruct.nodename;
       info["release"] = unameStruct.release;
       info["version"] = unameStruct.version;
       info["machine"] = unameStruct.machine;
       info["host"] = host;
     }
StringVector dqm4hep::core::getSpecialCharacterList () inline
Get the special character list that are to be avoided in some strings.
Definition at line 496 of file Internal.h.
Referenced by containsSpecialCharacters().
{
       StringVector specialCharacterList;
       specialCharacterList.push_back("|");
       specialCharacterList.push_back("&");
       specialCharacterList.push_back(";");
       specialCharacterList.push_back("<");
       specialCharacterList.push_back(">");
       specialCharacterList.push_back("(");
       specialCharacterList.push_back(")");
       specialCharacterList.push_back("$");
       specialCharacterList.push_back("\\");
       specialCharacterList.push_back("\'");
       specialCharacterList.push_back("\"");
       specialCharacterList.push_back("\t");
       specialCharacterList.push_back("\n");
       specialCharacterList.push_back("*");
       specialCharacterList.push_back("?");
       specialCharacterList.push_back(",");
       specialCharacterList.push_back("[");
       specialCharacterList.push_back("]");
       specialCharacterList.push_back("#");
       specialCharacterList.push_back("~");
       specialCharacterList.push_back("=");
       specialCharacterList.push_back("%");
       return specialCharacterList;
     }
void dqm4hep::core::memStats (MemoryStats & stats)
Get some memory stats.
Parameters
object the MemoryStats object to receive
Definition at line 800 of file Internal.cc.
{
 #if defined(__APPLE__)
       darwinMemStats(stats);
 #elif defined(__linux__)
       linuxMemStats(stats);
 #elif defined(_WIN32)
       winMemStats(stats);
 #else
 #error "Unrecognized OS plateform (not windows, linux, OSX or unix) !"
 #endif
     }
void dqm4hep::core::netStats (NetworkStats & stats, dqm_int sampleTime = 1)
Get some network stats.
Parameters
object the NetworkStats object to receive
Definition at line 828 of file Internal.cc.
{
 #if defined(__APPLE__)
       darwinNetStats(stats, sampleTime);
 #elif defined(__linux__)
       linuxNetStats(stats, sampleTime);
 #elif defined(_WIN32)
       winNetStats(stats, sampleTime);
 #else
 #error "Unrecognized OS plateform (not windows, linux, OSX or unix) !"
 #endif
     }
TimePoint dqm4hep::core::now ()
Definition at line 91 of file Internal.cc.
References dqm4hep::core::time::now().
Referenced by dqm4hep::core::time::now().
                     {
       return time::now();
     }
bool dqm4hep::core::operator!= (const Version & lhs, const Version & rhs)
Definition at line 144 of file Version.cc.
{
       return !(lhs == rhs);
     }
template<typename T > bool dqm4hep::core::operator!= (const PtrHandler< T > & lhs, const PtrHandler< T > & rhs) inline
Definition at line 223 of file PtrHandler.h.
References dqm4hep::core::PtrHandler< T >::m_ptr.
{
       return lhs.m_ptr != rhs.m_ptr;
     }
template<typename T > bool dqm4hep::core::operator!= (const T * lhs, const PtrHandler< T > & rhs) inline
Definition at line 230 of file PtrHandler.h.
References dqm4hep::core::PtrHandler< T >::m_ptr.
{
       return lhs != rhs.m_ptr;
     }
template<typename T > bool dqm4hep::core::operator!= (const PtrHandler< T > & lhs, const T * rhs) inline
Definition at line 237 of file PtrHandler.h.
References dqm4hep::core::PtrHandler< T >::m_ptr.
{
       return lhs.m_ptr != rhs;
     }
template<typename S > bool dqm4hep::core::operator!= (std::nullptr_t lhs, const PtrHandler< S > & rhs) inline
Definition at line 258 of file PtrHandler.h.
References dqm4hep::core::PtrHandler< T >::m_ptr.
{
       return lhs != rhs.m_ptr;
     }
template<typename S > bool dqm4hep::core::operator!= (const PtrHandler< S > & lhs, std::nullptr_t rhs) inline
Definition at line 265 of file PtrHandler.h.
References dqm4hep::core::PtrHandler< T >::m_ptr.
{
       return lhs.m_ptr != rhs;
     }
bool dqm4hep::core::operator!= (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 270 of file tinystr.h.
{
       return !(a == b);
     }
bool dqm4hep::core::operator!= (const TiXmlString & a, const char * b) inline
Definition at line 289 of file tinystr.h.
{
       return !(a == b);
     }
bool dqm4hep::core::operator!= (const char * a, const TiXmlString & b) inline
Definition at line 292 of file tinystr.h.
{
       return !(b == a);
     }
Path dqm4hep::core::operator+ (const Path & lhs, const Path & rhs) inline
operator
Definition at line 103 of file Path.h.
References dqm4hep::core::Path::m_path.
Referenced by nlohmann::detail::json_reverse_iterator< Base >::operator+().
{
       Path path(lhs.m_path);
       path += rhs;
       return path;
     }
TiXmlString dqm4hep::core::operator+ (const TiXmlString & a, const TiXmlString & b)
Definition at line 76 of file tinystr.cc.
References dqm4hep::core::TiXmlString::length(), and dqm4hep::core::TiXmlString::reserve().
{
       TiXmlString tmp;
       tmp.reserve(a.length() + b.length());
       tmp += a;
       tmp += b;
       return tmp;
     }
TiXmlString dqm4hep::core::operator+ (const TiXmlString & a, const char * b)
Definition at line 84 of file tinystr.cc.
References dqm4hep::core::TiXmlString::append(), dqm4hep::core::TiXmlString::length(), and dqm4hep::core::TiXmlString::reserve().
{
       TiXmlString tmp;
       TiXmlString::size_type b_len = strlen(b);
       tmp.reserve(a.length() + b_len);
       tmp += a;
       tmp.append(b, b_len);
       return tmp;
     }
TiXmlString dqm4hep::core::operator+ (const char * a, const TiXmlString & b)
Definition at line 93 of file tinystr.cc.
References dqm4hep::core::TiXmlString::append(), dqm4hep::core::TiXmlString::length(), and dqm4hep::core::TiXmlString::reserve().
{
       TiXmlString tmp;
       TiXmlString::size_type a_len = strlen(a);
       tmp.reserve(a_len + b.length());
       tmp.append(a, a_len);
       tmp += b;
       return tmp;
     }
bool dqm4hep::core::operator< (const Version & lhs, const Version & rhs)
Definition at line 99 of file Version.cc.
References dqm4hep::core::Version::getMajor(), dqm4hep::core::Version::getMinor(), and dqm4hep::core::Version::getPatch().
{
       if (lhs.getMajor() < rhs.getMajor())
         return true;
       if (lhs.getMinor() < rhs.getMinor())
         return true;
       if (lhs.getPatch() < rhs.getPatch())
         return true;
       return false;
     }
bool dqm4hep::core::operator< (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 266 of file tinystr.h.
References dqm4hep::core::TiXmlString::c_str().
{
       return strcmp(a.c_str(), b.c_str()) < 0;
     }
std::ostream& dqm4hep::core::operator<< (std::ostream & out, const Path & path) inline
Definition at line 112 of file Path.h.
References dqm4hep::core::Path::m_path.
{
       out << path.m_path;
       return out;
     }
std::ostream & dqm4hep::core::operator<< (std::ostream & out, const Run & run)
Definition at line 99 of file Run.cc.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump(), and dqm4hep::core::Run::toJson().
{
       core::json jrun;
       run.toJson(jrun);
       out << jrun.dump(2);
       return out;
     }
bool dqm4hep::core::operator<= (const Version & lhs, const Version & rhs)
Definition at line 114 of file Version.cc.
References dqm4hep::core::Version::getMajor(), dqm4hep::core::Version::getMinor(), and dqm4hep::core::Version::getPatch().
{
       if (lhs < rhs)
         return true;
       if (lhs.getMajor() == rhs.getMajor() && lhs.getMinor() == rhs.getMinor() && lhs.getPatch() == rhs.getPatch())
         return true;
       return false;
     }
bool dqm4hep::core::operator<= (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 276 of file tinystr.h.
{
       return !(b < a);
     }
bool dqm4hep::core::operator== (const Version & lhs, const Version & rhs)
Definition at line 138 of file Version.cc.
References dqm4hep::core::Version::getMajor(), dqm4hep::core::Version::getMinor(), and dqm4hep::core::Version::getPatch().
{
       return (lhs.getMajor() == rhs.getMajor() && lhs.getMinor() == rhs.getMinor() && lhs.getPatch() == rhs.getPatch());
     }
bool dqm4hep::core::operator== (const Path & lhs, const Path & rhs) inline
Definition at line 120 of file Path.h.
References dqm4hep::core::Path::getSplitPath().
{
       return (lhs.getSplitPath() == rhs.getSplitPath());
     }
template<typename T > bool dqm4hep::core::operator== (const PtrHandler< T > & lhs, const PtrHandler< T > & rhs) inline
Definition at line 202 of file PtrHandler.h.
References dqm4hep::core::PtrHandler< T >::m_ptr.
{
       return lhs.m_ptr == rhs.m_ptr;
     }
template<typename T > bool dqm4hep::core::operator== (const T * lhs, const PtrHandler< T > & rhs) inline
Definition at line 209 of file PtrHandler.h.
References dqm4hep::core::PtrHandler< T >::m_ptr.
{
       return lhs == rhs.m_ptr;
     }
template<typename T > bool dqm4hep::core::operator== (const PtrHandler< T > & lhs, const T * rhs) inline
Definition at line 216 of file PtrHandler.h.
References dqm4hep::core::PtrHandler< T >::m_ptr.
{
       return lhs.m_ptr == rhs;
     }
template<typename S > bool dqm4hep::core::operator== (std::nullptr_t lhs, const PtrHandler< S > & rhs) inline
Definition at line 244 of file PtrHandler.h.
References dqm4hep::core::PtrHandler< T >::m_ptr.
{
       return lhs == rhs.m_ptr;
     }
template<typename S > bool dqm4hep::core::operator== (const PtrHandler< S > & lhs, std::nullptr_t rhs) inline
Definition at line 251 of file PtrHandler.h.
References dqm4hep::core::PtrHandler< T >::m_ptr.
{
       return lhs.m_ptr == rhs;
     }
bool dqm4hep::core::operator== (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 262 of file tinystr.h.
References dqm4hep::core::TiXmlString::c_str(), and dqm4hep::core::TiXmlString::length().
{
       return (a.length() == b.length())              // optimization on some platforms
              && (strcmp(a.c_str(), b.c_str()) == 0); // actual compare
     }
bool dqm4hep::core::operator== (const TiXmlString & a, const char * b) inline
Definition at line 283 of file tinystr.h.
References dqm4hep::core::TiXmlString::c_str().
{
       return strcmp(a.c_str(), b) == 0;
     }
bool dqm4hep::core::operator== (const char * a, const TiXmlString & b) inline
Definition at line 286 of file tinystr.h.
{
       return b == a;
     }
bool dqm4hep::core::operator> (const Version & lhs, const Version & rhs)
Definition at line 126 of file Version.cc.
{
       return !(lhs <= rhs);
     }
bool dqm4hep::core::operator> (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 273 of file tinystr.h.
{
       return b < a;
     }
bool dqm4hep::core::operator>= (const Version & lhs, const Version & rhs)
Definition at line 132 of file Version.cc.
{
       return !(lhs < rhs);
     }
bool dqm4hep::core::operator>= (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 279 of file tinystr.h.
{
       return !(a < b);
     }
int dqm4hep::core::pid () inline
Get the current process id.
Definition at line 582 of file Internal.h.
                      {
 #if _WIN32
       return GetCurrentProcessId();
 #else
       return ::getpid();
 #endif
     }
void dqm4hep::core::procStats (ProcessStats & stats)
Get stats from current process.
Parameters
object the ProcessStats object to receive
Definition at line 814 of file Internal.cc.
{
 #if defined(__APPLE__)
       darwinProcStats(stats);
 #elif defined(__linux__)
       linuxProcStats(stats);
 #elif defined(_WIN32)
       winProcStats(stats);
 #else
 #error "Unrecognized OS plateform (not windows, linux, OSX or unix) !"
 #endif
     }
std::string & dqm4hep::core::replaceAll (std::string & subject, const std::string & search, const std::string & replace)
Replaces all occurences in the spcified string.
Parameters
subject the string on which to perform replace
search the portion of the input string to search
replace the portion of string to replace with
Definition at line 73 of file Internal.cc.
Referenced by wildcardMatch().
{
       size_t pos = 0;
       while ((pos = subject.find(search, pos)) != std::string::npos) {
          subject.replace(pos, search.length(), replace);
          pos += replace.length();
       }
       return subject;
     }
void dqm4hep::core::screenSplash () inline
Screen splash of DQM4HEP.
Definition at line 374 of file Internal.h.
References dqm4hep::core::time::asString(), DQMCore_VERSION_STR, and dqm4hep::core::time::now().
{
       std::cout << "#######################################################" << std::endl;
       std::cout << "#" << std::endl;
       std::cout << "#                    DQM4HEP (DQMCore)" << std::endl;
       std::cout << "#   (Data Quality Monitoring For High Energy Physics)" << std::endl;
       std::cout << "#" << std::endl;
       std::cout << "#      Version    : " << DQMCore_VERSION_STR << std::endl;
       std::cout << "#      Started at : " << time::asString(time::now()) << std::endl;
       std::cout << "#      Author     : R. Ete, A. Pingault" << std::endl;
       std::cout << "#      Mail       : <dqm4hep@gmail.com> " << std::endl;
       std::cout << "#" << std::endl;
       std::cout << "#######################################################" << std::endl;
     }
void dqm4hep::core::sleep (const TimeDuration & duration)
Definition at line 97 of file Internal.cc.
{
       std::this_thread::sleep_for(duration);
     }
std::string dqm4hep::core::statusCodeToString (const StatusCode statusCode) inline
Definition at line 227 of file StatusCodes.h.
References GET_NAME_SWITCH, and STATUS_CODE_TABLE.
Referenced by dqm4hep::core::StatusCodeException::toString().
{
       switch (statusCode) {
         STATUS_CODE_TABLE(GET_NAME_SWITCH)
       default:
         throw dqm4hep::core::StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
       }
     }
template<class T > bool dqm4hep::core::stringToType (const std::string & s, T & t) inline
Convert std::string to a type.
Definition at line 336 of file Internal.h.
Referenced by dqm4hep::core::XMLParser::constantAs(), dqm4hep::core::TScalarXMLAllocator::create(), dqm4hep::core::XmlHelper::getAttribute(), dqm4hep::core::Run::parameter(), dqm4hep::core::XmlHelper::parseParameterElement(), dqm4hep::core::DBInterface::query(), dqm4hep::core::DBInterface::queryVector(), dqm4hep::core::XmlHelper::read2DVectorOfValues(), dqm4hep::core::XmlHelper::readParameter(), dqm4hep::core::XmlHelper::readParameters(), dqm4hep::core::XmlHelper::readValue(), dqm4hep::core::XmlHelper::readVectorOfValues(), dqm4hep::core::RootStyle::stringToColor(), and tokenize().
{
       std::istringstream iss(s);
       return !(iss >> t).fail();
     }
template<> bool dqm4hep::core::stringToType (const std::string & s, std::string & t) inline
Definition at line 358 of file Internal.h.
{
       t = s;
       return true;
     }
template<> bool dqm4hep::core::stringToType (const std::string & s, bool & t) inline
Specialization for booleans.
Definition at line 566 of file Internal.h.
{
       if (s == "on" || s == "1" || s == "true")
         t = true;
       else if (s == "off" || s == "0" || s == "false")
         t = false;
       else
         return false;
       return true;
     }
void dqm4hep::core::timeToHMS (std::time_t t, std::string & timeStr)
Definition at line 84 of file Internal.cc.
References dqm4hep::core::time::asPoint(), and dqm4hep::core::time::asString().
{
       timeStr = time::asString(time::asPoint(t));
     }
FILE * dqm4hep::core::TiXmlFOpen (const char * filename, const char * mode)
Definition at line 43 of file tinyxml.cc.
Referenced by dqm4hep::core::TiXmlDocument::LoadFile(), and dqm4hep::core::TiXmlDocument::SaveFile().
{
 #if defined(_MSC_VER) && (_MSC_VER >= 1400)
       FILE *fp = 0;
       errno_t err = fopen_s(&fp, filename, mode);
       if (!err && fp)
         return fp;
       return 0;
 #else
       return fopen(filename, mode);
 #endif
     }
template<typename T > void dqm4hep::core::tokenize (const std::string & inputString, std::vector< T > & tokens, const std::string & delimiter = " ") inline
Tokenize string with delimiter.
Definition at line 393 of file Internal.h.
References stringToType().
Referenced by dqm4hep::core::Path::getSplitPath(), dqm4hep::core::PluginManager::loadLibraries(), dqm4hep::core::XmlHelper::read2DVectorOfValues(), dqm4hep::core::GenericEventXMLReader::readNextEvent(), dqm4hep::core::XmlHelper::readParameters(), and dqm4hep::core::XmlHelper::readVectorOfValues().
{
       std::string::size_type lastPos = inputString.find_first_not_of(delimiter, 0);
       std::string::size_type pos = inputString.find_first_of(delimiter, lastPos);
       while ((std::string::npos != pos) || (std::string::npos != lastPos)) {
         T value;
         if(not stringToType(inputString.substr(lastPos, pos - lastPos), value)) {
           return;
         }
         tokens.push_back(value);
         lastPos = inputString.find_first_not_of(delimiter, pos);
         pos = inputString.find_first_of(delimiter, lastPos);
       }
     }
template<> void dqm4hep::core::tokenize (const std::string & inputString, StringVector & tokens, const std::string & delimiter) inline
Tokenize string with delimiter.
Definition at line 413 of file Internal.h.
{
       std::string::size_type lastPos = inputString.find_first_not_of(delimiter, 0);
       std::string::size_type pos = inputString.find_first_of(delimiter, lastPos);
       while ((std::string::npos != pos) || (std::string::npos != lastPos)) {
         tokens.push_back(inputString.substr(lastPos, pos - lastPos));
         lastPos = inputString.find_first_not_of(delimiter, pos);
         pos = inputString.find_first_of(delimiter, lastPos);
       }
     }
template<class T > std::string dqm4hep::core::typeToString (const T & t) inline
Convert type to std::string.
Definition at line 346 of file Internal.h.
Referenced by dqm4hep::core::ExactRefCompareTest::doGraph1DTest(), dqm4hep::core::ExactRefCompareTest::doGraph2DTest(), dqm4hep::core::ExactRefCompareTest::doHistogramTest(), dqm4hep::core::XMLParser::resolveForLoop(), dqm4hep::core::QualityTest::run(), and dqm4hep::core::PropertyWithinExpectedTest::userRun().
{
       std::ostringstream oss;
       if ((oss << t).fail())
         throw;
       return oss.str();
     }
template<> std::string dqm4hep::core::typeToString (const std::string & t) inline
Definition at line 366 of file Internal.h.
{
       return t;
     }
bool dqm4hep::core::wildcardMatch (const std::string & testString, const std::string & wildcardString, bool caseSensitive = true)
Whether the test string matches the wildcard expression.
Parameters
testString the string to test
wildcardString the string containing wildcards
Definition at line 47 of file Internal.cc.
References replaceAll().
{
       std::string wildcardPattern = wildcardString;
       replaceAll(wildcardPattern, "\\", "\\\\");
       replaceAll(wildcardPattern, "^", "\\^");
       replaceAll(wildcardPattern, ".", "\\.");
       replaceAll(wildcardPattern, "$", "\\$");
       replaceAll(wildcardPattern, "|", "\\|");
       replaceAll(wildcardPattern, "(", "\\(");
       replaceAll(wildcardPattern, ")", "\\)");
       replaceAll(wildcardPattern, "[", "\\[");
       replaceAll(wildcardPattern, "]", "\\]");
       replaceAll(wildcardPattern, "*", "\\*");
       replaceAll(wildcardPattern, "+", "\\+");
       replaceAll(wildcardPattern, "?", "\\?");
       replaceAll(wildcardPattern, "/", "\\/");
       // Convert chars '*?' back to their regex equivalents
       replaceAll(wildcardPattern, "\\?", ".");
       replaceAll(wildcardPattern, "\\*", ".*");
       // regex !
       auto flag = caseSensitive ? std::regex::ECMAScript : std::regex::ECMAScript | std::regex::icase;
       std::regex pattern(wildcardPattern, flag);
       return std::regex_match(testString, pattern);
     }
Variable Documentation
const TiXmlEncoding dqm4hep::core::TIXML_DEFAULT_ENCODING = TIXML_ENCODING_UNKNOWN
Definition at line 183 of file tinyxml.h.
const int dqm4hep::core::TIXML_MAJOR_VERSION = 2
Definition at line 99 of file tinyxml.h.
const int dqm4hep::core::TIXML_MINOR_VERSION = 6
Definition at line 100 of file tinyxml.h.
const int dqm4hep::core::TIXML_PATCH_VERSION = 1
Definition at line 101 of file tinyxml.h.
const unsigned char dqm4hep::core::TIXML_UTF_LEAD_0 = 0xefU
Definition at line 60 of file tinyxmlparser.cc.
Referenced by dqm4hep::core::TiXmlDocument::Parse(), dqm4hep::core::TiXmlDocument::SaveFile(), dqm4hep::core::TiXmlBase::SkipWhiteSpace(), and dqm4hep::core::TiXmlParsingData::Stamp().
const unsigned char dqm4hep::core::TIXML_UTF_LEAD_1 = 0xbbU
Definition at line 61 of file tinyxmlparser.cc.
Referenced by dqm4hep::core::TiXmlDocument::Parse(), dqm4hep::core::TiXmlDocument::SaveFile(), dqm4hep::core::TiXmlBase::SkipWhiteSpace(), and dqm4hep::core::TiXmlParsingData::Stamp().
const unsigned char dqm4hep::core::TIXML_UTF_LEAD_2 = 0xbfU
Definition at line 62 of file tinyxmlparser.cc.
Referenced by dqm4hep::core::TiXmlDocument::Parse(), dqm4hep::core::TiXmlDocument::SaveFile(), dqm4hep::core::TiXmlBase::SkipWhiteSpace(), and dqm4hep::core::TiXmlParsingData::Stamp().