DQMCore: nlohmann::detail::dtoa_impl::diyfp Struct Reference
nlohmann::detail::dtoa_impl::diyfp Struct Reference
#include <json.h>
Public Member Functions
constexpr diyfp () noexcept
constexpr diyfp (uint64_t f_, int e_) noexcept
Static Public Member Functions
static diyfp sub (const diyfp &x, const diyfp &y) noexcept
returns x - y
static diyfp mul (const diyfp &x, const diyfp &y) noexcept
returns x * y
static diyfp normalize (diyfp x) noexcept
normalize x such that the significand is >= 2^(q-1)
static diyfp normalize_to (const diyfp &x, const int target_exponent) noexcept
normalize x such that the result has the exponent E
Public Attributes
uint64_t f
int e
Static Public Attributes
static constexpr int kPrecision = 64
Detailed Description
Definition at line 6345 of file json.h.
Constructor & Destructor Documentation
constexpr nlohmann::detail::dtoa_impl::diyfp::diyfp () inline noexcept
Definition at line 6352 of file json.h.
Referenced by mul(), normalize_to(), and sub().
                                    : f(0), e(0) {
         }
constexpr nlohmann::detail::dtoa_impl::diyfp::diyfp (uint64_t f_, int e_) inline noexcept
Definition at line 6354 of file json.h.
                                                       : f(f_), e(e_) {
         }
Member Function Documentation
static diyfp nlohmann::detail::dtoa_impl::diyfp::mul (const diyfp & x, const diyfp & y) inline static noexcept
returns x * y
Note
The result is rounded. (Only the upper q bits are returned.)
Definition at line 6372 of file json.h.
References diyfp(), and kPrecision.
Referenced by nlohmann::detail::dtoa_impl::grisu2().
{
           static_assert(kPrecision == 64, "internal error");
           // Computes:
           //  f = round((x.f * y.f) / 2^q)
           //  e = x.e + y.e + q
           // Emulate the 64-bit * 64-bit multiplication:
           //
           // p = u * v
           //   = (u_lo + 2^32 u_hi) (v_lo + 2^32 v_hi)
           //   = (u_lo v_lo         ) + 2^32 ((u_lo v_hi         ) + (u_hi v_lo         )) + 2^64 (u_hi v_hi         )
           //   = (p0                ) + 2^32 ((p1                ) + (p2                )) + 2^64 (p3                )
           //   = (p0_lo + 2^32 p0_hi) + 2^32 ((p1_lo + 2^32 p1_hi) + (p2_lo + 2^32 p2_hi)) + 2^64 (p3                )
           //   = (p0_lo             ) + 2^32 (p0_hi + p1_lo + p2_lo                      ) + 2^64 (p1_hi + p2_hi + p3)
           //   = (p0_lo             ) + 2^32 (Q                                          ) + 2^64 (H                 )
           //   = (p0_lo             ) + 2^32 (Q_lo + 2^32 Q_hi                           ) + 2^64 (H                 )
           //
           // (Since Q might be larger than 2^32 - 1)
           //
           //   = (p0_lo + 2^32 Q_lo) + 2^64 (Q_hi + H)
           //
           // (Q_hi + H does not overflow a 64-bit int)
           //
           //   = p_lo + 2^64 p_hi
           const uint64_t u_lo = x.f & 0xFFFFFFFF;
           const uint64_t u_hi = x.f >> 32;
           const uint64_t v_lo = y.f & 0xFFFFFFFF;
           const uint64_t v_hi = y.f >> 32;
           const uint64_t p0 = u_lo * v_lo;
           const uint64_t p1 = u_lo * v_hi;
           const uint64_t p2 = u_hi * v_lo;
           const uint64_t p3 = u_hi * v_hi;
           const uint64_t p0_hi = p0 >> 32;
           const uint64_t p1_lo = p1 & 0xFFFFFFFF;
           const uint64_t p1_hi = p1 >> 32;
           const uint64_t p2_lo = p2 & 0xFFFFFFFF;
           const uint64_t p2_hi = p2 >> 32;
           uint64_t Q = p0_hi + p1_lo + p2_lo;
           // The full product might now be computed as
           //
           // p_hi = p3 + p2_hi + p1_hi + (Q >> 32)
           // p_lo = p0_lo + (Q << 32)
           //
           // But in this particular case here, the full p_lo is not required.
           // Effectively we only need to add the highest bit in p_lo to p_hi (and
           // Q_hi + 1 does not overflow).
           Q += uint64_t{1} << (64 - 32 - 1); // round, ties up
           const uint64_t h = p3 + p2_hi + p1_hi + (Q >> 32);
           return diyfp(h, x.e + y.e + 64);
         }
static diyfp nlohmann::detail::dtoa_impl::diyfp::normalize (diyfp x) inline static noexcept
normalize x such that the significand is >= 2^(q-1)
Precondition
x.f != 0
Definition at line 6436 of file json.h.
Referenced by nlohmann::detail::dtoa_impl::compute_boundaries().
{
           assert(x.f != 0);
           while ((x.f >> 63) == 0) {
             x.f <<= 1;
             x.e--;
           }
           return x;
         }
static diyfp nlohmann::detail::dtoa_impl::diyfp::normalize_to (const diyfp & x, const int target_exponent) inline static noexcept
normalize x such that the result has the exponent E
Precondition
e >= x.e and the upper e - x.e bits of x.f must be zero.
Definition at line 6451 of file json.h.
References diyfp(), and e.
Referenced by nlohmann::detail::dtoa_impl::compute_boundaries().
{
           const int delta = x.e - target_exponent;
           assert(delta >= 0);
           assert(((x.f << delta) >> delta) == x.f);
           return diyfp(x.f << delta, target_exponent);
         }
static diyfp nlohmann::detail::dtoa_impl::diyfp::sub (const diyfp & x, const diyfp & y) inline static noexcept
returns x - y
Precondition
x.e == y.e and x.f >= y.f
Definition at line 6361 of file json.h.
References diyfp().
Referenced by nlohmann::detail::dtoa_impl::grisu2_digit_gen().
{
           assert(x.e == y.e);
           assert(x.f >= y.f);
           return diyfp(x.f - y.f, x.e);
         }
Member Data Documentation
int nlohmann::detail::dtoa_impl::diyfp::e
Definition at line 6350 of file json.h.
Referenced by nlohmann::detail::dtoa_impl::compute_boundaries(), nlohmann::detail::dtoa_impl::grisu2(), nlohmann::detail::dtoa_impl::grisu2_digit_gen(), and normalize_to().
uint64_t nlohmann::detail::dtoa_impl::diyfp::f
Definition at line 6349 of file json.h.
Referenced by nlohmann::detail::dtoa_impl::compute_boundaries(), nlohmann::detail::dtoa_impl::grisu2(), and nlohmann::detail::dtoa_impl::grisu2_digit_gen().
constexpr int nlohmann::detail::dtoa_impl::diyfp::kPrecision = 64 static
Definition at line 6347 of file json.h.
Referenced by nlohmann::detail::dtoa_impl::grisu2(), and mul().
The documentation for this struct was generated from the following file:
json.h