DQM4hep: dqm4hep::core::GenericEventStreamer Class Reference
dqm4hep::core::GenericEventStreamer Class Reference
GenericEventStreamer class.
Public Member Functions
GenericEventStreamer ()
Constructor.
~GenericEventStreamer () override
Destructor.
EventPtr createEvent () const override
Factory method to create the corresponding event to this streamer.
StatusCode write (EventPtr event, TBuffer &buffer) override
Serialize the event and store it into a data stream.
StatusCode read (EventPtr event, TBuffer &buffer) override
De-serialize the event.
template<>
void writeMap (TBuffer &buffer, const std::map< std::string, std::vector< std::string >> &values)
template<>
void readMap (TBuffer &buffer, std::map< std::string, std::vector< std::string >> &values)
Public Member Functions inherited from dqm4hep::core::EventStreamerPlugin
virtual ~EventStreamerPlugin ()=default
Destructor.
Private Member Functions
template<typename T >
void writeMap (TBuffer &buffer, const std::map< std::string, std::vector< T >> &values)
template<typename T >
void readMap (TBuffer &buffer, std::map< std::string, std::vector< T >> &values)
Detailed Description
GenericEventStreamer class.
Definition at line 45 of file GenericEventStreamer.cc.
Constructor & Destructor Documentation
dqm4hep::core::GenericEventStreamer::GenericEventStreamer ()
Constructor.
Definition at line 136 of file GenericEventStreamer.cc.
{
       /* nop */
     }
dqm4hep::core::GenericEventStreamer::~GenericEventStreamer () override
Destructor.
Definition at line 142 of file GenericEventStreamer.cc.
{
       /* nop */
     }
Member Function Documentation
EventPtr dqm4hep::core::GenericEventStreamer::createEvent () const override virtual
Factory method to create the corresponding event to this streamer.
The event is expected to contains an allocated wrapped event
Implements dqm4hep::core::EventStreamerPlugin.
Definition at line 148 of file GenericEventStreamer.cc.
{
       return Event::create<GenericEvent>();
     }
StatusCode dqm4hep::core::GenericEventStreamer::read (EventPtr event, TBuffer & buffer) override virtual
De-serialize the event.
Implements dqm4hep::core::EventStreamerPlugin.
Definition at line 169 of file GenericEventStreamer.cc.
References dqm4hep::core::GenericEvent::m_doubleValues, dqm4hep::core::GenericEvent::m_floatValues, dqm4hep::core::GenericEvent::m_intValues, dqm4hep::core::GenericEvent::m_stringValues, and readMap().
{
       GenericEvent *pGenericEvent = event->getEvent<GenericEvent>();
       if (nullptr == pGenericEvent) {
         return STATUS_CODE_INVALID_PARAMETER;
       }
       // write event contents
       readMap(buffer, pGenericEvent->m_intValues);
       readMap(buffer, pGenericEvent->m_floatValues);
       readMap(buffer, pGenericEvent->m_doubleValues);
       readMap(buffer, pGenericEvent->m_stringValues);
       return STATUS_CODE_SUCCESS;
     }
template<typename T > void dqm4hep::core::GenericEventStreamer::readMap (TBuffer & buffer, std::map< std::string, std::vector< T >> & values) inline private
Definition at line 87 of file GenericEventStreamer.cc.
Referenced by read().
{
       Int_t size = 0;
       buffer.ReadInt(size);
       for(Int_t s=0 ; s<size ; s++) {
         std::string key;
         buffer.ReadStdString(&key);
         T *array = nullptr;
         Int_t size = buffer.ReadArray(array);
         std::vector<T> vecValues(array, array + sizeof(array) / sizeof(T));
         delete [] array;
         values[key] = vecValues;
       }
     }
template<> void dqm4hep::core::GenericEventStreamer::readMap (TBuffer & buffer, std::map< std::string, std::vector< std::string >> & values) inline
Definition at line 114 of file GenericEventStreamer.cc.
{
       Int_t size = 0;
       buffer.ReadInt(size);
       for(Int_t s=0 ; s<size ; s++) {
         std::string key;
         buffer.ReadStdString(&key);
         Int_t vecSize = 0;
         buffer.ReadInt(vecSize);
         std::vector<std::string> vecValues;
         vecValues.reserve(vecSize);
         for(Int_t s2=0 ; s2<vecSize ; s2++) {
           std::string value;
           buffer.ReadStdString(&value);
           vecValues.push_back(value);
         }
         values[key] = vecValues;
       }
     }
StatusCode dqm4hep::core::GenericEventStreamer::write (EventPtr event, TBuffer & buffer) override virtual
Serialize the event and store it into a data stream.
Implements dqm4hep::core::EventStreamerPlugin.
Definition at line 154 of file GenericEventStreamer.cc.
References dqm4hep::core::GenericEvent::m_doubleValues, dqm4hep::core::GenericEvent::m_floatValues, dqm4hep::core::GenericEvent::m_intValues, dqm4hep::core::GenericEvent::m_stringValues, and writeMap().
{
       const GenericEvent *pGenericEvent = event->getEvent<GenericEvent>();
       if (nullptr == pGenericEvent) {
         return STATUS_CODE_INVALID_PARAMETER;
       }
       // write event contents
       writeMap(buffer, pGenericEvent->m_intValues);
       writeMap(buffer, pGenericEvent->m_floatValues);
       writeMap(buffer, pGenericEvent->m_doubleValues);
       writeMap(buffer, pGenericEvent->m_stringValues);
       return STATUS_CODE_SUCCESS;
     }
template<typename T > void dqm4hep::core::GenericEventStreamer::writeMap (TBuffer & buffer, const std::map< std::string, std::vector< T >> & values) inline private
Definition at line 78 of file GenericEventStreamer.cc.
Referenced by write().
{
       buffer.WriteInt(values.size());
       for(auto elt : values) {
         buffer.WriteStdString(&elt.first);
         buffer.WriteArray(&elt.second[0], elt.second.size());
       }
     }
template<> void dqm4hep::core::GenericEventStreamer::writeMap (TBuffer & buffer, const std::map< std::string, std::vector< std::string >> & values) inline
Definition at line 102 of file GenericEventStreamer.cc.
{
       buffer.WriteInt(values.size());
       for(auto elt : values) {
         buffer.WriteStdString(&elt.first);
         buffer.WriteInt(elt.second.size());
         for(auto elt2 : elt.second) {
           buffer.WriteStdString(&elt2);
         }
       }
     }
The documentation for this class was generated from the following file:
GenericEventStreamer.cc