DQM4hep: dqm4hep::net::CommandHandler Class Reference
dqm4hep::net::CommandHandler Class Reference
#include <RequestHandler.h>
Classes
class Command
Command class.
Public Types
typedef core::Signal< const
Buffer & > CommandSignal
Public Member Functions
const std::string & name () const
Get the request name.
Server * server () const
Get the server in which the request handler is declared.
Private Member Functions
template<typename Controller >
CommandHandler (Server *pServer, const std::string &name, Controller *pController, void(Controller::*function)(const Buffer &command))
Constructor.
CommandHandler (const CommandHandler &)=delete
CommandHandler & operator= (const CommandHandler &)=delete
CommandHandler (Server *pServer, const std::string &name)
Constructor.
~CommandHandler ()
Destructor.
void startHandlingCommands ()
Create the actual request handler connection.
void stopHandlingCommands ()
Remove the actual request handler connection.
bool isHandlingCommands () const
Whether the request handler is connected.
CommandSignal & onCommand ()
[onRequest description]
void handleCommand (const Buffer &command)
[handleCommand description]
Private Attributes
std::string m_name = {""}
The command handler name.
Server * m_pServer = {nullptr}
The server in which the command handler is declared.
CommandSignal m_commandSignal = {}
Command * m_pCommand = {nullptr}
Friends
class Server
class Command
Detailed Description
Definition at line 143 of file RequestHandler.h.
Member Typedef Documentation
typedef core::Signal<const Buffer &> dqm4hep::net::CommandHandler::CommandSignal
Definition at line 147 of file RequestHandler.h.
Constructor & Destructor Documentation
template<typename Controller > dqm4hep::net::CommandHandler::CommandHandler (Server * pServer, const std::string & name, Controller * pController, void(Controller::*)(const Buffer &command) function) inline private
Constructor.
Parameters
pServer the server managing the request handler
name the request handler name
Definition at line 252 of file RequestHandler.h.
References dqm4hep::core::Signal< Args >::connect(), and m_commandSignal.
         : m_name(cname), m_pServer(pServer) {
       m_commandSignal.connect(pController, function);
     }
dqm4hep::net::CommandHandler::CommandHandler (const CommandHandler &) private delete
dqm4hep::net::CommandHandler::CommandHandler (Server * pServer, const std::string & name) private
Constructor.
Parameters
pServer the server managing the request handler
name the request handler name
Definition at line 94 of file RequestHandler.cc.
         : m_name(cname), m_pServer(pServer), m_pCommand(nullptr) {
     }
dqm4hep::net::CommandHandler::~CommandHandler () private
Destructor.
Definition at line 100 of file RequestHandler.cc.
References stopHandlingCommands().
{
       this->stopHandlingCommands();
     }
Member Function Documentation
void dqm4hep::net::CommandHandler::handleCommand (const Buffer & command) private
[handleCommand description]
Parameters
request [description]
response [description]
Definition at line 147 of file RequestHandler.cc.
References dqm4hep::core::Signal< Args >::emit(), and m_commandSignal.
{
       m_commandSignal.emit(command);
     }
bool dqm4hep::net::CommandHandler::isHandlingCommands () const private
Whether the request handler is connected.
Definition at line 135 of file RequestHandler.cc.
References m_pCommand.
Referenced by dqm4hep::net::Server::startCommandHandler(), startHandlingCommands(), dqm4hep::net::Server::stopCommandHandler(), and stopHandlingCommands().
{
       return (m_pCommand != nullptr);
     }
const std::string & dqm4hep::net::CommandHandler::name () const
Get the request name.
Definition at line 106 of file RequestHandler.cc.
References m_name.
{
       return m_name;
     }
CommandHandler::CommandSignal & dqm4hep::net::CommandHandler::onCommand () private
[onRequest description]
Returns
[description]
Definition at line 141 of file RequestHandler.cc.
References m_commandSignal.
{
       return m_commandSignal;
     }
CommandHandler& dqm4hep::net::CommandHandler::operator= (const CommandHandler &) private delete
Server * dqm4hep::net::CommandHandler::server () const
Get the server in which the request handler is declared.
Definition at line 112 of file RequestHandler.cc.
References m_pServer.
{
       return m_pServer;
     }
void dqm4hep::net::CommandHandler::startHandlingCommands () private
Create the actual request handler connection.
Definition at line 118 of file RequestHandler.cc.
References Command, isHandlingCommands(), and m_pCommand.
Referenced by dqm4hep::net::Server::createCommandHandler(), and dqm4hep::net::Server::startCommandHandler().
{
       if (!this->isHandlingCommands()) {
         m_pCommand = new Command(this);
       }
     }
void dqm4hep::net::CommandHandler::stopHandlingCommands () private
Remove the actual request handler connection.
Definition at line 126 of file RequestHandler.cc.
References isHandlingCommands(), and m_pCommand.
Referenced by dqm4hep::net::Server::stopCommandHandler(), and ~CommandHandler().
{
       if (this->isHandlingCommands()) {
         delete m_pCommand;
         m_pCommand = nullptr;
       }
     }
Friends And Related Function Documentation
friend class Command friend
Definition at line 230 of file RequestHandler.h.
Referenced by startHandlingCommands().
friend class Server friend
Definition at line 144 of file RequestHandler.h.
Member Data Documentation
CommandSignal dqm4hep::net::CommandHandler::m_commandSignal = {} private
Definition at line 243 of file RequestHandler.h.
Referenced by CommandHandler(), handleCommand(), and onCommand().
std::string dqm4hep::net::CommandHandler::m_name = {""} private
The command handler name.
Definition at line 241 of file RequestHandler.h.
Referenced by name().
Command* dqm4hep::net::CommandHandler::m_pCommand = {nullptr} private
Definition at line 244 of file RequestHandler.h.
Referenced by isHandlingCommands(), startHandlingCommands(), and stopHandlingCommands().
Server* dqm4hep::net::CommandHandler::m_pServer = {nullptr} private
The server in which the command handler is declared.
Definition at line 242 of file RequestHandler.h.
Referenced by server().
The documentation for this class was generated from the following files:
RequestHandler.h
RequestHandler.cc