DQM4hep: dqm4hep::net::Server Class Reference
dqm4hep::net::Server Class Reference
Server class.
#include <Server.h>
Public Member Functions
Server (const std::string &name)
Constructor.
Server ()=delete
Server (const Server &)=delete
Server & operator= (const Server &)=delete
~Server () override
Destructor.
const std::string & name () const
Get the server name.
void start ()
Start serving services and handling requests.
void stop ()
Stop serving services and handling requests.
bool isRunning () const
Whether the server is running.
void clear ()
Close all service and request handlers.
Service * createService (const std::string &name)
Create a new service.
template<typename Controller >
void createRequestHandler (const std::string &name, Controller *pController, void(Controller::*function)(const Buffer &request, Buffer &response))
Create a new request handler.
template<typename Controller >
void createCommandHandler (const std::string &name, Controller *pController, void(Controller::*function)(const Buffer &command))
Create a new command handler.
bool isServiceRegistered (const std::string &name) const
Whether the target service is registered in this server.
bool isRequestHandlerRegistered (const std::string &name) const
Whether the request handler is registered in this server.
bool isCommandHandlerRegistered (const std::string &name) const
Whether the command handler is registered in this server.
void startService (const std::string &name)
Start a target service.
void stopService (const std::string &name)
Stop a target service.
void startRequestHandler (const std::string &name)
Start a target request handler.
void stopRequestHandler (const std::string &name)
Stop a target request handler.
void startCommandHandler (const std::string &name)
Start a target request handler.
void stopCommandHandler (const std::string &name)
Stop a target command handler.
template<typename Controller >
void stopCommandHandler (const std::string &name, Controller *pController)
Stop a specific command handler.
template<typename Controller >
void stopCommandHandler (const std::string &name, Controller *pController, void(Controller::*function)(const Buffer &command))
Stop a specific command handler.
Service * service (const std::string &name) const
Get a created service in this server.
core::Signal< int > & onClientExit ()
Get the signal processed on client exit.
int clientId () const
Get the client id.
Static Public Member Functions
static std::string dnsNode ()
Get the dim dns node.
static int dnsPort ()
Get the dim dns port.
static std::vector< std::string > runningServers ()
Get the list of running servers.
static bool isServerRunning (const std::string &serverName)
Whether the target server is already running on the network.
static bool serviceAlreadyRunning (const std::string &name)
Whether the service is already running on the network.
static bool requestHandlerAlreadyRunning (const std::string &name)
Whether the request handler is already running on the network.
static bool commandHandlerAlreadyRunning (const std::string &name)
Whether the command handler is already running on the network.
Private Types
typedef std::map< std::string,
Service * > ServiceMap
typedef std::map< std::string,
RequestHandler * > RequestHandlerMap
typedef std::map< std::string,
CommandHandler * > CommandHandlerMap
Private Member Functions
void handleServerInfoRequest (const Buffer &, Buffer &response)
RequestHandler * requestHandler (const std::string &name) const
CommandHandler * commandHandler (const std::string &name) const
void clientExitHandler () override
void commandHandler () override
Private Attributes
std::string m_name = {""}
The short server name.
bool m_started = {false}
Whether the server has been started.
ServiceMap m_serviceMap = {}
The map of registered services.
RequestHandlerMap m_requestHandlerMap = {}
The map of registered request handlers.
CommandHandlerMap m_commandHandlerMap = {}
The map of registered command handlers.
RequestHandler * m_serverInfoHandler = {nullptr}
The built-in request handler for server info.
core::Signal< int > m_clientExitSignal = {}
The signal emitted whenever a client exits.
Detailed Description
Server class.
Main interface for service and request handler registration. User can create services using the createService() method. Request from client side can be handled by registering a request handler by providing a class method to handle the request and fill a reponse.
All created services and request handlers are started after server startup.
Definition at line 39 of file Server.h.
Member Typedef Documentation
typedef std::map<std::string, CommandHandler *> dqm4hep::net::Server::CommandHandlerMap private
Definition at line 266 of file Server.h.
typedef std::map<std::string, RequestHandler *> dqm4hep::net::Server::RequestHandlerMap private
Definition at line 265 of file Server.h.
typedef std::map<std::string, Service *> dqm4hep::net::Server::ServiceMap private
Definition at line 261 of file Server.h.
Constructor & Destructor Documentation
dqm4hep::net::Server::Server (const std::string & name)
Constructor.
Parameters
name the server name
Definition at line 27 of file Server.cc.
References handleServerInfoRequest(), m_name, and m_serverInfoHandler.
         : m_name(sname),
           m_started(false) {
       DimServer::addClientExitHandler(this);
       m_serverInfoHandler = new RequestHandler(this, "/" + m_name + "/info", this, &Server::handleServerInfoRequest);
     }
dqm4hep::net::Server::Server () delete
dqm4hep::net::Server::Server (const Server &) delete
dqm4hep::net::Server::~Server () override
Destructor.
Definition at line 36 of file Server.cc.
References clear(), m_serverInfoHandler, and stop().
                     {
       this->stop();
       this->clear();
       delete m_serverInfoHandler;
     }
Member Function Documentation
void dqm4hep::net::Server::clear ()
Close all service and request handlers.
Called from destructor
Definition at line 113 of file Server.cc.
References m_commandHandlerMap, m_requestHandlerMap, m_serviceMap, and m_started.
Referenced by ~Server().
{
       for (auto iter = m_serviceMap.begin(), endIter = m_serviceMap.end(); endIter != iter; ++iter)
         delete iter->second;
       for (auto iter = m_requestHandlerMap.begin(), endIter = m_requestHandlerMap.end(); endIter != iter; ++iter)
         delete iter->second;
       for (auto iter = m_commandHandlerMap.begin(), endIter = m_commandHandlerMap.end(); endIter != iter; ++iter)
         delete iter->second;
       m_serviceMap.clear();
       m_requestHandlerMap.clear();
       m_commandHandlerMap.clear();
       DimServer::stop();
       m_started = false;
     }
void dqm4hep::net::Server::clientExitHandler () override private
Definition at line 439 of file Server.cc.
References dqm4hep::core::Signal< Args >::emit(), and m_clientExitSignal.
{
       int clientID(DimServer::getClientId());
       std::cout << "Client " << clientID << " exits" << std::endl;
       m_clientExitSignal.emit(clientID);
     }
int dqm4hep::net::Server::clientId () const
Get the client id.
To be used inside callbacks
Definition at line 260 of file Server.cc.
{
       return DimServer::getClientId();
     }
CommandHandler * dqm4hep::net::Server::commandHandler (const std::string & name) const private
Definition at line 247 of file Server.cc.
References m_commandHandlerMap.
{
       auto findIter = m_commandHandlerMap.find(cname);
       return (findIter == m_commandHandlerMap.end() ? nullptr : findIter->second);
     }
void dqm4hep::net::Server::commandHandler () inline override private
Definition at line 261 of file Server.h.
Referenced by startCommandHandler(), and stopCommandHandler().
 {};
bool dqm4hep::net::Server::commandHandlerAlreadyRunning (const std::string & name) static
Whether the command handler is already running on the network.
Parameters
name the command handler name
Definition at line 410 of file Server.cc.
References dqm_warning.
Referenced by createCommandHandler().
{
       if(DimServer::inCallback()) {
         dqm_warning( "Server::commandHandlerAlreadyRunning: can't check for duplicated command on network !" );
         return false;
       }
       DimBrowser browser;
       int nServices = browser.getServices(cname.c_str());
       if (nServices == 0)
         return false;
       int serviceType;
       char *serviceName, *format;
       while (1) {
         serviceType = browser.getNextService(serviceName, format);
         if (serviceType == 0)
           break;
         if (serviceType == DimCOMMAND)
           return true;
       }
       return false;
     }
template<typename Controller > void dqm4hep::net::Server::createCommandHandler (const std::string & name, Controller * pController, void(Controller::*)(const Buffer &command) function) inline
Create a new command handler.
Parameters
name the command handler name
pController the class instance that will handle the command
function the class method that will treat the command
Definition at line 310 of file Server.h.
References commandHandlerAlreadyRunning(), isRunning(), m_commandHandlerMap, and dqm4hep::net::CommandHandler::startHandlingCommands().
{
       auto findIter = m_commandHandlerMap.find(cname);
       if (findIter != m_commandHandlerMap.end()) {
         findIter->second->onCommand().connect(pController, function);
         if (this->isRunning())
           findIter->second->startHandlingCommands();
         return;
       }
       if (Server::commandHandlerAlreadyRunning(cname))
         throw std::runtime_error("Server::createCommandHandler(): command handler '" + cname +
                                  "' already running on network");
       // first insert nullptr, then create command handler
       auto inserted = m_commandHandlerMap.insert(CommandHandlerMap::value_type(cname, nullptr));
       if (inserted.second) {
         CommandHandler *pCommandHandler = new CommandHandler(this, cname, pController, function);
         inserted.first->second = pCommandHandler;
         if (this->isRunning())
           pCommandHandler->startHandlingCommands();
       } else
         throw;
     }
template<typename Controller > void dqm4hep::net::Server::createRequestHandler (const std::string & name, Controller * pController, void(Controller::*)(const Buffer &request, Buffer &response) function) inline
Create a new request handler.
Parameters
name the request handler name
pController the class instance that will handle the request
function the class method that will treat the request and provide a response
Definition at line 282 of file Server.h.
References isRunning(), m_requestHandlerMap, requestHandlerAlreadyRunning(), and dqm4hep::net::RequestHandler::startHandlingRequest().
{
       auto findIter = m_requestHandlerMap.find(rname);
       if (findIter != m_requestHandlerMap.end())
         throw std::runtime_error("Server::createRequestHandler(): request handler '" + rname +
                                  "' already exists in this client");
       if (Server::requestHandlerAlreadyRunning(rname))
         throw std::runtime_error("Server::createRequestHandler(): request handler '" + rname +
                                  "' already running on network");
       // first insert nullptr, then create request handler
       auto inserted = m_requestHandlerMap.insert(RequestHandlerMap::value_type(rname, nullptr));
       if (inserted.second) {
         RequestHandler *pRequestHandler = new RequestHandler(this, rname, pController, function);
         inserted.first->second = pRequestHandler;
         if (this->isRunning())
           pRequestHandler->startHandlingRequest();
       } else
         throw;
     }
Service * dqm4hep::net::Server::createService (const std::string & name)
Create a new service.
Parameters
name the service name
Definition at line 132 of file Server.cc.
References dqm4hep::net::Service::connectService(), isRunning(), m_serviceMap, and serviceAlreadyRunning().
{
       if (sname.empty())
         throw std::runtime_error("Server::createService(): service name is invalid");
       auto findIter = m_serviceMap.find(sname);
       if (findIter != m_serviceMap.end())
         return findIter->second;
       if (Server::serviceAlreadyRunning(sname))
         throw std::runtime_error("Server::createService(): service '" + sname + "' already running on network");
       // first insert nullptr, then create the service
       std::pair<ServiceMap::iterator, bool> inserted = m_serviceMap.insert(ServiceMap::value_type(sname, nullptr));
       if (inserted.second) {
         Service *pService = new Service(this, sname);
         inserted.first->second = pService;
         if (this->isRunning())
           pService->connectService();
         return pService;
       } else
         throw;
     }
std::string dqm4hep::net::Server::dnsNode () static
Get the dim dns node.
First look at DimServer::getDnsNode() then environment variable "DIM_DNS_NODE"
Definition at line 266 of file Server.cc.
{
       char *pDnsNode = DimServer::getDnsNode();
       if (pDnsNode)
         return pDnsNode;
       pDnsNode = getenv("DIM_DNS_NODE");
       return (pDnsNode ? pDnsNode : "");
     }
int dqm4hep::net::Server::dnsPort () static
Get the dim dns port.
Definition at line 278 of file Server.cc.
{
       return DimServer::getDnsPort();
     }
void dqm4hep::net::Server::handleServerInfoRequest (const Buffer & , Buffer & response) private
Definition at line 318 of file Server.cc.
References dqm4hep::net::Buffer::createModel(), dqm4hep::core::fillHostInfo(), m_commandHandlerMap, m_name, m_requestHandlerMap, m_serviceMap, and dqm4hep::net::Buffer::setModel().
Referenced by Server().
{
       // get the list of services, request handlers and command handlers
       core::StringVector serviceList, requestHandlerList, commandHandlerList;
       for (auto pservice : m_serviceMap) {
         serviceList.push_back(pservice.second->name());
       }
       for (auto request : m_requestHandlerMap) {
         requestHandlerList.push_back(request.second->name());
       }
       for (auto command : m_commandHandlerMap) {
         commandHandlerList.push_back(command.second->name());
       }
       // get host info
       core::StringMap hostInfo;
       core::fillHostInfo(hostInfo);
       core::json jsonResponse = {{"server", {{"name", m_name}}},
                                  {"host", hostInfo},
                                  {"services", serviceList},
                                  {"requestHandlers", requestHandlerList},
                                  {"commandHandlers", commandHandlerList}};
       std::string serializedJson = jsonResponse.dump();
       auto model = response.createModel<std::string>();
       response.setModel(model);
       model->move(std::move(serializedJson));
     }
bool dqm4hep::net::Server::isCommandHandlerRegistered (const std::string & name) const
Whether the command handler is registered in this server.
Parameters
name the command handler name
Definition at line 173 of file Server.cc.
References m_commandHandlerMap.
{
       return (m_commandHandlerMap.find(cname) != m_commandHandlerMap.end());
     }
bool dqm4hep::net::Server::isRequestHandlerRegistered (const std::string & name) const
Whether the request handler is registered in this server.
Parameters
name the request handler name
Definition at line 167 of file Server.cc.
References m_requestHandlerMap.
{
       return (m_requestHandlerMap.find(rname) != m_requestHandlerMap.end());
     }
bool dqm4hep::net::Server::isRunning () const
Whether the server is running.
Definition at line 107 of file Server.cc.
References m_started.
Referenced by createCommandHandler(), createRequestHandler(), and createService().
{
       return m_started;
     }
bool dqm4hep::net::Server::isServerRunning (const std::string & serverName) static
Whether the target server is already running on the network.
Parameters
serverName the 'short' server name
Definition at line 301 of file Server.cc.
Referenced by dqm4hep::online::EventSource::sendEvent().
{
       DimBrowser browser;
       browser.getServers();
       char *pServer, *pNode;
       while (browser.getNextServer(pServer, pNode)) {
         std::string server(pServer);
         if (server == serverName)
           return true;
       }
       return false;
     }
bool dqm4hep::net::Server::isServiceRegistered (const std::string & name) const
Whether the target service is registered in this server.
Parameters
name the service name
Definition at line 161 of file Server.cc.
References m_serviceMap.
{
       return (m_serviceMap.find(sname) != m_serviceMap.end());
     }
const std::string & dqm4hep::net::Server::name () const
Get the server name.
Definition at line 44 of file Server.cc.
References m_name.
{
       return m_name;
     }
core::Signal< int > & dqm4hep::net::Server::onClientExit ()
Get the signal processed on client exit.
Definition at line 254 of file Server.cc.
References m_clientExitSignal.
{
       return m_clientExitSignal;
     }
Server& dqm4hep::net::Server::operator= (const Server &) delete
RequestHandler * dqm4hep::net::Server::requestHandler (const std::string & name) const private
Definition at line 240 of file Server.cc.
References m_requestHandlerMap.
Referenced by startRequestHandler(), and stopRequestHandler().
{
       auto findIter = m_requestHandlerMap.find(rname);
       return (findIter == m_requestHandlerMap.end() ? nullptr : findIter->second);
     }
bool dqm4hep::net::Server::requestHandlerAlreadyRunning (const std::string & name) static
Whether the request handler is already running on the network.
Parameters
name the request handler name
Definition at line 381 of file Server.cc.
References dqm_warning.
Referenced by createRequestHandler().
{
       if(DimServer::inCallback()) {
         dqm_warning( "Server::requestHandlerAlreadyRunning: can't check for duplicated request handler on network !" );
         return false;
       }
       DimBrowser browser;
       int nServices = browser.getServices(rname.c_str());
       if (nServices == 0)
         return false;
       int serviceType;
       char *serviceName, *format;
       while (1) {
         serviceType = browser.getNextService(serviceName, format);
         if (serviceType == 0)
           break;
         if (serviceType == DimRPC)
           return true;
       }
       return false;
     }
std::vector< std::string > dqm4hep::net::Server::runningServers () static
Get the list of running servers.
Definition at line 284 of file Server.cc.
{
       std::vector<std::string> runningServers;
       DimBrowser browser;
       browser.getServers();
       char *pServer, *pNode;
       while (browser.getNextServer(pServer, pNode)) {
         std::string server(pServer);
         runningServers.push_back(server);
       }
       return runningServers;
     }
Service * dqm4hep::net::Server::service (const std::string & name) const
Get a created service in this server.
Parameters
name the service name
Definition at line 233 of file Server.cc.
References m_serviceMap.
Referenced by startService(), and stopService().
{
       auto findIter = m_serviceMap.find(sname);
       return (findIter == m_serviceMap.end() ? nullptr : findIter->second);
     }
bool dqm4hep::net::Server::serviceAlreadyRunning (const std::string & name) static
Whether the service is already running on the network.
Parameters
name the service name
Definition at line 352 of file Server.cc.
References dqm_warning.
Referenced by createService().
{
       if(DimServer::inCallback()) {
         dqm_warning( "Server::serviceAlreadyRunning: can't check for duplicated service on network !" );
         return false;
       }
       DimBrowser browser;
       int nServices = browser.getServices(sname.c_str());
       if (nServices == 0)
         return false;
       int serviceType;
       char *serviceName, *format;
       while (1) {
         serviceType = browser.getNextService(serviceName, format);
         if (serviceType == 0)
           break;
         if (serviceType == DimSERVICE)
           return true;
       }
       return false;
     }
void dqm4hep::net::Server::start ()
Start serving services and handling requests.
Definition at line 50 of file Server.cc.
References dqm4hep::net::RequestHandler::isHandlingRequest(), m_commandHandlerMap, m_name, m_requestHandlerMap, m_serverInfoHandler, m_serviceMap, m_started, and dqm4hep::net::RequestHandler::startHandlingRequest().
{
       if (m_started)
         return;
       for (auto iter = m_serviceMap.begin(), endIter = m_serviceMap.end(); endIter != iter; ++iter) {
         if (!iter->second->isServiceConnected())
           iter->second->connectService();
       }
       for (auto iter = m_requestHandlerMap.begin(), endIter = m_requestHandlerMap.end(); endIter != iter; ++iter) {
         if (!iter->second->isHandlingRequest())
           iter->second->startHandlingRequest();
       }
       for (auto iter = m_commandHandlerMap.begin(), endIter = m_commandHandlerMap.end(); endIter != iter; ++iter) {
         if (!iter->second->isHandlingCommands())
           iter->second->startHandlingCommands();
       }
       if (!m_serverInfoHandler->isHandlingRequest())
         m_serverInfoHandler->startHandlingRequest();
       DimServer::start(const_cast<char *>(m_name.c_str()));
       m_started = true;
     }
void dqm4hep::net::Server::startCommandHandler (const std::string & name)
Start a target request handler.
Parameters
name the command name
Definition at line 215 of file Server.cc.
References commandHandler(), dqm4hep::net::CommandHandler::isHandlingCommands(), and dqm4hep::net::CommandHandler::startHandlingCommands().
{
       CommandHandler *pCommandHandler = this->commandHandler(cname);
       if (nullptr != pCommandHandler && !pCommandHandler->isHandlingCommands())
         pCommandHandler->startHandlingCommands();
     }
void dqm4hep::net::Server::startRequestHandler (const std::string & name)
Start a target request handler.
Parameters
name the request handler name
Definition at line 197 of file Server.cc.
References dqm4hep::net::RequestHandler::isHandlingRequest(), requestHandler(), and dqm4hep::net::RequestHandler::startHandlingRequest().
{
       RequestHandler *pRequestHandler = this->requestHandler(rname);
       if (nullptr != pRequestHandler && !pRequestHandler->isHandlingRequest())
         pRequestHandler->startHandlingRequest();
     }
void dqm4hep::net::Server::startService (const std::string & name)
Start a target service.
Parameters
name the service name
Definition at line 179 of file Server.cc.
References dqm4hep::net::Service::connectService(), dqm4hep::net::Service::isServiceConnected(), and service().
{
       Service *pService = this->service(sname);
       if (nullptr != pService && !pService->isServiceConnected())
         pService->connectService();
     }
void dqm4hep::net::Server::stop ()
Stop serving services and handling requests.
Definition at line 79 of file Server.cc.
References dqm4hep::net::RequestHandler::isHandlingRequest(), m_commandHandlerMap, m_requestHandlerMap, m_serverInfoHandler, m_serviceMap, m_started, and dqm4hep::net::RequestHandler::stopHandlingRequest().
Referenced by ~Server().
                       {
       if (!m_started)
         return;
       for (auto iter = m_serviceMap.begin(), endIter = m_serviceMap.end(); endIter != iter; ++iter) {
         if (iter->second->isServiceConnected())
           iter->second->disconnectService();
       }
       for (auto iter = m_requestHandlerMap.begin(), endIter = m_requestHandlerMap.end(); endIter != iter; ++iter) {
         if (iter->second->isHandlingRequest())
           iter->second->stopHandlingRequest();
       }
       for (auto iter = m_commandHandlerMap.begin(), endIter = m_commandHandlerMap.end(); endIter != iter; ++iter) {
         if (iter->second->isHandlingCommands())
           iter->second->stopHandlingCommands();
       }
       if (m_serverInfoHandler->isHandlingRequest())
         m_serverInfoHandler->stopHandlingRequest();
       DimServer::stop();
       m_started = false;
     }
void dqm4hep::net::Server::stopCommandHandler (const std::string & name)
Stop a target command handler.
Parameters
name the command handler name
Definition at line 224 of file Server.cc.
References commandHandler(), dqm4hep::net::CommandHandler::isHandlingCommands(), and dqm4hep::net::CommandHandler::stopHandlingCommands().
{
       CommandHandler *pCommandHandler = this->commandHandler(cname);
       if (nullptr != pCommandHandler && pCommandHandler->isHandlingCommands())
         pCommandHandler->stopHandlingCommands();
     }
template<typename Controller > void dqm4hep::net::Server::stopCommandHandler (const std::string & name, Controller * pController) inline
Stop a specific command handler.
Parameters
name the command handler name
pController the command handler controller
Definition at line 343 of file Server.h.
References m_commandHandlerMap.
{
       auto findIter = m_commandHandlerMap.find(cname);
       if (findIter != m_commandHandlerMap.end()) {
         findIter->second->onCommand().disconnect(pController);
         if (!findIter->second->onCommand().hasConnection())
           m_commandHandlerMap.erase(findIter);
       }
     }
template<typename Controller > void dqm4hep::net::Server::stopCommandHandler (const std::string & name, Controller * pController, void(Controller::*)(const Buffer &command) function) inline
Stop a specific command handler.
Parameters
name the command handler name
pController the command handler controller
function the command handler function
Definition at line 357 of file Server.h.
References m_commandHandlerMap.
{
       auto findIter = m_commandHandlerMap.find(cname);
       if (findIter != m_commandHandlerMap.end()) {
         findIter->second->onCommand().disconnect(pController, function);
         if (!findIter->second->onCommand().hasConnection())
           m_commandHandlerMap.erase(findIter);
       }
     }
void dqm4hep::net::Server::stopRequestHandler (const std::string & name)
Stop a target request handler.
Parameters
name the request handler name
Definition at line 206 of file Server.cc.
References dqm4hep::net::RequestHandler::isHandlingRequest(), requestHandler(), and dqm4hep::net::RequestHandler::stopHandlingRequest().
{
       RequestHandler *pRequestHandler = this->requestHandler(rname);
       if (nullptr != pRequestHandler && pRequestHandler->isHandlingRequest())
         pRequestHandler->stopHandlingRequest();
     }
void dqm4hep::net::Server::stopService (const std::string & name)
Stop a target service.
Parameters
name the service name
Definition at line 188 of file Server.cc.
References dqm4hep::net::Service::disconnectService(), dqm4hep::net::Service::isServiceConnected(), and service().
{
       Service *pService = this->service(sname);
       if (nullptr != pService && pService->isServiceConnected())
         pService->disconnectService();
     }
Member Data Documentation
core::Signal<int> dqm4hep::net::Server::m_clientExitSignal = {} private
The signal emitted whenever a client exits.
Definition at line 274 of file Server.h.
Referenced by clientExitHandler(), and onClientExit().
CommandHandlerMap dqm4hep::net::Server::m_commandHandlerMap = {} private
The map of registered command handlers.
Definition at line 272 of file Server.h.
Referenced by clear(), commandHandler(), createCommandHandler(), handleServerInfoRequest(), isCommandHandlerRegistered(), start(), stop(), and stopCommandHandler().
std::string dqm4hep::net::Server::m_name = {""} private
The short server name.
Definition at line 268 of file Server.h.
Referenced by handleServerInfoRequest(), name(), Server(), and start().
RequestHandlerMap dqm4hep::net::Server::m_requestHandlerMap = {} private
The map of registered request handlers.
Definition at line 271 of file Server.h.
Referenced by clear(), createRequestHandler(), handleServerInfoRequest(), isRequestHandlerRegistered(), requestHandler(), start(), and stop().
RequestHandler* dqm4hep::net::Server::m_serverInfoHandler = {nullptr} private
The built-in request handler for server info.
Definition at line 273 of file Server.h.
Referenced by Server(), start(), stop(), and ~Server().
ServiceMap dqm4hep::net::Server::m_serviceMap = {} private
The map of registered services.
Definition at line 270 of file Server.h.
Referenced by clear(), createService(), handleServerInfoRequest(), isServiceRegistered(), service(), start(), and stop().
bool dqm4hep::net::Server::m_started = {false} private
Whether the server has been started.
Definition at line 269 of file Server.h.
Referenced by clear(), isRunning(), start(), and stop().
The documentation for this class was generated from the following files:
Server.h
Server.cc