DQM4hep: dqm4hep::online::Cycle Class Reference
dqm4hep::online::Cycle Class Reference
Cycle class.
#include <Cycle.h>
Public Member Functions
Cycle (AppEventLoop &loop)
Constructor.
~Cycle ()
Destructor.
unsigned int timeout () const
Get the timeout value (unit seconds)
void setTimeout (unsigned int value)
Set the cycle timeout value (unit seconds)
unsigned int timerPeriod () const
Get the timer period value (unit seconds)
void setTimerPeriod (unsigned int value)
Set the cycle timer period value (unit seconds)
void setCounterLimit (unsigned int value)
Set the couting limit.
unsigned int counterLimit () const
Get the couting limit.
void setEventPriority (int priority)
Set the EndOfCycleEvent event priority.
int eventPriority () const
Get the EndOfCycleEvent event priority.
void incrementCounter (unsigned int increment=1)
Increment the counter by a value.
void startCycle (bool emit=false)
Start a new cycle Stop the current cycle if running.
void forceStopCycle (bool waitEnd=true, bool emit=false)
Stop the current cycle if running.
bool running () const
Whether the cycle is running.
Private Member Functions
void cycleLoop ()
The main cycle loop thread.
void endOfCycle (EOCCondition &condition)
Called at end of cycle.
Private Attributes
AppEventLoop & m_eventLoop
The application event loop in which the cycle is running.
std::atomic_bool m_running = {false}
Whether a cycle has been started.
std::atomic_bool m_startCycleFlag = {false}
An internal flag to trigger a new cycle.
std::atomic_bool m_forceStopFlag = {false}
An internal flag to trigger an end of cycle.
std::atomic_bool m_eocEmit = {true}
Whether an event has to be posted on end of cycle.
std::atomic_bool m_stopFlag = {false}
An internal flag to stop the cycle thread.
std::thread m_thread = {}
The thread object running the cycle function.
std::atomic_uint m_timeout = {10}
The user timeout value, default 10 (unit seconds)
std::atomic_uint m_period = {30}
The user timer period, default 30 (unit seconds)
std::atomic_uint m_counterLimit = {0}
The user counter limit.
std::atomic_uint m_currentCounter = {0}
The internal counter incremented by user.
std::atomic_int m_eventPriority = {60}
The end of cycle event priority in the event loop.
core::time::point m_lastCounterIncrement = {}
The last time point when the increement method was called.
Detailed Description
Cycle class.
Process a cycle of processEvent(evt) call for a AnalysisModule. See implementation for cycle types.
The cycle value is the value for which the cycle should normally ends.
The timeout value is the maximum time between two processEvent(evt) call When the timeout is reached, the cycle ends. The default timeout value is 10 seconds and can be changed via the method setTimeout(secs)
Definition at line 62 of file Cycle.h.
Constructor & Destructor Documentation
dqm4hep::online::Cycle::Cycle (AppEventLoop & loop)
Constructor.
Parameters
loop the application event loop
Definition at line 29 of file Cycle.cc.
References cycleLoop(), and m_thread.
                                    :
       m_eventLoop(loop) {
       m_thread = std::thread(&Cycle::cycleLoop, this);
     }
dqm4hep::online::Cycle::~Cycle ()
Destructor.
Definition at line 36 of file Cycle.cc.
References m_stopFlag, and m_thread.
                   {
       m_stopFlag = true;
       m_thread.join();
     }
Member Function Documentation
unsigned int dqm4hep::online::Cycle::counterLimit () const
Get the couting limit.
Definition at line 67 of file Cycle.cc.
References m_counterLimit.
{
       return m_counterLimit.load();
     }
void dqm4hep::online::Cycle::cycleLoop () private
The main cycle loop thread.
Definition at line 132 of file Cycle.cc.
References endOfCycle(), m_counterLimit, m_currentCounter, m_eocEmit, dqm4hep::online::EOCCondition::m_forcedEnd, m_forceStopFlag, m_lastCounterIncrement, m_period, m_running, m_startCycleFlag, dqm4hep::online::EOCCondition::m_startTime, m_stopFlag, m_timeout, dqm4hep::online::EOCCondition::m_timeoutReached, and dqm4hep::core::time::now().
Referenced by Cycle().
{
       while(1) {
         if(m_stopFlag.load()) {
           break;
         }
         if(not m_startCycleFlag.load()) {
           usleep(10000);
           continue;
         }
         // start of cycle here
         m_running = true;
         m_forceStopFlag = false;
         m_eocEmit = true;
         EOCCondition condition;
         condition.m_startTime = core::time::now();
         condition.m_forcedEnd = false;
         m_lastCounterIncrement = condition.m_startTime;
         m_currentCounter = 0;
         while(1) {
           if(m_stopFlag.load() or m_forceStopFlag.load()) {
             condition.m_forcedEnd = true;
             if(m_eocEmit.load()) {
               endOfCycle(condition);
               break;
             }
           }
           const core::time::point now = core::time::now();
           const float timeoutEllapsed = std::chrono::duration_cast<std::chrono::milliseconds>(now-m_lastCounterIncrement).count() / 1000.f;
           const bool timeoutReached = (0 == m_timeout) ? false : (timeoutEllapsed >= m_timeout.load());
           // check timeout first
           if(timeoutReached) {
             condition.m_timeoutReached = true;
             endOfCycle(condition);
             break;
           }
           // check for normal termination of cycle
           const bool counterOver = (0 == m_counterLimit) ? false : (m_currentCounter >= m_counterLimit);
           const float ellapsed = std::chrono::duration_cast<std::chrono::milliseconds>(now-condition.m_startTime).count() / 1000.f;
           const bool periodReached = (0 == m_period) ? false : (ellapsed >= m_period.load());
           if(counterOver or periodReached) {
             endOfCycle(condition);
             break;
           }
           usleep(10000);
         }
         // reset cycle properties
         m_startCycleFlag = false;
         m_forceStopFlag = false;
         m_eocEmit = true;
         m_running = false;
         usleep(10000);
       }
     }
void dqm4hep::online::Cycle::endOfCycle (EOCCondition & condition) private
Called at end of cycle.
Fill the end of cycle conditions and post an event in the event loop
Parameters
condition the condition to fill and post
Definition at line 188 of file Cycle.cc.
References dqm_debug, dqm4hep::online::AppEvent::END_OF_CYCLE, dqm4hep::online::EOCCondition::m_counter, m_currentCounter, dqm4hep::online::EOCCondition::m_endTime, m_eventLoop, m_eventPriority, dqm4hep::online::EOCCondition::m_rate, dqm4hep::online::EOCCondition::m_startTime, dqm4hep::online::EOCCondition::m_totalTime, dqm4hep::core::time::now(), dqm4hep::online::AppEventLoop::postEvent(), and dqm4hep::online::AppEvent::setPriority().
Referenced by cycleLoop().
{
       condition.m_endTime = core::time::now();
       condition.m_counter = m_currentCounter.load();
       condition.m_totalTime = std::chrono::duration_cast<std::chrono::milliseconds>(condition.m_endTime - condition.m_startTime).count() / 1000.f;
       condition.m_rate = (condition.m_startTime == condition.m_endTime) ? 0 : (condition.m_counter / condition.m_totalTime);
       dqm_debug( "End of cycle !" );
       // post event to event loop
       auto *event = new StoreEvent<EOCCondition>(AppEvent::END_OF_CYCLE, condition);
       event->setPriority(m_eventPriority.load());
       m_eventLoop.postEvent(event);
     }
int dqm4hep::online::Cycle::eventPriority () const
Get the EndOfCycleEvent event priority.
Definition at line 87 of file Cycle.cc.
References m_eventPriority.
{
       return m_eventPriority.load();
     }
void dqm4hep::online::Cycle::forceStopCycle (bool waitEnd = true, bool emit = false)
Stop the current cycle if running.
User can choose whether to emit the end of cyle signal and wait for the end of cycle
Parameters
waitEnd whether to wait for status "not running"
emit whether to emit the end of cycle signal
Definition at line 112 of file Cycle.cc.
References m_eocEmit, m_forceStopFlag, and running().
Referenced by dqm4hep::online::ModuleApplication::processEndOfRun(), and startCycle().
{
       if(running()) {
         m_eocEmit = emit;
         m_forceStopFlag = true;
         if(waitEnd) {
           while(running()) {
             usleep(1000);
           }
         }
       }
     }
void dqm4hep::online::Cycle::incrementCounter (unsigned int increment = 1)
Increment the counter by a value.
Default is 1
Parameters
increment the increment value
Definition at line 93 of file Cycle.cc.
References m_currentCounter, m_lastCounterIncrement, and dqm4hep::core::time::now().
Referenced by dqm4hep::online::ModuleApplication::onEvent().
{
       m_currentCounter += increment;
       m_lastCounterIncrement = core::time::now();
     }
bool dqm4hep::online::Cycle::running () const
Whether the cycle is running.
Definition at line 126 of file Cycle.cc.
References m_running.
Referenced by forceStopCycle().
{
       return m_running.load();
     }
void dqm4hep::online::Cycle::setCounterLimit (unsigned int value)
Set the couting limit.
Parameters
value the couting limit
Definition at line 73 of file Cycle.cc.
References m_counterLimit.
Referenced by dqm4hep::online::ModuleApplication::configureCycle().
{
       m_counterLimit = value;
     }
void dqm4hep::online::Cycle::setEventPriority (int priority)
Set the EndOfCycleEvent event priority.
Parameters
priority the EndOfCycleEvent priority
Definition at line 79 of file Cycle.cc.
References m_eventPriority.
Referenced by dqm4hep::online::ModuleApplication::onInit().
{
       if(priority >= 0 and priority <= 100) {
         m_eventPriority = priority;
       }
     }
void dqm4hep::online::Cycle::setTimeout (unsigned int value)
Set the cycle timeout value (unit seconds)
Parameters
value the timeout value in seconds
Definition at line 49 of file Cycle.cc.
References m_timeout.
Referenced by dqm4hep::online::ModuleApplication::configureCycle().
{
       m_timeout = value;
     }
void dqm4hep::online::Cycle::setTimerPeriod (unsigned int value)
Set the cycle timer period value (unit seconds)
Parameters
value the period in seconds
Definition at line 61 of file Cycle.cc.
References m_period.
Referenced by dqm4hep::online::ModuleApplication::configureCycle().
{
       m_period = value;
     }
void dqm4hep::online::Cycle::startCycle (bool emit = false)
Start a new cycle Stop the current cycle if running.
User can choose whether to emit the end of cyle signal
Parameters
emit whether to emit the end of cycle signal
Definition at line 100 of file Cycle.cc.
References dqm_debug, dqm_error, forceStopCycle(), m_counterLimit, m_period, m_startCycleFlag, and m_timeout.
Referenced by dqm4hep::online::ModuleApplication::onEvent(), dqm4hep::online::ModuleApplication::onStart(), and dqm4hep::online::ModuleApplication::processStartOfRun().
{
       if(m_timeout >= m_period || (0 == m_counterLimit && 0 == m_period)) {
         dqm_error("Cycle::startCycle: invalid cycle settings (timeout {0}, counter limit {1}, period {2}) !", m_timeout.load(), m_counterLimit.load(), m_period.load());
         throw core::StatusCodeException(core::STATUS_CODE_FAILURE);
       }
       forceStopCycle(true, emit);
       m_startCycleFlag = true;
       dqm_debug( "=====> Started new cycle !" );
     }
unsigned int dqm4hep::online::Cycle::timeout () const
Get the timeout value (unit seconds)
Definition at line 43 of file Cycle.cc.
References m_timeout.
{
       return m_timeout.load();
     }
unsigned int dqm4hep::online::Cycle::timerPeriod () const
Get the timer period value (unit seconds)
Definition at line 55 of file Cycle.cc.
References m_period.
{
       return m_period.load();
     }
Member Data Documentation
std::atomic_uint dqm4hep::online::Cycle::m_counterLimit = {0} private
The user counter limit.
Definition at line 189 of file Cycle.h.
Referenced by counterLimit(), cycleLoop(), setCounterLimit(), and startCycle().
std::atomic_uint dqm4hep::online::Cycle::m_currentCounter = {0} private
The internal counter incremented by user.
Definition at line 191 of file Cycle.h.
Referenced by cycleLoop(), endOfCycle(), and incrementCounter().
std::atomic_bool dqm4hep::online::Cycle::m_eocEmit = {true} private
Whether an event has to be posted on end of cycle.
Definition at line 179 of file Cycle.h.
Referenced by cycleLoop(), and forceStopCycle().
AppEventLoop& dqm4hep::online::Cycle::m_eventLoop private
The application event loop in which the cycle is running.
Definition at line 171 of file Cycle.h.
Referenced by endOfCycle().
std::atomic_int dqm4hep::online::Cycle::m_eventPriority = {60} private
The end of cycle event priority in the event loop.
Definition at line 193 of file Cycle.h.
Referenced by endOfCycle(), eventPriority(), and setEventPriority().
std::atomic_bool dqm4hep::online::Cycle::m_forceStopFlag = {false} private
An internal flag to trigger an end of cycle.
Definition at line 177 of file Cycle.h.
Referenced by cycleLoop(), and forceStopCycle().
core::time::point dqm4hep::online::Cycle::m_lastCounterIncrement = {} private
The last time point when the increement method was called.
Definition at line 195 of file Cycle.h.
Referenced by cycleLoop(), and incrementCounter().
std::atomic_uint dqm4hep::online::Cycle::m_period = {30} private
The user timer period, default 30 (unit seconds)
Definition at line 187 of file Cycle.h.
Referenced by cycleLoop(), setTimerPeriod(), startCycle(), and timerPeriod().
std::atomic_bool dqm4hep::online::Cycle::m_running = {false} private
Whether a cycle has been started.
Definition at line 173 of file Cycle.h.
Referenced by cycleLoop(), and running().
std::atomic_bool dqm4hep::online::Cycle::m_startCycleFlag = {false} private
An internal flag to trigger a new cycle.
Definition at line 175 of file Cycle.h.
Referenced by cycleLoop(), and startCycle().
std::atomic_bool dqm4hep::online::Cycle::m_stopFlag = {false} private
An internal flag to stop the cycle thread.
Definition at line 181 of file Cycle.h.
Referenced by cycleLoop(), and ~Cycle().
std::thread dqm4hep::online::Cycle::m_thread = {} private
The thread object running the cycle function.
Definition at line 183 of file Cycle.h.
Referenced by Cycle(), and ~Cycle().
std::atomic_uint dqm4hep::online::Cycle::m_timeout = {10} private
The user timeout value, default 10 (unit seconds)
Definition at line 185 of file Cycle.h.
Referenced by cycleLoop(), setTimeout(), startCycle(), and timeout().
The documentation for this class was generated from the following files:
Cycle.h
Cycle.cc