DQM4hep: dqm4hep::online::OnlineRoutes::EventCollector Class Reference
dqm4hep::online::OnlineRoutes::EventCollector Class Reference
#include <OnlineRoutes.h>
Static Public Member Functions
static std::string applicationType ()
Get the event collector application type.
static std::string registerSource (const std::string &collector)
Get the event collector request name to register a new event source.
static std::string unregisterSource (const std::string &collector)
Get the event collector command name to unregister a new event source.
static std::string collectEvent (const std::string &collector)
Get the event collector command name to collect an event.
static std::string eventUpdate (const std::string &collector, const std::string &source)
Get the event collector service name to receive event updates.
static std::string eventRequest (const std::string &collector)
Get the event collector request name to receive event on query.
Detailed Description
Definition at line 83 of file OnlineRoutes.h.
Member Function Documentation
std::string dqm4hep::online::OnlineRoutes::EventCollector::applicationType () static
Get the event collector application type.
Definition at line 49 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::EventCollector::parseCmdLine(), dqm4hep::online::EventSource::registerMe(), and dqm4hep::online::EventSource::sendEvent().
{
       return "evtcol";
     }
std::string dqm4hep::online::OnlineRoutes::EventCollector::collectEvent (const std::string & collector) static
Get the event collector command name to collect an event.
Parameters
collector the collector name
Definition at line 67 of file OnlineRoutes.cc.
References dqm4hep::online::OnlineRoutes::Application::serverName().
Referenced by dqm4hep::online::EventCollector::onInit(), and dqm4hep::online::EventSource::sendEvent().
{
       return OnlineRoutes::Application::serverName(applicationType(), collector) + "/collect";
     }
std::string dqm4hep::online::OnlineRoutes::EventCollector::eventRequest (const std::string & collector) static
Get the event collector request name to receive event on query.
Parameters
collector the collector name
Definition at line 79 of file OnlineRoutes.cc.
References dqm4hep::online::OnlineRoutes::Application::serverName().
Referenced by dqm4hep::online::EventCollector::onInit(), and dqm4hep::online::EventCollectorClient::queryEvent().
{
       return OnlineRoutes::Application::serverName(applicationType(), collector) + "/lastevt";
     }
std::string dqm4hep::online::OnlineRoutes::EventCollector::eventUpdate (const std::string & collector, const std::string & source) static
Get the event collector service name to receive event updates.
Parameters
collector the collector name
source the source name
Definition at line 73 of file OnlineRoutes.cc.
References dqm4hep::online::OnlineRoutes::Application::serverName().
Referenced by dqm4hep::online::EventCollector::handleRegistration(), dqm4hep::online::EventCollectorClient::receivingEventUpdates(), and dqm4hep::online::EventCollectorClient::setUpdateMode().
{
       return OnlineRoutes::Application::serverName(applicationType(), collector) + "/updates/" + source;
     }
std::string dqm4hep::online::OnlineRoutes::EventCollector::registerSource (const std::string & collector) static
Get the event collector request name to register a new event source.
Parameters
collector the collector name
Definition at line 55 of file OnlineRoutes.cc.
References dqm4hep::online::OnlineRoutes::Application::serverName().
Referenced by dqm4hep::online::EventCollector::onInit(), and dqm4hep::online::EventSource::registerMe().
{
       return OnlineRoutes::Application::serverName(applicationType(), collector) + "/register";
     }
std::string dqm4hep::online::OnlineRoutes::EventCollector::unregisterSource (const std::string & collector) static
Get the event collector command name to unregister a new event source.
Parameters
collector the collector name
Definition at line 61 of file OnlineRoutes.cc.
References dqm4hep::online::OnlineRoutes::Application::serverName().
Referenced by dqm4hep::online::EventCollector::onInit(), and dqm4hep::online::EventSource::unregisterMe().
{
       return OnlineRoutes::Application::serverName(applicationType(), collector) + "/unregister";
     }
The documentation for this class was generated from the following files:
OnlineRoutes.h
OnlineRoutes.cc