DQM4hep: dqm4hep::core::Signal< Args > Class Template Reference
dqm4hep::core::Signal< Args > Class Template Reference
Signal class.
#include <Signal.h>
Public Member Functions
Signal ()=default
Default constructor.
~Signal ()
Destructor.
DEPRECATED (void process(Args...args))
Emit the signal.
void emit (Args...args)
Emit the signal.
template<typename T >
bool connect (T *object, void(T::*func)(Args...))
Connect a class member-function to signal.
bool connect (void(*func)(Args...))
Connect a function to signal.
template<typename T >
bool disconnect (T *object)
Disconnect all functions of the target object.
template<typename T >
bool disconnect (T *object, void(T::*func)(Args...))
Disconnect a specific class member-function.
bool disconnect (void(*func)(Args...))
Disconnect a function.
void disconnect ()
Disconnect all functions.
DEPRECATED (void disconnectAll())
Disconnect all functions.
template<typename T >
bool hasConnection (T *object) const
Whether the target object has any connected functions.
template<typename T >
bool isConnected (T *object, void(T::*func)(Args...)) const
Whether the target object and member-function is connected.
bool isConnected (void(*func)(Args...)) const
Whether the function is connected.
bool hasConnection () const
Whether the signal has at least one connection.
size_t nConnections () const
Get the number of connected functions.
Private Attributes
std::vector< SignalBase
< Args...> * > m_callbacks = {}
The list of callbacks.
Detailed Description
template<typename... Args>
class dqm4hep::core::Signal< Args >
Signal class.
Implement the observer pattern a la Qt. Example:
void func() {
  std::cout << "Hello world !" << std::endl;
}
class Toto {
public:
  void hello() {
    std::cout << "Toto world !" << std::endl;
  }
};
Signal<> sig;
Toto toto;
sig.connect(func);
sig.connect(&toto, &Toto::hello);
sig.emit();
Allows nice and understandable piece of code like:
// Holds a property and signal
class Property {
public:
  void setProperty(int value) {
    m_property = value;
    m_onUpdate.emit(m_property);
  }
  Signal<int> &onUpdate() {
    return m_onUpdate;
  }
private:
  int           m_property = {0};
  Signal<int>   m_onUpdate = {};
};
// To print the property !
class Printer {
public:
  void print(int value) {
    std::cout << "Value is " << value << std::endl;
  }
};
Printer printer;
Property property;
property.onUpdate().connect(&printer, &Printer::print); // I love this line !
property.setProperty(42); // Calls 'print' method
Definition at line 249 of file Signal.h.
Constructor & Destructor Documentation
template<typename... Args> dqm4hep::core::Signal< Args >::Signal () default
Default constructor.
template<typename... Args> dqm4hep::core::Signal< Args >::~Signal () inline
Destructor.
Definition at line 369 of file Signal.h.
{
       this->disconnect();
     }
Member Function Documentation
template<typename... Args> template<typename T > bool dqm4hep::core::Signal< Args >::connect (T * object, void(T::*)(Args...) func) inline
Connect a class member-function to signal.
Parameters
object the class object
func the class member-function
Definition at line 393 of file Signal.h.
Referenced by dqm4hep::net::CommandHandler::CommandHandler(), dqm4hep::online::Application::exec(), dqm4hep::online::Application::NetworkHandler::NetworkHandler(), dqm4hep::online::EventCollector::onInit(), dqm4hep::online::ModuleApplication::onInit(), dqm4hep::net::RequestHandler::RequestHandler(), and dqm4hep::net::ServiceHandler::ServiceHandler().
{
       if (this->isConnected(obj, func)) {
         return false;
       }
       m_callbacks.push_back(new SignalT<T, Args...>(obj, func));
       return true;
     }
template<typename... Args> bool dqm4hep::core::Signal< Args >::connect (void(*)(Args...) func) inline
Connect a function to signal.
Parameters
func [description]
Definition at line 404 of file Signal.h.
{
       if (this->isConnected(func)) {
         return false;
       }
       m_callbacks.push_back(new SignalT<void, Args...>(func));
       return true;
     }
template<typename... Args> dqm4hep::core::Signal< Args >::DEPRECATED (void processArgs...args)
Emit the signal.
This function is deprecated
Parameters
args arguments to forward
template<typename... Args> dqm4hep::core::Signal< Args >::DEPRECATED (void disconnectAll())
Disconnect all functions.
Deprecated, use disconnect() instead
template<typename... Args> template<typename T > bool dqm4hep::core::Signal< Args >::disconnect (T * object) inline
Disconnect all functions of the target object.
Parameters
object the object target
Definition at line 416 of file Signal.h.
{
       bool disconnected = false;
       auto iter = m_callbacks.begin();
       while(iter != m_callbacks.end()) {
       // for (auto iter = m_callbacks.begin(), endIter = m_callbacks.end(); endIter != iter; ++iter) {
         auto callback = dynamic_cast<SignalT<T, Args...>*>(*iter);
         if(nullptr == callback) {
           iter++;
           continue;
         }
         if (callback->object() == obj) {
           delete callback;
           iter = m_callbacks.erase(iter);
           disconnected = true;
           continue;
         }
         iter++;
       }
       return disconnected;
     }
template<typename... Args> template<typename T > bool dqm4hep::core::Signal< Args >::disconnect (T * object, void(T::*)(Args...) func) inline
Disconnect a specific class member-function.
Parameters
object the target object
func the class member-function
Definition at line 441 of file Signal.h.
{
       for (auto iter = m_callbacks.begin(), endIter = m_callbacks.end(); endIter != iter; ++iter) {
         auto callback = dynamic_cast<SignalT<T, Args...>*>(*iter);
         if(nullptr == callback) {
           continue;
         }
         if (callback->object() == obj && callback->function() == func) {
           delete callback;
           m_callbacks.erase(iter);
           return true;
         }
       }
       return false;
     }
template<typename... Args> bool dqm4hep::core::Signal< Args >::disconnect (void(*)(Args...) func) inline
Disconnect a function.
Parameters
object the target object
func the class member-function
Definition at line 459 of file Signal.h.
{
       for (auto iter = m_callbacks.begin(), endIter = m_callbacks.end(); endIter != iter; ++iter) {
         auto callback = dynamic_cast<SignalT<void, Args...>*>(*iter);
         if(nullptr == callback) {
           continue;
         }
         if (callback->function() == func) {
           delete callback;
           m_callbacks.erase(iter);
           return true;
         }
       }
       return false;
     }
template<typename... Args> void dqm4hep::core::Signal< Args >::disconnect () inline
Disconnect all functions.
Definition at line 477 of file Signal.h.
{
       for (auto iter = m_callbacks.begin(), endIter = m_callbacks.end(); endIter != iter; ++iter) {
         delete *iter;
       }
       m_callbacks.clear();
     }
template<typename... Args> void dqm4hep::core::Signal< Args >::emit (Args... args) inline
Emit the signal.
Parameters
args arguments to forward
Definition at line 383 of file Signal.h.
Referenced by dqm4hep::net::Server::clientExitHandler(), dqm4hep::online::RunControl::endCurrentRun(), dqm4hep::net::CommandHandler::handleCommand(), dqm4hep::net::RequestHandler::handleRequest(), dqm4hep::net::WsServer::onCommandMessage(), dqm4hep::net::WsServer::onRpcMessage(), dqm4hep::core::GenericEventXMLReader::readNextEvent(), dqm4hep::online::EventCollectorClient::SourceInfo::receiveEvent(), dqm4hep::net::ServiceHandler::receiveServiceUpdated(), and dqm4hep::online::RunControl::startNewRun().
{
       for (auto iter = m_callbacks.begin(), endIter = m_callbacks.end(); endIter != iter; ++iter) {
         (*iter)->emit(args...);
       }
     }
template<typename... Args> template<typename T > bool dqm4hep::core::Signal< Args >::hasConnection (T * object) const inline
Whether the target object has any connected functions.
Parameters
object the target object
Definition at line 495 of file Signal.h.
{
       for (auto iter = m_callbacks.begin(), endIter = m_callbacks.end(); endIter != iter; ++iter) {
         auto callback = dynamic_cast<const SignalT<T, Args...>*>(*iter);
         if (nullptr == callback) {
           continue;
         }
         if (callback->object() == obj) {
           return true;
         }
       }
       return false;
     }
template<typename... Args> bool dqm4hep::core::Signal< Args >::hasConnection () const inline
Whether the signal has at least one connection.
Definition at line 544 of file Signal.h.
{
       return (not m_callbacks.empty());
     }
template<typename... Args> template<typename T > bool dqm4hep::core::Signal< Args >::isConnected (T * object, void(T::*)(Args...) func) const inline
Whether the target object and member-function is connected.
Parameters
object the target object
func the class member-function
Definition at line 512 of file Signal.h.
{
       for (auto iter = m_callbacks.begin(), endIter = m_callbacks.end(); endIter != iter; ++iter) {
         auto callback = dynamic_cast<const SignalT<T, Args...>*>(*iter);
         if (nullptr == callback) {
           continue;
         }
         if (callback->object() == obj && callback->function() == func) {
           return true;
         }
       }
       return false;
     }
template<typename... Args> bool dqm4hep::core::Signal< Args >::isConnected (void(*)(Args...) func) const inline
Whether the function is connected.
Parameters
func the target function
Definition at line 528 of file Signal.h.
{
       for (auto iter = m_callbacks.begin(), endIter = m_callbacks.end(); endIter != iter; ++iter) {
         auto callback = dynamic_cast<const SignalT<void, Args...>*>(*iter);
         if (nullptr == callback) {
           continue;
         }
         if (callback->function() == func) {
           return true;
         }
       }
       return false;
     }
template<typename... Args> size_t dqm4hep::core::Signal< Args >::nConnections () const inline
Get the number of connected functions.
Definition at line 551 of file Signal.h.
{
       return m_callbacks.size();
     }
Member Data Documentation
template<typename... Args> std::vector<SignalBase<Args...>*> dqm4hep::core::Signal< Args >::m_callbacks = {} private
The list of callbacks.
Definition at line 362 of file Signal.h.
The documentation for this class was generated from the following file:
Signal.h