DQM4hep: dqm4hep::online::RemoteLogger Class Reference
dqm4hep::online::RemoteLogger Class Reference
RemoteLogger class.
#include <RemoteLogger.h>
Public Member Functions
RemoteLogger ()
Constructor.
void _sink_it (const spdlog::details::log_msg &msg) override
Log a message.
void flush () override
Flush the message.
Static Public Member Functions
static core::Logger::AppenderPtr make_shared ()
Create a shared pointer of RemoteLogger.
Private Attributes
core::json m_message = {}
The log message to send as json.
std::string m_hostname = {""}
The current host name.
net::Client m_client = {}
The net client interface.
Detailed Description
RemoteLogger class.
Definition at line 28 of file RemoteLogger.h.
Constructor & Destructor Documentation
dqm4hep::online::RemoteLogger::RemoteLogger ()
Constructor.
Definition at line 19 of file RemoteLogger.cc.
References m_hostname.
{
       char hname[256];
       gethostname(hname, 256);
       m_hostname = hname;
     }
Member Function Documentation
void dqm4hep::online::RemoteLogger::_sink_it (const spdlog::details::log_msg & msg) override
Log a message.
Parameters
msg the spdlog log message
Definition at line 33 of file RemoteLogger.cc.
References dqm4hep::online::OnlineRoutes::OnlineManager::collectLog(), m_client, m_hostname, m_message, dqm4hep::core::pid(), and dqm4hep::net::Client::sendCommand().
{
       m_message = {
         {"logger",   *msg.logger_name},
         {"level",   msg.level},
         {"message", msg.raw.str()},
         {"host",    m_hostname},
         {"pid",     dqm4hep::core::pid()}
       };
       m_client.sendCommand(OnlineRoutes::OnlineManager::collectLog(), m_message.dump());
     }
void dqm4hep::online::RemoteLogger::flush () override
Flush the message.
Definition at line 46 of file RemoteLogger.cc.
{
     }
core::Logger::AppenderPtr dqm4hep::online::RemoteLogger::make_shared () static
Create a shared pointer of RemoteLogger.
Definition at line 27 of file RemoteLogger.cc.
Referenced by dqm4hep::online::Application::init().
{
       return std::make_shared<RemoteLogger>();
     }
Member Data Documentation
net::Client dqm4hep::online::RemoteLogger::m_client = {} private
The net client interface.
Definition at line 55 of file RemoteLogger.h.
Referenced by _sink_it().
std::string dqm4hep::online::RemoteLogger::m_hostname = {""} private
The current host name.
Definition at line 54 of file RemoteLogger.h.
Referenced by _sink_it(), and RemoteLogger().
core::json dqm4hep::online::RemoteLogger::m_message = {} private
The log message to send as json.
Definition at line 53 of file RemoteLogger.h.
Referenced by _sink_it().
The documentation for this class was generated from the following files:
RemoteLogger.h
RemoteLogger.cc