DQM4hep: dqm4hep::core::TiXmlPrinter Class Reference
dqm4hep::core::TiXmlPrinter Class Reference
Print to memory functionality.
#include <tinyxml.h>
Public Member Functions
TiXmlPrinter ()
bool VisitEnter (const TiXmlDocument &doc) override
Visit a document.
bool VisitExit (const TiXmlDocument &doc) override
Visit a document.
bool VisitEnter (const TiXmlElement &element, const TiXmlAttribute *firstAttribute) override
Visit an element.
bool VisitExit (const TiXmlElement &element) override
Visit an element.
bool Visit (const TiXmlDeclaration &declaration) override
Visit a declaration.
bool Visit (const TiXmlText &text) override
Visit a text node.
bool Visit (const TiXmlComment &comment) override
Visit a comment node.
bool Visit (const TiXmlUnknown &unknown) override
Visit an unknow node.
void SetIndent (const char *_indent)
Set the indent characters for printing.
const char * Indent ()
Query the indention string.
void SetLineBreak (const char *_lineBreak)
Set the line breaking string.
const char * LineBreak ()
Query the current line breaking string.
void SetStreamPrinting ()
Switch over to "stream printing" which is the most dense formatting without linebreaks.
const char * CStr ()
Return the result.
size_t Size ()
Return the length of the result string.
const std::string & Str ()
Return the result.
Public Member Functions inherited from dqm4hep::core::TiXmlVisitor
virtual ~TiXmlVisitor ()=default
Private Member Functions
void DoIndent ()
void DoLineBreak ()
Private Attributes
int depth = {0}
bool simpleTextPrint = {false}
TIXML_STRING buffer = {}
TIXML_STRING indent = {" "}
TIXML_STRING lineBreak = {"\n"}
Detailed Description
Print to memory functionality.
The TiXmlPrinter is useful when you need to:
Print to memory (especially in non-STL mode)
Control formatting (line endings, etc.)
When constructed, the TiXmlPrinter is in its default "pretty printing" mode. Before calling Accept() you can call methods to control the printing of the XML document. After TiXmlNode::Accept() is called, the printed document can be accessed via the CStr(), Str(), and Size() methods.
TiXmlPrinter uses the Visitor API.
TiXmlPrinter printer;
printer.SetIndent("\t");
doc.Accept(&printer);
fprintf(stdout, "%s", printer.CStr());
Definition at line 1934 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::core::TiXmlPrinter::TiXmlPrinter () inline
Definition at line 1936 of file tinyxml.h.
                      : depth(0), simpleTextPrint(false), buffer(), indent("    "), lineBreak("\n") {
       }
Member Function Documentation
const char* dqm4hep::core::TiXmlPrinter::CStr () inline
Return the result.
Definition at line 1980 of file tinyxml.h.
References buffer.
{
         return buffer.c_str();
       }
void dqm4hep::core::TiXmlPrinter::DoIndent () inline private
Definition at line 1996 of file tinyxml.h.
References buffer, depth, and indent.
Referenced by Visit(), VisitEnter(), and VisitExit().
                       {
         for (int i = 0; i < depth; ++i)
           buffer += indent;
       }
void dqm4hep::core::TiXmlPrinter::DoLineBreak () inline private
Definition at line 2000 of file tinyxml.h.
References buffer, and lineBreak.
Referenced by Visit(), VisitEnter(), and VisitExit().
{
         buffer += lineBreak;
       }
const char* dqm4hep::core::TiXmlPrinter::Indent () inline
Query the indention string.
Definition at line 1957 of file tinyxml.h.
References indent.
{
         return indent.c_str();
       }
const char* dqm4hep::core::TiXmlPrinter::LineBreak () inline
Query the current line breaking string.
Definition at line 1968 of file tinyxml.h.
References lineBreak.
{
         return lineBreak.c_str();
       }
void dqm4hep::core::TiXmlPrinter::SetIndent (const char * _indent) inline
Set the indent characters for printing.
By default 4 spaces but tab () is also useful, or null/empty string for no indentation.
Definition at line 1953 of file tinyxml.h.
References indent.
{
         indent = _indent != nullptr ? _indent : "";
       }
void dqm4hep::core::TiXmlPrinter::SetLineBreak (const char * _lineBreak) inline
Set the line breaking string.
By default set to newline (
). Some operating systems prefer other characters, or can be set to the null/empty string for no indenation.
Definition at line 1964 of file tinyxml.h.
References lineBreak.
{
         lineBreak = _lineBreak != nullptr ? _lineBreak : "";
       }
void dqm4hep::core::TiXmlPrinter::SetStreamPrinting () inline
Switch over to "stream printing" which is the most dense formatting without linebreaks.
Common when the XML is needed for network transmission.
Definition at line 1975 of file tinyxml.h.
References indent, and lineBreak.
{
         indent = "";
         lineBreak = "";
       }
size_t dqm4hep::core::TiXmlPrinter::Size () inline
Return the length of the result string.
Definition at line 1984 of file tinyxml.h.
References buffer.
                     {
         return buffer.size();
       }
const std::string& dqm4hep::core::TiXmlPrinter::Str () inline
Return the result.
Definition at line 1990 of file tinyxml.h.
Referenced by dqm4hep::online::TestAnalysisModule::readSettings(), and dqm4hep::online::TestStandaloneModule::readSettings().
{
         return buffer;
       }
bool dqm4hep::core::TiXmlPrinter::Visit (const TiXmlDeclaration &) override virtual
Visit a declaration.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1486 of file tinyxml.cc.
References buffer, DoIndent(), DoLineBreak(), and dqm4hep::core::TiXmlDeclaration::Print().
{
       DoIndent();
       declaration.Print(nullptr, 0, &buffer);
       DoLineBreak();
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::Visit (const TiXmlText &) override virtual
Visit a text node.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1465 of file tinyxml.cc.
References buffer, dqm4hep::core::TiXmlText::CDATA(), DoIndent(), DoLineBreak(), dqm4hep::core::TiXmlBase::EncodeString(), simpleTextPrint, TIXML_STRING, dqm4hep::core::TiXmlNode::Value(), and dqm4hep::core::TiXmlNode::ValueTStr().
{
       if (text.CDATA()) {
         DoIndent();
         buffer += "<![CDATA[";
         buffer += text.Value();
         buffer += "]]>";
         DoLineBreak();
       } else if (simpleTextPrint) {
         TIXML_STRING str;
         TiXmlBase::EncodeString(text.ValueTStr(), &str);
         buffer += str;
       } else {
         DoIndent();
         TIXML_STRING str;
         TiXmlBase::EncodeString(text.ValueTStr(), &str);
         buffer += str;
         DoLineBreak();
       }
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::Visit (const TiXmlComment &) override virtual
Visit a comment node.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1493 of file tinyxml.cc.
References buffer, DoIndent(), DoLineBreak(), and dqm4hep::core::TiXmlNode::Value().
{
       DoIndent();
       buffer += "<!--";
       buffer += comment.Value();
       buffer += "-->";
       DoLineBreak();
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::Visit (const TiXmlUnknown &) override virtual
Visit an unknow node.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1502 of file tinyxml.cc.
References buffer, DoIndent(), DoLineBreak(), and dqm4hep::core::TiXmlNode::Value().
{
       DoIndent();
       buffer += "<";
       buffer += unknown.Value();
       buffer += ">";
       DoLineBreak();
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::VisitEnter (const TiXmlDocument &) override virtual
Visit a document.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1412 of file tinyxml.cc.
{
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::VisitEnter (const TiXmlElement & , const TiXmlAttribute *) override virtual
Visit an element.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1420 of file tinyxml.cc.
References buffer, dqm4hep::core::TiXmlText::CDATA(), depth, DoIndent(), DoLineBreak(), dqm4hep::core::TiXmlNode::FirstChild(), dqm4hep::core::TiXmlNode::LastChild(), dqm4hep::core::TiXmlAttribute::Next(), simpleTextPrint, dqm4hep::core::TiXmlNode::ToText(), and dqm4hep::core::TiXmlNode::Value().
{
       DoIndent();
       buffer += "<";
       buffer += element.Value();
       for (const TiXmlAttribute *attrib = firstAttribute; attrib != nullptr; attrib = attrib->Next()) {
         buffer += " ";
         attrib->Print(nullptr, 0, &buffer);
       }
       if (element.FirstChild() == nullptr) {
         buffer += " />";
         DoLineBreak();
       } else {
         buffer += ">";
         if ((element.FirstChild()->ToText() != nullptr) && element.LastChild() == element.FirstChild() &&
             !element.FirstChild()->ToText()->CDATA()) {
           simpleTextPrint = true;
           // no DoLineBreak()!
         } else {
           DoLineBreak();
         }
       }
       ++depth;
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::VisitExit (const TiXmlDocument &) override virtual
Visit a document.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1416 of file tinyxml.cc.
{
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::VisitExit (const TiXmlElement &) override virtual
Visit an element.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1447 of file tinyxml.cc.
References buffer, depth, DoIndent(), DoLineBreak(), dqm4hep::core::TiXmlNode::FirstChild(), simpleTextPrint, and dqm4hep::core::TiXmlNode::Value().
{
       --depth;
       if (element.FirstChild() == nullptr) {
         // nothing.
       } else {
         if (simpleTextPrint) {
           simpleTextPrint = false;
         } else {
           DoIndent();
         }
         buffer += "</";
         buffer += element.Value();
         buffer += ">";
         DoLineBreak();
       }
       return true;
     }
Member Data Documentation
TIXML_STRING dqm4hep::core::TiXmlPrinter::buffer = {} private
Definition at line 2006 of file tinyxml.h.
Referenced by CStr(), DoIndent(), DoLineBreak(), Size(), Visit(), VisitEnter(), and VisitExit().
int dqm4hep::core::TiXmlPrinter::depth = {0} private
Definition at line 2004 of file tinyxml.h.
Referenced by DoIndent(), VisitEnter(), and VisitExit().
TIXML_STRING dqm4hep::core::TiXmlPrinter::indent = {" "} private
Definition at line 2007 of file tinyxml.h.
Referenced by DoIndent(), Indent(), SetIndent(), and SetStreamPrinting().
TIXML_STRING dqm4hep::core::TiXmlPrinter::lineBreak = {"\n"} private
Definition at line 2008 of file tinyxml.h.
Referenced by DoLineBreak(), LineBreak(), SetLineBreak(), and SetStreamPrinting().
bool dqm4hep::core::TiXmlPrinter::simpleTextPrint = {false} private
Definition at line 2005 of file tinyxml.h.
Referenced by Visit(), VisitEnter(), and VisitExit().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc