DQM4hep: dqm4hep::online::OnlineRoutes::Application Class Reference
dqm4hep::online::OnlineRoutes::Application Class Reference
#include <OnlineRoutes.h>
Static Public Member Functions
static std::string serverName (const std::string &type, const std::string &name)
Get the server name given an app type and name.
static std::string state (const std::string &type, const std::string &name)
Get the app state service name given an app type and name.
Detailed Description
Definition at line 79 of file OnlineRoutes.h.
Member Function Documentation
std::string dqm4hep::online::OnlineRoutes::Application::serverName (const std::string & type, const std::string & name) static
Get the server name given an app type and name.
Parameters
type the app type
name the app name
Definition at line 54 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::OnlineRoutes::EventCollector::collectEvent(), dqm4hep::online::OnlineRoutes::EventCollector::eventRequest(), dqm4hep::online::OnlineRoutes::EventCollector::eventUpdate(), dqm4hep::online::Application::init(), dqm4hep::online::EventSource::registerMe(), dqm4hep::online::OnlineRoutes::EventCollector::registerSource(), dqm4hep::online::EventSource::sendEvent(), dqm4hep::online::OnlineRoutes::ModuleApplication::subscribe(), and dqm4hep::online::OnlineRoutes::EventCollector::unregisterSource().
{
       return "/dqm4hep/app/" + type + "/" + name;
     }
std::string dqm4hep::online::OnlineRoutes::Application::state (const std::string & type, const std::string & name) static
Get the app state service name given an app type and name.
Parameters
type the app type
name the app name
Definition at line 60 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::Application::init().
{
       return serverName(type, name) + "/state";
     }
The documentation for this class was generated from the following files:
OnlineRoutes.h
OnlineRoutes.cc