DQM4hep: dqm4hep::online::ServiceUpdateEvent Class Reference
dqm4hep::online::ServiceUpdateEvent Class Reference
#include <AppEvents.h>
Public Member Functions
ServiceUpdateEvent (const std::string &serviceName, net::BufferModelPtr bufferModel)
const std::string & serviceName () const
const net::Buffer & buffer () const
Public Member Functions inherited from dqm4hep::online::AppEvent
AppEvent (int type)
Constructor.
virtual ~AppEvent ()
Destructor.
int type () const
Returns the event type.
void setPriority (int priority)
Set the event priority, range [0,100].
int priority () const
Get the event priority.
Private Attributes
std::string m_serviceName = {""}
net::Buffer m_buffer = {}
Additional Inherited Members
Public Types inherited from dqm4hep::online::AppEvent
enum Type {
NONE = 0, QUIT, SERVICE_UPDATE, REQUEST_HANDLING,
COMMAND_HANDLING, CLIENT_EXIT, START_OF_RUN, END_OF_RUN,
END_OF_CYCLE, PROCESS_EVENT, USER = 1024, MAX_USER = 65535
}
AppEvent type enum.
Detailed Description
Definition at line 24 of file AppEvents.h.
Constructor & Destructor Documentation
dqm4hep::online::ServiceUpdateEvent::ServiceUpdateEvent (const std::string & serviceName, net::BufferModelPtr bufferModel) inline
Definition at line 79 of file AppEvents.h.
References m_buffer, and dqm4hep::net::Buffer::setModel().
                                                                                                        :
       AppEvent(SERVICE_UPDATE),
       m_serviceName(sname) {
       m_buffer.setModel(bufferModel);
     }
Member Function Documentation
const net::Buffer & dqm4hep::online::ServiceUpdateEvent::buffer () const inline
Definition at line 93 of file AppEvents.h.
References m_buffer.
Referenced by dqm4hep::online::ModuleApplication::processStartOfRun().
{
       return m_buffer;
     }
const std::string & dqm4hep::online::ServiceUpdateEvent::serviceName () const inline
Definition at line 87 of file AppEvents.h.
References m_serviceName.
Referenced by dqm4hep::online::ModuleApplication::onEvent(), and dqm4hep::online::Application::NetworkHandler::postServiceContent().
{
       return m_serviceName;
     }
Member Data Documentation
net::Buffer dqm4hep::online::ServiceUpdateEvent::m_buffer = {} private
Definition at line 31 of file AppEvents.h.
Referenced by buffer(), and ServiceUpdateEvent().
std::string dqm4hep::online::ServiceUpdateEvent::m_serviceName = {""} private
Definition at line 30 of file AppEvents.h.
Referenced by serviceName().
The documentation for this class was generated from the following file:
AppEvents.h