DQM4hep: dqm4hep::core::TiXmlElement Class Reference
dqm4hep::core::TiXmlElement Class Reference
The element is a container class.
#include <tinyxml.h>
Public Member Functions
TiXmlElement (const char *_value)
Construct an element.
TiXmlElement (const std::string &_value)
std::string constructor.
TiXmlElement (const TiXmlElement &)
TiXmlElement & operator= (const TiXmlElement &base)
~TiXmlElement () override
const char * Attribute (const char *name) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
const char * Attribute (const char *name, int *i) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
const char * Attribute (const char *name, double *d) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
int QueryIntAttribute (const char *name, int *ival) const
QueryIntAttribute examines the attribute - it is an alternative to the Attribute() method with richer error checking.
int QueryDoubleAttribute (const char *name, double *dval) const
QueryDoubleAttribute examines the attribute - see QueryIntAttribute().
int QueryFloatAttribute (const char *name, float *_value) const
QueryFloatAttribute examines the attribute - see QueryIntAttribute().
int QueryStringAttribute (const char *name, std::string *_value) const
QueryStringAttribute examines the attribute - see QueryIntAttribute().
template<typename T >
int QueryValueAttribute (const std::string &name, T *outValue) const
Template form of the attribute query which will try to read the attribute into the specified type.
int QueryValueAttribute (const std::string &name, std::string *outValue) const
void SetAttribute (const char *cname, const char *cvalue)
Sets an attribute of name to a given value.
const std::string * Attribute (const std::string &name) const
const std::string * Attribute (const std::string &name, int *i) const
const std::string * Attribute (const std::string &name, double *d) const
int QueryIntAttribute (const std::string &name, int *ival) const
int QueryDoubleAttribute (const std::string &name, double *dval) const
void SetAttribute (const std::string &_name, const std::string &_value)
STL std::string form.
void SetAttribute (const std::string &name, int val)
STL std::string form.
void SetDoubleAttribute (const std::string &name, double val)
void SetAttribute (const char *name, int val)
Sets an attribute of name to a given value.
void SetDoubleAttribute (const char *name, double val)
Sets an attribute of name to a given value.
void RemoveAttribute (const char *name)
Deletes an attribute with the given name.
void RemoveAttribute (const std::string &name)
STL std::string form.
const TiXmlAttribute * FirstAttribute () const
Access the first attribute in this element.
TiXmlAttribute * FirstAttribute ()
const TiXmlAttribute * LastAttribute () const
Access the last attribute in this element.
TiXmlAttribute * LastAttribute ()
const char * GetText () const
Convenience function for easy access to the text inside an element.
TiXmlNode * Clone () const override
Creates a new Element and returns it - the returned element is a copy.
void Print (FILE *cfile, int depth) const override
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding) override
const TiXmlElement * ToElement () const override
Cast to a more defined type. Will return null not of the requested type.
TiXmlElement * ToElement () override
Cast to a more defined type. Will return null not of the requested type.
bool Accept (TiXmlVisitor *visitor) const override
Walk the XML tree visiting this node and all of its children.
Public Member Functions inherited from dqm4hep::core::TiXmlNode
~TiXmlNode () override
const char * Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
const std::string & ValueStr () const
Return Value() as a std::string.
const TIXML_STRING & ValueTStr () const
void SetValue (const char *_value)
Changes the value of the node.
void SetValue (const std::string &_value)
STL std::string form.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *_value) const
The first child of this node with the matching 'value'.
TiXmlNode * FirstChild (const char *_value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *_value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * FirstChild (const std::string &_value) const
STL std::string form.
TiXmlNode * FirstChild (const std::string &_value)
STL std::string form.
const TiXmlNode * LastChild (const std::string &_value) const
STL std::string form.
TiXmlNode * LastChild (const std::string &_value)
STL std::string form.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
An alternate way to walk the children of a node.
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *val, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous) const
STL std::string form.
TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous)
STL std::string form.
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * LinkEndChild (TiXmlNode *node)
Add a new node related to this.
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
Replace a child of this node.
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * PreviousSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * PreviousSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * NextSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * NextSiblingElement (const std::string &_value) const
STL std::string form.
TiXmlElement * NextSiblingElement (const std::string &_value)
STL std::string form.
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
const TiXmlElement * FirstChildElement (const std::string &_value) const
STL std::string form.
TiXmlElement * FirstChildElement (const std::string &_value)
STL std::string form.
int Type () const
Query the type (as an enumerated value, above) of this node.
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
Public Member Functions inherited from dqm4hep::core::TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()=default
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Protected Member Functions
void CopyTo (TiXmlElement *target) const
void ClearThis ()
void StreamIn (std::istream *in, TIXML_STRING *tag) override
const char * ReadValue (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
Protected Member Functions inherited from dqm4hep::core::TiXmlNode
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *p, TiXmlEncoding encoding)
Private Attributes
TiXmlAttributeSet attributeSet = {}
Additional Inherited Members
Public Types inherited from dqm4hep::core::TiXmlNode
enum NodeType {
TINYXML_DOCUMENT, TINYXML_ELEMENT, TINYXML_COMMENT, TINYXML_UNKNOWN,
TINYXML_TEXT, TINYXML_DECLARATION, TINYXML_TYPECOUNT
}
The types of XML nodes supported by TinyXml.
Public Types inherited from dqm4hep::core::TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_PARSING_ELEMENT,
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES, TIXML_ERROR_PARSING_EMPTY,
TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT, TIXML_ERROR_PARSING_DECLARATION,
TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA, TIXML_ERROR_DOCUMENT_TOP_ONLY,
TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from dqm4hep::core::TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *outString)
Expands entities in a string.
Static Public Attributes inherited from dqm4hep::core::TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from dqm4hep::core::TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *p, TIXML_STRING *text, bool trimWhiteSpace, const char *endTag, bool caseInsensitive, TiXmlEncoding encoding)
static const char * GetEntity (const char *p, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *tag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from dqm4hep::core::TiXmlNode
TiXmlNode * parent = {nullptr}
NodeType type = {TINYXML_UNKNOWN}
TiXmlNode * firstChild = {nullptr}
TiXmlNode * lastChild = {nullptr}
TIXML_STRING value = {""}
TiXmlNode * prev = {nullptr}
TiXmlNode * next = {nullptr}
Protected Attributes inherited from dqm4hep::core::TiXmlBase
TiXmlCursor location = {}
void * userData = {nullptr}
Field containing a generic user pointer.
Static Protected Attributes inherited from dqm4hep::core::TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
The element is a container class.
It has a value, the element name, and can contain other elements, text, comments, and unknowns. Elements also contain an arbitrary number of attributes.
Definition at line 1054 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::core::TiXmlElement::TiXmlElement (const char * _value)
Construct an element.
Definition at line 427 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::firstChild, dqm4hep::core::TiXmlNode::lastChild, and dqm4hep::core::TiXmlNode::value.
Referenced by Clone().
                                                  : TiXmlNode(TiXmlNode::TINYXML_ELEMENT) {
       firstChild = lastChild = nullptr;
       value = _value;
     }
dqm4hep::core::TiXmlElement::TiXmlElement (const std::string & _value)
std::string constructor.
dqm4hep::core::TiXmlElement::TiXmlElement (const TiXmlElement & copy)
Definition at line 439 of file tinyxml.cc.
References CopyTo(), dqm4hep::core::TiXmlNode::firstChild, and dqm4hep::core::TiXmlNode::lastChild.
                                                        : TiXmlNode(TiXmlNode::TINYXML_ELEMENT) {
       firstChild = lastChild = nullptr;
       copy.CopyTo(this);
     }
dqm4hep::core::TiXmlElement::~TiXmlElement () override
Definition at line 450 of file tinyxml.cc.
References ClearThis().
{
       ClearThis();
     }
Member Function Documentation
bool dqm4hep::core::TiXmlElement::Accept (TiXmlVisitor * visitor) const override virtual
Walk the XML tree visiting this node and all of its children.
Implements dqm4hep::core::TiXmlNode.
Definition at line 675 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::First(), dqm4hep::core::TiXmlNode::FirstChild(), dqm4hep::core::TiXmlNode::NextSibling(), dqm4hep::core::TiXmlVisitor::VisitEnter(), and dqm4hep::core::TiXmlVisitor::VisitExit().
{
       if (visitor->VisitEnter(*this, attributeSet.First())) {
         for (const TiXmlNode *node = FirstChild(); node != nullptr; node = node->NextSibling()) {
           if (!node->Accept(visitor))
             break;
         }
       }
       return visitor->VisitExit(*this);
     }
const char * dqm4hep::core::TiXmlElement::Attribute (const char * name) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
Definition at line 463 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::Find(), and dqm4hep::core::TiXmlAttribute::Value().
Referenced by dqm4hep::core::XmlHelper::getAttribute(), dqm4hep::core::XMLParser::readDatabases(), and dqm4hep::core::XMLParser::resolveInclude().
{
       const TiXmlAttribute *node = attributeSet.Find(name);
       if (node != nullptr)
         return node->Value();
       return nullptr;
     }
const char * dqm4hep::core::TiXmlElement::Attribute (const char * name, int * i) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
If the attribute exists and can be converted to an integer, the integer value will be put in the return 'i', if 'i' is non-null.
Definition at line 479 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::Find(), dqm4hep::core::TiXmlAttribute::QueryIntValue(), and dqm4hep::core::TiXmlAttribute::Value().
{
       const TiXmlAttribute *attrib = attributeSet.Find(name);
       const char *result = nullptr;
       if (attrib != nullptr) {
         result = attrib->Value();
         if (i != nullptr) {
           attrib->QueryIntValue(i);
         }
       }
       return result;
     }
const char * dqm4hep::core::TiXmlElement::Attribute (const char * name, double * d) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
If the attribute exists and can be converted to an double, the double value will be put in the return 'd', if 'd' is non-null.
Definition at line 507 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::Find(), dqm4hep::core::TiXmlAttribute::QueryDoubleValue(), and dqm4hep::core::TiXmlAttribute::Value().
{
       const TiXmlAttribute *attrib = attributeSet.Find(name);
       const char *result = nullptr;
       if (attrib != nullptr) {
         result = attrib->Value();
         if (d != nullptr) {
           attrib->QueryDoubleValue(d);
         }
       }
       return result;
     }
const std::string* dqm4hep::core::TiXmlElement::Attribute (const std::string & name) const
const std::string* dqm4hep::core::TiXmlElement::Attribute (const std::string & name, int * i) const
const std::string* dqm4hep::core::TiXmlElement::Attribute (const std::string & name, double * d) const
void dqm4hep::core::TiXmlElement::ClearThis () protected
Definition at line 454 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlNode::Clear(), dqm4hep::core::TiXmlAttributeSet::First(), and dqm4hep::core::TiXmlAttributeSet::Remove().
Referenced by operator=(), and ~TiXmlElement().
{
       Clear();
       while (attributeSet.First() != nullptr) {
         TiXmlAttribute *node = attributeSet.First();
         attributeSet.Remove(node);
         delete node;
       }
     }
TiXmlNode * dqm4hep::core::TiXmlElement::Clone () const override virtual
Creates a new Element and returns it - the returned element is a copy.
Implements dqm4hep::core::TiXmlNode.
Definition at line 685 of file tinyxml.cc.
References CopyTo(), TiXmlElement(), and dqm4hep::core::TiXmlNode::Value().
{
       auto clone = new TiXmlElement(Value());
       if (clone == nullptr)
         return nullptr;
       CopyTo(clone);
       return clone;
     }
void dqm4hep::core::TiXmlElement::CopyTo (TiXmlElement * target) const protected
Definition at line 658 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlNode::Clone(), dqm4hep::core::TiXmlNode::CopyTo(), dqm4hep::core::TiXmlAttributeSet::First(), dqm4hep::core::TiXmlNode::firstChild, dqm4hep::core::TiXmlNode::LinkEndChild(), dqm4hep::core::TiXmlAttribute::Name(), dqm4hep::core::TiXmlAttribute::Next(), dqm4hep::core::TiXmlNode::NextSibling(), SetAttribute(), and dqm4hep::core::TiXmlAttribute::Value().
Referenced by Clone(), operator=(), and TiXmlElement().
{
       // superclass:
       TiXmlNode::CopyTo(target);
       // Element class:
       // Clone the attributes, then clone the children.
       const TiXmlAttribute *attribute = nullptr;
       for (attribute = attributeSet.First(); attribute != nullptr; attribute = attribute->Next()) {
         target->SetAttribute(attribute->Name(), attribute->Value());
       }
       TiXmlNode *node = nullptr;
       for (node = firstChild; node != nullptr; node = node->NextSibling()) {
         target->LinkEndChild(node->Clone());
       }
     }
const TiXmlAttribute* dqm4hep::core::TiXmlElement::FirstAttribute () const inline
Access the first attribute in this element.
Definition at line 1191 of file tinyxml.h.
References attributeSet, and dqm4hep::core::TiXmlAttributeSet::First().
Referenced by dqm4hep::core::XMLParser::resolveConstantsInElement(), and dqm4hep::core::XMLParser::resolveForLoop().
TiXmlAttribute* dqm4hep::core::TiXmlElement::FirstAttribute () inline
Definition at line 1194 of file tinyxml.h.
References attributeSet, and dqm4hep::core::TiXmlAttributeSet::First().
{
         return attributeSet.First();
       }
const char * dqm4hep::core::TiXmlElement::GetText () const
Convenience function for easy access to the text inside an element.
Although easy and concise, GetText() is limited compared to getting the TiXmlText child and accessing it directly.
If the first child of 'this' is a TiXmlText, the GetText() returns the character string of the Text node, else null is returned.
This is a convenient method for getting the text of simple contained text:
      <foo>This is text</foo>
      const char* str = fooElement->GetText();
'str' will be a pointer to "This is text".
Note that this function can be misleading. If the element foo was created from this XML:
      <foo><b>This is text</b></foo>
then the value of str would be null. The first child node isn't a text node, it is another element. From this XML:
      <foo>This is <b>text</b></foo>
GetText() will return "This is ".
WARNING: GetText() accesses a child node - don't become confused with the similarly named TiXmlHandle::Text() and TiXmlNode::ToText() which are safe type casts on the referenced node.
Definition at line 694 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChild(), dqm4hep::core::TiXmlNode::ToText(), and dqm4hep::core::TiXmlNode::Value().
Referenced by dqm4hep::core::XmlHelper::parseParameterElement(), dqm4hep::core::XmlHelper::read2DVectorOfValues(), dqm4hep::core::XmlHelper::readValue(), and dqm4hep::core::XmlHelper::readVectorOfValues().
{
       const TiXmlNode *child = this->FirstChild();
       if (child != nullptr) {
         const TiXmlText *childText = child->ToText();
         if (childText != nullptr) {
           return childText->Value();
         }
       }
       return nullptr;
     }
const TiXmlAttribute* dqm4hep::core::TiXmlElement::LastAttribute () const inline
Access the last attribute in this element.
Definition at line 1197 of file tinyxml.h.
References attributeSet, and dqm4hep::core::TiXmlAttributeSet::Last().
TiXmlAttribute* dqm4hep::core::TiXmlElement::LastAttribute () inline
Definition at line 1200 of file tinyxml.h.
References attributeSet, and dqm4hep::core::TiXmlAttributeSet::Last().
{
         return attributeSet.Last();
       }
TiXmlElement & dqm4hep::core::TiXmlElement::operator= (const TiXmlElement & base)
Definition at line 444 of file tinyxml.cc.
References ClearThis(), and CopyTo().
{
       ClearThis();
       base.CopyTo(this);
       return *this;
     }
const char * dqm4hep::core::TiXmlElement::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) override virtual
Implements dqm4hep::core::TiXmlBase.
Definition at line 905 of file tinyxmlparser.cc.
References dqm4hep::core::TiXmlAttributeSet::Add(), attributeSet, dqm4hep::core::TiXmlParsingData::Cursor(), dqm4hep::core::TiXmlAttributeSet::Find(), dqm4hep::core::TiXmlNode::GetDocument(), dqm4hep::core::TiXmlBase::location, dqm4hep::core::TiXmlBase::ReadName(), ReadValue(), dqm4hep::core::TiXmlDocument::SetError(), dqm4hep::core::TiXmlBase::SkipWhiteSpace(), dqm4hep::core::TiXmlParsingData::Stamp(), dqm4hep::core::TiXmlBase::StringEqual(), dqm4hep::core::TiXmlBase::TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, dqm4hep::core::TiXmlBase::TIXML_ERROR_PARSING_ELEMENT, dqm4hep::core::TiXmlBase::TIXML_ERROR_PARSING_EMPTY, dqm4hep::core::TiXmlBase::TIXML_ERROR_READING_ATTRIBUTES, dqm4hep::core::TiXmlBase::TIXML_ERROR_READING_END_TAG, TIXML_STRING, and dqm4hep::core::TiXmlNode::value.
{
       p = SkipWhiteSpace(p, encoding);
       TiXmlDocument *document = GetDocument();
       if ((p == nullptr) || (*p == 0)) {
         if (document != nullptr)
           document->SetError(TIXML_ERROR_PARSING_ELEMENT, nullptr, nullptr, encoding);
         return nullptr;
       }
       if (data != nullptr) {
         data->Stamp(p, encoding);
         location = data->Cursor();
       }
       if (*p != '<') {
         if (document != nullptr)
           document->SetError(TIXML_ERROR_PARSING_ELEMENT, p, data, encoding);
         return nullptr;
       }
       p = SkipWhiteSpace(p + 1, encoding);
       // Read the name.
       const char *pErr = p;
       p = ReadName(p, &value, encoding);
       if ((p == nullptr) || (*p == 0)) {
         if (document != nullptr)
           document->SetError(TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, pErr, data, encoding);
         return nullptr;
       }
       TIXML_STRING endTag("</");
       endTag += value;
       // Check for and read attributes. Also look for an empty
       // tag or an end tag.
       while ((p != nullptr) && (*p != 0)) {
         pErr = p;
         p = SkipWhiteSpace(p, encoding);
         if ((p == nullptr) || (*p == 0)) {
           if (document != nullptr)
             document->SetError(TIXML_ERROR_READING_ATTRIBUTES, pErr, data, encoding);
           return nullptr;
         }
         if (*p == '/') {
           ++p;
           // Empty tag.
           if (*p != '>') {
             if (document != nullptr)
               document->SetError(TIXML_ERROR_PARSING_EMPTY, p, data, encoding);
             return nullptr;
           }
           return (p + 1);
         }
         if (*p == '>') {
           // Done with attributes (if there were any.)
           // Read the value -- which can include other
           // elements -- read the end tag, and return.
           ++p;
           p = ReadValue(p, data, encoding); // Note this is an Element method, and will set the error if one happens.
           if ((p == nullptr) || (*p == 0)) {
             // We were looking for the end tag, but found nothing.
             // Fix for [ 1663758 ] Failure to report error on bad XML
             if (document != nullptr)
               document->SetError(TIXML_ERROR_READING_END_TAG, p, data, encoding);
             return nullptr;
           }
           // We should find the end tag now
           // note that:
           // </foo > and
           // </foo>
           // are both valid end tags.
           if (StringEqual(p, endTag.c_str(), false, encoding)) {
             p += endTag.length();
             p = SkipWhiteSpace(p, encoding);
             if ((p != nullptr) && (*p != 0) && *p == '>') {
               ++p;
               return p;
             }
             if (document != nullptr)
               document->SetError(TIXML_ERROR_READING_END_TAG, p, data, encoding);
             return nullptr;
           }
           if (document != nullptr)
             document->SetError(TIXML_ERROR_READING_END_TAG, p, data, encoding);
           return nullptr;
         } else {
           // Try to read an attribute:
           auto attrib = new TiXmlAttribute();
           if (attrib == nullptr) {
             return nullptr;
           }
           attrib->SetDocument(document);
           pErr = p;
           p = attrib->Parse(p, data, encoding);
           if ((p == nullptr) || (*p == 0)) {
             if (document != nullptr)
               document->SetError(TIXML_ERROR_PARSING_ELEMENT, pErr, data, encoding);
             delete attrib;
             return nullptr;
           }
 // Handle the strange case of double attributes:
 #ifdef TIXML_USE_STL
           TiXmlAttribute *node = attributeSet.Find(attrib->NameTStr());
 #else
           TiXmlAttribute *node = attributeSet.Find(attrib->Name());
 #endif
           if (node != nullptr) {
             if (document != nullptr)
               document->SetError(TIXML_ERROR_PARSING_ELEMENT, pErr, data, encoding);
             delete attrib;
             return nullptr;
           }
           attributeSet.Add(attrib);
         }
       }
       return p;
     }
void dqm4hep::core::TiXmlElement::Print (FILE * cfile, int depth) const override virtual
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements dqm4hep::core::TiXmlBase.
Definition at line 615 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::First(), dqm4hep::core::TiXmlNode::firstChild, dqm4hep::core::TiXmlNode::lastChild, dqm4hep::core::TiXmlAttribute::Next(), dqm4hep::core::TiXmlNode::NextSibling(), dqm4hep::core::TiXmlBase::Print(), dqm4hep::core::TiXmlNode::ToText(), and dqm4hep::core::TiXmlNode::value.
{
       int i;
       assert(cfile);
       for (i = 0; i < depth; i++) {
         fprintf(cfile, "    ");
       }
       fprintf(cfile, "<%s", value.c_str());
       const TiXmlAttribute *attrib;
       for (attrib = attributeSet.First(); attrib != nullptr; attrib = attrib->Next()) {
         fprintf(cfile, " ");
         attrib->Print(cfile, depth);
       }
       // There are 3 different formatting approaches:
       // 1) An element without children is printed as a <foo /> node
       // 2) An element with only a text child is printed as <foo> text </foo>
       // 3) An element with children is printed on multiple lines.
       TiXmlNode *node;
       if (firstChild == nullptr) {
         fprintf(cfile, " />");
       } else if (firstChild == lastChild && (firstChild->ToText() != nullptr)) {
         fprintf(cfile, ">");
         firstChild->Print(cfile, depth + 1);
         fprintf(cfile, "</%s>", value.c_str());
       } else {
         fprintf(cfile, ">");
         for (node = firstChild; node != nullptr; node = node->NextSibling()) {
           if (node->ToText() == nullptr) {
             fprintf(cfile, "\n");
           }
           node->Print(cfile, depth + 1);
         }
         fprintf(cfile, "\n");
         for (i = 0; i < depth; ++i) {
           fprintf(cfile, "    ");
         }
         fprintf(cfile, "</%s>", value.c_str());
       }
     }
int dqm4hep::core::TiXmlElement::QueryDoubleAttribute (const char * name, double * dval) const
QueryDoubleAttribute examines the attribute - see QueryIntAttribute().
Definition at line 551 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::Find(), dqm4hep::core::TiXmlAttribute::QueryDoubleValue(), and dqm4hep::core::TIXML_NO_ATTRIBUTE.
Referenced by QueryFloatAttribute().
{
       const TiXmlAttribute *attrib = attributeSet.Find(name);
       if (attrib == nullptr)
         return TIXML_NO_ATTRIBUTE;
       return attrib->QueryDoubleValue(dval);
     }
int dqm4hep::core::TiXmlElement::QueryDoubleAttribute (const std::string & name, double * dval) const
int dqm4hep::core::TiXmlElement::QueryFloatAttribute (const char * name, float * _value) const inline
QueryFloatAttribute examines the attribute - see QueryIntAttribute().
Definition at line 1102 of file tinyxml.h.
References QueryDoubleAttribute(), and dqm4hep::core::TIXML_SUCCESS.
{
         double d;
         int result = QueryDoubleAttribute(name, &d);
         if (result == TIXML_SUCCESS) {
           *_value = (float)d;
         }
         return result;
       }
int dqm4hep::core::TiXmlElement::QueryIntAttribute (const char * name, int * ival) const
QueryIntAttribute examines the attribute - it is an alternative to the Attribute() method with richer error checking.
If the attribute is an integer, it is stored in 'value' and the call returns TIXML_SUCCESS. If it is not an integer, it returns TIXML_WRONG_TYPE. If the attribute does not exist, then TIXML_NO_ATTRIBUTE is returned.
Definition at line 535 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::Find(), dqm4hep::core::TiXmlAttribute::QueryIntValue(), and dqm4hep::core::TIXML_NO_ATTRIBUTE.
Referenced by dqm4hep::core::XMLParser::resolveForLoops().
{
       const TiXmlAttribute *attrib = attributeSet.Find(name);
       if (attrib == nullptr)
         return TIXML_NO_ATTRIBUTE;
       return attrib->QueryIntValue(ival);
     }
int dqm4hep::core::TiXmlElement::QueryIntAttribute (const std::string & name, int * ival) const
int dqm4hep::core::TiXmlElement::QueryStringAttribute (const char * name, std::string * _value) const inline
QueryStringAttribute examines the attribute - see QueryIntAttribute().
Definition at line 1113 of file tinyxml.h.
Referenced by dqm4hep::core::XMLParser::resolveForLoops().
{
         const char *cstr = Attribute(name);
         if (cstr != nullptr) {
           *_value = std::string(cstr);
           return TIXML_SUCCESS;
         }
         return TIXML_NO_ATTRIBUTE;
       }
template<typename T > int dqm4hep::core::TiXmlElement::QueryValueAttribute (const std::string & name, T * outValue) const inline
Template form of the attribute query which will try to read the attribute into the specified type.
Very easy, very powerful, but be careful to make sure to call this with the correct type.
NOTE: This method doesn't work correctly for 'string' types that contain spaces.
Returns
TIXML_SUCCESS, TIXML_WRONG_TYPE, or TIXML_NO_ATTRIBUTE
Definition at line 1131 of file tinyxml.h.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::Find(), dqm4hep::core::TIXML_NO_ATTRIBUTE, dqm4hep::core::TIXML_SUCCESS, dqm4hep::core::TIXML_WRONG_TYPE, and dqm4hep::core::TiXmlAttribute::ValueStr().
{
         const TiXmlAttribute *node = attributeSet.Find(name);
         if (!node)
           return TIXML_NO_ATTRIBUTE;
         std::stringstream sstream(node->ValueStr());
         sstream >> *outValue;
         if (!sstream.fail())
           return TIXML_SUCCESS;
         return TIXML_WRONG_TYPE;
       }
int dqm4hep::core::TiXmlElement::QueryValueAttribute (const std::string & name, std::string * outValue) const inline
Definition at line 1143 of file tinyxml.h.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::Find(), dqm4hep::core::TIXML_NO_ATTRIBUTE, dqm4hep::core::TIXML_SUCCESS, and dqm4hep::core::TiXmlAttribute::ValueStr().
{
         const TiXmlAttribute *node = attributeSet.Find(name);
         if (node == nullptr)
           return TIXML_NO_ATTRIBUTE;
         *outValue = node->ValueStr();
         return TIXML_SUCCESS;
       }
const char * dqm4hep::core::TiXmlElement::ReadValue (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) protected
Definition at line 1033 of file tinyxmlparser.cc.
References dqm4hep::core::TiXmlNode::GetDocument(), dqm4hep::core::TiXmlNode::Identify(), dqm4hep::core::TiXmlBase::IsWhiteSpaceCondensed(), dqm4hep::core::TiXmlNode::LinkEndChild(), dqm4hep::core::TiXmlBase::Parse(), dqm4hep::core::TiXmlDocument::SetError(), dqm4hep::core::TiXmlBase::SkipWhiteSpace(), dqm4hep::core::TiXmlBase::StringEqual(), and dqm4hep::core::TiXmlBase::TIXML_ERROR_READING_ELEMENT_VALUE.
Referenced by Parse().
{
       TiXmlDocument *document = GetDocument();
       // Read in text and elements in any order.
       const char *pWithWhiteSpace = p;
       p = SkipWhiteSpace(p, encoding);
       while ((p != nullptr) && (*p != 0)) {
         if (*p != '<') {
           // Take what we have, make a text element.
           auto textNode = new TiXmlText("");
           if (textNode == nullptr) {
             return nullptr;
           }
           if (TiXmlBase::IsWhiteSpaceCondensed()) {
             p = textNode->Parse(p, data, encoding);
           } else {
             // Special case: we want to keep the white space
             // so that leading spaces aren't removed.
             p = textNode->Parse(pWithWhiteSpace, data, encoding);
           }
           if (!textNode->Blank())
             LinkEndChild(textNode);
           else
             delete textNode;
         } else {
           // We hit a '<'
           // Have we hit a new element or an end tag? This could also be
           // a TiXmlText in the "CDATA" style.
           if (StringEqual(p, "</", false, encoding)) {
             return p;
           }
           TiXmlNode *node = Identify(p, encoding);
           if (node != nullptr) {
             p = node->Parse(p, data, encoding);
             LinkEndChild(node);
           } else {
             return nullptr;
           }
         }
         pWithWhiteSpace = p;
         p = SkipWhiteSpace(p, encoding);
       }
       if (p == nullptr) {
         if (document != nullptr)
           document->SetError(TIXML_ERROR_READING_ELEMENT_VALUE, nullptr, nullptr, encoding);
       }
       return p;
     }
void dqm4hep::core::TiXmlElement::RemoveAttribute (const char * name)
Deletes an attribute with the given name.
Definition at line 364 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::Find(), dqm4hep::core::TiXmlAttributeSet::Remove(), and TIXML_STRING.
Referenced by RemoveAttribute().
{
 #ifdef TIXML_USE_STL
       TIXML_STRING str(name);
       TiXmlAttribute *node = attributeSet.Find(str);
 #else
       TiXmlAttribute *node = attributeSet.Find(name);
 #endif
       if (node != nullptr) {
         attributeSet.Remove(node);
         delete node;
       }
     }
void dqm4hep::core::TiXmlElement::RemoveAttribute (const std::string & name) inline
STL std::string form.
Definition at line 1186 of file tinyxml.h.
References RemoveAttribute().
void dqm4hep::core::TiXmlElement::SetAttribute (const char * cname, const char * cvalue)
Sets an attribute of name to a given value.
The attribute will be created if it does not exist, or changed if it does.
Definition at line 599 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::FindOrCreate(), and dqm4hep::core::TiXmlAttribute::SetValue().
Referenced by CopyTo().
{
       TiXmlAttribute *attrib = attributeSet.FindOrCreate(cname);
       if (attrib != nullptr) {
         attrib->SetValue(cvalue);
       }
     }
void dqm4hep::core::TiXmlElement::SetAttribute (const std::string & _name, const std::string & _value)
STL std::string form.
STL std::string form.
void dqm4hep::core::TiXmlElement::SetAttribute (const std::string & name, int val)
STL std::string form.
void dqm4hep::core::TiXmlElement::SetAttribute (const char * name, int val)
Sets an attribute of name to a given value.
The attribute will be created if it does not exist, or changed if it does.
Definition at line 567 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::FindOrCreate(), and dqm4hep::core::TiXmlAttribute::SetIntValue().
{
       TiXmlAttribute *attrib = attributeSet.FindOrCreate(name);
       if (attrib != nullptr) {
         attrib->SetIntValue(val);
       }
     }
void dqm4hep::core::TiXmlElement::SetDoubleAttribute (const std::string & name, double val)
void dqm4hep::core::TiXmlElement::SetDoubleAttribute (const char * name, double val)
Sets an attribute of name to a given value.
The attribute will be created if it does not exist, or changed if it does.
Definition at line 583 of file tinyxml.cc.
References attributeSet, dqm4hep::core::TiXmlAttributeSet::FindOrCreate(), and dqm4hep::core::TiXmlAttribute::SetDoubleValue().
{
       TiXmlAttribute *attrib = attributeSet.FindOrCreate(name);
       if (attrib != nullptr) {
         attrib->SetDoubleValue(val);
       }
     }
void dqm4hep::core::TiXmlElement::StreamIn (std::istream * in, TIXML_STRING * tag) override protected virtual
Implements dqm4hep::core::TiXmlNode.
const TiXmlElement* dqm4hep::core::TiXmlElement::ToElement () const inline override virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::core::TiXmlNode.
Definition at line 1248 of file tinyxml.h.
Referenced by dqm4hep::core::XMLParser::resolveConstantsInElement().
TiXmlElement* dqm4hep::core::TiXmlElement::ToElement () inline override virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::core::TiXmlNode.
Definition at line 1251 of file tinyxml.h.
Member Data Documentation
TiXmlAttributeSet dqm4hep::core::TiXmlElement::attributeSet = {} private
Definition at line 1274 of file tinyxml.h.
Referenced by Accept(), Attribute(), ClearThis(), CopyTo(), FirstAttribute(), LastAttribute(), Parse(), Print(), QueryDoubleAttribute(), QueryIntAttribute(), QueryValueAttribute(), RemoveAttribute(), SetAttribute(), and SetDoubleAttribute().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc