DQM4hep: dqm4hep::core::BufferEvent Class Reference
dqm4hep::core::BufferEvent Class Reference
BufferEvent class.
#include <BufferEvent.h>
Classes
struct Buffer
Buffer struct.
Public Member Functions
BufferEvent ()=default
~BufferEvent ()
Destructor.
void copyBuffer (const char *const b, std::size_t len)
Copy the target buffer in the event structure using memcpy.
void moveBuffer (char *b, std::size_t len)
Move the user buffer to the event structure.
void handleBuffer (char *b, std::size_t len)
Let the event structure handle the buffer.
const char * buffer () const
Access the event internal buffer.
std::size_t bufferSize () const
Access the event internal buffer length.
void clear ()
Clear the internal event buffer.
Static Public Member Functions
static EventPtr make_shared ()
Allocate a shared pointer of EventPtr.
Private Attributes
Buffer m_buffer = {}
The internal buffer handler.
Detailed Description
BufferEvent class.
Definition at line 26 of file BufferEvent.h.
Constructor & Destructor Documentation
dqm4hep::core::BufferEvent::BufferEvent () default
Referenced by make_shared().
dqm4hep::core::BufferEvent::~BufferEvent ()
Destructor.
Definition at line 19 of file BufferEvent.cc.
References clear().
{
       clear();
     }
Member Function Documentation
const char * dqm4hep::core::BufferEvent::buffer () const
Access the event internal buffer.
Definition at line 70 of file BufferEvent.cc.
References dqm4hep::core::BufferEvent::Buffer::m_buffer, and m_buffer.
Referenced by dqm4hep::core::BufferEventStreamer::write().
{
       return m_buffer.m_buffer;
     }
std::size_t dqm4hep::core::BufferEvent::bufferSize () const
Access the event internal buffer length.
Definition at line 76 of file BufferEvent.cc.
References m_buffer, and dqm4hep::core::BufferEvent::Buffer::m_size.
Referenced by dqm4hep::core::BufferEventStreamer::write().
{
       return m_buffer.m_size;
     }
void dqm4hep::core::BufferEvent::clear ()
Clear the internal event buffer.
Definition at line 82 of file BufferEvent.cc.
References dqm4hep::core::BufferEvent::Buffer::m_buffer, m_buffer, dqm4hep::core::BufferEvent::Buffer::m_isOwner, and dqm4hep::core::BufferEvent::Buffer::m_size.
Referenced by copyBuffer(), handleBuffer(), moveBuffer(), and ~BufferEvent().
{
       if( nullptr != m_buffer.m_buffer && m_buffer.m_isOwner ) {
         delete [] m_buffer.m_buffer;
       }
       m_buffer.m_buffer = nullptr;
       m_buffer.m_size = 0;
     }
void dqm4hep::core::BufferEvent::copyBuffer (const char *const b, std::size_t len)
Copy the target buffer in the event structure using memcpy.
The input buffer is still owned by the user after calling this method.
Parameters
b the buffer to copy
len the buffer length
Definition at line 33 of file BufferEvent.cc.
References clear(), dqm4hep::core::BufferEvent::Buffer::m_buffer, m_buffer, dqm4hep::core::BufferEvent::Buffer::m_isOwner, and dqm4hep::core::BufferEvent::Buffer::m_size.
{
       if(nullptr == b) {
         return;
       }
       clear();
       m_buffer.m_size = len;
       m_buffer.m_buffer = new char[len];
       m_buffer.m_isOwner = true;
       memcpy(m_buffer.m_buffer, b, len);
     }
void dqm4hep::core::BufferEvent::handleBuffer (char * b, std::size_t len)
Let the event structure handle the buffer.
The buffer is not copied and not owned by the event structure. ATN: This method is typically used for optimizing data transfer while sending event using an event source. As the handled buffer is still owned by the user, it can be deleted by the user leading to an invalid state of the internal event buffer. To make sure the event is not in an invalid state after buffer deletion in this case, use the method clear() right after the buffer deletion.
Parameters
b the buffer to handle
len the buffer length
Definition at line 58 of file BufferEvent.cc.
References clear(), dqm4hep::core::BufferEvent::Buffer::m_buffer, m_buffer, dqm4hep::core::BufferEvent::Buffer::m_isOwner, and dqm4hep::core::BufferEvent::Buffer::m_size.
{
       if(nullptr == b) {
         return;
       }
       clear();
       m_buffer.m_size = len;
       m_buffer.m_buffer = b;
       m_buffer.m_isOwner = false;
     }
EventPtr dqm4hep::core::BufferEvent::make_shared () static
Allocate a shared pointer of EventPtr.
Definition at line 25 of file BufferEvent.cc.
References BufferEvent().
{
       auto ptr = std::shared_ptr<Event>(new EventBase<BufferEvent>(new BufferEvent()));
       ptr->setStreamerName("BufferEventStreamer");
       return ptr;
     }
void dqm4hep::core::BufferEvent::moveBuffer (char * b, std::size_t len)
Move the user buffer to the event structure.
The buffer is not copied and is owned by the event after calling this method.
Parameters
b the buffer to move
len the buffer length
Definition at line 46 of file BufferEvent.cc.
References clear(), dqm4hep::core::BufferEvent::Buffer::m_buffer, m_buffer, dqm4hep::core::BufferEvent::Buffer::m_isOwner, and dqm4hep::core::BufferEvent::Buffer::m_size.
Referenced by dqm4hep::core::BufferEventStreamer::read().
{
       if(nullptr == b) {
         return;
       }
       clear();
       m_buffer.m_size = len;
       m_buffer.m_buffer = b;
       m_buffer.m_isOwner = true;
     }
Member Data Documentation
Buffer dqm4hep::core::BufferEvent::m_buffer = {} private
The internal buffer handler.
Definition at line 102 of file BufferEvent.h.
Referenced by buffer(), bufferSize(), clear(), copyBuffer(), handleBuffer(), and moveBuffer().
The documentation for this class was generated from the following files:
BufferEvent.h
BufferEvent.cc