DQM4hep: dqm4hep::core::ROOTHandle Class Reference
dqm4hep::core::ROOTHandle Class Reference
ROOTHandle class Special handle for ROOT objects.
#include <Handle.h>
Public Member Functions
ROOTHandle ()=delete
~ROOTHandle ()=default
ROOTHandle (const ROOTHandle &)=delete
ROOTHandle (ROOTHandle &&)=default
ROOTHandle & operator= (const ROOTHandle &)=delete
template<typename T >
ROOTHandle (T *ptr)
Constructor.
template<typename T >
ROOTHandle (std::shared_ptr< T > ptr)
Constructor.
ROOTHandle create () const
Create a new handle based on the same underlying type.
TClass * getClass () const
Get the ROOT object class.
Public Member Functions inherited from dqm4hep::core::Handle
Handle ()=delete
~Handle ()=default
Handle (const Handle &)=delete
Handle (Handle &&)=default
Handle & operator= (const Handle &)=delete
template<typename T >
Handle (T *ptr)
Constructor.
template<typename T >
Handle (std::shared_ptr< T > ptr)
Constructor.
template<typename T >
std::shared_ptr< T > ptr () const
Retrieve the handled pointer as a specific type.
Handle create () const
Create a new handle based on the same underlying type.
void * raw ()
Retrieve the handled pointer as raw pointer.
const void * raw () const
Retrieve the handled pointer as raw pointer (const version)
const std::type_index & typeInfo () const
Retrieve the handled pointer type information.
bool isValid () const
Whether the handled pointer is valid (non nullptr)
Private Attributes
TClass * m_class = {nullptr}
The ROOT object class.
Additional Inherited Members
Protected Attributes inherited from dqm4hep::core::Handle
std::shared_ptr< void > m_ptr = {nullptr}
The handled pointer.
std::type_index m_typeInfo
The type information of the handled type.
std::function< Handle(void)> m_newFunction = {nullptr}
A custom allocator function based on the underlying type.
Detailed Description
ROOTHandle class Special handle for ROOT objects.
ROOT I/O API requires to know the type or at least the TClass of the object to read or write
Definition at line 104 of file Handle.h.
Constructor & Destructor Documentation
dqm4hep::core::ROOTHandle::ROOTHandle () delete
Referenced by ROOTHandle().
dqm4hep::core::ROOTHandle::~ROOTHandle () default
dqm4hep::core::ROOTHandle::ROOTHandle (const ROOTHandle &) delete
dqm4hep::core::ROOTHandle::ROOTHandle (ROOTHandle &&) default
template<typename T > dqm4hep::core::ROOTHandle::ROOTHandle (T * ptr) inline
Constructor.
Parameters
ptr a ROOT object ptr to handle
Definition at line 177 of file Handle.h.
References dqm4hep::core::Handle::m_newFunction, and ROOTHandle().
                                         :
       Handle(ptr),
       m_class(TClass::GetClass(typeid(T))) {
       m_newFunction = []() {
         return ROOTHandle(new T());
       };
     }
template<typename T > dqm4hep::core::ROOTHandle::ROOTHandle (std::shared_ptr< T > ptr) inline
Constructor.
Parameters
ptr a ROOT object shared ptr to handle
Definition at line 188 of file Handle.h.
References dqm4hep::core::Handle::m_newFunction, and ROOTHandle().
                                                       :
       Handle(ptr),
       m_class(TClass::GetClass(typeid(T))) {
       m_newFunction = []() {
         return ROOTHandle(new T());
       };
     }
Member Function Documentation
ROOTHandle dqm4hep::core::ROOTHandle::create () const
Create a new handle based on the same underlying type.
TClass * dqm4hep::core::ROOTHandle::getClass () const
Get the ROOT object class.
Definition at line 49 of file Handle.cc.
References m_class.
{
       return m_class;
     }
ROOTHandle& dqm4hep::core::ROOTHandle::operator= (const ROOTHandle &) delete
Member Data Documentation
TClass* dqm4hep::core::ROOTHandle::m_class = {nullptr} private
The ROOT object class.
Definition at line 140 of file Handle.h.
Referenced by getClass().
The documentation for this class was generated from the following files:
Handle.h
Handle.cc