DQM4hep: dqm4hep::core::GenericEventXMLReader Class Reference
dqm4hep::core::GenericEventXMLReader Class Reference
GenericEventXMLReader class Read an XML and read GenericEvent events from it.
Public Member Functions
GenericEventXMLReader ()=default
~GenericEventXMLReader () override
GenericEventXMLReader (const GenericEventXMLReader &)=delete
GenericEventXMLReader & operator= (const GenericEventXMLReader &)=delete
core::StatusCode open (const std::string &fname) override
Open a new file.
core::StatusCode skipNEvents (int nEvents) override
Skip n events from the current position (usually from beginning of file)
core::StatusCode runInfo (core::Run &run) override
Extract the run info from file.
core::StatusCode readNextEvent () override
Read next event in the file and post it using the signal.
core::StatusCode close () override
Close the current file.
Public Member Functions inherited from dqm4hep::core::EventReader
virtual ~EventReader ()
Destructor.
core::Signal< core::EventPtr > & onEventRead ()
Get the signal on event read.
Private Attributes
TiXmlDocument m_document = {}
TiXmlElement * m_currentEvent = {nullptr}
Additional Inherited Members
Protected Attributes inherited from dqm4hep::core::EventReader
core::Signal< core::EventPtr > m_onEventRead = {}
The signal on event read.
Detailed Description
GenericEventXMLReader class Read an XML and read GenericEvent events from it.
Definition at line 27 of file GenericEventXMLReader.cc.
Constructor & Destructor Documentation
dqm4hep::core::GenericEventXMLReader::GenericEventXMLReader () default
dqm4hep::core::GenericEventXMLReader::~GenericEventXMLReader () override
Definition at line 48 of file GenericEventXMLReader.cc.
{
       /* nop */
     }
dqm4hep::core::GenericEventXMLReader::GenericEventXMLReader (const GenericEventXMLReader &) delete
Member Function Documentation
core::StatusCode dqm4hep::core::GenericEventXMLReader::close () override virtual
Close the current file.
Implements dqm4hep::core::EventReader.
Definition at line 203 of file GenericEventXMLReader.cc.
References dqm4hep::core::TiXmlNode::Clear(), and m_document.
{
       m_document.Clear();
       return STATUS_CODE_SUCCESS;
     }
core::StatusCode dqm4hep::core::GenericEventXMLReader::open (const std::string & fname) override virtual
Open a new file.
Parameters
fname the file name to open
Implements dqm4hep::core::EventReader.
Definition at line 54 of file GenericEventXMLReader.cc.
References dqm_error, dqm4hep::core::TiXmlDocument::ErrorCol(), dqm4hep::core::TiXmlDocument::ErrorDesc(), dqm4hep::core::TiXmlDocument::ErrorRow(), dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::TiXmlDocument::LoadFile(), m_currentEvent, m_document, and dqm4hep::core::TiXmlDocument::RootElement().
{
       if(not m_document.LoadFile(fname)) {
         dqm_error("GenericEventXMLReader::open(): couldn't load xml file ['{0}', row: {1}, col: {2}] : {3}", fname,
                   m_document.ErrorRow(), m_document.ErrorCol(), m_document.ErrorDesc());
         return STATUS_CODE_FAILURE;
       }
       m_currentEvent = m_document.RootElement()->FirstChildElement("event");
       if(nullptr == m_currentEvent) {
         dqm_error( "No event stored in the file '{0}'", fname );
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
GenericEventXMLReader& dqm4hep::core::GenericEventXMLReader::operator= (const GenericEventXMLReader &) delete
core::StatusCode dqm4hep::core::GenericEventXMLReader::readNextEvent () override virtual
Read next event in the file and post it using the signal.
STATUS_CODE_OUT_OF_RANGE is synonym of end of file. Anything else than STATUS_CODE_SUCCESS is considered as an error
Implements dqm4hep::core::EventReader.
Definition at line 125 of file GenericEventXMLReader.cc.
References dqm4hep::core::time::asPoint(), dqm_warning, dqm4hep::core::Signal< Args >::emit(), dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::XmlHelper::getAttribute(), m_currentEvent, dqm4hep::core::GenericEvent::make_shared(), dqm4hep::core::TiXmlNode::NextSiblingElement(), dqm4hep::core::EventReader::onEventRead(), dqm4hep::core::XmlHelper::readParameter(), RETURN_RESULT_IF, RETURN_RESULT_IF_AND_IF, dqm4hep::core::tokenize(), and dqm4hep::core::UNKNOWN_EVENT.
{
       EventPtr event = GenericEvent::make_shared();
       GenericEvent *generic = event->getEvent<GenericEvent>();
       // end of file !
       if(nullptr == m_currentEvent) {
         return STATUS_CODE_OUT_OF_RANGE;
       }
       TiXmlHandle handle(m_currentEvent);
       int32_t eventType = static_cast<int32_t>(UNKNOWN_EVENT);
       std::string source;
       int32_t timeStamp = 0, eventNumber = 0, runNumber = 0;
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "EventType", eventType));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "Source", source));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "TimeStamp", timeStamp));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "EventNumber", eventNumber));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "RunNumber", runNumber));
       event->setType(static_cast<EventType>(eventType));
       event->setSource(source);
       event->setTimeStamp(core::time::asPoint(timeStamp));
       event->setEventNumber(eventNumber);
       event->setRunNumber(runNumber);
       // loop over <field> elements
       for(auto field = m_currentEvent->FirstChildElement("field") ; nullptr != field ; field = field->NextSiblingElement("field")) {
         std::string name, type;
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(field, "name", name));
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(field, "type", type));
         if("int" == type) {
           if(nullptr == field->GetText()) {
             return STATUS_CODE_FAILURE;
           }
           std::string content = field->GetText();
           IntVector values;
           core::tokenize(content, values, " ");
           generic->setValues(name, values);
         }
         else if("float" == type) {
           if(nullptr == field->GetText()) {
             return STATUS_CODE_FAILURE;
           }
           std::string content = field->GetText();
           FloatVector values;
           core::tokenize(content, values, " ");
           generic->setValues(name, values);
         }
         else if("double" == type) {
           if(nullptr == field->GetText()) {
             return STATUS_CODE_FAILURE;
           }
           std::string content = field->GetText();
           DoubleVector values;
           core::tokenize(content, values, " ");
           generic->setValues(name, values);
         }
         else if("string" == type) {
           StringVector values;
           // Wrap string into <str> </str> elements to avoid string tokenize
           for(auto strElement = field->FirstChildElement("str") ; nullptr != strElement ; strElement = strElement->NextSiblingElement("str")) {
             values.push_back(strElement->GetText() != nullptr ? strElement->GetText() : "");
           }
           generic->setValues(name, values);
         }
         else {
           dqm_warning( "Unrecognized field type '{0}' ! Skipping ...", type );
           continue;
         }
       }
       onEventRead().emit(event);
       m_currentEvent = m_currentEvent->NextSiblingElement("event");
       return STATUS_CODE_SUCCESS;
     }
core::StatusCode dqm4hep::core::GenericEventXMLReader::runInfo (core::Run & run) override virtual
Extract the run info from file.
Parameters
run the run to receive
Implements dqm4hep::core::EventReader.
Definition at line 87 of file GenericEventXMLReader.cc.
References dqm4hep::core::time::asPoint(), dqm_error, dqm4hep::core::TiXmlNode::FirstChildElement(), m_document, dqm4hep::core::XmlHelper::parseParameterElement(), dqm4hep::core::XmlHelper::readParameter(), RETURN_RESULT_IF, RETURN_RESULT_IF_AND_IF, dqm4hep::core::TiXmlDocument::RootElement(), dqm4hep::core::Run::setDescription(), dqm4hep::core::Run::setDetectorName(), dqm4hep::core::Run::setEndTime(), dqm4hep::core::Run::setParameter(), dqm4hep::core::Run::setRunNumber(), dqm4hep::core::Run::setStartTime(), and dqm4hep::core::TiXmlNode::ValueStr().
{
       auto runInfoElement = m_document.RootElement()->FirstChildElement("run");
       if(!runInfoElement) {
         dqm_error( "No run info available in file '{0}'", m_document.ValueStr() );
         return STATUS_CODE_NOT_FOUND;
       }
       TiXmlHandle handle(runInfoElement);
       int runNumber = 0;
       int32_t startTime = 0, endTime = 0;
       std::string description, detectorName;
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "RunNumber", runNumber));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "StartTime", startTime));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "EndTime", endTime));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "Description", description));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(handle,
         "DetectorName", detectorName));
       auto parameters = runInfoElement->FirstChildElement("parameters");
       if(nullptr != parameters) {
         for(auto child = parameters->FirstChildElement("parameter") ; nullptr != child ; child = child->NextSiblingElement("parameter")) {
           std::string name, value;
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::parseParameterElement(child, name, value));
           run.setParameter(name, value);
         }
       }
       run.setRunNumber(runNumber);
       run.setStartTime(core::time::asPoint(startTime));
       run.setEndTime(core::time::asPoint(endTime));
       run.setDescription(description);
       run.setDetectorName(detectorName);
       return STATUS_CODE_SUCCESS;
     }
core::StatusCode dqm4hep::core::GenericEventXMLReader::skipNEvents (int nEvents) override virtual
Skip n events from the current position (usually from beginning of file)
Parameters
nEvents the number of event to skip
Implements dqm4hep::core::EventReader.
Definition at line 70 of file GenericEventXMLReader.cc.
References dqm_error, m_currentEvent, m_document, dqm4hep::core::TiXmlNode::NextSiblingElement(), and dqm4hep::core::TiXmlNode::ValueStr().
{
       int nSkippedEvents = 0;
       while(1) {
         if(nSkippedEvents == nEvents)
           break;
         m_currentEvent = m_currentEvent->NextSiblingElement("event");
         if(nullptr == m_currentEvent) {
           dqm_error( "Couldn't skip {0} events in file '{1}' : file has less than {1}", nEvents, m_document.ValueStr() );
           return STATUS_CODE_OUT_OF_RANGE;
         }
         nSkippedEvents++;
       }
       return STATUS_CODE_SUCCESS;
     }
Member Data Documentation
TiXmlElement* dqm4hep::core::GenericEventXMLReader::m_currentEvent = {nullptr} private
Definition at line 42 of file GenericEventXMLReader.cc.
Referenced by open(), readNextEvent(), and skipNEvents().
TiXmlDocument dqm4hep::core::GenericEventXMLReader::m_document = {} private
Definition at line 41 of file GenericEventXMLReader.cc.
Referenced by close(), open(), runInfo(), and skipNEvents().
The documentation for this class was generated from the following file:
GenericEventXMLReader.cc