DQM4hep: dqm4hep::core::PtrHandler< T > Class Template Reference
dqm4hep::core::PtrHandler< T > Class Template Reference
PtrHandler template class.
#include <PtrHandler.h>
Public Member Functions
PtrHandler (T *ptr=nullptr, bool owner=true)
Constructor.
T * take ()
Take the pointer, setting the handle pointer to nullptr.
void set (T *ptr, bool owner=true)
Set the pointer and ownership.
void clear ()
Clear the ptr.
T * ptr () const
Get the ptr.
bool isOwner () const
Whether the handler owns the ptr.
const T * operator-> () const
Pointer operator.
T * operator-> ()
Pointer operator.
const T & operator* () const
Reference operator.
T & operator* ()
Reference operator.
operator bool () const
Boolean operator.
Private Attributes
T * m_ptr
The handled pointer.
bool m_owner
Whether the pointer is owned by the handler.
Friends
template<typename S >
bool operator== (const PtrHandler< S > &lhs, const PtrHandler< S > &rhs)
template<typename S >
bool operator== (const S *lhs, const PtrHandler< S > &rhs)
template<typename S >
bool operator== (const PtrHandler< S > &lhs, const S *rhs)
template<typename S >
bool operator!= (const PtrHandler< S > &lhs, const PtrHandler< S > &rhs)
template<typename S >
bool operator!= (const S *lhs, const PtrHandler< S > &rhs)
template<typename S >
bool operator!= (const PtrHandler< S > &lhs, const S *rhs)
template<typename S >
bool operator== (std::nullptr_t lhs, const PtrHandler< S > &rhs)
template<typename S >
bool operator== (const PtrHandler< S > &lhs, std::nullptr_t rhs)
template<typename S >
bool operator!= (std::nullptr_t lhs, const PtrHandler< S > &rhs)
template<typename S >
bool operator!= (const PtrHandler< S > &lhs, std::nullptr_t rhs)
Detailed Description
template<typename T>
class dqm4hep::core::PtrHandler< T >
PtrHandler template class.
Definition at line 24 of file PtrHandler.h.
Constructor & Destructor Documentation
template<typename T> dqm4hep::core::PtrHandler< T >::PtrHandler (T * ptr = nullptr, bool owner = true) inline
Constructor.
Definition at line 102 of file PtrHandler.h.
                                                            : m_ptr(pointer), m_owner(owner) {
       /* nop */
     }
Member Function Documentation
template<typename T > void dqm4hep::core::PtrHandler< T >::clear () inline
Clear the ptr.
Delete if owned and set to nullptr
Definition at line 127 of file PtrHandler.h.
Referenced by dqm4hep::core::MonitorElement::fromJson(), dqm4hep::core::MonitorElement::reset(), dqm4hep::core::MonitorElement::set(), dqm4hep::core::MonitorElement::setMonitorObject(), and dqm4hep::core::MonitorElement::setReferenceObject().
{
       if (m_owner && nullptr != m_ptr)
         delete m_ptr;
       m_ptr = nullptr;
     }
template<typename T > bool dqm4hep::core::PtrHandler< T >::isOwner () const inline
Whether the handler owns the ptr.
Definition at line 143 of file PtrHandler.h.
{
       return m_owner;
     }
template<typename T > dqm4hep::core::PtrHandler< T >::operator bool () const inline
Boolean operator.
Definition at line 178 of file PtrHandler.h.
{
       return m_ptr != nullptr;
     }
template<typename T > const T & dqm4hep::core::PtrHandler< T >::operator* () const inline
Reference operator.
Definition at line 164 of file PtrHandler.h.
{
       return *m_ptr;
     }
template<typename T > T & dqm4hep::core::PtrHandler< T >::operator* () inline
Reference operator.
Definition at line 171 of file PtrHandler.h.
{
       return *m_ptr;
     }
template<typename T > const T * dqm4hep::core::PtrHandler< T >::operator-> () const inline
Pointer operator.
Definition at line 150 of file PtrHandler.h.
{
       return m_ptr;
     }
template<typename T > T * dqm4hep::core::PtrHandler< T >::operator-> () inline
Pointer operator.
Definition at line 157 of file PtrHandler.h.
{
       return m_ptr;
     }
template<typename T > T * dqm4hep::core::PtrHandler< T >::ptr () const inline
Get the ptr.
Definition at line 136 of file PtrHandler.h.
Referenced by dqm4hep::core::MonitorElement::object(), dqm4hep::core::MonitorElement::reference(), dqm4hep::core::MonitorElement::set(), dqm4hep::core::MonitorElement::setMonitorObject(), dqm4hep::core::MonitorElement::setName(), dqm4hep::core::MonitorElement::setReferenceObject(), dqm4hep::core::MonitorElement::setTitle(), and dqm4hep::core::MonitorElement::toJson().
{
       return m_ptr;
     }
template<typename T> void dqm4hep::core::PtrHandler< T >::set (T * ptr, bool owner = true) inline
Set the pointer and ownership.
Definition at line 118 of file PtrHandler.h.
Referenced by dqm4hep::core::MonitorElement::fromJson(), dqm4hep::core::MonitorElement::read(), dqm4hep::core::MonitorElement::set(), dqm4hep::core::MonitorElement::setMonitorObject(), and dqm4hep::core::MonitorElement::setReferenceObject().
{
       this->clear();
       m_ptr = pointer;
       m_owner = owner;
     }
template<typename T > T * dqm4hep::core::PtrHandler< T >::take () inline
Take the pointer, setting the handle pointer to nullptr.
The ownership is transfered to the caller
Definition at line 109 of file PtrHandler.h.
{
       T *pointer = m_ptr;
       m_ptr = nullptr;
       return pointer;
     }
Friends And Related Function Documentation
template<typename T> template<typename S > bool operator!= (const PtrHandler< S > & lhs, const PtrHandler< S > & rhs) friend
template<typename T> template<typename S > bool operator!= (const S * lhs, const PtrHandler< S > & rhs) friend
template<typename T> template<typename S > bool operator!= (const PtrHandler< S > & lhs, const S * rhs) friend
template<typename T> template<typename S > bool operator!= (std::nullptr_t lhs, const PtrHandler< S > & rhs) friend
Definition at line 241 of file PtrHandler.h.
{
       return lhs != rhs.m_ptr;
     }
template<typename T> template<typename S > bool operator!= (const PtrHandler< S > & lhs, std::nullptr_t rhs) friend
Definition at line 248 of file PtrHandler.h.
{
       return lhs.m_ptr != rhs;
     }
template<typename T> template<typename S > bool operator== (const PtrHandler< S > & lhs, const PtrHandler< S > & rhs) friend
template<typename T> template<typename S > bool operator== (const S * lhs, const PtrHandler< S > & rhs) friend
template<typename T> template<typename S > bool operator== (const PtrHandler< S > & lhs, const S * rhs) friend
template<typename T> template<typename S > bool operator== (std::nullptr_t lhs, const PtrHandler< S > & rhs) friend
Definition at line 227 of file PtrHandler.h.
{
       return lhs == rhs.m_ptr;
     }
template<typename T> template<typename S > bool operator== (const PtrHandler< S > & lhs, std::nullptr_t rhs) friend
Definition at line 234 of file PtrHandler.h.
{
       return lhs.m_ptr == rhs;
     }
Member Data Documentation
template<typename T> bool dqm4hep::core::PtrHandler< T >::m_owner private
Whether the pointer is owned by the handler.
Definition at line 74 of file PtrHandler.h.
template<typename T> T* dqm4hep::core::PtrHandler< T >::m_ptr private
The handled pointer.
Definition at line 73 of file PtrHandler.h.
Referenced by dqm4hep::core::operator!=(), and dqm4hep::core::operator==().
The documentation for this class was generated from the following file:
PtrHandler.h