DQM4hep: dqm4hep::core::Archiver Class Reference
dqm4hep::core::Archiver Class Reference
Archiver class.
#include <Archiver.h>
Public Types
typedef std::function< bool(MonitorElementPtr)> SelectorFunction
Public Member Functions
Archiver (const Archiver &)=delete
Archiver & operator= (const Archiver &)=delete
Archiver ()
Default constructor.
~Archiver ()
Destructor.
StatusCode open (const std::string &fname, const std::string &opMode="RECREATE", bool overwrite=true, int runNumber=-1)
Open a new archive.
StatusCode close ()
Close the current archive.
void setSelectorFunction (std::function< bool(MonitorElementPtr)> func)
Set the selector function to use on write operation.
StatusCode archive (const Storage< MonitorElement > &storage, const std::string &dirName="")
Archive the monitor element storage in the ROOT file.
StatusCode archiveWithReferences (const Storage< MonitorElement > &storage, const std::string &dirName="", const std::string &refSuffix="_ref")
Archive the monitor element storage in the ROOT file.
const std::string & fileName () const
Get the file name.
bool isOpened () const
Whether the archive is opened.
const std::string & openingMode () const
Get the opening mode of this archive.
Private Member Functions
StatusCode prepareForArchiving (const std::string &dirName, TDirectory *&directory)
Prepare the ROOT file for archiving.
StatusCode recursiveWrite (MonitorElementDir directory, TDirectory *rootDirectory, const std::string &refSuffix="")
Fill recursively the TDirectory with the Directory.
StatusCode writeMonitorElements (MonitorElementDir directory, TDirectory *rootDirectory, const std::string &refSuffix="")
Write the monitor elements contained in the Directory in the TDirectory.
Private Attributes
std::string m_fileName = {""}
The archive file name.
std::string m_openingMode = {"RECREATE"}
The root file opening mode.
bool m_isOpened = {false}
SelectorFunction m_selectorFunction = {nullptr}
The selector function.
std::unique_ptr< TFile > m_file = {nullptr}
The actual archive implementation (root file)
Detailed Description
Archiver class.
Definition at line 36 of file Archiver.h.
Member Typedef Documentation
typedef std::function<bool(MonitorElementPtr)> dqm4hep::core::Archiver::SelectorFunction
Definition at line 41 of file Archiver.h.
Constructor & Destructor Documentation
dqm4hep::core::Archiver::Archiver (const Archiver &) delete
dqm4hep::core::Archiver::Archiver ()
Default constructor.
Definition at line 27 of file Archiver.cc.
References m_selectorFunction.
{
       m_selectorFunction = [](MonitorElementPtr)->bool{return true;};
     }
dqm4hep::core::Archiver::~Archiver ()
Destructor.
Definition at line 33 of file Archiver.cc.
References close(), and isOpened().
{
       if (isOpened())
         close();
     }
Member Function Documentation
StatusCode dqm4hep::core::Archiver::archive (const Storage< MonitorElement > & storage, const std::string & dirName = "")
Archive the monitor element storage in the ROOT file.
The result can be written in a specific directory using the dirName argument. By default, the content is written directly in the top-level directory
Parameters
storage the storage to archive
dirName the directory in which to archive the storage (optional)
Definition at line 110 of file Archiver.cc.
References m_file, prepareForArchiving(), recursiveWrite(), RETURN_RESULT_IF, and dqm4hep::core::Storage< T >::root().
Referenced by dqm4hep::core::MonitorElementManager::archive().
{
       TDirectory *directory = nullptr;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, prepareForArchiving(dirName, directory));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, recursiveWrite(storage.root(), directory, ""));
       m_file->cd();
       m_file->Write();
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::Archiver::archiveWithReferences (const Storage< MonitorElement > & storage, const std::string & dirName = "", const std::string & refSuffix = "_ref")
Archive the monitor element storage in the ROOT file.
Also archive the references along with the monitor object in the same directory. The reference is written with the same name as the object plus a suffix (default "_ref"). The result can be written in a specific directory using the dirName argument. By default, the content is written directly in the top-level directory.
Parameters
storage the storage to archive
dirName the directory in which to archive the storage (optional)
refSuffix the reference name suffix (optional)
Definition at line 121 of file Archiver.cc.
References m_file, prepareForArchiving(), recursiveWrite(), RETURN_RESULT_IF, and dqm4hep::core::Storage< T >::root().
Referenced by dqm4hep::core::MonitorElementManager::archive().
{
       TDirectory *directory = nullptr;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, prepareForArchiving(dirName, directory));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, recursiveWrite(storage.root(), directory, refSuffix));
       m_file->cd();
       m_file->Write();
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::Archiver::close ()
Close the current archive.
Definition at line 91 of file Archiver.cc.
References isOpened(), m_file, m_isOpened, and m_openingMode.
Referenced by open(), and ~Archiver().
{
       if (not isOpened()) {
         return STATUS_CODE_SUCCESS;
       }
       m_file->Close();
       m_file.reset(nullptr);
       m_isOpened = false;
       m_openingMode = "";
       return STATUS_CODE_SUCCESS;
     }
const std::string & dqm4hep::core::Archiver::fileName () const
Get the file name.
Definition at line 132 of file Archiver.cc.
References m_fileName.
{
       return m_fileName;
     }
bool dqm4hep::core::Archiver::isOpened () const
Whether the archive is opened.
Definition at line 138 of file Archiver.cc.
References m_isOpened.
Referenced by close(), open(), prepareForArchiving(), and ~Archiver().
{
       return m_isOpened;
     }
StatusCode dqm4hep::core::Archiver::open (const std::string & fname, const std::string & opMode = "RECREATE", bool overwrite = true, int runNumber = -1)
Open a new archive.
Close the current file if opened. Supported opening mode are the TFile opening mode option (see TFile). If overwrite is set to false, an id is appended before the .root extension to ensure the file name is unique and no archive is overwritten. If the run number is positive then it is appended in the file name as _IRunNumber.
Parameters
fname the ROOT file name to open
opMode the ROOT file opening mode
overwrite whether to allow for overwrite
runNumber the run number to append to the archive name
Definition at line 40 of file Archiver.cc.
References close(), dqm_error, dqm_info, isOpened(), m_file, m_fileName, m_isOpened, m_openingMode, and RETURN_RESULT_IF.
{
       // if already open write the archive if not done
       // and close it before to re-open
       if (isOpened()) {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, close());
       }
       if (fname.empty()) {
         return STATUS_CODE_INVALID_PARAMETER;
       }
       int fileId(0);
       size_t pos = fname.rfind(".root");
       if (std::string::npos == pos) {
         dqm_error("Couldn't open archive '{0}' ! Must be a root file !", fname);
         return STATUS_CODE_INVALID_PARAMETER;
       }
       std::string baseArchiveName = fname.substr(0, pos);
       std::string fullArchiveName = fname;
       if (not overwrite) {
         while (!gSystem->AccessPathName(fullArchiveName.c_str())) {
           std::stringstream ss;
           ss << baseArchiveName;
           if(runNumber >= 0) {
             ss << "_I" << runNumber;
           }
           ss << "_" << fileId << ".root";
           fullArchiveName = ss.str();
           fileId++;
         }
         m_fileName = fullArchiveName;
       }
       else if(runNumber >= 0) {
         std::stringstream ss;
         ss << baseArchiveName << "_I" << runNumber << ".root";
         m_fileName = ss.str();
       }
       else {
         m_fileName = fname;
       }
       m_openingMode = opMode;
       dqm_info("Archiver::open: Opening archive {0}", m_fileName);
       m_file.reset(new TFile(m_fileName.c_str(), m_openingMode.c_str()));
       if (nullptr == m_file) {
         dqm_error("Archiver::open: Couldn't open archive '{0}' !", m_fileName);
         return STATUS_CODE_FAILURE;
       }
       m_isOpened = true;
       return STATUS_CODE_SUCCESS;
     }
const std::string & dqm4hep::core::Archiver::openingMode () const
Get the opening mode of this archive.
Definition at line 144 of file Archiver.cc.
References m_openingMode.
{
       return m_openingMode;
     }
Archiver& dqm4hep::core::Archiver::operator= (const Archiver &) delete
StatusCode dqm4hep::core::Archiver::prepareForArchiving (const std::string & dirName, TDirectory *& directory) private
Prepare the ROOT file for archiving.
Parameters
dirName the top-level root directory in which the elements will be archived
directory the top-level directory pointer to receive
Definition at line 150 of file Archiver.cc.
References isOpened(), and m_file.
Referenced by archive(), and archiveWithReferences().
{
       if(not isOpened()) {
         return STATUS_CODE_NOT_INITIALIZED;
       }
       directory = nullptr;
       if (!dirName.empty()) {
         directory = m_file->mkdir(dirName.c_str());
         if (directory == nullptr) {
           return STATUS_CODE_FAILURE;
         }
       }
       else {
         directory = m_file.get();
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::Archiver::recursiveWrite (MonitorElementDir directory, TDirectory * rootDirectory, const std::string & refSuffix = "") private
Fill recursively the TDirectory with the Directory.
Parameters
directory the monitor element storage directory
rootDirectory the corresponding ROOT directory
refSuffix the suffix to add for object references
Definition at line 169 of file Archiver.cc.
References RETURN_RESULT_IF, and writeMonitorElements().
Referenced by archive(), and archiveWithReferences().
{
       if (nullptr == directory || nullptr == rootDirectory) {
         return STATUS_CODE_INVALID_PTR;
       }
       rootDirectory->cd();
       const auto &subDirList(directory->subdirs());
       for (auto iter = subDirList.begin(), endIter = subDirList.end(); endIter != iter; ++iter) {
         auto subDir = *iter;
         TDirectory *rootSubDirectory = rootDirectory->mkdir(subDir->name().c_str());
         if (nullptr != rootSubDirectory) {
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, Archiver::recursiveWrite(subDir, rootSubDirectory, refSuffix));
         }
       }
       // write the monitor elements
       if (not directory->isEmpty()) {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, Archiver::writeMonitorElements(directory, rootDirectory, refSuffix));
       }
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::Archiver::setSelectorFunction (std::function< bool(MonitorElementPtr)> func)
Set the selector function to use on write operation.
The function should return true to archive the element. By default, every monitor element is written.
Parameters
func the selector function
Definition at line 104 of file Archiver.cc.
References m_selectorFunction.
{
       m_selectorFunction = func;
     }
StatusCode dqm4hep::core::Archiver::writeMonitorElements (MonitorElementDir directory, TDirectory * rootDirectory, const std::string & refSuffix = "") private
Write the monitor elements contained in the Directory in the TDirectory.
Parameters
directory the monitor element storage directory
rootDirectory the corresponding ROOT directory
refSuffix the suffix to add for object references
Definition at line 191 of file Archiver.cc.
References m_selectorFunction.
Referenced by recursiveWrite().
{
       if (nullptr == directory || nullptr == rootDirectory) {
         return STATUS_CODE_INVALID_PTR;
       }
       rootDirectory->cd();
       const auto &monitorElementList(directory->contents());
       for (auto iter = monitorElementList.begin(), endIter = monitorElementList.end(); endIter != iter; ++iter) {
         if(not m_selectorFunction(*iter)) {
           continue;
         }
         const std::string writeName = (*iter)->name();
         TObject *object = (*iter)->object();
         if(nullptr != object) {
           rootDirectory->WriteObjectAny(object, object->IsA(), writeName.c_str());
           TObject *reference = (*iter)->reference();
           if(not refSuffix.empty() and nullptr != reference) {
             rootDirectory->WriteObjectAny(reference, reference->IsA(), (writeName + refSuffix).c_str());
           }
         }
       }
       return STATUS_CODE_SUCCESS;
     }
Member Data Documentation
std::unique_ptr<TFile> dqm4hep::core::Archiver::m_file = {nullptr} private
The actual archive implementation (root file)
Definition at line 158 of file Archiver.h.
Referenced by archive(), archiveWithReferences(), close(), open(), and prepareForArchiving().
std::string dqm4hep::core::Archiver::m_fileName = {""} private
The archive file name.
Definition at line 150 of file Archiver.h.
Referenced by fileName(), and open().
bool dqm4hep::core::Archiver::m_isOpened = {false} private
Definition at line 154 of file Archiver.h.
Referenced by close(), isOpened(), and open().
std::string dqm4hep::core::Archiver::m_openingMode = {"RECREATE"} private
The root file opening mode.
Whether the archive is opened
Definition at line 152 of file Archiver.h.
Referenced by close(), open(), and openingMode().
SelectorFunction dqm4hep::core::Archiver::m_selectorFunction = {nullptr} private
The selector function.
Definition at line 156 of file Archiver.h.
Referenced by Archiver(), setSelectorFunction(), and writeMonitorElements().
The documentation for this class was generated from the following files:
Archiver.h
Archiver.cc