DQM4hep: dqm4hep::core::Handle Class Reference
dqm4hep::core::Handle Class Reference
Handle class Non-template class handling a template pointer in a type-safe manner.
#include <Handle.h>
Public Member Functions
Handle ()=delete
~Handle ()=default
Handle (const Handle &)=delete
Handle (Handle &&)=default
Handle & operator= (const Handle &)=delete
template<typename T >
Handle (T *ptr)
Constructor.
template<typename T >
Handle (std::shared_ptr< T > ptr)
Constructor.
template<typename T >
std::shared_ptr< T > ptr () const
Retrieve the handled pointer as a specific type.
Handle create () const
Create a new handle based on the same underlying type.
void * raw ()
Retrieve the handled pointer as raw pointer.
const void * raw () const
Retrieve the handled pointer as raw pointer (const version)
const std::type_index & typeInfo () const
Retrieve the handled pointer type information.
bool isValid () const
Whether the handled pointer is valid (non nullptr)
Protected Attributes
std::shared_ptr< void > m_ptr = {nullptr}
The handled pointer.
std::type_index m_typeInfo
The type information of the handled type.
std::function< Handle(void)> m_newFunction = {nullptr}
A custom allocator function based on the underlying type.
Detailed Description
Handle class Non-template class handling a template pointer in a type-safe manner.
Definition at line 32 of file Handle.h.
Constructor & Destructor Documentation
dqm4hep::core::Handle::Handle () delete
Referenced by Handle().
dqm4hep::core::Handle::~Handle () default
dqm4hep::core::Handle::Handle (const Handle &) delete
dqm4hep::core::Handle::Handle (Handle &&) default
template<typename T > dqm4hep::core::Handle::Handle (T * ptr) inline
Constructor.
Parameters
ptr a raw pointer to handle
Definition at line 147 of file Handle.h.
References Handle(), and m_newFunction.
                                 :
       m_ptr(ptr),
       m_typeInfo(typeid(T)) {
       m_newFunction = []() {
         return Handle(new T());
       };
     }
template<typename T > dqm4hep::core::Handle::Handle (std::shared_ptr< T > ptr) inline
Constructor.
Parameters
ptr a shared pointer to handle
Definition at line 158 of file Handle.h.
References Handle(), and m_newFunction.
                                               :
       m_ptr(ptr),
       m_typeInfo(typeid(T)) {
       m_newFunction = []() {
         return Handle(new T());
       };
     }
Member Function Documentation
Handle dqm4hep::core::Handle::create () const
Create a new handle based on the same underlying type.
Definition at line 42 of file Handle.cc.
References m_newFunction.
{
       return m_newFunction();
     }
bool dqm4hep::core::Handle::isValid () const
Whether the handled pointer is valid (non nullptr)
Definition at line 36 of file Handle.cc.
References raw().
{
       return (nullptr != raw());
     }
Handle& dqm4hep::core::Handle::operator= (const Handle &) delete
template<typename T > std::shared_ptr< T > dqm4hep::core::Handle::ptr () const inline
Retrieve the handled pointer as a specific type.
Definition at line 169 of file Handle.h.
References m_ptr.
{
       return std::static_pointer_cast<T>(m_ptr);
     }
void * dqm4hep::core::Handle::raw ()
Retrieve the handled pointer as raw pointer.
Definition at line 18 of file Handle.cc.
References m_ptr.
Referenced by isValid().
                       {
       return m_ptr.get();
     }
const void * dqm4hep::core::Handle::raw () const
Retrieve the handled pointer as raw pointer (const version)
Definition at line 24 of file Handle.cc.
References m_ptr.
{
       return m_ptr.get();
     }
const std::type_index & dqm4hep::core::Handle::typeInfo () const
Retrieve the handled pointer type information.
Definition at line 30 of file Handle.cc.
References m_typeInfo.
{
       return m_typeInfo;
     }
Member Data Documentation
std::function<Handle(void)> dqm4hep::core::Handle::m_newFunction = {nullptr} protected
A custom allocator function based on the underlying type.
Definition at line 93 of file Handle.h.
Referenced by create(), Handle(), and dqm4hep::core::ROOTHandle::ROOTHandle().
std::shared_ptr<void> dqm4hep::core::Handle::m_ptr = {nullptr} protected
The handled pointer.
Definition at line 89 of file Handle.h.
Referenced by ptr(), and raw().
std::type_index dqm4hep::core::Handle::m_typeInfo protected
The type information of the handled type.
Definition at line 91 of file Handle.h.
Referenced by typeInfo().
The documentation for this class was generated from the following files:
Handle.h
Handle.cc