DQM4hep: dqm4hep::net::Client Class Reference
dqm4hep::net::Client Class Reference
Client class.
#include <Client.h>
Public Member Functions
Client ()
Constructor.
~Client ()
Destructor.
void queryServerInfo (const std::string &serverName, core::json &serverInfo) const
Query server information.
template<typename Request >
void sendRequest (const std::string &name, const Request &request) const
Send a command.
template<typename Operation >
void sendRequest (const std::string &name, const Buffer &request, Operation operation) const
Send a request.
template<typename Command >
void sendCommand (const std::string &name, const Command &command, bool blocking=false) const
Send a command.
template<typename Controller >
void subscribe (const std::string &serviceName, Controller *pController, void(Controller::*function)(const Buffer &))
Subscribe to service.
template<typename Controller >
void unsubscribe (const std::string &serviceName, Controller *pController)
Unsubscribe from a particular service.
bool hasSubscribed (const std::string &serviceName) const
Whether this client already registered a service subscription.
unsigned int numberOfSubscriptions (const std::string &serviceName) const
Get the number of subscriptions for a specific service.
void notifyServerOnExit (const std::string &serverName)
.
template<>
void sendRequest (const std::string &name, const Buffer &request) const
template<>
void sendCommand (const std::string &name, const Buffer &buffer, bool blocking) const
Private Types
typedef std::map< std::string,
ServiceHandler * > ServiceHandlerMap
typedef std::vector
< ServiceHandler * > ServiceHandlerList
Private Attributes
ServiceHandlerMap m_serviceHandlerMap = {}
The service map.
Detailed Description
Client class.
Main interface to server. User can send request to a server with or without expecting a response using the sendRequest() function. User can also subscribe to a particular service run on a server by using the subscribe() method and by providing a callback function.
Definition at line 39 of file Client.h.
Member Typedef Documentation
typedef std::vector<ServiceHandler *> dqm4hep::net::Client::ServiceHandlerList private
Definition at line 139 of file Client.h.
typedef std::map<std::string, ServiceHandler *> dqm4hep::net::Client::ServiceHandlerMap private
Definition at line 138 of file Client.h.
Constructor & Destructor Documentation
dqm4hep::net::Client::Client ()
Constructor.
Definition at line 19 of file Client.cc.
                    {
       DimClient::setNoDataCopy();
     }
dqm4hep::net::Client::~Client ()
Destructor.
Definition at line 25 of file Client.cc.
References m_serviceHandlerMap.
                     {
       for (auto iter = m_serviceHandlerMap.begin(), endIter = m_serviceHandlerMap.end(); endIter != iter; ++iter)
         delete iter->second;
       m_serviceHandlerMap.clear();
     }
Member Function Documentation
bool dqm4hep::net::Client::hasSubscribed (const std::string & serviceName) const
Whether this client already registered a service subscription.
Parameters
serviceName the service name
Definition at line 42 of file Client.cc.
References m_serviceHandlerMap.
Referenced by dqm4hep::online::EventCollectorClient::receivingEventUpdates(), and dqm4hep::online::EventCollectorClient::setUpdateMode().
{
       return (m_serviceHandlerMap.end() != m_serviceHandlerMap.find(name));
     }
void dqm4hep::net::Client::notifyServerOnExit (const std::string & serverName)
.
Tell the specified server to be notified when this client exits
Parameters
serverName the server name to inform
Definition at line 54 of file Client.cc.
Referenced by dqm4hep::online::EventSource::registerMe().
{
       DimClient::setExitHandler(serverName.c_str());
     }
unsigned int dqm4hep::net::Client::numberOfSubscriptions (const std::string & serviceName) const
Get the number of subscriptions for a specific service.
Parameters
serviceName the service name
Definition at line 48 of file Client.cc.
References m_serviceHandlerMap.
{
       return m_serviceHandlerMap.count(serviceName);
     }
void dqm4hep::net::Client::queryServerInfo (const std::string & serverName, core::json & serverInfo) const
Query server information.
Parameters
serverName the server name
serverInfo the json value describing the server information
Definition at line 34 of file Client.cc.
References dqm4hep::net::Buffer::begin(), dqm4hep::net::Buffer::end(), and sendRequest().
{
       Buffer request;
       this->sendRequest("/" + serverName + "/info", request,
                         [&serverInfo](const Buffer &buffer) { serverInfo = core::json::parse(buffer.begin(), buffer.end()); });
     }
template<typename Command > void dqm4hep::net::Client::sendCommand (const std::string & name, const Command & command, bool blocking = false) const inline
Send a command.
Parameters
name the command name
command the command to send
blocking whether to wait for command reception on server side
Definition at line 191 of file Client.h.
References dqm4hep::net::Buffer::begin(), dqm4hep::net::Buffer::createModel(), dqm4hep::net::Buffer::setModel(), and dqm4hep::net::Buffer::size().
Referenced by dqm4hep::online::RemoteLogger::_sink_it(), dqm4hep::online::Application::sendCommand(), dqm4hep::online::EventSource::sendEvent(), dqm4hep::online::Application::sendStat(), and dqm4hep::online::EventSource::unregisterMe().
{
       Buffer contents;
       auto model = contents.createModel<Command>();
       model->copy(command);
       contents.setModel(model);
       if (blocking) {
         DimClient::sendCommand(const_cast<char *>(name.c_str()), (void *)contents.begin(), contents.size());
       } else {
         DimClient::sendCommandNB(const_cast<char *>(name.c_str()), (void *)contents.begin(), contents.size());
       }
     }
template<> void dqm4hep::net::Client::sendCommand (const std::string & name, const Buffer & buffer, bool blocking) const inline
Definition at line 207 of file Client.h.
References dqm4hep::net::Buffer::begin(), and dqm4hep::net::Buffer::size().
{
       if (blocking) {
         DimClient::sendCommand(const_cast<char *>(name.c_str()), (void *)buffer.begin(), buffer.size());
       } else {
         DimClient::sendCommandNB(const_cast<char *>(name.c_str()), (void *)buffer.begin(), buffer.size());
       }
     }
template<typename Request > void dqm4hep::net::Client::sendRequest (const std::string & name, const Request & request) const inline
Send a command.
Do not wait for any response
Parameters
name the request name
command the request content
Definition at line 148 of file Client.h.
References dqm4hep::net::Buffer::createModel().
Referenced by dqm4hep::online::EventCollectorClient::queryEvent(), queryServerInfo(), dqm4hep::online::EventSource::registerMe(), and dqm4hep::online::Application::sendRequest().
{
       DimRpcInfo rpcInfo(const_cast<char *>(name.c_str()), (void *)nullptr, 0);
       Buffer contents;
       auto model = contents.createModel<Request>();
       model->copy(request);
       contents.setModel(model);
       rpcInfo.setData((void *)contents.begin(), contents.size());
     }
template<typename Operation > void dqm4hep::net::Client::sendRequest (const std::string & name, const Buffer & request, Operation operation) const inline
Send a request.
Wait for the server response (blocking)
Parameters
name the request name
request the request to send
operation the callback operation to perform on data reception
Definition at line 170 of file Client.h.
References dqm4hep::net::Buffer::adopt(), dqm4hep::net::Buffer::begin(), and dqm4hep::net::Buffer::size().
{
       DimRpcInfo rpcInfo(const_cast<char *>(name.c_str()), (void *)nullptr, 0);
       // send request
       rpcInfo.setData((void *)request.begin(), request.size());
       // wait for answer from server
       char *data = (char *)rpcInfo.getData();
       int size = rpcInfo.getSize();
       Buffer response;
       if (nullptr != data && 0 != size)
         response.adopt(data, size);
       operation(response);
     }
template<> void dqm4hep::net::Client::sendRequest (const std::string & name, const Buffer & request) const inline
Definition at line 160 of file Client.h.
References dqm4hep::net::Buffer::adopt(), dqm4hep::net::Buffer::begin(), and dqm4hep::net::Buffer::size().
{
       DimRpcInfo rpcInfo(const_cast<char *>(name.c_str()), (void *)nullptr, 0);
       Buffer contents;
       contents.adopt(request.begin(), request.size());
       rpcInfo.setData((void *)contents.begin(), contents.size());
     }
template<typename Controller > void dqm4hep::net::Client::subscribe (const std::string & serviceName, Controller * pController, void(Controller::*)(const Buffer &) function) inline
Subscribe to service.
Parameters
serviceName the service name
pController the class instance that will receive the service updates
function the class method that will receive the service update
// the class callback method
void MyClass::myfunction(const int &integer) { ... }
Client client;
MyClass c;
client.subscribe("service-name", &c, &MyClass::myfunction);
Definition at line 218 of file Client.h.
References m_serviceHandlerMap.
Referenced by dqm4hep::online::Application::directSubscribe(), dqm4hep::online::Application::queuedSubscribe(), and dqm4hep::online::EventCollectorClient::setUpdateMode().
{
       auto findIter = m_serviceHandlerMap.find(name);
       if (findIter != m_serviceHandlerMap.end()) {
         findIter->second->onServiceUpdate().connect(pController, function);
         return;
       }
       m_serviceHandlerMap.insert(
           ServiceHandlerMap::value_type(name, new ServiceHandler(this, name, pController, function)));
     }
template<typename Controller > void dqm4hep::net::Client::unsubscribe (const std::string & serviceName, Controller * pController) inline
Unsubscribe from a particular service.
Parameters
serviceName the service name
pController the controller class handling the service update
Definition at line 234 of file Client.h.
References m_serviceHandlerMap.
Referenced by dqm4hep::online::EventCollectorClient::setUpdateMode().
{
       for (auto iter = m_serviceHandlerMap.begin(), endIter = m_serviceHandlerMap.end(); endIter != iter; ++iter) {
         if (serviceName != iter->first)
           continue;
         if (iter->second->onServiceUpdate().disconnect(pController))
           break;
       }
     }
Member Data Documentation
ServiceHandlerMap dqm4hep::net::Client::m_serviceHandlerMap = {} private
The service map.
Definition at line 140 of file Client.h.
Referenced by hasSubscribed(), numberOfSubscriptions(), subscribe(), unsubscribe(), and ~Client().
The documentation for this class was generated from the following files:
Client.h
Client.cc