DQM4hep: dqm4hep::core::MonitorElement Class Reference
dqm4hep::core::MonitorElement Class Reference
MonitorElement class.
#include <MonitorElement.h>
Public Member Functions
virtual ~MonitorElement ()=default
Default destructor.
std::string type () const
Get the monitor element type (class name)
std::string name () const
Get the object name.
std::string title () const
Get the object title.
void setTitle (const std::string &title)
Set the object title.
std::string path () const
Get the object path (in directory structure)
bool hasObject () const
Whether the monitor element has a valid object ptr.
bool hasReference () const
Whether the monitor element has a valid reference ptr.
TObject * object ()
Get the monitor object.
const TObject * object () const
Get the monitor object.
TObject * reference ()
Get the reference object.
const TObject * reference () const
Get the reference object.
template<typename T >
T * objectTo ()
Get a casted version of the monitor object.
template<typename T >
T * referenceTo ()
Get a casted version of the reference object.
void setMonitorObject (TObject *pMonitorObject)
Set the monitor object.
void setMonitorObject (const PtrHandler< TObject > &monitorObject)
Set the wrapped object (ptr handle)
void setReferenceObject (TObject *pReferenceObject)
Set the wrapped reference object.
void setReferenceObject (const PtrHandler< TObject > &referenceObject)
Set the wrapped reference object (ptr handle)
void set (TObject *pMonitorObject, TObject *pReferenceObject)
Set the wrapped object and reference object.
void set (const PtrHandler< TObject > &monitorObject, const PtrHandler< TObject > &referenceObject)
Set the wrapped object and reference object (ptr handle)
virtual void reset (bool resetQtests=true)
Reset the monitor element.
virtual void toJson (json &object) const
Convert the monitor element to json.
virtual void fromJson (const json &value)
Parse the json object and set monitor element properties.
virtual StatusCode write (TBuffer &buffer) const
Write monitor element to device.
virtual StatusCode read (TBuffer &buffer)
Read the monitor element from device.
Static Public Member Functions
static MonitorElementPtr make_shared ()
Make a shared pointer of MonitorElement.
static MonitorElementPtr make_shared (TObject *pMonitorObject)
Make a shared pointer of MonitorElement.
static MonitorElementPtr make_shared (TObject *pMonitorObject, TObject *pReferenceObject)
Make a shared pointer of MonitorElement.
static MonitorElementPtr make_shared (const PtrHandler< TObject > &monitorObject)
Make a shared pointer of MonitorElement.
static MonitorElementPtr make_shared (const PtrHandler< TObject > &monitorObject, const PtrHandler< TObject > &referenceObject)
Make a shared pointer of MonitorElement.
Protected Member Functions
MonitorElement ()
Constructor.
MonitorElement (TObject *pMonitorObject)
Constructor with ROOT object.
MonitorElement (TObject *pMonitorObject, TObject *pReferenceObject)
Constructor with ROOT object and reference.
MonitorElement (const PtrHandler< TObject > &monitorObject)
Constructor with ROOT object ptr.
MonitorElement (const PtrHandler< TObject > &monitorObject, const PtrHandler< TObject > &referenceObject)
Constructor with ROOT object and reference ptr.
void setName (const std::string &name)
Set the monitor element object name.
void setPath (const std::string &path)
Set the monitor element object path.
StatusCode addQualityTest (QTestPtr qualityTest)
Add a quality test.
StatusCode removeQualityTest (const std::string &name)
Remove a quality test.
virtual StatusCode runQualityTests (QReportMap &reports)
Run all quality tests.
virtual StatusCode runQualityTest (const std::string &name, QReport &report)
Run a specific quality test.
Private Attributes
std::string m_path = {""}
The monitor element path.
PtrHandler< TObject > m_monitorObject = {}
The monitored object.
PtrHandler< TObject > m_referenceObject = {}
The reference object.
QTestMap m_qualityTests = {}
The list of assigned quality tests.
Friends
class MonitorElementManager
Detailed Description
MonitorElement class.
Author
Remi Ete, DESY
Definition at line 58 of file MonitorElement.h.
Constructor & Destructor Documentation
virtual dqm4hep::core::MonitorElement::~MonitorElement () virtual default
Default destructor.
MonitorElement::MonitorElement () protected
Constructor.
Definition at line 80 of file MonitorElement.cc.
                                    : m_path(""), m_monitorObject(), m_referenceObject() {
     }
MonitorElement::MonitorElement (TObject * pMonitorObject) protected
Constructor with ROOT object.
Parameters
pMonitorObject a root object as main monitor object
Definition at line 85 of file MonitorElement.cc.
                                                           : m_monitorObject(pMonitorObject), m_referenceObject() {
     }
MonitorElement::MonitorElement (TObject * pMonitorObject, TObject * pReferenceObject) protected
Constructor with ROOT object and reference.
Parameters
pMonitorObject a root object as main monitor object
pReferenceObject a root object as reference object
Definition at line 90 of file MonitorElement.cc.
         : m_monitorObject(pMonitorObject), m_referenceObject(pReferenceObject) {
     }
MonitorElement::MonitorElement (const PtrHandler< TObject > & monitorObject) protected
Constructor with ROOT object ptr.
Parameters
monitorObject a root object pointer as main monitor object
Definition at line 96 of file MonitorElement.cc.
         : m_monitorObject(monitorObject.ptr(), false), m_referenceObject() {
     }
MonitorElement::MonitorElement (const PtrHandler< TObject > & monitorObject, const PtrHandler< TObject > & referenceObject) protected
Constructor with ROOT object and reference ptr.
Parameters
monitorObject a root object pointer as main monitor object
referenceObject a root object pointer as reference object
Definition at line 102 of file MonitorElement.cc.
         : m_monitorObject(monitorObject.ptr(), false), m_referenceObject(referenceObject.ptr(), false) {
     }
Member Function Documentation
StatusCode MonitorElement::addQualityTest (QTestPtr qualityTest) protected
Add a quality test.
Parameters
qualityTest a quality test pointer
Definition at line 367 of file MonitorElement.cc.
References m_qualityTests.
{
       const std::string &qname(qualityTest->name());
       auto iter = m_qualityTests.find(qname);
       if (m_qualityTests.end() != iter)
         return STATUS_CODE_ALREADY_PRESENT;
       m_qualityTests.insert(QTestMap::value_type(qname, qualityTest));
       return STATUS_CODE_SUCCESS;
     }
void MonitorElement::fromJson (const json & value) virtual
Parse the json object and set monitor element properties.
Parameters
object the json object to parse
Definition at line 282 of file MonitorElement.cc.
References dqm4hep::core::PtrHandler< T >::clear(), m_monitorObject, m_path, m_referenceObject, and dqm4hep::core::PtrHandler< T >::set().
{
       // read object
       m_monitorObject.clear();
       auto jsonObject = object.value("object", json(nullptr));
       if(nullptr != jsonObject) {
         TObject *pTObject = TBufferJSON::ConvertFromJSON(jsonObject.dump().c_str());
         if(nullptr != pTObject) {
           m_monitorObject.set(pTObject, true);
         }
       }
       // read reference
       m_referenceObject.clear();
       auto jsonReference = object.value("reference", json(nullptr));
       if(nullptr != jsonReference) {
         TObject *pTObject = TBufferJSON::ConvertFromJSON(jsonReference.dump().c_str());
         if(nullptr != pTObject) {
           m_referenceObject.set(pTObject, true);
         }
       }
       // read path
       m_path = object.value<std::string>("path", "");
     }
bool MonitorElement::hasObject () const
Whether the monitor element has a valid object ptr.
Definition at line 168 of file MonitorElement.cc.
References m_monitorObject.
Referenced by write().
{
       return (m_monitorObject != nullptr);
     }
bool MonitorElement::hasReference () const
Whether the monitor element has a valid reference ptr.
Definition at line 174 of file MonitorElement.cc.
References m_referenceObject.
Referenced by write().
{
       return (m_referenceObject != nullptr);
     }
static MonitorElementPtr dqm4hep::core::MonitorElement::make_shared () static
Make a shared pointer of MonitorElement.
MonitorElementPtr MonitorElement::make_shared (TObject * pMonitorObject) static
Make a shared pointer of MonitorElement.
Parameters
pMonitorObject a root object as main monitor object
Definition at line 55 of file MonitorElement.cc.
{
       return std::shared_ptr<MonitorElement>(new MonitorElement(pMonitorObject));
     }
MonitorElementPtr MonitorElement::make_shared (TObject * pMonitorObject, TObject * pReferenceObject) static
Make a shared pointer of MonitorElement.
Parameters
pMonitorObject a root object as main monitor object
pReferenceObject a root object as reference object
Definition at line 61 of file MonitorElement.cc.
{
       return std::shared_ptr<MonitorElement>(new MonitorElement(pMonitorObject, pReferenceObject));
     }
MonitorElementPtr MonitorElement::make_shared (const PtrHandler< TObject > & monitorObject) static
Make a shared pointer of MonitorElement.
Parameters
monitorObject a root object pointer as main monitor object
Definition at line 67 of file MonitorElement.cc.
{
       return std::shared_ptr<MonitorElement>(new MonitorElement(monitorObject));
     }
MonitorElementPtr MonitorElement::make_shared (const PtrHandler< TObject > & monitorObject, const PtrHandler< TObject > & referenceObject) static
Make a shared pointer of MonitorElement.
Parameters
monitorObject a root object pointer as main monitor object
referenceObject a root object pointer as reference object
Definition at line 73 of file MonitorElement.cc.
{
       return std::shared_ptr<MonitorElement>(new MonitorElement(monitorObject, referenceObject));
     }
std::string MonitorElement::name () const
Get the object name.
Definition at line 114 of file MonitorElement.cc.
References m_monitorObject.
Referenced by dqm4hep::core::QualityTest::fillBasicInfo(), dqm4hep::core::AnalysisHelper::mean(), dqm4hep::core::AnalysisHelper::median(), and dqm4hep::core::AnalysisHelper::rms().
{
       return (m_monitorObject ? m_monitorObject->GetName() : "");
     }
TObject * MonitorElement::object ()
Get the monitor object.
Definition at line 180 of file MonitorElement.cc.
References m_monitorObject, and dqm4hep::core::PtrHandler< T >::ptr().
Referenced by dqm4hep::core::ExactRefCompareTest::doIsEqualTest(), objectTo(), dqm4hep::core::QualityTest::run(), dqm4hep::core::Chi2Test::userRun(), dqm4hep::core::KolmogorovTest::userRun(), and dqm4hep::core::ExactRefCompareTest::userRun().
{
       return m_monitorObject ? m_monitorObject.ptr() : nullptr;
     }
const TObject* dqm4hep::core::MonitorElement::object () const
Get the monitor object.
template<typename T > T * dqm4hep::core::MonitorElement::objectTo () inline
Get a casted version of the monitor object.
Definition at line 348 of file MonitorElement.h.
References object().
Referenced by dqm4hep::core::FitParamInRangeTest::checkElement(), dqm4hep::core::ExactRefCompareTest::doGraph1DTest(), dqm4hep::core::ExactRefCompareTest::doGraph2DTest(), dqm4hep::core::ExactRefCompareTest::doHistogramTest(), dqm4hep::core::AnalysisHelper::mean(), dqm4hep::core::AnalysisHelper::median(), dqm4hep::core::FitParamInRangeTest::performFit(), dqm4hep::core::AnalysisHelper::rms(), dqm4hep::core::PropertyWithinExpectedTest::userRun(), dqm4hep::core::Chi2Test::userRun(), and dqm4hep::core::KolmogorovTest::userRun().
{
       return dynamic_cast<T*>(object());
     }
std::string MonitorElement::path () const
Get the object path (in directory structure)
Definition at line 141 of file MonitorElement.cc.
References m_path.
Referenced by dqm4hep::core::QualityTest::fillBasicInfo().
{
       return m_path;
     }
StatusCode MonitorElement::read (TBuffer & buffer) virtual
Read the monitor element from device.
Parameters
device the device to read from
Reimplemented in dqm4hep::online::OnlineElement.
Definition at line 337 of file MonitorElement.cc.
References m_monitorObject, m_path, m_referenceObject, reset(), and dqm4hep::core::PtrHandler< T >::set().
Referenced by dqm4hep::online::OnlineElement::read().
{
       if(not buffer.IsReading()) {
         return STATUS_CODE_NOT_ALLOWED;
       }
       reset(false);
       // write path
       buffer.ReadStdString(&m_path);
       bool hasObjectRead(false);
       buffer.ReadBool(hasObjectRead);
       if(hasObjectRead) {
         TObject *obj = buffer.ReadObject(nullptr);
         if(nullptr == obj) {
           return STATUS_CODE_FAILURE;
         }
         m_monitorObject.set(obj, true);
       }
       bool hasReferenceRead(false);
       buffer.ReadBool(hasReferenceRead);
       if(hasReferenceRead) {
         TObject *ref = buffer.ReadObject(nullptr);
         if(nullptr == ref) {
           return STATUS_CODE_FAILURE;
         }
         m_referenceObject.set(ref, true);
       }
       return STATUS_CODE_SUCCESS;
     }
TObject * MonitorElement::reference ()
Get the reference object.
Definition at line 192 of file MonitorElement.cc.
References m_referenceObject, and dqm4hep::core::PtrHandler< T >::ptr().
Referenced by dqm4hep::core::ExactRefCompareTest::doIsEqualTest(), referenceTo(), dqm4hep::core::KolmogorovTest::userRun(), dqm4hep::core::Chi2Test::userRun(), dqm4hep::core::ExactRefCompareTest::userRun(), and write().
{
       return m_referenceObject ? m_referenceObject.ptr() : nullptr;
     }
const TObject* dqm4hep::core::MonitorElement::reference () const
Get the reference object.
template<typename T > T * dqm4hep::core::MonitorElement::referenceTo () inline
Get a casted version of the reference object.
Definition at line 355 of file MonitorElement.h.
References reference().
Referenced by dqm4hep::core::ExactRefCompareTest::doGraph1DTest(), dqm4hep::core::ExactRefCompareTest::doGraph2DTest(), dqm4hep::core::ExactRefCompareTest::doHistogramTest(), dqm4hep::core::Chi2Test::userRun(), and dqm4hep::core::KolmogorovTest::userRun().
{
       return dynamic_cast<T*>(reference());
     }
StatusCode MonitorElement::removeQualityTest (const std::string & name) protected
Remove a quality test.
Parameters
name the quality test name
Definition at line 381 of file MonitorElement.cc.
References m_qualityTests.
{
       auto iter = m_qualityTests.find(qname);
       if (m_qualityTests.end() == iter)
         return STATUS_CODE_NOT_FOUND;
       m_qualityTests.erase(iter);
       return STATUS_CODE_SUCCESS;
     }
void MonitorElement::reset (bool resetQtests = true) virtual
Reset the monitor element.
Parameters
resetQtests whether to also reset the quality tests
Reimplemented in dqm4hep::online::OnlineElement.
Definition at line 250 of file MonitorElement.cc.
References dqm4hep::core::PtrHandler< T >::clear(), m_monitorObject, m_path, m_qualityTests, and m_referenceObject.
Referenced by read(), and dqm4hep::online::OnlineElement::reset().
{
       m_monitorObject.clear();
       m_referenceObject.clear();
       m_path.clear();
       if(resetQtests) {
         m_qualityTests.clear();
       }
     }
StatusCode MonitorElement::runQualityTest (const std::string & name, QReport & report) protected virtual
Run a specific quality test.
Parameters
name the quality test name to run
report the quality test report to receive
Reimplemented in dqm4hep::online::OnlineElement.
Definition at line 412 of file MonitorElement.cc.
References m_qualityTests.
Referenced by dqm4hep::online::OnlineElement::runQualityTest().
{
       auto iter = m_qualityTests.find(qname);
       if (m_qualityTests.end() == iter)
         return STATUS_CODE_NOT_FOUND;
       iter->second->run(this, report);
       return STATUS_CODE_SUCCESS;
     }
StatusCode MonitorElement::runQualityTests (QReportMap & reports) protected virtual
Run all quality tests.
Parameters
reports the list of quality test reports to receive
Definition at line 394 of file MonitorElement.cc.
References dqm4hep::core::StatusCodeException::getStatusCode(), and m_qualityTests.
Referenced by dqm4hep::online::OnlineElement::runQualityTests().
{
       try {
         for (auto iter : m_qualityTests) {
           QReport report;
           iter.second->run(this, report);
           reports.insert(QReportMap::value_type(iter.first, report));
         }
       } catch (StatusCodeException &exception) {
         return exception.getStatusCode();
       } catch (...) {
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
void MonitorElement::set (TObject * pMonitorObject, TObject * pReferenceObject)
Set the wrapped object and reference object.
Parameters
pMonitorObject a root object as main monitor object
pReferenceObject a root object as reference object
Definition at line 232 of file MonitorElement.cc.
References dqm4hep::core::PtrHandler< T >::clear(), m_monitorObject, m_referenceObject, and dqm4hep::core::PtrHandler< T >::set().
{
       m_monitorObject.clear();
       m_monitorObject.set(pMonitorObject);
       m_referenceObject.clear();
       m_referenceObject.set(pReferenceObject);
     }
void MonitorElement::set (const PtrHandler< TObject > & monitorObject, const PtrHandler< TObject > & referenceObject)
Set the wrapped object and reference object (ptr handle)
Parameters
monitorObject a root object pointer as main monitor object
referenceObject a root object pointer as reference object
Definition at line 241 of file MonitorElement.cc.
References dqm4hep::core::PtrHandler< T >::clear(), m_monitorObject, m_referenceObject, dqm4hep::core::PtrHandler< T >::ptr(), and dqm4hep::core::PtrHandler< T >::set().
{
       m_monitorObject.clear();
       m_monitorObject.set(monitorObject.ptr(), false);
       m_referenceObject.clear();
       m_referenceObject.set(referenceObject.ptr(), false);
     }
void MonitorElement::setMonitorObject (TObject * pMonitorObject)
Set the monitor object.
Parameters
pMonitorObject a root object as main monitor object
Definition at line 204 of file MonitorElement.cc.
References dqm4hep::core::PtrHandler< T >::clear(), m_monitorObject, and dqm4hep::core::PtrHandler< T >::set().
{
       m_monitorObject.clear();
       m_monitorObject.set(pMonitorObject);
     }
void MonitorElement::setMonitorObject (const PtrHandler< TObject > & monitorObject)
Set the wrapped object (ptr handle)
Parameters
monitorObject a root object pointer as main monitor object
Definition at line 211 of file MonitorElement.cc.
References dqm4hep::core::PtrHandler< T >::clear(), m_monitorObject, dqm4hep::core::PtrHandler< T >::ptr(), and dqm4hep::core::PtrHandler< T >::set().
{
       m_monitorObject.clear();
       m_monitorObject.set(monitorObject.ptr(), false);
     }
void MonitorElement::setName (const std::string & name) protected
Set the monitor element object name.
Parameters
name the monitor element name
Definition at line 153 of file MonitorElement.cc.
References dqm_error, m_monitorObject, and dqm4hep::core::PtrHandler< T >::ptr().
{
       if(nullptr == m_monitorObject) {
         dqm_error("Trying to set monitor element name: not initialized!");
         throw StatusCodeException(STATUS_CODE_NOT_INITIALIZED);
       }
       if(not m_monitorObject.ptr()->InheritsFrom("TNamed")) {
         dqm_error("Trying to set monitor element name: does not inherits from TNamed!");
         throw StatusCodeException(STATUS_CODE_NOT_ALLOWED);
       }
       TNamed *named = objectTo<TNamed>();
       named->SetName(n.c_str());
     }
void MonitorElement::setPath (const std::string & path) protected
Set the monitor element object path.
Parameters
path the monitor element path
Definition at line 147 of file MonitorElement.cc.
References m_path.
{
       m_path = p;
     }
void MonitorElement::setReferenceObject (TObject * pReferenceObject)
Set the wrapped reference object.
Parameters
pReferenceObject a root object as reference object
Definition at line 218 of file MonitorElement.cc.
References dqm4hep::core::PtrHandler< T >::clear(), m_referenceObject, and dqm4hep::core::PtrHandler< T >::set().
{
       m_referenceObject.clear();
       m_referenceObject.set(pReferenceObject);
     }
void MonitorElement::setReferenceObject (const PtrHandler< TObject > & referenceObject)
Set the wrapped reference object (ptr handle)
Parameters
referenceObject a root object pointer as reference object
Definition at line 225 of file MonitorElement.cc.
References dqm4hep::core::PtrHandler< T >::clear(), m_referenceObject, dqm4hep::core::PtrHandler< T >::ptr(), and dqm4hep::core::PtrHandler< T >::set().
{
       m_referenceObject.clear();
       m_referenceObject.set(referenceObject.ptr(), false);
     }
void MonitorElement::setTitle (const std::string & title)
Set the object title.
Throw if the object does not inherit the TNamed class
Parameters
title the object title
Definition at line 126 of file MonitorElement.cc.
References dqm_error, m_monitorObject, and dqm4hep::core::PtrHandler< T >::ptr().
{
       if(nullptr == m_monitorObject) {
         dqm_error("Trying to set monitor element title: not initialized!");
         throw StatusCodeException(STATUS_CODE_NOT_INITIALIZED);
       }
       if(not m_monitorObject.ptr()->InheritsFrom("TNamed")) {
         dqm_error("Trying to set monitor element title: does not inherits from TNamed!");
         throw StatusCodeException(STATUS_CODE_NOT_ALLOWED);
       }
       TNamed *named = objectTo<TNamed>();
       named->SetTitle(t.c_str());
     }
std::string MonitorElement::title () const
Get the object title.
Definition at line 120 of file MonitorElement.cc.
References m_monitorObject.
{
       return (m_monitorObject ? m_monitorObject->GetTitle() : "");
     }
void MonitorElement::toJson (json & object) const virtual
Convert the monitor element to json.
Parameters
object the json object to receive
Reimplemented in dqm4hep::online::OnlineElement.
Definition at line 261 of file MonitorElement.cc.
References m_monitorObject, m_path, m_referenceObject, and dqm4hep::core::PtrHandler< T >::ptr().
Referenced by dqm4hep::online::OnlineElement::toJson().
{
       json jsonObject = nullptr, jsonReference = nullptr;
       if(nullptr != m_monitorObject) {
         jsonObject = json::parse(TBufferJSON::ConvertToJSON(m_monitorObject.ptr(), 23).Data());
       }
       if(nullptr != m_referenceObject) {
         jsonReference = json::parse(TBufferJSON::ConvertToJSON(m_referenceObject.ptr(), 23).Data());
       }
       jobject = {
         {"object", jsonObject},
         {"reference", jsonReference},
         {"path", m_path}
       };
     }
std::string MonitorElement::type () const
Get the monitor element type (class name)
Definition at line 108 of file MonitorElement.cc.
References m_monitorObject.
Referenced by dqm4hep::core::QualityTest::fillBasicInfo(), dqm4hep::core::AnalysisHelper::mean(), dqm4hep::core::AnalysisHelper::median(), and dqm4hep::core::AnalysisHelper::rms().
{
       return (m_monitorObject ? m_monitorObject->ClassName() : "");
     }
StatusCode MonitorElement::write (TBuffer & buffer) const virtual
Write monitor element to device.
Parameters
device the device to write to
Reimplemented in dqm4hep::online::OnlineElement.
Definition at line 308 of file MonitorElement.cc.
References hasObject(), hasReference(), m_path, and reference().
Referenced by dqm4hep::online::OnlineElement::write().
{
       if(not buffer.IsWriting()) {
         return STATUS_CODE_NOT_ALLOWED;
       }
       // write path
       buffer.WriteStdString(&m_path);
       // write object
       const bool hasObjectWrite = hasObject();
       buffer.WriteBool(hasObjectWrite);
       if(hasObjectWrite) {
         TClass *objClass = TClass::GetClass(object()->ClassName());
         if(not buffer.WriteObjectAny((void*)object(), objClass)) {
           return STATUS_CODE_FAILURE;
         }
       }
       // write reference
       const bool hasReferenceWrite = hasReference();
       buffer.WriteBool(hasReferenceWrite);
       if(hasReferenceWrite) {
         TClass *refClass = TClass::GetClass(reference()->ClassName());
         if(not buffer.WriteObjectAny((void*)reference(), refClass)) {
           return STATUS_CODE_FAILURE;
         }
       }
       return STATUS_CODE_SUCCESS;
     }
Friends And Related Function Documentation
friend class MonitorElementManager friend
Definition at line 59 of file MonitorElement.h.
Member Data Documentation
PtrHandler<TObject> dqm4hep::core::MonitorElement::m_monitorObject = {} private
The monitored object.
Definition at line 337 of file MonitorElement.h.
Referenced by fromJson(), hasObject(), name(), object(), read(), reset(), set(), setMonitorObject(), setName(), setTitle(), title(), toJson(), and type().
std::string dqm4hep::core::MonitorElement::m_path = {""} private
The monitor element path.
Definition at line 335 of file MonitorElement.h.
Referenced by fromJson(), path(), read(), reset(), setPath(), toJson(), and write().
QTestMap dqm4hep::core::MonitorElement::m_qualityTests = {} private
The list of assigned quality tests.
Definition at line 341 of file MonitorElement.h.
Referenced by addQualityTest(), removeQualityTest(), reset(), runQualityTest(), and runQualityTests().
PtrHandler<TObject> dqm4hep::core::MonitorElement::m_referenceObject = {} private
The reference object.
Definition at line 339 of file MonitorElement.h.
Referenced by fromJson(), hasReference(), read(), reference(), reset(), set(), setReferenceObject(), and toJson().
The documentation for this class was generated from the following files:
MonitorElement.h
MonitorElement.cc