DQM4hep: dqm4hep::net::Buffer Class Reference
dqm4hep::net::Buffer Class Reference
Buffer class.
#include <NetBuffer.h>
Public Member Functions
Buffer (const Buffer &)=delete
Buffer & operator= (const Buffer &)=delete
Buffer && operator= (Buffer &&)=delete
Buffer ()
Constructor.
Buffer (Buffer &&buffer)
Move constructor.
template<typename T >
std::shared_ptr< BufferModelT
< T > > createModel () const
Factory method to create a new model.
std::shared_ptr< BufferModel > createModel () const
Factory method to create a new model (std::string specialization)
void setModel (std::shared_ptr< BufferModel > model)
Set the new model to handle the buffer.
const char * begin () const
Get the start address of the buffer internally stored.
const char * end () const
Get the end address of the buffer internally stored.
size_t size () const
Get the size of the buffer internally stored.
void adopt (const char *buffer, size_t size)
Adopt a new buffer.
BufferModelPtr model () const
Get the model handling the raw buffer.
Private Attributes
BufferModelPtr m_model = {nullptr}
The buffer model handling the raw buffer.
Detailed Description
Buffer class.
Definition at line 179 of file NetBuffer.h.
Constructor & Destructor Documentation
dqm4hep::net::Buffer::Buffer (const Buffer &) delete
dqm4hep::net::Buffer::Buffer ()
Constructor.
Definition at line 69 of file NetBuffer.cc.
References adopt(), dqm4hep::net::NullBuffer::buffer, and dqm4hep::net::NullBuffer::size.
                    {
       this->adopt(NullBuffer::buffer, NullBuffer::size);
     }
dqm4hep::net::Buffer::Buffer (Buffer && buffer)
Move constructor.
Parameters
buffer the buffer to move
Definition at line 75 of file NetBuffer.cc.
References m_model.
{
       m_model = std::move(buffer.m_model);
     }
Member Function Documentation
void dqm4hep::net::Buffer::adopt (const char * buffer, size_t size)
Adopt a new buffer.
A new model is created to handle this new buffer
Parameters
buffer the start address of the new buffer to adopt
size the size of the new buffer to adopt
Definition at line 113 of file NetBuffer.cc.
References createModel(), and setModel().
Referenced by Buffer(), dqm4hep::net::CommandHandler::Command::commandHandler(), dqm4hep::net::ServiceHandler::ServiceInfo::infoHandler(), dqm4hep::net::RequestHandler::Rpc::rpcHandler(), dqm4hep::net::Service::sendBuffer(), and dqm4hep::net::Client::sendRequest().
{
       auto m = this->createModel();
       m->handle(buffer, s);
       this->setModel(m);
     }
const char * dqm4hep::net::Buffer::begin () const
Get the start address of the buffer internally stored.
Definition at line 95 of file NetBuffer.cc.
References m_model.
Referenced by dqm4hep::online::OnlineManagerServer::collectAppStat(), dqm4hep::online::OnlineManagerServer::collectLog(), dqm4hep::online::EventCollector::handleCollectEvent(), dqm4hep::online::EventCollector::handleEventRequest(), dqm4hep::online::EventCollector::handleRegistration(), dqm4hep::online::Application::NetworkHandler::postCommandEvent(), dqm4hep::online::Application::NetworkHandler::postServiceContent(), dqm4hep::online::ModuleApplication::processStartOfRun(), dqm4hep::net::Client::queryServerInfo(), dqm4hep::online::EventCollectorClient::readEvent(), dqm4hep::online::ModuleApplication::receiveSubscriptionList(), dqm4hep::online::EventSource::registerMe(), dqm4hep::net::RequestHandler::Rpc::rpcHandler(), dqm4hep::net::Client::sendCommand(), dqm4hep::net::Service::sendData(), and dqm4hep::net::Client::sendRequest().
{
       return m_model->raw().begin();
     }
template<typename T > std::shared_ptr< BufferModelT< T > > dqm4hep::net::Buffer::createModel () const inline
Factory method to create a new model.
Definition at line 274 of file NetBuffer.h.
Referenced by adopt(), dqm4hep::online::EventCollector::handleRegistration(), dqm4hep::net::Server::handleServerInfoRequest(), dqm4hep::online::Application::NetworkHandler::postCommandEvent(), dqm4hep::online::Application::NetworkHandler::postServiceContent(), dqm4hep::online::EventCollectorClient::queryEvent(), dqm4hep::online::EventSource::registerMe(), dqm4hep::net::Service::send(), dqm4hep::net::Client::sendCommand(), dqm4hep::online::RunControlServer::sendCurrentRun(), dqm4hep::online::EventSource::sendEvent(), and dqm4hep::net::Client::sendRequest().
{
       return std::make_shared<BufferModelT<T>>();
     }
std::shared_ptr< BufferModel > dqm4hep::net::Buffer::createModel () const
Factory method to create a new model (std::string specialization)
Definition at line 81 of file NetBuffer.cc.
{
       return std::make_shared<BufferModel>();
     }
const char * dqm4hep::net::Buffer::end () const
Get the end address of the buffer internally stored.
Definition at line 101 of file NetBuffer.cc.
References m_model.
Referenced by dqm4hep::online::OnlineManagerServer::collectAppStat(), dqm4hep::online::OnlineManagerServer::collectLog(), dqm4hep::online::EventCollector::handleRegistration(), dqm4hep::online::ModuleApplication::processStartOfRun(), dqm4hep::net::Client::queryServerInfo(), dqm4hep::online::ModuleApplication::receiveSubscriptionList(), and dqm4hep::online::EventSource::registerMe().
{
       return m_model->raw().end();
     }
BufferModelPtr dqm4hep::net::Buffer::model () const
Get the model handling the raw buffer.
Definition at line 121 of file NetBuffer.cc.
References m_model.
{
       return m_model;
     }
Buffer& dqm4hep::net::Buffer::operator= (const Buffer &) delete
Buffer&& dqm4hep::net::Buffer::operator= (Buffer &&) delete
void dqm4hep::net::Buffer::setModel (std::shared_ptr< BufferModel > model)
Set the new model to handle the buffer.
Parameters
model the new model to handle
Definition at line 87 of file NetBuffer.cc.
References m_model.
Referenced by adopt(), dqm4hep::online::CommandEvent::CommandEvent(), dqm4hep::online::EventCollector::handleEventRequest(), dqm4hep::online::EventCollector::handleRegistration(), dqm4hep::net::Server::handleServerInfoRequest(), dqm4hep::online::EventCollectorClient::queryEvent(), dqm4hep::online::EventSource::registerMe(), dqm4hep::online::RequestEvent::RequestEvent(), dqm4hep::net::Service::send(), dqm4hep::net::Client::sendCommand(), dqm4hep::online::RunControlServer::sendCurrentRun(), dqm4hep::online::EventSource::sendEvent(), and dqm4hep::online::ServiceUpdateEvent::ServiceUpdateEvent().
{
       if (!m)
         return;
       m_model = m;
     }
size_t dqm4hep::net::Buffer::size () const
Get the size of the buffer internally stored.
Definition at line 107 of file NetBuffer.cc.
References m_model.
Referenced by dqm4hep::online::OnlineManagerServer::collectAppStat(), dqm4hep::online::OnlineManagerServer::collectLog(), dqm4hep::online::EventCollector::handleCollectEvent(), dqm4hep::online::EventCollector::handleEventRequest(), dqm4hep::online::EventCollector::handleRegistration(), dqm4hep::online::Application::NetworkHandler::postCommandEvent(), dqm4hep::online::Application::NetworkHandler::postServiceContent(), dqm4hep::online::EventCollectorClient::readEvent(), dqm4hep::online::EventSource::registerMe(), dqm4hep::net::RequestHandler::Rpc::rpcHandler(), dqm4hep::net::Client::sendCommand(), dqm4hep::net::Service::sendData(), and dqm4hep::net::Client::sendRequest().
{
       return m_model->raw().size();
     }
Member Data Documentation
BufferModelPtr dqm4hep::net::Buffer::m_model = {nullptr} private
The buffer model handling the raw buffer.
Definition at line 243 of file NetBuffer.h.
Referenced by begin(), Buffer(), end(), model(), setModel(), and size().
The documentation for this class was generated from the following files:
NetBuffer.h
NetBuffer.cc