DQM4hep: dqm4hep::core::QReportStorage Class Reference
dqm4hep::core::QReportStorage Class Reference
QReportStorage class.
#include <QualityTest.h>
Public Member Functions
QReportStorage ()
Constructor.
void addReport (const QReport &report, bool warnOnReplace=true)
Add report to list.
void addReports (const QReportMap &reports, bool warnOnReplace=true)
Add reports to list.
StatusCode report (const std::string &path, const std::string &name, const std::string &qualityTestName, QReport &report)
Get a specific report.
StatusCode reports (const std::string &path, const std::string &name, QReportMap &reports)
Get all reports of the monitor element.
StatusCode reportsQualityHigher (const std::string &path, const std::string &name, float qlimit, QReportMap &reports)
Get all reports of the monitor element with quality higher than a limit (range [0,1])
StatusCode reportsQualityLower (const std::string &path, const std::string &name, float qlimit, QReportMap &reports)
Get all reports of the monitor element with quality lower than a limit (range [0,1])
const QReportContainer & reports ()
Get all reports.
StatusCode reportsQualityHigher (float qlimit, QReportContainer &reports)
Get all reports with quality higher than a limit (range [0,1])
StatusCode reportsQualityLower (float qlimit, QReportContainer &reports)
Get all reports with quality lower than a limit (range [0,1])
void clear ()
Clear all contents.
void toJson (json &object) const
Convert all stored reports to json format.
Private Attributes
QReportContainer m_reports
Detailed Description
QReportStorage class.
Definition at line 84 of file QualityTest.h.
Constructor & Destructor Documentation
dqm4hep::core::QReportStorage::QReportStorage ()
Constructor.
Definition at line 74 of file QualityTest.cc.
                                    : m_reports() {
       /* nop */
     }
Member Function Documentation
void dqm4hep::core::QReportStorage::addReport (const QReport & report, bool warnOnReplace = true)
Add report to list.
If report already exists, replace it. Comparison made from :
monitor element name
monitor element type
quality test name
Definition at line 80 of file QualityTest.cc.
References dqm_warning, dqm4hep::core::QualityTestReport::m_monitorElementName, dqm4hep::core::QualityTestReport::m_monitorElementPath, dqm4hep::core::QualityTestReport::m_qualityTestName, and m_reports.
Referenced by addReports(), and dqm4hep::core::MonitorElementManager::runQualityTest().
{
       const std::string &path(qreport.m_monitorElementPath);
       const std::string &name(qreport.m_monitorElementName);
       const std::string &qtname(qreport.m_qualityTestName);
       if (!warnOnReplace) {
         QReportContainer::key_type key(path, name);
         m_reports[key][qtname] = qreport;
       } else {
         QReportContainer::key_type key(path, name);
         auto iter1 = m_reports.find(key);
         if (m_reports.end() == iter1)
           iter1 = m_reports.insert(QReportContainer::value_type(key, QReportMap())).first;
         auto iter2 = iter1->second.find(qtname);
         if (iter1->second.end() == iter2) {
           iter2 = iter1->second.insert(QReportMap::value_type(qtname, qreport)).first;
         } else {
           dqm_warning("QReportStorage::addReport: Replacing qreport path '{0}', name '{1}', qtest '{2}'", path, name,
                       qtname);
           iter2->second = qreport;
         }
       }
     }
void dqm4hep::core::QReportStorage::addReports (const QReportMap & reports, bool warnOnReplace = true)
Add reports to list.
If reports already exists, replace it. Comparison made from :
monitor element name
monitor element type
quality test name
Definition at line 109 of file QualityTest.cc.
References addReport().
Referenced by dqm4hep::core::MonitorElementManager::runQualityTests().
{
       for (auto iter : qreports)
         this->addReport(iter.second, warnOnReplace);
     }
void dqm4hep::core::QReportStorage::clear ()
Clear all contents.
Definition at line 246 of file QualityTest.cc.
References m_reports.
{
       m_reports.clear();
     }
StatusCode dqm4hep::core::QReportStorage::report (const std::string & path, const std::string & name, const std::string & qualityTestName, QReport & report)
Get a specific report.
Definition at line 116 of file QualityTest.cc.
References m_reports.
{
       QReportContainer::key_type key(path, name);
       auto findIter = m_reports.find(key);
       if (m_reports.end() == findIter)
         return STATUS_CODE_NOT_FOUND;
       auto findIter2 = findIter->second.find(qualityTestName);
       if (findIter->second.end() == findIter2)
         return STATUS_CODE_NOT_FOUND;
       qreport = findIter2->second;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::QReportStorage::reports (const std::string & path, const std::string & name, QReportMap & reports)
Get all reports of the monitor element.
Definition at line 135 of file QualityTest.cc.
References m_reports.
{
       QReportContainer::key_type key(path, name);
       auto findIter = m_reports.find(key);
       if (m_reports.end() == findIter)
         return STATUS_CODE_NOT_FOUND;
       qreports.insert(findIter->second.begin(), findIter->second.end());
       return STATUS_CODE_SUCCESS;
     }
const QReportContainer & dqm4hep::core::QReportStorage::reports ()
Get all reports.
Definition at line 192 of file QualityTest.cc.
References m_reports.
{
       return m_reports;
     }
StatusCode dqm4hep::core::QReportStorage::reportsQualityHigher (const std::string & path, const std::string & name, float qlimit, QReportMap & reports)
Get all reports of the monitor element with quality higher than a limit (range [0,1])
Definition at line 148 of file QualityTest.cc.
References m_reports.
{
       if (0.f < qlimit || qlimit > 1.f)
         return STATUS_CODE_OUT_OF_RANGE;
       QReportContainer::key_type key(path, name);
       auto findIter = m_reports.find(key);
       if (m_reports.end() == findIter)
         return STATUS_CODE_NOT_FOUND;
       for (auto qtest : findIter->second) {
         if (qtest.second.m_quality >= qlimit) {
           qreports.insert(QReportMap::value_type(qtest.first, qtest.second));
         }
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::QReportStorage::reportsQualityHigher (float qlimit, QReportContainer & reports)
Get all reports with quality higher than a limit (range [0,1])
Definition at line 198 of file QualityTest.cc.
References m_reports.
{
       if (0.f < qlimit || qlimit > 1.f)
         return STATUS_CODE_OUT_OF_RANGE;
       for (auto iter1 : m_reports) {
         QReportMap reportMap;
         for (auto iter2 : iter1.second) {
           if (iter2.second.m_quality >= qlimit) {
             reportMap.insert(QReportMap::value_type(iter2.first, iter2.second));
           }
         }
         if (reportMap.empty())
           continue;
         qreports.insert(QReportContainer::value_type(iter1.first, reportMap));
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::QReportStorage::reportsQualityLower (const std::string & path, const std::string & name, float qlimit, QReportMap & reports)
Get all reports of the monitor element with quality lower than a limit (range [0,1])
Definition at line 170 of file QualityTest.cc.
References m_reports.
{
       if (0.f < qlimit || qlimit > 1.f)
         return STATUS_CODE_OUT_OF_RANGE;
       QReportContainer::key_type key(path, name);
       auto findIter = m_reports.find(key);
       if (m_reports.end() == findIter)
         return STATUS_CODE_NOT_FOUND;
       for (auto qtest : findIter->second) {
         if (qtest.second.m_quality <= qlimit) {
           qreports.insert(QReportMap::value_type(qtest.first, qtest.second));
         }
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::QReportStorage::reportsQualityLower (float qlimit, QReportContainer & reports)
Get all reports with quality lower than a limit (range [0,1])
Definition at line 222 of file QualityTest.cc.
References m_reports.
{
       if (0.f < qlimit || qlimit > 1.f)
         return STATUS_CODE_OUT_OF_RANGE;
       for (auto iter1 : m_reports) {
         QReportMap reportMap;
         for (auto iter2 : iter1.second) {
           if (iter2.second.m_quality <= qlimit) {
             reportMap.insert(QReportMap::value_type(iter2.first, iter2.second));
           }
         }
         if (reportMap.empty())
           continue;
         qreports.insert(QReportContainer::value_type(iter1.first, reportMap));
       }
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::QReportStorage::toJson (json & object) const
Convert all stored reports to json format.
Parameters
object the json object to receive
Definition at line 252 of file QualityTest.cc.
References m_reports.
Referenced by dqm4hep::online::ModuleApplication::onEvent().
{
       for (const auto &iter : m_reports) {
         for (const auto &iter2 : iter.second) {
           json jsonQReport;
           iter2.second.toJson(jsonQReport);
           object.push_back(jsonQReport);
         }
       }
     }
Member Data Documentation
QReportContainer dqm4hep::core::QReportStorage::m_reports private
Definition at line 149 of file QualityTest.h.
Referenced by addReport(), clear(), report(), reports(), reportsQualityHigher(), reportsQualityLower(), and toJson().
The documentation for this class was generated from the following files:
QualityTest.h
QualityTest.cc