DQM4hep: dqm4hep::net::Service Class Reference
dqm4hep::net::Service Class Reference
#include <Service.h>
Public Member Functions
const std::string & name () const
Get the service name.
Server * server () const
Get the server in which the service is declared.
template<typename T >
void send (const T &value)
Send a simple value.
template<typename T >
void sendArray (const T *value, size_t nElements)
Send an array of simple values.
void sendBuffer (const void *ptr, size_t size)
Send a raw buffer.
template<typename T >
void send (const T &value, int clientId)
Send a simple value to a specific client.
template<typename T >
void sendArray (const T *value, size_t nElements, int clientId)
Send an array of simple values to a specific client.
void sendBuffer (const void *ptr, size_t size, int clientId)
Send a raw buffer to a specific client.
template<typename T >
void send (const T &value, const std::vector< int > &clientIds)
Send a simple value to a specific list of clients.
template<typename T >
void sendArray (const T *value, size_t nElements, const std::vector< int > &clientIds)
Send an array of simple values to a specific list of clients.
void sendBuffer (const void *ptr, size_t size, const std::vector< int > &clientIds)
Send a raw buffer to a specific list of clients.
Private Member Functions
Service (Server *pServer, const std::string &name)
Constructor with service name.
Service (const Service &)=delete
Service & operator= (const Service &)=delete
virtual ~Service ()
Destructor.
void connectService ()
Create the actual service connection.
void disconnectService ()
Remove the actual service connection.
bool isServiceConnected () const
Whether the service is connected.
void sendData (const Buffer &buffer, const std::vector< int > &clientIds)
Private Attributes
DimService * m_pService = {nullptr}
The service implementation.
std::string m_name = {""}
The service name.
Server * m_pServer = {nullptr}
The server in which the service is declared.
Friends
class Server
Detailed Description
Definition at line 31 of file Service.h.
Constructor & Destructor Documentation
dqm4hep::net::Service::Service (Server * pServer, const std::string & name) private
Constructor with service name.
Parameters
pServer the server that owns the service instance
name the service name
Definition at line 18 of file Service.cc.
                                                             :
       m_name(sname),
       m_pServer(pServer) {
       /* nop */
     }
dqm4hep::net::Service::Service (const Service &) private delete
dqm4hep::net::Service::~Service () private virtual
Destructor.
Definition at line 26 of file Service.cc.
References disconnectService().
                       {
       this->disconnectService();
     }
Member Function Documentation
void dqm4hep::net::Service::connectService () private
Create the actual service connection.
Definition at line 44 of file Service.cc.
References dqm4hep::net::NullBuffer::buffer, isServiceConnected(), m_name, m_pService, and dqm4hep::net::NullBuffer::size.
Referenced by dqm4hep::net::Server::createService(), and dqm4hep::net::Server::startService().
{
       if (!this->isServiceConnected()) {
         m_pService = new DimService((char *)m_name.c_str(), "C", (char *)NullBuffer::buffer, NullBuffer::size);
       }
     }
void dqm4hep::net::Service::disconnectService () private
Remove the actual service connection.
Definition at line 52 of file Service.cc.
References isServiceConnected(), and m_pService.
Referenced by dqm4hep::net::Server::stopService(), and ~Service().
{
       if (this->isServiceConnected()) {
         delete m_pService;
         m_pService = nullptr;
       }
     }
bool dqm4hep::net::Service::isServiceConnected () const private
Whether the service is connected.
Definition at line 61 of file Service.cc.
References m_pService.
Referenced by connectService(), disconnectService(), sendData(), dqm4hep::net::Server::startService(), and dqm4hep::net::Server::stopService().
{
       return (m_pService != nullptr);
     }
const std::string & dqm4hep::net::Service::name () const
Get the service name.
Definition at line 32 of file Service.cc.
References m_name.
{
       return m_name;
     }
Service& dqm4hep::net::Service::operator= (const Service &) private delete
template<typename T > void dqm4hep::net::Service::send (const T & value) inline
Send a simple value.
Definition at line 142 of file Service.h.
References dqm4hep::net::Buffer::createModel(), sendData(), and dqm4hep::net::Buffer::setModel().
Referenced by dqm4hep::online::Application::setState().
{
       Buffer buffer;
       auto model = buffer.createModel<T>();
       model->copy(value);
       buffer.setModel(model);
       this->sendData(buffer, std::vector<int>());
     }
template<typename T > void dqm4hep::net::Service::send (const T & value, int clientId) inline
Send a simple value to a specific client.
Definition at line 161 of file Service.h.
References sendData().
{
       Buffer buffer(value);
       this->sendData(buffer, std::vector<int>(1, clientId));
     }
template<typename T > void dqm4hep::net::Service::send (const T & value, const std::vector< int > & clientIds) inline
Send a simple value to a specific list of clients.
Definition at line 177 of file Service.h.
References sendData().
{
       Buffer buffer(value);
       this->sendData(buffer, clientIds);
     }
template<typename T > void dqm4hep::net::Service::sendArray (const T * value, size_t nElements) inline
Send an array of simple values.
Definition at line 153 of file Service.h.
References sendData().
{
       Buffer buffer(value, nElements);
       this->sendData(buffer, std::vector<int>());
     }
template<typename T > void dqm4hep::net::Service::sendArray (const T * value, size_t nElements, int clientId) inline
Send an array of simple values to a specific client.
Definition at line 169 of file Service.h.
References sendData().
{
       Buffer buffer(value, nElements);
       this->sendData(buffer, std::vector<int>(1, clientId));
     }
template<typename T > void dqm4hep::net::Service::sendArray (const T * value, size_t nElements, const std::vector< int > & clientIds) inline
Send an array of simple values to a specific list of clients.
Definition at line 185 of file Service.h.
References sendData().
{
       Buffer buffer(value, nElements);
       this->sendData(buffer, clientIds);
     }
void dqm4hep::net::Service::sendBuffer (const void * ptr, size_t size)
Send a raw buffer.
The buffer is owned by the caller
Definition at line 67 of file Service.cc.
References dqm4hep::net::Buffer::adopt(), and sendData().
Referenced by dqm4hep::online::OnlineManagerServer::collectAppStat(), and dqm4hep::online::OnlineManagerServer::collectLog().
{
       Buffer buffer;
       buffer.adopt((const char *)ptr, size);
       this->sendData(buffer, std::vector<int>());
     }
void dqm4hep::net::Service::sendBuffer (const void * ptr, size_t size, int clientId)
Send a raw buffer to a specific client.
The buffer is owned by the caller
Definition at line 75 of file Service.cc.
References dqm4hep::net::Buffer::adopt(), and sendData().
{
       Buffer buffer;
       buffer.adopt((const char *)ptr, size);
       this->sendData(buffer, std::vector<int>(1, clientId));
     }
void dqm4hep::net::Service::sendBuffer (const void * ptr, size_t size, const std::vector< int > & clientIds)
Send a raw buffer to a specific list of clients.
The buffer is owned by the caller
Definition at line 83 of file Service.cc.
References dqm4hep::net::Buffer::adopt(), and sendData().
{
       Buffer buffer;
       buffer.adopt((const char *)ptr, size);
       this->sendData(buffer, clientIds);
     }
void dqm4hep::net::Service::sendData (const Buffer & buffer, const std::vector< int > & clientIds) private
Definition at line 91 of file Service.cc.
References dqm4hep::net::Buffer::begin(), dqm4hep::net::NullBuffer::buffer, isServiceConnected(), m_pService, dqm4hep::net::NullBuffer::size, and dqm4hep::net::Buffer::size().
Referenced by send(), sendArray(), and sendBuffer().
{
       if (!this->isServiceConnected())
         throw; // TODO implement exceptions
       if (clientIds.empty()) {
         m_pService->updateService((void *)buffer.begin(), buffer.size());
         m_pService->itsData = (void *)NullBuffer::buffer;
         m_pService->itsSize = NullBuffer::size;
       } else {
         std::vector<int> clientIdList(clientIds);
         if (clientIdList.back() != 0)
           clientIdList.push_back(0);
         int *clientIdsArray = &clientIdList[0];
         m_pService->selectiveUpdateService((void *)buffer.begin(), buffer.size(), clientIdsArray);
         m_pService->itsData = (void *)NullBuffer::buffer;
         m_pService->itsSize = NullBuffer::size;
       }
     }
Server * dqm4hep::net::Service::server () const
Get the server in which the service is declared.
Definition at line 38 of file Service.cc.
References m_pServer.
{
       return m_pServer;
     }
Friends And Related Function Documentation
friend class Server friend
Definition at line 32 of file Service.h.
Member Data Documentation
std::string dqm4hep::net::Service::m_name = {""} private
The service name.
Definition at line 134 of file Service.h.
Referenced by connectService(), and name().
Server* dqm4hep::net::Service::m_pServer = {nullptr} private
The server in which the service is declared.
Definition at line 135 of file Service.h.
Referenced by server().
DimService* dqm4hep::net::Service::m_pService = {nullptr} private
The service implementation.
Definition at line 133 of file Service.h.
Referenced by connectService(), disconnectService(), isServiceConnected(), and sendData().
The documentation for this class was generated from the following files:
Service.h
Service.cc