DQM4hep: dqm4hep::core::PropertyWithinExpectedTest Class Reference
dqm4hep::core::PropertyWithinExpectedTest Class Reference
PropertyWithinExpectedTest class.
Classes
class Factory
Public Member Functions
PropertyWithinExpectedTest (const std::string &name)
~PropertyWithinExpectedTest () override=default
StatusCode readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override
Read the settings from the xml handle.
void userRun (MonitorElement *monitorElement, QualityTestReport &report) override
Runs a quality test on the given monitor element and return a quality estimate.
Public Member Functions inherited from dqm4hep::core::QualityTest
QualityTest (const std::string &type, const std::string &name)
Constructor.
virtual ~QualityTest ()
Destructor.
const std::string & type () const
Get the quality test type.
const std::string & name () const
Get the quality test name (unique identifier)
const std::string & description () const
Get the quality test description.
void run (MonitorElement *monitorElement, QualityTestReport &report)
Perform the quality test result and fill the quality test report.
virtual StatusCode init ()
Initialize the quality test.
virtual bool enoughStatistics (MonitorElement *monitorElement) const
Whether the monitor element has enough statistics to perform the qtest.
void setLimits (float warning, float error)
Set the warning and error limits on quality test result.
float warningLimit () const
Get the warning limit.
float errorLimit () const
Get the error limit.
Protected Attributes
float m_expectedValue
float m_deviationLower
float m_deviationUpper
float m_percentage
std::string m_property
std::string m_method
Protected Attributes inherited from dqm4hep::core::QualityTest
std::string m_description = {""}
Quality test description.
Additional Inherited Members
Static Public Member Functions inherited from dqm4hep::core::QualityTest
static float defaultWarningLimit ()
Get the default warning limit.
static float defaultErrorLimit ()
Get the default error limit.
Protected Member Functions inherited from dqm4hep::core::QualityTest
void fillBasicInfo (MonitorElement *monitorElement, QualityTestReport &report) const
Fill basic info in the qtest report.
Static Protected Attributes inherited from dqm4hep::core::QualityTest
static float m_defaultWarningLimit = 0.8
static float m_defaultErrorLimit = 0.5
Detailed Description
PropertyWithinExpectedTest class.
Definition at line 31 of file PropertyWithinExpectedTest.cc.
Constructor & Destructor Documentation
dqm4hep::core::PropertyWithinExpectedTest::PropertyWithinExpectedTest (const std::string & name)
Definition at line 66 of file PropertyWithinExpectedTest.cc.
References dqm4hep::core::QualityTest::m_description.
Referenced by dqm4hep::core::PropertyWithinExpectedTest::Factory::createQualityTest().
         : QualityTest("PropertyWithinExpected", qname),
           m_expectedValue(0.f),
     m_deviationLower(0.f),
     m_deviationUpper(0.f),
     m_percentage(1.0),
     m_property(),
     m_method("WithinRange")
 {
       m_description = "Test if a given property (Mean, Mean90, RMS, RMS90, Median) of a histogram or graph is contained within the expected user-defined range, "
                 "or above or below a user-defined threshold. For 'within range' tests the quality is defined as the probability to be close to the mean: 1 at "
                 "the mean, 0 infinitely far from the mean (using TMath::Prob(chi2,1)). For threshold tests the quality is 1 if it passes, 0 otherwise.";
     }
dqm4hep::core::PropertyWithinExpectedTest::~PropertyWithinExpectedTest () override default
Member Function Documentation
StatusCode dqm4hep::core::PropertyWithinExpectedTest::readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override virtual
Read the settings from the xml handle.
Implements dqm4hep::core::QualityTest.
Definition at line 82 of file PropertyWithinExpectedTest.cc.
References m_deviationLower, m_deviationUpper, m_expectedValue, m_method, m_percentage, m_property, dqm4hep::core::XmlHelper::readParameter(), RETURN_RESULT_IF, and RETURN_RESULT_IF_AND_IF.
{
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(xmlHandle, "Property", m_property));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle, "Percentage", m_percentage));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle, "Method", m_method));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle, "ExpectedValue", m_expectedValue));
       if (m_method == "HigherThan") {
   RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(xmlHandle, "DeviationLower", m_deviationLower));
       }
       if (m_method == "LowerThan") {
   RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(xmlHandle, "DeviationUpper", m_deviationUpper));
       }
       if (m_method == "WithinRange") {
   RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(xmlHandle, "DeviationUpper", m_deviationUpper));
   RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(xmlHandle, "DeviationLower", m_deviationLower));
       }
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::PropertyWithinExpectedTest::userRun (MonitorElement * monitorElement, QualityTestReport & report) override virtual
Runs a quality test on the given monitor element and return a quality estimate.
Implements dqm4hep::core::QualityTest.
Definition at line 106 of file PropertyWithinExpectedTest.cc.
References dqm_error, m_deviationLower, m_deviationUpper, m_expectedValue, dqm4hep::core::QualityTestReport::m_message, m_method, m_property, dqm4hep::core::QualityTestReport::m_quality, dqm4hep::core::AnalysisHelper::mean(), dqm4hep::core::AnalysisHelper::mean90(), dqm4hep::core::AnalysisHelper::median(), dqm4hep::core::QualityTest::name(), dqm4hep::core::MonitorElement::objectTo(), dqm4hep::core::AnalysisHelper::rms(), dqm4hep::core::AnalysisHelper::rms90(), and dqm4hep::core::typeToString().
{
       if (nullptr == monitorElement->objectTo<TH1>() && nullptr == monitorElement->objectTo<TGraph>()) {
   report.m_message = "ROOT monitor element object is of unrecognised type!";
   throw StatusCodeException(STATUS_CODE_INVALID_PTR);
       }
       // For-loop code for doing multiple test types per qtest; use TBD
       /*
       for (std::vector<std::string>::iterator it = m_properties.begin(); it != m_properties.end(); it++
       {
         // Do something
       }
       */
       float result;
       if (m_property == "Mean")
   {
     result = AnalysisHelper::mean(monitorElement);
   }
       else if (m_property == "Mean90")
   {
     result = AnalysisHelper::mean90(monitorElement);
   }
       else if (m_property == "RMS")
   {
     result = AnalysisHelper::rms(monitorElement);
   }
       else if (m_property == "RMS90")
   {
     result = AnalysisHelper::rms90(monitorElement);
   }
       else if (m_property == "Median")
   {
     result = AnalysisHelper::median(monitorElement);
   }
       else
   {
     dqm_error("Error in qtest {0} : unrecognised test type {1}", name(), m_property);
     throw StatusCodeException(STATUS_CODE_FAILURE);
   }
       if ( m_method == "LowerThan" ) {
   if (result < m_deviationUpper) {
     report.m_message =
       "Below expected value: expected " + typeToString(m_deviationUpper) + ", got " + typeToString(result);
     report.m_quality = 1.0;
   }
   else {
     report.m_message =
       "Above expected value: expected " + typeToString(m_deviationUpper) + ", got " + typeToString(result);
     report.m_quality = 0.0;
   }
       }
       else if ( m_method == "HigherThan" ) {
   if (result > m_deviationLower) {
     report.m_message =
       "Above expected value: expected " + typeToString(m_deviationLower) + ", got " + typeToString(result);
     report.m_quality = 1.0;
   }
   else {
     report.m_message =
       "Below expected value: expected " + typeToString(m_deviationLower) + ", got " + typeToString(result);
     report.m_quality = 0.0;
   }
       }
       else if ( m_method == "WithinRange" ) {
   const float range(fabs(m_deviationUpper - m_deviationLower));
   if (m_deviationLower < result && result < m_deviationUpper) {
     report.m_message =
             "Within expected range: expected " + typeToString(m_expectedValue) + ", got " + typeToString(result);
   }
   else if (result < m_deviationLower || result > m_deviationUpper) {
     report.m_message =
             "Out of expected range: expected " + typeToString(m_expectedValue) + ", got " + typeToString(result);
   }
   const float chi = (result - m_expectedValue) / range;
   report.m_quality = TMath::Prob(chi * chi, 1);
       }
       else {
   dqm_error("Error in qtest {0} : unrecognised test method {1}", name(), m_method);
   throw StatusCodeException(STATUS_CODE_FAILURE);
       }
     }
Member Data Documentation
float dqm4hep::core::PropertyWithinExpectedTest::m_deviationLower protected
Definition at line 45 of file PropertyWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
float dqm4hep::core::PropertyWithinExpectedTest::m_deviationUpper protected
Definition at line 46 of file PropertyWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
float dqm4hep::core::PropertyWithinExpectedTest::m_expectedValue protected
Definition at line 44 of file PropertyWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
std::string dqm4hep::core::PropertyWithinExpectedTest::m_method protected
Definition at line 49 of file PropertyWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
float dqm4hep::core::PropertyWithinExpectedTest::m_percentage protected
Definition at line 47 of file PropertyWithinExpectedTest.cc.
Referenced by readSettings().
std::string dqm4hep::core::PropertyWithinExpectedTest::m_property protected
Definition at line 48 of file PropertyWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
The documentation for this class was generated from the following file:
PropertyWithinExpectedTest.cc