DQM4hep: dqm4hep::online::Module Class Reference
dqm4hep::online::Module Class Reference abstract
Module base class.
#include <Module.h>
Public Member Functions
Module ()=default
Default constructor.
Module (const Module &)=delete
Module & operator= (const Module &)=delete
virtual ~Module ()
Destructor.
const std::string & name () const
Get the module name.
const std::string & detectorName () const
Get the detector name.
const core::Version & version () const
Get the module version.
virtual void initModule ()=0
Initialize the module.
virtual void readSettings (const core::TiXmlHandle &handle)=0
Read the user settings from the xml handle.
virtual void startOfRun (core::Run &run)=0
Callback function on start of run.
virtual void startOfCycle ()=0
Callback function on start of cycle.
virtual void endOfCycle (const EOCCondition &condition)=0
Callback function on end of cycle The monitor elements are send to the collector after calling this function.
virtual void endOfRun (const core::Run &run)=0
Callback function on end of run.
virtual void endModule ()=0
Callback function before terminate.
Protected Member Functions
void setDetectorName (const std::string &detector)
Set the detector name.
void setName (const std::string &module)
Set the module name.
void setVersion (unsigned int major, unsigned int minor=0, unsigned int patch=0)
Set the module version.
Private Member Functions
ModuleApplication * moduleApplication () const
Get the module application to which the module is associated.
void setModuleApplication (ModuleApplication *application)
Set the module application to which the module is associated.
Private Attributes
std::string m_name = {""}
The module name.
std::string m_detectorName = {""}
The detector name for this module.
core::Version m_version = {}
The module version.
ModuleApplication * m_moduleApplication = {nullptr}
The module application instance.
Friends
class ModuleApplication
class ModuleApi
Detailed Description
Module base class.
Base class for monitor element booking modules. See daughter classes for specific implementations.
Definition at line 34 of file Module.h.
Constructor & Destructor Documentation
dqm4hep::online::Module::Module () default
Default constructor.
dqm4hep::online::Module::Module (const Module &) delete
virtual dqm4hep::online::Module::~Module () inline virtual
Destructor.
Definition at line 48 of file Module.h.
 {}
Member Function Documentation
const std::string & dqm4hep::online::Module::detectorName () const
Get the detector name.
Definition at line 36 of file Module.cc.
References m_detectorName.
{
       return m_detectorName;
     }
virtual void dqm4hep::online::Module::endModule () pure virtual
Callback function before terminate.
Implemented in dqm4hep::online::TestStandaloneModule, and dqm4hep::online::TestAnalysisModule.
virtual void dqm4hep::online::Module::endOfCycle (const EOCCondition & condition) pure virtual
Callback function on end of cycle The monitor elements are send to the collector after calling this function.
Parameters
condition the end of cycle conditions
Implemented in dqm4hep::online::TestStandaloneModule, and dqm4hep::online::TestAnalysisModule.
virtual void dqm4hep::online::Module::endOfRun (const core::Run & run) pure virtual
Callback function on end of run.
User can get final run configuration from the run object
Parameters
run the run configuration
Implemented in dqm4hep::online::TestStandaloneModule, and dqm4hep::online::TestAnalysisModule.
Referenced by dqm4hep::online::ModuleApplication::onInit().
virtual void dqm4hep::online::Module::initModule () pure virtual
Initialize the module.
In this method, user should book monitor elements. See ModuleApi class.
Implemented in dqm4hep::online::TestStandaloneModule, and dqm4hep::online::TestAnalysisModule.
ModuleApplication * dqm4hep::online::Module::moduleApplication () const private
Get the module application to which the module is associated.
Definition at line 54 of file Module.cc.
References m_moduleApplication.
Referenced by dqm4hep::online::ModuleApi::addQualityTest(), dqm4hep::online::ModuleApi::bookHisto(), dqm4hep::online::ModuleApi::bookObject(), dqm4hep::online::ModuleApi::bookScalar(), dqm4hep::online::ModuleApi::cd(), dqm4hep::online::ModuleApi::checkModule(), dqm4hep::online::ModuleApi::dirExists(), dqm4hep::online::ModuleApi::dump(), dqm4hep::online::ModuleApi::getMonitorElement(), dqm4hep::online::ModuleApi::getMonitorElements(), dqm4hep::online::ModuleApi::goUp(), dqm4hep::online::ModuleApi::mkdir(), dqm4hep::online::ModuleApi::pwd(), dqm4hep::online::ModuleApi::resetMonitorElements(), and dqm4hep::online::ModuleApi::rmdir().
{
       return m_moduleApplication;
     }
const std::string & dqm4hep::online::Module::name () const
Get the module name.
Definition at line 24 of file Module.cc.
References m_name.
Referenced by dqm4hep::online::ModuleApi::bookHisto(), dqm4hep::online::ModuleApi::bookObject(), and dqm4hep::online::ModuleApi::bookScalar().
{
       return m_name;
     }
Module& dqm4hep::online::Module::operator= (const Module &) delete
virtual void dqm4hep::online::Module::readSettings (const core::TiXmlHandle & handle) pure virtual
Read the user settings from the xml handle.
handle the xml handle
Implemented in dqm4hep::online::TestStandaloneModule, and dqm4hep::online::TestAnalysisModule.
void dqm4hep::online::Module::setDetectorName (const std::string & detector) protected
Set the detector name.
Parameters
detectorName the detector name
Definition at line 30 of file Module.cc.
References m_detectorName.
{
       m_detectorName = detector;
     }
void dqm4hep::online::Module::setModuleApplication (ModuleApplication * application) private
Set the module application to which the module is associated.
Parameters
application the module application
Definition at line 60 of file Module.cc.
References m_moduleApplication.
{
       m_moduleApplication = application;
     }
void dqm4hep::online::Module::setName (const std::string & module) protected
Set the module name.
name the module name
Definition at line 18 of file Module.cc.
References m_name.
{
       m_name = module;
     }
void dqm4hep::online::Module::setVersion (unsigned int major, unsigned int minor = 0, unsigned int patch = 0) protected
Set the module version.
Parameters
major the major version
minor the minor version
patch the patch number
Definition at line 42 of file Module.cc.
References m_version, and dqm4hep::core::Version::set().
{
       m_version.set(major, minor, patch);
     }
virtual void dqm4hep::online::Module::startOfCycle () pure virtual
Callback function on start of cycle.
User can take appropriate actions such as monitor element reset, etc ...
Implemented in dqm4hep::online::TestStandaloneModule, and dqm4hep::online::TestAnalysisModule.
virtual void dqm4hep::online::Module::startOfRun (core::Run & run) pure virtual
Callback function on start of run.
User can get run configuration from the run object
Parameters
run the run configuration
Implemented in dqm4hep::online::TestStandaloneModule, and dqm4hep::online::TestAnalysisModule.
Referenced by dqm4hep::online::ModuleApplication::onInit().
const core::Version & dqm4hep::online::Module::version () const
Get the module version.
Definition at line 48 of file Module.cc.
References m_version.
{
       return m_version;
     }
Friends And Related Function Documentation
friend class ModuleApi friend
Definition at line 36 of file Module.h.
friend class ModuleApplication friend
Definition at line 35 of file Module.h.
Member Data Documentation
std::string dqm4hep::online::Module::m_detectorName = {""} private
The detector name for this module.
Definition at line 155 of file Module.h.
Referenced by detectorName(), and setDetectorName().
ModuleApplication* dqm4hep::online::Module::m_moduleApplication = {nullptr} private
The module application instance.
Definition at line 159 of file Module.h.
Referenced by moduleApplication(), and setModuleApplication().
std::string dqm4hep::online::Module::m_name = {""} private
The module name.
Definition at line 153 of file Module.h.
Referenced by name(), and setName().
core::Version dqm4hep::online::Module::m_version = {} private
The module version.
Definition at line 157 of file Module.h.
Referenced by setVersion(), and version().
The documentation for this class was generated from the following files:
Module.h
Module.cc