DQM4hep: dqm4hep::core::MonitorElementManager Class Reference
dqm4hep::core::MonitorElementManager Class Reference
MonitorElementManager class.
#include <MonitorElementManager.h>
Public Member Functions
MonitorElementManager ()
Constructor.
~MonitorElementManager ()
Destructor.
void cd ()
Go back to root directory.
StatusCode cd (const std::string &dirName)
Go to specific directory.
StatusCode mkdir (const std::string &dirName)
Create a directory If the directory name starts with with '/' the path is absolute and refers to the root directory, else it refers to the current directory.
const std::string & pwd ()
Get the current directory name.
const std::string & fullPwd ()
Get the current directory full name (parents included)
StatusCode goUp ()
Navigate backward in the directory structure.
StatusCode rmdir (const std::string &dirName)
Remove a directory If the directory name starts with with '/' the path is absolute and refers to the root directory, else it refers to the current directory.
bool dirExists (const std::string &dirName) const
Whether the directory exists or not.
template<typename T >
StatusCode addMonitorElement (const std::string &path, TObject *object, std::shared_ptr< T > &monitorElement)
Add a monitor element from an external source.
template<typename T >
StatusCode readMonitorElement (const std::string &fileName, const std::string &path, const std::string &name, std::shared_ptr< T > &monitorElement)
Read TObject from file and add it to list.
template<typename T >
StatusCode readMonitorElement (TFile *pTFile, const std::string &path, const std::string &name, std::shared_ptr< T > &monitorElement)
Read TObject from file and add it to list.
template<typename T >
StatusCode bookMonitorElement (const std::string &className, const std::string &path, const std::string &name, std::shared_ptr< T > &monitorElement)
Book a monitor element using the ROOT TClass facility.
template<typename T >
StatusCode handleMonitorElement (const std::string &path, TObject *pObject, std::shared_ptr< T > &monitorElement)
Handle and wrap the TObject in a monitor element.
template<typename ObjectType , typename T , typename... Args>
StatusCode bookObject (const std::string &path, const std::string &name, const std::string &title, std::shared_ptr< T > &monitorElement, Args...args)
Create a custom ROOT object and wrap it into a monitor element.
template<typename HistoType , typename T , typename... Args>
StatusCode bookHisto (const std::string &path, const std::string &name, const std::string &title, std::shared_ptr< T > &monitorElement, Args...args)
Create a ROOT histogram and wrap it into a monitor element.
template<typename ScalarType , typename T , typename... Args>
StatusCode bookScalar (const std::string &path, const std::string &name, const std::string &title, std::shared_ptr< T > &monitorElement, Args...args)
Create a TScalarObject<ScalarType> of type T and wrap it into a monitor element.
template<typename T >
StatusCode attachReference (std::shared_ptr< T > monitorElement, const std::string &refId)
Find reference file using the refId, look for a reference object and attach it to the monitor element.
template<typename T >
StatusCode attachReference (std::shared_ptr< T > monitorElement, const std::string &refId, const std::string &path, const std::string &name)
Find reference file using the refId, look for a reference object and attach it to the monitor element.
void monitorElementsToJson (json &object) const
Write all monitor elements in the storage to json.
StatusCode addReferenceFile (const std::string &refId, const std::string &fname)
Add a reference file under the specified id.
template<typename T , typename Function >
void iterate (Function function)
Iterate over the monitor element directory structure and call the user callback function.
void dumpStorage ()
Dump the monitor element storage in the console.
template<typename T >
StatusCode parseStorage (TiXmlElement *xmlElement)
Parse the xml section describing:
StatusCode archive (Archiver &archiver, bool withReferences=true)
Archive the current monitor element content in a root file.
template<typename T >
void getMonitorElements (std::vector< std::shared_ptr< T >> &monitorElements) const
Get all the monitor elements already booked by this module in all the directories.
template<typename T >
StatusCode getMonitorElement (const std::string &name, std::shared_ptr< T > &monitorElement) const
Get the monitor element in the current directory (result by ptr reference)
template<typename T >
StatusCode getMonitorElement (const std::string &path, const std::string &name, std::shared_ptr< T > &monitorElement) const
Get the monitor element in the given directory (result by ptr reference)
void resetMonitorElements ()
Reset all monitor elements.
StatusCode removeMonitorElement (const std::string &path, const std::string &name)
Remove a specific monitor element.
StatusCode createQualityTest (TiXmlElement *const pXmlElement, float warning=QualityTest::defaultWarningLimit(), float error=QualityTest::defaultErrorLimit())
Create a quality test from the xml element.
StatusCode addQualityTest (const std::string &path, const std::string &name, const std::string &qualityTestName)
Attach an already created quality test to the monitor element.
StatusCode removeQualityTest (const std::string &path, const std::string &name, const std::string &qualityTestName)
Remove a quality test from the monitor element.
StatusCode runQualityTests (QReportStorage &reports)
Run all quality tests for all monitor elements and receive qtest reports.
StatusCode runQualityTests (const std::string &path, const std::string &name, QReportStorage &reports)
Run all quality tests attached to a particular monitor element.
StatusCode runQualityTest (const std::string &path, const std::string &name, const std::string &qualityTestName, QReportStorage &reports)
Run a particular quality test on one monitor element.
Private Types
typedef std::shared_ptr
< QualityTest > QualityTestPtr
typedef std::shared_ptr
< QualityTestFactory > QualityTestFactoryPtr
typedef std::map< const
std::string, QualityTestPtr > QualityTestMap
typedef std::map< const
std::string, const
QualityTestFactoryPtr > QualityTestFactoryMap
typedef std::shared_ptr
< TObjectXMLAllocator > XMLAllocatorPtr
typedef std::map
< MonitorElementPtr,
QualityTestMap > MonitorElementToQTestMap
typedef std::map< std::string,
XMLAllocatorPtr > XMLAllocatorMap
typedef std::map< std::string,
std::shared_ptr< TFile > > ReferenceMap
Private Member Functions
StatusCode parseStyle (TiXmlElement *xmlElement)
Read the style settings from the XML element.
template<typename T >
StatusCode bookMonitorElement (TiXmlElement *xmlElement, std::shared_ptr< T > &monitorElement)
Book a monitor element from the xml element.
template<typename T >
StatusCode parseMonitorElements (TiXmlElement *xmlElement)
Read monitor element described by the xml element.
template<typename T >
StatusCode readMonitorElement (const std::string &fileName, TiXmlElement *xmlElement, std::shared_ptr< T > &monitorElement)
Read monitor element described by the xml element from a root file.
StatusCode parseReferences (TiXmlElement *xmlElement)
Read reference files from XML element Feed a map of reference id (string) and reference file.
StatusCode parseReference (TiXmlElement *xmlElement)
Read a single reference file the from XML element Feed the map of reference id (string) -> reference file.
StatusCode parseQualityTests (TiXmlElement *xmlElement)
Create quality tests from the xml element.
bool checkClass (TClass *cls)
Check if the target class is compatible with the DQM4hep requirements.
StatusCode addToStorage (const std::string &path, MonitorElementPtr element)
Add a monitor element to the internal storage.
template<typename T >
StatusCode createAndAddMonitorElement (const std::string &path, TObject *pObject, std::shared_ptr< T > &monitorElement, bool owner)
Create a monitor element and add it the internal storage.
template<typename T >
StatusCode attachReference (std::shared_ptr< T > monitorElement, TiXmlElement *xmlElement)
Attach a reference, describe by the XML element, to the target monitor element.
template<typename T , typename... Args>
std::shared_ptr< T > createMonitorElement (Args...args)
Performs the actual monitor element memory allocation.
const Storage< MonitorElement > & getStorage () const
Get the monitor element storage.
template<typename T >
void doROOTNotOwner (T function)
Perform a user action after having disabling any ROOT framework memory handling such as the one implicitly done with TObject::GetObjectStat() or with TH1::AddDirectoryStatus().
Private Attributes
Storage< MonitorElement > m_storage = {}
The internal monitor element storage.
QualityTestMap m_qualityTestMap = {}
The actual allocated quality test map.
XMLAllocatorMap m_xmlAllocatorMap = {}
The XML allocator map to create monitor elements from XML description.
XMLAllocatorPtr m_defaultXMLAllocator = {nullptr}
The default XML allocator function.
RootStyle m_objectStyle = {}
The current monitor element object style.
RootStyle m_referenceStyle = {}
The current monitor element reference style.
ReferenceMap m_references = {}
The map of reference ROOT files currently handled.
Detailed Description
MonitorElementManager class.
Definition at line 36 of file MonitorElementManager.h.
Member Typedef Documentation
typedef std::map<MonitorElementPtr, QualityTestMap> dqm4hep::core::MonitorElementManager::MonitorElementToQTestMap private
Definition at line 569 of file MonitorElementManager.h.
typedef std::map<const std::string, const QualityTestFactoryPtr> dqm4hep::core::MonitorElementManager::QualityTestFactoryMap private
Definition at line 40 of file MonitorElementManager.h.
typedef std::shared_ptr<QualityTestFactory> dqm4hep::core::MonitorElementManager::QualityTestFactoryPtr private
Definition at line 38 of file MonitorElementManager.h.
typedef std::map<const std::string, QualityTestPtr> dqm4hep::core::MonitorElementManager::QualityTestMap private
Definition at line 39 of file MonitorElementManager.h.
typedef std::shared_ptr<QualityTest> dqm4hep::core::MonitorElementManager::QualityTestPtr private
Definition at line 37 of file MonitorElementManager.h.
typedef std::map<std::string, std::shared_ptr<TFile> > dqm4hep::core::MonitorElementManager::ReferenceMap private
Definition at line 571 of file MonitorElementManager.h.
typedef std::map<std::string, XMLAllocatorPtr> dqm4hep::core::MonitorElementManager::XMLAllocatorMap private
Definition at line 570 of file MonitorElementManager.h.
typedef std::shared_ptr<TObjectXMLAllocator> dqm4hep::core::MonitorElementManager::XMLAllocatorPtr private
Definition at line 568 of file MonitorElementManager.h.
Constructor & Destructor Documentation
dqm4hep::core::MonitorElementManager::MonitorElementManager ()
Constructor.
Definition at line 26 of file MonitorElementManager.cc.
References m_defaultXMLAllocator, and m_xmlAllocatorMap.
{
       // the default one
       m_defaultXMLAllocator = std::make_shared<DefaultXMLAllocator>();
       // TH1
       m_xmlAllocatorMap["TH1D"] = std::make_shared<TH1XMLAllocator>();
       m_xmlAllocatorMap["TH1F"] = std::make_shared<TH1XMLAllocator>();
       m_xmlAllocatorMap["TH1I"] = std::make_shared<TH1XMLAllocator>();
       m_xmlAllocatorMap["TH1C"] = std::make_shared<TH1XMLAllocator>();
       m_xmlAllocatorMap["TH1S"] = std::make_shared<TH1XMLAllocator>();
       // TH2
       m_xmlAllocatorMap["TH2D"] = std::make_shared<TH2XMLAllocator>();
       m_xmlAllocatorMap["TH2F"] = std::make_shared<TH2XMLAllocator>();
       m_xmlAllocatorMap["TH2I"] = std::make_shared<TH2XMLAllocator>();
       m_xmlAllocatorMap["TH2C"] = std::make_shared<TH2XMLAllocator>();
       m_xmlAllocatorMap["TH2S"] = std::make_shared<TH2XMLAllocator>();
       // TH2
       m_xmlAllocatorMap["TH3D"] = std::make_shared<TH3XMLAllocator>();
       m_xmlAllocatorMap["TH3F"] = std::make_shared<TH3XMLAllocator>();
       m_xmlAllocatorMap["TH3I"] = std::make_shared<TH3XMLAllocator>();
       m_xmlAllocatorMap["TH3C"] = std::make_shared<TH3XMLAllocator>();
       m_xmlAllocatorMap["TH3S"] = std::make_shared<TH3XMLAllocator>();
       // scalars
       m_xmlAllocatorMap["int"] = std::make_shared<TScalarXMLAllocator>();
       m_xmlAllocatorMap["real"] = std::make_shared<TScalarXMLAllocator>();
       m_xmlAllocatorMap["float"] = std::make_shared<TScalarXMLAllocator>();
       m_xmlAllocatorMap["double"] = std::make_shared<TScalarXMLAllocator>();
       m_xmlAllocatorMap["short"] = std::make_shared<TScalarXMLAllocator>();
       m_xmlAllocatorMap["long"] = std::make_shared<TScalarXMLAllocator>();
       m_xmlAllocatorMap["long64"] = std::make_shared<TScalarXMLAllocator>();
       // others
       m_xmlAllocatorMap["THStack"] = std::make_shared<THStackXMLAllocator>();
       m_xmlAllocatorMap["TH2Poly"] = std::make_shared<TH2PolyXMLAllocator>();
       m_xmlAllocatorMap["TProfile"] = std::make_shared<TProfileXMLAllocator>();
       m_xmlAllocatorMap["TProfile2D"] = std::make_shared<TProfile2DXMLAllocator>();
     }
dqm4hep::core::MonitorElementManager::~MonitorElementManager ()
Destructor.
Definition at line 64 of file MonitorElementManager.cc.
References m_qualityTestMap.
{
       m_qualityTestMap.clear();
     }
Member Function Documentation
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::addMonitorElement (const std::string & path, TObject * object, std::shared_ptr< T > & monitorElement)
Add a monitor element from an external source.
WARNING : The ROOT object is owned by the framework. The caller must NOT delete the object
Parameters
path the monitor element path in the directory structure
object the ROOT object to wrap in a monitor element
monitorElement the monitor element pointer to receive
Definition at line 712 of file MonitorElementManager.h.
{
       return createAndAddMonitorElement<T>(path, pObject, monitorElement, true);
     }
StatusCode dqm4hep::core::MonitorElementManager::addQualityTest (const std::string & path, const std::string & name, const std::string & qualityTestName)
Attach an already created quality test to the monitor element.
Parameters
path the path to the monitor element
name the name of the monitor element
qualityTestName the name of the quality test to attach
Definition at line 225 of file MonitorElementManager.cc.
References RETURN_RESULT_IF.
Referenced by parseMonitorElements().
{
       auto findIter = m_qualityTestMap.find(qualityTestName);
       if (m_qualityTestMap.end() == findIter)
         return STATUS_CODE_NOT_FOUND;
       MonitorElementPtr monitorElement;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElement(path, name, monitorElement));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, monitorElement->addQualityTest(findIter->second));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::addReferenceFile (const std::string & refId, const std::string & fname)
Add a reference file under the specified id.
Parameters
refId the reference file id
fname the reference file name
Definition at line 389 of file MonitorElementManager.cc.
References dqm_error.
{
       auto findIter = m_references.find(refId);
       if(m_references.end() != findIter) {
         dqm_error( "The reference id '{0}' is already registered with file name '{1}'", refId, findIter->second->GetName());
         return STATUS_CODE_ALREADY_PRESENT;
       }
       std::shared_ptr<TFile> filePtr(TFile::Open(fname.c_str(), "READ"));
       if(nullptr == filePtr) {
         dqm_error( "Couldn't open reference file '{0}'", fname );
         return STATUS_CODE_FAILURE;
       }
       m_references[refId] = filePtr;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::addToStorage (const std::string & path, MonitorElementPtr element) private
Add a monitor element to the internal storage.
Parameters
path the path where to add this monitor element
element the monitor element to add
Definition at line 331 of file MonitorElementManager.cc.
Referenced by createAndAddMonitorElement().
{
       // check for existence
       if (nullptr != m_storage.findObject(path, [&](MonitorElementPtr obj) {
         return obj->name() == monitorElement->name();
       })) {
         dqm_error("Monitor element '{0}' in directory '{1}' already booked !", monitorElement->name(), path);
         return STATUS_CODE_ALREADY_PRESENT;
       }
       // try to add it
       try {
         std::string fullPath;
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_storage.add(path, monitorElement, fullPath));
         monitorElement->setPath(fullPath);
       }
       catch (StatusCodeException &e) {
         return e.getStatusCode();
       }
       catch (...) {
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::archive (Archiver & archiver, bool withReferences = true)
Archive the current monitor element content in a root file.
Parameters
archiver the archiver performing the write operation
withReferences whether to write references with monitor elements
Definition at line 430 of file MonitorElementManager.cc.
References dqm4hep::core::Archiver::archive(), and dqm4hep::core::Archiver::archiveWithReferences().
{
       if(withReferences) {
         return archiver.archiveWithReferences(m_storage, "", "_ref");
       }
       else {
         return archiver.archive(m_storage, "");
       }
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::attachReference (std::shared_ptr< T > monitorElement, const std::string & refId) inline
Find reference file using the refId, look for a reference object and attach it to the monitor element.
The path and name of the reference must be the same as the monitor element
Parameters
monitorElement the monitor element to attach the reference
refId the reference file id
Definition at line 811 of file MonitorElementManager.h.
Referenced by attachReference(), and parseMonitorElements().
{
       if (nullptr == monitorElement) {
         return STATUS_CODE_INVALID_PTR;
       }
       return attachReference(monitorElement, refId, monitorElement->path(), monitorElement->name());
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::attachReference (std::shared_ptr< T > monitorElement, const std::string & refId, const std::string & path, const std::string & name) inline
Find reference file using the refId, look for a reference object and attach it to the monitor element.
Parameters
monitorElement the monitor element to attach the reference
refId the reference file id
path the path to reference object in file
name the name to reference object in file
Definition at line 821 of file MonitorElementManager.h.
References dqm4hep::core::RootStyle::applyTo(), doROOTNotOwner(), dqm_debug, dqm_error, dqm4hep::core::Path::getPath(), m_references, and m_referenceStyle.
{
       if (nullptr == monitorElement){
         return STATUS_CODE_INVALID_PTR;
       }
       Path fullName = path;
       fullName += name;
       dqm_debug("MonitorElementManager::attachReference: looking for element {0}", fullName.getPath());
       auto findIter = m_references.find(refId);
       if(m_references.end() == findIter) {
         dqm_error( "MonitorElementManager::attachReference: refId '{0}' not found !", refId );
         return STATUS_CODE_NOT_FOUND;
       }
       auto rootFile = findIter->second;
       const std::string queryPath = (path == "/") ? name : fullName.getPath();
       TObject *pTObject = nullptr;
       doROOTNotOwner([&](){
         auto local = rootFile->Get(queryPath.c_str());
         if(nullptr != local) {
           pTObject = local->Clone();
         }
       });
       if (pTObject == nullptr)
         return STATUS_CODE_NOT_FOUND;
       m_referenceStyle.applyTo(pTObject);
       monitorElement->setReferenceObject(pTObject);
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::attachReference (std::shared_ptr< T > monitorElement, TiXmlElement * xmlElement) private
Attach a reference, describe by the XML element, to the target monitor element.
Parameters
monitorElement the monitor element to which to attach the reference
xmlElement the XML element from which to extract the reference
Definition at line 950 of file MonitorElementManager.h.
References attachReference(), dqm4hep::core::XmlHelper::getAttribute(), and RETURN_RESULT_IF.
{
       std::string refId, path, name;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(element, "id", refId));
       auto pathCode = XmlHelper::getAttribute(element, "path", path);
       if(STATUS_CODE_NOT_FOUND == pathCode) {
         path = monitorElement->path();
       }
       else if(STATUS_CODE_SUCCESS != pathCode) {
         return pathCode;
       }
       auto nameCode = XmlHelper::getAttribute(element, "name", name);
       if(STATUS_CODE_NOT_FOUND == nameCode) {
         name = monitorElement->name();
       }
       else if(STATUS_CODE_SUCCESS != nameCode) {
         return nameCode;
       }
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, attachReference(monitorElement, refId, path, name));
       return STATUS_CODE_SUCCESS;
     }
template<typename HistoType , typename T , typename... Args> StatusCode dqm4hep::core::MonitorElementManager::bookHisto (const std::string & path, const std::string & name, const std::string & title, std::shared_ptr< T > & monitorElement, Args... args) inline
Create a ROOT histogram and wrap it into a monitor element.
The created histogram is owned by the monitor element and must not be delete by users. The allocation is performed using the ROOT object constructor possibly with arguments. For scalar types (int, double, ...) use the bookScalar() method instead. For other custom classes, use the bookObject() function. The last argument args are the arguments passed to the histogram constructor after the "name" and "title" arguments.
Example:
// Use the constructor TH1F::TH1F(const char *name, const char *title, Int_t nBins, Double_t min, Double_t max)
MonitorElement histo1DElement = nullptr;
mgr->bookHisto<TH1F>("/MyDirectory", "SuperHisto", "A supeeeeer histo !", histo1DElement, 10, 0., 9.);
Parameters
path the path where to store the monitor element
name the monitor element name
title the monitor element title
monitorElement the monitor element pointer to receive
args optional arguments to pass to the histogram class after the name and title arguments
Definition at line 649 of file MonitorElementManager.h.
References dqm4hep::core::RootStyle::applyTo(), checkClass(), doROOTNotOwner(), dqm_warning, and m_objectStyle.
{
       monitorElement = nullptr;
       if(not checkClass(HistoType::Class())) {
         return STATUS_CODE_NOT_ALLOWED;
       }
       TObject *pTObject = nullptr;
       doROOTNotOwner([&](){
         pTObject = new HistoType(name.c_str(), title.c_str(), args...);
       });
       if (!pTObject) {
         dqm_warning("Couldn't allocate monitor element of type '{0}', path '{1}', name '{2}'", HistoType::Class_Name(), path, name);
         return STATUS_CODE_FAILURE;
       }
       m_objectStyle.applyTo(pTObject);
       return addMonitorElement<T>(path, pTObject, monitorElement);
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::bookMonitorElement (const std::string & className, const std::string & path, const std::string & name, std::shared_ptr< T > & monitorElement) inline
Book a monitor element using the ROOT TClass facility.
The className is passed to TClass::GetClass() to get the corresponding TClass object handler. Note that to allocate the TObject:
the default constructor is used
the ROOT object is not referenced anywhere in the ROOT framework (see TObject::SetObjectStat and TH1::AddDirectory) The resulting allocated TObject is thus fully owned by the manager
Parameters
className the ROOT class name (i.e "TGraph") to allocate
path the path where to store the monitor element
name the TObject name to set
monitorElement the monitor element pointer to receive
Definition at line 759 of file MonitorElementManager.h.
References dqm4hep::core::RootStyle::applyTo(), checkClass(), doROOTNotOwner(), dqm_error, and m_objectStyle.
{
       monitorElement = nullptr;
       TClass *pTClass = TClass::GetClass(className.c_str());
       if(not checkClass(pTClass)) {
         return STATUS_CODE_NOT_ALLOWED;
       }
       TObject *pTObject = nullptr;
       doROOTNotOwner([&](){
         pTObject = (TObject *)pTClass->New();
       });
       if (pTObject == nullptr) {
         dqm_error("MonitorElementManager::bookMonitorElement: Couldn't allocate ROOT class '{0}' from TClass facility",
                   className);
         return STATUS_CODE_FAILURE;
       }
       ((TNamed *)pTObject)->SetName(name.c_str());
       m_objectStyle.applyTo(pTObject);
       return addMonitorElement<T>(path, pTObject, monitorElement);
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::bookMonitorElement (TiXmlElement * xmlElement, std::shared_ptr< T > & monitorElement) inline private
Book a monitor element from the xml element.
Parameters
xmlElement the xml element to parse
monitorelement the monitor element to receive
Definition at line 783 of file MonitorElementManager.h.
References dqm4hep::core::RootStyle::applyTo(), doROOTNotOwner(), dqm_error, dqm4hep::core::XmlHelper::getAttribute(), m_defaultXMLAllocator, m_objectStyle, m_xmlAllocatorMap, RETURN_RESULT_IF, and RETURN_RESULT_IF_AND_IF.
{
       if(nullptr == xmlElement) {
         return STATUS_CODE_INVALID_PTR;
       }
       std::string className, name, path, title;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(xmlElement, "type", className));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(xmlElement, "name", name));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(xmlElement, "path", path));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(xmlElement, "title", title));
       auto findIter = m_xmlAllocatorMap.find(className);
       XMLAllocatorPtr allocator = (m_xmlAllocatorMap.end() == findIter) ? m_defaultXMLAllocator : findIter->second;
       TObject *pTObject = nullptr;
       doROOTNotOwner([&](){
         pTObject = allocator->create(xmlElement);
       });
       if(nullptr == pTObject) {
         dqm_error( "Object of type '{0}' couldn't be created from xml element !", className );
         return STATUS_CODE_FAILURE;
       }
       dynamic_cast<TNamed *>(pTObject)->SetNameTitle(name.c_str(), title.c_str());
       m_objectStyle.applyTo(pTObject);
       return addMonitorElement<T>(path, pTObject, monitorElement);
     }
template<typename ObjectType , typename T , typename... Args> StatusCode dqm4hep::core::MonitorElementManager::bookObject (const std::string & path, const std::string & name, const std::string & title, std::shared_ptr< T > & monitorElement, Args... args) inline
Create a custom ROOT object and wrap it into a monitor element.
WARNING: The root class must inherit form TNamed in order to set the name and title corectly. The created TObject is owned by the monitor element and must not be delete by users. The allocation is performed using the ROOT object constructor possibly with arguments. For histogram classes like TH1, TH2, TH3 and TProfile and daughters, use the bookHisto() method instead. For scalar types (int, double, ...) use the bookScalar() method instead.
Example:
// Without arguments. Use the TGraph::TGraph() constructor
MonitorElement graphElement = nullptr;
mgr->bookObject<TGraph>("/MyDirectory", "SuperGraph", "A supeeeeer graph !", graphElement);
// With 42 points. Use the constructor Use the TGraph::TGraph(Int_t n) constructor
MonitorElement graphElement2 = nullptr;
mgr->bookObject<TGraph>("/MyDirectory", "SuperGraph2", "A supeeeeer graph with n points set!", graphElement2, 42);
Parameters
path the path where to store the monitor element
name the monitor element name
title the monitor element title
monitorElement the monitor element pointer to receive
args optional arguments to pass to the ROOT class constructor
Definition at line 627 of file MonitorElementManager.h.
References dqm4hep::core::RootStyle::applyTo(), checkClass(), doROOTNotOwner(), dqm_warning, and m_objectStyle.
{
       monitorElement = nullptr;
       if(not checkClass(ObjectType::Class())) {
         return STATUS_CODE_NOT_ALLOWED;
       }
       TObject *pTObject = nullptr;
       doROOTNotOwner([&](){
         pTObject = new ObjectType(args...);
       });
       if (!pTObject) {
         dqm_warning("Couldn't allocate monitor element of type '{0}', path '{1}', name '{2}'", ObjectType::Class_Name(),
                     path, name);
         return STATUS_CODE_FAILURE;
       }
       ((TNamed *)pTObject)->SetNameTitle(name.c_str(), title.c_str());
       m_objectStyle.applyTo(pTObject);
       return addMonitorElement<T>(path, pTObject, monitorElement);
     }
template<typename ScalarType , typename T , typename... Args> StatusCode dqm4hep::core::MonitorElementManager::bookScalar (const std::string & path, const std::string & name, const std::string & title, std::shared_ptr< T > & monitorElement, Args... args) inline
Create a TScalarObject<ScalarType> of type T and wrap it into a monitor element.
The created scalar object is owned by the monitor element and must not be delete by users. The allocation is performed using the TScalarObject<ScalarType> constructor possibly with arguments. For histogram classes like TH1, TH2, TH3 and TProfile and daughters, use the bookHisto() method instead. For other custom classes, use the bookObject() function. The last argument args are the arguments passed to the TScalarObject<ScalarType> constructor.
Example:
// Use the constructor TScalarObject<int>::TScalarObject<int>(int value)
MonitorElement intScalarElement = nullptr;
mgr->bookScalar<int>("/MyDirectory", "SuperScalar", "A supeeeeer scalar !", intScalarElement, 42);
Parameters
path the path where to store the monitor element
name the monitor element name
title the monitor element title
monitorElement the monitor element pointer to receive
args optional arguments to pass to the TScalarObject class
Definition at line 669 of file MonitorElementManager.h.
References dqm4hep::core::RootStyle::applyTo(), checkClass(), doROOTNotOwner(), dqm_warning, and m_objectStyle.
{
       monitorElement = nullptr;
       if(not checkClass(TScalarObject<ScalarType>::Class())) {
         return STATUS_CODE_NOT_ALLOWED;
       }
       TObject *pTObject = nullptr;
       doROOTNotOwner([&](){
         pTObject = new TScalarObject<ScalarType>(args...);
       });
       if (!pTObject) {
         dqm_warning("Couldn't allocate monitor element of type '{0}', path '{1}', name '{2}'", TScalarObject<ScalarType>::Class_Name(), path, name);
         return STATUS_CODE_FAILURE;
       }
       ((TNamed *)pTObject)->SetNameTitle(name.c_str(), title.c_str());
       m_objectStyle.applyTo(pTObject);
       return addMonitorElement<T>(path, pTObject, monitorElement);
     }
void dqm4hep::core::MonitorElementManager::cd ()
Go back to root directory.
Definition at line 70 of file MonitorElementManager.cc.
References m_storage.
{
       m_storage.cd();
     }
StatusCode dqm4hep::core::MonitorElementManager::cd (const std::string & dirName)
Go to specific directory.
If the directory name starts with with '/' the path is absolute and refers to the root directory, else it refers to the current directory
Parameters
dirName the directory name to enter
Definition at line 76 of file MonitorElementManager.cc.
References m_storage.
{
       return m_storage.cd(dirName);
     }
bool dqm4hep::core::MonitorElementManager::checkClass (TClass * cls) private
Check if the target class is compatible with the DQM4hep requirements.
See implementation for details
Parameters
cls the ROOT TClass to check
Definition at line 305 of file MonitorElementManager.cc.
References dqm_error.
Referenced by bookHisto(), bookMonitorElement(), bookObject(), bookScalar(), and createAndAddMonitorElement().
{
       if(nullptr == cls) {
         dqm_error("MonitorElementManager::checkClass: class is nullptr! Please check for class existence !");
         return false;
       }
       if(not cls->HasDictionary()) {
         dqm_error("MonitorElementManager::checkClass: class '{0}' has no dictionnary!", cls->GetName());
         return false;
       }
       if (cls->IsForeign()) {
         dqm_error(
             "MonitorElementManager::checkClass: class '{0}' is foreign (does not have a Streamer method)!",
             cls->GetName());
         return false;
       }
       if (not cls->InheritsFrom("TNamed")) {
         dqm_error("MonitorElementManager::checkClass: class '{0}' doesn't inherit TNamed (required to call "
                   "SetName())!",
                   cls->GetName());
         return false;
       }
       return true;
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::createAndAddMonitorElement (const std::string & path, TObject * pObject, std::shared_ptr< T > & monitorElement, bool owner) inline private
Create a monitor element and add it the internal storage.
Parameters
path the path where to add this monitor element
pObject the ROOT object pointer to wrap in the monitor element
monitorElement the monitor element to receive
owner whether the monitor element should owns the ROOT object
Definition at line 697 of file MonitorElementManager.h.
References addToStorage(), checkClass(), and RETURN_RESULT_IF.
{
       PtrHandler<TObject> ptrObject(pObject, owner);
       monitorElement = nullptr;
       TClass *cls = TClass::GetClass(pObject->ClassName());
       if(not checkClass(cls)) {
         return STATUS_CODE_NOT_ALLOWED;
       }
       monitorElement = createMonitorElement<T>(ptrObject);
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, addToStorage(path, monitorElement));
       return STATUS_CODE_SUCCESS;
     }
template<typename T , typename... Args> std::shared_ptr< T > dqm4hep::core::MonitorElementManager::createMonitorElement (Args... args) inline private
Performs the actual monitor element memory allocation.
The actual type T should inherit the MonitorElement class and provides the same make_shared interface as the MonitorElement class (see MonitorElement.h)
Parameters
args the arguments to forward to the allocator function
Definition at line 690 of file MonitorElementManager.h.
{
       return T::make_shared(args...);
     }
StatusCode dqm4hep::core::MonitorElementManager::createQualityTest (TiXmlElement *const pXmlElement, float warning = QualityTest::defaultWarningLimit(), float error = QualityTest::defaultErrorLimit())
Create a quality test from the xml element.
The xml element must contain the attribute 'type' and 'name'
Parameters
pXmlElement the XML element to parse
warning the warning threshold level for this particular qtest (optional)
error the error threshold level for this particular qtest (optional)
Definition at line 186 of file MonitorElementManager.cc.
References dqm4hep::core::QualityTestFactory::createQualityTest(), RETURN_RESULT_IF, and RETURN_RESULT_IF_AND_IF.
{
       std::string name, type;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "name", name));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "type", type));
       float warningLimit(warning), errorLimit(error);
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(pXmlElement, "error", errorLimit, [](const float &value){
         return (value >= 0.f && value < 1.f);
       }));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(pXmlElement, "warning", warningLimit, [&errorLimit](const float &value){
         return (value >=0.f && value > errorLimit && value <= 1.f);
       }));
       // quality test already there ?
       auto findIter = m_qualityTestMap.find(name);
       if (m_qualityTestMap.end() != findIter) {
         return STATUS_CODE_ALREADY_PRESENT;
       }
       // create our quality test from plugins
       auto mgr = PluginManager::instance();
       auto factory = mgr->create<QualityTestFactory>(type);
       if(nullptr == factory) {
         return STATUS_CODE_NOT_FOUND;
       }
       auto qualityTest = factory->createQualityTest(name);
       // configure our quality test
       qualityTest->setLimits(warningLimit, errorLimit);
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, qualityTest->readSettings(TiXmlHandle(pXmlElement)));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, qualityTest->init());
       // add it !
       if (!m_qualityTestMap.insert(QualityTestMap::value_type(name, qualityTest)).second) {
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
bool dqm4hep::core::MonitorElementManager::dirExists (const std::string & dirName) const
Whether the directory exists or not.
If the directory name starts with with '/' the path is absolute and refers to the root directory, else it refers to the current directory
Parameters
dirName the directory name
Definition at line 119 of file MonitorElementManager.cc.
References m_storage.
{
       return m_storage.dirExists(dirName);
     }
template<typename T > void dqm4hep::core::MonitorElementManager::doROOTNotOwner (T function) private
Perform a user action after having disabling any ROOT framework memory handling such as the one implicitly done with TObject::GetObjectStat() or with TH1::AddDirectoryStatus().
The ROOT memory handling is restored after the function has been called. The function must have the form 'void f()'.
Parameters
function a user call back function
Definition at line 927 of file MonitorElementManager.h.
Referenced by attachReference(), bookHisto(), bookMonitorElement(), bookObject(), bookScalar(), and readMonitorElement().
{
       const bool objectStat(TObject::GetObjectStat());
       const bool directoryStatus(TH1::AddDirectoryStatus());
       TObject::SetObjectStat(false);
       TH1::AddDirectory(false);
       userFunction();
       TH1::AddDirectory(directoryStatus);
       TObject::SetObjectStat(objectStat);
     }
void dqm4hep::core::MonitorElementManager::dumpStorage ()
Dump the monitor element storage in the console.
Uses the macro dqm_info() for printing out
Definition at line 356 of file MonitorElementManager.cc.
{
       m_storage.dump([](MonitorElementPtr monitorElement){
         return monitorElement->name() + " (" + monitorElement->type() + ") - " + monitorElement->title();
       });
     }
const std::string & dqm4hep::core::MonitorElementManager::fullPwd ()
Get the current directory full name (parents included)
Definition at line 101 of file MonitorElementManager.cc.
References m_storage.
{
       return m_storage.current()->fullPath().getPath();
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::getMonitorElement (const std::string & name, std::shared_ptr< T > & monitorElement) const inline
Get the monitor element in the current directory (result by ptr reference)
Parameters
name the name of the monitor element
monitorElement the monitor element to receive
Definition at line 600 of file MonitorElementManager.h.
References m_storage.
Referenced by removeMonitorElement().
{
       monitorElement = std::dynamic_pointer_cast<T>(m_storage.findObject([&name](const MonitorElementPtr &elt) { return (elt->name() == name); }));
       if (nullptr == monitorElement)
         return STATUS_CODE_NOT_FOUND;
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::getMonitorElement (const std::string & path, const std::string & name, std::shared_ptr< T > & monitorElement) const inline
Get the monitor element in the given directory (result by ptr reference)
Parameters
path the path to the monitor element to find
name the name of the monitor element to find
monitorElement the monitor element to receive
Definition at line 613 of file MonitorElementManager.h.
References m_storage.
{
       monitorElement = std::dynamic_pointer_cast<T>(
           m_storage.findObject(dirName, [&name](const MonitorElementPtr &elt) { return (elt->name() == name); }));
       if (nullptr == monitorElement)
         return STATUS_CODE_NOT_FOUND;
       return STATUS_CODE_SUCCESS;
     }
template<typename T > void dqm4hep::core::MonitorElementManager::getMonitorElements (std::vector< std::shared_ptr< T >> & monitorElements) const inline
Get all the monitor elements already booked by this module in all the directories.
Parameters
monitorElements the monitor elements to receive
Definition at line 593 of file MonitorElementManager.h.
References m_storage.
{
       m_storage.getObjects(monitorElements);
     }
const Storage< MonitorElement > & dqm4hep::core::MonitorElementManager::getStorage () const private
Get the monitor element storage.
Definition at line 299 of file MonitorElementManager.cc.
{
       return m_storage;
     }
StatusCode dqm4hep::core::MonitorElementManager::goUp ()
Navigate backward in the directory structure.
Equivalent of 'cd ..' in a shell.
Definition at line 107 of file MonitorElementManager.cc.
References m_storage.
{
       return m_storage.goUp();
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::handleMonitorElement (const std::string & path, TObject * pObject, std::shared_ptr< T > & monitorElement) inline
Handle and wrap the TObject in a monitor element.
WARNING : The ROOT object is NOT owned by the framework. The caller must delete the object on termination. You might use this function when the TObject is owned by another framework.
Parameters
path the path where to store the monitor element
pObject the input ROOT TObject to wrap
monitorElement the monitor element pointer to receive
Definition at line 719 of file MonitorElementManager.h.
{
       return createAndAddMonitorElement<T>(path, pObject, monitorElement, false);
     }
template<typename T , typename Function > void dqm4hep::core::MonitorElementManager::iterate (Function function) inline
Iterate over the monitor element directory structure and call the user callback function.
The user function must have the form void f(std::shared_ptr<T> ptr), where T stand for the monitor element type, i.e MonitorElement.
Example:
// Use a lambda function
mgr->iterate<MonitorElement>([](std::shared_ptr<MonitorElement> ptr){
  std::cout << "Got element: type: " << ptr->type() << ", name: " << ptr->name() << std::endl;
});
Parameters
function a user of the form void f(std::shared_ptr<T> ptr);
Definition at line 940 of file MonitorElementManager.h.
References m_storage.
{
       m_storage.iterate([&](const Directory<MonitorElement>::DirectoryPtr &, MonitorElementPtr monitorElement){
         auto castPointer = std::dynamic_pointer_cast<T>(monitorElement);
         return function(castPointer);
       });
     }
StatusCode dqm4hep::core::MonitorElementManager::mkdir (const std::string & dirName)
Create a directory If the directory name starts with with '/' the path is absolute and refers to the root directory, else it refers to the current directory.
Parameters
dirName the directory name
Definition at line 82 of file MonitorElementManager.cc.
References m_storage.
{
       return m_storage.mkdir(dirName);
     }
void dqm4hep::core::MonitorElementManager::monitorElementsToJson (json & object) const
Write all monitor elements in the storage to json.
Parameters
object the json object to receive
Definition at line 134 of file MonitorElementManager.cc.
References m_storage.
{
       m_storage.iterate([&object](const MonitorElementDir &, MonitorElementPtr monitorElement) {
         json meObject;
         monitorElement->toJson(meObject);
         object.push_back(meObject);
         return true;
       });
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::parseMonitorElements (TiXmlElement * xmlElement) inline private
Read monitor element described by the xml element.
Parameters
pXmlElement the xml element describing the monitor elements
Definition at line 856 of file MonitorElementManager.h.
References addQualityTest(), attachReference(), dqm_warning, dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::XmlHelper::getAttribute(), dqm4hep::core::TiXmlNode::NextSiblingElement(), and RETURN_RESULT_IF.
{
       if(nullptr == xmlElement) {
         dqm_warning( "MonitorElementManager::readMonitorElements: No monitor elements to read from XML" );
         return STATUS_CODE_SUCCESS;
       }
       for (TiXmlElement *child = xmlElement->FirstChildElement(); child != nullptr; child = child->NextSiblingElement()) {
         std::shared_ptr<T> monitorElement;
         if(child->ValueStr() == "bookElement") {
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, bookMonitorElement<T>(child, monitorElement));
           auto referenceElement = child->FirstChildElement("reference");
           if(nullptr != referenceElement) {
             RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, attachReference(monitorElement, referenceElement));
           }
         }
         else if(child->ValueStr() == "fileElement") {
           std::string rootFile;
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(child, "file", rootFile));
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, readMonitorElement<T>(rootFile, child, monitorElement));
           auto referenceElement = child->FirstChildElement("reference");
           if(nullptr != referenceElement) {
             RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, attachReference(monitorElement, referenceElement));
           }
         }
         else if(child->ValueStr() == "file") {
           std::string rootFile;
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(child, "name", rootFile));
           for (TiXmlElement *child2 = child->FirstChildElement("fileElement"); child2 != nullptr; child2 = child2->NextSiblingElement("fileElement")) {
             // read sub-element
             std::shared_ptr<T> monitorElement2;
             RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, readMonitorElement<T>(rootFile, child2, monitorElement2));
             auto referenceElement = child2->FirstChildElement("reference");
             if(nullptr != referenceElement) {
               RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, attachReference(monitorElement2, referenceElement));
             }
             // attach quality tests if option set
             for (TiXmlElement *qtest = child2->FirstChildElement("qtest"); qtest != nullptr; qtest = qtest->NextSiblingElement("qtest")) {
               std::string qTestName;
               RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(qtest, "name", qTestName));
               RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, addQualityTest(monitorElement2->path(), monitorElement2->name(), qTestName));
             }
           }
           continue;
         }
         else {
           continue;
         }
         // attach quality tests if option set
         for (TiXmlElement *qtest = child->FirstChildElement("qtest"); qtest != nullptr; qtest = qtest->NextSiblingElement("qtest")) {
           std::string qTestName;
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(qtest, "name", qTestName));
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, addQualityTest(monitorElement->path(), monitorElement->name(), qTestName));
         }
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::parseQualityTests (TiXmlElement * xmlElement) private
Create quality tests from the xml element.
Parameters
xmlElement the XML element to parse
Definition at line 160 of file MonitorElementManager.cc.
References dqm_error, dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::TiXmlNode::NextSiblingElement(), RETURN_RESULT_IF, and RETURN_RESULT_IF_AND_IF.
Referenced by parseStorage().
{
       if (nullptr == pXmlElement) {
         dqm_error("MonitorElementManager::createQualityTests: invalid xml element!");
         return STATUS_CODE_INVALID_PTR;
       }
       float warningLimit(QualityTest::defaultWarningLimit()), errorLimit(QualityTest::defaultWarningLimit());
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(pXmlElement, "error", errorLimit, [](const float &value){
         return (value >= 0.f && value < 1.f);
       }));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(pXmlElement, "warning", warningLimit, [&errorLimit](const float &value){
         return (value >=0.f && value > errorLimit && value <= 1.f);
       }));
       for (TiXmlElement *qtest = pXmlElement->FirstChildElement("qtest"); qtest != nullptr; qtest = qtest->NextSiblingElement("qtest")) {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->createQualityTest(qtest, warningLimit, errorLimit));
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::parseReference (TiXmlElement * xmlElement) private
Read a single reference file the from XML element Feed the map of reference id (string) -> reference file.
No reference association is made.
Parameters
element the XML element to read
Definition at line 376 of file MonitorElementManager.cc.
References RETURN_RESULT_IF.
{
       if(nullptr == element) {
         return STATUS_CODE_INVALID_PTR;
       }
       std::string id, fileName;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(element, "id", id));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(element, "name", fileName));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, addReferenceFile(id, fileName));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::parseReferences (TiXmlElement * xmlElement) private
Read reference files from XML element Feed a map of reference id (string) and reference file.
No reference association is made.
Parameters
element the XML element to read
Definition at line 364 of file MonitorElementManager.cc.
References dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::TiXmlNode::NextSiblingElement(), and RETURN_RESULT_IF.
Referenced by parseStorage().
{
       if(nullptr == element) {
         return STATUS_CODE_INVALID_PTR;
       }
       for (TiXmlElement *fileElement = element->FirstChildElement("file"); fileElement != nullptr; fileElement = fileElement->NextSiblingElement("file")) {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, parseReference(fileElement));
       }
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::parseStorage (TiXmlElement * xmlElement)
Parse the xml section describing:
monitor element style in <style>
reference files in <references>
quality tests configuration in <qtests>
monitor element to read/book in <monitorElements> The template type T reference to the monitor element type to create
Parameters
xmlElement the input xml element
Definition at line 974 of file MonitorElementManager.h.
References dqm_error, dqm4hep::core::TiXmlNode::FirstChildElement(), parseQualityTests(), parseReferences(), parseStyle(), and RETURN_RESULT_IF.
{
       if(nullptr == xmlElement) {
         dqm_error( "MonitorElementManager::parseStorage: Got nullptr as input xml element !" );
         return STATUS_CODE_INVALID_PTR;
       }
       // parse the monitor element style
       auto styleElement = xmlElement->FirstChildElement("style");
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, parseStyle(styleElement));
       // parse the references
       auto referencesElement = xmlElement->FirstChildElement("references");
       if(nullptr != referencesElement) {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, parseReferences(referencesElement));
       }
       // parse the quality tests
       auto qtestsElement = xmlElement->FirstChildElement("qtests");
       if(nullptr != qtestsElement) {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, parseQualityTests(qtestsElement));
       }
       // parse the monitor elements
       auto monitorElementsElement = xmlElement->FirstChildElement("monitorElements");
       if(nullptr != monitorElementsElement) {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, parseMonitorElements<T>(monitorElementsElement));
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::parseStyle (TiXmlElement * xmlElement) private
Read the style settings from the XML element.
Parameters
xmlElement the input XML element
Definition at line 406 of file MonitorElementManager.cc.
References dqm4hep::core::TiXmlNode::FirstChildElement(), RETURN_RESULT_IF, and RETURN_RESULT_IF_AND_IF.
Referenced by parseStorage().
{
       if(nullptr != styleElement) {
         std::string theme = RootStyle::Theme::DEFAULT;
         RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(styleElement,
           "theme", theme));
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, RootStyle::builtinStyle(theme, m_objectStyle, m_referenceStyle));
         auto objectStyleElement = styleElement->FirstChildElement("object");
         if(nullptr != objectStyleElement) {
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_objectStyle.fromXml(TiXmlHandle(objectStyleElement)));
         }
         auto referenceStyleElement = styleElement->FirstChildElement("reference");
         if(nullptr != referenceStyleElement) {
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_referenceStyle.fromXml(TiXmlHandle(referenceStyleElement)));
         }
       }
       else {
         // Use default style
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, RootStyle::builtinStyle(RootStyle::Theme::DEFAULT, m_objectStyle, m_referenceStyle));
       }
       return STATUS_CODE_SUCCESS;
     }
const std::string & dqm4hep::core::MonitorElementManager::pwd ()
Get the current directory name.
Definition at line 95 of file MonitorElementManager.cc.
References m_storage.
{
       return m_storage.pwd();
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::readMonitorElement (const std::string & fileName, const std::string & path, const std::string & name, std::shared_ptr< T > & monitorElement) inline
Read TObject from file and add it to list.
The ROOT TObject is owned by the manager. Note that this method might not be so efficient of called mutiple times as a TFile is opened and closed for each call
Parameters
fileName the ROOT file name to read
path the path to the ROOT object to read and wrap in the monitor element
name the name of the ROOT object
monitorElement the monitor element to receive
Definition at line 727 of file MonitorElementManager.h.
{
       monitorElement = nullptr;
       std::unique_ptr<TFile> rootFile(new TFile(fileName.c_str(), "READ"));
       return readMonitorElement<T>(rootFile.get(), path, name, monitorElement);
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::readMonitorElement (TFile * pTFile, const std::string & path, const std::string & name, std::shared_ptr< T > & monitorElement) inline
Read TObject from file and add it to list.
The ROOT TObject is owned by the manager.
Parameters
pTFile the ROOT file instance to read the monitor element from
path the TObject path in the file
name the TObject name in the file
monitorElement the monitor element instance to receive
Definition at line 737 of file MonitorElementManager.h.
References dqm4hep::core::RootStyle::applyTo(), doROOTNotOwner(), dqm4hep::core::Path::getPath(), and m_objectStyle.
{
       monitorElement = nullptr;
       Path fullName = path;
       fullName += name;
       const std::string queryPath = (path == "/") ? name : fullName.getPath();
       TObject *pTObject = nullptr;
       doROOTNotOwner([&](){
         auto local = pTFile->Get(queryPath.c_str());
         if(nullptr != local) {
           pTObject = local->Clone();
         }
       });
       if (pTObject == nullptr) {
         return STATUS_CODE_NOT_FOUND;
       }
       m_objectStyle.applyTo(pTObject);
       return addMonitorElement<T>(path, pTObject, monitorElement);
     }
template<typename T > StatusCode dqm4hep::core::MonitorElementManager::readMonitorElement (const std::string & fileName, TiXmlElement * xmlElement, std::shared_ptr< T > & monitorElement) inline private
Read monitor element described by the xml element from a root file.
Parameters
pXmlElement the xml element describing the objects to read
monitorelement the monitor element to receive
Definition at line 915 of file MonitorElementManager.h.
References dqm4hep::core::XmlHelper::getAttribute(), RETURN_RESULT_IF, and RETURN_RESULT_IF_AND_IF.
{
       std::string path, name;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "name", name));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(pXmlElement, "path", path));
       // read element from root file
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, readMonitorElement<T>(fileName, path, name, monitorElement));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::removeMonitorElement (const std::string & path, const std::string & name)
Remove a specific monitor element.
Parameters
path the path to the monitor element
name the name of the monitor element
Definition at line 146 of file MonitorElementManager.cc.
References getMonitorElement(), m_storage, and RETURN_RESULT_IF.
{
       MonitorElementPtr monitorElement;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElement(path, name, monitorElement));
       // remove the element form storage. Call delete operator
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_storage.remove(path, [&name](const MonitorElementPtr &element) {
         return (element->name() == name);
       }));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::removeQualityTest (const std::string & path, const std::string & name, const std::string & qualityTestName)
Remove a quality test from the monitor element.
Parameters
path the path to the monitor element
name the name of the monitor element
qualityTestName the name of the quality test to remove
Definition at line 241 of file MonitorElementManager.cc.
References RETURN_RESULT_IF.
{
       MonitorElementPtr monitorElement;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElement(path, name, monitorElement));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, monitorElement->removeQualityTest(qualityTestName));
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::MonitorElementManager::resetMonitorElements ()
Reset all monitor elements.
Definition at line 125 of file MonitorElementManager.cc.
References m_storage.
{
       m_storage.iterate([](const MonitorElementDir &, MonitorElementPtr monitorElement) {
         monitorElement->reset();
         return true;
       });
     }
StatusCode dqm4hep::core::MonitorElementManager::rmdir (const std::string & dirName)
Remove a directory If the directory name starts with with '/' the path is absolute and refers to the root directory, else it refers to the current directory.
Parameters
dirName the directory name
Definition at line 113 of file MonitorElementManager.cc.
References m_storage.
{
       return m_storage.rmdir(dirName);
     }
StatusCode dqm4hep::core::MonitorElementManager::runQualityTest (const std::string & path, const std::string & name, const std::string & qualityTestName, QReportStorage & reports)
Run a particular quality test on one monitor element.
Parameters
path the path to the monitor element
name the name of the monitor element
qualityTestName the name of the quality test to run
reports the quality test reports to receive
Definition at line 286 of file MonitorElementManager.cc.
References dqm4hep::core::QReportStorage::addReport(), and RETURN_RESULT_IF.
{
       MonitorElementPtr monitorElement;
       QReport report;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElement(path, name, monitorElement));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, monitorElement->runQualityTest(qualityTestName, report));
       reports.addReport(report);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::runQualityTests (QReportStorage & reports)
Run all quality tests for all monitor elements and receive qtest reports.
Parameters
reports the quality test reports to receive
Definition at line 252 of file MonitorElementManager.cc.
References dqm4hep::core::QReportStorage::addReports(), dqm_error, dqm4hep::core::StatusCodeException::getStatusCode(), THROW_RESULT_IF, and dqm4hep::core::StatusCodeException::toString().
{
       try {
         m_storage.iterate([&reports](const MonitorElementDir &, MonitorElementPtr monitorElement) {
           QReportMap reportMap;
           THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, monitorElement->runQualityTests(reportMap));
           reports.addReports(reportMap);
           return true;
         });
       } catch (StatusCodeException &exception) {
         dqm_error("Failed to process qtests: {0}", exception.toString());
         return exception.getStatusCode();
       } catch (...) {
         dqm_error("Failed to process qtests: Unknown exception");
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::runQualityTests (const std::string & path, const std::string & name, QReportStorage & reports)
Run all quality tests attached to a particular monitor element.
Parameters
path the path to the monitor element
name the name of the monitor element
reports the quality test reports to receive
Definition at line 273 of file MonitorElementManager.cc.
References dqm4hep::core::QReportStorage::addReports(), and RETURN_RESULT_IF.
{
       MonitorElementPtr monitorElement;
       QReportMap reportMap;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElement(path, name, monitorElement));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, monitorElement->runQualityTests(reportMap));
       reports.addReports(reportMap);
       return STATUS_CODE_SUCCESS;
     }
Member Data Documentation
XMLAllocatorPtr dqm4hep::core::MonitorElementManager::m_defaultXMLAllocator = {nullptr} private
The default XML allocator function.
Definition at line 580 of file MonitorElementManager.h.
Referenced by bookMonitorElement(), and MonitorElementManager().
RootStyle dqm4hep::core::MonitorElementManager::m_objectStyle = {} private
The current monitor element object style.
Definition at line 582 of file MonitorElementManager.h.
Referenced by bookHisto(), bookMonitorElement(), bookObject(), bookScalar(), and readMonitorElement().
QualityTestMap dqm4hep::core::MonitorElementManager::m_qualityTestMap = {} private
The actual allocated quality test map.
Definition at line 576 of file MonitorElementManager.h.
Referenced by ~MonitorElementManager().
ReferenceMap dqm4hep::core::MonitorElementManager::m_references = {} private
The map of reference ROOT files currently handled.
Definition at line 586 of file MonitorElementManager.h.
Referenced by attachReference().
RootStyle dqm4hep::core::MonitorElementManager::m_referenceStyle = {} private
The current monitor element reference style.
Definition at line 584 of file MonitorElementManager.h.
Referenced by attachReference().
Storage<MonitorElement> dqm4hep::core::MonitorElementManager::m_storage = {} private
The internal monitor element storage.
Definition at line 574 of file MonitorElementManager.h.
Referenced by cd(), dirExists(), fullPwd(), getMonitorElement(), getMonitorElements(), goUp(), iterate(), mkdir(), monitorElementsToJson(), pwd(), removeMonitorElement(), resetMonitorElements(), and rmdir().
XMLAllocatorMap dqm4hep::core::MonitorElementManager::m_xmlAllocatorMap = {} private
The XML allocator map to create monitor elements from XML description.
Definition at line 578 of file MonitorElementManager.h.
Referenced by bookMonitorElement(), and MonitorElementManager().
The documentation for this class was generated from the following files:
MonitorElementManager.h
MonitorElementManager.cc