DQM4hep: dqm4hep::core::QualityTest Class Reference
dqm4hep::core::QualityTest Class Reference abstract
QualityTest class.
#include <QualityTest.h>
Public Member Functions
QualityTest (const std::string &type, const std::string &name)
Constructor.
virtual ~QualityTest ()
Destructor.
const std::string & type () const
Get the quality test type.
const std::string & name () const
Get the quality test name (unique identifier)
const std::string & description () const
Get the quality test description.
void run (MonitorElement *monitorElement, QualityTestReport &report)
Perform the quality test result and fill the quality test report.
virtual StatusCode readSettings (const dqm4hep::core::TiXmlHandle xmlHandle)=0
Read the settings from the xml handle.
virtual StatusCode init ()
Initialize the quality test.
virtual bool enoughStatistics (MonitorElement *monitorElement) const
Whether the monitor element has enough statistics to perform the qtest.
void setLimits (float warning, float error)
Set the warning and error limits on quality test result.
float warningLimit () const
Get the warning limit.
float errorLimit () const
Get the error limit.
Static Public Member Functions
static float defaultWarningLimit ()
Get the default warning limit.
static float defaultErrorLimit ()
Get the default error limit.
Protected Member Functions
virtual void userRun (MonitorElement *monitorElement, QualityTestReport &report)=0
Runs a quality test on the given monitor element and return a quality estimate.
void fillBasicInfo (MonitorElement *monitorElement, QualityTestReport &report) const
Fill basic info in the qtest report.
Protected Attributes
std::string m_description = {""}
Quality test description.
Static Protected Attributes
static float m_defaultWarningLimit = 0.8
static float m_defaultErrorLimit = 0.5
Private Attributes
std::string m_type = {""}
Quality test type (usually class name)
std::string m_name = {""}
Quality test name.
float m_warningLimit = {m_defaultWarningLimit}
The quality test warning threshold.
float m_errorLimit = {m_defaultErrorLimit}
The quality test error threshold.
Detailed Description
QualityTest class.
Definition at line 173 of file QualityTest.h.
Constructor & Destructor Documentation
dqm4hep::core::QualityTest::QualityTest (const std::string & type, const std::string & name)
Constructor.
Definition at line 286 of file QualityTest.cc.
                                                                            :
       m_type(qtype),
       m_name(qname),
       m_description("") {
       /* nop */
     }
dqm4hep::core::QualityTest::~QualityTest () virtual
Destructor.
Definition at line 295 of file QualityTest.cc.
{
       /* nop */
     }
Member Function Documentation
float dqm4hep::core::QualityTest::defaultErrorLimit () static
Get the default error limit.
Definition at line 421 of file QualityTest.cc.
References m_defaultErrorLimit.
{
       return m_defaultErrorLimit;
     }
float dqm4hep::core::QualityTest::defaultWarningLimit () static
Get the default warning limit.
Definition at line 415 of file QualityTest.cc.
References m_defaultWarningLimit.
{
       return m_defaultWarningLimit;
     }
const std::string & dqm4hep::core::QualityTest::description () const
Get the quality test description.
Definition at line 313 of file QualityTest.cc.
References m_description.
Referenced by fillBasicInfo().
{
       return m_description;
     }
bool dqm4hep::core::QualityTest::enoughStatistics (MonitorElement * monitorElement) const inline virtual
Whether the monitor element has enough statistics to perform the qtest.
Parameters
monitorElement the monitor element to check
Definition at line 290 of file QualityTest.h.
Referenced by run().
{
       return true;
     }
float dqm4hep::core::QualityTest::errorLimit () const
Get the error limit.
Definition at line 409 of file QualityTest.cc.
References m_errorLimit.
Referenced by dqm4hep::core::ExactRefCompareTest::doGraph1DTest(), dqm4hep::core::ExactRefCompareTest::doGraph2DTest(), dqm4hep::core::ExactRefCompareTest::doHistogramTest(), and dqm4hep::core::FitParamInRangeTest::performRangeTest().
{
       return m_errorLimit;
     }
void dqm4hep::core::QualityTest::fillBasicInfo (MonitorElement * monitorElement, QualityTestReport & report) const protected
Fill basic info in the qtest report.
Must be called at start of qtest run
Definition at line 427 of file QualityTest.cc.
References description(), dqm4hep::core::QualityTestReport::m_extraInfos, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_monitorElementName, dqm4hep::core::QualityTestReport::m_monitorElementPath, dqm4hep::core::QualityTestReport::m_monitorElementType, dqm4hep::core::QualityTestReport::m_quality, dqm4hep::core::QualityTestReport::m_qualityFlag, dqm4hep::core::QualityTestReport::m_qualityTestDescription, dqm4hep::core::QualityTestReport::m_qualityTestName, dqm4hep::core::QualityTestReport::m_qualityTestType, dqm4hep::core::MonitorElement::name(), name(), dqm4hep::core::MonitorElement::path(), dqm4hep::core::MonitorElement::type(), type(), and dqm4hep::core::UNDEFINED.
Referenced by run().
{
       report.m_qualityTestName = this->name();
       report.m_qualityTestType = this->type();
       report.m_qualityTestDescription = this->description();
       report.m_monitorElementType = monitorElement ? monitorElement->type() : "";
       report.m_monitorElementName = monitorElement ? monitorElement->name() : "";
       report.m_monitorElementPath = monitorElement ? monitorElement->path() : "";
       report.m_quality = 0.f;
       report.m_message = "";
       report.m_qualityFlag = UNDEFINED;
       report.m_extraInfos.clear();
     }
StatusCode dqm4hep::core::QualityTest::init () inline virtual
Initialize the quality test.
Definition at line 284 of file QualityTest.h.
{
       return STATUS_CODE_SUCCESS;
     }
const std::string & dqm4hep::core::QualityTest::name () const
Get the quality test name (unique identifier)
Definition at line 307 of file QualityTest.cc.
References m_name.
Referenced by fillBasicInfo(), and dqm4hep::core::PropertyWithinExpectedTest::userRun().
{
       return m_name;
     }
virtual StatusCode dqm4hep::core::QualityTest::readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) pure virtual
Read the settings from the xml handle.
Implemented in dqm4hep::core::FitParamInRangeTest, dqm4hep::core::ExactRefCompareTest, dqm4hep::core::Chi2Test, dqm4hep::core::KolmogorovTest, and dqm4hep::core::PropertyWithinExpectedTest.
void dqm4hep::core::QualityTest::run (MonitorElement * monitorElement, QualityTestReport & report)
Perform the quality test result and fill the quality test report.
Definition at line 319 of file QualityTest.cc.
References enoughStatistics(), dqm4hep::core::ERROR, fillBasicInfo(), dqm4hep::core::INSUFFICENT_STAT, dqm4hep::core::INVALID, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, dqm4hep::core::QualityTestReport::m_qualityFlag, dqm4hep::core::MonitorElement::object(), dqm4hep::core::SUCCESS, dqm4hep::core::StatusCodeException::toString(), dqm4hep::core::typeToString(), userRun(), dqm4hep::core::WARNING, and warningLimit().
{
       this->fillBasicInfo(monitorElement, report);
       if (nullptr == monitorElement) {
         report.m_message = "Couldn't run quality test: monitor element pointer is nullptr";
         report.m_quality = 0.f;
         report.m_qualityFlag = INVALID;
         return;
       }
       if (nullptr == monitorElement->object()) {
         report.m_message = "Couldn't run quality test: ROOT monitor object is nullptr";
         report.m_quality = 0.f;
         report.m_qualityFlag = INVALID;
         return;
       }
       if(!this->enoughStatistics(monitorElement)) {
         report.m_message = "Couldn't run quality test: Not enough statistics !";
         report.m_quality = 0.f;
         report.m_qualityFlag = INSUFFICENT_STAT;
         return;
       }
       try {
         this->userRun(monitorElement, report);
         if(report.m_quality >= 0.f && report.m_quality < this->errorLimit()) {
           report.m_qualityFlag = ERROR;
         }
         else if(report.m_quality >= this->errorLimit() && report.m_quality < this->warningLimit()) {
           report.m_qualityFlag = WARNING;
         }
         else if(report.m_quality >= this->warningLimit() && report.m_quality <= 1.f) {
           report.m_qualityFlag = SUCCESS;
         }
         else {
           const std::string message("Quality value (" + typeToString(report.m_quality) + ") is out range !");
           if (!report.m_message.empty())
             report.m_message += " " + message;
           else
             report.m_message = message;
           throw StatusCodeException(STATUS_CODE_OUT_OF_RANGE);
         }
       } catch (StatusCodeException &exception) {
         const std::string message("Caught StatusCodeException while run QTest: " + exception.toString());
         if (!report.m_message.empty())
           report.m_message += " " + message;
         else
           report.m_message = message;
         report.m_quality = 0.f;
         report.m_qualityFlag = INVALID;
       } catch (...) {
         const std::string message("Caught unknown exception while run QTest");
         if (!report.m_message.empty())
           report.m_message += " " + message;
         else
           report.m_message = message;
         report.m_quality = 0.f;
         report.m_qualityFlag = INVALID;
       }
     }
void dqm4hep::core::QualityTest::setLimits (float warning, float error)
Set the warning and error limits on quality test result.
The limits must be ordered as 0 < error < warning < 1, else throws an exception
Parameters
warning the warning limit
error the error limit
Definition at line 390 of file QualityTest.cc.
References dqm_error, m_errorLimit, and m_warningLimit.
{
       if (warning < 0.f || error > 1.f || warning < error) {
         dqm_error("QualityTest::setLimits: Wrong limits provided (warning = {0}, error = {1})!", warning, error);
         throw StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
       }
       m_warningLimit = warning;
       m_errorLimit = error;
     }
const std::string & dqm4hep::core::QualityTest::type () const
Get the quality test type.
Definition at line 301 of file QualityTest.cc.
References m_type.
Referenced by fillBasicInfo().
{
       return m_type;
     }
virtual void dqm4hep::core::QualityTest::userRun (MonitorElement * monitorElement, QualityTestReport & report) protected pure virtual
Runs a quality test on the given monitor element and return a quality estimate.
Implemented in dqm4hep::core::FitParamInRangeTest, dqm4hep::core::ExactRefCompareTest, dqm4hep::core::Chi2Test, dqm4hep::core::KolmogorovTest, and dqm4hep::core::PropertyWithinExpectedTest.
Referenced by run().
float dqm4hep::core::QualityTest::warningLimit () const
Get the warning limit.
Definition at line 403 of file QualityTest.cc.
References m_warningLimit.
Referenced by dqm4hep::core::FitParamInRangeTest::performRangeTest(), and run().
{
       return m_warningLimit;
     }
Member Data Documentation
float dqm4hep::core::QualityTest::m_defaultErrorLimit = 0.5 static protected
Definition at line 262 of file QualityTest.h.
Referenced by defaultErrorLimit().
float dqm4hep::core::QualityTest::m_defaultWarningLimit = 0.8 static protected
Definition at line 261 of file QualityTest.h.
Referenced by defaultWarningLimit().
std::string dqm4hep::core::QualityTest::m_description = {""} protected
Quality test description.
Definition at line 260 of file QualityTest.h.
Referenced by dqm4hep::core::Chi2Test::Chi2Test(), description(), dqm4hep::core::ExactRefCompareTest::ExactRefCompareTest(), dqm4hep::core::FitParamInRangeTest::FitParamInRangeTest(), dqm4hep::core::KolmogorovTest::KolmogorovTest(), and dqm4hep::core::PropertyWithinExpectedTest::PropertyWithinExpectedTest().
float dqm4hep::core::QualityTest::m_errorLimit = {m_defaultErrorLimit} private
The quality test error threshold.
Definition at line 257 of file QualityTest.h.
Referenced by errorLimit(), and setLimits().
std::string dqm4hep::core::QualityTest::m_name = {""} private
Quality test name.
Definition at line 255 of file QualityTest.h.
Referenced by name().
std::string dqm4hep::core::QualityTest::m_type = {""} private
Quality test type (usually class name)
Definition at line 254 of file QualityTest.h.
Referenced by type().
float dqm4hep::core::QualityTest::m_warningLimit = {m_defaultWarningLimit} private
The quality test warning threshold.
Definition at line 256 of file QualityTest.h.
Referenced by setLimits(), and warningLimit().
The documentation for this class was generated from the following files:
QualityTest.h
QualityTest.cc