DQM4hep: dqm4hep::core::TiXmlDocument Class Reference
dqm4hep::core::TiXmlDocument Class Reference
Always the top level node.
#include <tinyxml.h>
Public Member Functions
TiXmlDocument ()
Create an empty document, that has no name.
TiXmlDocument (const char *documentName)
Create a document with a name. The name of the document is also the filename of the xml.
TiXmlDocument (const std::string &documentName)
Constructor.
TiXmlDocument (const TiXmlDocument &copy)
TiXmlDocument & operator= (const TiXmlDocument &copy)
~TiXmlDocument () override=default
bool LoadFile (TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the current document value.
bool SaveFile () const
Save a file using the current document value. Returns true if successful.
bool LoadFile (const char *_filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
bool SaveFile (const char *filename) const
Save a file using the given filename. Returns true if successful.
bool LoadFile (FILE *, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given FILE*.
bool SaveFile (FILE *) const
Save a file using the given FILE*. Returns true if successful.
bool LoadFile (const std::string &filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool SaveFile (const std::string &filename) const
< STL std::string version.
const char * Parse (const char *p, TiXmlParsingData *prevData=nullptr, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING) override
Parse the given null terminated block of xml data.
const TiXmlElement * RootElement () const
Get the root element – the only top level element – of the document.
TiXmlElement * RootElement ()
bool Error () const
If an error occurs, Error will be set to true.
const char * ErrorDesc () const
Contains a textual (english) description of the error if one occurs.
int ErrorId () const
Generally, you probably want the error string (ErrorDesc()).
int ErrorRow () const
Returns the location (if known) of the error.
int ErrorCol () const
The column where the error occured. See ErrorRow()
void SetTabSize (int _tabsize)
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column.
int TabSize () const
void ClearError ()
If you have handled the error, it can be reset with this call.
void Print () const
Write the document to standard out using formatted printing ("pretty print").
void Print (FILE *cfile, int depth=0) const override
Print this Document to a FILE stream.
void SetError (int err, const char *pError, TiXmlParsingData *data, TiXmlEncoding encoding)
const TiXmlDocument * ToDocument () const override
Cast to a more defined type. Will return null not of the requested type.
TiXmlDocument * ToDocument () override
Cast to a more defined type. Will return null not of the requested type.
bool Accept (TiXmlVisitor *visitor) const override
Walk the XML tree visiting this node and all of its children.
Public Member Functions inherited from dqm4hep::core::TiXmlNode
~TiXmlNode () override
const char * Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
const std::string & ValueStr () const
Return Value() as a std::string.
const TIXML_STRING & ValueTStr () const
void SetValue (const char *_value)
Changes the value of the node.
void SetValue (const std::string &_value)
STL std::string form.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *_value) const
The first child of this node with the matching 'value'.
TiXmlNode * FirstChild (const char *_value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *_value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * FirstChild (const std::string &_value) const
STL std::string form.
TiXmlNode * FirstChild (const std::string &_value)
STL std::string form.
const TiXmlNode * LastChild (const std::string &_value) const
STL std::string form.
TiXmlNode * LastChild (const std::string &_value)
STL std::string form.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
An alternate way to walk the children of a node.
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *val, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous) const
STL std::string form.
TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous)
STL std::string form.
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * LinkEndChild (TiXmlNode *node)
Add a new node related to this.
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
Replace a child of this node.
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * PreviousSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * PreviousSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * NextSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * NextSiblingElement (const std::string &_value) const
STL std::string form.
TiXmlElement * NextSiblingElement (const std::string &_value)
STL std::string form.
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
const TiXmlElement * FirstChildElement (const std::string &_value) const
STL std::string form.
TiXmlElement * FirstChildElement (const std::string &_value)
STL std::string form.
int Type () const
Query the type (as an enumerated value, above) of this node.
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
Public Member Functions inherited from dqm4hep::core::TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()=default
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Protected Member Functions
TiXmlNode * Clone () const override
Create an exact duplicate of this node and return it.
void StreamIn (std::istream *in, TIXML_STRING *tag) override
Protected Member Functions inherited from dqm4hep::core::TiXmlNode
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *p, TiXmlEncoding encoding)
Private Member Functions
void CopyTo (TiXmlDocument *target) const
Private Attributes
bool error = {false}
int errorId = {-1}
TIXML_STRING errorDesc = {""}
int tabsize = {4}
TiXmlCursor errorLocation = {}
bool useMicrosoftBOM = false
Additional Inherited Members
Public Types inherited from dqm4hep::core::TiXmlNode
enum NodeType {
TINYXML_DOCUMENT, TINYXML_ELEMENT, TINYXML_COMMENT, TINYXML_UNKNOWN,
TINYXML_TEXT, TINYXML_DECLARATION, TINYXML_TYPECOUNT
}
The types of XML nodes supported by TinyXml.
Public Types inherited from dqm4hep::core::TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_PARSING_ELEMENT,
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES, TIXML_ERROR_PARSING_EMPTY,
TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT, TIXML_ERROR_PARSING_DECLARATION,
TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA, TIXML_ERROR_DOCUMENT_TOP_ONLY,
TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from dqm4hep::core::TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *outString)
Expands entities in a string.
Static Public Attributes inherited from dqm4hep::core::TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from dqm4hep::core::TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *p, TIXML_STRING *text, bool trimWhiteSpace, const char *endTag, bool caseInsensitive, TiXmlEncoding encoding)
static const char * GetEntity (const char *p, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *tag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from dqm4hep::core::TiXmlNode
TiXmlNode * parent = {nullptr}
NodeType type = {TINYXML_UNKNOWN}
TiXmlNode * firstChild = {nullptr}
TiXmlNode * lastChild = {nullptr}
TIXML_STRING value = {""}
TiXmlNode * prev = {nullptr}
TiXmlNode * next = {nullptr}
Protected Attributes inherited from dqm4hep::core::TiXmlBase
TiXmlCursor location = {}
void * userData = {nullptr}
Field containing a generic user pointer.
Static Protected Attributes inherited from dqm4hep::core::TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
Always the top level node.
A document binds together all the XML pieces. It can be saved, loaded, and printed to the screen. The 'value' of a document node is the xml file name.
Definition at line 1533 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::core::TiXmlDocument::TiXmlDocument ()
Create an empty document, that has no name.
Definition at line 705 of file tinyxml.cc.
References ClearError(), tabsize, and useMicrosoftBOM.
Referenced by Clone().
                                  : TiXmlNode(TiXmlNode::TINYXML_DOCUMENT) {
       tabsize = 4;
       useMicrosoftBOM = false;
       ClearError();
     }
dqm4hep::core::TiXmlDocument::TiXmlDocument (const char * documentName)
Create a document with a name. The name of the document is also the filename of the xml.
Definition at line 711 of file tinyxml.cc.
References ClearError(), tabsize, useMicrosoftBOM, and dqm4hep::core::TiXmlNode::value.
                                                          : TiXmlNode(TiXmlNode::TINYXML_DOCUMENT) {
       tabsize = 4;
       useMicrosoftBOM = false;
       value = documentName;
       ClearError();
     }
dqm4hep::core::TiXmlDocument::TiXmlDocument (const std::string & documentName)
Constructor.
dqm4hep::core::TiXmlDocument::TiXmlDocument (const TiXmlDocument & copy)
Definition at line 727 of file tinyxml.cc.
References CopyTo().
                                                           : TiXmlNode(TiXmlNode::TINYXML_DOCUMENT) {
       copy.CopyTo(this);
     }
dqm4hep::core::TiXmlDocument::~TiXmlDocument () override default
Member Function Documentation
bool dqm4hep::core::TiXmlDocument::Accept (TiXmlVisitor * visitor) const override virtual
Walk the XML tree visiting this node and all of its children.
Implements dqm4hep::core::TiXmlNode.
Definition at line 915 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChild(), dqm4hep::core::TiXmlNode::NextSibling(), dqm4hep::core::TiXmlVisitor::VisitEnter(), and dqm4hep::core::TiXmlVisitor::VisitExit().
{
       if (visitor->VisitEnter(*this)) {
         for (const TiXmlNode *node = FirstChild(); node != nullptr; node = node->NextSibling()) {
           if (!node->Accept(visitor))
             break;
         }
       }
       return visitor->VisitExit(*this);
     }
void dqm4hep::core::TiXmlDocument::ClearError () inline
If you have handled the error, it can be reset with this call.
The error state is automatically cleared if you Parse a new XML block.
Definition at line 1670 of file tinyxml.h.
References dqm4hep::core::TiXmlCursor::col, error, errorDesc, errorId, errorLocation, and dqm4hep::core::TiXmlCursor::row.
Referenced by Parse(), and TiXmlDocument().
{
         error = false;
         errorId = 0;
         errorDesc = "";
         errorLocation.row = errorLocation.col = 0;
         // errorLocation.last = 0;
       }
TiXmlNode * dqm4hep::core::TiXmlDocument::Clone () const override protected virtual
Create an exact duplicate of this node and return it.
The memory must be deleted by the caller.
Implements dqm4hep::core::TiXmlNode.
Definition at line 898 of file tinyxml.cc.
References CopyTo(), and TiXmlDocument().
{
       auto clone = new TiXmlDocument();
       if (clone == nullptr)
         return nullptr;
       CopyTo(clone);
       return clone;
     }
void dqm4hep::core::TiXmlDocument::CopyTo (TiXmlDocument * target) const private
Definition at line 882 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::Clone(), dqm4hep::core::TiXmlNode::CopyTo(), error, errorDesc, errorId, errorLocation, dqm4hep::core::TiXmlNode::firstChild, dqm4hep::core::TiXmlNode::LinkEndChild(), dqm4hep::core::TiXmlNode::NextSibling(), tabsize, and useMicrosoftBOM.
Referenced by Clone(), operator=(), and TiXmlDocument().
{
       TiXmlNode::CopyTo(target);
       target->error = error;
       target->errorId = errorId;
       target->errorDesc = errorDesc;
       target->tabsize = tabsize;
       target->errorLocation = errorLocation;
       target->useMicrosoftBOM = useMicrosoftBOM;
       TiXmlNode *node = nullptr;
       for (node = firstChild; node != nullptr; node = node->NextSibling()) {
         target->LinkEndChild(node->Clone());
       }
     }
bool dqm4hep::core::TiXmlDocument::Error () const inline
If an error occurs, Error will be set to true.
Also,
The ErrorId() will contain the integer identifier of the error (not generally useful)
The ErrorDesc() method will return the name of the error. (very useful)
The ErrorRow() and ErrorCol() will return the location of the error (if known)
Definition at line 1605 of file tinyxml.h.
References error.
Referenced by LoadFile().
{
         return error;
       }
int dqm4hep::core::TiXmlDocument::ErrorCol () const inline
The column where the error occured. See ErrorRow()
Definition at line 1631 of file tinyxml.h.
References dqm4hep::core::TiXmlCursor::col, and errorLocation.
Referenced by dqm4hep::core::GenericEventXMLReader::open(), dqm4hep::core::XMLParser::parse(), and dqm4hep::core::XMLParser::resolveInclude().
const char* dqm4hep::core::TiXmlDocument::ErrorDesc () const inline
Contains a textual (english) description of the error if one occurs.
Definition at line 1610 of file tinyxml.h.
References errorDesc.
Referenced by dqm4hep::core::GenericEventXMLReader::open(), dqm4hep::core::XMLParser::parse(), and dqm4hep::core::XMLParser::resolveInclude().
{
         return errorDesc.c_str();
       }
int dqm4hep::core::TiXmlDocument::ErrorId () const inline
Generally, you probably want the error string (ErrorDesc()).
But if you prefer the ErrorId, this function will fetch it.
Definition at line 1617 of file tinyxml.h.
References errorId.
{
         return errorId;
       }
int dqm4hep::core::TiXmlDocument::ErrorRow () const inline
Returns the location (if known) of the error.
The first column is column 1, and the first row is row 1. A value of 0 means the row and column wasn't applicable (memory errors, for example, have no row/column) or the parser lost the error. (An error in the error reporting, in that case.)
See Also
SetTabSize, Row, Column
Definition at line 1628 of file tinyxml.h.
References errorLocation, and dqm4hep::core::TiXmlCursor::row.
Referenced by dqm4hep::core::GenericEventXMLReader::open(), dqm4hep::core::XMLParser::parse(), and dqm4hep::core::XMLParser::resolveInclude().
{
         return errorLocation.row + 1;
       }
bool dqm4hep::core::TiXmlDocument::LoadFile (TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the current document value.
Returns true if successful. Will delete any existing document data before loading.
Definition at line 737 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::Value().
Referenced by LoadFile(), dqm4hep::core::GenericEventXMLReader::open(), dqm4hep::core::XMLParser::parse(), and dqm4hep::core::XMLParser::resolveInclude().
{
       return LoadFile(Value(), encoding);
     }
bool dqm4hep::core::TiXmlDocument::LoadFile (const char * _filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
Definition at line 745 of file tinyxml.cc.
References LoadFile(), SetError(), dqm4hep::core::TIXML_ENCODING_UNKNOWN, dqm4hep::core::TiXmlBase::TIXML_ERROR_OPENING_FILE, TIXML_STRING, dqm4hep::core::TiXmlFOpen(), and dqm4hep::core::TiXmlNode::value.
{
       TIXML_STRING filename(_filename);
       value = filename;
       // reading in binary mode so that tinyxml can normalize the EOL
       FILE *file = TiXmlFOpen(value.c_str(), "rb");
       if (file != nullptr) {
         bool result = LoadFile(file, encoding);
         fclose(file);
         return result;
       }
       SetError(TIXML_ERROR_OPENING_FILE, nullptr, nullptr, TIXML_ENCODING_UNKNOWN);
       return false;
     }
bool dqm4hep::core::TiXmlDocument::LoadFile (FILE * file, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the given FILE*.
Returns true if successful. Note that this method doesn't stream - the entire object pointed at by the FILE* will be interpreted as an XML file. TinyXML doesn't stream in XML from the current file location. Streaming may be added in the future.
Definition at line 762 of file tinyxml.cc.
References dqm4hep::core::TiXmlCursor::Clear(), dqm4hep::core::TiXmlNode::Clear(), Error(), dqm4hep::core::TiXmlBase::location, Parse(), SetError(), dqm4hep::core::TIXML_ENCODING_UNKNOWN, dqm4hep::core::TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, and dqm4hep::core::TiXmlBase::TIXML_ERROR_OPENING_FILE.
{
       if (file == nullptr) {
         SetError(TIXML_ERROR_OPENING_FILE, nullptr, nullptr, TIXML_ENCODING_UNKNOWN);
         return false;
       }
       // Delete the existing data:
       Clear();
       location.Clear();
       // Get the file size, so we can pre-allocate the string. HUGE speed impact.
       long length = 0;
       fseek(file, 0, SEEK_END);
       length = ftell(file);
       fseek(file, 0, SEEK_SET);
       // Strange case, but good to handle up front.
       if (length <= 0) {
         SetError(TIXML_ERROR_DOCUMENT_EMPTY, nullptr, nullptr, TIXML_ENCODING_UNKNOWN);
         return false;
       }
       // Subtle bug here. TinyXml did use fgets. But from the XML spec:
       // 2.11 End-of-Line Handling
       // <snip>
       // <quote>
       // ...the XML processor MUST behave as if it normalized all line breaks in external
       // parsed entities (including the document entity) on input, before parsing, by translating
       // both the two-character sequence #xD #xA and any #xD that is not followed by #xA to
       // a single #xA character.
       // </quote>
       //
       // It is not clear fgets does that, and certainly isn't clear it works cross platform.
       // Generally, you expect fgets to translate from the convention of the OS to the c/unix
       // convention, and not work generally.
       /*
         while( fgets( buf, sizeof(buf), file ) )
         {
                 data += buf;
         }
        */
       auto buf = new char[length + 1];
       buf[0] = 0;
       if (fread(buf, length, 1, file) != 1) {
         delete[] buf;
         SetError(TIXML_ERROR_OPENING_FILE, nullptr, nullptr, TIXML_ENCODING_UNKNOWN);
         return false;
       }
       // Process the buffer in place to normalize new lines. (See comment above.)
       // Copies from the 'p' to 'q' pointer, where p can advance faster if
       // a newline-carriage return is hit.
       //
       // Wikipedia:
       // Systems based on ASCII or a compatible character set use either LF  (Line feed, '\n', 0x0A, 10 in decimal) or
       // CR (Carriage return, '\r', 0x0D, 13 in decimal) individually, or CR followed by LF (CR+LF, 0x0D 0x0A)...
       //    * LF:    Multics, Unix and Unix-like systems (GNU/Linux, AIX, Xenix, Mac OS X, FreeBSD, etc.),
       // BeOS, Amiga, RISC OS, and others
       //    * CR+LF: DEC RT-11 and most other early non-Unix, non-IBM OSes, CP/M, MP/M, DOS, OS/2, Microsoft
       // Windows, Symbian OS
       //    * CR:    Commodore 8-bit machines, Apple II family, Mac OS up to version 9 and OS-9
       const char *p = buf; // the read head
       char *q = buf;       // the write head
       const char CR = 0x0d;
       const char LF = 0x0a;
       buf[length] = 0;
       while (*p != 0) {
         assert(p < (buf + length));
         assert(q <= (buf + length));
         assert(q <= p);
         if (*p == CR) {
           *q++ = LF;
           p++;
           if (*p == LF) { // check for CR+LF (and skip LF)
             p++;
           }
         } else {
           *q++ = *p++;
         }
       }
       assert(q <= (buf + length));
       *q = 0;
       Parse(buf, nullptr, encoding);
       delete[] buf;
       return !Error();
     }
bool dqm4hep::core::TiXmlDocument::LoadFile (const std::string & filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING) inline
Parameters
encoding STL std::string version.
Definition at line 1571 of file tinyxml.h.
References LoadFile().
       {
         return LoadFile(filename.c_str(), encoding);
       }
TiXmlDocument & dqm4hep::core::TiXmlDocument::operator= (const TiXmlDocument & copy)
Definition at line 731 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::Clear(), and CopyTo().
{
       Clear();
       copy.CopyTo(this);
       return *this;
     }
const char * dqm4hep::core::TiXmlDocument::Parse (const char * p, TiXmlParsingData * prevData = nullptr, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING) override virtual
Parse the given null terminated block of xml data.
Passing in an encoding to this method (either TIXML_ENCODING_LEGACY or TIXML_ENCODING_UTF8 will force TinyXml to use that encoding, regardless of what TinyXml might otherwise try to detect.
Implements dqm4hep::core::TiXmlBase.
Definition at line 614 of file tinyxmlparser.cc.
References dqm4hep::core::TiXmlCursor::Clear(), ClearError(), dqm4hep::core::TiXmlCursor::col, dqm4hep::core::TiXmlParsingData::Cursor(), dqm4hep::core::TiXmlParsingData::cursor, dqm4hep::core::TiXmlDeclaration::Encoding(), dqm4hep::core::TiXmlNode::firstChild, dqm4hep::core::TiXmlNode::Identify(), dqm4hep::core::TiXmlNode::LinkEndChild(), dqm4hep::core::TiXmlBase::location, dqm4hep::core::TiXmlBase::Parse(), dqm4hep::core::TiXmlCursor::row, SetError(), dqm4hep::core::TiXmlBase::SkipWhiteSpace(), dqm4hep::core::TiXmlBase::StringEqual(), TabSize(), dqm4hep::core::TIXML_ENCODING_LEGACY, dqm4hep::core::TIXML_ENCODING_UNKNOWN, dqm4hep::core::TIXML_ENCODING_UTF8, dqm4hep::core::TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, dqm4hep::core::TIXML_UTF_LEAD_0, dqm4hep::core::TIXML_UTF_LEAD_1, dqm4hep::core::TIXML_UTF_LEAD_2, dqm4hep::core::TiXmlNode::ToDeclaration(), and useMicrosoftBOM.
Referenced by LoadFile().
{
       ClearError();
       // Parse away, at the document level. Since a document
       // contains nothing but other tags, most of what happens
       // here is skipping white space.
       if ((p == nullptr) || (*p == 0)) {
         SetError(TIXML_ERROR_DOCUMENT_EMPTY, nullptr, nullptr, TIXML_ENCODING_UNKNOWN);
         return nullptr;
       }
       // Note that, for a document, this needs to come
       // before the while space skip, so that parsing
       // starts from the pointer we are given.
       location.Clear();
       if (prevData != nullptr) {
         location.row = prevData->cursor.row;
         location.col = prevData->cursor.col;
       } else {
         location.row = 0;
         location.col = 0;
       }
       TiXmlParsingData data(p, TabSize(), location.row, location.col);
       location = data.Cursor();
       if (encoding == TIXML_ENCODING_UNKNOWN) {
         // Check for the Microsoft UTF-8 lead bytes.
         const unsigned char *pU = (const unsigned char *)p;
         if ((*(pU + 0) != 0u) && *(pU + 0) == TIXML_UTF_LEAD_0 && (*(pU + 1) != 0u) && *(pU + 1) == TIXML_UTF_LEAD_1 &&
             (*(pU + 2) != 0u) && *(pU + 2) == TIXML_UTF_LEAD_2) {
           encoding = TIXML_ENCODING_UTF8;
           useMicrosoftBOM = true;
         }
       }
       p = SkipWhiteSpace(p, encoding);
       if (p == nullptr) {
         SetError(TIXML_ERROR_DOCUMENT_EMPTY, nullptr, nullptr, TIXML_ENCODING_UNKNOWN);
         return nullptr;
       }
       while ((p != nullptr) && (*p != 0)) {
         TiXmlNode *node = Identify(p, encoding);
         if (node != nullptr) {
           p = node->Parse(p, &data, encoding);
           LinkEndChild(node);
         } else {
           break;
         }
         // Did we get encoding info?
         if (encoding == TIXML_ENCODING_UNKNOWN && (node->ToDeclaration() != nullptr)) {
           TiXmlDeclaration *dec = node->ToDeclaration();
           const char *enc = dec->Encoding();
           assert(enc);
           if (*enc == 0)
             encoding = TIXML_ENCODING_UTF8;
           else if (StringEqual(enc, "UTF-8", true, TIXML_ENCODING_UNKNOWN))
             encoding = TIXML_ENCODING_UTF8;
           else if (StringEqual(enc, "UTF8", true, TIXML_ENCODING_UNKNOWN))
             encoding = TIXML_ENCODING_UTF8; // incorrect, but be nice
           else
             encoding = TIXML_ENCODING_LEGACY;
         }
         p = SkipWhiteSpace(p, encoding);
       }
       // Was this empty?
       if (firstChild == nullptr) {
         SetError(TIXML_ERROR_DOCUMENT_EMPTY, nullptr, nullptr, encoding);
         return nullptr;
       }
       // All is well.
       return p;
     }
void dqm4hep::core::TiXmlDocument::Print () const inline
Write the document to standard out using formatted printing ("pretty print").
Definition at line 1679 of file tinyxml.h.
Referenced by SaveFile().
{
         Print(stdout, 0);
       }
void dqm4hep::core::TiXmlDocument::Print (FILE * cfile, int depth = 0) const override virtual
Print this Document to a FILE stream.
Implements dqm4hep::core::TiXmlBase.
Definition at line 907 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::FirstChild(), and dqm4hep::core::TiXmlNode::NextSibling().
{
       assert(cfile);
       for (const TiXmlNode *node = FirstChild(); node != nullptr; node = node->NextSibling()) {
         node->Print(cfile, depth);
         fprintf(cfile, "\n");
       }
     }
const TiXmlElement* dqm4hep::core::TiXmlDocument::RootElement () const inline
Get the root element – the only top level element – of the document.
In well formed XML, there should only be one. TinyXml is tolerant of multiple elements at the document level.
Definition at line 1593 of file tinyxml.h.
References dqm4hep::core::TiXmlNode::FirstChildElement().
Referenced by dqm4hep::core::GenericEventXMLReader::open(), dqm4hep::core::XMLParser::readConstants(), dqm4hep::core::XMLParser::readDatabases(), dqm4hep::core::XMLParser::replaceAllConstants(), dqm4hep::core::XMLParser::resolveForLoops(), dqm4hep::core::XMLParser::resolveIncludes(), and dqm4hep::core::GenericEventXMLReader::runInfo().
{
         return FirstChildElement();
       }
TiXmlElement* dqm4hep::core::TiXmlDocument::RootElement () inline
Definition at line 1596 of file tinyxml.h.
References dqm4hep::core::TiXmlNode::FirstChildElement().
{
         return FirstChildElement();
       }
bool dqm4hep::core::TiXmlDocument::SaveFile () const
Save a file using the current document value. Returns true if successful.
Definition at line 741 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::Value().
Referenced by SaveFile().
{
       return SaveFile(Value());
     }
bool dqm4hep::core::TiXmlDocument::SaveFile (const char * filename) const
Save a file using the given filename. Returns true if successful.
Definition at line 857 of file tinyxml.cc.
References SaveFile(), and dqm4hep::core::TiXmlFOpen().
{
       // The old c stuff lives on...
       FILE *fp = TiXmlFOpen(filename, "w");
       if (fp != nullptr) {
         bool result = SaveFile(fp);
         fclose(fp);
         return result;
       }
       return false;
     }
bool dqm4hep::core::TiXmlDocument::SaveFile (FILE * fp) const
Save a file using the given FILE*. Returns true if successful.
Definition at line 868 of file tinyxml.cc.
References Print(), dqm4hep::core::TIXML_UTF_LEAD_0, dqm4hep::core::TIXML_UTF_LEAD_1, dqm4hep::core::TIXML_UTF_LEAD_2, and useMicrosoftBOM.
{
       if (useMicrosoftBOM) {
         const unsigned char TIXML_UTF_LEAD_0 = 0xefU;
         const unsigned char TIXML_UTF_LEAD_1 = 0xbbU;
         const unsigned char TIXML_UTF_LEAD_2 = 0xbfU;
         fputc(TIXML_UTF_LEAD_0, fp);
         fputc(TIXML_UTF_LEAD_1, fp);
         fputc(TIXML_UTF_LEAD_2, fp);
       }
       Print(fp, 0);
       return (ferror(fp) == 0);
     }
bool dqm4hep::core::TiXmlDocument::SaveFile (const std::string & filename) const inline
< STL std::string version.
Definition at line 1576 of file tinyxml.h.
References SaveFile().
       {
         return SaveFile(filename.c_str());
       }
void dqm4hep::core::TiXmlDocument::SetError (int err, const char * pError, TiXmlParsingData * data, TiXmlEncoding encoding)
Definition at line 693 of file tinyxmlparser.cc.
References dqm4hep::core::TiXmlCursor::Clear(), dqm4hep::core::TiXmlParsingData::Cursor(), error, errorDesc, errorId, errorLocation, dqm4hep::core::TiXmlBase::errorString, dqm4hep::core::TiXmlParsingData::Stamp(), and dqm4hep::core::TiXmlBase::TIXML_ERROR_STRING_COUNT.
Referenced by dqm4hep::core::TiXmlNode::InsertAfterChild(), dqm4hep::core::TiXmlNode::InsertBeforeChild(), dqm4hep::core::TiXmlNode::InsertEndChild(), dqm4hep::core::TiXmlNode::LinkEndChild(), LoadFile(), dqm4hep::core::TiXmlAttribute::Parse(), dqm4hep::core::TiXmlElement::Parse(), dqm4hep::core::TiXmlComment::Parse(), dqm4hep::core::TiXmlText::Parse(), dqm4hep::core::TiXmlDeclaration::Parse(), dqm4hep::core::TiXmlUnknown::Parse(), Parse(), dqm4hep::core::TiXmlElement::ReadValue(), and dqm4hep::core::TiXmlNode::ReplaceChild().
{
       // The first error in a chain is more accurate - don't set again!
       if (error)
         return;
       assert(err > 0 && err < TIXML_ERROR_STRING_COUNT);
       error = true;
       errorId = err;
       errorDesc = errorString[errorId];
       errorLocation.Clear();
       if ((pError != nullptr) && (data != nullptr)) {
         data->Stamp(pError, encoding);
         errorLocation = data->Cursor();
       }
     }
void dqm4hep::core::TiXmlDocument::SetTabSize (int _tabsize) inline
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column.
It does not change the output or input in any way.
By calling this method, with a tab size greater than 0, the row and column of each node and attribute is stored when the file is loaded. Very useful for tracking the DOM back in to the source file.
The tab size is required for calculating the location of nodes. If not set, the default of 4 is used. The tabsize is set per document. Setting the tabsize to 0 disables row/column tracking.
Note that row and column tracking is not supported when using operator>>.
The tab size needs to be enabled before the parse or load. Correct usage:
      TiXmlDocument doc;
      doc.SetTabSize( 8 );
      doc.Load( "myfile.xml" );
See Also
Row, Column
Definition at line 1659 of file tinyxml.h.
References tabsize.
{
         tabsize = _tabsize;
       }
void dqm4hep::core::TiXmlDocument::StreamIn (std::istream * in, TIXML_STRING * tag) override protected virtual
Implements dqm4hep::core::TiXmlNode.
int dqm4hep::core::TiXmlDocument::TabSize () const inline
Definition at line 1663 of file tinyxml.h.
References tabsize.
Referenced by Parse().
{
         return tabsize;
       }
const TiXmlDocument* dqm4hep::core::TiXmlDocument::ToDocument () const inline override virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::core::TiXmlNode.
Definition at line 1694 of file tinyxml.h.
TiXmlDocument* dqm4hep::core::TiXmlDocument::ToDocument () inline override virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::core::TiXmlNode.
Definition at line 1697 of file tinyxml.h.
Member Data Documentation
bool dqm4hep::core::TiXmlDocument::error = {false} private
Definition at line 1715 of file tinyxml.h.
Referenced by ClearError(), CopyTo(), Error(), and SetError().
TIXML_STRING dqm4hep::core::TiXmlDocument::errorDesc = {""} private
Definition at line 1717 of file tinyxml.h.
Referenced by ClearError(), CopyTo(), ErrorDesc(), and SetError().
int dqm4hep::core::TiXmlDocument::errorId = {-1} private
Definition at line 1716 of file tinyxml.h.
Referenced by ClearError(), CopyTo(), ErrorId(), and SetError().
TiXmlCursor dqm4hep::core::TiXmlDocument::errorLocation = {} private
Definition at line 1719 of file tinyxml.h.
Referenced by ClearError(), CopyTo(), ErrorCol(), ErrorRow(), and SetError().
int dqm4hep::core::TiXmlDocument::tabsize = {4} private
Definition at line 1718 of file tinyxml.h.
Referenced by CopyTo(), SetTabSize(), TabSize(), and TiXmlDocument().
bool dqm4hep::core::TiXmlDocument::useMicrosoftBOM = false private
Definition at line 1720 of file tinyxml.h.
Referenced by CopyTo(), Parse(), SaveFile(), and TiXmlDocument().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc