DQM4hep: dqm4hep::net::RequestHandler Class Reference
dqm4hep::net::RequestHandler Class Reference
#include <RequestHandler.h>
Classes
class Rpc
Rpc class.
Public Types
typedef core::Signal< const
Buffer &, Buffer & > RequestSignal
Public Member Functions
const std::string & name () const
Get the request name.
Server * server () const
Get the server in which the request handler is declared.
Private Member Functions
template<typename Controller >
RequestHandler (Server *pServer, const std::string &name, Controller *pController, void(Controller::*function)(const Buffer &request, Buffer &response))
Constructor.
RequestHandler (const RequestHandler &)=delete
RequestHandler & operator= (const RequestHandler &)=delete
~RequestHandler ()
Destructor.
void startHandlingRequest ()
Create the actual request handler connection.
void stopHandlingRequest ()
Remove the actual request handler connection.
bool isHandlingRequest () const
Whether the request handler is connected.
RequestSignal & onRequest ()
[onRequest description]
void handleRequest (const Buffer &request, Buffer &response)
[handleRequest description]
Private Attributes
std::string m_name = {""}
The request handler name.
Server * m_pServer = {nullptr}
The server in which the request handler is declared.
RequestSignal m_requestSignal = {}
Rpc * m_pRpc = {nullptr}
Friends
class Server
class Rpc
Detailed Description
Definition at line 32 of file RequestHandler.h.
Member Typedef Documentation
typedef core::Signal<const Buffer &, Buffer &> dqm4hep::net::RequestHandler::RequestSignal
Definition at line 36 of file RequestHandler.h.
Constructor & Destructor Documentation
template<typename Controller > dqm4hep::net::RequestHandler::RequestHandler (Server * pServer, const std::string & name, Controller * pController, void(Controller::*)(const Buffer &request, Buffer &response) function) inline private
Constructor.
Parameters
pServer the server managing the request handler
name the request handler name
Definition at line 133 of file RequestHandler.h.
References dqm4hep::core::Signal< Args >::connect(), and m_requestSignal.
         : m_name(rname), m_pServer(pServer), m_pRpc(nullptr) {
       m_requestSignal.connect(pController, function);
     }
dqm4hep::net::RequestHandler::RequestHandler (const RequestHandler &) private delete
dqm4hep::net::RequestHandler::~RequestHandler () private
Destructor.
Definition at line 17 of file RequestHandler.cc.
References stopHandlingRequest().
{
       this->stopHandlingRequest();
     }
Member Function Documentation
void dqm4hep::net::RequestHandler::handleRequest (const Buffer & request, Buffer & response) private
[handleRequest description]
Parameters
request [description]
response [description]
Definition at line 64 of file RequestHandler.cc.
References dqm4hep::core::Signal< Args >::emit(), and m_requestSignal.
{
       m_requestSignal.emit(request, response);
     }
bool dqm4hep::net::RequestHandler::isHandlingRequest () const private
Whether the request handler is connected.
Definition at line 52 of file RequestHandler.cc.
References m_pRpc.
Referenced by dqm4hep::net::Server::start(), startHandlingRequest(), dqm4hep::net::Server::startRequestHandler(), dqm4hep::net::Server::stop(), stopHandlingRequest(), and dqm4hep::net::Server::stopRequestHandler().
{
       return (m_pRpc != nullptr);
     }
const std::string & dqm4hep::net::RequestHandler::name () const
Get the request name.
Definition at line 23 of file RequestHandler.cc.
References m_name.
{
       return m_name;
     }
RequestHandler::RequestSignal & dqm4hep::net::RequestHandler::onRequest () private
[onRequest description]
Returns
[description]
Definition at line 58 of file RequestHandler.cc.
References m_requestSignal.
{
       return m_requestSignal;
     }
RequestHandler& dqm4hep::net::RequestHandler::operator= (const RequestHandler &) private delete
Server * dqm4hep::net::RequestHandler::server () const
Get the server in which the request handler is declared.
Definition at line 29 of file RequestHandler.cc.
References m_pServer.
{
       return m_pServer;
     }
void dqm4hep::net::RequestHandler::startHandlingRequest () private
Create the actual request handler connection.
Definition at line 35 of file RequestHandler.cc.
References isHandlingRequest(), m_pRpc, and Rpc.
Referenced by dqm4hep::net::Server::createRequestHandler(), dqm4hep::net::Server::start(), and dqm4hep::net::Server::startRequestHandler().
{
       if (!this->isHandlingRequest()) {
         m_pRpc = new Rpc(this);
       }
     }
void dqm4hep::net::RequestHandler::stopHandlingRequest () private
Remove the actual request handler connection.
Definition at line 43 of file RequestHandler.cc.
References isHandlingRequest(), and m_pRpc.
Referenced by dqm4hep::net::Server::stop(), dqm4hep::net::Server::stopRequestHandler(), and ~RequestHandler().
{
       if (this->isHandlingRequest()) {
         delete m_pRpc;
         m_pRpc = nullptr;
       }
     }
Friends And Related Function Documentation
friend class Rpc friend
Definition at line 111 of file RequestHandler.h.
Referenced by startHandlingRequest().
friend class Server friend
Definition at line 33 of file RequestHandler.h.
Member Data Documentation
std::string dqm4hep::net::RequestHandler::m_name = {""} private
The request handler name.
Definition at line 122 of file RequestHandler.h.
Referenced by name().
Rpc* dqm4hep::net::RequestHandler::m_pRpc = {nullptr} private
Definition at line 125 of file RequestHandler.h.
Referenced by isHandlingRequest(), startHandlingRequest(), and stopHandlingRequest().
Server* dqm4hep::net::RequestHandler::m_pServer = {nullptr} private
The server in which the request handler is declared.
Definition at line 123 of file RequestHandler.h.
Referenced by server().
RequestSignal dqm4hep::net::RequestHandler::m_requestSignal = {} private
Definition at line 124 of file RequestHandler.h.
Referenced by handleRequest(), onRequest(), and RequestHandler().
The documentation for this class was generated from the following files:
RequestHandler.h
RequestHandler.cc