DQM4hep: dqm4hep::core::EventBase< T > Class Template Reference
dqm4hep::core::EventBase< T > Class Template Reference
EventBase interface.
#include <Event.h>
Public Member Functions
EventBase ()
Constructor.
EventBase (const EventBase &)=delete
EventBase & operator= (const EventBase &)=delete
EventBase (T *pEvent)
Constructor with real event.
~EventBase () override
Destructor.
T * getEvent () const
Returns the real event implementation.
void setEvent (T *pEvent, bool owner=true)
Set the real event implementation.
bool isOwner () const
Whether the event wrapper owns the real event implementation.
void clear () override
The implementation of this method may delete the real event implementation if needed.
Public Member Functions inherited from dqm4hep::core::Event
virtual ~Event ()=default
Destructor.
void setType (EventType type)
Set the event type.
EventType getType () const
Get the event type.
void setSource (const std::string &sourceName)
Get the event source.
const std::string & getSource () const
Set the event source.
void setTimeStamp (const core::time::point &timeStamp)
Set the event time stamp.
const core::time::point & getTimeStamp () const
Get the event time stamp.
uint64_t getEventSize () const
Get the real event implementation size, as extracted after its deserialization (unit bytes)
void setEventNumber (uint32_t eventNumber)
Set the event number.
uint32_t getEventNumber () const
Get the event number.
void setRunNumber (uint32_t runNumber)
Set the run number.
uint32_t getRunNumber () const
Get the run number.
void setStreamerName (const std::string &streamer)
Set the streamer name.
const std::string & getStreamerName () const
Get the streamer name.
template<typename T >
T * getEvent () const
Returns the true event implementation.
template<typename T >
void setEvent (T *pEvent, bool owner=true)
Set the event.
Protected Attributes
T * m_pEvent = {nullptr}
The real event implementation.
bool m_isOwner = {true}
Whether the event wrapper owns the real event implementation.
Protected Attributes inherited from dqm4hep::core::Event
EventType m_type = {UNKNOWN_EVENT}
The event type.
std::string m_source = {""}
The event source.
core::time::point m_timeStamp = {}
The event time stamp.
uint64_t m_eventSize = {0}
The serialized event size (unit bytes)
uint32_t m_eventNumber = {0}
The event number.
uint32_t m_runNumber = {0}
The run number.
std::string m_streamerName = {""}
Additional Inherited Members
Static Public Member Functions inherited from dqm4hep::core::Event
template<typename T , typename... Args>
static EventPtr create (Args...args)
Create an event pointer wrapping an event of type T.
template<typename T >
static EventPtr create (T *event)
Create an event pointer wrapping an event of type T.
Protected Member Functions inherited from dqm4hep::core::Event
Event ()=default
Event (const Event &)=delete
Event & operator= (const Event &)=delete
void setEventSize (uint64_t eventSize)
Set the real event implementation size, as extracted after its serialization (unit bytes)
void writeBase (TBuffer &buffer) const
Write the base event information in the xdrstream device.
void readBase (TBuffer &buffer)
Read the base event information from the xdrstream device.
Detailed Description
template<typename T>
class dqm4hep::core::EventBase< T >
EventBase interface.
Definition at line 172 of file Event.h.
Constructor & Destructor Documentation
template<typename T > dqm4hep::core::EventBase< T >::EventBase () inline
Constructor.
Definition at line 314 of file Event.h.
                                    :
       Event() {
       /* nop */
     }
template<typename T> dqm4hep::core::EventBase< T >::EventBase (const EventBase< T > &) delete
template<typename T > dqm4hep::core::EventBase< T >::EventBase (T * pEvent) inline
Constructor with real event.
Definition at line 322 of file Event.h.
                                             :
       Event(),
       m_pEvent(pEvent) {
       /* nop */
     }
template<typename T > dqm4hep::core::EventBase< T >::~EventBase () inline override
Destructor.
Definition at line 331 of file Event.h.
{
       this->clear();
     }
Member Function Documentation
template<typename T > void dqm4hep::core::EventBase< T >::clear () inline override virtual
The implementation of this method may delete the real event implementation if needed.
ATTN : do not forget the check the event ownership using the isOwner() method
Reimplemented from dqm4hep::core::Event.
Definition at line 354 of file Event.h.
References dqm4hep::core::Event::clear().
Referenced by dqm4hep::core::Event::setEvent().
{
       Event::clear();
       if (nullptr != m_pEvent && this->isOwner())
         delete m_pEvent;
       m_pEvent = nullptr;
     }
template<typename T > T * dqm4hep::core::EventBase< T >::getEvent () const inline
Returns the real event implementation.
Definition at line 338 of file Event.h.
Referenced by dqm4hep::core::Event::getEvent().
{
       return m_pEvent;
     }
template<typename T > bool dqm4hep::core::EventBase< T >::isOwner () const inline
Whether the event wrapper owns the real event implementation.
Definition at line 366 of file Event.h.
{
       return m_isOwner;
     }
template<typename T> EventBase& dqm4hep::core::EventBase< T >::operator= (const EventBase< T > &) delete
template<typename T > void dqm4hep::core::EventBase< T >::setEvent (T * pEvent, bool owner = true) inline
Set the real event implementation.
Definition at line 345 of file Event.h.
Referenced by dqm4hep::core::Event::setEvent().
{
       this->clear();
       m_pEvent = pEvent;
       m_isOwner = owner;
     }
Member Data Documentation
template<typename T> bool dqm4hep::core::EventBase< T >::m_isOwner = {true} protected
Whether the event wrapper owns the real event implementation.
Definition at line 207 of file Event.h.
template<typename T> T* dqm4hep::core::EventBase< T >::m_pEvent = {nullptr} protected
The real event implementation.
Definition at line 206 of file Event.h.
The documentation for this class was generated from the following file:
Event.h