DQM4hep: dqm4hep::online::TestAnalysisModule Class Reference
dqm4hep::online::TestAnalysisModule Class Reference
Public Member Functions
TestAnalysisModule ()=default
~TestAnalysisModule ()=default
Public Member Functions inherited from dqm4hep::online::ModuleT< T >
ModuleT ()=default
Default constructor.
ModuleT (const ModuleT &)=delete
ModuleT & operator= (const ModuleT &)=delete
virtual ~ModuleT ()
Destructor.
virtual void process (T item)=0
Callback function to process an item.
Public Member Functions inherited from dqm4hep::online::Module
Module ()=default
Default constructor.
Module (const Module &)=delete
Module & operator= (const Module &)=delete
virtual ~Module ()
Destructor.
const std::string & name () const
Get the module name.
const std::string & detectorName () const
Get the detector name.
const core::Version & version () const
Get the module version.
Private Member Functions
void readSettings (const core::TiXmlHandle &handle)
Read the user settings from the xml handle.
void initModule ()
Initialize the module.
void startOfRun (core::Run &run)
Callback function on start of run.
void startOfCycle ()
Callback function on start of cycle.
void endOfCycle (const EOCCondition &condition)
Callback function on end of cycle The monitor elements are send to the collector after calling this function.
void endOfRun (const core::Run &run)
Callback function on end of run.
void endModule ()
Callback function before terminate.
void process (core::EventPtr event)
Private Attributes
OnlineElementPtr m_testGraph = {nullptr}
OnlineElementPtr m_testGraph2D = {nullptr}
OnlineElementPtr m_testHisto1D = {nullptr}
OnlineElementPtr m_testHisto2D = {nullptr}
OnlineElementPtr m_testScalarInt = {nullptr}
OnlineElementPtr m_testScalarFloat = {nullptr}
OnlineElementPtr m_testScalarShort = {nullptr}
OnlineElementPtr m_testScalarString = {nullptr}
Additional Inherited Members
Protected Member Functions inherited from dqm4hep::online::Module
void setDetectorName (const std::string &detector)
Set the detector name.
void setName (const std::string &module)
Set the module name.
void setVersion (unsigned int major, unsigned int minor=0, unsigned int patch=0)
Set the module version.
Detailed Description
Definition at line 23 of file TestAnalysisModule.cc.
Constructor & Destructor Documentation
dqm4hep::online::TestAnalysisModule::TestAnalysisModule () default
dqm4hep::online::TestAnalysisModule::~TestAnalysisModule () default
Member Function Documentation
void dqm4hep::online::TestAnalysisModule::endModule () private virtual
Callback function before terminate.
Implements dqm4hep::online::Module.
Definition at line 130 of file TestAnalysisModule.cc.
References dqm_info.
{
       dqm_info( "TestAnalysisModule::endModule");
     }
void dqm4hep::online::TestAnalysisModule::endOfCycle (const EOCCondition & condition) private virtual
Callback function on end of cycle The monitor elements are send to the collector after calling this function.
Parameters
condition the end of cycle conditions
Implements dqm4hep::online::Module.
Definition at line 118 of file TestAnalysisModule.cc.
References dqm_info, and dqm4hep::core::typeToString().
{
       dqm_info( "====> TestAnalysisModule::endOfCycle: {0}", core::typeToString(condition) );
     }
void dqm4hep::online::TestAnalysisModule::endOfRun (const core::Run & run) private virtual
Callback function on end of run.
User can get final run configuration from the run object
Parameters
run the run configuration
Implements dqm4hep::online::Module.
Definition at line 124 of file TestAnalysisModule.cc.
References dqm_info, and dqm4hep::core::typeToString().
{
       dqm_info( "=> TestAnalysisModule::endOfRun: {0}", core::typeToString(run) );
     }
void dqm4hep::online::TestAnalysisModule::initModule () private virtual
Initialize the module.
In this method, user should book monitor elements. See ModuleApi class.
Implements dqm4hep::online::Module.
Definition at line 60 of file TestAnalysisModule.cc.
References dqm4hep::online::ModuleApi::cd(), dqm_info, dqm4hep::online::ModuleApi::dump(), m_testGraph, m_testGraph2D, m_testHisto1D, m_testHisto2D, m_testScalarFloat, m_testScalarInt, m_testScalarShort, m_testScalarString, dqm4hep::online::ModuleApi::mkdir(), and THROW_RESULT_IF.
{
       dqm_info( "TestAnalysisModule::initModule" );
       // Create graphs in the Graphs directory
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::mkdir(this, "Graphs"));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::cd(this, "Graphs"));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::bookObject<TGraph>(this,
         m_testGraph, ".", "MyGraph", "The graph title"));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::bookObject<TGraph2D>(this,
         m_testGraph2D, ".", "MyGraph2D", "The graph 2D title"));
       // Create the histograms in the Histos directory
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::cd(this));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::mkdir(this, "Histos"));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::cd(this, "Histos"));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::bookHisto<TH1D>(this,
         m_testHisto1D, ".", "MyHisto1D", "The histo 1D title", 10, 0, 45));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::bookHisto<TH2D>(this,
         m_testHisto2D, ".", "MyHisto2D", "The histo 2D title", 100, 0., 99., 90, 0, 89));
       // Create the scalars in the Scalars directory
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::cd(this));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::mkdir(this, "Scalars"));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::cd(this, "Scalars"));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::bookScalar<int>(this,
         m_testScalarInt, ".", "MyScalarInt", "The scalar int title", 42));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::bookScalar<float>(this,
         m_testScalarFloat, ".", "MyScalarFloat", "The scalar float title", 785.f));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::bookScalar<short>(this,
         m_testScalarShort, ".", "MyScalarShort", "The scalar short title", 11));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::bookScalar<std::string>(this,
         m_testScalarString, ".", "MyScalarString", "The scalar string title", "Pimp my DQM !"));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::cd(this));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::dump(this));
     }
void dqm4hep::online::TestAnalysisModule::process (core::EventPtr event) private
Definition at line 136 of file TestAnalysisModule.cc.
References dqm_info, and dqm4hep::core::typeToString().
{
       dqm_info( "========> TestAnalysisModule::process: received event:");
       dqm_info( "========== Event {0}, run {1} ==", event->getEventNumber(), event->getRunNumber());
       dqm_info( "============> Event size: {0} bytes", event->getEventSize());
       dqm_info( "============> Time stamp: {0} ", core::typeToString(std::chrono::system_clock::to_time_t(event->getTimeStamp())));
     }
void dqm4hep::online::TestAnalysisModule::readSettings (const core::TiXmlHandle & handle) private virtual
Read the user settings from the xml handle.
handle the xml handle
Implements dqm4hep::online::Module.
Definition at line 50 of file TestAnalysisModule.cc.
References dqm_info, dqm4hep::core::TiXmlHandle::Element(), and dqm4hep::core::TiXmlPrinter::Str().
{
       auto element = handle.Element();
       core::TiXmlPrinter printer;
       element->Accept(&printer);
       dqm_info( "Received the following XML settings:" );
       dqm_info( printer.Str() );
     }
void dqm4hep::online::TestAnalysisModule::startOfCycle () private virtual
Callback function on start of cycle.
User can take appropriate actions such as monitor element reset, etc ...
Implements dqm4hep::online::Module.
Definition at line 112 of file TestAnalysisModule.cc.
References dqm_info.
{
       dqm_info( "====> TestAnalysisModule::startOfCycle" );
     }
void dqm4hep::online::TestAnalysisModule::startOfRun (core::Run & run) private virtual
Callback function on start of run.
User can get run configuration from the run object
Parameters
run the run configuration
Implements dqm4hep::online::Module.
Definition at line 106 of file TestAnalysisModule.cc.
References dqm_info, and dqm4hep::core::typeToString().
{
       dqm_info( "=> TestAnalysisModule::startOfRun: {0}", core::typeToString(run) );
     }
Member Data Documentation
OnlineElementPtr dqm4hep::online::TestAnalysisModule::m_testGraph = {nullptr} private
Definition at line 28 of file TestAnalysisModule.cc.
Referenced by initModule().
OnlineElementPtr dqm4hep::online::TestAnalysisModule::m_testGraph2D = {nullptr} private
Definition at line 29 of file TestAnalysisModule.cc.
Referenced by initModule().
OnlineElementPtr dqm4hep::online::TestAnalysisModule::m_testHisto1D = {nullptr} private
Definition at line 30 of file TestAnalysisModule.cc.
Referenced by initModule().
OnlineElementPtr dqm4hep::online::TestAnalysisModule::m_testHisto2D = {nullptr} private
Definition at line 31 of file TestAnalysisModule.cc.
Referenced by initModule().
OnlineElementPtr dqm4hep::online::TestAnalysisModule::m_testScalarFloat = {nullptr} private
Definition at line 33 of file TestAnalysisModule.cc.
Referenced by initModule().
OnlineElementPtr dqm4hep::online::TestAnalysisModule::m_testScalarInt = {nullptr} private
Definition at line 32 of file TestAnalysisModule.cc.
Referenced by initModule().
OnlineElementPtr dqm4hep::online::TestAnalysisModule::m_testScalarShort = {nullptr} private
Definition at line 34 of file TestAnalysisModule.cc.
Referenced by initModule().
OnlineElementPtr dqm4hep::online::TestAnalysisModule::m_testScalarString = {nullptr} private
Definition at line 35 of file TestAnalysisModule.cc.
Referenced by initModule().
The documentation for this class was generated from the following file:
TestAnalysisModule.cc