DQM4hep: dqm4hep::online::Application::NetworkHandler Class Reference
dqm4hep::online::Application::NetworkHandler Class Reference
NetworkHandler class.
Public Member Functions
NetworkHandler (AppEventLoop &eventLoop, const std::string &name, int priority=50, int maxNEvents=std::numeric_limits< int >::max())
Constructor.
template<typename Controller >
NetworkHandler (AppEventLoop &eventLoop, const std::string &name, Controller *controller, void(Controller::*function)(const net::Buffer &))
Constructor.
template<typename Controller >
NetworkHandler (AppEventLoop &eventLoop, const std::string &name, Controller *controller, void(Controller::*function)(const net::Buffer &, net::Buffer &))
Constructor.
void postServiceContent (const net::Buffer &buffer)
Post the service content in the event loop.
void sendServiceContent (const net::Buffer &buffer)
Send directly the service content.
void sendRequestEvent (const net::Buffer &request, net::Buffer &response)
Send directly the request content.
void postCommandEvent (const net::Buffer &buffer)
Post the command content in the event loop.
void sendCommandEvent (const net::Buffer &buffer)
Send directly the command content.
template<typename Controller >
NetworkHandler (AppEventLoop &eventLoop, const std::string &sname, Controller *controller, void(Controller::*function)(const net::Buffer &buffer))
template<typename Controller >
NetworkHandler (AppEventLoop &eventLoop, const std::string &sname, Controller *controller, void(Controller::*function)(const net::Buffer &buffer, net::Buffer &response))
Private Types
using ContentSignal = core::Signal< const net::Buffer & >
using RequestSignal = core::Signal< const net::Buffer &, net::Buffer & >
Private Attributes
AppEventLoop & m_eventLoop
const std::string m_name = {""}
const int m_priority = {50}
const int m_maxNEvents = {std::numeric_limits<int>::max()}
ContentSignal m_sendContentSignal = {}
RequestSignal m_sendRequestSignal = {}
Detailed Description
NetworkHandler class.
Definition at line 356 of file Application.h.
Member Typedef Documentation
using dqm4hep::online::Application::NetworkHandler::ContentSignal = core::Signal<const net::Buffer&> private
Definition at line 434 of file Application.h.
using dqm4hep::online::Application::NetworkHandler::RequestSignal = core::Signal<const net::Buffer&, net::Buffer&> private
Definition at line 435 of file Application.h.
Constructor & Destructor Documentation
dqm4hep::online::Application::NetworkHandler::NetworkHandler (AppEventLoop & eventLoop, const std::string & name, int priority = 50, int maxNEvents = std::numeric_limits<int>::max())
Constructor.
Parameters
eventLoop the application event loop
name the name of service/command/request to handle
priority the event priority, if the event is posted
Definition at line 425 of file Application.cc.
                                                                                                                           :
       m_eventLoop(eventLoop),
       m_name(name),
       m_priority(priority),
       m_maxNEvents(maxNEvents)
     {
     }
template<typename Controller > dqm4hep::online::Application::NetworkHandler::NetworkHandler (AppEventLoop & eventLoop, const std::string & name, Controller * controller, void(Controller::*)(const net::Buffer &) function)
Constructor.
Parameters
eventLoop the application event loop
name the name of service/command/request to handle
priority the event priority, if the event is posted
template<typename Controller > dqm4hep::online::Application::NetworkHandler::NetworkHandler (AppEventLoop & eventLoop, const std::string & name, Controller * controller, void(Controller::*)(const net::Buffer &, net::Buffer &) function)
Constructor.
Parameters
eventLoop the application event loop
name the name of service/command/request to handle
priority the event priority, if the event is posted
template<typename Controller > dqm4hep::online::Application::NetworkHandler::NetworkHandler (AppEventLoop & eventLoop, const std::string & sname, Controller * controller, void(Controller::*)(const net::Buffer &buffer) function) inline
Definition at line 533 of file Application.h.
References dqm4hep::core::Signal< Args >::connect(), and m_sendContentSignal.
                                                                                                                                                                                  :
       m_eventLoop(eventLoop),
       m_name(sname),
       m_priority(0),
       m_maxNEvents(0) {
       m_sendContentSignal.connect(controller, function);
     }
template<typename Controller > dqm4hep::online::Application::NetworkHandler::NetworkHandler (AppEventLoop & eventLoop, const std::string & sname, Controller * controller, void(Controller::*)(const net::Buffer &buffer, net::Buffer &response) function) inline
Definition at line 544 of file Application.h.
References dqm4hep::core::Signal< Args >::connect(), and m_sendRequestSignal.
                                                                                                                                                                                                       :
       m_eventLoop(eventLoop),
       m_name(sname),
       m_priority(0),
       m_maxNEvents(0) {
       m_sendRequestSignal.connect(controller, function);
     }
Member Function Documentation
void dqm4hep::online::Application::NetworkHandler::postCommandEvent (const net::Buffer & buffer)
Post the command content in the event loop.
The received buffer from the command is copied and pushed to the event queue using the AppEventLoop::postEvent() method.
Parameters
buffer the received buffer from the command handler
Definition at line 480 of file Application.cc.
References dqm4hep::net::Buffer::begin(), dqm4hep::online::CommandEvent::commandName(), dqm4hep::online::AppEventLoop::count(), dqm4hep::net::Buffer::createModel(), dqm_debug, dqm4hep::online::Application::m_eventLoop, dqm4hep::online::Application::m_name, dqm4hep::online::AppEventLoop::postEvent(), dqm4hep::online::AppEvent::setPriority(), and dqm4hep::net::Buffer::size().
Referenced by dqm4hep::online::Application::createQueuedCommand().
{
       int count = m_eventLoop.count([this](AppEvent* ptr){
         CommandEvent *evt = dynamic_cast<CommandEvent*>(ptr);
         return (evt && evt->commandName() == this->m_name);
       });
       if(count >= m_maxNEvents) {
         dqm_debug( "NetworkHandler::postCommandEvent(): maximum of posted command handling reached ({0}) !", m_maxNEvents );
         return;
       }
       // copy buffer content
       std::string content;
       content.assign(buffer.begin(), buffer.size());
       // create new buffer model
       auto bufferModel = buffer.createModel<std::string>();
       bufferModel->move(std::move(content));
       // create the event to post, pass the copied buffer in ctor
       CommandEvent *pEvent = new CommandEvent(m_name, bufferModel);
       pEvent->setPriority(m_priority);
       // post the event !
       m_eventLoop.postEvent(pEvent);
     }
void dqm4hep::online::Application::NetworkHandler::postServiceContent (const net::Buffer & buffer)
Post the service content in the event loop.
The received buffer from the service update is copied and pushed to the event queue using the AppEventLoop::postEvent() method.
Parameters
buffer the received buffer from the service update
Definition at line 435 of file Application.cc.
References dqm4hep::net::Buffer::begin(), dqm4hep::online::AppEventLoop::count(), dqm4hep::net::Buffer::createModel(), dqm_debug, dqm4hep::online::Application::m_eventLoop, dqm4hep::online::Application::m_name, dqm4hep::online::AppEventLoop::postEvent(), dqm4hep::online::ServiceUpdateEvent::serviceName(), dqm4hep::online::AppEvent::setPriority(), and dqm4hep::net::Buffer::size().
Referenced by dqm4hep::online::Application::queuedSubscribe().
{
       int count = m_eventLoop.count([this](AppEvent* ptr){
         ServiceUpdateEvent *evt = dynamic_cast<ServiceUpdateEvent*>(ptr);
         return (evt && evt->serviceName() == this->m_name);
       });
       if(count >= m_maxNEvents) {
         dqm_debug( "NetworkHandler::postServiceContent(): maximum of posted service updates reached ({0}) !", m_maxNEvents );
         return;
       }
       // copy buffer content
       std::string content;
       content.assign(buffer.begin(), buffer.size());
       // create new buffer model
       auto bufferModel = buffer.createModel<std::string>();
       bufferModel->move(std::move(content));
       // create the event to post, pass the copied buffer in ctor
       ServiceUpdateEvent *pEvent = new ServiceUpdateEvent(m_name, bufferModel);
       pEvent->setPriority(m_priority);
       // post the event !
       m_eventLoop.postEvent(pEvent);
     }
void dqm4hep::online::Application::NetworkHandler::sendCommandEvent (const net::Buffer & buffer)
Send directly the command content.
The received buffer from the command handler is not copied but directly sent to the user using the AppEventLoop::postEvent() method.
Parameters
buffer the received buffer from the command handler
Definition at line 509 of file Application.cc.
References dqm4hep::online::Application::m_eventLoop, and dqm4hep::online::AppEventLoop::processFunction().
Referenced by dqm4hep::online::Application::createDirectCommand().
{
       m_eventLoop.processFunction([&](){
         m_sendContentSignal.emit(buffer);
       });
     }
void dqm4hep::online::Application::NetworkHandler::sendRequestEvent (const net::Buffer & request, net::Buffer & response)
Send directly the request content.
The received buffer from the request handler is not copied but directly sent to the user using the AppEventLoop::postEvent() method.
Parameters
request the received buffer from the request handler
response the buffer to send back as response
Definition at line 472 of file Application.cc.
References dqm4hep::online::Application::m_eventLoop, and dqm4hep::online::AppEventLoop::processFunction().
Referenced by dqm4hep::online::Application::createRequestHandler().
{
       m_eventLoop.processFunction([&](){
         m_sendRequestSignal.emit(request, response);
       });
     }
void dqm4hep::online::Application::NetworkHandler::sendServiceContent (const net::Buffer & buffer)
Send directly the service content.
The received buffer from the service update is not copied but directly sent to the user using the AppEventLoop::postEvent() method.
Parameters
buffer the received buffer from the service update
Definition at line 464 of file Application.cc.
References dqm4hep::online::Application::m_eventLoop, and dqm4hep::online::AppEventLoop::processFunction().
Referenced by dqm4hep::online::Application::directSubscribe().
{
       m_eventLoop.processFunction([&](){
         m_sendContentSignal.emit(buffer);
       });
     }
Member Data Documentation
AppEventLoop& dqm4hep::online::Application::NetworkHandler::m_eventLoop private
Definition at line 437 of file Application.h.
const int dqm4hep::online::Application::NetworkHandler::m_maxNEvents = {std::numeric_limits<int>::max()} private
Definition at line 440 of file Application.h.
const std::string dqm4hep::online::Application::NetworkHandler::m_name = {""} private
Definition at line 438 of file Application.h.
const int dqm4hep::online::Application::NetworkHandler::m_priority = {50} private
Definition at line 439 of file Application.h.
ContentSignal dqm4hep::online::Application::NetworkHandler::m_sendContentSignal = {} private
Definition at line 441 of file Application.h.
Referenced by NetworkHandler().
RequestSignal dqm4hep::online::Application::NetworkHandler::m_sendRequestSignal = {} private
Definition at line 442 of file Application.h.
Referenced by NetworkHandler().
The documentation for this class was generated from the following files:
Application.h
Application.cc