DQM4hep: dqm4hep::online::StoreEvent< T > Class Template Reference
dqm4hep::online::StoreEvent< T > Class Template Reference
#include <AppEvents.h>
Public Member Functions
StoreEvent (int type, T data)
const T & data () const
Public Member Functions inherited from dqm4hep::online::AppEvent
AppEvent (int type)
Constructor.
virtual ~AppEvent ()
Destructor.
int type () const
Returns the event type.
void setPriority (int priority)
Set the event priority, range [0,100].
int priority () const
Get the event priority.
Private Attributes
T m_data
Additional Inherited Members
Public Types inherited from dqm4hep::online::AppEvent
enum Type {
NONE = 0, QUIT, SERVICE_UPDATE, REQUEST_HANDLING,
COMMAND_HANDLING, CLIENT_EXIT, START_OF_RUN, END_OF_RUN,
END_OF_CYCLE, PROCESS_EVENT, USER = 1024, MAX_USER = 65535
}
AppEvent type enum.
Detailed Description
template<typename T>
class dqm4hep::online::StoreEvent< T >
Definition at line 66 of file AppEvents.h.
Constructor & Destructor Documentation
template<typename T > dqm4hep::online::StoreEvent< T >::StoreEvent (int type, T data) inline
Definition at line 150 of file AppEvents.h.
                                                :
       AppEvent(t),
       m_data(d) {
       /* nop */
     }
Member Function Documentation
template<typename T > const T & dqm4hep::online::StoreEvent< T >::data () const inline
Definition at line 159 of file AppEvents.h.
Referenced by dqm4hep::online::EventCollector::handleClientExit(), dqm4hep::online::ModuleApplication::onEvent(), and dqm4hep::online::AppEventLoop::processEvent().
{
       return m_data;
     }
Member Data Documentation
template<typename T> T dqm4hep::online::StoreEvent< T >::m_data private
Definition at line 71 of file AppEvents.h.
The documentation for this class was generated from the following file:
AppEvents.h