DQM4hep: dqm4hep::core::time Class Reference
dqm4hep::core::time Class Reference
time helper class
#include <Internal.h>
Public Types
typedef std::chrono::system_clock clock
typedef clock::time_point point
typedef clock::duration duration
typedef clock::period period
Static Public Member Functions
static point now ()
Returns the current time.
static void sleep (const duration &d)
Sleep for a given duration.
static void usleep (unsigned int usec)
Sleep for n microseconds.
static void msleep (unsigned int msec)
Sleep for n milliseconds.
static void nsleep (unsigned int nsec)
Sleep for n nanoseconds.
static point asPoint (std::time_t t)
Convert time_t to time point.
static std::time_t asTime (const point &p)
Convert the time point to time_t.
static point asPoint (int32_t integer)
Convert the integer to time point.
static int32_t asInt (const point &p)
Convert the time point to integer.
static std::string asString (const point &p)
Convert a time pointto string.
Detailed Description
time helper class
Definition at line 149 of file Internal.h.
Member Typedef Documentation
typedef std::chrono::system_clock dqm4hep::core::time::clock
Definition at line 152 of file Internal.h.
typedef clock::duration dqm4hep::core::time::duration
Definition at line 154 of file Internal.h.
typedef clock::period dqm4hep::core::time::period
Definition at line 155 of file Internal.h.
typedef clock::time_point dqm4hep::core::time::point
Definition at line 153 of file Internal.h.
Member Function Documentation
static int32_t dqm4hep::core::time::asInt (const point & p) inline static
Convert the time point to integer.
Parameters
p the time point to convert
Definition at line 232 of file Internal.h.
References asTime().
{
         return static_cast<int32_t>(asTime(p));
       }
static point dqm4hep::core::time::asPoint (std::time_t t) inline static
Convert time_t to time point.
Parameters
t the time_t to convert
Definition at line 205 of file Internal.h.
Referenced by asPoint(), dqm4hep::core::Run::fromJson(), dqm4hep::core::Event::readBase(), dqm4hep::core::GenericEventXMLReader::readNextEvent(), and dqm4hep::core::GenericEventXMLReader::runInfo().
{
         return clock::from_time_t(t);
       }
static point dqm4hep::core::time::asPoint (int32_t integer) inline static
Convert the integer to time point.
Parameters
integer the integer to convert
Definition at line 223 of file Internal.h.
References asPoint().
{
         return asPoint(static_cast<std::time_t>(integer));
       }
static std::string dqm4hep::core::time::asString (const point & p) inline static
Convert a time pointto string.
Format is HH:MM:SS
Parameters
p the time point to convert
Definition at line 241 of file Internal.h.
References asTime().
Referenced by dqm4hep::core::screenSplash().
{
         auto timeT = asTime(p);
         std::tm timeTm;
         localtime_r(&timeT, &timeTm);
         std::stringstream ss;
         ss << timeTm.tm_hour << ":" << timeTm.tm_min << ":" << timeTm.tm_sec;
         return ss.str();
       }
static std::time_t dqm4hep::core::time::asTime (const point & p) inline static
Convert the time point to time_t.
Parameters
p the time point to convert
Definition at line 214 of file Internal.h.
Referenced by asInt(), asString(), dqm4hep::online::Application::sendStat(), dqm4hep::core::Run::toJson(), and dqm4hep::core::Event::writeBase().
{
         return clock::to_time_t(p);
       }
static void dqm4hep::core::time::msleep (unsigned int msec) inline static
Sleep for n milliseconds.
Parameters
usec the number of milliseconds to sleep for
Definition at line 187 of file Internal.h.
Referenced by dqm4hep::online::OnlineManagerServer::run(), and dqm4hep::online::RunControlServer::run().
{
         std::this_thread::sleep_for(std::chrono::milliseconds(msec));
       }
static point dqm4hep::core::time::now () inline static
Returns the current time.
Definition at line 160 of file Internal.h.
Referenced by dqm4hep::online::Cycle::cycleLoop(), dqm4hep::online::Cycle::endOfCycle(), dqm4hep::online::Cycle::incrementCounter(), dqm4hep::online::EventCollector::onInit(), dqm4hep::online::ModuleApplication::postStandaloneProcess(), dqm4hep::core::screenSplash(), dqm4hep::online::Application::sendStat(), dqm4hep::online::EventCollector::sendStatsTimer10(), dqm4hep::online::EventCollector::sendStatsTimer60(), dqm4hep::online::AppEventLoop::startTimer(), and dqm4hep::online::AppEventLoop::timerThread().
{
         return clock::now();
       }
static void dqm4hep::core::time::nsleep (unsigned int nsec) inline static
Sleep for n nanoseconds.
Parameters
usec the number of nanoseconds to sleep for
Definition at line 196 of file Internal.h.
{
         std::this_thread::sleep_for(std::chrono::nanoseconds(nsec));
       }
static void dqm4hep::core::time::sleep (const duration & d) inline static
Sleep for a given duration.
Parameters
d the duration to sleep for
Definition at line 169 of file Internal.h.
{
         std::this_thread::sleep_for(d);
       }
static void dqm4hep::core::time::usleep (unsigned int usec) inline static
Sleep for n microseconds.
Parameters
usec the number of micro seconds to sleep for
Definition at line 178 of file Internal.h.
{
         std::this_thread::sleep_for(std::chrono::microseconds(usec));
       }
The documentation for this class was generated from the following file:
Internal.h