DQM4hep: dqm4hep::core::Chi2Test Class Reference
dqm4hep::core::Chi2Test Class Reference
Chi2Test class.
Classes
class Factory
Public Member Functions
Chi2Test (const std::string &name)
~Chi2Test () override=default
StatusCode readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override
Read the settings from the xml handle.
std::string getTestOptions (std::string comparisonType)
void userRun (MonitorElement *monitorElement, QualityTestReport &report) override
Runs a quality test on the given monitor element and return a quality estimate.
Public Member Functions inherited from dqm4hep::core::QualityTest
QualityTest (const std::string &type, const std::string &name)
Constructor.
virtual ~QualityTest ()
Destructor.
const std::string & type () const
Get the quality test type.
const std::string & name () const
Get the quality test name (unique identifier)
const std::string & description () const
Get the quality test description.
void run (MonitorElement *monitorElement, QualityTestReport &report)
Perform the quality test result and fill the quality test report.
virtual StatusCode init ()
Initialize the quality test.
virtual bool enoughStatistics (MonitorElement *monitorElement) const
Whether the monitor element has enough statistics to perform the qtest.
void setLimits (float warning, float error)
Set the warning and error limits on quality test result.
float warningLimit () const
Get the warning limit.
float errorLimit () const
Get the error limit.
Protected Attributes
std::string m_comparisonType
bool m_useUnderflow = {false}
bool m_useOverflow = {false}
Protected Attributes inherited from dqm4hep::core::QualityTest
std::string m_description = {""}
Quality test description.
Additional Inherited Members
Static Public Member Functions inherited from dqm4hep::core::QualityTest
static float defaultWarningLimit ()
Get the default warning limit.
static float defaultErrorLimit ()
Get the default error limit.
Protected Member Functions inherited from dqm4hep::core::QualityTest
void fillBasicInfo (MonitorElement *monitorElement, QualityTestReport &report) const
Fill basic info in the qtest report.
Static Protected Attributes inherited from dqm4hep::core::QualityTest
static float m_defaultWarningLimit = 0.8
static float m_defaultErrorLimit = 0.5
Detailed Description
Chi2Test class.
Definition at line 31 of file Chi2Test.cc.
Constructor & Destructor Documentation
dqm4hep::core::Chi2Test::Chi2Test (const std::string & name)
Definition at line 63 of file Chi2Test.cc.
References dqm4hep::core::QualityTest::m_description.
Referenced by dqm4hep::core::Chi2Test::Factory::createQualityTest().
         : QualityTest("Chi2", qname),
     m_comparisonType("UU")
 {
       m_description = "Performs the chi-squared test on a TH1 and a reference, outputting the p-value. This is analogous to the Kolmogorov-Smirnov "
                 "test but is appropriate for use on binned data like histograms, which the Kolmogorov test is not.";
     }
dqm4hep::core::Chi2Test::~Chi2Test () override default
Member Function Documentation
std::string dqm4hep::core::Chi2Test::getTestOptions (std::string comparisonType)
Definition at line 81 of file Chi2Test.cc.
References m_useOverflow, and m_useUnderflow.
Referenced by userRun().
{
       std::string optionsString;
       if (comparisonType == "UU") {
   optionsString = "UU";
       }
       else if (comparisonType == "UW") {
   optionsString = "UW";
       }
       else if (comparisonType == "WW") {
   optionsString = "WW";
       }
       else if (comparisonType == "NORM") {
   optionsString = "NORM";
       }
       if (m_useUnderflow) {
   optionsString += "UF";
       }
       if (m_useOverflow) {
   optionsString += "OF";
       }
       return optionsString;
     }
StatusCode dqm4hep::core::Chi2Test::readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override virtual
Read the settings from the xml handle.
Implements dqm4hep::core::QualityTest.
Definition at line 73 of file Chi2Test.cc.
References m_comparisonType, m_useOverflow, m_useUnderflow, dqm4hep::core::XmlHelper::readParameter(), and RETURN_RESULT_IF_AND_IF.
{
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle, "ComparisonType", m_comparisonType));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle, "UseUnderflow", m_useUnderflow));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle, "UseOverflow", m_useOverflow));
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::Chi2Test::userRun (MonitorElement * monitorElement, QualityTestReport & report) override virtual
Runs a quality test on the given monitor element and return a quality estimate.
Implements dqm4hep::core::QualityTest.
Definition at line 108 of file Chi2Test.cc.
References getTestOptions(), m_comparisonType, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, dqm4hep::core::MonitorElement::object(), dqm4hep::core::MonitorElement::objectTo(), dqm4hep::core::MonitorElement::reference(), and dqm4hep::core::MonitorElement::referenceTo().
{
       const bool hasObject = (pMonitorElement->object() != nullptr);
       const bool hasReference = (pMonitorElement->reference() != nullptr);
       if (!hasObject) {
         report.m_message = "No object attached to monitor element";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_INVALID_PTR);
       }
       if (!hasReference) {
         report.m_message = "No reference attached to monitor element";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_INVALID_PTR);
       }
       const bool isObjHistogram = pMonitorElement->object()->InheritsFrom("TH1");
       const bool isRefHistogram = pMonitorElement->reference()->InheritsFrom("TH1");
       if (!isObjHistogram or !isRefHistogram) {
         report.m_message = "Both the object and the reference must be a TH1";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
       }
       TH1* pHistogram = pMonitorElement->objectTo<TH1>();
       TH1* pReferenceHistogram = pMonitorElement->referenceTo<TH1>();
       std::string options = Chi2Test::getTestOptions(m_comparisonType);
       report.m_quality = pHistogram->Chi2Test(pReferenceHistogram, options.c_str());
     }
Member Data Documentation
std::string dqm4hep::core::Chi2Test::m_comparisonType protected
Definition at line 45 of file Chi2Test.cc.
Referenced by readSettings(), and userRun().
bool dqm4hep::core::Chi2Test::m_useOverflow = {false} protected
Definition at line 47 of file Chi2Test.cc.
Referenced by getTestOptions(), and readSettings().
bool dqm4hep::core::Chi2Test::m_useUnderflow = {false} protected
Definition at line 46 of file Chi2Test.cc.
Referenced by getTestOptions(), and readSettings().
The documentation for this class was generated from the following file:
Chi2Test.cc