DQM4hep: dqm4hep::online::AppEvent Class Reference
dqm4hep::online::AppEvent Class Reference
#include <AppEvent.h>
Public Types
enum Type {
NONE = 0, QUIT, SERVICE_UPDATE, REQUEST_HANDLING,
COMMAND_HANDLING, CLIENT_EXIT, START_OF_RUN, END_OF_RUN,
END_OF_CYCLE, PROCESS_EVENT, USER = 1024, MAX_USER = 65535
}
AppEvent type enum.
Public Member Functions
AppEvent (int type)
Constructor.
virtual ~AppEvent ()
Destructor.
int type () const
Returns the event type.
void setPriority (int priority)
Set the event priority, range [0,100].
int priority () const
Get the event priority.
Private Attributes
int m_type = {AppEvent::NONE}
The application event type.
int m_priority = {50}
The event priority.
Detailed Description
Definition at line 18 of file AppEvent.h.
Member Enumeration Documentation
enum dqm4hep::online::AppEvent::Type
AppEvent type enum.
Enumerator
NONE
QUIT
SERVICE_UPDATE
REQUEST_HANDLING
COMMAND_HANDLING
CLIENT_EXIT
START_OF_RUN
END_OF_RUN
END_OF_CYCLE
PROCESS_EVENT
USER
MAX_USER
Definition at line 23 of file AppEvent.h.
                 {
         NONE = 0,
         QUIT,
         SERVICE_UPDATE,
         REQUEST_HANDLING,
         COMMAND_HANDLING,
         CLIENT_EXIT,
         START_OF_RUN,
         END_OF_RUN,
         END_OF_CYCLE,
         PROCESS_EVENT,
         USER = 1024,
         MAX_USER = 65535
       };
Constructor & Destructor Documentation
dqm4hep::online::AppEvent::AppEvent (int type)
Constructor.
Definition at line 18 of file AppEvent.cc.
                             :
       m_type(t) {
         /* nop */
     }
dqm4hep::online::AppEvent::~AppEvent () virtual
Destructor.
Definition at line 25 of file AppEvent.cc.
{
       /* nop */
     }
Member Function Documentation
int dqm4hep::online::AppEvent::priority () const
Get the event priority.
Definition at line 51 of file AppEvent.cc.
References m_priority.
Referenced by dqm4hep::online::AppEventLoop::QueueCompare::operator()().
{
       return m_priority;
     }
void dqm4hep::online::AppEvent::setPriority (int priority)
Set the event priority, range [0,100].
Parameters
priority the event priority
Definition at line 37 of file AppEvent.cc.
References m_priority.
Referenced by dqm4hep::online::Cycle::endOfCycle(), dqm4hep::online::AppEventLoop::exit(), dqm4hep::online::Application::NetworkHandler::postCommandEvent(), dqm4hep::online::Application::NetworkHandler::postServiceContent(), dqm4hep::online::ModuleApplication::postStandaloneProcess(), dqm4hep::online::ModuleApplication::processEndOfRun(), and dqm4hep::online::ModuleApplication::receiveEvent().
{
       if(p > 100) {
         m_priority = 100;
       }
       else if(p < 0) {
         m_priority = 0;
       }
       else {
         m_priority = p;
       }
     }
int dqm4hep::online::AppEvent::type () const
Returns the event type.
Definition at line 31 of file AppEvent.cc.
References m_type.
Referenced by dqm4hep::online::EventCollector::onEvent(), dqm4hep::online::ModuleApplication::onEvent(), dqm4hep::online::AppEventLoop::processEvent(), and dqm4hep::online::AppEventLoop::sendEvent().
{
       return m_type;
     }
Member Data Documentation
int dqm4hep::online::AppEvent::m_priority = {50} private
The event priority.
Definition at line 69 of file AppEvent.h.
Referenced by priority(), and setPriority().
int dqm4hep::online::AppEvent::m_type = {AppEvent::NONE} private
The application event type.
Definition at line 67 of file AppEvent.h.
Referenced by type().
The documentation for this class was generated from the following files:
AppEvent.h
AppEvent.cc