DQM4hep: dqm4hep::core::FitParamInRangeTest Class Reference
dqm4hep::core::FitParamInRangeTest Class Reference
FitParamInRangeTest class.
Classes
class Factory
Factory class to create quality test.
Public Member Functions
FitParamInRangeTest (const std::string &qname)
Constructor.
~FitParamInRangeTest () override=default
Destructor.
StatusCode readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override
Read settings from the xml handle.
void userRun (MonitorElement *monitorElement, QualityTestReport &report) override
Run the quality test and get a quality test report from it.
Public Member Functions inherited from dqm4hep::core::QualityTest
QualityTest (const std::string &type, const std::string &name)
Constructor.
virtual ~QualityTest ()
Destructor.
const std::string & type () const
Get the quality test type.
const std::string & name () const
Get the quality test name (unique identifier)
const std::string & description () const
Get the quality test description.
void run (MonitorElement *monitorElement, QualityTestReport &report)
Perform the quality test result and fill the quality test report.
virtual StatusCode init ()
Initialize the quality test.
virtual bool enoughStatistics (MonitorElement *monitorElement) const
Whether the monitor element has enough statistics to perform the qtest.
void setLimits (float warning, float error)
Set the warning and error limits on quality test result.
float warningLimit () const
Get the warning limit.
float errorLimit () const
Get the error limit.
Private Member Functions
TF1 * createFunction () const
Create the function to fit.
bool checkElement (MonitorElement *monitorElement) const
Check the input monitor element.
bool checkElement (MonitorElement *monitorElement, TF1 *function, QReport &report) const
Check consistency between the monitor element and the fit function.
std::string getFitOptions (bool isHistogram, bool withSumW2) const
Get the fit options.
TFitResultPtr performFit (MonitorElement *monitorElement, TF1 *fitFunction, QReport &report) const
Perform the fit.
void performRangeTest (TFitResultPtr fitResult, QReport &report) const
Perform the range test.
template<typename T >
bool withinRange (T value, T lower, T upper) const
Test whether a value is within a certain range.
Private Attributes
std::string m_fitFormula = {""}
The TF1 formula to fit (mandatory)
FloatVector m_guessParameters = {}
The list of function parameter to guess before fitting (optional)
unsigned int m_testParameter = {0}
The parameter id to test (mandatory)
double m_deviationLower = {0.}
The lower deviation bound allow for the test parameter (mandatory)
double m_deviationUpper = {0.}
The upper deviation bound allow for the test parameter (mandatory)
FloatVector m_functionRange = {}
The function range for fitting (optional)
bool m_useLoglikelihood = {false}
Whether to use a log likelihood for fitting (optional)
bool m_usePearsonChi2 = {false}
Whether to use a pearson chi2 for fitting.
bool m_improveFitResult = {false}
Whether to use the IMPROVE command in TMinuit fitter.
Additional Inherited Members
Static Public Member Functions inherited from dqm4hep::core::QualityTest
static float defaultWarningLimit ()
Get the default warning limit.
static float defaultErrorLimit ()
Get the default error limit.
Protected Member Functions inherited from dqm4hep::core::QualityTest
void fillBasicInfo (MonitorElement *monitorElement, QualityTestReport &report) const
Fill basic info in the qtest report.
Protected Attributes inherited from dqm4hep::core::QualityTest
std::string m_description = {""}
Quality test description.
Static Protected Attributes inherited from dqm4hep::core::QualityTest
static float m_defaultWarningLimit = 0.8
static float m_defaultErrorLimit = 0.5
Detailed Description
FitParamInRangeTest class.
Fit a user function on
TGraph
TGraph2D
TH1 and look if a chosen fit parameter is within a certain allowed range.
Definition at line 45 of file FitParamInRangeTest.cc.
Constructor & Destructor Documentation
dqm4hep::core::FitParamInRangeTest::FitParamInRangeTest (const std::string & qname)
Constructor.
Parameters
qname the quality test name
Definition at line 179 of file FitParamInRangeTest.cc.
References dqm4hep::core::QualityTest::m_description.
Referenced by dqm4hep::core::FitParamInRangeTest::Factory::createQualityTest().
         : QualityTest("FitParameters", qname) {
       m_description = std::string("Fit a user function on\n") +
       "  - TGraph\n" +
       "  - TGraph2D\n" +
       "  - TH1\n" +
       "and look if a chosen fit parameter is within a certain allowed range.";
     }
dqm4hep::core::FitParamInRangeTest::~FitParamInRangeTest () override default
Destructor.
Member Function Documentation
bool dqm4hep::core::FitParamInRangeTest::checkElement (MonitorElement * monitorElement) const private
Check the input monitor element.
Parameters
monitorElement the monitor element to check
Definition at line 326 of file FitParamInRangeTest.cc.
References dqm4hep::core::MonitorElement::objectTo().
Referenced by userRun().
{
       const bool isHistogram = (nullptr == monitorElement->objectTo<TH1>());
       const bool isGraph = (nullptr == monitorElement->objectTo<TGraph>());
       const bool isGraph2D = (nullptr == monitorElement->objectTo<TGraph2D>());
       return (isHistogram or isGraph or isGraph2D);
     }
bool dqm4hep::core::FitParamInRangeTest::checkElement (MonitorElement * monitorElement, TF1 * function, QReport & report) const private
Check consistency between the monitor element and the fit function.
Parameters
monitorElement the input monitor element
function the fit function
report the quality test report to fill if error occurs
Definition at line 335 of file FitParamInRangeTest.cc.
References dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, and dqm4hep::core::MonitorElement::objectTo().
{
       TH1 *histogram = monitorElement->objectTo<TH1>();
       TGraph *graph = monitorElement->objectTo<TGraph>();
       TGraph2D *graph2D = monitorElement->objectTo<TGraph2D>();
       // Check formula dimensions
       if(nullptr != histogram and fitFunction->GetNdim() != histogram->GetDimension()) {
         report.m_message = "TH1 attached to monitor element and fit formula have different dimensions !";
         report.m_quality = 0.f;
         return false;
       }
       if(nullptr != graph and fitFunction->GetNdim() != 1) {
         report.m_message = "TGraph attached to monitor element and fit formula have different dimensions !";
         report.m_quality = 0.f;
         return false;
       }
       if(nullptr != graph2D and fitFunction->GetNdim() != 2) {
         report.m_message = "TGraph2D attached to monitor element and fit formula have different dimensions !";
         report.m_quality = 0.f;
         return false;
       }
       return true;
     }
TF1 * dqm4hep::core::FitParamInRangeTest::createFunction () const private
Create the function to fit.
Definition at line 275 of file FitParamInRangeTest.cc.
References dqm_debug, m_fitFormula, m_functionRange, and m_guessParameters.
Referenced by userRun().
{
       // Create our function
       std::stringstream formulaName;
       formulaName << "FitFormula_" << (void*)this;
       TFormula formula(formulaName.str().c_str(), m_fitFormula.c_str(), true);
       TF1 *fitFunction = nullptr;
       if(formula.GetNdim() == 1) {
         dqm_debug( "Created function 1D" );
         fitFunction = new TF1(formulaName.str().c_str(), m_fitFormula.c_str(), 0, 1);
       }
       else if(formula.GetNdim() == 2) {
         dqm_debug( "Created function 2D" );
         fitFunction = new TF2(formulaName.str().c_str(), m_fitFormula.c_str(), 0, 1, 0, 1);
       }
       else if(formula.GetNdim() == 3) {
         dqm_debug( "Created function 3D" );
         fitFunction = new TF3(formulaName.str().c_str(), m_fitFormula.c_str(), 0, 1, 0, 1, 0, 1);
       }
       else {
         throw StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
       }
       // set guess parameters
       dqm_debug( "Settings guess parameters ..." );
       for(unsigned int i=0 ; i<m_guessParameters.size() ; ++i) {
         fitFunction->SetParameter(i, m_guessParameters.at(i));
       }
       dqm_debug( "Settings guess parameters ... OK" );
       // set function range
       dqm_debug( "Settings function range ..." );
       Double_t functionRange[6] = {0};
       for(unsigned int i=0 ; i<6 ; ++i) {
         if(i < m_functionRange.size()) {
           functionRange[i] = m_functionRange.at(i);
         }
         else {
           functionRange[i] = 0.;
         }
       }
       if(not m_functionRange.empty()) {
         dqm_debug( "Calling SetRange(...)" );
         fitFunction->SetRange(
           functionRange[0], functionRange[2], functionRange[4],
           functionRange[1], functionRange[3], functionRange[5]
         );
       }
       dqm_debug( "Settings function range ... OK" );
       return fitFunction;
     }
std::string dqm4hep::core::FitParamInRangeTest::getFitOptions (bool isHistogram, bool withSumW2) const private
Get the fit options.
Parameters
isHistogram whether the fit object is an histogram
withSumW2 whether the histogram as the sumw2 set
Definition at line 360 of file FitParamInRangeTest.cc.
References m_functionRange, m_improveFitResult, m_useLoglikelihood, and m_usePearsonChi2.
Referenced by performFit().
{
       // setup fit option
       std::string fitOptions = "QN0+S";
       if(m_usePearsonChi2 and isHistogram) {
         fitOptions += "P";
       }
       if(m_useLoglikelihood and isHistogram) {
         if(withSumW2) {
           fitOptions += "W";
         }
         fitOptions += "L";
       }
       if(m_improveFitResult) {
         fitOptions += "M";
       }
       if(not m_functionRange.empty()) {
         fitOptions += "R";
       }
       return fitOptions;
     }
TFitResultPtr dqm4hep::core::FitParamInRangeTest::performFit (MonitorElement * monitorElement, TF1 * fitFunction, QReport & report) const private
Perform the fit.
Parameters
monitorElement the monitor element to fit
fitFunction the function to fit
report the quality test report to fill
Definition at line 383 of file FitParamInRangeTest.cc.
References dqm_debug, getFitOptions(), dqm4hep::core::QualityTestReport::m_extraInfos, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, and dqm4hep::core::MonitorElement::objectTo().
Referenced by userRun().
{
       TH1 *histogram = monitorElement->objectTo<TH1>();
       TGraph *graph = monitorElement->objectTo<TGraph>();
       TGraph2D *graph2D = monitorElement->objectTo<TGraph2D>();
       // get the fit options
       bool isHistogram = (nullptr != monitorElement->objectTo<TH1>());
       bool withSumW2 = false;
       if(isHistogram)
         withSumW2 = (0 != monitorElement->objectTo<TH1>()->GetSumw2N());
       std::string fitOptions = getFitOptions(isHistogram, withSumW2);
       report.m_extraInfos["fit.opt"] = fitOptions;
       // perform fit
       TFitResultPtr fitResult;
       if(nullptr != histogram) {
         dqm_debug( "Fitting histogram" );
         fitResult = histogram->Fit(fitFunction, fitOptions.c_str(), "");
       }
       else if(nullptr != graph) {
         dqm_debug( "Fitting graph" );
         fitResult = graph->Fit(fitFunction, fitOptions.c_str(), "");
       }
       else if(nullptr != graph2D) {
         dqm_debug( "Fitting graph2D" );
         TF2 *fitFunction2D = (TF2*)fitFunction;
         fitResult = graph2D->Fit(fitFunction2D, fitOptions.c_str(), "");
       }
       dqm_debug( "Fitting done ..." );
       if(not fitResult->IsValid() or fitResult->IsEmpty()) {
         report.m_message = "Fit operation returned error !";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       return fitResult;
     }
void dqm4hep::core::FitParamInRangeTest::performRangeTest (TFitResultPtr fitResult, QReport & report) const private
Perform the range test.
Parameters
fitResult the actual fit result
report the quality test report to fill
Definition at line 420 of file FitParamInRangeTest.cc.
References dqm4hep::core::QualityTest::errorLimit(), m_deviationLower, m_deviationUpper, dqm4hep::core::QualityTestReport::m_extraInfos, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, m_testParameter, dqm4hep::core::QualityTest::warningLimit(), and withinRange().
Referenced by userRun().
{
       const double testParameter = fitResult->GetParams()[m_testParameter];
       const double testParameterError = fitResult->GetErrors()[m_testParameter];
       const double testParameterMinus = testParameter - testParameterError;
       const double testParameterPlus = testParameter + testParameterError;
       if(withinRange(testParameter, m_deviationLower, m_deviationUpper)) {
         report.m_message = "Fit parameter within range";
         report.m_quality = 1.f; // TODO scale me correctly !
       }
       else if(testParameterPlus > m_deviationLower or testParameterMinus < m_deviationUpper) {
         report.m_message = "Fit parameter not within range, but by using the fit parameter error, the value is within the expected range";
         report.m_quality = (this->errorLimit() + this->warningLimit())/2.f; // TODO scale me correctly !
       }
       else {
         report.m_message = "Fit parameter not within range !";
         report.m_quality = this->errorLimit() / 2.f; // TODO scale me correctly !
       }
       report.m_extraInfos["fit.val"] = testParameter;
       report.m_extraInfos["fit.err"] = testParameterError;
       report.m_extraInfos["fit.prob"] = fitResult->Prob();
       report.m_extraInfos["fit.status"] = fitResult->Status();
       report.m_extraInfos["fit.ncalls"] = fitResult->NCalls();
       report.m_extraInfos["fit.mintype"] = fitResult->MinimizerType();
       report.m_extraInfos["fit.minfcn"] = fitResult->MinFcnValue();
       report.m_extraInfos["fit.edm"] = fitResult->Edm();
       report.m_extraInfos["fit.chi2"] = fitResult->Chi2();
     }
StatusCode dqm4hep::core::FitParamInRangeTest::readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override virtual
Read settings from the xml handle.
Parameters
xmlHandle the xml handle to parse
Implements dqm4hep::core::QualityTest.
Definition at line 197 of file FitParamInRangeTest.cc.
References m_deviationLower, m_deviationUpper, m_fitFormula, m_functionRange, m_guessParameters, m_improveFitResult, m_testParameter, m_useLoglikelihood, m_usePearsonChi2, dqm4hep::core::XmlHelper::readParameter(), dqm4hep::core::XmlHelper::readParameters(), RETURN_RESULT_IF, and RETURN_RESULT_IF_AND_IF.
{
       UInt_t nParameters = 0;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(xmlHandle,
         "FitFormula", m_fitFormula, [&nParameters,this](const std::string &value){
           if(value.empty()) {
             return false;
           }
           std::stringstream formulaName;
           formulaName << "Formula_RS_" << (void*)this;
           TFormula formula(formulaName.str().c_str(), value.c_str(), true);
           nParameters = formula.GetNpar();
           if(0 == nParameters) {
             return false;
           }
           return true;
         }));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameters(xmlHandle,
         "GuessParameters", m_guessParameters, [nParameters](const FloatVector &values){
           return (values.size() <= nParameters);
         }));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(xmlHandle,
         "TestParameter", m_testParameter, [nParameters](unsigned int value){
           return (nParameters > value);
         }));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(xmlHandle,
         "DeviationLower", m_deviationLower));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameter(xmlHandle,
         "DeviationUpper", m_deviationUpper, [this](double value){
           return (this->m_deviationLower < value);
         }));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameters(xmlHandle,
         "FunctionRange", m_functionRange, [](const FloatVector &values){
           return (values.size() <= 6);
         }));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle,
         "UseLoglikelihood", m_useLoglikelihood));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle,
         "UsePearsonChi2", m_usePearsonChi2));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle,
         "ImproveFitResult", m_improveFitResult));
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::FitParamInRangeTest::userRun (MonitorElement * monitorElement, QualityTestReport & report) override virtual
Run the quality test and get a quality test report from it.
Parameters
monitorElement the monitor element to test
report the quality test report to receive
Implements dqm4hep::core::QualityTest.
Definition at line 251 of file FitParamInRangeTest.cc.
References checkElement(), createFunction(), dqm4hep::core::QualityTestReport::m_extraInfos, m_fitFormula, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, performFit(), and performRangeTest().
{
       report.m_extraInfos["formula"] = m_fitFormula;
       // check monitor element first
       if(not checkElement(monitorElement)) {
         report.m_message = "Object attached to monitor element is not a TH1, TGraph or TGraph2D !";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_INVALID_PTR);
       }
       // create the function
       TF1 *fitFunction = createFunction();
       std::unique_ptr<TF1> up(fitFunction);
       // check monitor element <-> function matching
       if(not checkElement(monitorElement, fitFunction, report)) {
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       // perform fit
       TFitResultPtr fitResult = performFit(monitorElement, fitFunction, report);
       up.release();
       // perform range check
       performRangeTest(fitResult, report);
     }
template<typename T > bool dqm4hep::core::FitParamInRangeTest::withinRange (T value, T lower, T upper) const inline private
Test whether a value is within a certain range.
Parameters
value the value to test
lower the lower range bound
upper the upper range bound
Definition at line 191 of file FitParamInRangeTest.cc.
Referenced by performRangeTest().
{
       return (value > lower and value < upper);
     }
Member Data Documentation
double dqm4hep::core::FitParamInRangeTest::m_deviationLower = {0.} private
The lower deviation bound allow for the test parameter (mandatory)
Definition at line 152 of file FitParamInRangeTest.cc.
Referenced by performRangeTest(), and readSettings().
double dqm4hep::core::FitParamInRangeTest::m_deviationUpper = {0.} private
The upper deviation bound allow for the test parameter (mandatory)
Definition at line 154 of file FitParamInRangeTest.cc.
Referenced by performRangeTest(), and readSettings().
std::string dqm4hep::core::FitParamInRangeTest::m_fitFormula = {""} private
The TF1 formula to fit (mandatory)
Definition at line 146 of file FitParamInRangeTest.cc.
Referenced by createFunction(), readSettings(), and userRun().
FloatVector dqm4hep::core::FitParamInRangeTest::m_functionRange = {} private
The function range for fitting (optional)
Definition at line 156 of file FitParamInRangeTest.cc.
Referenced by createFunction(), getFitOptions(), and readSettings().
FloatVector dqm4hep::core::FitParamInRangeTest::m_guessParameters = {} private
The list of function parameter to guess before fitting (optional)
Definition at line 148 of file FitParamInRangeTest.cc.
Referenced by createFunction(), and readSettings().
bool dqm4hep::core::FitParamInRangeTest::m_improveFitResult = {false} private
Whether to use the IMPROVE command in TMinuit fitter.
Definition at line 162 of file FitParamInRangeTest.cc.
Referenced by getFitOptions(), and readSettings().
unsigned int dqm4hep::core::FitParamInRangeTest::m_testParameter = {0} private
The parameter id to test (mandatory)
Definition at line 150 of file FitParamInRangeTest.cc.
Referenced by performRangeTest(), and readSettings().
bool dqm4hep::core::FitParamInRangeTest::m_useLoglikelihood = {false} private
Whether to use a log likelihood for fitting (optional)
Definition at line 158 of file FitParamInRangeTest.cc.
Referenced by getFitOptions(), and readSettings().
bool dqm4hep::core::FitParamInRangeTest::m_usePearsonChi2 = {false} private
Whether to use a pearson chi2 for fitting.
Definition at line 160 of file FitParamInRangeTest.cc.
Referenced by getFitOptions(), and readSettings().
The documentation for this class was generated from the following file:
FitParamInRangeTest.cc