DQM4hep: dqm4hep::online::RunControlServer Class Reference
dqm4hep::online::RunControlServer Class Reference
RunControlServer class The main run control server runner class.
#include <RunControlServer.h>
Public Member Functions
RunControlServer ()=default
Default constructor.
RunControlServer (const RunControlServer &)=delete
RunControlServer & operator= (const RunControlServer &)=delete
~RunControlServer ()=default
Destructor.
void setName (const std::string &name)
Set the run control name Must be called before run()
void setPassword (const std::string &password)
Set the run control password Must be called before run()
void setInterface (const std::string &name)
Set the plugin name of the ouside interface.
void setUserParameters (const dqm4hep::core::StringMap &parameters)
Set the user parameters.
void run ()
Run the server.
void stop ()
Stop the server.
RunControl & runControl ()
Get the run control.
Private Types
typedef std::shared_ptr
< RunControlInterface > RunControlInterfacePtr
typedef std::shared_ptr
< dqm4hep::net::Server > ServerPtr
Private Member Functions
void sor (dqm4hep::core::Run &run)
void eor (const dqm4hep::core::Run &run)
void sendCurrentRun (const dqm4hep::net::Buffer &request, dqm4hep::net::Buffer &response)
Private Attributes
RunControl m_runControl = {}
The main run control.
ServerPtr m_server = {nullptr}
The server to run.
dqm4hep::net::Service * m_pSorService = {nullptr}
The "start of run" service.
dqm4hep::net::Service * m_pEorService = {nullptr}
The "end of run" service.
RunControlInterfacePtr m_interface = {nullptr}
The external user plugin interface.
dqm4hep::core::StringMap m_userParameters = {}
The user parameters.
std::atomic< bool > m_stopFlag = {false}
The stop flag to run the server.
std::string m_interfaceName = {""}
The external user interface plugin name.
Detailed Description
RunControlServer class The main run control server runner class.
May be instantiated from a main(). Act as a bridge between an external run control interface and the applications listenning to this run control.
Definition at line 52 of file RunControlServer.h.
Member Typedef Documentation
typedef std::shared_ptr<RunControlInterface> dqm4hep::online::RunControlServer::RunControlInterfacePtr private
Definition at line 118 of file RunControlServer.h.
typedef std::shared_ptr<dqm4hep::net::Server> dqm4hep::online::RunControlServer::ServerPtr private
Definition at line 119 of file RunControlServer.h.
Constructor & Destructor Documentation
dqm4hep::online::RunControlServer::RunControlServer () default
Default constructor.
dqm4hep::online::RunControlServer::RunControlServer (const RunControlServer &) delete
dqm4hep::online::RunControlServer::~RunControlServer () default
Destructor.
Member Function Documentation
void dqm4hep::online::RunControlServer::eor (const dqm4hep::core::Run & run) private
Definition at line 140 of file RunControlServer.cc.
References dqm4hep::core::Run::toJson().
{
       core::json jsonRun;
       r.toJson(jsonRun);
       m_pEorService->send(jsonRun.dump());
     }
RunControlServer& dqm4hep::online::RunControlServer::operator= (const RunControlServer &) delete
void dqm4hep::online::RunControlServer::run ()
Run the server.
Definition at line 72 of file RunControlServer.cc.
References dqm4hep::core::PluginManager::create(), dqm_error, dqm4hep::core::Singleton< PluginManager >::instance(), and dqm4hep::core::sleep().
{
       m_stopFlag = false;
       // create user external interface (plugin)
       m_interface = PluginManager::instance()->create<RunControlInterface>(m_interfaceName);
       if( not m_interface ) {
         dqm_error( "Couldn't find run control interface '{0}' in plugin manager", m_interfaceName );
         throw StatusCodeException(STATUS_CODE_NOT_FOUND);
       }
       // create network interface
       m_server = std::make_shared<dqm4hep::net::Server>(m_runControl.name());
       m_pSorService = m_server->createService(OnlineRoutes::RunControl::sor(m_runControl.name()));
       m_runControl.onStartOfRun().connect(this, &RunControlServer::sor);
       m_pEorService = m_server->createService(OnlineRoutes::RunControl::eor(m_runControl.name()));
       m_runControl.onEndOfRun().connect(this, &RunControlServer::eor);
       m_server->createRequestHandler(OnlineRoutes::RunControl::status(m_runControl.name()), this, &RunControlServer::sendCurrentRun);
       m_interface->setServer(this);
       m_interface->readSettings(m_userParameters);
       // start the server
       m_server->start();
       // run the user plugin
       if(m_interface->runBlocking())
       {
         // block here until stop called from outside
         m_interface->run();
       }
       else
       {
         // call run and sleep
         m_interface->run();
         while( ! m_stopFlag )
           dqm4hep::core::sleep(dqm4hep::core::TimeDuration(1));
       }
       m_server->stop();
       m_pSorService = nullptr;
       m_pEorService = nullptr;
     }
RunControl & dqm4hep::online::RunControlServer::runControl ()
Get the run control.
Definition at line 66 of file RunControlServer.cc.
{
       return m_runControl;
     }
void dqm4hep::online::RunControlServer::sendCurrentRun (const dqm4hep::net::Buffer & request, dqm4hep::net::Buffer & response) private
Definition at line 148 of file RunControlServer.cc.
References dqm4hep::net::Buffer::createModel(), and dqm4hep::net::Buffer::setModel().
{
       core::json jsonStatus, jsonRun;
       m_runControl.currentRun().toJson(jsonRun);
       jsonStatus = {
         {"running", m_runControl.isRunning()},
         {"run", jsonRun}
       };
       auto model = response.createModel<std::string>();
       std::string jsonDump(jsonStatus.dump());
       model->move(std::move(jsonDump));
       response.setModel(model);
     }
void dqm4hep::online::RunControlServer::setInterface (const std::string & name)
Set the plugin name of the ouside interface.
Parameters
name the run control interface plugin name to load from the plugin manager
Definition at line 54 of file RunControlServer.cc.
{
       m_interfaceName = name;
     }
void dqm4hep::online::RunControlServer::setName (const std::string & name)
Set the run control name Must be called before run()
Parameters
name the run control name
Definition at line 42 of file RunControlServer.cc.
{
       m_runControl.setName(name);
     }
void dqm4hep::online::RunControlServer::setPassword (const std::string & password)
Set the run control password Must be called before run()
Parameters
password the run control password
Definition at line 48 of file RunControlServer.cc.
{
       m_runControl.setPassword(pwd);
     }
void dqm4hep::online::RunControlServer::setUserParameters (const dqm4hep::core::StringMap & parameters)
Set the user parameters.
Parameters
parameters the user parameters, usually extracted from cmd line
Definition at line 60 of file RunControlServer.cc.
{
       m_userParameters = parameters;
     }
void dqm4hep::online::RunControlServer::sor (dqm4hep::core::Run & run) private
Definition at line 132 of file RunControlServer.cc.
References dqm4hep::core::Run::toJson().
{
       core::json jsonRun;
       r.toJson(jsonRun);
       m_pSorService->send(jsonRun.dump());
     }
void dqm4hep::online::RunControlServer::stop ()
Stop the server.
Definition at line 122 of file RunControlServer.cc.
     {
       if(m_interface)
         m_interface->stop();
       m_stopFlag = true;
     }
Member Data Documentation
RunControlInterfacePtr dqm4hep::online::RunControlServer::m_interface = {nullptr} private
The external user plugin interface.
Definition at line 124 of file RunControlServer.h.
std::string dqm4hep::online::RunControlServer::m_interfaceName = {""} private
The external user interface plugin name.
Definition at line 127 of file RunControlServer.h.
dqm4hep::net::Service* dqm4hep::online::RunControlServer::m_pEorService = {nullptr} private
The "end of run" service.
Definition at line 123 of file RunControlServer.h.
dqm4hep::net::Service* dqm4hep::online::RunControlServer::m_pSorService = {nullptr} private
The "start of run" service.
Definition at line 122 of file RunControlServer.h.
RunControl dqm4hep::online::RunControlServer::m_runControl = {} private
The main run control.
Definition at line 120 of file RunControlServer.h.
ServerPtr dqm4hep::online::RunControlServer::m_server = {nullptr} private
The server to run.
Definition at line 121 of file RunControlServer.h.
std::atomic<bool> dqm4hep::online::RunControlServer::m_stopFlag = {false} private
The stop flag to run the server.
Definition at line 126 of file RunControlServer.h.
dqm4hep::core::StringMap dqm4hep::online::RunControlServer::m_userParameters = {} private
The user parameters.
Definition at line 125 of file RunControlServer.h.
The documentation for this class was generated from the following files:
RunControlServer.h
RunControlServer.cc