DQM4hep: dqm4hep::net::BufferModelT< std::string > Class Template Reference
dqm4hep::net::BufferModelT< std::string > Class Template Reference
BufferModelT class specialization (std::string)
#include <NetBuffer.h>
Public Member Functions
BufferModelT ()
void copy (const std::string &value)
void move (std::string &&value)
Public Member Functions inherited from dqm4hep::net::BufferModel
BufferModel ()=default
Constructor.
const RawBuffer & raw () const
Get the raw buffer.
void handle (const char *buffer, size_t size)
Handle the buffer.
Private Attributes
std::string m_value = {""}
An internal copy of the stored value as std::string.
Additional Inherited Members
Protected Attributes inherited from dqm4hep::net::BufferModel
RawBuffer m_rawBuffer = {}
The raw buffer.
Detailed Description
template<>
class dqm4hep::net::BufferModelT< std::string >
BufferModelT class specialization (std::string)
Definition at line 150 of file NetBuffer.h.
Constructor & Destructor Documentation
dqm4hep::net::BufferModelT< std::string >::BufferModelT () inline
Definition at line 152 of file NetBuffer.h.
References dqm4hep::net::RawBuffer::adopt(), dqm4hep::net::NullBuffer::buffer, dqm4hep::net::BufferModel::m_rawBuffer, dqm4hep::net::BufferModelT< T >::m_value, and dqm4hep::net::NullBuffer::size.
{
         m_value.assign(NullBuffer::buffer, NullBuffer::size);
         m_rawBuffer.adopt(m_value.c_str(), m_value.size());
       }
Member Function Documentation
void dqm4hep::net::BufferModelT< std::string >::copy (const std::string & value) inline
Definition at line 157 of file NetBuffer.h.
References dqm4hep::net::RawBuffer::adopt(), dqm4hep::net::BufferModel::m_rawBuffer, and dqm4hep::net::BufferModelT< T >::m_value.
{
         m_value = value;
         m_rawBuffer.adopt(m_value.c_str(), m_value.size());
       }
void dqm4hep::net::BufferModelT< std::string >::move (std::string && value) inline
Definition at line 162 of file NetBuffer.h.
References dqm4hep::net::RawBuffer::adopt(), dqm4hep::net::BufferModel::m_rawBuffer, and dqm4hep::net::BufferModelT< T >::m_value.
{
         m_value = std::move(value);
         m_rawBuffer.adopt(m_value.c_str(), m_value.size());
       }
Member Data Documentation
std::string dqm4hep::net::BufferModelT< std::string >::m_value = {""} private
An internal copy of the stored value as std::string.
Definition at line 168 of file NetBuffer.h.
The documentation for this class was generated from the following file:
NetBuffer.h