DQM4hep: dqm4hep::online::ModuleApi Class Reference
dqm4hep::online::ModuleApi Class Reference
ModuleApi class.
#include <ModuleApi.h>
Static Public Member Functions
static core::StatusCode cd (const Module *const module)
Go back to root directory.
static core::StatusCode cd (const Module *const module, const std::string &dirName)
Go to a specific directory.
static core::StatusCode mkdir (const Module *const module, const std::string &dirName)
Create the directory 'dirName'.
static const std::string & pwd (const Module *const module)
Get the current directory name.
static core::StatusCode goUp (const Module *const module)
Navigate backward in the directory structure.
static core::StatusCode rmdir (const Module *const module, const std::string &dirName)
Remove the directory 'dirName'.
static bool dirExists (const Module *const module, const std::string &dirName)
Whether the directory exists.
static core::StatusCode dump (const Module *const module)
Dump the monitor element storage to console.
template<typename ObjectType , typename... Args>
static core::StatusCode bookObject (const Module *const module, OnlineElementPtr &monitorElement, const std::string &path, const std::string &name, const std::string &title, Args...args)
Book a monitor element with a custom ROOT object.
template<typename HistoType , typename... Args>
static core::StatusCode bookHisto (const Module *const module, OnlineElementPtr &monitorElement, const std::string &path, const std::string &name, const std::string &title, Args...args)
Book a monitor element with a ROOT histogram handled (anything inheriting from TH1).
template<typename ScalarType , typename... Args>
static core::StatusCode bookScalar (const Module *const module, OnlineElementPtr &monitorElement, const std::string &path, const std::string &name, const std::string &title, Args...args)
Book a monitor element handling a scalar value (the real type is TScalarObject<T>).
static core::StatusCode getMonitorElements (const Module *const module, OnlineElementPtrList &monitorElementList)
Get all the monitor elements already booked by this module in all the directories.
static core::StatusCode getMonitorElement (const Module *const module, const std::string &monitorElementName, OnlineElementPtr &monitorElement)
Get the monitor element in the current directory (result by ptr reference)
static core::StatusCode getMonitorElement (const Module *const module, const std::string &dirName, const std::string &monitorElementName, OnlineElementPtr &monitorElement)
Get the monitor element in the given directory (result by ptr reference)
static OnlineElementPtr getMonitorElement (const Module *const module, const std::string &monitorElementName)
Get the monitor element in the current directory.
static OnlineElementPtr getMonitorElement (const Module *const module, const std::string &dirName, const std::string &monitorElementName)
Get the monitor element in the given directory.
static core::StatusCode resetMonitorElements (const Module *const module)
Reset all the monitor elements of this module.
static core::StatusCode addQualityTest (const Module *const module, OnlineElementPtr monitorElement, const std::string &qualityTestName)
Add a pre-booked quality test to a particular monitor element.
Static Private Member Functions
static core::StatusCode checkModule (const Module *const module)
Check module validity.
Detailed Description
ModuleApi class.
Responsible for direct operation on module application and modules such as monitor element booking and directory navigation. Monitor element booking should be done via a Module
Definition at line 35 of file ModuleApi.h.
Member Function Documentation
core::StatusCode dqm4hep::online::ModuleApi::addQualityTest (const Module *const module, OnlineElementPtr monitorElement, const std::string & qualityTestName) static
Add a pre-booked quality test to a particular monitor element.
Parameters
module the user module calling this method
monitorElement the monitor element to attach the quality test
qualityTestName the quality test name to attach
Definition at line 130 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       return module->moduleApplication()->monitorElementManager()->addQualityTest(monitorElement->path(), monitorElement->name(), qualityTestName);
     }
template<typename HistoType , typename... Args> core::StatusCode dqm4hep::online::ModuleApi::bookHisto (const Module *const module, OnlineElementPtr & monitorElement, const std::string & path, const std::string & name, const std::string & title, Args... args) inline static
Book a monitor element with a ROOT histogram handled (anything inheriting from TH1).
The arguments 'args' are the ones passed in the TH1 constructors after the name and title. For example:
OnlineElementPtr element;
ModuleApi::bookHisto<TH1F>(this, element, "/", "MyHisto", "A title", 100, 0, 99);
books a TH1F object with 100 bins from 0 to 99
Parameters
module the user module calling this method
monitorElement the monitor element to receive
path the monitor element directory
name the monitor element name
title the monitor element title
args the arguments to pass in the object constructor (optional)
Definition at line 273 of file ModuleApi.h.
References dqm4hep::online::ModuleApplication::allowBooking(), checkModule(), dqm_error, dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), dqm4hep::online::Module::name(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       if(not module->moduleApplication()->allowBooking()) {
         dqm_error( "Module application allows monitor element booking only in readSettings() or init() functions !" );
         return core::STATUS_CODE_NOT_ALLOWED;
       }
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, module->moduleApplication()->monitorElementManager()->bookHisto<HistoType>(path, name, title, monitorElement, args...));
       monitorElement->setModuleName(module->name());
       return core::STATUS_CODE_SUCCESS;
     }
template<typename ObjectType , typename... Args> core::StatusCode dqm4hep::online::ModuleApi::bookObject (const Module *const module, OnlineElementPtr & monitorElement, const std::string & path, const std::string & name, const std::string & title, Args... args) inline static
Book a monitor element with a custom ROOT object.
For histograms and scalars see below.
The arguments 'args' are directly passed to the object constructor, so that you have simple cases without arguments such as:
OnlineElementPtr graphElement;
ModuleApi::bookObject<TGraph>(this, graphElement, "/", "MyGraph", "A title");
or more complicated cases with custom arguments such as:
const Int_t nPoints = 5;
Float_t x[] = {0, 2, 4, 9, 15};
Float_t y[] = {4, 12, 7, 14, 75};
OnlineElementPtr graphElement;
ModuleApi::bookObject<TGraph>(this, graphElement, "/", "MyGraph", "A title", nPoints, x, y);
Parameters
module the user module calling this method
monitorElement the monitor element to receive
path the monitor element directory
name the monitor element name
title the monitor element title
args the arguments to pass in the object constructor (optional)
Definition at line 259 of file ModuleApi.h.
References dqm4hep::online::ModuleApplication::allowBooking(), checkModule(), dqm_error, dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), dqm4hep::online::Module::name(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       if(not module->moduleApplication()->allowBooking()) {
         dqm_error( "Module application allows monitor element booking only in readSettings() or init() functions !" );
         return core::STATUS_CODE_NOT_ALLOWED;
       }
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, module->moduleApplication()->monitorElementManager()->bookObject<ObjectType>(path, name, title, monitorElement, args...));
       monitorElement->setModuleName(module->name());
       return core::STATUS_CODE_SUCCESS;
     }
template<typename ScalarType , typename... Args> core::StatusCode dqm4hep::online::ModuleApi::bookScalar (const Module *const module, OnlineElementPtr & monitorElement, const std::string & path, const std::string & name, const std::string & title, Args... args) inline static
Book a monitor element handling a scalar value (the real type is TScalarObject<T>).
The template parameter ScalarType must be a C++ builtin type like in, float, etc ... For example:
OnlineElementPtr element;
ModuleApi::bookScalar<int>(this, element, "/", "MyScalar", "The answer", 42);
books a TScalarInt object with an initial value of 42.
Parameters
module the user module calling this method
monitorElement the monitor element to receive
path the monitor element directory
name the monitor element name
title the monitor element title
args the arguments to pass in the object constructor (optional)
Definition at line 287 of file ModuleApi.h.
References dqm4hep::online::ModuleApplication::allowBooking(), checkModule(), dqm_error, dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), dqm4hep::online::Module::name(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       if(not module->moduleApplication()->allowBooking()) {
         dqm_error( "Module application allows monitor element booking only in readSettings() or init() functions !" );
         return core::STATUS_CODE_NOT_ALLOWED;
       }
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, module->moduleApplication()->monitorElementManager()->bookScalar<ScalarType>(path, name, title, monitorElement, args...));
       monitorElement->setModuleName(module->name());
       return core::STATUS_CODE_SUCCESS;
     }
core::StatusCode dqm4hep::online::ModuleApi::cd (const Module *const module) static
Go back to root directory.
Parameters
module the user module calling this method
Definition at line 21 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
Referenced by dqm4hep::online::TestAnalysisModule::initModule(), and dqm4hep::online::TestStandaloneModule::initModule().
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       module->moduleApplication()->monitorElementManager()->cd();
       return core::STATUS_CODE_SUCCESS;
     }
core::StatusCode dqm4hep::online::ModuleApi::cd (const Module *const module, const std::string & dirName) static
Go to a specific directory.
Parameters
module the user module calling this method
dirName the directory to enter
Definition at line 29 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       return module->moduleApplication()->monitorElementManager()->cd(dirName);
     }
core::StatusCode dqm4hep::online::ModuleApi::checkModule (const Module *const module) static private
Check module validity.
Parameters
module the user module calling this method
Definition at line 137 of file ModuleApi.cc.
References dqm_error, and dqm4hep::online::Module::moduleApplication().
Referenced by addQualityTest(), bookHisto(), bookObject(), bookScalar(), cd(), dirExists(), dump(), getMonitorElement(), getMonitorElements(), goUp(), mkdir(), pwd(), resetMonitorElements(), and rmdir().
{
       if(nullptr == module) {
         dqm_error( "ModuleApi::checkModule: module is nullptr!" );
         return core::STATUS_CODE_INVALID_PTR;
       }
       if(nullptr == module->moduleApplication()) {
         dqm_error( "ModuleApi::checkModule: module application is nullptr!" );
         return core::STATUS_CODE_NOT_INITIALIZED;
       }
       return core::STATUS_CODE_SUCCESS;
     }
bool dqm4hep::online::ModuleApi::dirExists (const Module *const module, const std::string & dirName) static
Whether the directory exists.
Parameters
module the user module calling this method
dirName the directory name to check
Definition at line 64 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and THROW_RESULT_IF.
{
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       return module->moduleApplication()->monitorElementManager()->dirExists(dirName);
     }
core::StatusCode dqm4hep::online::ModuleApi::dump (const Module *const module) static
Dump the monitor element storage to console.
Definition at line 71 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
Referenced by dqm4hep::online::TestAnalysisModule::initModule(), and dqm4hep::online::TestStandaloneModule::initModule().
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       module->moduleApplication()->monitorElementManager()->dumpStorage();
       return core::STATUS_CODE_SUCCESS;
     }
core::StatusCode dqm4hep::online::ModuleApi::getMonitorElement (const Module *const module, const std::string & monitorElementName, OnlineElementPtr & monitorElement) static
Get the monitor element in the current directory (result by ptr reference)
Parameters
module the user module calling this method
monitorElementName the monitor element name
monitorElement the monitor element to receive
Definition at line 88 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       return module->moduleApplication()->monitorElementManager()->getMonitorElement(monitorElementName, monitorElement);
     }
core::StatusCode dqm4hep::online::ModuleApi::getMonitorElement (const Module *const module, const std::string & dirName, const std::string & monitorElementName, OnlineElementPtr & monitorElement) static
Get the monitor element in the given directory (result by ptr reference)
Parameters
module the user module calling this method
dirName the monitor element path
monitorElementName the monitor element name
monitorElement the monitor element to receive
Definition at line 95 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       return module->moduleApplication()->monitorElementManager()->getMonitorElement(dirName, monitorElementName, monitorElement);
     }
OnlineElementPtr dqm4hep::online::ModuleApi::getMonitorElement (const Module *const module, const std::string & monitorElementName) static
Get the monitor element in the current directory.
Parameters
module the user module calling this method
monitorElementName the monitor element name
Definition at line 102 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and THROW_RESULT_IF.
{
       OnlineElementPtr monitorElement;
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, module->moduleApplication()->monitorElementManager()->getMonitorElement(monitorElementName, monitorElement));
       return monitorElement;
     }
OnlineElementPtr dqm4hep::online::ModuleApi::getMonitorElement (const Module *const module, const std::string & dirName, const std::string & monitorElementName) static
Get the monitor element in the given directory.
The element is directly returned without any ptr check
Parameters
module the user module calling this method
dirName the monitor element path
monitorElementName the monitor element name
Definition at line 111 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and THROW_RESULT_IF.
{
       OnlineElementPtr monitorElement;
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, module->moduleApplication()->monitorElementManager()->getMonitorElement(dirName, monitorElementName, monitorElement));
       return monitorElement;
     }
core::StatusCode dqm4hep::online::ModuleApi::getMonitorElements (const Module *const module, OnlineElementPtrList & monitorElementList) static
Get all the monitor elements already booked by this module in all the directories.
Parameters
module the user module calling this method
monitorElementList the monitor element list to receive
Definition at line 80 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       module->moduleApplication()->monitorElementManager()->getMonitorElements(monitorElementList);
       return core::STATUS_CODE_SUCCESS;
     }
core::StatusCode dqm4hep::online::ModuleApi::goUp (const Module *const module) static
Navigate backward in the directory structure.
Parameters
module the user module calling this method
Definition at line 50 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       return module->moduleApplication()->monitorElementManager()->goUp();
     }
core::StatusCode dqm4hep::online::ModuleApi::mkdir (const Module *const module, const std::string & dirName) static
Create the directory 'dirName'.
Parameters
module the user module calling this method
dirName the directory name to create
Definition at line 36 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
Referenced by dqm4hep::online::TestAnalysisModule::initModule(), and dqm4hep::online::TestStandaloneModule::initModule().
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       return module->moduleApplication()->monitorElementManager()->mkdir(dirName);
     }
const std::string & dqm4hep::online::ModuleApi::pwd (const Module *const module) static
Get the current directory name.
Parameters
module the user module calling this method
Definition at line 43 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and THROW_RESULT_IF.
{
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       return module->moduleApplication()->monitorElementManager()->pwd();
     }
core::StatusCode dqm4hep::online::ModuleApi::resetMonitorElements (const Module *const module) static
Reset all the monitor elements of this module.
Parameters
module the user module calling this method
Definition at line 121 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       module->moduleApplication()->monitorElementManager()->resetMonitorElements();
       return core::STATUS_CODE_SUCCESS;
     }
core::StatusCode dqm4hep::online::ModuleApi::rmdir (const Module *const module, const std::string & dirName) static
Remove the directory 'dirName'.
Parameters
module the user module calling this method
dirName the directory name to remove
Definition at line 57 of file ModuleApi.cc.
References checkModule(), dqm4hep::online::Module::moduleApplication(), dqm4hep::online::ModuleApplication::monitorElementManager(), and RETURN_RESULT_IF.
{
       RETURN_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::checkModule(module));
       return module->moduleApplication()->monitorElementManager()->rmdir(dirName);
     }
The documentation for this class was generated from the following files:
ModuleApi.h
ModuleApi.cc