DQM4hep: dqm4hep::online::EventCollector Class Reference
dqm4hep::online::EventCollector Class Reference
EventCollector class.
#include <EventCollector.h>
Classes
struct SourceInfo
SourceInfo struct.
Public Member Functions
EventCollector ()
Default constructor.
EventCollector (const EventCollector &)=delete
EventCollector & operator= (const EventCollector &)=delete
~EventCollector ()
Default destructor.
void parseCmdLine (int argc, char **argv) override
Parse the command line arguments.
void onInit () override
Custom application initialization function.
void onEvent (AppEvent *pAppEvent) override
Process an event from the event loop.
void onStart () override
Custom user function called just before starting the event loop.
void onStop () override
Custom user function called just after exiting the event loop.
Public Member Functions inherited from dqm4hep::online::Application
Application ()=default
Default constructor.
Application (const Application &)=delete
Application & operator= (const Application &)=delete
virtual ~Application ()
Destructor.
const std::string & type () const
Get the application type.
void setType (const std::string &type)
Set the application type.
const std::string & name () const
Get the application name.
void setName (const std::string &name)
Set the application name Throw exception if called after init() is called.
const std::string & state () const
Get the application state.
void setState (const std::string &state)
Change the application state.
core::Logger::Level logLevel () const
Get the application log level.
void setLogLevel (core::Logger::Level lvl)
Get the application log level.
void createStatsEntry (const std::string &name, const std::string &unit, const std::string &description)
Create a statistics entry.
template<typename T >
void sendStat (const std::string &name, const T &stats)
Send the stat entry with a new value.
void enableStats (bool enable)
Set whether to send statistics on update.
bool statsEnabled () const
Whether the statistics are enabled.
void setNoServer (bool nosrv)
Enable or disable running the application server.
bool noServer () const
Whether the server has been disabled.
void init (int argc, char **argv)
Initialize the application.
int exec ()
Run the application.
void exit (int returnCode)
Exit the application with the specified return code If the application is running with exec(), exec will return the specified code.
bool initialized () const
Whether the application has been initialized.
bool running () const
Whether the application is running.
template<typename T >
void sendCommand (const std::string &name, const T &contents, bool blocking=false) const
Client interface.
template<typename Operation >
void sendRequest (const std::string &name, const net::Buffer &request, Operation operation)
Send a request using the net client interface.
void queuedSubscribe (const std::string &serviceName, int priority=50, int maxNEvents=std::numeric_limits< int >::max())
Subscribe to service.
template<typename Controller >
void directSubscribe (const std::string &serviceName, Controller *controller, void(Controller::*function)(const net::Buffer &))
Subscribe to service.
net::Service * createService (const std::string &name)
Server interface.
template<typename Controller >
void createRequestHandler (const std::string &requestName, Controller *controller, void(Controller::*function)(const net::Buffer &, net::Buffer &))
Create a request handler.
void createQueuedCommand (const std::string &commandName, int priority=50, int maxNEvents=std::numeric_limits< int >::max())
Create a command handler.
template<typename Controller >
void createDirectCommand (const std::string &commandName, Controller *controller, void(Controller::*function)(const net::Buffer &))
Create a command handler.
int serverClientId () const
Get the current server client id.
void sendClientExitEvent (int clientId)
Send a client exit event in the event loop.
AppTimer * createTimer ()
Create a timer synchronized with the event loop The allocated timer has to be removed by calling removeTimer()
void removeTimer (AppTimer *timer)
Remove timer.
Private Types
typedef std::map< std::string,
SourceInfo > SourceInfoMap
Private Member Functions
void handleRegistration (const net::Buffer &request, net::Buffer &response)
void handleClientExit (StoreEvent< int > *event)
void handleCollectEvent (const net::Buffer &buffer)
void handleClientUnregistration (const net::Buffer &buffer)
void handleEventRequest (const net::Buffer &request, net::Buffer &response)
void sendStatsTimer10 ()
void sendStatsTimer60 ()
void printSourceMap ()
Private Attributes
std::shared_ptr< TCLAP::CmdLine > m_cmdLine = nullptr
SourceInfoMap m_sourceInfoMap = {}
core::time::point m_lastStatCall10 = {}
core::time::point m_lastStatCall60 = {}
unsigned int m_nCollectedEvents10 = {0}
unsigned int m_nCollectedEvents60 = {0}
unsigned int m_nCollectedBytes10 = {0}
unsigned int m_nCollectedBytes60 = {0}
AppTimer * m_statsTimer10 = {nullptr}
AppTimer * m_statsTimer60 = {nullptr}
Additional Inherited Members
Protected Attributes inherited from dqm4hep::online::Application
AppEventLoop m_eventLoop = {}
The application event loop.
Detailed Description
EventCollector class.
Definition at line 30 of file EventCollector.h.
Member Typedef Documentation
typedef std::map<std::string, SourceInfo> dqm4hep::online::EventCollector::SourceInfoMap private
Definition at line 79 of file EventCollector.h.
Constructor & Destructor Documentation
dqm4hep::online::EventCollector::EventCollector ()
Default constructor.
Definition at line 21 of file EventCollector.cc.
                                    :
       Application() {
     }
dqm4hep::online::EventCollector::EventCollector (const EventCollector &) delete
dqm4hep::online::EventCollector::~EventCollector ()
Default destructor.
Definition at line 27 of file EventCollector.cc.
References m_statsTimer10, m_statsTimer60, and dqm4hep::online::Application::removeTimer().
{
       removeTimer(m_statsTimer10);
       removeTimer(m_statsTimer60);
     }
Member Function Documentation
void dqm4hep::online::EventCollector::handleClientExit (StoreEvent< int > * event) private
Definition at line 200 of file EventCollector.cc.
References dqm4hep::online::StoreEvent< T >::data(), dqm_info, m_sourceInfoMap, and dqm4hep::online::Application::sendStat().
Referenced by onEvent().
{
       const int clientId(event->data());
       auto findIter = std::find_if(m_sourceInfoMap.begin(), m_sourceInfoMap.end(), [&clientId](const SourceInfoMap::value_type &iter){
         return (iter.second.m_clientId == clientId);
       });
       if(findIter != m_sourceInfoMap.end()) {
         dqm_info( "Removing event source '{0}' from source list !", findIter->second.m_name );
         m_sourceInfoMap.erase(findIter);
         sendStat("NSources", m_sourceInfoMap.size());
       }
     }
void dqm4hep::online::EventCollector::handleClientUnregistration (const net::Buffer & buffer) private
Definition at line 239 of file EventCollector.cc.
References dqm_info, m_sourceInfoMap, dqm4hep::online::Application::sendStat(), and dqm4hep::online::Application::serverClientId().
Referenced by onInit().
{
       const int clientId(serverClientId());
       auto findIter = std::find_if(m_sourceInfoMap.begin(), m_sourceInfoMap.end(), [&clientId](const SourceInfoMap::value_type &iter){
         return (iter.second.m_clientId == clientId);
       });
       if(findIter != m_sourceInfoMap.end()) {
         dqm_info( "Removing event source '{0}' from source list !", findIter->second.m_name );
         m_sourceInfoMap.erase(findIter);
         sendStat("NSources", m_sourceInfoMap.size());
       }
     }
void dqm4hep::online::EventCollector::handleCollectEvent (const net::Buffer & buffer) private
Definition at line 215 of file EventCollector.cc.
References dqm4hep::net::Buffer::begin(), m_nCollectedBytes10, m_nCollectedBytes60, m_nCollectedEvents10, m_nCollectedEvents60, m_sourceInfoMap, dqm4hep::online::Application::serverClientId(), and dqm4hep::net::Buffer::size().
Referenced by onInit().
{
       const int clientId(serverClientId());
       auto findIter = std::find_if(m_sourceInfoMap.begin(), m_sourceInfoMap.end(), [&clientId](const SourceInfoMap::value_type &iter){
         return (iter.second.m_clientId == clientId);
       });
       if(findIter != m_sourceInfoMap.end()) {
         std::string copiedBuffer(buffer.begin(), buffer.size());
         auto newModel = findIter->second.m_buffer.createModel<std::string>();
         findIter->second.m_buffer.setModel(newModel);
         newModel->move(std::move(copiedBuffer));
         m_nCollectedEvents10++;
         m_nCollectedEvents60++;
         m_nCollectedBytes10 += buffer.size();
         m_nCollectedBytes60 += buffer.size();
         // send update
         findIter->second.m_eventService->sendBuffer(buffer.begin(), buffer.size());
       }
     }
void dqm4hep::online::EventCollector::handleEventRequest (const net::Buffer & request, net::Buffer & response) private
Definition at line 254 of file EventCollector.cc.
References dqm4hep::net::Buffer::begin(), m_sourceInfoMap, dqm4hep::net::Buffer::setModel(), and dqm4hep::net::Buffer::size().
Referenced by onInit().
{
       std::string sourceName(request.begin(), request.size());
       auto findIter = m_sourceInfoMap.find(sourceName);
       if(m_sourceInfoMap.end() != findIter) {
         response.setModel(findIter->second.m_buffer.model());
       }
     }
void dqm4hep::online::EventCollector::handleRegistration (const net::Buffer & request, net::Buffer & response) private
Definition at line 140 of file EventCollector.cc.
References dqm4hep::net::Buffer::begin(), dqm4hep::net::Buffer::createModel(), dqm4hep::online::Application::createService(), dqm_info, dqm4hep::net::Buffer::end(), dqm4hep::online::OnlineRoutes::EventCollector::eventUpdate(), m_sourceInfoMap, dqm4hep::online::Application::name(), dqm4hep::online::Application::sendStat(), dqm4hep::online::Application::serverClientId(), dqm4hep::net::Buffer::setModel(), and dqm4hep::net::Buffer::size().
Referenced by onInit().
{
       core::json registrationDetails({});
       if(0 != request.size()) {
         registrationDetails = core::json::parse(request.begin(), request.end());
       }
       auto clientSourceName = registrationDetails.value<std::string>("source", "");
       auto clientId = this->serverClientId();
       auto findIter = m_sourceInfoMap.find(clientSourceName);
       core::json clientResponseValue({});
       // source already registered
       if(m_sourceInfoMap.end() != findIter) {
         if(clientId == findIter->second.m_clientId) {
           clientResponseValue["message"] = "Event source already registered !";
           clientResponseValue["registered"] = true;
         }
         else {
           std::stringstream ss; ss << "Event source already registered with a different client ID (" << findIter->second.m_clientId << ") !";
           clientResponseValue["message"] = ss.str();
           clientResponseValue["registered"] = false;
         }
       }
       // source not registered yet
       else {
         std::string sourceName = registrationDetails.value<std::string>("source", "");
         SourceInfo sourceInfo;
         findIter = m_sourceInfoMap.insert(SourceInfoMap::value_type(sourceName, std::move(sourceInfo))).first;
         findIter->second.m_clientId = clientId;
         findIter->second.m_name = registrationDetails.value<std::string>("source", "");
         findIter->second.m_streamerName = registrationDetails.value<std::string>("streamer", "");
         findIter->second.m_eventService = createService(OnlineRoutes::EventCollector::eventUpdate(name(), findIter->first));
         auto collectors = registrationDetails["collectors"];
         auto hostInfo = registrationDetails["host"];
         for(auto collector : collectors) {
           findIter->second.m_collectors.push_back(collector.get<std::string>());
         }
         for(auto hostInfoIter : hostInfo.items()) {
           findIter->second.m_hostInfo[hostInfoIter.key()] = hostInfo[hostInfoIter.key()].get<std::string>();
         }
         auto model = findIter->second.m_buffer.createModel<std::string>();
         findIter->second.m_buffer.setModel(model);
         dqm_info( "New event source '{0}' registered with client id {1}", findIter->second.m_name, findIter->second.m_clientId );
         clientResponseValue["registered"] = true;
         sendStat("NSources", m_sourceInfoMap.size());
       }
       auto model = response.createModel<std::string>();
       model->copy(clientResponseValue.dump());
       response.setModel(model);
     }
void dqm4hep::online::EventCollector::onEvent (AppEvent * pAppEvent) override virtual
Process an event from the event loop.
Parameters
pAppEvent the event to process
Implements dqm4hep::online::Application.
Definition at line 121 of file EventCollector.cc.
References dqm4hep::online::AppEvent::CLIENT_EXIT, handleClientExit(), and dqm4hep::online::AppEvent::type().
{
       if(pAppEvent->type() == AppEvent::CLIENT_EXIT) {
         auto exitEvent = dynamic_cast<StoreEvent<int>*>(pAppEvent);
         this->handleClientExit(exitEvent);
       }
     }
void dqm4hep::online::EventCollector::onInit () override virtual
Custom application initialization function.
At this step the server is created but is not yet running. This is the place where the application should create:
all needed services
all stats entries
Implements dqm4hep::online::Application.
Definition at line 70 of file EventCollector.cc.
References dqm4hep::online::OnlineRoutes::EventCollector::collectEvent(), dqm4hep::core::Signal< Args >::connect(), dqm4hep::online::Application::createDirectCommand(), dqm4hep::online::Application::createRequestHandler(), dqm4hep::online::Application::createStatsEntry(), dqm4hep::online::Application::createTimer(), dqm4hep::online::OnlineRoutes::EventCollector::eventRequest(), handleClientUnregistration(), handleCollectEvent(), handleEventRequest(), handleRegistration(), m_lastStatCall10, m_lastStatCall60, m_statsTimer10, m_statsTimer60, dqm4hep::online::Application::name(), dqm4hep::core::time::now(), dqm4hep::online::AppTimer::onTimeout(), dqm4hep::online::OnlineRoutes::EventCollector::registerSource(), sendStatsTimer10(), sendStatsTimer60(), dqm4hep::online::AppTimer::setInterval(), dqm4hep::online::AppTimer::setSingleShot(), dqm4hep::online::AppTimer::start(), and dqm4hep::online::OnlineRoutes::EventCollector::unregisterSource().
{
       // create network services
       createRequestHandler(
         OnlineRoutes::EventCollector::registerSource(name()),
         this,
         &EventCollector::handleRegistration
       );
       createRequestHandler(
         OnlineRoutes::EventCollector::eventRequest(name()),
         this,
         &EventCollector::handleEventRequest
       );
       createDirectCommand(
         OnlineRoutes::EventCollector::unregisterSource(name()),
         this,
         &EventCollector::handleClientUnregistration
       );
       createDirectCommand(
         OnlineRoutes::EventCollector::collectEvent(name()),
         this,
         &EventCollector::handleCollectEvent
       );
       // create statistics entries
       createStatsEntry("NSources", "", "The current number of registered sources");
       createStatsEntry("NEvents_60sec", "1/min", "The number of collected events within the last minute");
       createStatsEntry("NEvents_10sec", "1/10 sec", "The number of collected events within the last 10 secondes");
       createStatsEntry("NBytes_60sec", "bytes", "The total number of collected bytes within the last minute");
       createStatsEntry("NBytes_10sec", "bytes", "The total number of collected bytes within the last 10 secondes");
       createStatsEntry("NMeanBytes_60sec", "bytes/min", "The mean number of collected bytes within the last minute");
       createStatsEntry("NMeanBytes_10sec", "bytes/10 sec", "The mean number of collected bytes within the last 10 secondes");
       // app stats timers
       m_statsTimer10 = createTimer();
       m_statsTimer10->setInterval(10000);
       m_statsTimer10->setSingleShot(false);
       m_statsTimer10->onTimeout().connect(this, &EventCollector::sendStatsTimer10);
       m_statsTimer60 = createTimer();
       m_statsTimer60->setInterval(60000);
       m_statsTimer60->setSingleShot(false);
       m_statsTimer60->onTimeout().connect(this, &EventCollector::sendStatsTimer60);
       m_lastStatCall10 = core::time::now();
       m_lastStatCall60 = core::time::now();
       m_statsTimer10->start();
       m_statsTimer60->start();
     }
void dqm4hep::online::EventCollector::onStart () override virtual
Custom user function called just before starting the event loop.
At this step the internal server is already running. This function may e.g send an initial event to the event loop.
Implements dqm4hep::online::Application.
Definition at line 130 of file EventCollector.cc.
{
     }
void dqm4hep::online::EventCollector::onStop () override virtual
Custom user function called just after exiting the event loop.
Implements dqm4hep::online::Application.
Definition at line 135 of file EventCollector.cc.
{
     }
EventCollector& dqm4hep::online::EventCollector::operator= (const EventCollector &) delete
void dqm4hep::online::EventCollector::parseCmdLine (int argc, char ** argv) override virtual
Parse the command line arguments.
After parsing the cmd line, the application must provide a valid type and name. At this step the server is not yet created.
Parameters
argc the argc argument from the main function
argc the argv argument from the main function
Implements dqm4hep::online::Application.
Definition at line 34 of file EventCollector.cc.
References dqm4hep::online::OnlineRoutes::EventCollector::applicationType(), DQM4hep_VERSION_STR, dqm4hep::core::Logger::logLevelFromString(), dqm4hep::core::Logger::logLevels(), m_cmdLine, dqm4hep::online::Application::setLogLevel(), dqm4hep::online::Application::setName(), and dqm4hep::online::Application::setType().
{
       std::string cmdLineFooter = "Please report bug to <dqm4hep@gmail.com>";
       m_cmdLine = std::make_shared<TCLAP::CmdLine>(cmdLineFooter, ' ', DQM4hep_VERSION_STR);
       TCLAP::ValueArg<std::string> collectorNameArg(
           "c"
           , "collector-name"
           , "The event collector name"
           , true
           , ""
           , "string");
       m_cmdLine->add(collectorNameArg);
       core::StringVector verbosities(core::Logger::logLevels());
       TCLAP::ValuesConstraint<std::string> verbosityConstraint(verbosities);
       TCLAP::ValueArg<std::string> verbosityArg(
           "v"
           , "verbosity"
           , "The logging verbosity"
           , false
           , "info"
           , &verbosityConstraint);
       m_cmdLine->add(verbosityArg);
       // parse command line
       m_cmdLine->parse(argc, argv);
       std::string verbosity(verbosityArg.getValue());
       std::string collectorName(collectorNameArg.getValue());
       setType(OnlineRoutes::EventCollector::applicationType());
       setName(collectorName);
       setLogLevel(core::Logger::logLevelFromString(verbosity));
     }
void dqm4hep::online::EventCollector::printSourceMap () private
Definition at line 292 of file EventCollector.cc.
References dqm_debug, and m_sourceInfoMap.
{
       for(auto &source : m_sourceInfoMap) {
         dqm_debug( "== Source '{0}' ==", source.first );
         dqm_debug( "     Client id: '{0}' ==", source.second.m_clientId );
         dqm_debug( "     Streamer:  '{0}' ==", source.second.m_streamerName );
       }
     }
void dqm4hep::online::EventCollector::sendStatsTimer10 () private
Definition at line 264 of file EventCollector.cc.
References m_lastStatCall10, m_nCollectedBytes10, m_nCollectedEvents10, dqm4hep::core::time::now(), and dqm4hep::online::Application::sendStat().
Referenced by onInit().
{
       auto timeDifference = std::chrono::duration_cast<std::chrono::milliseconds>(core::time::now()-m_lastStatCall10).count();
       // send stats
       sendStat("NEvents_10sec", m_nCollectedEvents10);
       sendStat("NBytes_10sec", m_nCollectedBytes10);
       sendStat("NMeanBytes_10sec", m_nCollectedBytes10 / (timeDifference/1000.));
       // reset counters
       m_nCollectedEvents10 = 0;
       m_nCollectedBytes10 = 0;
       m_lastStatCall10 = core::time::now();
     }
void dqm4hep::online::EventCollector::sendStatsTimer60 () private
Definition at line 278 of file EventCollector.cc.
References m_lastStatCall60, m_nCollectedBytes60, m_nCollectedEvents60, dqm4hep::core::time::now(), and dqm4hep::online::Application::sendStat().
Referenced by onInit().
{
       auto timeDifference = std::chrono::duration_cast<std::chrono::milliseconds>(core::time::now()-m_lastStatCall60).count();
       // send stats
       sendStat("NEvents_60sec", m_nCollectedEvents60);
       sendStat("NBytes_60sec", m_nCollectedBytes60);
       sendStat("NMeanBytes_60sec", m_nCollectedBytes60 / (timeDifference/1000.));
       // reset counters
       m_nCollectedEvents60 = 0;
       m_nCollectedBytes60 = 0;
       m_lastStatCall60 = core::time::now();
     }
Member Data Documentation
std::shared_ptr<TCLAP::CmdLine> dqm4hep::online::EventCollector::m_cmdLine = nullptr private
Definition at line 81 of file EventCollector.h.
Referenced by parseCmdLine().
core::time::point dqm4hep::online::EventCollector::m_lastStatCall10 = {} private
Definition at line 83 of file EventCollector.h.
Referenced by onInit(), and sendStatsTimer10().
core::time::point dqm4hep::online::EventCollector::m_lastStatCall60 = {} private
Definition at line 84 of file EventCollector.h.
Referenced by onInit(), and sendStatsTimer60().
unsigned int dqm4hep::online::EventCollector::m_nCollectedBytes10 = {0} private
Definition at line 87 of file EventCollector.h.
Referenced by handleCollectEvent(), and sendStatsTimer10().
unsigned int dqm4hep::online::EventCollector::m_nCollectedBytes60 = {0} private
Definition at line 88 of file EventCollector.h.
Referenced by handleCollectEvent(), and sendStatsTimer60().
unsigned int dqm4hep::online::EventCollector::m_nCollectedEvents10 = {0} private
Definition at line 85 of file EventCollector.h.
Referenced by handleCollectEvent(), and sendStatsTimer10().
unsigned int dqm4hep::online::EventCollector::m_nCollectedEvents60 = {0} private
Definition at line 86 of file EventCollector.h.
Referenced by handleCollectEvent(), and sendStatsTimer60().
SourceInfoMap dqm4hep::online::EventCollector::m_sourceInfoMap = {} private
Definition at line 82 of file EventCollector.h.
Referenced by handleClientExit(), handleClientUnregistration(), handleCollectEvent(), handleEventRequest(), handleRegistration(), and printSourceMap().
AppTimer* dqm4hep::online::EventCollector::m_statsTimer10 = {nullptr} private
Definition at line 89 of file EventCollector.h.
Referenced by onInit(), and ~EventCollector().
AppTimer* dqm4hep::online::EventCollector::m_statsTimer60 = {nullptr} private
Definition at line 90 of file EventCollector.h.
Referenced by onInit(), and ~EventCollector().
The documentation for this class was generated from the following files:
EventCollector.h
EventCollector.cc