DQM4hep: dqm4hep::online::OnlineRoutes::ModuleApplication Class Reference
dqm4hep::online::OnlineRoutes::ModuleApplication Class Reference
ModuleApplication class Defines routes related to module application.
#include <OnlineRoutes.h>
Static Public Member Functions
static const std::string applicationType ()
Get the application type.
static const std::string subscribe (const std::string &moduleName)
Get the name of the command to receive (module) or send (client) a new monitor element subscription list.
Detailed Description
ModuleApplication class Defines routes related to module application.
Definition at line 169 of file OnlineRoutes.h.
Member Function Documentation
const std::string dqm4hep::online::OnlineRoutes::ModuleApplication::applicationType () static
Get the application type.
Definition at line 117 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::ModuleApplication::parseCmdLine().
{
       return "module";
     }
const std::string dqm4hep::online::OnlineRoutes::ModuleApplication::subscribe (const std::string & moduleName) static
Get the name of the command to receive (module) or send (client) a new monitor element subscription list.
Parameters
moduleName the module name of the aplication
Definition at line 123 of file OnlineRoutes.cc.
References dqm4hep::online::OnlineRoutes::Application::serverName().
Referenced by dqm4hep::online::ModuleApplication::onEvent(), and dqm4hep::online::ModuleApplication::onInit().
{
       return OnlineRoutes::Application::serverName(applicationType(), moduleName) + "/subscribe";
     }
The documentation for this class was generated from the following files:
OnlineRoutes.h
OnlineRoutes.cc