DQM4hep: dqm4hep::core::XMLParser Class Reference
dqm4hep::core::XMLParser Class Reference
XMLParser class.
#include <XMLParser.h>
Public Member Functions
XMLParser ()
Constructor.
void parse (const std::string &fname)
Parse the xml file.
const std::string & fileName () const
Get the last parsed file name.
const StringMap & constants () const
Get the constants map.
template<typename T >
T constantAs (const std::string &name, const T &fallback=T()) const
Get a constant value to specified type.
const TiXmlDocument & document () const
Get the xml document.
TiXmlDocument & document ()
Get the xml document.
void reset ()
Reset the parser: clear the constants and the xml document.
void setProcessIncludes (bool process)
Set whether to process element while parsing.
bool processIncludes () const
Whether to process elements.
void setAllowNestedIncludes (bool allow)
Set whether to allow nested elements, meaning include elements in included files.
bool allowNestedIncludes () const
Whether to allow nested elements meaning include elements in included files.
void setProcessConstants (bool process)
Set whether to process constants sections while parsing.
bool processConstants () const
Whether to process constants sections while parsing.
void setProcessDatabase (bool process)
Set whether to process <database> elements.
bool processDatabase () const
Whether to process <database> elements.
void setAllowEnvVariables (bool allow)
Set whether to allow the use of environment variable while resolving constants.
bool allowEnvVariables () const
Whether to allow the use of environment variable while resolving constants.
void setProcessForLoops (bool process)
Set whether to process XML for loop elements.
bool processForLoops () const
Whether to process XML for loop elements.
Private Types
typedef std::map< std::string,
std::shared_ptr< DBInterface > > DBInterfaceMap
Private Member Functions
void resolveIncludes ()
void resolveForLoops ()
void resolveConstants ()
void resolveDbParameters ()
void resolveIncludes (const std::string &referencePath, TiXmlNode *node)
void resolveInclude (const std::string &referencePath, TiXmlElement *element, TiXmlDocument &document)
void getFilePath (const std::string &fileName, std::string &filePath)
void getRelativeFileName (const std::string &fileName, const std::string &relativeTo, std::string &relativeFileName)
void readConstants ()
void replaceAllConstants ()
void readConstantsSection (TiXmlElement *constants)
void resolveConstantsInElement (TiXmlElement *element)
void performConstantReplacement (std::string &value)
void performEnvVariableReplacement (std::string &value)
void readDatabases ()
void resolveAllDbSelect (TiXmlElement *pXmlElement)
void resolveForLoops (TiXmlElement *element)
void resolveForLoop (TiXmlNode *node, const std::string &id, int value)
Private Attributes
bool m_processIncludes = {true}
Whether to process includes elements.
bool m_allowNestedIncludes = {true}
Whether to allow nested include elements.
bool m_processConstants = {true}
Whether to process constants elements.
bool m_processDatabase = {true}
Whether to process database elements.
bool m_allowEnvVariables = {true}
Whether to allow the use of environment variables.
bool m_processForLoops = {true}
Whether to process for loops.
std::string m_fileName = {""}
The file name of the last parsed file.
TiXmlDocument m_document = {}
The xml document.
StringMap m_constants = {}
The constants map.
DBInterfaceMap m_databases = {}
The map of databases.
Detailed Description
XMLParser class.
Definition at line 26 of file XMLParser.h.
Member Typedef Documentation
typedef std::map<std::string, std::shared_ptr<DBInterface> > dqm4hep::core::XMLParser::DBInterfaceMap private
Definition at line 179 of file XMLParser.h.
Constructor & Destructor Documentation
dqm4hep::core::XMLParser::XMLParser ()
Constructor.
Definition at line 20 of file XMLParser.cc.
{
       /* nop */
     }
Member Function Documentation
bool dqm4hep::core::XMLParser::allowEnvVariables () const
Whether to allow the use of environment variable while resolving constants.
Definition at line 179 of file XMLParser.cc.
References m_allowEnvVariables.
Referenced by performEnvVariableReplacement(), and resolveConstantsInElement().
{
       return m_allowEnvVariables;
     }
bool dqm4hep::core::XMLParser::allowNestedIncludes () const
Whether to allow nested elements meaning include elements in included files.
Definition at line 134 of file XMLParser.cc.
References m_allowNestedIncludes.
Referenced by resolveInclude().
{
       return m_allowNestedIncludes;
     }
template<typename T > T dqm4hep::core::XMLParser::constantAs (const std::string & name, const T & fallback = T()) const inline
Get a constant value to specified type.
Parameters
name the constant name
fallback fallback value if constant doesn't exists
Definition at line 197 of file XMLParser.h.
References m_constants, and dqm4hep::core::stringToType().
{
       T value(fallback);
       auto iter = m_constants.find(name);
       if (m_constants.end() != iter)
         dqm4hep::core::stringToType(iter->second, value);
       return value;
     }
const StringMap & dqm4hep::core::XMLParser::constants () const
Get the constants map.
Definition at line 95 of file XMLParser.cc.
References m_constants.
{
       return m_constants;
     }
const TiXmlDocument & dqm4hep::core::XMLParser::document () const
Get the xml document.
Definition at line 83 of file XMLParser.cc.
References m_document.
Referenced by dqm4hep::online::ModuleApplication::parseSteeringFile(), readConstants(), readDatabases(), and resolveDbParameters().
{
       return m_document;
     }
TiXmlDocument & dqm4hep::core::XMLParser::document ()
Get the xml document.
Definition at line 89 of file XMLParser.cc.
References m_document.
{
       return m_document;
     }
const std::string & dqm4hep::core::XMLParser::fileName () const
Get the last parsed file name.
Definition at line 77 of file XMLParser.cc.
References m_fileName.
{
       return m_fileName;
     }
void dqm4hep::core::XMLParser::getFilePath (const std::string & fileName, std::string & filePath) private
Definition at line 339 of file XMLParser.cc.
Referenced by resolveInclude(), and resolveIncludes().
{
       filePath = "";
       size_t idx = fName.find_last_of("/");
       if (idx != std::string::npos)
         filePath = fName.substr(0, idx);
     }
void dqm4hep::core::XMLParser::getRelativeFileName (const std::string & fileName, const std::string & relativeTo, std::string & relativeFileName) private
Definition at line 349 of file XMLParser.cc.
Referenced by resolveInclude().
{
       if (fName.at(0) != '/')
         relativeFileName = relativeTo + "/" + fName;
       else
         relativeFileName = fName;
     }
void dqm4hep::core::XMLParser::parse (const std::string & fname)
Parse the xml file.
See the different parsing options below
Parameters
fname the xml file name
Definition at line 26 of file XMLParser.cc.
References dqm_error, dqm4hep::core::TiXmlDocument::ErrorCol(), dqm4hep::core::TiXmlDocument::ErrorDesc(), dqm4hep::core::TiXmlDocument::ErrorRow(), dqm4hep::core::TiXmlDocument::LoadFile(), m_document, m_fileName, processConstants(), processDatabase(), processForLoops(), processIncludes(), reset(), resolveConstants(), resolveDbParameters(), resolveForLoops(), resolveIncludes(), and dqm4hep::core::StatusCodeException::toString().
Referenced by dqm4hep::online::ModuleApplication::parseSteeringFile().
{
       this->reset();
       m_fileName = fname;
       bool loaded = m_document.LoadFile(m_fileName);
       if (!loaded) {
         dqm_error("XMLParser::parse(): couldn't load xml file ['{0}', row: {1}, col: {2}] : {3}", m_fileName,
                   m_document.ErrorRow(), m_document.ErrorCol(), m_document.ErrorDesc());
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       if (this->processIncludes()) {
         try {
           this->resolveIncludes();
         } catch (StatusCodeException &exception) {
           dqm_error("XMLParser::parse(): fail to resolve includes, {0}", exception.toString());
           throw exception;
         }
       }
       if (this->processConstants()) {
         try {
           this->resolveConstants();
         } catch (StatusCodeException &exception) {
           dqm_error("XMLParser::parse(): fail to resolve constants, {0}", exception.toString());
           throw exception;
         }
       }
       if (this->processDatabase()) {
         try {
           this->resolveDbParameters();
         } catch (StatusCodeException &exception) {
           dqm_error("XMLParser::parse(): fail to resolve db parameters, {0}", exception.toString());
           throw exception;
         }
       }
       if(this->processForLoops()) {
         try {
           this->resolveForLoops();
         } catch (StatusCodeException &exception) {
           dqm_error("XMLParser::parse(): fail to resolve for loops, {0}", exception.toString());
           throw exception;
         }
       }
     }
void dqm4hep::core::XMLParser::performConstantReplacement (std::string & value) private
Definition at line 420 of file XMLParser.cc.
References dqm_error, and m_constants.
Referenced by resolveConstantsInElement().
{
       size_t pos = value.find("${");
       std::string original(value);
       while (pos != std::string::npos) {
         size_t pos2 = value.find_first_of("}", pos + 2);
         if (pos2 == std::string::npos) {
           dqm_error("XMLParser::performConstantReplacement(): couldn't parse constant value !");
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         const std::string key(value.substr(pos + 2, pos2 - pos - 2));
         auto findConstant = m_constants.find(key);
         const std::string replacementValue(findConstant != m_constants.end() ? findConstant->second : "");
         if (replacementValue.empty()) {
           dqm_error("XMLParser::performConstantReplacement(): constant \"{0}\" not found in available constants !",
                     key);
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         value.replace(pos, (pos2 + 1 - pos), replacementValue);
         pos2 = pos + replacementValue.size(); // new end position after replace
         pos = value.find("${", pos2);         // find next possible key to replace
       }
     }
void dqm4hep::core::XMLParser::performEnvVariableReplacement (std::string & value) private
Definition at line 450 of file XMLParser.cc.
References allowEnvVariables(), and dqm_error.
Referenced by resolveConstantsInElement().
{
       if (!this->allowEnvVariables())
         return;
       size_t pos = value.find("$ENV{");
       std::string original(value);
       while (pos != std::string::npos) {
         size_t pos2 = value.find_first_of("}", pos + 5);
         if (pos2 == std::string::npos) {
           dqm_error("XMLParser::performEnvVariableReplacement(): couldn't parse env variable name !");
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         const std::string key(value.substr(pos + 5, pos2 - pos - 5));
         char *env = getenv(key.c_str());
         if (env == nullptr) {
           dqm_error("XMLParser::performEnvVariableReplacement(): env variable \"{0}\" not found !", key);
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         const std::string replacementValue(env);
         value.replace(pos, (pos2 + 1 - pos), replacementValue);
         pos2 = pos + replacementValue.size(); // new end position after replace
         pos = value.find("$ENV{", pos2);      // find next possible key to replace
       }
     }
bool dqm4hep::core::XMLParser::processConstants () const
Whether to process constants sections while parsing.
Definition at line 149 of file XMLParser.cc.
References m_processConstants.
Referenced by parse().
{
       return m_processConstants;
     }
bool dqm4hep::core::XMLParser::processDatabase () const
Whether to process <database> elements.
Definition at line 164 of file XMLParser.cc.
References m_processDatabase.
Referenced by parse().
{
       return m_processDatabase;
     }
bool dqm4hep::core::XMLParser::processForLoops () const
Whether to process XML for loop elements.
Definition at line 194 of file XMLParser.cc.
References m_processForLoops.
Referenced by parse().
{
       return m_processForLoops;
     }
bool dqm4hep::core::XMLParser::processIncludes () const
Whether to process elements.
Definition at line 119 of file XMLParser.cc.
References m_processIncludes.
Referenced by parse().
{
       return m_processIncludes;
     }
void dqm4hep::core::XMLParser::readConstants () private
Definition at line 359 of file XMLParser.cc.
References document(), dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::TiXmlNode::NextSiblingElement(), readConstantsSection(), and dqm4hep::core::TiXmlDocument::RootElement().
Referenced by resolveConstants().
{
       TiXmlElement *root = document().RootElement();
       for (TiXmlElement *element = root->FirstChildElement(); element != nullptr; element = element->NextSiblingElement()) {
         if (element->Value() == std::string("constants")) {
           this->readConstantsSection(element);
         }
       }
     }
void dqm4hep::core::XMLParser::readConstantsSection (TiXmlElement * constants) private
Definition at line 380 of file XMLParser.cc.
References dqm_error, dqm4hep::core::TiXmlNode::FirstChildElement(), m_constants, dqm4hep::core::TiXmlNode::NextSiblingElement(), and resolveConstantsInElement().
Referenced by readConstants().
{
       for (TiXmlElement *element = constantsElement->FirstChildElement("constant"); element != nullptr;
            element = element->NextSiblingElement("constant")) {
         this->resolveConstantsInElement(element);
         if (element->Attribute("name") == nullptr) {
           dqm_error("XMLParser::readConstantsSection(): constant element without name !");
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         std::string name(element->Attribute("name"));
         if (name.empty()) {
           dqm_error("XMLParser::readConstantsSection(): parsed empty constant name !");
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         if (m_constants.end() != m_constants.find(name)) {
           dqm_error("XMLParser::readConstantsSection(): constant \"{0}\" defined twice !", name);
           throw StatusCodeException(STATUS_CODE_ALREADY_PRESENT);
         }
         std::string value;
         if (element->Attribute("value") != nullptr) {
           value = element->Attribute("value");
         } else {
           if (element->FirstChild() != nullptr)
             value = element->FirstChild()->Value();
         }
         if (!m_constants.insert(StringMap::value_type(name, value)).second) {
           dqm_error("XMLParser::readConstantsSection(): couldn't add constant \"{0}\" to constant map !", name);
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
       }
     }
void dqm4hep::core::XMLParser::readDatabases () private
Definition at line 516 of file XMLParser.cc.
References dqm4hep::core::TiXmlElement::Attribute(), document(), dqm_error, dqm4hep::core::TiXmlNode::FirstChildElement(), m_databases, dqm4hep::core::TiXmlNode::NextSiblingElement(), dqm4hep::core::TiXmlDocument::RootElement(), and THROW_RESULT_IF.
Referenced by resolveDbParameters().
{
       TiXmlDocument &doc(this->document());
       TiXmlElement *databases = doc.RootElement()->FirstChildElement("databases");
       if (databases == nullptr)
         return;
       for (TiXmlElement *db = databases->FirstChildElement("db"); db != nullptr; db = db->NextSiblingElement("db")) {
         const char *dbID = db->Attribute("id");
         if ((dbID == nullptr) || std::string(dbID).empty()) {
           dqm_error("ERROR: <db> tag has no 'id' attribute or is empty, line {0}", db->Row());
           throw StatusCodeException(STATUS_CODE_NOT_FOUND);
         }
         if (m_databases.find(dbID) != m_databases.end()) {
           dqm_error("ERROR: <db> tag with id '{0}', line {1}, is duplicated !", dbID, db->Row());
           throw StatusCodeException(STATUS_CODE_ALREADY_PRESENT);
         }
         std::string dbHost = db->Attribute("host") != nullptr ? db->Attribute("host") : "localhost";
         std::string dbUser = "DQM4HEP"; // always has read access
         std::string dbDb = db->Attribute("db") != nullptr ? db->Attribute("db") : "DQM4HEP";
         std::shared_ptr<DBInterface> dbInterface(std::make_shared<DBInterface>());
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, dbInterface->connect(dbHost, dbUser, "", dbDb));
         m_databases[dbID] = dbInterface;
       }
     }
void dqm4hep::core::XMLParser::replaceAllConstants () private
Definition at line 370 of file XMLParser.cc.
References dqm4hep::core::TiXmlNode::FirstChildElement(), m_document, dqm4hep::core::TiXmlNode::NextSiblingElement(), resolveConstantsInElement(), and dqm4hep::core::TiXmlDocument::RootElement().
Referenced by resolveConstants().
{
       TiXmlElement *root = m_document.RootElement();
       for (TiXmlElement *element = root->FirstChildElement(); element != nullptr;
            element = element->NextSiblingElement())
         this->resolveConstantsInElement(element);
     }
void dqm4hep::core::XMLParser::reset ()
Reset the parser: clear the constants and the xml document.
Definition at line 101 of file XMLParser.cc.
References dqm4hep::core::TiXmlNode::Clear(), m_constants, m_databases, m_document, and m_fileName.
Referenced by parse().
{
       m_constants.clear();
       m_fileName.clear();
       m_document.Clear();
       m_databases.clear();
     }
void dqm4hep::core::XMLParser::resolveAllDbSelect (TiXmlElement * pXmlElement) private
Definition at line 550 of file XMLParser.cc.
References dqm_error, dqm_info, dqm4hep::core::TiXmlNode::FirstChildElement(), m_databases, dqm4hep::core::TiXmlNode::NextSiblingElement(), dqm4hep::core::TiXmlNode::PreviousSibling(), dqm4hep::core::TiXmlNode::RemoveChild(), THROW_RESULT_IF, and dqm4hep::core::TiXmlNode::ToElement().
Referenced by resolveDbParameters().
{
       if (m_databases.empty())
         return;
       for (TiXmlElement *element = pXmlElement->FirstChildElement(); element != nullptr;
            element = element->NextSiblingElement()) {
         if (std::string(element->Value()) == "select") {
           std::string dbID = element->Attribute("db") != nullptr ? element->Attribute("db") : "";
           std::string dbTable = element->Attribute("table") != nullptr ? element->Attribute("table") : "";
           if (dbID.empty() || dbTable.empty()) {
             dqm_error("<select> element, row {0}, column {1}: invalid/missing attributes 'db' or 'table'",
                       element->Row(), element->Column());
             throw StatusCodeException(STATUS_CODE_FAILURE);
           }
           auto findIter = m_databases.find(dbID);
           if (m_databases.end() == findIter) {
             dqm_error("<select> element, row {0}, column {1}: db id '{2}' not found !", element->Row(),
                       element->Column(), dbID);
             throw StatusCodeException(STATUS_CODE_NOT_FOUND);
           }
           std::shared_ptr<DBInterface> dbInterface(findIter->second);
           StringMap parameterMap;
           THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, dbInterface->getTableParameters(dbTable, parameterMap));
           TiXmlNode *pInsertAfter(element), *pParentElement(element->Parent()->ToElement());
           for (auto parameterIter : parameterMap) {
             dqm_info("Selected parameter '{0}' = '{1}'", parameterIter.first, parameterIter.second);
             auto pParameterElement = new TiXmlElement("parameter");
             pParameterElement->SetAttribute("name", parameterIter.first);
             pParameterElement->SetAttribute("value", parameterIter.second);
             pInsertAfter = pParentElement->InsertAfterChild(pInsertAfter, *pParameterElement);
             delete pParameterElement;
           }
           TiXmlElement *previousElement(nullptr);
           TiXmlNode *previousNode(element);
           while(nullptr != previousNode->PreviousSibling()) {
             if(nullptr != previousNode->PreviousSibling()->ToElement()) {
               previousElement = previousNode->PreviousSibling()->ToElement();
               break;
             }
             else {
               previousNode = previousNode->PreviousSibling();
             }
           }
           // if a previous element is available,
           // continue the loop from it
           if(nullptr != previousElement) {
             pParentElement->RemoveChild(element);
             element = previousElement;
           }
           // if no previous element is available,
           // restart from the first child of input
           else {
             pParentElement->RemoveChild(element);
             element = pParentElement->FirstChildElement();
           }
         } else {
           // recursive call on childs !
           this->resolveAllDbSelect(element);
         }
       }
     }
void dqm4hep::core::XMLParser::resolveConstants () private
Definition at line 217 of file XMLParser.cc.
References readConstants(), and replaceAllConstants().
Referenced by parse().
{
       this->readConstants();
       this->replaceAllConstants();
     }
void dqm4hep::core::XMLParser::resolveConstantsInElement (TiXmlElement * element) private
Definition at line 483 of file XMLParser.cc.
References allowEnvVariables(), dqm4hep::core::TiXmlElement::FirstAttribute(), dqm4hep::core::TiXmlNode::FirstChild(), dqm4hep::core::TiXmlAttribute::Next(), dqm4hep::core::TiXmlNode::NextSibling(), performConstantReplacement(), performEnvVariableReplacement(), dqm4hep::core::TiXmlNode::SetValue(), dqm4hep::core::TiXmlNode::TINYXML_ELEMENT, dqm4hep::core::TiXmlNode::TINYXML_TEXT, dqm4hep::core::TiXmlElement::ToElement(), dqm4hep::core::TiXmlText::ToText(), and dqm4hep::core::TiXmlNode::ValueStr().
Referenced by readConstantsSection(), and replaceAllConstants().
{
       // replace constants in all attributes
       for (TiXmlAttribute *attribute = element->FirstAttribute(); attribute != nullptr; attribute = attribute->Next()) {
         std::string value(attribute->ValueStr());
         this->performConstantReplacement(value);
         if (this->allowEnvVariables())
           this->performEnvVariableReplacement(value);
         attribute->SetValue(value);
       }
       for (TiXmlNode *node = element->FirstChild(); node != nullptr; node = node->NextSibling()) {
         if (node->Type() == TiXmlNode::TINYXML_ELEMENT) {
           TiXmlElement *child = node->ToElement();
           this->resolveConstantsInElement(child);
         } else if (node->Type() == TiXmlNode::TINYXML_TEXT) {
           TiXmlText *child = node->ToText();
           std::string value(child->ValueStr());
           this->performConstantReplacement(value);
           if (this->allowEnvVariables())
             this->performEnvVariableReplacement(value);
           child->SetValue(value);
         }
       }
     }
void dqm4hep::core::XMLParser::resolveDbParameters () private
Definition at line 224 of file XMLParser.cc.
References document(), readDatabases(), and resolveAllDbSelect().
Referenced by parse().
{
       this->readDatabases();
       this->resolveAllDbSelect(this->document().RootElement());
     }
void dqm4hep::core::XMLParser::resolveForLoop (TiXmlNode * node, const std::string & id, int value) private
Definition at line 679 of file XMLParser.cc.
References dqm4hep::core::TiXmlElement::FirstAttribute(), dqm4hep::core::TiXmlNode::FirstChild(), dqm4hep::core::TiXmlAttribute::Next(), dqm4hep::core::TiXmlNode::NextSibling(), dqm4hep::core::TiXmlNode::SetValue(), dqm4hep::core::TiXmlNode::TINYXML_COMMENT, dqm4hep::core::TiXmlNode::TINYXML_ELEMENT, dqm4hep::core::TiXmlNode::TINYXML_TEXT, dqm4hep::core::TiXmlNode::ToElement(), dqm4hep::core::TiXmlNode::Type(), dqm4hep::core::typeToString(), and dqm4hep::core::TiXmlNode::ValueStr().
Referenced by resolveForLoops().
{
       std::string loopIDStr = "$FOR{" + id + "}";
       std::string valueStr = typeToString(value);
       if(node->Type() == TiXmlNode::TINYXML_ELEMENT) {
         TiXmlElement *nodeElement = node->ToElement();
         // replace occurences in all attributes
         for(auto attr = nodeElement->FirstAttribute() ; nullptr != attr ; attr = attr->Next()) {
           std::string attrValue(attr->ValueStr());
           size_t pos = attrValue.find(loopIDStr, 0);
           while(pos != std::string::npos) {
             attrValue.replace(pos, loopIDStr.size(), valueStr);
             pos = attrValue.find(loopIDStr, pos+valueStr.size());
           }
           attr->SetValue(attrValue);
         }
         // make it recursive
         for(auto child = nodeElement->FirstChild() ; nullptr != child ; child = child->NextSibling()) {
           resolveForLoop(child, id, value);
         }
       }
       else if((node->Type() == TiXmlNode::TINYXML_COMMENT) or (node->Type() == TiXmlNode::TINYXML_TEXT)) {
         std::string nodeValue = node->ValueStr();
         size_t pos = nodeValue.find(loopIDStr, 0);
         while(pos != std::string::npos) {
           nodeValue.replace(pos, loopIDStr.size(), valueStr);
           pos = nodeValue.find(loopIDStr, pos+valueStr.size());
         }
         node->SetValue(nodeValue);
       }
     }
void dqm4hep::core::XMLParser::resolveForLoops () private
Definition at line 623 of file XMLParser.cc.
References m_document, and dqm4hep::core::TiXmlDocument::RootElement().
Referenced by parse(), and resolveForLoops().
{
       TiXmlElement *root = m_document.RootElement();
       resolveForLoops(root);
     }
void dqm4hep::core::XMLParser::resolveForLoops (TiXmlElement * element) private
Definition at line 630 of file XMLParser.cc.
References dqm_error, dqm4hep::core::TiXmlNode::FirstChild(), dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::TiXmlNode::NextSibling(), dqm4hep::core::TiXmlNode::NextSiblingElement(), dqm4hep::core::TiXmlNode::Parent(), dqm4hep::core::TiXmlElement::QueryIntAttribute(), dqm4hep::core::TiXmlElement::QueryStringAttribute(), resolveForLoop(), resolveForLoops(), dqm4hep::core::TIXML_SUCCESS, and dqm4hep::core::TiXmlNode::Value().
{
       // first, resolve for loops in child elements
       for(auto child = element->FirstChildElement(); nullptr != child ; child = child->NextSiblingElement()) {
         resolveForLoops(child);
       }
       // if loop element, resolve it
       if(element->Value() == std::string("for")) {
         auto parent = element->Parent();
         if(nullptr == parent) {
           return;
         }
         int begin(0), end(0), increment(0);
         std::string loopId;
         if(TIXML_SUCCESS != element->QueryIntAttribute("begin", &begin)) {
           dqm_error( "XMLParser::resolveForLoops: <for> element with invalid 'begin' attribute !" );
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         if(TIXML_SUCCESS != element->QueryIntAttribute("end", &end)) {
           dqm_error( "XMLParser::resolveForLoops: <for> element with invalid 'end' attribute !" );
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         if(TIXML_SUCCESS != element->QueryStringAttribute("id", &loopId) or loopId.empty()) {
           dqm_error( "XMLParser::resolveForLoops: <for> element with invalid 'id' attribute !" );
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         // optional attribute
         element->QueryIntAttribute("increment", &increment);
         const bool forwardLoop(begin < end);
         if((forwardLoop and increment < 0) or (not forwardLoop and increment > 0)) {
           dqm_error( "XMLParser::resolveForLoops: <for> element with infinite loop detected !" );
           throw StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
         }
         for(int i=begin ; i<=end ; i+=increment) {
           for(auto child = element->FirstChild() ; nullptr != child ; child = child->NextSibling()) {
             auto cloneChild = child->Clone();
             if(nullptr != cloneChild) {
               resolveForLoop(cloneChild, loopId, i);
               parent->InsertBeforeChild(element, *cloneChild);
               delete cloneChild;
             }
           }
         }
         // remove the element itself from the tree
         parent->RemoveChild(element);
       }
     }
void dqm4hep::core::XMLParser::resolveInclude (const std::string & referencePath, TiXmlElement * element, TiXmlDocument & document) private
Definition at line 304 of file XMLParser.cc.
References allowNestedIncludes(), dqm4hep::core::TiXmlElement::Attribute(), dqm_error, dqm4hep::core::TiXmlDocument::ErrorCol(), dqm4hep::core::TiXmlDocument::ErrorDesc(), dqm4hep::core::TiXmlDocument::ErrorRow(), getFilePath(), getRelativeFileName(), dqm4hep::core::TiXmlDocument::LoadFile(), resolveIncludes(), and dqm4hep::core::TiXmlNode::Value().
Referenced by resolveIncludes().
{
       if (element->Attribute("ref") == nullptr) {
         dqm_error("XMLParser::resolveInclude(): missing attribute \"ref\" in element <{0}/>", element->Value());
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       std::string ref(element->Attribute("ref"));
       if (ref.size() < 5 || ref.substr(ref.size() - 4) != ".xml") {
         dqm_error("XMLParser::resolveInclude(): invalid ref file name \"{0}\" in element <{1}/>", ref,
                   element->Value());
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       std::string refFileName;
       this->getRelativeFileName(ref, referencePath, refFileName);
       bool loadOkay = doc.LoadFile(refFileName);
       if (!loadOkay) {
         dqm_error("XMLParser::resolveInclude(): error in file [{0}, row: {1}, col: {2}] : {3}", refFileName,
                   doc.ErrorRow(), doc.ErrorCol(), doc.ErrorDesc());
         throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       // process nested includes if enabled
       if (this->allowNestedIncludes()) {
         std::string includeReferencePath;
         this->getFilePath(refFileName, includeReferencePath);
         this->resolveIncludes(includeReferencePath, &doc);
       }
     }
void dqm4hep::core::XMLParser::resolveIncludes () private
Definition at line 200 of file XMLParser.cc.
References dqm_error, getFilePath(), m_document, m_fileName, dqm4hep::core::TiXmlDocument::RootElement(), and dqm4hep::core::StatusCodeException::toString().
Referenced by parse(), resolveInclude(), and resolveIncludes().
{
       TiXmlElement *root = m_document.RootElement();
       std::string filePath;
       this->getFilePath(m_fileName, filePath);
       try {
         this->resolveIncludes(filePath, root);
       } catch (StatusCodeException &exception) {
         dqm_error("XMLParser::resolveIncludes(): fail to resolve include in root document '{0}', {1}", m_fileName,
                   exception.toString());
         throw exception;
       }
     }
void dqm4hep::core::XMLParser::resolveIncludes (const std::string & referencePath, TiXmlNode * node) private
Definition at line 231 of file XMLParser.cc.
References dqm_debug, dqm_error, dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::TiXmlNode::InsertAfterChild(), dqm4hep::core::TiXmlNode::NextSiblingElement(), dqm4hep::core::TiXmlNode::PreviousSibling(), dqm4hep::core::TiXmlNode::RemoveChild(), resolveInclude(), resolveIncludes(), dqm4hep::core::TiXmlDocument::RootElement(), dqm4hep::core::TiXmlNode::ToElement(), and dqm4hep::core::TiXmlNode::Value().
{
       TiXmlElement *child = node->FirstChildElement();
       while (true) {
         if (child == nullptr)
           break;
         if (child->Value() != std::string("include")) {
           this->resolveIncludes(referencePath, child);
           child = child->NextSiblingElement();
           continue;
         }
         // process the include and returns the parsed document
         TiXmlDocument doc;
         this->resolveInclude(referencePath, child, doc);
         TiXmlElement *rootInclude = doc.RootElement();
         if (std::string(rootInclude->Value()) != "dqm4hep") {
           dqm_error("XMLParser::resolveIncludes(): no <dqm4hep> root element in included file '{0}'", doc.Value());
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         // add them to the xml tree
         TiXmlNode *includeAfter(child);
         for (TiXmlElement *includeElement = rootInclude->FirstChildElement(); includeElement != nullptr;
              includeElement = includeElement->NextSiblingElement())
           includeAfter = node->InsertAfterChild(includeAfter, *includeElement);
         // case where at least one element has been inserted from the include file
         if(includeAfter != child) {
           node->RemoveChild(child);
           child = includeAfter->NextSiblingElement();
         }
         // case where nothing was inserted
         else {
           dqm_debug( "XMLParser::resolveIncludes(): No element in included file" );
           // Find the previous element to point to if any
           TiXmlElement *previousElement(nullptr);
           TiXmlNode *previousNode(child);
           while(nullptr != previousNode->PreviousSibling()) {
             if(nullptr != previousNode->PreviousSibling()->ToElement()) {
               previousElement = previousNode->PreviousSibling()->ToElement();
               break;
             }
             else {
               previousNode = previousNode->PreviousSibling();
             }
           }
           // node->RemoveChild(child);
           // if a previous element is available,
           // continue the while from it
           if(nullptr != previousElement) {
             dqm_debug( "XMLParser::resolveIncludes(): Previous element found" );
             node->RemoveChild(child);
             child = previousElement;
           }
           // if no previous element is available,
           // restart from the first child of input
           else {
             dqm_debug( "XMLParser::resolveIncludes(): No previous element" );
             node->RemoveChild(child);
             child = node->FirstChildElement();
           }
         }
       }
     }
void dqm4hep::core::XMLParser::setAllowEnvVariables (bool allow)
Set whether to allow the use of environment variable while resolving constants.
Parameters
allow whether to allow the use of environment variable
Definition at line 170 of file XMLParser.cc.
References dqm_warning, and m_allowEnvVariables.
{
       m_allowEnvVariables = allow;
       if(not m_allowEnvVariables) {
         dqm_warning( "XMLParser: environment variables will not be replaced !" );
       }
     }
void dqm4hep::core::XMLParser::setAllowNestedIncludes (bool allow)
Set whether to allow nested elements, meaning include elements in included files.
Parameters
allow whether to allow nested includes
Definition at line 125 of file XMLParser.cc.
References dqm_warning, and m_allowNestedIncludes.
{
       m_allowNestedIncludes = allow;
       if(not m_allowNestedIncludes) {
         dqm_warning( "XMLParser: nested <include> elements will not be processed !" );
       }
     }
void dqm4hep::core::XMLParser::setProcessConstants (bool process)
Set whether to process constants sections while parsing.
Parameters
process whether to process constants
Definition at line 140 of file XMLParser.cc.
References dqm_warning, and m_processConstants.
{
       m_processConstants = process;
       if(not m_processConstants) {
         dqm_warning( "XMLParser: constants will not be parsed !" );
       }
     }
void dqm4hep::core::XMLParser::setProcessDatabase (bool process)
Set whether to process <database> elements.
Parameters
process whether to process <database> elements
Definition at line 155 of file XMLParser.cc.
References dqm_warning, and m_processDatabase.
{
       m_processDatabase = process;
       if(not m_processDatabase) {
         dqm_warning( "XMLParser: no database will be used for parsing !" );
       }
     }
void dqm4hep::core::XMLParser::setProcessForLoops (bool process)
Set whether to process XML for loop elements.
Parameters
process whether to process for loops
Definition at line 185 of file XMLParser.cc.
References dqm_warning, and m_processForLoops.
{
       m_processForLoops = process;
       if(not m_processForLoops) {
         dqm_warning( "XMLParser: <for> for loop elements will not be processed !" );
       }
     }
void dqm4hep::core::XMLParser::setProcessIncludes (bool process)
Set whether to process element while parsing.
Parameters
process whether to process includes
Definition at line 110 of file XMLParser.cc.
References dqm_warning, and m_processIncludes.
{
       m_processIncludes = process;
       if(not m_processIncludes) {
         dqm_warning( "XMLParser: <include> elements will not be processed !" );
       }
     }
Member Data Documentation
bool dqm4hep::core::XMLParser::m_allowEnvVariables = {true} private
Whether to allow the use of environment variables.
Definition at line 185 of file XMLParser.h.
Referenced by allowEnvVariables(), and setAllowEnvVariables().
bool dqm4hep::core::XMLParser::m_allowNestedIncludes = {true} private
Whether to allow nested include elements.
Definition at line 182 of file XMLParser.h.
Referenced by allowNestedIncludes(), and setAllowNestedIncludes().
StringMap dqm4hep::core::XMLParser::m_constants = {} private
The constants map.
Definition at line 189 of file XMLParser.h.
Referenced by constantAs(), constants(), performConstantReplacement(), readConstantsSection(), and reset().
DBInterfaceMap dqm4hep::core::XMLParser::m_databases = {} private
The map of databases.
Definition at line 190 of file XMLParser.h.
Referenced by readDatabases(), reset(), and resolveAllDbSelect().
TiXmlDocument dqm4hep::core::XMLParser::m_document = {} private
The xml document.
Definition at line 188 of file XMLParser.h.
Referenced by document(), parse(), replaceAllConstants(), reset(), resolveForLoops(), and resolveIncludes().
std::string dqm4hep::core::XMLParser::m_fileName = {""} private
The file name of the last parsed file.
Definition at line 187 of file XMLParser.h.
Referenced by fileName(), parse(), reset(), and resolveIncludes().
bool dqm4hep::core::XMLParser::m_processConstants = {true} private
Whether to process constants elements.
Definition at line 183 of file XMLParser.h.
Referenced by processConstants(), and setProcessConstants().
bool dqm4hep::core::XMLParser::m_processDatabase = {true} private
Whether to process database elements.
Definition at line 184 of file XMLParser.h.
Referenced by processDatabase(), and setProcessDatabase().
bool dqm4hep::core::XMLParser::m_processForLoops = {true} private
Whether to process for loops.
Definition at line 186 of file XMLParser.h.
Referenced by processForLoops(), and setProcessForLoops().
bool dqm4hep::core::XMLParser::m_processIncludes = {true} private
Whether to process includes elements.
Definition at line 181 of file XMLParser.h.
Referenced by processIncludes(), and setProcessIncludes().
The documentation for this class was generated from the following files:
XMLParser.h
XMLParser.cc