DQM4hep: dqm4hep::net::WsService Class Reference
dqm4hep::net::WsService Class Reference
WsService class Implementation of a server service.
#include <WebSocketServer.h>
Public Member Functions
WsService (WsServer *s, const std::string &n)
Constructor.
template<typename T >
void send (const T &value)
Send data to all listening clients.
void send (const char *buffer, size_t size, bool containsBinary=false)
Send data to all listening clients.
template<>
void send (const std::string &value)
Public Member Functions inherited from dqm4hep::net::WsServiceBase
WsServiceBase (WsServer *s, const std::string &n, ServiceType t)
Constructor.
virtual ~WsServiceBase ()
Destructor.
WsServer * server () const
Get the server owning the service.
const std::string & name () const
Get the service name.
ServiceType type () const
Get the service type.
Detailed Description
WsService class Implementation of a server service.
A service send data to client whenever the server needs it.
Definition at line 113 of file WebSocketServer.h.
Constructor & Destructor Documentation
dqm4hep::net::WsService::WsService (WsServer * s, const std::string & n)
Constructor.
Parameters
s the server owning the service
n the service name
Definition at line 55 of file WebSocketServer.cc.
                                                         :
       WsServiceBase(s, n, SERVICE_TYPE) {
     }
Member Function Documentation
template<typename T > void dqm4hep::net::WsService::send (const T & value) inline
Send data to all listening clients.
The data is converted to string using the dqm4hep::core::typeToString() function. std::string data type is not converted . Note that the final converted string must not contain binary characters. For binary data, use the dedicated method with buffer instead.
Parameters
value the value to send
Definition at line 371 of file WebSocketServer.h.
References dqm4hep::core::typeToString().
Referenced by send().
{
       std::string valueStr = dqm4hep::core::typeToString(value);
       send(valueStr.c_str(), valueStr.size(), false);
     }
void dqm4hep::net::WsService::send (const char * buffer, size_t size, bool containsBinary = false)
Send data to all listening clients.
Parameters
buffer a buffer of data to send
size the buffer size
containsBinary whether the buffer contains binary data
Definition at line 62 of file WebSocketServer.cc.
References dqm4hep::net::WsServer::send(), and dqm4hep::net::WsServiceBase::server().
{
       server()->send(this, buffer, size, containsBinary);
     }
template<> void dqm4hep::net::WsService::send (const std::string & value) inline
Definition at line 379 of file WebSocketServer.h.
References send().
{
       send(value.c_str(), value.size(), false);
     }
The documentation for this class was generated from the following files:
WebSocketServer.h
WebSocketServer.cc