DQM4hep: dqm4hep::online::OnlineManagerServer Class Reference
dqm4hep::online::OnlineManagerServer Class Reference
OnlineManagerServer class.
#include <OnlineManagerServer.h>
Public Member Functions
OnlineManagerServer ()=default
Constructor.
OnlineManagerServer (const OnlineManagerServer &)=delete
OnlineManagerServer & operator= (const OnlineManagerServer &)=delete
void run ()
Run the server.
void stop ()
Stop the server.
void setLogProperties (const std::string &fileBaseName, size_t maxFileSize, size_t maxNFiles)
.
Private Member Functions
void collectLog (const net::Buffer &buffer)
Collect a log message (server command)
void collectAppStat (const net::Buffer &buffer)
Collect an app stat (server command)
void logMessage (const core::json &message)
Log message in log file.
std::string currentTimeToString () const
Private Attributes
std::shared_ptr< net::Server > m_server = {nullptr}
The main server.
net::Service * m_logsService = {nullptr}
The logs service.
net::Service * m_appStatsService = {nullptr}
The application stats service.
std::atomic< bool > m_stopFlag = {false}
The main loop stop flag.
std::string m_logFileBaseName = {""}
std::size_t m_logFileMaxSize = {2*1024*1024}
std::size_t m_logFileNFiles = {2}
core::Logger::LoggerPtr m_logger = {nullptr}
Detailed Description
OnlineManagerServer class.
Definition at line 49 of file OnlineManagerServer.h.
Constructor & Destructor Documentation
dqm4hep::online::OnlineManagerServer::OnlineManagerServer () default
Constructor.
dqm4hep::online::OnlineManagerServer::OnlineManagerServer (const OnlineManagerServer &) delete
Member Function Documentation
void dqm4hep::online::OnlineManagerServer::collectAppStat (const net::Buffer & buffer) private
Collect an app stat (server command)
Parameters
buffer the app stat as json buffer
Definition at line 109 of file OnlineManagerServer.cc.
References dqm4hep::net::Buffer::begin(), dqm_warning, dqm4hep::net::Buffer::end(), m_appStatsService, dqm4hep::net::Service::sendBuffer(), and dqm4hep::net::Buffer::size().
Referenced by run().
{
       core::json appStat;
       try {
         appStat = core::json::parse(buffer.begin(), buffer.end());
       }
       catch(core::json::parse_error& e) {
         dqm_warning( "OnlineManagerServer::collectAppStat: received unexpected app stat (json parse error)" );
         return;
       }
       // check app stat consistency
       bool appStatConsistent = (
         1 == appStat.count("logger") &&
         1 == appStat.count("value") &&
         1 == appStat.count("appType") &&
         1 == appStat.count("appName") &&
         1 == appStat.count("time")
       );
       if(not appStatConsistent) {
         dqm_warning( "OnlineManagerServer::collectAppStat: received inconsistent app stat" );
       }
       // send the log message to listeners
       m_appStatsService->sendBuffer(buffer.begin(), buffer.size());
     }
void dqm4hep::online::OnlineManagerServer::collectLog (const net::Buffer & buffer) private
Collect a log message (server command)
Parameters
buffer the log message as json buffer
Definition at line 80 of file OnlineManagerServer.cc.
References dqm4hep::net::Buffer::begin(), dqm_warning, dqm4hep::net::Buffer::end(), logMessage(), m_logger, m_logsService, dqm4hep::net::Service::sendBuffer(), and dqm4hep::net::Buffer::size().
Referenced by run().
{
       core::json message;
       try {
         message = core::json::parse(buffer.begin(), buffer.end());
       }
       catch(core::json::parse_error& e) {
         dqm_warning( "OnlineManagerServer::collectLog: received unexpected log message (json parse error)" );
         return;
       }
       // check log consistency
       bool logConsistent = (
         1 == message.count("logger") &&
         1 == message.count("level") &&
         1 == message.count("message") &&
         1 == message.count("host") &&
         1 == message.count("pid")
       );
       if(not logConsistent) {
         dqm_warning( "OnlineManagerServer::collectLog: received inconsistent log message" );
       }
       if(nullptr != m_logger) {
         this->logMessage(message);
       }
       // send the log message to listeners
       m_logsService->sendBuffer(buffer.begin(), buffer.size());
     }
std::string dqm4hep::online::OnlineManagerServer::currentTimeToString () const private
Definition at line 156 of file OnlineManagerServer.cc.
Referenced by logMessage().
{
       std::time_t t = std::time(nullptr);
       std::string currentTime;
       currentTime.resize(9);
       std::strftime(const_cast<char*>(currentTime.c_str()), 9, "%T", std::localtime(&t));
       return currentTime;
     }
void dqm4hep::online::OnlineManagerServer::logMessage (const core::json & message) private
Log message in log file.
Parameters
message the json object describing the log message
Definition at line 135 of file OnlineManagerServer.cc.
References currentTimeToString(), dqm_logger_log, dqm4hep::core::Logger::logLevelToString(), m_logger, and dqm4hep::core::pid().
Referenced by collectLog().
{
       // extract metadata
       std::string loggerName = message.value<std::string>("logger", "");
       core::Logger::Level logLevel = static_cast<core::Logger::Level>(message.value<int>("level", 0));
       std::string logLevelStr = core::Logger::logLevelToString(logLevel);
       std::string msg = message.value<std::string>("message", "");
       std::string host = message.value<std::string>("host", "");
       int pid = message.value<int>("pid", 0);
       // log message
       dqm_logger_log(m_logger, logLevel,
         "[{0} on {1} ({2})] {3} - {4}: {5}",
         loggerName,
         host,
         pid,
         currentTimeToString(),
         logLevelStr,
         msg);
     }
OnlineManagerServer& dqm4hep::online::OnlineManagerServer::operator= (const OnlineManagerServer &) delete
void dqm4hep::online::OnlineManagerServer::run ()
Run the server.
Definition at line 37 of file OnlineManagerServer.cc.
References dqm4hep::online::OnlineRoutes::OnlineManager::appStats(), collectAppStat(), dqm4hep::online::OnlineRoutes::OnlineManager::collectAppStat(), collectLog(), dqm4hep::online::OnlineRoutes::OnlineManager::collectLog(), dqm4hep::core::Logger::createLogger(), dqm4hep::online::OnlineRoutes::OnlineManager::logs(), m_appStatsService, m_logFileBaseName, m_logFileMaxSize, m_logFileNFiles, m_logger, m_logsService, m_server, m_stopFlag, dqm4hep::core::Logger::rotatingFile(), dqm4hep::online::OnlineRoutes::OnlineManager::serverName(), and dqm4hep::core::sleep().
{
       if(not m_logFileBaseName.empty()) {
         m_logger = core::Logger::createLogger("online-logger", {
           core::Logger::rotatingFile(
             m_logFileBaseName,
             m_logFileMaxSize,
             m_logFileNFiles
           )
         });
         m_logger->set_pattern("%v");
         m_logger->set_level(spdlog::level::trace); // all message
       }
       m_server = std::make_shared<net::Server>(OnlineRoutes::OnlineManager::serverName());
       m_logsService = m_server->createService(OnlineRoutes::OnlineManager::logs());
       m_appStatsService = m_server->createService(OnlineRoutes::OnlineManager::appStats());
       m_server->createCommandHandler(OnlineRoutes::OnlineManager::collectLog(), this, &OnlineManagerServer::collectLog);
       m_server->createCommandHandler(OnlineRoutes::OnlineManager::collectAppStat(), this, &OnlineManagerServer::collectAppStat);
       m_server->start();
       while(not m_stopFlag.load())
         core::sleep(std::chrono::seconds(1));
     }
void dqm4hep::online::OnlineManagerServer::setLogProperties (const std::string & fileBaseName, size_t maxFileSize, size_t maxNFiles)
.
Set the rotating log file properties
Parameters
fileBaseName the log file base name (.log appended)
maxFileSize the maximum single file size (unit bytes)
maxNFiles the maximum number of rotating files
Definition at line 72 of file OnlineManagerServer.cc.
References m_logFileBaseName, m_logFileMaxSize, and m_logFileNFiles.
{
       m_logFileBaseName = fileBaseName;
       m_logFileMaxSize = maxFileSize;
       m_logFileNFiles = maxNFiles;
     }
void dqm4hep::online::OnlineManagerServer::stop ()
Stop the server.
Definition at line 66 of file OnlineManagerServer.cc.
References m_stopFlag.
{
       m_stopFlag = true;
     }
Member Data Documentation
net::Service* dqm4hep::online::OnlineManagerServer::m_appStatsService = {nullptr} private
The application stats service.
Definition at line 104 of file OnlineManagerServer.h.
Referenced by collectAppStat(), and run().
std::string dqm4hep::online::OnlineManagerServer::m_logFileBaseName = {""} private
Definition at line 106 of file OnlineManagerServer.h.
Referenced by run(), and setLogProperties().
std::size_t dqm4hep::online::OnlineManagerServer::m_logFileMaxSize = {2*1024*1024} private
Definition at line 107 of file OnlineManagerServer.h.
Referenced by run(), and setLogProperties().
std::size_t dqm4hep::online::OnlineManagerServer::m_logFileNFiles = {2} private
Definition at line 108 of file OnlineManagerServer.h.
Referenced by run(), and setLogProperties().
core::Logger::LoggerPtr dqm4hep::online::OnlineManagerServer::m_logger = {nullptr} private
Definition at line 109 of file OnlineManagerServer.h.
Referenced by collectLog(), logMessage(), and run().
net::Service* dqm4hep::online::OnlineManagerServer::m_logsService = {nullptr} private
The logs service.
Definition at line 103 of file OnlineManagerServer.h.
Referenced by collectLog(), and run().
std::shared_ptr<net::Server> dqm4hep::online::OnlineManagerServer::m_server = {nullptr} private
The main server.
Definition at line 102 of file OnlineManagerServer.h.
Referenced by run().
std::atomic<bool> dqm4hep::online::OnlineManagerServer::m_stopFlag = {false} private
The main loop stop flag.
Definition at line 105 of file OnlineManagerServer.h.
Referenced by run(), and stop().
The documentation for this class was generated from the following files:
OnlineManagerServer.h
OnlineManagerServer.cc