DQM4hep: dqm4hep::online::OnlineRoutes::RunControl Class Reference
dqm4hep::online::OnlineRoutes::RunControl Class Reference
RunControl class.
#include <OnlineRoutes.h>
Static Public Member Functions
static const std::string status (const std::string &runControlName)
Definition of the status RPC service name.
static const std::string sor (const std::string &runControlName)
Definition of the SOR service name.
static const std::string eor (const std::string &runControlName)
Definition of the EOR service name.
Detailed Description
RunControl class.
Defines the routes related to run control
Definition at line 31 of file OnlineRoutes.h.
Member Function Documentation
const std::string dqm4hep::online::OnlineRoutes::RunControl::eor (const std::string & runControlName) static
Definition of the EOR service name.
Parameters
runControlName the run control name
Returns
the EOR service name
Definition at line 29 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::ModuleApplication::onEvent(), and dqm4hep::online::ModuleApplication::onInit().
{
       return "/dqm4hep/RunControl/" + runControlName + "/EOR";
     }
const std::string dqm4hep::online::OnlineRoutes::RunControl::sor (const std::string & runControlName) static
Definition of the SOR service name.
Parameters
runControlName the run control name
Returns
the SOR service name
Definition at line 23 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::ModuleApplication::onEvent(), and dqm4hep::online::ModuleApplication::onInit().
{
       return "/dqm4hep/RunControl/" + runControlName + "/SOR";
     }
const std::string dqm4hep::online::OnlineRoutes::RunControl::status (const std::string & runControlName) static
Definition of the status RPC service name.
Parameters
runControlName the run control name
Returns
the status RPC service name
Definition at line 17 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::ModuleApplication::onStart().
{
       return "/dqm4hep/RunControl/" + runControlName + "/Status";
     }
The documentation for this class was generated from the following files:
OnlineRoutes.h
OnlineRoutes.cc