DQM4hep: dqm4hep::core::BufferEventStreamer Class Reference
dqm4hep::core::BufferEventStreamer Class Reference
BufferEventStreamer class.
Public Member Functions
BufferEventStreamer ()=default
~BufferEventStreamer () override=default
EventPtr createEvent () const override
Factory method to create the corresponding event to this streamer.
StatusCode write (EventPtr event, TBuffer &buffer) override
Serialize the event and store it into a data stream.
StatusCode read (EventPtr event, TBuffer &buffer) override
De-serialize the event.
Public Member Functions inherited from dqm4hep::core::EventStreamerPlugin
virtual ~EventStreamerPlugin ()=default
Destructor.
Detailed Description
BufferEventStreamer class.
Definition at line 28 of file BufferEventStreamer.cc.
Constructor & Destructor Documentation
dqm4hep::core::BufferEventStreamer::BufferEventStreamer () default
dqm4hep::core::BufferEventStreamer::~BufferEventStreamer () override default
Member Function Documentation
EventPtr dqm4hep::core::BufferEventStreamer::createEvent () const override virtual
Factory method to create the corresponding event to this streamer.
The event is expected to contains an allocated wrapped event
Implements dqm4hep::core::EventStreamerPlugin.
Definition at line 50 of file BufferEventStreamer.cc.
{
       return Event::create<BufferEvent>();
     }
StatusCode dqm4hep::core::BufferEventStreamer::read (EventPtr event, TBuffer & buffer) override virtual
De-serialize the event.
Implements dqm4hep::core::EventStreamerPlugin.
Definition at line 67 of file BufferEventStreamer.cc.
References dqm4hep::core::BufferEvent::moveBuffer().
{
       BufferEvent *bufferEvent = event->getEvent<BufferEvent>();
       Char_t *rawBuffer = nullptr;
       Int_t size = buffer.ReadArray(rawBuffer);
       bufferEvent->moveBuffer(rawBuffer, size);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::BufferEventStreamer::write (EventPtr event, TBuffer & buffer) override virtual
Serialize the event and store it into a data stream.
Implements dqm4hep::core::EventStreamerPlugin.
Definition at line 56 of file BufferEventStreamer.cc.
References dqm4hep::core::BufferEvent::buffer(), and dqm4hep::core::BufferEvent::bufferSize().
{
       const BufferEvent *bufferEvent = event->getEvent<BufferEvent>();
       if (nullptr == bufferEvent) {
         return STATUS_CODE_INVALID_PARAMETER;
       }
       buffer.WriteArray(bufferEvent->buffer(), bufferEvent->bufferSize());
       return STATUS_CODE_SUCCESS;
     }
The documentation for this class was generated from the following file:
BufferEventStreamer.cc