DQM4hep: dqm4hep::core::StatusCodeException Class Reference
dqm4hep::core::StatusCodeException Class Reference
StatusCodeException class.
#include <StatusCodes.h>
Public Member Functions
StatusCodeException (const StatusCode statusCode)
Constructor.
StatusCodeException (const StatusCodeException &e)=default
~StatusCodeException () override
Constructor.
StatusCode getStatusCode () const
Get status code.
std::string toString () const
Get status code as a string.
const std::string & getBackTrace () const
Get back trace at point of exception construction (gcc only)
Private Attributes
const StatusCode m_statusCode = {STATUS_CODE_SUCCESS}
The status code.
std::string m_backTrace = {""}
The back trace.
Detailed Description
StatusCodeException class.
Definition at line 133 of file StatusCodes.h.
Constructor & Destructor Documentation
dqm4hep::core::StatusCodeException::StatusCodeException (const StatusCode statusCode) inline
Constructor.
Definition at line 164 of file StatusCodes.h.
References m_backTrace.
                                                                                :
       m_statusCode(statusCode) {
 #if defined(__GNUC__) && defined(BACKTRACE)
       const size_t maxDepth = 100;
       void *stackAddresses[maxDepth];
       size_t stackDepth = backtrace(stackAddresses, maxDepth);
       char **stackStrings = backtrace_symbols(stackAddresses, stackDepth);
       m_backTrace = "\nBackTrace\n    ";
       for (size_t i = 1; i < stackDepth; ++i) {
         m_backTrace += stackStrings[i];
         m_backTrace += "\n    ";
       }
       free(stackStrings); // malloc()ed by backtrace_symbols
 #endif
     }
dqm4hep::core::StatusCodeException::StatusCodeException (const StatusCodeException & e) default
dqm4hep::core::StatusCodeException::~StatusCodeException () inline override
Constructor.
Definition at line 186 of file StatusCodes.h.
{
       /* nop */
     }
Member Function Documentation
const std::string & dqm4hep::core::StatusCodeException::getBackTrace () const inline
Get back trace at point of exception construction (gcc only)
Definition at line 204 of file StatusCodes.h.
References m_backTrace.
{
       return m_backTrace;
     }
StatusCode dqm4hep::core::StatusCodeException::getStatusCode () const inline
Get status code.
Definition at line 192 of file StatusCodes.h.
References m_statusCode.
Referenced by dqm4hep::core::DBInterface::connect(), dqm4hep::online::ModuleApplication::onEvent(), dqm4hep::core::MonitorElement::runQualityTests(), and dqm4hep::core::MonitorElementManager::runQualityTests().
{
       return m_statusCode;
     }
std::string dqm4hep::core::StatusCodeException::toString () const inline
Get status code as a string.
Definition at line 198 of file StatusCodes.h.
References m_statusCode, and dqm4hep::core::statusCodeToString().
Referenced by dqm4hep::core::XMLParser::parse(), dqm4hep::online::HttpRunControl::receiveEndOfRunPost(), dqm4hep::online::HttpRunControl::receiveStartOfRunPost(), dqm4hep::core::XMLParser::resolveIncludes(), dqm4hep::core::QualityTest::run(), and dqm4hep::core::MonitorElementManager::runQualityTests().
{
       return statusCodeToString(m_statusCode);
     }
Member Data Documentation
std::string dqm4hep::core::StatusCodeException::m_backTrace = {""} private
The back trace.
Definition at line 158 of file StatusCodes.h.
Referenced by getBackTrace(), and StatusCodeException().
const StatusCode dqm4hep::core::StatusCodeException::m_statusCode = {STATUS_CODE_SUCCESS} private
The status code.
Definition at line 157 of file StatusCodes.h.
Referenced by getStatusCode(), and toString().
The documentation for this class was generated from the following file:
StatusCodes.h