DQM4hep: dqm4hep::core::TiXmlVisitor Class Reference
dqm4hep::core::TiXmlVisitor Class Reference
Implements the interface to the "Visitor pattern" (see the Accept() method.) If you call the Accept() method, it requires being passed a TiXmlVisitor class to handle callbacks.
#include <tinyxml.h>
Public Member Functions
virtual ~TiXmlVisitor ()=default
virtual bool VisitEnter (const TiXmlDocument &)
Visit a document.
virtual bool VisitExit (const TiXmlDocument &)
Visit a document.
virtual bool VisitEnter (const TiXmlElement &, const TiXmlAttribute *)
Visit an element.
virtual bool VisitExit (const TiXmlElement &)
Visit an element.
virtual bool Visit (const TiXmlDeclaration &)
Visit a declaration.
virtual bool Visit (const TiXmlText &)
Visit a text node.
virtual bool Visit (const TiXmlComment &)
Visit a comment node.
virtual bool Visit (const TiXmlUnknown &)
Visit an unknow node.
Detailed Description
Implements the interface to the "Visitor pattern" (see the Accept() method.) If you call the Accept() method, it requires being passed a TiXmlVisitor class to handle callbacks.
For nodes that contain other nodes (Document, Element) you will get called with a VisitEnter/VisitExit pair. Nodes that are always leaves are simply called with Visit().
If you return 'true' from a Visit method, recursive parsing will continue. If you return false, no children of this node or its sibilings will be Visited.
All flavors of Visit methods have a default implementation that returns 'true' (continue visiting). You need to only override methods that are interesting to you.
Generally Accept() is called on the TiXmlDocument, although all nodes suppert Visiting.
You should never change the document from a callback.
See Also
TiXmlNode::Accept()
Definition at line 137 of file tinyxml.h.
Constructor & Destructor Documentation
virtual dqm4hep::core::TiXmlVisitor::~TiXmlVisitor () virtual default
Member Function Documentation
virtual bool dqm4hep::core::TiXmlVisitor::Visit (const TiXmlDeclaration &) inline virtual
Visit a declaration.
Reimplemented in dqm4hep::core::TiXmlPrinter.
Definition at line 160 of file tinyxml.h.
Referenced by dqm4hep::core::TiXmlComment::Accept(), dqm4hep::core::TiXmlText::Accept(), dqm4hep::core::TiXmlDeclaration::Accept(), and dqm4hep::core::TiXmlUnknown::Accept().
{
         return true;
       }
virtual bool dqm4hep::core::TiXmlVisitor::Visit (const TiXmlText &) inline virtual
Visit a text node.
Reimplemented in dqm4hep::core::TiXmlPrinter.
Definition at line 164 of file tinyxml.h.
{
         return true;
       }
virtual bool dqm4hep::core::TiXmlVisitor::Visit (const TiXmlComment &) inline virtual
Visit a comment node.
Reimplemented in dqm4hep::core::TiXmlPrinter.
Definition at line 168 of file tinyxml.h.
{
         return true;
       }
virtual bool dqm4hep::core::TiXmlVisitor::Visit (const TiXmlUnknown &) inline virtual
Visit an unknow node.
Reimplemented in dqm4hep::core::TiXmlPrinter.
Definition at line 172 of file tinyxml.h.
{
         return true;
       }
virtual bool dqm4hep::core::TiXmlVisitor::VisitEnter (const TiXmlDocument &) inline virtual
Visit a document.
Reimplemented in dqm4hep::core::TiXmlPrinter.
Definition at line 142 of file tinyxml.h.
Referenced by dqm4hep::core::TiXmlElement::Accept(), and dqm4hep::core::TiXmlDocument::Accept().
{
         return true;
       }
virtual bool dqm4hep::core::TiXmlVisitor::VisitEnter (const TiXmlElement & , const TiXmlAttribute *) inline virtual
Visit an element.
Reimplemented in dqm4hep::core::TiXmlPrinter.
Definition at line 151 of file tinyxml.h.
{
         return true;
       }
virtual bool dqm4hep::core::TiXmlVisitor::VisitExit (const TiXmlDocument &) inline virtual
Visit a document.
Reimplemented in dqm4hep::core::TiXmlPrinter.
Definition at line 146 of file tinyxml.h.
Referenced by dqm4hep::core::TiXmlElement::Accept(), and dqm4hep::core::TiXmlDocument::Accept().
{
         return true;
       }
virtual bool dqm4hep::core::TiXmlVisitor::VisitExit (const TiXmlElement &) inline virtual
Visit an element.
Reimplemented in dqm4hep::core::TiXmlPrinter.
Definition at line 155 of file tinyxml.h.
{
         return true;
       }
The documentation for this class was generated from the following file:
tinyxml.h