DQM4hep: dqm4hep::online::TestStandaloneModule Class Reference
dqm4hep::online::TestStandaloneModule Class Reference
Public Member Functions
TestStandaloneModule ()=default
~TestStandaloneModule ()=default
Public Member Functions inherited from dqm4hep::online::ModuleT< void >
ModuleT ()=default
Default constructor.
ModuleT (const ModuleT &)=delete
ModuleT & operator= (const ModuleT &)=delete
virtual ~ModuleT ()
Destructor.
Public Member Functions inherited from dqm4hep::online::Module
Module ()=default
Default constructor.
Module (const Module &)=delete
Module & operator= (const Module &)=delete
virtual ~Module ()
Destructor.
const std::string & name () const
Get the module name.
const std::string & detectorName () const
Get the detector name.
const core::Version & version () const
Get the module version.
Private Member Functions
void readSettings (const core::TiXmlHandle &handle)
Read the user settings from the xml handle.
void initModule ()
Initialize the module.
void startOfRun (core::Run &run)
Callback function on start of run.
void startOfCycle ()
Callback function on start of cycle.
void endOfCycle (const EOCCondition &condition)
Callback function on end of cycle The monitor elements are send to the collector after calling this function.
void endOfRun (const core::Run &run)
Callback function on end of run.
void endModule ()
Callback function before terminate.
void process ()
Callback function.
Private Attributes
std::mt19937 m_rndGen {}
std::normal_distribution m_temperatureDistribution {}
std::normal_distribution m_pressureDistribution {}
float m_meanT = {24}
float m_rmsT = {1}
float m_meanP = {1024}
float m_rmsP = {2}
OnlineElementPtr m_temperature = {nullptr}
OnlineElementPtr m_pressure = {nullptr}
Additional Inherited Members
Protected Member Functions inherited from dqm4hep::online::Module
void setDetectorName (const std::string &detector)
Set the detector name.
void setName (const std::string &module)
Set the module name.
void setVersion (unsigned int major, unsigned int minor=0, unsigned int patch=0)
Set the module version.
Detailed Description
Definition at line 26 of file TestStandaloneModule.cc.
Constructor & Destructor Documentation
dqm4hep::online::TestStandaloneModule::TestStandaloneModule () default
dqm4hep::online::TestStandaloneModule::~TestStandaloneModule () default
Member Function Documentation
void dqm4hep::online::TestStandaloneModule::endModule () private virtual
Callback function before terminate.
Implements dqm4hep::online::Module.
Definition at line 123 of file TestStandaloneModule.cc.
References dqm_info.
{
       dqm_info( "TestStandaloneModule::endModule");
     }
void dqm4hep::online::TestStandaloneModule::endOfCycle (const EOCCondition & condition) private virtual
Callback function on end of cycle The monitor elements are send to the collector after calling this function.
Parameters
condition the end of cycle conditions
Implements dqm4hep::online::Module.
Definition at line 111 of file TestStandaloneModule.cc.
References dqm_info, and dqm4hep::core::typeToString().
{
       dqm_info( "====> TestStandaloneModule::endOfCycle: {0}", core::typeToString(condition) );
     }
void dqm4hep::online::TestStandaloneModule::endOfRun (const core::Run & run) private virtual
Callback function on end of run.
User can get final run configuration from the run object
Parameters
run the run configuration
Implements dqm4hep::online::Module.
Definition at line 117 of file TestStandaloneModule.cc.
References dqm_info, and dqm4hep::core::typeToString().
{
       dqm_info( "=> TestStandaloneModule::endOfRun: {0}", core::typeToString(run) );
     }
void dqm4hep::online::TestStandaloneModule::initModule () private virtual
Initialize the module.
In this method, user should book monitor elements. See ModuleApi class.
Implements dqm4hep::online::Module.
Definition at line 76 of file TestStandaloneModule.cc.
References dqm4hep::online::ModuleApi::cd(), dqm_info, dqm4hep::online::ModuleApi::dump(), m_meanP, m_meanT, m_pressure, m_pressureDistribution, m_rmsP, m_rmsT, m_temperature, m_temperatureDistribution, dqm4hep::online::ModuleApi::mkdir(), and THROW_RESULT_IF.
{
       dqm_info( "TestStandaloneModule::initModule" );
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::mkdir(this, "Sensors"));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::cd(this, "Sensors"));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::bookObject<core::TDynamicGraph>(this,
         m_temperature, ".", "Temperature", "The temperature evolution"));
       m_temperature->objectTo<core::TDynamicGraph>()->SetRangeLength(60*60); // 1h range
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::bookObject<core::TDynamicGraph>(this,
         m_pressure, ".", "Pressure", "The pressure evolution"));
       m_pressure->objectTo<core::TDynamicGraph>()->SetRangeLength(60*60); // 1h range
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::cd(this));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, ModuleApi::dump(this));
       m_temperatureDistribution.param(std::normal_distribution<>::param_type(m_meanT, m_rmsT));
       m_pressureDistribution.param(std::normal_distribution<>::param_type(m_meanP, m_rmsP));
     }
void dqm4hep::online::TestStandaloneModule::process () private virtual
Callback function.
Fully user defined
Implements dqm4hep::online::ModuleT< void >.
Definition at line 129 of file TestStandaloneModule.cc.
References dqm_info, m_pressure, m_pressureDistribution, m_rndGen, m_temperature, and m_temperatureDistribution.
{
       auto temperature = m_temperatureDistribution(m_rndGen);
       auto pressure = m_pressureDistribution(m_rndGen);
       auto now = time(0);
       m_temperature->objectTo<core::TDynamicGraph>()->AddPoint(now, temperature);
       m_pressure->objectTo<core::TDynamicGraph>()->AddPoint(now, pressure);
       dqm_info( "========> TestStandaloneModule::process: time is {0}, T={1}, P={2}", now, temperature, pressure);
     }
void dqm4hep::online::TestStandaloneModule::readSettings (const core::TiXmlHandle & handle) private virtual
Read the user settings from the xml handle.
handle the xml handle
Implements dqm4hep::online::Module.
Definition at line 54 of file TestStandaloneModule.cc.
References dqm_info, dqm4hep::core::TiXmlHandle::Element(), m_meanP, m_meanT, m_rmsP, m_rmsT, dqm4hep::core::XmlHelper::readParameter(), dqm4hep::core::TiXmlPrinter::Str(), and THROW_RESULT_IF_AND_IF.
{
       auto element = handle.Element();
       core::TiXmlPrinter printer;
       element->Accept(&printer);
       dqm_info( "Received the following XML settings:" );
       dqm_info( "{0}", printer.Str() );
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=,
         core::XmlHelper::readParameter(handle, "TMean", m_meanT));
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=,
         core::XmlHelper::readParameter(handle, "TRms", m_rmsT));
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=,
         core::XmlHelper::readParameter(handle, "PMean", m_meanP));
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=,
         core::XmlHelper::readParameter(handle, "PRms", m_rmsP));
     }
void dqm4hep::online::TestStandaloneModule::startOfCycle () private virtual
Callback function on start of cycle.
User can take appropriate actions such as monitor element reset, etc ...
Implements dqm4hep::online::Module.
Definition at line 105 of file TestStandaloneModule.cc.
References dqm_info.
{
       dqm_info( "====> TestStandaloneModule::startOfCycle" );
     }
void dqm4hep::online::TestStandaloneModule::startOfRun (core::Run & run) private virtual
Callback function on start of run.
User can get run configuration from the run object
Parameters
run the run configuration
Implements dqm4hep::online::Module.
Definition at line 99 of file TestStandaloneModule.cc.
References dqm_info, and dqm4hep::core::typeToString().
{
       dqm_info( "=> TestStandaloneModule::startOfRun: {0}", core::typeToString(run) );
     }
Member Data Documentation
float dqm4hep::online::TestStandaloneModule::m_meanP = {1024} private
Definition at line 36 of file TestStandaloneModule.cc.
Referenced by initModule(), and readSettings().
float dqm4hep::online::TestStandaloneModule::m_meanT = {24} private
Definition at line 34 of file TestStandaloneModule.cc.
Referenced by initModule(), and readSettings().
OnlineElementPtr dqm4hep::online::TestStandaloneModule::m_pressure = {nullptr} private
Definition at line 39 of file TestStandaloneModule.cc.
Referenced by initModule(), and process().
std::normal_distribution dqm4hep::online::TestStandaloneModule::m_pressureDistribution {} private
Definition at line 33 of file TestStandaloneModule.cc.
Referenced by initModule(), and process().
float dqm4hep::online::TestStandaloneModule::m_rmsP = {2} private
Definition at line 37 of file TestStandaloneModule.cc.
Referenced by initModule(), and readSettings().
float dqm4hep::online::TestStandaloneModule::m_rmsT = {1} private
Definition at line 35 of file TestStandaloneModule.cc.
Referenced by initModule(), and readSettings().
std::mt19937 dqm4hep::online::TestStandaloneModule::m_rndGen {} private
Definition at line 31 of file TestStandaloneModule.cc.
Referenced by process().
OnlineElementPtr dqm4hep::online::TestStandaloneModule::m_temperature = {nullptr} private
Definition at line 38 of file TestStandaloneModule.cc.
Referenced by initModule(), and process().
std::normal_distribution dqm4hep::online::TestStandaloneModule::m_temperatureDistribution {} private
Definition at line 32 of file TestStandaloneModule.cc.
Referenced by initModule(), and process().
The documentation for this class was generated from the following file:
TestStandaloneModule.cc