DQM4hep: dqm4hep::net::RequestHandler::Rpc Class Reference
dqm4hep::net::RequestHandler::Rpc Class Reference
Rpc class.
Public Member Functions
Rpc (RequestHandler *pHandler)
Contructor.
Rpc (const Rpc &)=delete
Rpc & operator= (const Rpc &)=delete
void rpcHandler () override
The dim rpc handler.
Private Attributes
RequestHandler * m_pHandler = {nullptr}
The request handler owner instance.
Detailed Description
Rpc class.
The concrete dim rpc implementation
Definition at line 93 of file RequestHandler.h.
Constructor & Destructor Documentation
dqm4hep::net::RequestHandler::Rpc::Rpc (RequestHandler * pHandler)
Contructor.
Definition at line 71 of file RequestHandler.cc.
         : DimRpc((char *)pHandler->name().c_str(), "C", "C"), m_pHandler(pHandler) {
       /* nop */
     }
dqm4hep::net::RequestHandler::Rpc::Rpc (const Rpc &) delete
Member Function Documentation
Rpc& dqm4hep::net::RequestHandler::Rpc::operator= (const Rpc &) delete
void dqm4hep::net::RequestHandler::Rpc::rpcHandler () override
The dim rpc handler.
Definition at line 78 of file RequestHandler.cc.
References dqm4hep::net::Buffer::adopt(), dqm4hep::net::Buffer::begin(), and dqm4hep::net::Buffer::size().
{
       char *data = (char *)this->getData();
       int size = this->getSize();
       Buffer request;
       if (nullptr != data && size != 0)
         request.adopt(data, size);
       Buffer response;
       m_pHandler->handleRequest(request, response);
       this->setData((void *)response.begin(), response.size());
     }
Member Data Documentation
RequestHandler* dqm4hep::net::RequestHandler::Rpc::m_pHandler = {nullptr} private
The request handler owner instance.
Definition at line 108 of file RequestHandler.h.
The documentation for this class was generated from the following files:
RequestHandler.h
RequestHandler.cc