DQM4hep: dqm4hep::online::AppEventLoop Class Reference
dqm4hep::online::AppEventLoop Class Reference
#include <AppEventLoop.h>
Classes
struct QueueCompare
Public Member Functions
AppEventLoop ()
Constructor.
~AppEventLoop ()
Destructor.
void postEvent (AppEvent *pAppEvent)
Post an event in the event queue.
void sendEvent (AppEvent *pAppEvent)
Send an event, to be directly processed.
template<typename Function , typename... Args>
void processFunction (Function function, Args...args)
Safely process the function in the event loop.
void clear ()
Clear the event queue.
int exec ()
Start processing the events in the event queue.
bool running () const
Whether the event loop is running.
template<typename T >
bool connectOnEvent (T *pObject, void(T::*function)(AppEvent *))
Connect a function to callback on event processing.
template<typename T >
bool disconnectOnEvent (T *pObject)
Disconnect all functions of the specified object for event processing.
template<typename T >
bool hasEventConnection (T *pObject)
Whether the specified object has at least one connection for event processing.
void exit (int returnCode)
Exit the event loop with the specified status.
void quit ()
Exit the event loop with a return code 0.
template<typename T >
void onException (T *pObject, void(T::*function)(AppEvent *))
Add an exception handler function.
int count (int eventType)
Count the number of events of the given type currently in the event queue.
template<typename Predicate >
int count (Predicate predicate)
Count the number of events currently in the event queue satifying the unary predicate.
Private Member Functions
void processEvent (AppEvent *pAppEvent)
void timerThread ()
void addTimer (AppTimer *timer)
void startTimer (AppTimer *timer)
void stopTimer (AppTimer *timer)
void removeTimer (AppTimer *timer)
AppEventLoop & operator= (const AppEventLoop &)=delete
AppEventLoop (const AppEventLoop &)=delete
AppEventLoop (AppEventLoop &&)=delete
Private Attributes
std::set< AppEvent
*, QueueCompare > m_eventQueue = {}
std::recursive_mutex m_queueMutex = {}
std::recursive_mutex m_eventMutex = {}
std::recursive_mutex m_exceptionMutex = {}
std::recursive_mutex m_timerMutex = {}
core::Signal< AppEvent * > m_onEventSignal = {}
core::Signal< AppEvent * > m_onExceptionSignal = {}
std::atomic< bool > m_running = {false}
std::atomic< bool > m_quitFlag = {false}
std::atomic< int > m_returnCode = {0}
std::thread m_timerThread = {}
std::atomic_bool m_timerStopFlag = {false}
std::set< AppTimer * > m_timers = {}
Friends
class AppTimer
class Application
Detailed Description
Definition at line 30 of file AppEventLoop.h.
Constructor & Destructor Documentation
dqm4hep::online::AppEventLoop::AppEventLoop ()
Constructor.
Definition at line 22 of file AppEventLoop.cc.
{
     }
dqm4hep::online::AppEventLoop::~AppEventLoop ()
Destructor.
Definition at line 28 of file AppEventLoop.cc.
{
     }
dqm4hep::online::AppEventLoop::AppEventLoop (const AppEventLoop &) private delete
dqm4hep::online::AppEventLoop::AppEventLoop (AppEventLoop &&) private delete
Member Function Documentation
void dqm4hep::online::AppEventLoop::addTimer (AppTimer * timer) private
Definition at line 241 of file AppEventLoop.cc.
References m_timerMutex, and m_timers.
Referenced by dqm4hep::online::Application::createTimer().
{
       std::lock_guard<std::recursive_mutex> lock(m_timerMutex);
       m_timers.insert(timer);
     }
void dqm4hep::online::AppEventLoop::clear ()
Clear the event queue.
Definition at line 61 of file AppEventLoop.cc.
References m_eventQueue, and m_queueMutex.
{
       std::lock_guard<std::recursive_mutex> lock(m_queueMutex);
       for(auto evt : m_eventQueue) {
         delete evt;
       }
       m_eventQueue.clear();
     }
template<typename T > bool dqm4hep::online::AppEventLoop::connectOnEvent (T * pObject, void(T::*)(AppEvent *) function) inline
Connect a function to callback on event processing.
Calling this function is thread safe. Returns true if the connection has been made.
Definition at line 191 of file AppEventLoop.h.
References m_eventMutex, and m_onEventSignal.
Referenced by dqm4hep::online::Application::exec().
{
       std::lock_guard<std::recursive_mutex> lock(m_eventMutex);
       return m_onEventSignal.connect(pObject, function);
     }
int dqm4hep::online::AppEventLoop::count (int eventType)
Count the number of events of the given type currently in the event queue.
Parameters
eventType the event type
Definition at line 191 of file AppEventLoop.cc.
References m_eventQueue, and m_queueMutex.
Referenced by dqm4hep::online::Application::NetworkHandler::postCommandEvent(), dqm4hep::online::Application::NetworkHandler::postServiceContent(), and timerThread().
{
       std::lock_guard<std::recursive_mutex> lock(m_queueMutex);
       return std::count_if(m_eventQueue.begin(), m_eventQueue.end(), [&eventType](AppEvent* ptr){
         return (ptr->type() == eventType);
       });
     }
template<typename Predicate > int dqm4hep::online::AppEventLoop::count (Predicate predicate) inline
Count the number of events currently in the event queue satifying the unary predicate.
Parameters
predicate the unary predicate
Definition at line 223 of file AppEventLoop.h.
References m_eventQueue, and m_queueMutex.
{
       std::lock_guard<std::recursive_mutex> lock(m_queueMutex);
       return std::count_if(m_eventQueue.begin(), m_eventQueue.begin(), predicate);
     }
template<typename T > bool dqm4hep::online::AppEventLoop::disconnectOnEvent (T * pObject) inline
Disconnect all functions of the specified object for event processing.
Calling this function is thread safe. Returns true if all connections has been removed.
Definition at line 199 of file AppEventLoop.h.
References m_eventMutex, and m_onEventSignal.
Referenced by dqm4hep::online::Application::exec().
{
       std::lock_guard<std::recursive_mutex> lock(m_eventMutex);
       return m_onEventSignal.disconnect(pObject);
     }
int dqm4hep::online::AppEventLoop::exec ()
Start processing the events in the event queue.
This is a blocking function. To exit the event loop, post or send a QuitEvent event. Posting or sending events is thread safe, even when an event is being processed.
Definition at line 71 of file AppEventLoop.cc.
References m_eventQueue, m_queueMutex, m_quitFlag, m_returnCode, m_running, m_timerStopFlag, m_timerThread, processEvent(), and timerThread().
Referenced by dqm4hep::online::Application::exec().
{
       m_running = true;
       m_quitFlag = false;
       m_timerThread = std::thread(&AppEventLoop::timerThread, this);
       while(1) {
         if(m_quitFlag) {
           break;
         }
         // safely get the app event pointer
         AppEvent* event = nullptr;
         {
           std::lock_guard<std::recursive_mutex> lock(m_queueMutex);
           if(!m_eventQueue.empty()) {
             event = *m_eventQueue.rbegin();
             m_eventQueue.erase(event);
           }
         }
         // if no event, save cpu ressources ...
         if(nullptr == event) {
           usleep(100);
           continue;
         }
         try {
           this->processEvent(event);
         }
         catch(...) {
           m_returnCode = 1;
           break;
         }
         delete event;
         usleep(100);
       }
       m_timerStopFlag = true;
       m_timerThread.join();
       m_running = false;
       return m_returnCode.load();
     }
void dqm4hep::online::AppEventLoop::exit (int returnCode)
Exit the event loop with the specified status.
Parameters
returnCode the code to return
Definition at line 125 of file AppEventLoop.cc.
References dqm4hep::online::AppEvent::QUIT, sendEvent(), and dqm4hep::online::AppEvent::setPriority().
Referenced by dqm4hep::online::Application::exit(), and quit().
{
       auto event = new StoreEvent<int>(AppEvent::QUIT, returnCode);
       event->setPriority(100);
       this->sendEvent(event);
     }
template<typename T > bool dqm4hep::online::AppEventLoop::hasEventConnection (T * pObject) inline
Whether the specified object has at least one connection for event processing.
Calling this function is thread safe.
Definition at line 207 of file AppEventLoop.h.
References m_eventMutex, and m_onEventSignal.
{
       std::lock_guard<std::recursive_mutex> lock(m_eventMutex);
       return m_onEventSignal.isConnected(pObject);
     }
template<typename T > void dqm4hep::online::AppEventLoop::onException (T * pObject, void(T::*)(AppEvent *) function) inline
Add an exception handler function.
If no handler is specified and an exception is caught, the event loop exit imediately by throwing an exception. The event causing the exception is passed to the callback function.
Parameters
pObject the object handling the exception
function the method called on exception
Definition at line 215 of file AppEventLoop.h.
References m_exceptionMutex, and m_onExceptionSignal.
{
       std::lock_guard<std::recursive_mutex> lock(m_exceptionMutex);
       return m_onExceptionSignal.connect(pObject, function);
     }
AppEventLoop& dqm4hep::online::AppEventLoop::operator= (const AppEventLoop &) private delete
void dqm4hep::online::AppEventLoop::postEvent (AppEvent * pAppEvent)
Post an event in the event queue.
The event queue is sorted by event priority. The event pointer ownership is taken by the event loop.
Parameters
pAppEvent the event to post
Definition at line 34 of file AppEventLoop.cc.
References m_eventQueue, and m_queueMutex.
Referenced by dqm4hep::online::Cycle::endOfCycle(), dqm4hep::online::Application::NetworkHandler::postCommandEvent(), dqm4hep::online::Application::NetworkHandler::postServiceContent(), dqm4hep::online::ModuleApplication::postStandaloneProcess(), dqm4hep::online::ModuleApplication::processEndOfRun(), and dqm4hep::online::ModuleApplication::receiveEvent().
{
       if(nullptr == pAppEvent) {
         return;
       }
       // push event in the queue
       std::lock_guard<std::recursive_mutex> lock(m_queueMutex);
       m_eventQueue.insert(pAppEvent);
     }
void dqm4hep::online::AppEventLoop::processEvent (AppEvent * pAppEvent) private
Definition at line 139 of file AppEventLoop.cc.
References dqm4hep::online::StoreEvent< T >::data(), dqm_error, m_eventMutex, m_exceptionMutex, m_onEventSignal, m_onExceptionSignal, m_quitFlag, m_returnCode, dqm4hep::online::AppEvent::QUIT, and dqm4hep::online::AppEvent::type().
Referenced by exec(), and sendEvent().
{
       try {
         std::lock_guard<std::recursive_mutex> lock(m_eventMutex);
         m_onEventSignal.emit(pAppEvent);
       }
       catch(core::StatusCodeException &except) {
         std::lock_guard<std::recursive_mutex> lock(m_exceptionMutex);
         if(!m_onExceptionSignal.hasConnection()) {
           dqm_error( "EventLoop::exec(): Caught exception: {0}" , except.what() );
           throw except;
         }
         else {
           m_onExceptionSignal.emit(pAppEvent);
         }
       }
       catch(std::exception &except) {
         std::lock_guard<std::recursive_mutex> lock(m_exceptionMutex);
         if(!m_onExceptionSignal.hasConnection()) {
           dqm_error( "EventLoop::exec(): Caught exception: {0}" , except.what() );
           throw except;
         }
         else {
           m_onExceptionSignal.emit(pAppEvent);
         }
       }
       catch(...) {
         std::lock_guard<std::recursive_mutex> lock(m_exceptionMutex);
         if(!m_onExceptionSignal.hasConnection()) {
           dqm_error( "EventLoop::exec(): Caught unknown exception !" );
           throw core::StatusCodeException(core::STATUS_CODE_FAILURE);
         }
         else {
           m_onExceptionSignal.emit(pAppEvent);
         }
       }
       if(pAppEvent->type() == AppEvent::QUIT) {
         m_quitFlag = true;
         m_returnCode = 1;
         StoreEvent<int> *quitEvent = dynamic_cast<StoreEvent<int>*>(pAppEvent);
         if(quitEvent) {
           m_returnCode = quitEvent->data();
         }
       }
     }
template<typename Function , typename... Args> void dqm4hep::online::AppEventLoop::processFunction (Function function, Args... args) inline
Safely process the function in the event loop.
Parameters
function the function to process
args the function arguments
Definition at line 231 of file AppEventLoop.h.
References m_eventMutex.
Referenced by dqm4hep::online::Application::NetworkHandler::sendCommandEvent(), dqm4hep::online::Application::NetworkHandler::sendRequestEvent(), dqm4hep::online::Application::NetworkHandler::sendServiceContent(), and timerThread().
{
       std::lock_guard<std::recursive_mutex> lock(m_eventMutex);
       function(args...);
     }
void dqm4hep::online::AppEventLoop::quit ()
Exit the event loop with a return code 0.
Definition at line 133 of file AppEventLoop.cc.
References exit().
{
       this->exit(0);
     }
void dqm4hep::online::AppEventLoop::removeTimer (AppTimer * timer) private
Definition at line 266 of file AppEventLoop.cc.
References m_timerMutex, m_timers, and stopTimer().
Referenced by dqm4hep::online::Application::removeTimer().
{
       stopTimer(timer);
       std::lock_guard<std::recursive_mutex> lock(m_timerMutex);
       m_timers.erase(timer);
       delete timer;
     }
bool dqm4hep::online::AppEventLoop::running () const
Whether the event loop is running.
Definition at line 119 of file AppEventLoop.cc.
References m_running.
{
       return m_running.load();
     }
void dqm4hep::online::AppEventLoop::sendEvent (AppEvent * pAppEvent)
Send an event, to be directly processed.
The event pointer ownership is taken by the event loop.
Parameters
pAppEvent the event to send
Definition at line 45 of file AppEventLoop.cc.
References dqm_error, processEvent(), and dqm4hep::online::AppEvent::type().
Referenced by exit(), and dqm4hep::online::Application::sendClientExitEvent().
{
       if(nullptr == pAppEvent) {
         return;
       }
       // process an event
       try {
         this->processEvent(pAppEvent);
       }
       catch(...) {
         dqm_error( "AppEventLoop::sendEvent: caught exception for event {0} of type {1}", (void*)pAppEvent, pAppEvent->type() );
       }
       delete pAppEvent;
     }
void dqm4hep::online::AppEventLoop::startTimer (AppTimer * timer) private
Definition at line 248 of file AppEventLoop.cc.
References dqm4hep::online::AppTimer::m_active, dqm4hep::online::AppTimer::m_startTime, m_timerMutex, and dqm4hep::core::time::now().
Referenced by dqm4hep::online::AppTimer::setInterval(), and dqm4hep::online::AppTimer::start().
{
       std::lock_guard<std::recursive_mutex> lock(m_timerMutex);
       timer->m_startTime = core::time::now();
       timer->m_active = true;
     }
void dqm4hep::online::AppEventLoop::stopTimer (AppTimer * timer) private
Definition at line 256 of file AppEventLoop.cc.
References m_timerMutex, and m_timers.
Referenced by removeTimer(), and dqm4hep::online::AppTimer::stop().
{
       std::lock_guard<std::recursive_mutex> lock(m_timerMutex);
       auto findIter = m_timers.find(timer);
       if(m_timers.end() != findIter) {
         (*findIter)->m_active = false;
       }
     }
void dqm4hep::online::AppEventLoop::timerThread () private
Definition at line 200 of file AppEventLoop.cc.
References count(), dqm_debug, m_timerMutex, m_timers, m_timerStopFlag, dqm4hep::core::time::now(), and processFunction().
Referenced by exec().
{
       {
         // initialize start time point of all timers
         std::lock_guard<std::recursive_mutex> lock(m_timerMutex);
         for(auto timer : m_timers) {
           timer->m_startTime = core::time::now();
         }
       }
       while(not m_timerStopFlag.load()) {
         {
           std::lock_guard<std::recursive_mutex> lock(m_timerMutex);
           for(auto timer : m_timers) {
             if(timer->active()) {
               const unsigned int timeoutEllapsed = std::chrono::duration_cast<std::chrono::milliseconds>(core::time::now()-timer->m_startTime).count();
               const bool timeoutReached = (timeoutEllapsed >= timer->interval());
               if(timeoutReached) {
                 // process timer timeout in event loop
                 processFunction([timer](){
                   timer->m_signal.emit();
                 });
                 // stop it if single shot
                 if(timer->singleShot()) {
                   timer->m_active = false;
                 }
                 else {
                   timer->m_startTime = core::time::now();
                 }
               }
             }
             if(m_timerStopFlag.load()) {
               break;
             }
           }
         }
         usleep(100);
       }
       dqm_debug( "Exiting timer thread !" );
     }
Friends And Related Function Documentation
friend class Application friend
Definition at line 32 of file AppEventLoop.h.
friend class AppTimer friend
Definition at line 31 of file AppEventLoop.h.
Member Data Documentation
std::recursive_mutex dqm4hep::online::AppEventLoop::m_eventMutex = {} private
Definition at line 174 of file AppEventLoop.h.
Referenced by connectOnEvent(), disconnectOnEvent(), hasEventConnection(), processEvent(), and processFunction().
std::set<AppEvent*,QueueCompare> dqm4hep::online::AppEventLoop::m_eventQueue = {} private
Definition at line 172 of file AppEventLoop.h.
Referenced by clear(), count(), exec(), and postEvent().
std::recursive_mutex dqm4hep::online::AppEventLoop::m_exceptionMutex = {} private
Definition at line 175 of file AppEventLoop.h.
Referenced by onException(), and processEvent().
core::Signal<AppEvent *> dqm4hep::online::AppEventLoop::m_onEventSignal = {} private
Definition at line 177 of file AppEventLoop.h.
Referenced by connectOnEvent(), disconnectOnEvent(), hasEventConnection(), and processEvent().
core::Signal<AppEvent *> dqm4hep::online::AppEventLoop::m_onExceptionSignal = {} private
Definition at line 178 of file AppEventLoop.h.
Referenced by onException(), and processEvent().
std::recursive_mutex dqm4hep::online::AppEventLoop::m_queueMutex = {} private
Definition at line 173 of file AppEventLoop.h.
Referenced by clear(), count(), exec(), and postEvent().
std::atomic<bool> dqm4hep::online::AppEventLoop::m_quitFlag = {false} private
Definition at line 180 of file AppEventLoop.h.
Referenced by exec(), and processEvent().
std::atomic<int> dqm4hep::online::AppEventLoop::m_returnCode = {0} private
Definition at line 181 of file AppEventLoop.h.
Referenced by exec(), and processEvent().
std::atomic<bool> dqm4hep::online::AppEventLoop::m_running = {false} private
Definition at line 179 of file AppEventLoop.h.
Referenced by exec(), and running().
std::recursive_mutex dqm4hep::online::AppEventLoop::m_timerMutex = {} private
Definition at line 176 of file AppEventLoop.h.
Referenced by addTimer(), removeTimer(), startTimer(), stopTimer(), and timerThread().
std::set<AppTimer*> dqm4hep::online::AppEventLoop::m_timers = {} private
Definition at line 184 of file AppEventLoop.h.
Referenced by addTimer(), removeTimer(), stopTimer(), and timerThread().
std::atomic_bool dqm4hep::online::AppEventLoop::m_timerStopFlag = {false} private
Definition at line 183 of file AppEventLoop.h.
Referenced by exec(), and timerThread().
std::thread dqm4hep::online::AppEventLoop::m_timerThread = {} private
Definition at line 182 of file AppEventLoop.h.
Referenced by exec().
The documentation for this class was generated from the following files:
AppEventLoop.h
AppEventLoop.cc