DQM4hep: dqm4hep::net::WsServer Class Reference
dqm4hep::net::WsServer Class Reference
WsServer class.
#include <WebSocketServer.h>
Public Member Functions
WsServer ()
Constructor.
~WsServer ()
Destructor.
void setPort (int port)
Set the server on which to listen Can be done only before calling start()
WsService * createService (const std::string &name)
Create a new service.
WsCommandHandler * createCommandHandler (const std::string &name)
Create a command handler.
WsRequestHandler * createRequestHandler (const std::string &name)
Create a request handler.
WsService * findService (const std::string &name)
Find an existing service.
WsCommandHandler * findCommandHandler (const std::string &name)
Find an existing command handler.
WsRequestHandler * findRequestHandler (const std::string &name)
Find an exisiting request handler.
void start ()
Start the server.
void stop ()
Stop the server.
template<typename Operation >
void synchronize (Operation operation)
Synchronize a user operation with the server thread.
Private Member Functions
WsServer (const WsServer &)=delete
WsServer & operator= (const WsServer &)=delete
void onOpen (connection_hdl hdl)
void onClose (connection_hdl hdl)
void onMessage (connection_hdl hdl, message_ptr msg)
void send (WsService *service, const char *buffer, size_t size, bool containsBinary)
void onServiceMessage (const std::string &serviceName, connection_hdl hdl, message_ptr msg)
void onCommandMessage (const std::string &serviceName, connection_hdl hdl, message_ptr msg)
void onRpcMessage (const std::string &serviceName, connection_hdl hdl, message_ptr msg)
Private Attributes
connection_map m_serviceConnections = {}
The list of service connections.
server m_server
The real server implementation.
int m_port = {5555}
The server port on which to listen.
std::thread m_thread = {}
The server thread in which it runs.
ServiceMap m_serviceMap = {}
The map of all services (services, command and request handlers)
std::atomic_bool m_running = {false}
Whether the server is running.
std::recursive_mutex m_mutex = {}
The mutex to synchronize operations.
Friends
class WsService
Detailed Description
WsServer class.
Implements a websocket server with which users can:
create services to broadcast data to all clients
receive commands from clients
receive requests from clients
Definition at line 228 of file WebSocketServer.h.
Constructor & Destructor Documentation
dqm4hep::net::WsServer::WsServer (const WsServer &) private delete
dqm4hep::net::WsServer::WsServer ()
Constructor.
Definition at line 97 of file WebSocketServer.cc.
                        :
       m_server() {
     }
dqm4hep::net::WsServer::~WsServer ()
Destructor.
Definition at line 104 of file WebSocketServer.cc.
References m_serviceConnections, m_serviceMap, and stop().
{
       stop();
       for(auto &svc : m_serviceMap) {
         delete svc.second;
       }
       m_serviceConnections.clear();
       m_serviceMap.clear();
     }
Member Function Documentation
WsCommandHandler * dqm4hep::net::WsServer::createCommandHandler (const std::string & name)
Create a command handler.
If the command already exists, a nullptr is returned. Use findCommandHandler() to get an already existsing command handler. Command handlers can also be created after server start.
Parameters
name the command name
Definition at line 138 of file WebSocketServer.cc.
References dqm_error, m_mutex, and m_serviceMap.
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       auto findIter = m_serviceMap.find(name);
       if(findIter != m_serviceMap.end()) {
         dqm_error("Couldn't create service '{0}' twice", name);
         return nullptr;
       }
       WsCommandHandler *service = new WsCommandHandler(this, name);
       m_serviceMap.insert(ServiceMap::value_type(name, service));
       return service;
     }
WsRequestHandler * dqm4hep::net::WsServer::createRequestHandler (const std::string & name)
Create a request handler.
If the request handler already exists, a nullptr is returned. Use findRequestHandler() to get an already existsing request handler. Request handlers can also be created after server start.
Parameters
name the request handler name
Definition at line 152 of file WebSocketServer.cc.
References dqm_error, m_mutex, and m_serviceMap.
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       auto findIter = m_serviceMap.find(name);
       if(findIter != m_serviceMap.end()) {
         dqm_error("Couldn't create service '{0}' twice", name);
         return nullptr;
       }
       WsRequestHandler *service = new WsRequestHandler(this, name);
       m_serviceMap.insert(ServiceMap::value_type(name, service));
       return service;
     }
WsService * dqm4hep::net::WsServer::createService (const std::string & name)
Create a new service.
If the service already exists, a nullptr is returned. Use findService() to get an already existsing service. Services can also be created after server start.
Parameters
name the service name
Definition at line 123 of file WebSocketServer.cc.
References dqm_error, m_mutex, m_serviceConnections, m_serviceMap, and WsService.
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       auto findIter = m_serviceMap.find(name);
       if(findIter != m_serviceMap.end()) {
         dqm_error("Couldn't create service '{0}' twice", name);
         return nullptr;
       }
       WsService *service = new WsService(this, name);
       m_serviceMap.insert(ServiceMap::value_type(name, service));
       m_serviceConnections[name] = connection_set();
       return service;
     }
WsCommandHandler * dqm4hep::net::WsServer::findCommandHandler (const std::string & name)
Find an existing command handler.
Parameters
name the command handler name
Definition at line 180 of file WebSocketServer.cc.
References dqm4hep::net::COMMAND_TYPE, m_mutex, and m_serviceMap.
Referenced by onCommandMessage().
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       auto findIter = m_serviceMap.find(name);
       if(findIter == m_serviceMap.end()) {
         return nullptr;
       }
       if(findIter->second->type() != COMMAND_TYPE) {
         return nullptr;
       }
       return dynamic_cast<WsCommandHandler*>(findIter->second);
     }
WsRequestHandler * dqm4hep::net::WsServer::findRequestHandler (const std::string & name)
Find an exisiting request handler.
Parameters
name the request handler name
Definition at line 194 of file WebSocketServer.cc.
References m_mutex, m_serviceMap, and dqm4hep::net::RPC_TYPE.
Referenced by onRpcMessage().
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       auto findIter = m_serviceMap.find(name);
       if(findIter == m_serviceMap.end()) {
         return nullptr;
       }
       if(findIter->second->type() != RPC_TYPE) {
         return nullptr;
       }
       return dynamic_cast<WsRequestHandler*>(findIter->second);
     }
WsService * dqm4hep::net::WsServer::findService (const std::string & name)
Find an existing service.
Parameters
name the service name
Definition at line 166 of file WebSocketServer.cc.
References m_mutex, m_serviceMap, and dqm4hep::net::SERVICE_TYPE.
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       auto findIter = m_serviceMap.find(name);
       if(findIter == m_serviceMap.end()) {
         return nullptr;
       }
       if(findIter->second->type() != SERVICE_TYPE) {
         return nullptr;
       }
       return dynamic_cast<WsService*>(findIter->second);
     }
void dqm4hep::net::WsServer::onClose (connection_hdl hdl) private
Definition at line 254 of file WebSocketServer.cc.
References m_mutex, m_server, m_serviceConnections, m_serviceMap, and dqm4hep::net::SERVICE_TYPE.
Referenced by start().
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       server::connection_ptr con = m_server.get_con_from_hdl(hdl);
       const std::string serviceName = con->get_resource();
       auto findIter = m_serviceMap.find(serviceName);
       if(m_serviceMap.end() == findIter) {
         return;
       }
       // remove service subscriber (if subscribed)
       if(findIter->second->type() == SERVICE_TYPE) {
         auto findIter2 = m_serviceConnections.find(serviceName);
         if(findIter2 == m_serviceConnections.end()) {
           return;
         }
         findIter2->second.erase(con);
       }
     }
void dqm4hep::net::WsServer::onCommandMessage (const std::string & serviceName, connection_hdl hdl, message_ptr msg) private
Definition at line 348 of file WebSocketServer.cc.
References dqm4hep::core::Signal< Args >::emit(), findCommandHandler(), m_server, and dqm4hep::net::WsCommandHandler::onCommand().
Referenced by onMessage().
{
       WsCommandHandler *command = findCommandHandler(serviceName);
       if(nullptr == command) {
         m_server.close(hdl, websocketpp::close::status::normal, "Internal error: command '" + serviceName + "' not available !");
         return;
       }
       server::connection_ptr con = m_server.get_con_from_hdl(hdl);
       command->onCommand().emit(con, msg);
     }
void dqm4hep::net::WsServer::onMessage (connection_hdl hdl, message_ptr msg) private
Definition at line 274 of file WebSocketServer.cc.
References dqm4hep::net::COMMAND_TYPE, m_mutex, m_server, m_serviceMap, onCommandMessage(), onRpcMessage(), onServiceMessage(), dqm4hep::net::RPC_TYPE, and dqm4hep::net::SERVICE_TYPE.
Referenced by start().
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       server::connection_ptr con = m_server.get_con_from_hdl(hdl);
       const std::string serviceName = con->get_resource();
       auto findIter = m_serviceMap.find(serviceName);
       if(findIter == m_serviceMap.end()) {
         m_server.close(hdl, websocketpp::close::status::normal, "Service '" + serviceName + "' not available !");
         return;
       }
       // handle service subscription / unsubscription
       if(findIter->second->type() == SERVICE_TYPE) {
         onServiceMessage(serviceName, hdl, msg);
       }
       else if(findIter->second->type() == COMMAND_TYPE) {
         onCommandMessage(serviceName, hdl, msg);
       }
       else if(findIter->second->type() == RPC_TYPE) {
         onRpcMessage(serviceName, hdl, msg);
       }
       else {
         m_server.close(hdl, websocketpp::close::status::normal, "Service '" + serviceName + "' unknown type !");
         return;
       }
     }
void dqm4hep::net::WsServer::onOpen (connection_hdl hdl) private
Definition at line 248 of file WebSocketServer.cc.
Referenced by start().
{
     }
void dqm4hep::net::WsServer::onRpcMessage (const std::string & serviceName, connection_hdl hdl, message_ptr msg) private
Definition at line 360 of file WebSocketServer.cc.
References dqm4hep::core::Signal< Args >::emit(), findRequestHandler(), m_server, and dqm4hep::net::WsRequestHandler::onRequest().
Referenced by onMessage().
{
       WsRequestHandler *request = findRequestHandler(serviceName);
       if(nullptr == request) {
         m_server.close(hdl, websocketpp::close::status::normal, "Internal error: request '" + serviceName + "' not available !");
         return;
       }
       server::connection_ptr con = m_server.get_con_from_hdl(hdl);
       message_ptr responseMsg = con->get_message(websocketpp::frame::opcode::text, 0);
       request->onRequest().emit(con, msg, responseMsg);
       m_server.send(con, responseMsg);
     }
void dqm4hep::net::WsServer::onServiceMessage (const std::string & serviceName, connection_hdl hdl, message_ptr msg) private
Definition at line 316 of file WebSocketServer.cc.
References m_server, and m_serviceConnections.
Referenced by onMessage().
{
       server::connection_ptr con = m_server.get_con_from_hdl(hdl);
       auto findIter2 = m_serviceConnections.find(serviceName);
       // handle subscription/un-subscription to/from service
       if(msg->get_payload() == "subscribe") {
         if(findIter2 == m_serviceConnections.end()) {
           m_server.close(hdl, websocketpp::close::status::normal, "Internal error: service '" + serviceName + "' not available !");
           return;
         }
         // insert new subscriber
         findIter2->second.insert(con);
         m_server.send(hdl, "ok", websocketpp::frame::opcode::text);
         return;
       }
       else if(msg->get_payload() == "unsubscribe") {
         if(findIter2 == m_serviceConnections.end()) {
           m_server.close(hdl, websocketpp::close::status::normal, "Internal error: service '" + serviceName + "' not available !");
           return;
         }
         // remove subscriber
         findIter2->second.erase(con);
         m_server.send(hdl, "ok", websocketpp::frame::opcode::text);
         return;
       }
       else {
         m_server.close(hdl, websocketpp::close::status::normal, "Unknown command for service '" + serviceName + "', command: " + msg->get_payload() + " !");
         return;
       }
     }
WsServer& dqm4hep::net::WsServer::operator= (const WsServer &) private delete
void dqm4hep::net::WsServer::send (WsService * service, const char * buffer, size_t size, bool containsBinary) private
Definition at line 302 of file WebSocketServer.cc.
References m_mutex, m_server, m_serviceConnections, and dqm4hep::net::WsServiceBase::name().
Referenced by dqm4hep::net::WsService::send().
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       auto findIter = m_serviceConnections.find(service->name());
       if(findIter == m_serviceConnections.end()) {
         return;
       }
       websocketpp::frame::opcode::value opcode = containsBinary ? websocketpp::frame::opcode::binary : websocketpp::frame::opcode::text;
       for(auto &con : findIter->second) {
         m_server.send(con, buffer, size, opcode);
       }
     }
void dqm4hep::net::WsServer::setPort (int port)
Set the server on which to listen Can be done only before calling start()
Parameters
port the server port
Definition at line 115 of file WebSocketServer.cc.
References m_port, and m_running.
{
       if(not m_running.load()) {
         m_port = port;
       }
     }
void dqm4hep::net::WsServer::start ()
Start the server.
Start listening to client connections. Note that the server is started in a separate thread. To synchronize an operation with the server to avoid data race condition, use the synchronize() method.
Definition at line 208 of file WebSocketServer.cc.
References m_port, m_running, m_server, m_thread, onClose(), onMessage(), and onOpen().
{
       if(m_running.load()) {
         return;
       }
       // Set logging settings
       m_server.set_access_channels(websocketpp::log::alevel::none);
       // Initialize Asio
       m_server.init_asio();
       // Register our message handler
       m_server.set_message_handler(std::bind(&WsServer::onMessage, this, _1, _2));
       m_server.set_open_handler(std::bind(&WsServer::onOpen, this, _1));
       m_server.set_close_handler(std::bind(&WsServer::onClose, this, _1));
       // Start listening
       m_server.listen(m_port);
       // Start the server accept loop
       m_server.start_accept();
       // Start the ASIO io_service run loop
       m_thread = std::thread(&server::run, std::ref(m_server));
       m_running = true;
     }
void dqm4hep::net::WsServer::stop ()
Stop the server.
The server thread is stopped and client connections closed. The list of services, command and request handlers are NOT cleared and can be re-used. The server can be re-started using the start() method again.
Definition at line 236 of file WebSocketServer.cc.
References m_running, m_server, m_serviceConnections, and m_thread.
Referenced by ~WsServer().
{
       if(m_running.load()) {
         // std::lock_guard<std::recursive_mutex> lock(m_mutex);
         m_server.stop();
         m_thread.join();
         m_serviceConnections.clear();
         m_running = false;
       }
     }
template<typename Operation > void dqm4hep::net::WsServer::synchronize (Operation operation) inline
Synchronize a user operation with the server thread.
This can be used for updating shared data between the user code and the request and command handlers. Typical use is by using a lambda function.
Example:
server->synchronize([&](){
  shared_data = update();
});
The performed operation has to be fast in order to avoid long server operation blocking.
Definition at line 386 of file WebSocketServer.h.
References m_mutex.
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       operation();
     }
Friends And Related Function Documentation
friend class WsService friend
Definition at line 231 of file WebSocketServer.h.
Referenced by createService().
Member Data Documentation
std::recursive_mutex dqm4hep::net::WsServer::m_mutex = {} private
The mutex to synchronize operations.
Definition at line 364 of file WebSocketServer.h.
Referenced by createCommandHandler(), createRequestHandler(), createService(), findCommandHandler(), findRequestHandler(), findService(), onClose(), onMessage(), send(), and synchronize().
int dqm4hep::net::WsServer::m_port = {5555} private
The server port on which to listen.
Definition at line 356 of file WebSocketServer.h.
Referenced by setPort(), and start().
std::atomic_bool dqm4hep::net::WsServer::m_running = {false} private
Whether the server is running.
Definition at line 362 of file WebSocketServer.h.
Referenced by setPort(), start(), and stop().
server dqm4hep::net::WsServer::m_server private
The real server implementation.
Definition at line 354 of file WebSocketServer.h.
Referenced by onClose(), onCommandMessage(), onMessage(), onRpcMessage(), onServiceMessage(), send(), start(), and stop().
connection_map dqm4hep::net::WsServer::m_serviceConnections = {} private
The list of service connections.
Definition at line 352 of file WebSocketServer.h.
Referenced by createService(), onClose(), onServiceMessage(), send(), stop(), and ~WsServer().
ServiceMap dqm4hep::net::WsServer::m_serviceMap = {} private
The map of all services (services, command and request handlers)
Definition at line 360 of file WebSocketServer.h.
Referenced by createCommandHandler(), createRequestHandler(), createService(), findCommandHandler(), findRequestHandler(), findService(), onClose(), onMessage(), and ~WsServer().
std::thread dqm4hep::net::WsServer::m_thread = {} private
The server thread in which it runs.
Definition at line 358 of file WebSocketServer.h.
Referenced by start(), and stop().
The documentation for this class was generated from the following files:
WebSocketServer.h
WebSocketServer.cc