DQM4hep: dqm4hep::online::ModuleApplication Class Reference
dqm4hep::online::ModuleApplication Class Reference
ModuleApplication class.
#include <ModuleApplication.h>
Public Types
enum ModuleType { UNDEFINED_TYPE, ANALYSIS, STANDALONE }
Mode enumerator.
enum RunningMode { UNDEFINED_MODE, ONLINE, EVENT_READER }
Public Member Functions
ModuleApplication (const ModuleApplication &)=delete
ModuleApplication & operator= (const ModuleApplication &)=delete
ModuleApplication ()
Constructor.
~ModuleApplication ()
Default destructor.
ModulePtr module () const
Get the module managed by this application.
template<typename T >
T * moduleAs ()
Get a pointer to the user module dynamic casted to a certain type.
const std::string & moduleName () const
Get the module name.
const std::string & moduleType () const
Get the module type.
RunningMode appRunningMode () const
Get the application running mode.
ModuleType appModuleType () const
Get the application module type.
const RunControl & runControl () const
Get the run control.
bool allowBooking () const
Whether the application the application is in a state where booking monitor elements is allowed.
Public Member Functions inherited from dqm4hep::online::Application
Application ()=default
Default constructor.
Application (const Application &)=delete
Application & operator= (const Application &)=delete
virtual ~Application ()
Destructor.
const std::string & type () const
Get the application type.
void setType (const std::string &type)
Set the application type.
const std::string & name () const
Get the application name.
void setName (const std::string &name)
Set the application name Throw exception if called after init() is called.
const std::string & state () const
Get the application state.
void setState (const std::string &state)
Change the application state.
core::Logger::Level logLevel () const
Get the application log level.
void setLogLevel (core::Logger::Level lvl)
Get the application log level.
void createStatsEntry (const std::string &name, const std::string &unit, const std::string &description)
Create a statistics entry.
template<typename T >
void sendStat (const std::string &name, const T &stats)
Send the stat entry with a new value.
void enableStats (bool enable)
Set whether to send statistics on update.
bool statsEnabled () const
Whether the statistics are enabled.
void setNoServer (bool nosrv)
Enable or disable running the application server.
bool noServer () const
Whether the server has been disabled.
void init (int argc, char **argv)
Initialize the application.
int exec ()
Run the application.
void exit (int returnCode)
Exit the application with the specified return code If the application is running with exec(), exec will return the specified code.
bool initialized () const
Whether the application has been initialized.
bool running () const
Whether the application is running.
template<typename T >
void sendCommand (const std::string &name, const T &contents, bool blocking=false) const
Client interface.
template<typename Operation >
void sendRequest (const std::string &name, const net::Buffer &request, Operation operation)
Send a request using the net client interface.
void queuedSubscribe (const std::string &serviceName, int priority=50, int maxNEvents=std::numeric_limits< int >::max())
Subscribe to service.
template<typename Controller >
void directSubscribe (const std::string &serviceName, Controller *controller, void(Controller::*function)(const net::Buffer &))
Subscribe to service.
net::Service * createService (const std::string &name)
Server interface.
template<typename Controller >
void createRequestHandler (const std::string &requestName, Controller *controller, void(Controller::*function)(const net::Buffer &, net::Buffer &))
Create a request handler.
void createQueuedCommand (const std::string &commandName, int priority=50, int maxNEvents=std::numeric_limits< int >::max())
Create a command handler.
template<typename Controller >
void createDirectCommand (const std::string &commandName, Controller *controller, void(Controller::*function)(const net::Buffer &))
Create a command handler.
int serverClientId () const
Get the current server client id.
void sendClientExitEvent (int clientId)
Send a client exit event in the event loop.
AppTimer * createTimer ()
Create a timer synchronized with the event loop The allocated timer has to be removed by calling removeTimer()
void removeTimer (AppTimer *timer)
Remove timer.
Private Types
enum Priorities {
PROCESS_CALL = 50, END_OF_RUN = 60, END_OF_CYCLE = 70, SUBSCRIBE = 75,
START_OF_RUN = 80
}
Priorities enumerator.
using CmdLine = std::shared_ptr< TCLAP::CmdLine >
using EventClientPtr = std::shared_ptr< EventCollectorClient >
using MonitorElementManagerPtr = std::shared_ptr< core::MonitorElementManager >
using EventReaderPtr = std::shared_ptr< core::EventReader >
using ArchiverPtr = std::shared_ptr< core::Archiver >
Private Member Functions
void parseCmdLine (int argc, char **argv) override
Parse the command line arguments.
void onInit () override
Custom application initialization function.
void onEvent (AppEvent *pAppEvent) override
Process an event from the event loop.
void onStart () override
Custom user function called just before starting the event loop.
void onStop () override
Custom user function called just after exiting the event loop.
void parseSteeringFile (const std::string &fname)
Parse the input steering file.
void configureModule (core::TiXmlElement *element)
Configure the user module.
void configureCycle (core::TiXmlElement *element)
Configure the application cycle.
void configureNetwork (core::TiXmlElement *element)
Configure the network interface.
void configureEventReader (core::TiXmlElement *element)
Configure the event reader.
void configureArchiver (core::TiXmlElement *element)
Configure the archiver.
void processStartOfRun (ServiceUpdateEvent *svc)
Process the start of run service update.
void processEndOfRun ()
Process the end of run service update.
void receiveEvent (core::EventPtr event)
Receive an event from event collector and post it in the event loop.
void receiveSubscriptionList (CommandEvent *cmd)
Receive the new monitor element subscription list.
void setElementsRunNumber (core::Run &run)
Slot to set the run number of all monitor elements on start of run.
std::shared_ptr
< core::MonitorElementManager > monitorElementManager () const
Get the monitor element manager.
void postStandaloneProcess ()
Slot to post an event on standalone timer timeout.
void openArchive (core::Run &run)
Open a new archive.
void archiveAndClose (const core::Run &run)
Archive the current storage and close the archivve.
Private Attributes
std::string m_moduleType = {""}
The user module type (plugin name)
std::string m_moduleName = {""}
The user module name (runtime defined)
RunControl m_runControl = {}
The application run control.
RunningMode m_appRunningMode = {UNDEFINED_MODE}
The application running mode.
ModuleType m_appModuleType = {UNDEFINED_TYPE}
The application module type mode.
CmdLine m_cmdLine = {nullptr}
The command line argument object.
core::XMLParser m_parser = {}
The XML parser to parse the input steering file.
ModulePtr m_module = {nullptr}
The user module plugin.
Cycle m_cycle
The cycle object managing cycles in the application.
EventClientPtr m_eventCollectorClient = {nullptr}
The event collector client to receive events from collector.
std::string m_eventSourceName = {""}
The event source from the event collector.
std::atomic_uint m_currentNQueuedEvents = {0}
The current number of events in the event loop.
unsigned int m_eventQueueSize = {100}
The maximum of queued events to be processed (sub-sampling)
AppTimer * m_standaloneTimer = {nullptr}
The timer for the standalone module mode.
unsigned int m_standaloneSleep = {1000}
The time between two consecutive standalone module process (unit ms)
MonitorElementManagerPtr m_monitorElementManager = {nullptr}
The monitor element manager.
bool m_allowBooking = {false}
Whether the application for monitor element booking (state variable)
EventReaderPtr m_eventReader = {nullptr}
The event reader.
std::string m_inputArchiveName = {""}
The archiver file name as read from config.
std::string m_archiveOpenMode = {"RECREATE"}
The archiver open mode.
bool m_archiverRunNumber = {true}
Whether to name the archive file with run number.
bool m_archiverWithReferences = {false}
Whether to archive references.
bool m_allowOverwrite = {false}
Whether to allow for archive overwrite.
core::ArchiverSelector m_archiverSelector = {}
The archiver selector.
ArchiverPtr m_archiver = {nullptr}
The monitor element archiver.
Friends
class ModuleApi
Additional Inherited Members
Protected Attributes inherited from dqm4hep::online::Application
AppEventLoop m_eventLoop = {}
The application event loop.
Detailed Description
ModuleApplication class.
Definition at line 40 of file ModuleApplication.h.
Member Typedef Documentation
using dqm4hep::online::ModuleApplication::ArchiverPtr = std::shared_ptr<core::Archiver> private
Definition at line 223 of file ModuleApplication.h.
using dqm4hep::online::ModuleApplication::CmdLine = std::shared_ptr<TCLAP::CmdLine> private
Definition at line 219 of file ModuleApplication.h.
using dqm4hep::online::ModuleApplication::EventClientPtr = std::shared_ptr<EventCollectorClient> private
Definition at line 220 of file ModuleApplication.h.
using dqm4hep::online::ModuleApplication::EventReaderPtr = std::shared_ptr<core::EventReader> private
Definition at line 222 of file ModuleApplication.h.
using dqm4hep::online::ModuleApplication::MonitorElementManagerPtr = std::shared_ptr<core::MonitorElementManager> private
Definition at line 221 of file ModuleApplication.h.
Member Enumeration Documentation
enum dqm4hep::online::ModuleApplication::ModuleType
Mode enumerator.
Enumerator
UNDEFINED_TYPE
ANALYSIS
STANDALONE
Definition at line 46 of file ModuleApplication.h.
                       {
         UNDEFINED_TYPE,
         ANALYSIS,
         STANDALONE
       };
enum dqm4hep::online::ModuleApplication::Priorities private
Priorities enumerator.
Enumerator
PROCESS_CALL
END_OF_RUN
END_OF_CYCLE
SUBSCRIBE
START_OF_RUN
Definition at line 228 of file ModuleApplication.h.
                       {
         PROCESS_CALL = 50,
         END_OF_RUN = 60,
         END_OF_CYCLE = 70,
         SUBSCRIBE = 75,
         START_OF_RUN = 80
       };
enum dqm4hep::online::ModuleApplication::RunningMode
Enumerator
UNDEFINED_MODE
ONLINE
EVENT_READER
Definition at line 52 of file ModuleApplication.h.
{
         UNDEFINED_MODE,
         ONLINE,
         EVENT_READER
       };
Constructor & Destructor Documentation
dqm4hep::online::ModuleApplication::ModuleApplication (const ModuleApplication &) delete
dqm4hep::online::ModuleApplication::ModuleApplication ()
Constructor.
Definition at line 26 of file ModuleApplication.cc.
References m_monitorElementManager.
                                          :
       m_cycle(m_eventLoop) {
       m_monitorElementManager = std::make_shared<core::MonitorElementManager>();
     }
dqm4hep::online::ModuleApplication::~ModuleApplication ()
Default destructor.
Definition at line 33 of file ModuleApplication.cc.
References m_standaloneTimer, and dqm4hep::online::Application::removeTimer().
{
       removeTimer(m_standaloneTimer);
     }
Member Function Documentation
bool dqm4hep::online::ModuleApplication::allowBooking () const
Whether the application the application is in a state where booking monitor elements is allowed.
Definition at line 318 of file ModuleApplication.cc.
References m_allowBooking.
Referenced by dqm4hep::online::ModuleApi::bookHisto(), dqm4hep::online::ModuleApi::bookObject(), and dqm4hep::online::ModuleApi::bookScalar().
{
       return m_allowBooking;
     }
ModuleApplication::ModuleType dqm4hep::online::ModuleApplication::appModuleType () const
Get the application module type.
Definition at line 306 of file ModuleApplication.cc.
References m_appModuleType.
Referenced by configureNetwork(), onEvent(), onStart(), onStop(), processEndOfRun(), and processStartOfRun().
{
       return m_appModuleType;
     }
ModuleApplication::RunningMode dqm4hep::online::ModuleApplication::appRunningMode () const
Get the application running mode.
Definition at line 300 of file ModuleApplication.cc.
References m_appRunningMode.
Referenced by configureEventReader(), configureNetwork(), onEvent(), onInit(), onStart(), processEndOfRun(), and processStartOfRun().
{
       return m_appRunningMode;
     }
void dqm4hep::online::ModuleApplication::archiveAndClose (const core::Run & run) private
Archive the current storage and close the archivve.
Parameters
run the run description on end of run
Definition at line 655 of file ModuleApplication.cc.
References m_archiver, m_archiverWithReferences, m_monitorElementManager, and THROW_RESULT_IF.
Referenced by onInit().
{
       if(nullptr != m_archiver) {
         THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, m_monitorElementManager->archive(*m_archiver, m_archiverWithReferences));
         THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, m_archiver->close());
       }
     }
void dqm4hep::online::ModuleApplication::configureArchiver (core::TiXmlElement * element) private
Configure the archiver.
Parameters
element the xml element
Definition at line 497 of file ModuleApplication.cc.
References dqm4hep::core::ArchiverSelector::addSelector(), dqm_debug, dqm_error, dqm_info, dqm4hep::core::TiXmlHandle::Element(), dqm4hep::core::TiXmlHandle::FirstChildElement(), dqm4hep::core::ArchiverSelector::function(), dqm4hep::core::XmlHelper::getAttribute(), dqm4hep::core::Path::getPath(), m_allowOverwrite, m_archiveOpenMode, m_archiver, m_archiverRunNumber, m_archiverSelector, m_archiverWithReferences, m_inputArchiveName, dqm4hep::core::XmlHelper::readParameter(), THROW_RESULT_IF, and THROW_RESULT_IF_AND_IF.
Referenced by parseSteeringFile().
{
       if(nullptr == element) {
         return;
       }
       bool enableArchiver = true;
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=,
         core::XmlHelper::getAttribute(element, "enable", enableArchiver));
       if(not enableArchiver) {
         dqm_info( "The archiver has been disabled. No monitor element will be archived !" );
         return;
       }
       core::TiXmlHandle handle(element);
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=,
         core::XmlHelper::readParameter(handle, "FileName", m_inputArchiveName));
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=,
         core::XmlHelper::readParameter(handle, "AllowOverwrite", m_allowOverwrite));
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=,
         core::XmlHelper::readParameter(handle, "AppendRunNumber", m_archiverRunNumber));
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=,
         core::XmlHelper::readParameter(handle, "WriteReferences", m_archiverWithReferences));
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=,
         core::XmlHelper::readParameter(handle, "OpenMode", m_archiveOpenMode));
       // finally create our archiver
       m_archiver = std::make_shared<core::Archiver>();
       auto selectorsElement = handle.FirstChildElement("selectors").Element();
       if(nullptr != selectorsElement) {
         for(auto selectorElement = selectorsElement->FirstChildElement("selector") ;
           nullptr != selectorElement ; selectorElement = selectorElement->NextSiblingElement("selector")) {
           std::string expression;
           bool select = true;
           THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=,
             core::XmlHelper::getAttribute(selectorElement, "regex", expression));
           THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=,
             core::XmlHelper::getAttribute(selectorElement, "select", select));
           // try to compile the regex first
           try {
             std::regex reg(expression);
           }
           catch(std::regex_error) {
             dqm_error( "Archiver selector: invalid regular expression : {0}", expression );
             throw core::StatusCodeException(core::STATUS_CODE_INVALID_PARAMETER);
           }
           dqm_debug( "Archiver append selector, expression: {0}, select: {1}", expression, select );
           m_archiverSelector.addSelector([expression,select](core::MonitorElementPtr me)->bool{
             core::Path path = me->path();
             path += me->name();
             std::regex pattern(expression);
             const bool match = std::regex_match(path.getPath(), pattern);
             return select ? match : not match;
           });
         }
       }
       m_archiver->setSelectorFunction(m_archiverSelector.function());
     }
void dqm4hep::online::ModuleApplication::configureCycle (core::TiXmlElement * element) private
Configure the application cycle.
Parameters
element the xml element
Definition at line 423 of file ModuleApplication.cc.
References dqm_error, dqm_info, m_cycle, dqm4hep::core::XmlHelper::readParameter(), dqm4hep::online::Cycle::setCounterLimit(), dqm4hep::online::Cycle::setTimeout(), dqm4hep::online::Cycle::setTimerPeriod(), and THROW_RESULT_IF_AND_IF.
Referenced by parseSteeringFile().
{
       unsigned int timeout = 10;
       unsigned int period = 30;
       unsigned int counterLimit = 0;
       if(nullptr != element) {
         core::TiXmlHandle handle(element);
         THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=, core::XmlHelper::readParameter(handle, "CycleTimeout", timeout));
         THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=, core::XmlHelper::readParameter(handle, "CyclePeriod", period));
         THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=, core::XmlHelper::readParameter(handle, "CycleCounter", counterLimit));
       }
       if((timeout >= period) || (0 == period && 0 == counterLimit)) {
         dqm_error( "Invalid cycle settings: period={0}, timeout={1}, counter={2}", period, timeout, counterLimit );
         throw core::StatusCodeException(core::STATUS_CODE_INVALID_PARAMETER);
       }
       dqm_info( "== Cycle settings ==" );
       dqm_info( "=> Period:  {0}", period );
       dqm_info( "=> Timeout: {0}", timeout );
       dqm_info( "=> Counter: {0}", counterLimit );
       dqm_info( "====================" );
       m_cycle.setTimeout(timeout);
       m_cycle.setTimerPeriod(period);
       m_cycle.setCounterLimit(counterLimit);
     }
void dqm4hep::online::ModuleApplication::configureEventReader (core::TiXmlElement * element) private
Configure the event reader.
Parameters
element the xml element
Definition at line 471 of file ModuleApplication.cc.
References appRunningMode(), dqm4hep::core::PluginManager::create(), dqm_error, dqm_info, EVENT_READER, dqm4hep::core::PluginManager::instance(), m_eventReader, dqm4hep::core::XmlHelper::readParameter(), THROW_RESULT_IF, and THROW_RESULT_IF_AND_IF.
Referenced by parseSteeringFile().
{
       if(EVENT_READER != appRunningMode()) {
         return;
       }
       std::string eventReaderName, eventFileName;
       int skipNEvents = 0;
       core::TiXmlHandle handle(element);
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, core::XmlHelper::readParameter(handle, "EventReader", eventReaderName));
       m_eventReader = core::PluginManager::instance()->create<core::EventReader>(eventReaderName);
       if(nullptr == m_eventReader) {
         dqm_error( "Could not found event reader {0} in list of plugins", eventReaderName );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_FOUND);
       }
       dqm_info( "Loaded file reader plugin '{0}'", eventReaderName );
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, core::XmlHelper::readParameter(handle, "EventFileName", eventFileName));
       dqm_info( "Opening file: {0}", eventFileName );
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=, core::XmlHelper::readParameter(handle, "SkipNEvents", skipNEvents));
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, m_eventReader->open(eventFileName));
       if(0 != skipNEvents) {
         dqm_info( "Will skip {0} first events ...", skipNEvents );
         m_eventReader->skipNEvents(skipNEvents); // running offline ...
       }
     }
void dqm4hep::online::ModuleApplication::configureModule (core::TiXmlElement * element) private
Configure the user module.
Parameters
element the xml element
Definition at line 380 of file ModuleApplication.cc.
References ANALYSIS, dqm4hep::core::PluginManager::create(), dqm_error, EVENT_READER, dqm4hep::core::XmlHelper::getAttribute(), dqm4hep::core::PluginManager::instance(), m_allowBooking, m_appModuleType, m_appRunningMode, m_module, m_moduleName, m_moduleType, dqm4hep::online::Application::setName(), STANDALONE, and THROW_RESULT_IF.
Referenced by parseSteeringFile().
{
       if(m_moduleType.empty()) {
         THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, core::XmlHelper::getAttribute(element, "type", m_moduleType));
       }
       if(m_moduleName.empty()) {
         THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, core::XmlHelper::getAttribute(element, "name", m_moduleName));
       }
       if(m_moduleType.empty() or m_moduleName.empty()) {
         dqm_error( "Undefined module type and/or module name (type: {0}, name: {1}).", m_moduleType, m_moduleName );
         throw core::StatusCodeException(core::STATUS_CODE_FAILURE);
       }
       setName(m_moduleName);
       m_module = core::PluginManager::instance()->create<Module>(m_moduleType);
       if(nullptr == m_module) {
         dqm_error( "Module '{0}' not registered in plugin manager!", m_moduleType );
         dqm_error( "Please check your plugin settings (libraries, environment) and restart the application" );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_FOUND);
       }
       if(nullptr != dynamic_cast<AnalysisModule*>(m_module.get())) {
         m_appModuleType = ANALYSIS;
       }
       else if(nullptr != dynamic_cast<StandaloneModule*>(m_module.get())) {
         m_appModuleType = STANDALONE;
       }
       else {
         dqm_error( "Undefined module type, must be AnalysisModule or StandaloneModule" );
         throw core::StatusCodeException(core::STATUS_CODE_INVALID_PARAMETER);
       }
       if(m_appRunningMode == EVENT_READER and m_appModuleType != ANALYSIS) {
         dqm_error( "Application running in FileReader mode. Can run only module of type AnalysisModule" );
         throw core::StatusCodeException(core::STATUS_CODE_INVALID_PARAMETER);
       }
       m_module->setModuleApplication(this);
       const core::TiXmlHandle moduleHandle(element);
       m_allowBooking = true;
       m_module->readSettings(moduleHandle);
       m_module->initModule();
       m_allowBooking = false;
     }
void dqm4hep::online::ModuleApplication::configureNetwork (core::TiXmlElement * element) private
Configure the network interface.
Parameters
element the xml element
Definition at line 449 of file ModuleApplication.cc.
References ANALYSIS, appModuleType(), appRunningMode(), m_eventCollectorClient, m_eventQueueSize, m_eventSourceName, m_runControl, ONLINE, dqm4hep::core::XmlHelper::readParameter(), receiveEvent(), dqm4hep::online::RunControl::setName(), THROW_RESULT_IF, and THROW_RESULT_IF_AND_IF.
Referenced by parseSteeringFile().
{
       if(ONLINE != appRunningMode()) {
         return;
       }
       core::TiXmlHandle handle(element);
       std::string runControlName;
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, core::XmlHelper::readParameter(handle, "RunControl", runControlName));
       m_runControl.setName(runControlName);
       if(ANALYSIS == appModuleType()) {
         std::string eventCollector;
         THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, core::XmlHelper::readParameter(handle, "EventCollector", eventCollector));
         THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, core::XmlHelper::readParameter(handle, "EventSource", m_eventSourceName));
         THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND, !=, core::XmlHelper::readParameter(handle, "EventQueueSize", m_eventQueueSize));
         m_eventCollectorClient = std::make_shared<EventClientPtr::element_type>(eventCollector);
         m_eventCollectorClient->onEventUpdate(m_eventSourceName, this, &ModuleApplication::receiveEvent);
       }
     }
ModulePtr dqm4hep::online::ModuleApplication::module () const
Get the module managed by this application.
Definition at line 282 of file ModuleApplication.cc.
References m_module.
{
       return m_module;
     }
template<typename T > T * dqm4hep::online::ModuleApplication::moduleAs () inline
Get a pointer to the user module dynamic casted to a certain type.
Definition at line 293 of file ModuleApplication.h.
References m_module.
{
       return dynamic_cast<T*>(m_module.get());
     }
const std::string & dqm4hep::online::ModuleApplication::moduleName () const
Get the module name.
Definition at line 288 of file ModuleApplication.cc.
References m_moduleName.
{
       return m_moduleName;
     }
const std::string & dqm4hep::online::ModuleApplication::moduleType () const
Get the module type.
Definition at line 294 of file ModuleApplication.cc.
References m_moduleType.
{
       return m_moduleType;
     }
std::shared_ptr< core::MonitorElementManager > dqm4hep::online::ModuleApplication::monitorElementManager () const private
Get the monitor element manager.
Definition at line 324 of file ModuleApplication.cc.
References m_monitorElementManager.
Referenced by dqm4hep::online::ModuleApi::addQualityTest(), dqm4hep::online::ModuleApi::bookHisto(), dqm4hep::online::ModuleApi::bookObject(), dqm4hep::online::ModuleApi::bookScalar(), dqm4hep::online::ModuleApi::cd(), dqm4hep::online::ModuleApi::dirExists(), dqm4hep::online::ModuleApi::dump(), dqm4hep::online::ModuleApi::getMonitorElement(), dqm4hep::online::ModuleApi::getMonitorElements(), dqm4hep::online::ModuleApi::goUp(), dqm4hep::online::ModuleApi::mkdir(), dqm4hep::online::ModuleApi::pwd(), dqm4hep::online::ModuleApi::resetMonitorElements(), and dqm4hep::online::ModuleApi::rmdir().
{
       return m_monitorElementManager;
     }
void dqm4hep::online::ModuleApplication::onEvent (AppEvent * pAppEvent) override private virtual
Process an event from the event loop.
Parameters
pAppEvent the event to process
Implements dqm4hep::online::Application.
Definition at line 136 of file ModuleApplication.cc.
References ANALYSIS, appModuleType(), appRunningMode(), dqm4hep::online::AppEvent::COMMAND_HANDLING, dqm4hep::online::CommandEvent::commandName(), dqm4hep::online::StoreEvent< T >::data(), dqm_error, dqm_info, dqm4hep::online::AppEvent::END_OF_CYCLE, dqm4hep::online::AppEvent::END_OF_RUN, dqm4hep::online::RunControl::endCurrentRun(), dqm4hep::online::OnlineRoutes::RunControl::eor(), EVENT_READER, dqm4hep::online::Application::exit(), dqm4hep::core::StatusCodeException::getStatusCode(), dqm4hep::online::Cycle::incrementCounter(), dqm4hep::online::RunControl::isRunning(), m_currentNQueuedEvents, m_cycle, m_eventReader, m_module, m_monitorElementManager, m_runControl, m_standaloneTimer, dqm4hep::online::RunControl::name(), dqm4hep::online::Application::name(), dqm4hep::online::AppEvent::PROCESS_EVENT, processEndOfRun(), processStartOfRun(), receiveSubscriptionList(), dqm4hep::online::AppEvent::SERVICE_UPDATE, dqm4hep::online::ServiceUpdateEvent::serviceName(), dqm4hep::online::OnlineRoutes::RunControl::sor(), STANDALONE, dqm4hep::online::AppTimer::start(), dqm4hep::online::Cycle::startCycle(), dqm4hep::core::statusCodeToString(), dqm4hep::online::OnlineRoutes::ModuleApplication::subscribe(), THROW_RESULT_IF, dqm4hep::core::QReportStorage::toJson(), and dqm4hep::online::AppEvent::type().
{
       if(AppEvent::SERVICE_UPDATE == appEvent->type()) {
         ServiceUpdateEvent* svc = dynamic_cast<ServiceUpdateEvent*>(appEvent);
         // Start of run
         if(svc->serviceName() == OnlineRoutes::RunControl::sor(m_runControl.name())) {
           processStartOfRun(svc);
         }
         // End of run
         if(svc->serviceName() == OnlineRoutes::RunControl::eor(m_runControl.name())) {
           processEndOfRun();
         }
       }
       if(AppEvent::COMMAND_HANDLING == appEvent->type()) {
         CommandEvent *cmd = dynamic_cast<CommandEvent*>(appEvent);
         // update subscription list
         if(cmd->commandName() == OnlineRoutes::ModuleApplication::subscribe(name())) {
           receiveSubscriptionList(cmd);
         }
       }
       if(AppEvent::END_OF_RUN == appEvent->type()) {
         auto eorEvent = dynamic_cast<StoreEvent<core::Run>*>(appEvent);
         auto run = eorEvent->data();
         m_runControl.endCurrentRun(run.parameters());
         if(EVENT_READER == appRunningMode()) {
           dqm_info( "End of run processed. Exiting application ..." );
           this->exit(0);
         }
       }
       // process event received from the event collector
       if(AppEvent::PROCESS_EVENT == appEvent->type() and ANALYSIS == appModuleType()) {
         if(m_currentNQueuedEvents != 0) {
           m_currentNQueuedEvents--;
         }
         if(m_runControl.isRunning()) {
           auto procEvent = dynamic_cast<StoreEvent<core::EventPtr>*>(appEvent);
           auto anaModule = moduleAs<AnalysisModule>();
           anaModule->process(procEvent->data());
           m_cycle.incrementCounter();
           if(EVENT_READER == appRunningMode()) {
             auto status = m_eventReader->readNextEvent();
             // end of file ?
             if(status == core::STATUS_CODE_OUT_OF_RANGE) {
               processEndOfRun();
             }
             else if(status != core::STATUS_CODE_SUCCESS) {
               dqm_error( "Error while reading event: file reader returned status '{0}'", core::statusCodeToString(status) );
               this->exit(1);
             }
           }
         }
       }
       // generic loop
       if(AppEvent::PROCESS_EVENT == appEvent->type() and STANDALONE == appModuleType()) {
         auto standModule = moduleAs<StandaloneModule>();
         standModule->process();
         m_cycle.incrementCounter();
         m_standaloneTimer->start();
       }
       // end of cycle
       if(AppEvent::END_OF_CYCLE == appEvent->type()) {
         auto eocEvent = dynamic_cast<StoreEvent<EOCCondition>*>(appEvent);
         auto condition = eocEvent->data();
         m_module->endOfCycle(condition);
         if(condition.m_counter > 0) {
           try {
             core::QReportStorage reportStorage;
             // process quality tests
             THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, m_monitorElementManager->runQualityTests(reportStorage));
             core::json jreports;
             reportStorage.toJson(jreports);
             dqm_info( jreports.dump(2) );
             OnlineElementPtrList publishElements;
             m_monitorElementManager->iterate<OnlineElement>([&](OnlineElementPtr monitorElement){
               if(not monitorElement->publish() or not monitorElement->subscribed()){
                 return true;
               }
               publishElements.push_back(monitorElement);
               return true;
             });
             // TODO send monitor element to collector
           }
           catch(core::StatusCodeException &exception) {
             dqm_error( "Error caught at end of cycle: {0}", exception.getStatusCode() );
           }
         }
         // always restart a new cycle for standalone modules
         if(STANDALONE == appModuleType()) {
           m_module->startOfCycle();
           m_cycle.startCycle(true);
         }
         // forced end is a synonym of end of run for analysis modules
         // do not restart a cycle in this case
         if(ANALYSIS == appModuleType() and not condition.m_forcedEnd) {
           m_module->startOfCycle();
           m_cycle.startCycle(true);
         }
       }
     }
void dqm4hep::online::ModuleApplication::onInit () override private virtual
Custom application initialization function.
At this step the server is created but is not yet running. This is the place where the application should create:
all needed services
all stats entries
Implements dqm4hep::online::Application.
Definition at line 103 of file ModuleApplication.cc.
References appRunningMode(), archiveAndClose(), dqm4hep::core::Signal< Args >::connect(), dqm4hep::online::Application::createQueuedCommand(), dqm4hep::online::Application::createTimer(), dqm_info, dqm4hep::online::Module::endOfRun(), dqm4hep::online::OnlineRoutes::RunControl::eor(), EVENT_READER, m_appRunningMode, m_cycle, m_eventReader, m_module, m_runControl, m_standaloneSleep, m_standaloneTimer, dqm4hep::online::RunControl::name(), dqm4hep::online::Application::name(), dqm4hep::online::RunControl::onEndOfRun(), ONLINE, dqm4hep::online::RunControl::onStartOfRun(), dqm4hep::online::AppTimer::onTimeout(), openArchive(), postStandaloneProcess(), dqm4hep::online::Application::queuedSubscribe(), receiveEvent(), setElementsRunNumber(), dqm4hep::online::Cycle::setEventPriority(), dqm4hep::online::AppTimer::setInterval(), dqm4hep::online::AppTimer::setSingleShot(), dqm4hep::online::OnlineRoutes::RunControl::sor(), dqm4hep::online::Module::startOfRun(), and dqm4hep::online::OnlineRoutes::ModuleApplication::subscribe().
{
       dqm_info( "Module application running mode set to {0}", m_appRunningMode );
       m_standaloneTimer = createTimer();
       m_standaloneTimer->setInterval(m_standaloneSleep);
       m_standaloneTimer->setSingleShot(true);
       m_standaloneTimer->onTimeout().connect(this, &ModuleApplication::postStandaloneProcess);
       m_cycle.setEventPriority(Priorities::END_OF_CYCLE);
       m_runControl.onStartOfRun().connect(this, &ModuleApplication::setElementsRunNumber);
       m_runControl.onStartOfRun().connect(m_module.get(), &Module::startOfRun);
       m_runControl.onEndOfRun().connect(m_module.get(), &Module::endOfRun);
       m_runControl.onStartOfRun().connect(this, &ModuleApplication::openArchive);
       m_runControl.onEndOfRun().connect(this, &ModuleApplication::archiveAndClose);
       if(ONLINE == appRunningMode()) {
         queuedSubscribe(
           OnlineRoutes::RunControl::sor(m_runControl.name()),
           Priorities::START_OF_RUN
         );
         queuedSubscribe(
           OnlineRoutes::RunControl::eor(m_runControl.name()),
           Priorities::END_OF_RUN
         );
       }
       createQueuedCommand(
         OnlineRoutes::ModuleApplication::subscribe(name()),
         Priorities::SUBSCRIBE
       );
       if(EVENT_READER == appRunningMode()) {
         m_eventReader->onEventRead().connect(this, &ModuleApplication::receiveEvent);
       }
     }
void dqm4hep::online::ModuleApplication::onStart () override private virtual
Custom user function called just before starting the event loop.
At this step the internal server is already running. This function may e.g send an initial event to the event loop.
Implements dqm4hep::online::Application.
Definition at line 238 of file ModuleApplication.cc.
References ANALYSIS, appModuleType(), appRunningMode(), EVENT_READER, dqm4hep::core::Run::fromJson(), dqm4hep::online::RunControl::isRunning(), m_cycle, m_eventReader, m_module, m_runControl, m_standaloneTimer, dqm4hep::online::RunControl::name(), ONLINE, dqm4hep::online::Application::sendRequest(), STANDALONE, dqm4hep::online::AppTimer::start(), dqm4hep::online::Cycle::startCycle(), dqm4hep::online::RunControl::startNewRun(), dqm4hep::online::OnlineRoutes::RunControl::status(), and THROW_RESULT_IF.
{
       if(ONLINE == appRunningMode()) {
         // get run control status in case it is already running
         sendRequest(OnlineRoutes::RunControl::status(m_runControl.name()), net::Buffer(), [this](const net::Buffer &response){
           core::json statusJson = core::json::parse(response.begin(), response.end());
           bool rcRunning = statusJson.value<bool>("running", false);
           if(rcRunning) {
             core::json runJson = statusJson.value<core::json>("run", core::json({}));
             core::Run run;
             run.fromJson(runJson);
             m_runControl.startNewRun(run);
           }
         });
       }
       if(STANDALONE == appModuleType()) {
         m_module->startOfCycle();
         m_cycle.startCycle(true);
         m_standaloneTimer->start();
       }
       else if(ANALYSIS == appModuleType() and m_runControl.isRunning()) {
         m_module->startOfCycle();
         m_cycle.startCycle(true);
       }
       if(EVENT_READER == appRunningMode()) {
         core::Run run;
         THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, m_eventReader->runInfo(run));
         m_runControl.startNewRun(run);
         m_module->startOfCycle();
         m_cycle.startCycle();
         // read first will post an event in event loop
         THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, m_eventReader->readNextEvent());
       }
     }
void dqm4hep::online::ModuleApplication::onStop () override private virtual
Custom user function called just after exiting the event loop.
Implements dqm4hep::online::Application.
Definition at line 274 of file ModuleApplication.cc.
References appModuleType(), m_standaloneTimer, STANDALONE, and dqm4hep::online::AppTimer::stop().
{
       if(STANDALONE == appModuleType()) {
         m_standaloneTimer->stop();
       }
     }
void dqm4hep::online::ModuleApplication::openArchive (core::Run & run) private
Open a new archive.
Parameters
run the run description on start of run
Definition at line 646 of file ModuleApplication.cc.
References m_allowOverwrite, m_archiveOpenMode, m_archiver, m_archiverRunNumber, m_inputArchiveName, dqm4hep::core::Run::runNumber(), and THROW_RESULT_IF.
Referenced by onInit().
{
       if(nullptr != m_archiver) {
         const int runNumber = m_archiverRunNumber ? run.runNumber() : -1;
         THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, m_archiver->open(m_inputArchiveName, m_archiveOpenMode, m_allowOverwrite, runNumber));
       }
     }
ModuleApplication& dqm4hep::online::ModuleApplication::operator= (const ModuleApplication &) delete
void dqm4hep::online::ModuleApplication::parseCmdLine (int argc, char ** argv) override private virtual
Parse the command line arguments.
After parsing the cmd line, the application must provide a valid type and name. At this step the server is not yet created.
Parameters
argc the argc argument from the main function
argc the argv argument from the main function
Implements dqm4hep::online::Application.
Definition at line 39 of file ModuleApplication.cc.
References dqm4hep::online::OnlineRoutes::ModuleApplication::applicationType(), DQM4hep_VERSION_STR, dqm4hep::core::Logger::logLevelFromString(), dqm4hep::core::Logger::logLevels(), m_cmdLine, m_moduleName, m_moduleType, parseSteeringFile(), dqm4hep::online::Application::setLogLevel(), and dqm4hep::online::Application::setType().
{
       std::string cmdLineFooter = "Please report bug to <dqm4hep@desy.de>";
       m_cmdLine = std::make_shared<CmdLine::element_type>(cmdLineFooter, ' ', DQM4hep_VERSION_STR);
       TCLAP::ValueArg<std::string> steeringFileNameArg(
           "f"
           , "steering-file"
           , "The xml steering file for the module application"
           , true
           , ""
           , "string");
       m_cmdLine->add(steeringFileNameArg);
       core::StringVector verbosities(core::Logger::logLevels());
       TCLAP::ValuesConstraint<std::string> verbosityConstraint(verbosities);
       TCLAP::ValueArg<std::string> verbosityArg(
           "v"
           , "verbosity"
           , "The logging verbosity"
           , false
           , "info"
           , &verbosityConstraint);
       m_cmdLine->add(verbosityArg);
       TCLAP::ValueArg<std::string> moduleTypeArg(
           "t"
           , "type"
           , "The module type to run (plugin name). Overwrite the module type from steering file"
           , false
           , ""
           , "string");
       m_cmdLine->add(moduleTypeArg);
       TCLAP::ValueArg<std::string> moduleNameArg(
           "n"
           , "name"
           , "The module name to run. Overwrite the module name from steering file"
           , false
           , ""
           , "string");
       m_cmdLine->add(moduleNameArg);
       // TCLAP::MultiArg<std::string> parameterArg(
       //     "p"
       //     , "parameter"
       //     , "A parameter to replace in the application (see XmlHelper)"
       //     , false
       //     , "");
       // m_cmdLine->add(parameterArg);
       // parse command line
       m_cmdLine->parse(argc, argv);
       m_moduleType = moduleTypeArg.getValue();
       m_moduleName = moduleNameArg.getValue();
       setType(OnlineRoutes::ModuleApplication::applicationType());
       setLogLevel(core::Logger::logLevelFromString(verbosityArg.getValue()));
       parseSteeringFile(steeringFileNameArg.getValue());
     }
void dqm4hep::online::ModuleApplication::parseSteeringFile (const std::string & fname) private
Parse the input steering file.
Parameters
fname the file name to parse
Definition at line 330 of file ModuleApplication.cc.
References configureArchiver(), configureCycle(), configureEventReader(), configureModule(), configureNetwork(), dqm4hep::core::XMLParser::document(), dqm_error, dqm4hep::core::TiXmlHandle::Element(), dqm4hep::online::Application::enableStats(), EVENT_READER, dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::TiXmlHandle::FirstChildElement(), dqm4hep::core::XmlHelper::getAttribute(), m_appRunningMode, m_monitorElementManager, m_parser, m_standaloneSleep, ONLINE, dqm4hep::core::XMLParser::parse(), dqm4hep::core::XmlHelper::readParameter(), THROW_RESULT_IF, and THROW_RESULT_IF_AND_IF.
Referenced by parseCmdLine().
{
       m_parser.parse(fname);
       auto document = m_parser.document();
       const core::TiXmlHandle xmlHandle(document.RootElement());
       auto storageElement = xmlHandle.FirstChildElement("storage").Element();
       auto settingsElement = xmlHandle.FirstChildElement("settings").Element();
       auto moduleElement = xmlHandle.FirstChildElement("module").Element();
       auto archiverElement = xmlHandle.FirstChildElement("archiver").Element();
       if(nullptr != storageElement) {
         THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, m_monitorElementManager->parseStorage<OnlineElement>(storageElement));
       }
       if(nullptr == settingsElement) {
         dqm_error("parseSteeringFile: Missing <settings> section !");
         throw core::StatusCodeException(core::STATUS_CODE_NOT_FOUND);
       }
       // determine running mode
       static core::StringVector possibleModes = {"Online", "EventReader"};
       std::string runningMode;
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, core::XmlHelper::getAttribute(settingsElement,
         "mode", runningMode, [&](const std::string &value){
         return (std::find(possibleModes.begin(), possibleModes.end(), value) != possibleModes.end());
       }));
       if(runningMode == "Online") {
         m_appRunningMode = ONLINE;
       }
       else {
         m_appRunningMode = EVENT_READER;
       }
       configureModule(moduleElement);
       configureCycle(settingsElement);
       configureNetwork(settingsElement);
       configureEventReader(settingsElement);
       configureArchiver(archiverElement);
       core::TiXmlHandle settingsHandle(settingsElement);
       bool enableStatistics = false;
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND,!=,
         core::XmlHelper::readParameter(settingsHandle, "StandaloneSleepTime", m_standaloneSleep));
       THROW_RESULT_IF_AND_IF(core::STATUS_CODE_SUCCESS, core::STATUS_CODE_NOT_FOUND,!=,
         core::XmlHelper::readParameter(settingsHandle, "EnableStatistics", enableStatistics));
       enableStats(enableStatistics);
     }
void dqm4hep::online::ModuleApplication::postStandaloneProcess () private
Slot to post an event on standalone timer timeout.
Definition at line 638 of file ModuleApplication.cc.
References dqm4hep::online::Application::m_eventLoop, dqm4hep::core::time::now(), dqm4hep::online::AppEventLoop::postEvent(), PROCESS_CALL, dqm4hep::online::AppEvent::PROCESS_EVENT, and dqm4hep::online::AppEvent::setPriority().
Referenced by onInit().
{
       auto *processEvent = new StoreEvent<core::time::point>(AppEvent::PROCESS_EVENT, core::time::now());
       processEvent->setPriority(ModuleApplication::PROCESS_CALL);
       m_eventLoop.postEvent(processEvent);
     }
void dqm4hep::online::ModuleApplication::processEndOfRun () private
Process the end of run service update.
Definition at line 571 of file ModuleApplication.cc.
References ANALYSIS, appModuleType(), appRunningMode(), dqm4hep::online::RunControl::currentRun(), dqm4hep::online::AppEvent::END_OF_RUN, END_OF_RUN, dqm4hep::online::Cycle::forceStopCycle(), m_cycle, m_eventCollectorClient, dqm4hep::online::Application::m_eventLoop, m_eventSourceName, m_runControl, ONLINE, dqm4hep::online::AppEventLoop::postEvent(), and dqm4hep::online::AppEvent::setPriority().
Referenced by onEvent().
{
       if(ANALYSIS == appModuleType() and ONLINE == appRunningMode()) {
         m_eventCollectorClient->stopEventUpdates(m_eventSourceName);
       }
       // end cycle only for analysis module case
       // standalone modules never stops
       if(ANALYSIS == appModuleType()) {
         m_cycle.forceStopCycle(true, true);
       }
       auto eorEvent = new StoreEvent<core::Run>(AppEvent::END_OF_RUN, m_runControl.currentRun());
       eorEvent->setPriority(ModuleApplication::END_OF_RUN);
       m_eventLoop.postEvent(eorEvent);
     }
void dqm4hep::online::ModuleApplication::processStartOfRun (ServiceUpdateEvent * svc) private
Process the start of run service update.
Parameters
svc the service update content
Definition at line 554 of file ModuleApplication.cc.
References ANALYSIS, appModuleType(), appRunningMode(), dqm4hep::net::Buffer::begin(), dqm4hep::online::ServiceUpdateEvent::buffer(), dqm_info, dqm4hep::net::Buffer::end(), dqm4hep::core::Run::fromJson(), m_cycle, m_eventCollectorClient, m_eventSourceName, m_module, m_runControl, ONLINE, dqm4hep::online::Cycle::startCycle(), and dqm4hep::online::RunControl::startNewRun().
Referenced by onEvent().
{
       core::json runJson = core::json::parse(svc->buffer().begin(), svc->buffer().end());
       core::Run run;
       run.fromJson(runJson);
       dqm_info( "Starting new run {0}", run.runNumber() );
       m_runControl.startNewRun(run);
       if(ANALYSIS == appModuleType()) {
         m_module->startOfCycle();
         m_cycle.startCycle();
         if(ONLINE == appRunningMode()) {
           m_eventCollectorClient->startEventUpdates(m_eventSourceName);
         }
       }
     }
void dqm4hep::online::ModuleApplication::receiveEvent (core::EventPtr event) private
Receive an event from event collector and post it in the event loop.
Parameters
event an event from the event collector
Definition at line 587 of file ModuleApplication.cc.
References m_currentNQueuedEvents, dqm4hep::online::Application::m_eventLoop, m_eventQueueSize, dqm4hep::online::AppEventLoop::postEvent(), PROCESS_CALL, dqm4hep::online::AppEvent::PROCESS_EVENT, and dqm4hep::online::AppEvent::setPriority().
Referenced by configureNetwork(), and onInit().
{
       if(m_currentNQueuedEvents.load() >= m_eventQueueSize) {
         return;
       }
       auto appEvent = new StoreEvent<core::EventPtr>(AppEvent::PROCESS_EVENT, event);
       appEvent->setPriority(ModuleApplication::PROCESS_CALL);
       m_eventLoop.postEvent(appEvent);
       m_currentNQueuedEvents++;
     }
void dqm4hep::online::ModuleApplication::receiveSubscriptionList (CommandEvent * cmd) private
Receive the new monitor element subscription list.
Parameters
cmd the network command buffer (json)
Definition at line 599 of file ModuleApplication.cc.
References dqm4hep::net::Buffer::begin(), dqm4hep::online::CommandEvent::buffer(), dqm_error, dqm_info, dqm_warning, dqm4hep::net::Buffer::end(), and m_monitorElementManager.
Referenced by onEvent().
{
       core::json jsubscription = nullptr;
       try {
         jsubscription = core::json::parse(cmd->buffer().begin(), cmd->buffer().end());
       }
       catch(...) {
         dqm_error( "Caught exception: Couldn't update monitor element subscription list !" );
         return;
       }
       if(not jsubscription.is_array()) {
         dqm_error( "Monitor element subscription json object is not a list !" );
         return;
       }
       for(auto &element : jsubscription) {
         auto path = element.value<std::string>("path", "");
         auto eltName = element.value<std::string>("name", "");
         auto subscribe = element.value<bool>("sub", false);
         OnlineElementPtr monitorElement = nullptr;
         if(core::STATUS_CODE_SUCCESS != m_monitorElementManager->getMonitorElement(path, eltName, monitorElement)) {
           dqm_warning( "While updating subscription list: couldn't find element path'{0}', name '{1}'", path, eltName );
           continue;
         }
         monitorElement->setSubscribed(subscribe);
         dqm_info( "Monitor element: path {0}, name {1} has been {2}subscribed", path, eltName, subscribe ? "" : "un-" );
       }
     }
const RunControl & dqm4hep::online::ModuleApplication::runControl () const
Get the run control.
Definition at line 312 of file ModuleApplication.cc.
References m_runControl.
{
       return m_runControl;
     }
void dqm4hep::online::ModuleApplication::setElementsRunNumber (core::Run & run) private
Slot to set the run number of all monitor elements on start of run.
Parameters
run the run description
Definition at line 629 of file ModuleApplication.cc.
References m_monitorElementManager, and dqm4hep::core::Run::runNumber().
Referenced by onInit().
{
       m_monitorElementManager->iterate<OnlineElement>([&](OnlineElementPtr monitorElement){
         monitorElement->setRunNumber(run.runNumber());
         return true;
       });
     }
Friends And Related Function Documentation
friend class ModuleApi friend
Definition at line 41 of file ModuleApplication.h.
Member Data Documentation
bool dqm4hep::online::ModuleApplication::m_allowBooking = {false} private
Whether the application for monitor element booking (state variable)
Definition at line 270 of file ModuleApplication.h.
Referenced by allowBooking(), and configureModule().
bool dqm4hep::online::ModuleApplication::m_allowOverwrite = {false} private
Whether to allow for archive overwrite.
Definition at line 282 of file ModuleApplication.h.
Referenced by configureArchiver(), and openArchive().
ModuleType dqm4hep::online::ModuleApplication::m_appModuleType = {UNDEFINED_TYPE} private
The application module type mode.
Definition at line 246 of file ModuleApplication.h.
Referenced by appModuleType(), and configureModule().
RunningMode dqm4hep::online::ModuleApplication::m_appRunningMode = {UNDEFINED_MODE} private
The application running mode.
Definition at line 244 of file ModuleApplication.h.
Referenced by appRunningMode(), configureModule(), onInit(), and parseSteeringFile().
std::string dqm4hep::online::ModuleApplication::m_archiveOpenMode = {"RECREATE"} private
The archiver open mode.
Definition at line 276 of file ModuleApplication.h.
Referenced by configureArchiver(), and openArchive().
ArchiverPtr dqm4hep::online::ModuleApplication::m_archiver = {nullptr} private
The monitor element archiver.
Definition at line 286 of file ModuleApplication.h.
Referenced by archiveAndClose(), configureArchiver(), and openArchive().
bool dqm4hep::online::ModuleApplication::m_archiverRunNumber = {true} private
Whether to name the archive file with run number.
Definition at line 278 of file ModuleApplication.h.
Referenced by configureArchiver(), and openArchive().
core::ArchiverSelector dqm4hep::online::ModuleApplication::m_archiverSelector = {} private
The archiver selector.
Definition at line 284 of file ModuleApplication.h.
Referenced by configureArchiver().
bool dqm4hep::online::ModuleApplication::m_archiverWithReferences = {false} private
Whether to archive references.
Definition at line 280 of file ModuleApplication.h.
Referenced by archiveAndClose(), and configureArchiver().
CmdLine dqm4hep::online::ModuleApplication::m_cmdLine = {nullptr} private
The command line argument object.
Definition at line 248 of file ModuleApplication.h.
Referenced by parseCmdLine().
std::atomic_uint dqm4hep::online::ModuleApplication::m_currentNQueuedEvents = {0} private
The current number of events in the event loop.
Definition at line 260 of file ModuleApplication.h.
Referenced by onEvent(), and receiveEvent().
Cycle dqm4hep::online::ModuleApplication::m_cycle private
The cycle object managing cycles in the application.
Definition at line 254 of file ModuleApplication.h.
Referenced by configureCycle(), onEvent(), onInit(), onStart(), processEndOfRun(), and processStartOfRun().
EventClientPtr dqm4hep::online::ModuleApplication::m_eventCollectorClient = {nullptr} private
The event collector client to receive events from collector.
Definition at line 256 of file ModuleApplication.h.
Referenced by configureNetwork(), processEndOfRun(), and processStartOfRun().
unsigned int dqm4hep::online::ModuleApplication::m_eventQueueSize = {100} private
The maximum of queued events to be processed (sub-sampling)
Definition at line 262 of file ModuleApplication.h.
Referenced by configureNetwork(), and receiveEvent().
EventReaderPtr dqm4hep::online::ModuleApplication::m_eventReader = {nullptr} private
The event reader.
Definition at line 272 of file ModuleApplication.h.
Referenced by configureEventReader(), onEvent(), onInit(), and onStart().
std::string dqm4hep::online::ModuleApplication::m_eventSourceName = {""} private
The event source from the event collector.
Definition at line 258 of file ModuleApplication.h.
Referenced by configureNetwork(), processEndOfRun(), and processStartOfRun().
std::string dqm4hep::online::ModuleApplication::m_inputArchiveName = {""} private
The archiver file name as read from config.
Definition at line 274 of file ModuleApplication.h.
Referenced by configureArchiver(), and openArchive().
ModulePtr dqm4hep::online::ModuleApplication::m_module = {nullptr} private
The user module plugin.
Definition at line 252 of file ModuleApplication.h.
Referenced by configureModule(), module(), moduleAs(), onEvent(), onInit(), onStart(), and processStartOfRun().
std::string dqm4hep::online::ModuleApplication::m_moduleName = {""} private
The user module name (runtime defined)
Definition at line 240 of file ModuleApplication.h.
Referenced by configureModule(), moduleName(), and parseCmdLine().
std::string dqm4hep::online::ModuleApplication::m_moduleType = {""} private
The user module type (plugin name)
Definition at line 238 of file ModuleApplication.h.
Referenced by configureModule(), moduleType(), and parseCmdLine().
MonitorElementManagerPtr dqm4hep::online::ModuleApplication::m_monitorElementManager = {nullptr} private
The monitor element manager.
Definition at line 268 of file ModuleApplication.h.
Referenced by archiveAndClose(), ModuleApplication(), monitorElementManager(), onEvent(), parseSteeringFile(), receiveSubscriptionList(), and setElementsRunNumber().
core::XMLParser dqm4hep::online::ModuleApplication::m_parser = {} private
The XML parser to parse the input steering file.
Definition at line 250 of file ModuleApplication.h.
Referenced by parseSteeringFile().
RunControl dqm4hep::online::ModuleApplication::m_runControl = {} private
The application run control.
Definition at line 242 of file ModuleApplication.h.
Referenced by configureNetwork(), onEvent(), onInit(), onStart(), processEndOfRun(), processStartOfRun(), and runControl().
unsigned int dqm4hep::online::ModuleApplication::m_standaloneSleep = {1000} private
The time between two consecutive standalone module process (unit ms)
Definition at line 266 of file ModuleApplication.h.
Referenced by onInit(), and parseSteeringFile().
AppTimer* dqm4hep::online::ModuleApplication::m_standaloneTimer = {nullptr} private
The timer for the standalone module mode.
Definition at line 264 of file ModuleApplication.h.
Referenced by onEvent(), onInit(), onStart(), onStop(), and ~ModuleApplication().
The documentation for this class was generated from the following files:
ModuleApplication.h
ModuleApplication.cc