DQM4hep: dqm4hep::online::Application Class Reference
dqm4hep::online::Application Class Reference abstract
Application class.
#include <Application.h>
Classes
class NetworkHandler
NetworkHandler class.
Public Member Functions
Application ()=default
Default constructor.
Application (const Application &)=delete
Application & operator= (const Application &)=delete
virtual ~Application ()
Destructor.
virtual void parseCmdLine (int argc, char **argv)=0
Parse the command line arguments.
virtual void onInit ()=0
Custom application initialization function.
virtual void onEvent (AppEvent *pAppEvent)=0
Process an event from the event loop.
virtual void onStart ()=0
Custom user function called just before starting the event loop.
virtual void onStop ()=0
Custom user function called just after exiting the event loop.
const std::string & type () const
Get the application type.
void setType (const std::string &type)
Set the application type.
const std::string & name () const
Get the application name.
void setName (const std::string &name)
Set the application name Throw exception if called after init() is called.
const std::string & state () const
Get the application state.
void setState (const std::string &state)
Change the application state.
core::Logger::Level logLevel () const
Get the application log level.
void setLogLevel (core::Logger::Level lvl)
Get the application log level.
void createStatsEntry (const std::string &name, const std::string &unit, const std::string &description)
Create a statistics entry.
template<typename T >
void sendStat (const std::string &name, const T &stats)
Send the stat entry with a new value.
void enableStats (bool enable)
Set whether to send statistics on update.
bool statsEnabled () const
Whether the statistics are enabled.
void setNoServer (bool nosrv)
Enable or disable running the application server.
bool noServer () const
Whether the server has been disabled.
void init (int argc, char **argv)
Initialize the application.
int exec ()
Run the application.
void exit (int returnCode)
Exit the application with the specified return code If the application is running with exec(), exec will return the specified code.
bool initialized () const
Whether the application has been initialized.
bool running () const
Whether the application is running.
template<typename T >
void sendCommand (const std::string &name, const T &contents, bool blocking=false) const
Client interface.
template<typename Operation >
void sendRequest (const std::string &name, const net::Buffer &request, Operation operation)
Send a request using the net client interface.
void queuedSubscribe (const std::string &serviceName, int priority=50, int maxNEvents=std::numeric_limits< int >::max())
Subscribe to service.
template<typename Controller >
void directSubscribe (const std::string &serviceName, Controller *controller, void(Controller::*function)(const net::Buffer &))
Subscribe to service.
net::Service * createService (const std::string &name)
Server interface.
template<typename Controller >
void createRequestHandler (const std::string &requestName, Controller *controller, void(Controller::*function)(const net::Buffer &, net::Buffer &))
Create a request handler.
void createQueuedCommand (const std::string &commandName, int priority=50, int maxNEvents=std::numeric_limits< int >::max())
Create a command handler.
template<typename Controller >
void createDirectCommand (const std::string &commandName, Controller *controller, void(Controller::*function)(const net::Buffer &))
Create a command handler.
int serverClientId () const
Get the current server client id.
void sendClientExitEvent (int clientId)
Send a client exit event in the event loop.
AppTimer * createTimer ()
Create a timer synchronized with the event loop The allocated timer has to be removed by calling removeTimer()
void removeTimer (AppTimer *timer)
Remove timer.
Protected Attributes
AppEventLoop m_eventLoop = {}
The application event loop.
Private Types
using NetworkHandlerPtr = std::shared_ptr< NetworkHandler >
using NetworkHandlerPtrMap = std::map< const std::string, NetworkHandlerPtr >
using ServerPtr = std::shared_ptr< net::Server >
using LoggerPtr = core::Logger::LoggerPtr
using LogLevel = core::Logger::Level
using Service = net::Service
using Client = net::Client
Private Member Functions
void sendAppStats ()
Send application statistics.
void createInternalStats ()
Create the internal stat entries (memory, CPU, etc ...)
Private Attributes
std::string m_type = {""}
The application type.
std::string m_name = {""}
The application name.
std::string m_state = {"Unknown"}
The application state.
bool m_running = {false}
Whether the application is running.
bool m_initialized = {false}
Whether the application is initialized.
bool m_statsEnabled = {true}
Whether the application statistics are available.
core::ProcessStats m_stats = {}
The application statistics.
bool m_noServer = {false}
ServerPtr m_server = {nullptr}
The main server interface of the application.
Service * m_pAppStateService = {nullptr}
The service for application state, updated when the state changes.
Client m_client = {}
The main client interface of the application.
NetworkHandlerPtrMap m_serviceHandlerPtrMap = {}
The map handling service updates from the client interface.
NetworkHandlerPtrMap m_requestHandlerPtrMap = {}
The map handling request handlers from the server interface.
NetworkHandlerPtrMap m_commandHandlerPtrMap = {}
The map handling command handlers from the server interface.
core::json m_statistics = {}
The json value handling the application statistics.
LoggerPtr m_logger = {nullptr}
The application logger.
LogLevel m_logLevel = {spdlog::level::info}
The logger log level.
AppTimer * m_appStatTimer = {nullptr}
Detailed Description
Application class.
Definition at line 31 of file Application.h.
Member Typedef Documentation
using dqm4hep::online::Application::Client = net::Client private
Definition at line 451 of file Application.h.
using dqm4hep::online::Application::LoggerPtr = core::Logger::LoggerPtr private
Definition at line 448 of file Application.h.
using dqm4hep::online::Application::LogLevel = core::Logger::Level private
Definition at line 449 of file Application.h.
using dqm4hep::online::Application::NetworkHandlerPtr = std::shared_ptr<NetworkHandler> private
Definition at line 445 of file Application.h.
using dqm4hep::online::Application::NetworkHandlerPtrMap = std::map<const std::string, NetworkHandlerPtr> private
Definition at line 446 of file Application.h.
using dqm4hep::online::Application::ServerPtr = std::shared_ptr<net::Server> private
Definition at line 447 of file Application.h.
using dqm4hep::online::Application::Service = net::Service private
Definition at line 450 of file Application.h.
Constructor & Destructor Documentation
dqm4hep::online::Application::Application () default
Default constructor.
dqm4hep::online::Application::Application (const Application &) delete
dqm4hep::online::Application::~Application () virtual
Destructor.
Definition at line 23 of file Application.cc.
References m_appStatTimer, and removeTimer().
{
       removeTimer(m_appStatTimer);
     }
Member Function Documentation
template<typename Controller > void dqm4hep::online::Application::createDirectCommand (const std::string & commandName, Controller * controller, void(Controller::*)(const net::Buffer &) function) inline
Create a command handler.
On command reception, the content is posted using the sendEvent() function with a CommandEvent event. The received command buffer is not copied but directly passed to the user. The buffer can be accessed using the method CommandEvent::buffer() in the callback method Application::onEvent(). ATTN! The server thread will not be released until the event has been processed by the sendEvent method !
Parameters
commandName the command name to subscribe
Definition at line 591 of file Application.h.
References dqm_error, m_commandHandlerPtrMap, m_eventLoop, m_server, and dqm4hep::online::Application::NetworkHandler::sendCommandEvent().
Referenced by dqm4hep::online::EventCollector::onInit().
{
       if(not m_server) {
         dqm_error( "Application::createDirectCommand(): couldn't create command handler '{0}', server is not yet allocated", commandName );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_INITIALIZED);
       }
       auto findIter = m_commandHandlerPtrMap.find(commandName);
       if(m_commandHandlerPtrMap.end() != findIter) {
         dqm_error( "Application::createDirectCommand(): couldn't create command handler '{0}' twice", commandName );
         throw core::StatusCodeException(core::STATUS_CODE_ALREADY_PRESENT);
       }
       auto handler = std::make_shared<NetworkHandler>(m_eventLoop, commandName, controller, function);
       m_commandHandlerPtrMap.insert(NetworkHandlerPtrMap::value_type(commandName, handler));
       m_server->createCommandHandler(commandName, handler.get(), &Application::NetworkHandler::sendCommandEvent);
     }
void dqm4hep::online::Application::createInternalStats () private
Create the internal stat entries (memory, CPU, etc ...)
Definition at line 377 of file Application.cc.
References createStatsEntry(), dqm4hep::core::ProcessStats::lastPollTime, m_stats, and dqm4hep::core::procStats().
Referenced by init().
{
       // Virtual memory
       createStatsEntry("VmProc", "Mo", "The current virtual memory in use by the application (unit Mo)");
       createStatsEntry("VmTotal", "%", "The current virtual memory percentage in use by the application compared to the total available on the host (unit %)");
       createStatsEntry("VmInUse", "%", "The current virtual memory percentage in use by the application compared to the total used by the running processes (unit %)");
       // Resident set size
       createStatsEntry("RSSProc", "Mo", "The current resident set size memory in use by the application (unit Mo)");
       createStatsEntry("RSSTotal", "%", "The current resident set size memory percentage in use by the application compared to the total available on the host (unit %)");
       createStatsEntry("RSSInUse", "%", "The current resident set size memory percentage in use by the application compared to the total used by the running processes (unit %)");
       // Cpu
       createStatsEntry("CpuUser", "%", "The current user cpu load of the application (unit %)");
       createStatsEntry("CpuSys", "%", "The current system cpu load of the application (unit %)");
       createStatsEntry("CpuTotal", "%", "The current total cpu load of the application (unit %)");
       // Last Update
       createStatsEntry("LastUpdate", "%Y-%m-%d %H:%M:%S", "The time the last statistics update occured (unit %Y-%m-%d %H:%M:%S)");
       // Network
       // createStatsEntry("CPU", "%", "The current resident set size memory in use by the application (unit Mo)");
       // createStatsEntry("CPU", "%", "The current resident set size memory percentage in use by the application compare to the total available on the host (unit %)");
       // createStatsEntry("CPU", "%", "The current resident set size memory percentage in use by the application compare to the total used by the running processes (unit %)");
       // Initialise first reading
       struct timeval timeStart;
       gettimeofday(&timeStart, NULL);
       m_stats.lastPollTime = timeStart;
       core::procStats(m_stats);
     }
void dqm4hep::online::Application::createQueuedCommand (const std::string & commandName, int priority = 50, int maxNEvents = std::numeric_limits<int>::max())
Create a command handler.
On command reception, the content is posted using the postEvent() function with a CommandEvent event. The received service buffer is copied and can be accessed using the method CommandEvent::buffer() in the callback method Application::onEvent(). A maximum limit of posted event from the command can be set using the argument maxNEvents. If this limit is reached, the command handling is not posted.
Parameters
commandName the command name to handle
priority the priority of the event in the event queue
maxNEvents the maximum number of event for this command to post
Definition at line 304 of file Application.cc.
References dqm_error, m_commandHandlerPtrMap, m_eventLoop, m_server, noServer(), and dqm4hep::online::Application::NetworkHandler::postCommandEvent().
Referenced by dqm4hep::online::ModuleApplication::onInit().
{
       if(noServer()){
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       }
       if(not m_server) {
         dqm_error( "Application::createQueuedCommand(): couldn't create command handler '{0}', server is not yet allocated", commandName );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_INITIALIZED);
       }
       auto findIter = m_commandHandlerPtrMap.find(commandName);
       if(m_commandHandlerPtrMap.end() != findIter) {
         dqm_error( "Application::createQueuedCommand(): couldn't create command handler '{0}' twice", commandName );
         throw core::StatusCodeException(core::STATUS_CODE_ALREADY_PRESENT);
       }
       auto handler = std::make_shared<NetworkHandler>(m_eventLoop, commandName, priority, maxNEvents);
       m_commandHandlerPtrMap.insert(NetworkHandlerPtrMap::value_type(commandName, handler));
       m_server->createCommandHandler(commandName, handler.get(), &Application::NetworkHandler::postCommandEvent);
     }
template<typename Controller > void dqm4hep::online::Application::createRequestHandler (const std::string & requestName, Controller * controller, void(Controller::*)(const net::Buffer &, net::Buffer &) function) inline
Create a request handler.
On request, the request content is posted using the sendEvent() function with a RequestEvent event. The received service buffer is not copied but directly passed to the user. The request buffer and the response buffer can be accessed respectively using the method RequestEvent::request() and RequestEvent::response() in the callback method Application::onEvent(). ATTN! The server thread will not be released until the event has been processed by the sendEvent method !
Parameters
requestName the request name to handle
Definition at line 571 of file Application.h.
References dqm_error, m_eventLoop, m_requestHandlerPtrMap, m_server, m_serviceHandlerPtrMap, and dqm4hep::online::Application::NetworkHandler::sendRequestEvent().
Referenced by dqm4hep::online::EventCollector::onInit().
{
       if(not m_server) {
         dqm_error( "Application::createRequestHandler(): couldn't create request handler '{0}', server is not yet allocated", requestName );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_INITIALIZED);
       }
       auto findIter = m_requestHandlerPtrMap.find(requestName);
       if(m_requestHandlerPtrMap.end() != findIter) {
         dqm_error( "Application::createRequestHandler(): couldn't create twice request handler '{0}'", requestName );
         throw core::StatusCodeException(core::STATUS_CODE_ALREADY_PRESENT);
       }
       auto handler = std::make_shared<NetworkHandler>(m_eventLoop, requestName, controller, function);
       m_serviceHandlerPtrMap.insert(NetworkHandlerPtrMap::value_type(requestName, handler));
       m_server->createRequestHandler(requestName, handler.get(), &Application::NetworkHandler::sendRequestEvent);
     }
net::Service * dqm4hep::online::Application::createService (const std::string & name)
Server interface.
Create a new service
Parameters
name the service name
Definition at line 291 of file Application.cc.
References dqm_error, m_server, and noServer().
Referenced by dqm4hep::online::EventCollector::handleRegistration().
{
       if(noServer()){
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       }
       if(not m_server) {
         dqm_error( "Application::createService(): couldn't create service '{0}', server is not yet allocated", sname );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_INITIALIZED);
       }
       return m_server->createService(sname);
     }
void dqm4hep::online::Application::createStatsEntry (const std::string & name, const std::string & unit, const std::string & description)
Create a statistics entry.
Parameters
name the stat entry name
unit the stat entry unit
description the stat entry description
Definition at line 94 of file Application.cc.
References dqm_debug, dqm_error, initialized(), and m_statistics.
Referenced by createInternalStats(), and dqm4hep::online::EventCollector::onInit().
{
       if(initialized()) {
         dqm_error( "Application::createStatsEntry(): Couldn't create stat entry, app is already initialized !" );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       }
       if(not m_statistics[entryName].is_null())
         throw core::StatusCodeException(core::STATUS_CODE_ALREADY_PRESENT);
       // add stat entry
       m_statistics[entryName] = {
         {"description", description},
         {"unit", unit}
       };
       dqm_debug( "Creating stat entry '{0}' (unit {1}): {2}", entryName, unit, description );
     }
AppTimer * dqm4hep::online::Application::createTimer ()
Create a timer synchronized with the event loop The allocated timer has to be removed by calling removeTimer()
Definition at line 410 of file Application.cc.
References dqm4hep::online::AppEventLoop::addTimer(), and m_eventLoop.
Referenced by exec(), dqm4hep::online::EventCollector::onInit(), and dqm4hep::online::ModuleApplication::onInit().
{
       auto timer = new AppTimer(m_eventLoop);
       m_eventLoop.addTimer(timer);
       return timer;
     }
template<typename Controller > void dqm4hep::online::Application::directSubscribe (const std::string & serviceName, Controller * controller, void(Controller::*)(const net::Buffer &) function) inline
Subscribe to service.
On service update, the content is posted using the sendEvent() function with a ServiceUpdateEvent event. The received service buffer is not copied but directly passed to the user. The buffer can be accessed using the method ServiceUpdateEvent::buffer() in the callback method Application::onEvent(). ATTN! The server thread will not be released until the event has been processed by the sendEvent method !
Parameters
serviceName the service name to subscribe
Definition at line 555 of file Application.h.
References dqm_error, m_client, m_eventLoop, m_serviceHandlerPtrMap, dqm4hep::online::Application::NetworkHandler::sendServiceContent(), and dqm4hep::net::Client::subscribe().
{
       auto findIter = m_serviceHandlerPtrMap.find(serviceName);
       if(m_serviceHandlerPtrMap.end() != findIter) {
         dqm_error( "Application::directSubscribe(): couldn't subscribe twice to service '{0}'", serviceName );
         throw core::StatusCodeException(core::STATUS_CODE_ALREADY_PRESENT);
       }
       auto handler = std::make_shared<NetworkHandler>(m_eventLoop, serviceName, controller, function);
       m_serviceHandlerPtrMap.insert(NetworkHandlerPtrMap::value_type(serviceName, handler));
       m_client.subscribe(serviceName, handler.get(), &Application::NetworkHandler::sendServiceContent);
     }
void dqm4hep::online::Application::enableStats (bool enable)
Set whether to send statistics on update.
Parameters
enable whether to enable application stats
Definition at line 114 of file Application.cc.
References dqm_error, initialized(), and m_statsEnabled.
Referenced by dqm4hep::online::ModuleApplication::parseSteeringFile().
{
       if(initialized()) {
         dqm_error( "Application::enableStats(): Couldn't enable/disable stats, app is already initialized !" );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       }
       m_statsEnabled = enable;
     }
int dqm4hep::online::Application::exec ()
Run the application.
Definition at line 203 of file Application.cc.
References dqm4hep::core::Signal< Args >::connect(), dqm4hep::online::AppEventLoop::connectOnEvent(), createTimer(), dqm4hep::online::AppEventLoop::disconnectOnEvent(), dqm_error, dqm_info, dqm4hep::online::AppEventLoop::exec(), m_appStatTimer, m_eventLoop, m_running, m_server, noServer(), onEvent(), onStart(), onStop(), dqm4hep::online::AppTimer::onTimeout(), sendAppStats(), dqm4hep::online::AppTimer::setInterval(), dqm4hep::online::AppTimer::setSingleShot(), setState(), dqm4hep::online::AppTimer::start(), and statsEnabled().
{
       m_running = true;
       if(not noServer()) {
         m_server->start();
         sleep(1);
       }
       this->setState("Running");
       try {
         dqm_info( "Application on start ..." );
         this->onStart();
       }
       catch(...) {
         dqm_error( "Application::init(): failed to start the app !" );
         throw core::StatusCodeException(core::STATUS_CODE_FAILURE);
       }
       int returnCode(0);
       try {
         if(statsEnabled() and not noServer()) {
           // send statistics every 5 seconds
           dqm_info( "Statistics enabled. Creating timer (5 secs) ..." );
           m_appStatTimer = createTimer();
           m_appStatTimer->setInterval(5000); // 5 seconds
           m_appStatTimer->setSingleShot(false);
           m_appStatTimer->onTimeout().connect(this, &Application::sendAppStats);
           m_appStatTimer->start();
         }
         m_eventLoop.connectOnEvent(this, &Application::onEvent);
         dqm_info( "Starting event loop ..." );
         returnCode = m_eventLoop.exec();
         dqm_info( "Exiting event loop ..." );
         m_eventLoop.disconnectOnEvent(this);
         if(not noServer()){
           m_server->onClientExit().disconnect();
         }
         this->onStop();
       }
       catch(...) {
         dqm_error( "Application::init(): failed to start the app !" );
         throw core::StatusCodeException(core::STATUS_CODE_FAILURE);
       }
       std::stringstream appState; appState << "Exiting (" << returnCode << ")";
       this->setState(appState.str());
       m_running = false;
       return returnCode;
     }
void dqm4hep::online::Application::exit (int returnCode)
Exit the application with the specified return code If the application is running with exec(), exec will return the specified code.
Parameters
returnCode the code to return from exec()
Definition at line 255 of file Application.cc.
References dqm4hep::online::AppEventLoop::exit(), and m_eventLoop.
Referenced by dqm4hep::online::ModuleApplication::onEvent().
{
       m_eventLoop.exit(returnCode);
     }
void dqm4hep::online::Application::init (int argc, char ** argv)
Initialize the application.
Calls userInit()
Parameters
argc the argc from the main function
argv the argv from the main function
Definition at line 146 of file Application.cc.
References dqm4hep::core::Logger::coloredConsole(), createInternalStats(), dqm4hep::core::Logger::createLogger(), dqm_debug, dqm_error, dqm_info, initialized(), m_initialized, m_logger, m_logLevel, m_pAppStateService, m_server, m_statsEnabled, dqm4hep::online::RemoteLogger::make_shared(), name(), noServer(), onInit(), parseCmdLine(), sendClientExitEvent(), dqm4hep::online::OnlineRoutes::Application::serverName(), dqm4hep::core::Logger::setMainLogger(), dqm4hep::online::OnlineRoutes::Application::state(), and type().
{
       if(initialized()) {
         dqm_error( "Application::init(): app already initialized !" );
         throw core::StatusCodeException(core::STATUS_CODE_ALREADY_INITIALIZED);
       }
       try {
         this->parseCmdLine(argc, argv);
       }
       catch(...) {
         dqm_error( "Application::init(): failed to parse cmd line !" );
         throw core::StatusCodeException(core::STATUS_CODE_FAILURE);
       }
       if(noServer()) {
         // configure logger
         m_logger = core::Logger::createLogger(this->type() + ":" + this->name(), {
           core::Logger::coloredConsole()
         });
       }
       else {
         // configure logger
         m_logger = core::Logger::createLogger(this->type() + ":" + this->name(), {
           core::Logger::coloredConsole(),
           RemoteLogger::make_shared()
         });
       }
       core::Logger::setMainLogger(m_logger->name());
       m_logger->set_level(m_logLevel);
       if(not noServer()) {
         // configure server
         dqm_debug( "Creating server ..." );
         m_server = std::make_shared<net::Server>(OnlineRoutes::Application::serverName(this->type(), this->name()));
         m_pAppStateService = m_server->createService(OnlineRoutes::Application::state(this->type(), this->name()));
         if(m_statsEnabled) {
           dqm_debug( "Creating internal app stats ..." );
           createInternalStats();
         }
         m_server->onClientExit().connect(this, &Application::sendClientExitEvent);
       }
       try {
         dqm_info( "User init ..." );
         this->onInit();
       }
       catch(...) {
         dqm_error( "Application::init(): failed to initialize the app !" );
         throw core::StatusCodeException(core::STATUS_CODE_FAILURE);
       }
       dqm_info( "Application successfully initialized !" );
       m_initialized = true;
     }
bool dqm4hep::online::Application::initialized () const
Whether the application has been initialized.
Definition at line 261 of file Application.cc.
References m_initialized.
Referenced by createStatsEntry(), enableStats(), init(), setName(), setNoServer(), and setType().
{
       return m_initialized;
     }
core::Logger::Level dqm4hep::online::Application::logLevel () const
Get the application log level.
Definition at line 79 of file Application.cc.
References m_logLevel.
{
       return m_logLevel;
     }
const std::string & dqm4hep::online::Application::name () const
Get the application name.
Definition at line 46 of file Application.cc.
References m_name.
Referenced by dqm4hep::online::EventCollector::handleRegistration(), init(), dqm4hep::online::ModuleApplication::onEvent(), dqm4hep::online::EventCollector::onInit(), dqm4hep::online::ModuleApplication::onInit(), and sendStat().
{
       return m_name;
     }
bool dqm4hep::online::Application::noServer () const
Whether the server has been disabled.
Definition at line 140 of file Application.cc.
References m_noServer.
Referenced by createQueuedCommand(), createService(), exec(), init(), queuedSubscribe(), sendClientExitEvent(), sendStat(), and serverClientId().
{
       return m_noServer;
     }
virtual void dqm4hep::online::Application::onEvent (AppEvent * pAppEvent) pure virtual
Process an event from the event loop.
Parameters
pAppEvent the event to process
Implemented in dqm4hep::online::ModuleApplication, and dqm4hep::online::EventCollector.
Referenced by exec().
virtual void dqm4hep::online::Application::onInit () pure virtual
Custom application initialization function.
At this step the server is created but is not yet running. This is the place where the application should create:
all needed services
all stats entries
Implemented in dqm4hep::online::ModuleApplication, and dqm4hep::online::EventCollector.
Referenced by init().
virtual void dqm4hep::online::Application::onStart () pure virtual
Custom user function called just before starting the event loop.
At this step the internal server is already running. This function may e.g send an initial event to the event loop.
Implemented in dqm4hep::online::ModuleApplication, and dqm4hep::online::EventCollector.
Referenced by exec().
virtual void dqm4hep::online::Application::onStop () pure virtual
Custom user function called just after exiting the event loop.
Implemented in dqm4hep::online::ModuleApplication, and dqm4hep::online::EventCollector.
Referenced by exec().
Application& dqm4hep::online::Application::operator= (const Application &) delete
virtual void dqm4hep::online::Application::parseCmdLine (int argc, char ** argv) pure virtual
Parse the command line arguments.
After parsing the cmd line, the application must provide a valid type and name. At this step the server is not yet created.
Parameters
argc the argc argument from the main function
argc the argv argument from the main function
Implemented in dqm4hep::online::ModuleApplication, and dqm4hep::online::EventCollector.
Referenced by init().
void dqm4hep::online::Application::queuedSubscribe (const std::string & serviceName, int priority = 50, int maxNEvents = std::numeric_limits<int>::max())
Subscribe to service.
On service update, the content is posted using the postEvent() function with a ServiceUpdateEvent event. The received service buffer is copied and can be accessed using the method ServiceUpdateEvent::buffer() in the callback method Application::onEvent(). A maximum limit of posted event from the service can be set using the argument maxNEvents. If this limit is reached, the service update is not posted.
Parameters
serviceName the service name to subscribe
priority the priority of the event in the event queue
maxNEvents the maximum number of updates for this service to post
Definition at line 273 of file Application.cc.
References dqm_error, m_client, m_eventLoop, m_serviceHandlerPtrMap, noServer(), dqm4hep::online::Application::NetworkHandler::postServiceContent(), and dqm4hep::net::Client::subscribe().
Referenced by dqm4hep::online::ModuleApplication::onInit().
{
       if(noServer()){
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       }
       auto findIter = m_serviceHandlerPtrMap.find(serviceName);
       if(m_serviceHandlerPtrMap.end() != findIter) {
         dqm_error( "Application::queuedSubscribe(): couldn't subscribe twice to service '{0}'", serviceName );
         throw core::StatusCodeException(core::STATUS_CODE_ALREADY_PRESENT);
       }
       auto handler = std::make_shared<NetworkHandler>(m_eventLoop, serviceName, priority, maxNEvents);
       m_serviceHandlerPtrMap.insert(NetworkHandlerPtrMap::value_type(serviceName, handler));
       m_client.subscribe(serviceName, handler.get(), &Application::NetworkHandler::postServiceContent);
     }
void dqm4hep::online::Application::removeTimer (AppTimer * timer)
Remove timer.
Parameters
timer the timer to remove
Definition at line 418 of file Application.cc.
References m_eventLoop, and dqm4hep::online::AppEventLoop::removeTimer().
Referenced by ~Application(), dqm4hep::online::EventCollector::~EventCollector(), and dqm4hep::online::ModuleApplication::~ModuleApplication().
{
       m_eventLoop.removeTimer(timer);
     }
bool dqm4hep::online::Application::running () const
Whether the application is running.
Definition at line 267 of file Application.cc.
References m_running.
{
       return m_running;
     }
void dqm4hep::online::Application::sendAppStats () private
Send application statistics.
Definition at line 346 of file Application.cc.
References dqm4hep::core::ProcessStats::cpuSys, dqm4hep::core::ProcessStats::cpuTot, dqm4hep::core::ProcessStats::cpuUser, dqm_debug, dqm4hep::core::ProcessStats::lastPollTime, m_stats, dqm4hep::core::memStats(), dqm4hep::core::procStats(), dqm4hep::core::ProcessStats::rss, dqm4hep::core::MemoryStats::rssTot, dqm4hep::core::MemoryStats::rssUsed, sendStat(), dqm4hep::core::ProcessStats::vm, dqm4hep::core::MemoryStats::vmTot, and dqm4hep::core::MemoryStats::vmUsed.
Referenced by exec().
{
       core::MemoryStats memInfo;
       core::memStats(memInfo);
       core::procStats(m_stats);
       long procVm = m_stats.vm/1024.;   // in MB
       long procRss = m_stats.rss/1024.; // in MB
       dqm_debug("Sending internal app stats ..." );
       sendStat("VmProc", procVm);
       sendStat("VmTotal", (procVm/(memInfo.vmTot*1.))*100.);
       sendStat("VmInUse", (procVm/(memInfo.vmUsed*1.))*100.);
       sendStat("RSSProc", procRss);
       sendStat("RSSTotal", (procRss/(memInfo.rssTot*1.))*100.);
       sendStat("RSSInUse", (procRss/(memInfo.rssUsed*1.))*100.);
       sendStat("CpuUser", m_stats.cpuUser);
       sendStat("CpuSys", m_stats.cpuSys);
       sendStat("CpuTotal", m_stats.cpuTot);
       auto tm_time = localtime(&m_stats.lastPollTime.tv_sec);
       char date_buf[100];
       std::strftime(date_buf, sizeof(date_buf), "%Y-%m-%d %H:%M:%S", tm_time);
       sendStat("LastUpdate", date_buf );
       dqm_debug( "Sending internal app stats ... OK" );
     }
void dqm4hep::online::Application::sendClientExitEvent (int clientId)
Send a client exit event in the event loop.
Parameters
clientId the client id
Definition at line 336 of file Application.cc.
References dqm4hep::online::AppEvent::CLIENT_EXIT, m_eventLoop, noServer(), and dqm4hep::online::AppEventLoop::sendEvent().
Referenced by init().
{
       if(noServer()){
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       }
       auto event = new StoreEvent<int>(AppEvent::CLIENT_EXIT, id);
       m_eventLoop.sendEvent(event);
     }
template<typename T > void dqm4hep::online::Application::sendCommand (const std::string & name, const T & contents, bool blocking = false) const inline
Client interface.
Send a request using the net client interface. See net::Client class.
Parameters
name the command name
contents the command contents to send
blocking whether to receive aknowledgment while send the command
Definition at line 519 of file Application.h.
References m_client, and dqm4hep::net::Client::sendCommand().
{
       m_client.sendCommand(cname, contents, blocking);
     }
template<typename Operation > void dqm4hep::online::Application::sendRequest (const std::string & name, const net::Buffer & request, Operation operation) inline
Send a request using the net client interface.
See net::Client class.
Parameters
name the request name
request the buffer to send
operation the operation to perform on answer reception
Definition at line 526 of file Application.h.
References m_client, and dqm4hep::net::Client::sendRequest().
Referenced by dqm4hep::online::ModuleApplication::onStart().
{
       m_client.sendRequest(rname, request, operation);
     }
template<typename T > void dqm4hep::online::Application::sendStat (const std::string & name, const T & stats) inline
Send the stat entry with a new value.
Parameters
name the stat entry name
stats the new stat value
Definition at line 500 of file Application.h.
References dqm4hep::online::OnlineRoutes::OnlineManager::appStats(), dqm4hep::core::time::asTime(), dqm_debug, m_client, m_statistics, name(), noServer(), dqm4hep::core::time::now(), dqm4hep::net::Client::sendCommand(), statsEnabled(), and type().
Referenced by dqm4hep::online::EventCollector::handleClientExit(), dqm4hep::online::EventCollector::handleClientUnregistration(), dqm4hep::online::EventCollector::handleRegistration(), sendAppStats(), dqm4hep::online::EventCollector::sendStatsTimer10(), and dqm4hep::online::EventCollector::sendStatsTimer60().
{
       if(not statsEnabled() or noServer()) {
         return;
       }
       core::json object = m_statistics[entryName];
       if(object.is_null())
         throw core::StatusCodeException(core::STATUS_CODE_NOT_FOUND);
       // add metadata on the fly
       object["name"] = entryName;
       object["value"] = stats;
       object["appType"] = this->type();
       object["appName"] = this->name();
       object["time"] = core::time::asTime(core::time::now());
       dqm_debug( "Sending app stat : \n'{0}'", object.dump() );
       m_client.sendCommand(OnlineRoutes::OnlineManager::appStats(), object.dump());
     }
int dqm4hep::online::Application::serverClientId () const
Get the current server client id.
Definition at line 327 of file Application.cc.
References m_server, and noServer().
Referenced by dqm4hep::online::EventCollector::handleClientUnregistration(), dqm4hep::online::EventCollector::handleCollectEvent(), and dqm4hep::online::EventCollector::handleRegistration().
{
       if(noServer()){
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       }
       return m_server->clientId();
     }
void dqm4hep::online::Application::setLogLevel (core::Logger::Level lvl)
Get the application log level.
Parameters
lvl the new logging level
Definition at line 85 of file Application.cc.
References m_logger, and m_logLevel.
Referenced by dqm4hep::online::EventCollector::parseCmdLine(), and dqm4hep::online::ModuleApplication::parseCmdLine().
{
       m_logLevel = lvl;
       if(nullptr != m_logger) {
         m_logger->set_level(m_logLevel);
       }
     }
void dqm4hep::online::Application::setName (const std::string & name)
Set the application name Throw exception if called after init() is called.
Parameters
name the application name
Definition at line 52 of file Application.cc.
References dqm_debug, dqm_error, initialized(), and m_name.
Referenced by dqm4hep::online::ModuleApplication::configureModule(), and dqm4hep::online::EventCollector::parseCmdLine().
{
       if(initialized()) {
         dqm_error( "Application::setName(): Couldn't set app name, app is already initialized !" );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       }
       dqm_debug( "Application set name to '{0}'", appName );
       m_name = appName;
     }
void dqm4hep::online::Application::setNoServer (bool nosrv)
Enable or disable running the application server.
Some application might not need to setup a server to run and can be disabled by calling setNoServer(true) in the ctor or in parseCmdLine()
Parameters
nosrv whether to enable / disable the server
Definition at line 130 of file Application.cc.
References dqm_error, initialized(), and m_noServer.
{
       if(initialized()) {
         dqm_error( "Application::enableStats(): Couldn't enable/disable stats, app is already initialized !" );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       }
       m_noServer = nosrv;
     }
void dqm4hep::online::Application::setState (const std::string & state)
Change the application state.
Parameters
state the new application state
Definition at line 69 of file Application.cc.
References dqm_debug, m_pAppStateService, m_server, m_state, and dqm4hep::net::Service::send().
Referenced by exec().
{
       m_state = appState;
       dqm_debug( "Changing app state to '{0}'", appState );
       if(m_pAppStateService && m_server && m_server->isRunning())
         m_pAppStateService->send(m_state);
     }
void dqm4hep::online::Application::setType (const std::string & type)
Set the application type.
Throw exception if called after init() is called
Parameters
type the application type
Definition at line 35 of file Application.cc.
References dqm_debug, dqm_error, initialized(), and m_type.
Referenced by dqm4hep::online::EventCollector::parseCmdLine(), and dqm4hep::online::ModuleApplication::parseCmdLine().
{
       if(initialized()) {
         dqm_error( "Application::setType(): Couldn't set app type, app is already initialized !" );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       }
       dqm_debug( "Application set type to '{0}'", appType );
       m_type = appType;
     }
const std::string & dqm4hep::online::Application::state () const
Get the application state.
Definition at line 63 of file Application.cc.
References m_state.
{
       return m_state;
     }
bool dqm4hep::online::Application::statsEnabled () const
Whether the statistics are enabled.
Definition at line 124 of file Application.cc.
References m_statsEnabled.
Referenced by exec(), and sendStat().
{
       return m_statsEnabled;
     }
const std::string & dqm4hep::online::Application::type () const
Get the application type.
Definition at line 29 of file Application.cc.
References m_type.
Referenced by init(), and sendStat().
{
       return m_type;
     }
Member Data Documentation
AppTimer* dqm4hep::online::Application::m_appStatTimer = {nullptr} private
Definition at line 489 of file Application.h.
Referenced by exec(), and ~Application().
Client dqm4hep::online::Application::m_client = {} private
The main client interface of the application.
Definition at line 475 of file Application.h.
Referenced by directSubscribe(), queuedSubscribe(), sendCommand(), sendRequest(), and sendStat().
NetworkHandlerPtrMap dqm4hep::online::Application::m_commandHandlerPtrMap = {} private
The map handling command handlers from the server interface.
Definition at line 481 of file Application.h.
Referenced by createDirectCommand(), and createQueuedCommand().
AppEventLoop dqm4hep::online::Application::m_eventLoop = {} protected
The application event loop.
Definition at line 493 of file Application.h.
Referenced by createDirectCommand(), createQueuedCommand(), createRequestHandler(), createTimer(), directSubscribe(), exec(), exit(), dqm4hep::online::Application::NetworkHandler::postCommandEvent(), dqm4hep::online::Application::NetworkHandler::postServiceContent(), dqm4hep::online::ModuleApplication::postStandaloneProcess(), dqm4hep::online::ModuleApplication::processEndOfRun(), queuedSubscribe(), dqm4hep::online::ModuleApplication::receiveEvent(), removeTimer(), sendClientExitEvent(), dqm4hep::online::Application::NetworkHandler::sendCommandEvent(), dqm4hep::online::Application::NetworkHandler::sendRequestEvent(), and dqm4hep::online::Application::NetworkHandler::sendServiceContent().
bool dqm4hep::online::Application::m_initialized = {false} private
Whether the application is initialized.
Definition at line 463 of file Application.h.
Referenced by init(), and initialized().
LoggerPtr dqm4hep::online::Application::m_logger = {nullptr} private
The application logger.
Definition at line 485 of file Application.h.
Referenced by init(), and setLogLevel().
LogLevel dqm4hep::online::Application::m_logLevel = {spdlog::level::info} private
The logger log level.
Definition at line 487 of file Application.h.
Referenced by init(), logLevel(), and setLogLevel().
std::string dqm4hep::online::Application::m_name = {""} private
The application name.
Definition at line 457 of file Application.h.
Referenced by name(), dqm4hep::online::Application::NetworkHandler::postCommandEvent(), dqm4hep::online::Application::NetworkHandler::postServiceContent(), and setName().
bool dqm4hep::online::Application::m_noServer = {false} private
Definition at line 469 of file Application.h.
Referenced by noServer(), and setNoServer().
Service* dqm4hep::online::Application::m_pAppStateService = {nullptr} private
The service for application state, updated when the state changes.
Definition at line 473 of file Application.h.
Referenced by init(), and setState().
NetworkHandlerPtrMap dqm4hep::online::Application::m_requestHandlerPtrMap = {} private
The map handling request handlers from the server interface.
Definition at line 479 of file Application.h.
Referenced by createRequestHandler().
bool dqm4hep::online::Application::m_running = {false} private
Whether the application is running.
Definition at line 461 of file Application.h.
Referenced by exec(), and running().
ServerPtr dqm4hep::online::Application::m_server = {nullptr} private
The main server interface of the application.
Definition at line 471 of file Application.h.
Referenced by createDirectCommand(), createQueuedCommand(), createRequestHandler(), createService(), exec(), init(), serverClientId(), and setState().
NetworkHandlerPtrMap dqm4hep::online::Application::m_serviceHandlerPtrMap = {} private
The map handling service updates from the client interface.
Definition at line 477 of file Application.h.
Referenced by createRequestHandler(), directSubscribe(), and queuedSubscribe().
std::string dqm4hep::online::Application::m_state = {"Unknown"} private
The application state.
Definition at line 459 of file Application.h.
Referenced by setState(), and state().
core::json dqm4hep::online::Application::m_statistics = {} private
The json value handling the application statistics.
Definition at line 483 of file Application.h.
Referenced by createStatsEntry(), and sendStat().
core::ProcessStats dqm4hep::online::Application::m_stats = {} private
The application statistics.
Definition at line 467 of file Application.h.
Referenced by createInternalStats(), and sendAppStats().
bool dqm4hep::online::Application::m_statsEnabled = {true} private
Whether the application statistics are available.
Definition at line 465 of file Application.h.
Referenced by enableStats(), init(), and statsEnabled().
std::string dqm4hep::online::Application::m_type = {""} private
The application type.
Definition at line 455 of file Application.h.
Referenced by setType(), and type().
The documentation for this class was generated from the following files:
Application.h
Application.cc