DQM4hep: dqm4hep::core::KolmogorovTest Class Reference
dqm4hep::core::KolmogorovTest Class Reference
KolmogorovTest class.
Classes
class Factory
Public Member Functions
KolmogorovTest (const std::string &name)
~KolmogorovTest () override=default
StatusCode readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override
Read the settings from the xml handle.
std::string getTestOptions (const bool isHistogram)
void userRun (MonitorElement *monitorElement, QualityTestReport &report) override
Runs a quality test on the given monitor element and return a quality estimate.
Public Member Functions inherited from dqm4hep::core::QualityTest
QualityTest (const std::string &type, const std::string &name)
Constructor.
virtual ~QualityTest ()
Destructor.
const std::string & type () const
Get the quality test type.
const std::string & name () const
Get the quality test name (unique identifier)
const std::string & description () const
Get the quality test description.
void run (MonitorElement *monitorElement, QualityTestReport &report)
Perform the quality test result and fill the quality test report.
virtual StatusCode init ()
Initialize the quality test.
virtual bool enoughStatistics (MonitorElement *monitorElement) const
Whether the monitor element has enough statistics to perform the qtest.
void setLimits (float warning, float error)
Set the warning and error limits on quality test result.
float warningLimit () const
Get the warning limit.
float errorLimit () const
Get the error limit.
Protected Attributes
bool m_useUnderflow = {false}
bool m_useOverflow = {false}
Protected Attributes inherited from dqm4hep::core::QualityTest
std::string m_description = {""}
Quality test description.
Additional Inherited Members
Static Public Member Functions inherited from dqm4hep::core::QualityTest
static float defaultWarningLimit ()
Get the default warning limit.
static float defaultErrorLimit ()
Get the default error limit.
Protected Member Functions inherited from dqm4hep::core::QualityTest
void fillBasicInfo (MonitorElement *monitorElement, QualityTestReport &report) const
Fill basic info in the qtest report.
Static Protected Attributes inherited from dqm4hep::core::QualityTest
static float m_defaultWarningLimit = 0.8
static float m_defaultErrorLimit = 0.5
Detailed Description
KolmogorovTest class.
Definition at line 31 of file KolmogorovTest.cc.
Constructor & Destructor Documentation
dqm4hep::core::KolmogorovTest::KolmogorovTest (const std::string & name)
Definition at line 62 of file KolmogorovTest.cc.
References dqm4hep::core::QualityTest::m_description.
Referenced by dqm4hep::core::KolmogorovTest::Factory::createQualityTest().
         : QualityTest("Kolmogorov", qname)
 {
       m_description = "Performs the Kolmogorov-Smirnov test on a monitor element and a reference, outputting the p-value. In general this should only "
                 "be used for TGraphs. While this test can take TH1s, the Kolmogorov test is intended for use on unbinned data, not histograms. "
                 "See https://root.cern.ch/doc/master/classTH1.html#aeadcf087afe6ba203bcde124cfabbee4 for more information.";
     }
dqm4hep::core::KolmogorovTest::~KolmogorovTest () override default
Member Function Documentation
std::string dqm4hep::core::KolmogorovTest::getTestOptions (const bool isHistogram)
Definition at line 79 of file KolmogorovTest.cc.
References m_useOverflow, and m_useUnderflow.
Referenced by userRun().
{
       std::string optionsString = "";
       if (m_useUnderflow and isHistogram) {
   optionsString += "U";
       }
       if (m_useOverflow and isHistogram) {
   optionsString += "O";
       }
       return optionsString;
     }
StatusCode dqm4hep::core::KolmogorovTest::readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) override virtual
Read the settings from the xml handle.
Implements dqm4hep::core::QualityTest.
Definition at line 72 of file KolmogorovTest.cc.
References m_useOverflow, m_useUnderflow, dqm4hep::core::XmlHelper::readParameter(), and RETURN_RESULT_IF_AND_IF.
{
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle, "UseUnderflow", m_useUnderflow));
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameter(xmlHandle, "UseOverflow", m_useOverflow));
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::KolmogorovTest::userRun (MonitorElement * monitorElement, QualityTestReport & report) override virtual
Runs a quality test on the given monitor element and return a quality estimate.
Implements dqm4hep::core::QualityTest.
Definition at line 91 of file KolmogorovTest.cc.
References getTestOptions(), dqm4hep::core::QualityTestReport::m_extraInfos, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, dqm4hep::core::MonitorElement::object(), dqm4hep::core::MonitorElement::objectTo(), dqm4hep::core::MonitorElement::reference(), and dqm4hep::core::MonitorElement::referenceTo().
{
       const bool hasObject = (pMonitorElement->object() != nullptr);
       const bool hasReference = (pMonitorElement->reference() != nullptr);
       if (!hasObject) {
         report.m_message = "No object attached to monitor element";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_INVALID_PTR);
       }
       if (!hasReference) {
         report.m_message = "No reference attached to monitor element";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_INVALID_PTR);
       }
       const bool isObjHistogram = pMonitorElement->object()->InheritsFrom("TH1");
       const bool isObjGraph = pMonitorElement->object()->InheritsFrom("TGraph");
       const bool isRefHistogram = pMonitorElement->reference()->InheritsFrom("TH1");
       const bool isRefGraph = pMonitorElement->reference()->InheritsFrom("TGraph");
       if ( (isObjGraph and !isRefGraph) or (isObjHistogram and !isRefHistogram) ) {
         report.m_message = "The object and reference must be of the same type";
         report.m_quality = 0.f;
         throw StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
       }
       if (isObjGraph) {
   TGraph* pGraph = pMonitorElement->objectTo<TGraph>();
   TGraph* pReferenceGraph = pMonitorElement->referenceTo<TGraph>();
   std::string options = KolmogorovTest::getTestOptions(isObjHistogram);
   int sizeGraph = pGraph->GetN();
   int sizeRef = pReferenceGraph->GetN();
   if ( (sizeGraph == 0) or (sizeRef == 0) ) {
     report.m_message = "One or more of the graphs are empty!";
     report.m_quality = 0.0;
     throw StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
   }
   pGraph->Sort();
   pReferenceGraph->Sort();
   double* pArrayGraph = pGraph->GetY();
   double* pArrayRef = pReferenceGraph->GetY();
   report.m_extraInfos["options"] = options;
   report.m_quality = TMath::KolmogorovTest(sizeGraph, pArrayGraph, sizeRef, pArrayRef, options.c_str());
       }
       else if (isObjHistogram) {
   TH1* pHistogram = pMonitorElement->objectTo<TH1>();
   TH1* pReferenceHistogram = pMonitorElement->referenceTo<TH1>();
   std::string options = KolmogorovTest::getTestOptions(isObjHistogram);
   report.m_extraInfos["options"] = options;
   report.m_message = "The Kolmogorov test isn't intended for histograms! Use caution when interepreting the quality.";
   report.m_quality = pHistogram->KolmogorovTest(pReferenceHistogram, options.c_str());
       }
       else {
   report.m_message = "ROOT monitor element object is of unrecognised type!";
         report.m_quality = 0.f;
   throw StatusCodeException(STATUS_CODE_INVALID_PTR);
       }
     }
Member Data Documentation
bool dqm4hep::core::KolmogorovTest::m_useOverflow = {false} protected
Definition at line 46 of file KolmogorovTest.cc.
Referenced by getTestOptions(), and readSettings().
bool dqm4hep::core::KolmogorovTest::m_useUnderflow = {false} protected
Definition at line 45 of file KolmogorovTest.cc.
Referenced by getTestOptions(), and readSettings().
The documentation for this class was generated from the following file:
KolmogorovTest.cc