DQM4hep: dqm4hep::core::Plugin Class Reference
dqm4hep::core::Plugin Class Reference
Plugin class.
#include <PluginManager.h>
Public Member Functions
template<typename T >
Plugin (const std::string &id, const T &)
Constructor.
const std::type_index & type () const
Get the type information on the internal plugin class.
template<typename T >
std::shared_ptr< T > create () const
Create a plugin instance.
const std::string & name () const
Get the plugin name.
Private Attributes
const std::string m_name
The plugin name.
const std::type_index m_typeInfo
The plugin class type information.
std::function< std::shared_ptr
< void >void)> m_newFunction = {nullptr}
A custom allocator function based on the underlying type.
Detailed Description
Plugin class.
Definition at line 139 of file PluginManager.h.
Constructor & Destructor Documentation
template<typename T > dqm4hep::core::Plugin::Plugin (const std::string & id, const T &) inline
Constructor.
Parameters
id the plugin identifier
Definition at line 147 of file PluginManager.h.
References dqm4hep::core::PluginManager::instance(), m_newFunction, and dqm4hep::core::PluginManager::registerPlugin().
                                                      :
         m_name(id),
         m_typeInfo(typeid(T)) {
         m_newFunction = [](){
           return std::make_shared<T>();
         };
         PluginManager::instance()->registerPlugin(this);
       }
Member Function Documentation
template<typename T > std::shared_ptr<T> dqm4hep::core::Plugin::create () const inline
Create a plugin instance.
Definition at line 167 of file PluginManager.h.
References m_newFunction.
{
         return std::static_pointer_cast<T>(m_newFunction());
       }
const std::string& dqm4hep::core::Plugin::name () const inline
Get the plugin name.
Definition at line 174 of file PluginManager.h.
References m_name.
Referenced by dqm4hep::core::PluginManager::registerPlugin().
{
         return m_name;
       }
const std::type_index& dqm4hep::core::Plugin::type () const inline
Get the type information on the internal plugin class.
Definition at line 159 of file PluginManager.h.
References m_typeInfo.
{
         return m_typeInfo;
       }
Member Data Documentation
const std::string dqm4hep::core::Plugin::m_name private
The plugin name.
Definition at line 180 of file PluginManager.h.
Referenced by name().
std::function<std::shared_ptr<void>void)> dqm4hep::core::Plugin::m_newFunction = {nullptr} private
A custom allocator function based on the underlying type.
Definition at line 184 of file PluginManager.h.
Referenced by create(), and Plugin().
const std::type_index dqm4hep::core::Plugin::m_typeInfo private
The plugin class type information.
Definition at line 182 of file PluginManager.h.
Referenced by type().
The documentation for this class was generated from the following file:
PluginManager.h