DQM4hep: dqm4hep::core::Run Class Reference
dqm4hep::core::Run Class Reference
Run class.
#include <Run.h>
Public Member Functions
Run (int runNumber=0, const std::string &description="", const std::string &detectorName="")
Constructor.
~Run ()=default
Default destructor.
int runNumber () const
Get the run number.
core::time::point startTime () const
Get the run start time.
core::time::point endTime () const
Get the run end time.
const std::string & description () const
Get the run description.
const std::string & detectorName () const
Get the detector name.
void setRunNumber (int runNumber)
Set the run number.
void setStartTime (const core::time::point &startTime)
Set the run start time.
void setEndTime (const core::time::point &endTime)
Set the run end tim.
void setDescription (const std::string &description)
Set the run description.
void setDetectorName (const std::string &detectorName)
Set the detector name.
template<typename T >
void setParameter (const std::string &key, const T &value)
Set a run parameter The value is converted to string.
template<typename T >
void parameter (const std::string &key, T &value) const
Get a run parameter The value is converted into template type using the << operator If the parameter is not found, the value remains unchanged.
template<typename T >
void parameter (const std::string &key, T &value, const T &fallback) const
Get a run parameter The value is converted into template type using the << operator If the parameter is not found, the fallback value is used instead.
unsigned int nParameters () const
Get the number of run parameters.
StringVector parameterKeys () const
Get the run parameters keys.
const StringMap & parameters () const
Get the run parameters.
void reset ()
Reset the run properties.
void toJson (json &value) const
Convert the run object to json.
void fromJson (const json &value)
Read and set run info from json object.
template<>
void setParameter (const std::string &key, const std::string &value)
template<>
void parameter (const std::string &key, std::string &value) const
template<>
void parameter (const std::string &key, std::string &value, const std::string &fallback) const
Protected Attributes
int m_runNumber = {0}
The run number.
core::time::point m_startTime = {}
The run start time.
core::time::point m_endTime = {}
The run end time.
std::string m_detectorName = {""}
The detector name.
std::string m_description = {""}
The run description.
StringMap m_parametersMap = {}
The run parameters.
Detailed Description
Run class.
Definition at line 30 of file Run.h.
Constructor & Destructor Documentation
dqm4hep::core::Run::Run (int runNumber = 0, const std::string & description = "", const std::string & detectorName = "")
Constructor.
Parameters
runNumber the run number
description the run description
detectorName the detector name
Definition at line 17 of file Run.cc.
                                                               :
       m_runNumber(rn),
       m_startTime(dqm4hep::core::time::now()),
       m_detectorName(dn),
       m_description(des) {
       /* nop */
     }
dqm4hep::core::Run::~Run () default
Default destructor.
Member Function Documentation
const std::string & dqm4hep::core::Run::description () const inline
Get the run description.
Definition at line 213 of file Run.h.
References m_description.
{
       return m_description;
     }
const std::string & dqm4hep::core::Run::detectorName () const inline
Get the detector name.
Definition at line 219 of file Run.h.
References m_detectorName.
{
       return m_detectorName;
     }
core::time::point dqm4hep::core::Run::endTime () const inline
Get the run end time.
Definition at line 207 of file Run.h.
References m_endTime.
{
       return m_endTime;
     }
void dqm4hep::core::Run::fromJson (const json & value)
Read and set run info from json object.
Parameters
value the json object to read
Definition at line 68 of file Run.cc.
References dqm4hep::core::time::asPoint(), m_description, m_detectorName, m_endTime, m_parametersMap, m_runNumber, and m_startTime.
Referenced by dqm4hep::online::ModuleApplication::onStart(), and dqm4hep::online::ModuleApplication::processStartOfRun().
{
       m_runNumber = value.value<int>("runNumber", 0);
       auto st = value.value<int32_t>("startTime", 0);
       auto et = value.value<int32_t>("endTime", 0);
       m_startTime = core::time::asPoint(st);
       m_endTime = core::time::asPoint(et);
       m_detectorName = value.value<std::string>("detector", "");
       m_description = value.value<std::string>("description", "");
       m_parametersMap = value.value<StringMap>("parameters", StringMap());
     }
unsigned int dqm4hep::core::Run::nParameters () const inline
Get the number of run parameters.
Definition at line 313 of file Run.h.
References m_parametersMap.
{
       return m_parametersMap.size();
     }
template<typename T > void dqm4hep::core::Run::parameter (const std::string & key, T & value) const inline
Get a run parameter The value is converted into template type using the << operator If the parameter is not found, the value remains unchanged.
Parameters
key the parameter name
value the value to receive
Definition at line 263 of file Run.h.
References m_parametersMap, and dqm4hep::core::stringToType().
{
       auto findIter = m_parametersMap.find(key);
       if (m_parametersMap.end() == findIter)
         return;
       dqm4hep::core::stringToType(findIter->second, value);
     }
template<typename T > void dqm4hep::core::Run::parameter (const std::string & key, T & value, const T & fallback) const inline
Get a run parameter The value is converted into template type using the << operator If the parameter is not found, the fallback value is used instead.
Parameters
key the parameter name
value the value to receive
fallback the fallback value
Definition at line 273 of file Run.h.
References m_parametersMap, and dqm4hep::core::stringToType().
{
       auto findIter = m_parametersMap.find(key);
       if (m_parametersMap.end() == findIter) {
         value = fallback;
         return;
       }
       dqm4hep::core::stringToType(findIter->second, value);
     }
template<> void dqm4hep::core::Run::parameter (const std::string & key, std::string & value) const inline
Definition at line 292 of file Run.h.
References m_parametersMap.
{
       auto findIter = m_parametersMap.find(key);
       if (m_parametersMap.end() == findIter)
         return;
       value = findIter->second;
     }
template<> void dqm4hep::core::Run::parameter (const std::string & key, std::string & value, const std::string & fallback) const inline
Definition at line 302 of file Run.h.
References m_parametersMap.
{
       auto findIter = m_parametersMap.find(key);
       if (m_parametersMap.end() == findIter) {
         value = fallback;
         return;
       }
       value = findIter->second;
     }
StringVector dqm4hep::core::Run::parameterKeys () const
Get the run parameters keys.
Definition at line 27 of file Run.cc.
References m_parametersMap.
{
       StringVector keys;
       for (auto iter = m_parametersMap.begin(), endIter = m_parametersMap.end(); endIter != iter; ++iter)
         keys.push_back(iter->first);
       return keys;
     }
const StringMap & dqm4hep::core::Run::parameters () const
Get the run parameters.
Definition at line 36 of file Run.cc.
References m_parametersMap.
{
       return m_parametersMap;
     }
void dqm4hep::core::Run::reset ()
Reset the run properties.
Definition at line 42 of file Run.cc.
References m_description, m_detectorName, m_endTime, m_parametersMap, m_runNumber, and m_startTime.
Referenced by dqm4hep::online::RunControl::endCurrentRun().
                     {
       m_runNumber = 0;
       m_startTime = core::time::point();
       m_endTime = core::time::point();
       m_detectorName.clear();
       m_description.clear();
       m_parametersMap.clear();
     }
int dqm4hep::core::Run::runNumber () const inline
Get the run number.
Definition at line 195 of file Run.h.
References m_runNumber.
Referenced by dqm4hep::online::ModuleApplication::openArchive(), and dqm4hep::online::ModuleApplication::setElementsRunNumber().
{
       return m_runNumber;
     }
void dqm4hep::core::Run::setDescription (const std::string & description) inline
Set the run description.
Parameters
description the run description
Definition at line 243 of file Run.h.
References m_description.
Referenced by dqm4hep::online::HttpRunControl::receiveStartOfRunPost(), and dqm4hep::core::GenericEventXMLReader::runInfo().
{
       m_description = des;
     }
void dqm4hep::core::Run::setDetectorName (const std::string & detectorName) inline
Set the detector name.
Parameters
detectorName the detector name
Definition at line 249 of file Run.h.
References m_detectorName.
Referenced by dqm4hep::online::HttpRunControl::receiveStartOfRunPost(), and dqm4hep::core::GenericEventXMLReader::runInfo().
{
       m_detectorName = dn;
     }
void dqm4hep::core::Run::setEndTime (const core::time::point & endTime) inline
Set the run end tim.
Parameters
endTime the run end time
Definition at line 237 of file Run.h.
References m_endTime.
Referenced by dqm4hep::core::GenericEventXMLReader::runInfo().
{
       m_endTime = et;
     }
template<typename T > void dqm4hep::core::Run::setParameter (const std::string & key, const T & value) inline
Set a run parameter The value is converted to string.
Parameters
key the parameter name
value the parameter value to set
Definition at line 256 of file Run.h.
References m_parametersMap.
Referenced by dqm4hep::online::RunControl::endCurrentRun(), dqm4hep::online::HttpRunControl::receiveStartOfRunPost(), dqm4hep::core::GenericEventXMLReader::runInfo(), and dqm4hep::online::RunControl::startNewRun().
{
       m_parametersMap[key] = dqm4hep::core::typeToString<T>(value);
     }
template<> void dqm4hep::core::Run::setParameter (const std::string & key, const std::string & value) inline
Definition at line 285 of file Run.h.
References m_parametersMap.
{
       m_parametersMap[key] = value;
     }
void dqm4hep::core::Run::setRunNumber (int runNumber) inline
Set the run number.
Parameters
runNumber the run number
Definition at line 225 of file Run.h.
References m_runNumber.
Referenced by dqm4hep::online::HttpRunControl::receiveStartOfRunPost(), and dqm4hep::core::GenericEventXMLReader::runInfo().
{
       m_runNumber = rn;
     }
void dqm4hep::core::Run::setStartTime (const core::time::point & startTime) inline
Set the run start time.
Parameters
startTime the run start time
Definition at line 231 of file Run.h.
References m_startTime.
Referenced by dqm4hep::core::GenericEventXMLReader::runInfo().
{
       m_startTime = st;
     }
core::time::point dqm4hep::core::Run::startTime () const inline
Get the run start time.
Definition at line 201 of file Run.h.
References m_startTime.
{
       return m_startTime;
     }
void dqm4hep::core::Run::toJson (json & value) const
Convert the run object to json.
Parameters
value the json value to receive
Definition at line 53 of file Run.cc.
References dqm4hep::core::time::asTime(), m_description, m_detectorName, m_endTime, m_parametersMap, m_runNumber, and m_startTime.
Referenced by dqm4hep::online::RunControlServer::eor(), dqm4hep::core::operator<<(), and dqm4hep::online::RunControlServer::sor().
{
       auto st = core::time::asTime(m_startTime);
       auto et = core::time::asTime(m_endTime);
       value = {
         {"runNumber", m_runNumber},
         {"startTime", st},
         {"endTime", et},
         {"detector", m_detectorName},
         {"description", m_description},
         {"parameters", m_parametersMap}
       };
     }
Member Data Documentation
std::string dqm4hep::core::Run::m_description = {""} protected
The run description.
Definition at line 183 of file Run.h.
Referenced by description(), fromJson(), reset(), setDescription(), and toJson().
std::string dqm4hep::core::Run::m_detectorName = {""} protected
The detector name.
Definition at line 181 of file Run.h.
Referenced by detectorName(), fromJson(), reset(), setDetectorName(), and toJson().
core::time::point dqm4hep::core::Run::m_endTime = {} protected
The run end time.
Definition at line 179 of file Run.h.
Referenced by endTime(), fromJson(), reset(), setEndTime(), and toJson().
StringMap dqm4hep::core::Run::m_parametersMap = {} protected
The run parameters.
Definition at line 185 of file Run.h.
Referenced by fromJson(), nParameters(), parameter(), parameterKeys(), parameters(), reset(), setParameter(), and toJson().
int dqm4hep::core::Run::m_runNumber = {0} protected
The run number.
Definition at line 175 of file Run.h.
Referenced by fromJson(), reset(), runNumber(), setRunNumber(), and toJson().
core::time::point dqm4hep::core::Run::m_startTime = {} protected
The run start time.
Definition at line 177 of file Run.h.
Referenced by fromJson(), reset(), setStartTime(), startTime(), and toJson().
The documentation for this class was generated from the following files:
Run.h
Run.cc