DQM4hep: dqm4hep::online::CommandEvent Class Reference
dqm4hep::online::CommandEvent Class Reference
#include <AppEvents.h>
Public Member Functions
CommandEvent (const std::string &commandName, net::BufferModelPtr bufferModel)
const std::string & commandName () const
const net::Buffer & buffer () const
Public Member Functions inherited from dqm4hep::online::AppEvent
AppEvent (int type)
Constructor.
virtual ~AppEvent ()
Destructor.
int type () const
Returns the event type.
void setPriority (int priority)
Set the event priority, range [0,100].
int priority () const
Get the event priority.
Private Attributes
std::string m_commandName = {""}
net::Buffer m_buffer = {}
Additional Inherited Members
Public Types inherited from dqm4hep::online::AppEvent
enum Type {
NONE = 0, QUIT, SERVICE_UPDATE, REQUEST_HANDLING,
COMMAND_HANDLING, CLIENT_EXIT, START_OF_RUN, END_OF_RUN,
END_OF_CYCLE, PROCESS_EVENT, USER = 1024, MAX_USER = 65535
}
AppEvent type enum.
Detailed Description
Definition at line 52 of file AppEvents.h.
Constructor & Destructor Documentation
dqm4hep::online::CommandEvent::CommandEvent (const std::string & commandName, net::BufferModelPtr bufferModel) inline
Definition at line 128 of file AppEvents.h.
References m_buffer, and dqm4hep::net::Buffer::setModel().
                                                                                            :
       AppEvent(AppEvent::COMMAND_HANDLING),
       m_commandName(cname) {
       m_buffer.setModel(bufferModel);
     }
Member Function Documentation
const net::Buffer & dqm4hep::online::CommandEvent::buffer () const inline
Definition at line 142 of file AppEvents.h.
References m_buffer.
Referenced by dqm4hep::online::ModuleApplication::receiveSubscriptionList().
{
       return m_buffer;
     }
const std::string & dqm4hep::online::CommandEvent::commandName () const inline
Definition at line 136 of file AppEvents.h.
References m_commandName.
Referenced by dqm4hep::online::ModuleApplication::onEvent(), and dqm4hep::online::Application::NetworkHandler::postCommandEvent().
{
       return m_commandName;
     }
Member Data Documentation
net::Buffer dqm4hep::online::CommandEvent::m_buffer = {} private
Definition at line 59 of file AppEvents.h.
Referenced by buffer(), and CommandEvent().
std::string dqm4hep::online::CommandEvent::m_commandName = {""} private
Definition at line 58 of file AppEvents.h.
Referenced by commandName().
The documentation for this class was generated from the following file:
AppEvents.h