DQM4hep: dqm4hep::net::RawBuffer Class Reference
dqm4hep::net::RawBuffer Class Reference
RawBuffer class.
#include <NetBuffer.h>
Public Member Functions
RawBuffer (const RawBuffer &)=delete
RawBuffer (RawBuffer &&)=delete
RawBuffer & operator= (const RawBuffer &)=delete
RawBuffer && operator= (RawBuffer &&)=delete
RawBuffer ()
Constructor.
const char * begin () const
Get the buffer begin address.
const char * end () const
Get the buffer end address.
size_t size () const
Get the buffer size.
void adopt (const char *buffer, size_t size)
Adopt a new buffer (does not own it !)
Private Attributes
const char * m_pBuffer = {nullptr}
The buffer.
size_t m_size = {0}
The buffer size.
Detailed Description
RawBuffer class.
Definition at line 41 of file NetBuffer.h.
Constructor & Destructor Documentation
dqm4hep::net::RawBuffer::RawBuffer (const RawBuffer &) delete
dqm4hep::net::RawBuffer::RawBuffer (RawBuffer &&) delete
dqm4hep::net::RawBuffer::RawBuffer ()
Constructor.
Definition at line 24 of file NetBuffer.cc.
References adopt(), dqm4hep::net::NullBuffer::buffer, and dqm4hep::net::NullBuffer::size.
{
       this->adopt(NullBuffer::buffer, NullBuffer::size);
     }
Member Function Documentation
void dqm4hep::net::RawBuffer::adopt (const char * buffer, size_t size)
Adopt a new buffer (does not own it !)
Parameters
buffer the buffer start address
size the buffer size
Definition at line 48 of file NetBuffer.cc.
References m_pBuffer, and m_size.
Referenced by dqm4hep::net::BufferModelT< std::string >::BufferModelT(), dqm4hep::net::BufferModelT< std::string >::copy(), dqm4hep::net::BufferModel::handle(), dqm4hep::net::BufferModelT< std::string >::move(), and RawBuffer().
{
       m_pBuffer = buffer;
       m_size = s;
     }
const char * dqm4hep::net::RawBuffer::begin () const
Get the buffer begin address.
Definition at line 30 of file NetBuffer.cc.
References m_pBuffer.
{
       return m_pBuffer;
     }
const char * dqm4hep::net::RawBuffer::end () const
Get the buffer end address.
Definition at line 36 of file NetBuffer.cc.
References m_pBuffer, and m_size.
{
       return m_pBuffer + m_size;
     }
RawBuffer& dqm4hep::net::RawBuffer::operator= (const RawBuffer &) delete
RawBuffer&& dqm4hep::net::RawBuffer::operator= (RawBuffer &&) delete
size_t dqm4hep::net::RawBuffer::size () const
Get the buffer size.
Definition at line 42 of file NetBuffer.cc.
References m_size.
{
       return m_size;
     }
Member Data Documentation
const char* dqm4hep::net::RawBuffer::m_pBuffer = {nullptr} private
The buffer.
Definition at line 77 of file NetBuffer.h.
Referenced by adopt(), begin(), and end().
size_t dqm4hep::net::RawBuffer::m_size = {0} private
The buffer size.
Definition at line 78 of file NetBuffer.h.
Referenced by adopt(), end(), and size().
The documentation for this class was generated from the following files:
NetBuffer.h
NetBuffer.cc