DQM4hep: dqm4hep::online::RunControl Class Reference
dqm4hep::online::RunControl Class Reference
RunControl class.
#include <RunControl.h>
Public Member Functions
RunControl ()=default
Default constructor.
RunControl (const std::string &name)
Constructor.
~RunControl ()
Destructor.
dqm4hep::core::StatusCode setName (const std::string &name)
Set the run control name.
const std::string & name () const
Get the run control name.
dqm4hep::core::StatusCode startNewRun (const dqm4hep::core::Run &run, const std::string &password="")
Start a new run.
dqm4hep::core::StatusCode startNewRun (int runNumber, const std::string &description="", const std::string &detectorName="", const dqm4hep::core::StringMap &parameters=dqm4hep::core::StringMap(), const std::string &password="")
Start a new run.
dqm4hep::core::StatusCode endCurrentRun (const dqm4hep::core::StringMap &parameters=dqm4hep::core::StringMap(), const std::string &password="")
End the current run.
const dqm4hep::core::Run & currentRun () const
Get the current run.
dqm4hep::core::Run & currentRun ()
Get the current run.
bool isRunning () const
Whether a run has been started.
void setPassword (const std::string &password)
Set the password needed to start/stop runs Throw exception if a run has already been started.
bool checkPassword (const std::string &password)
Check the run control password.
StartOfRunSignal & onStartOfRun ()
Get the start of run signal.
EndOfRunSignal & onEndOfRun ()
Get the end of run signal.
Protected Attributes
bool m_running = {false}
Whether a run has been started.
dqm4hep::core::Run m_run = {dqm4hep::core::Run()}
The main run object.
std::string m_name = {"Global"}
The run control name.
std::string m_password = {""}
An optional password to access the run control.
StartOfRunSignal m_sorSignal = {StartOfRunSignal()}
The start of run signal.
EndOfRunSignal m_eorSignal = {EndOfRunSignal()}
The end of run signal.
Detailed Description
RunControl class.
Implements the main logic of a run control. A run control has a name and optionally, a password to start/stop runs. One can use the SOR and EOR signals to be notified on start of run or end of run. E.g for SOR :
void MyClass::onStartOfRun(Run &run) {
  dqm_info( "Run no {0} has been started !", run.runNumber() );
}
void MyClass::onEndOfRun(const Run &run) {
  dqm_info( "Run no {0} ended !", run.runNumber() );
}
MyClass *usrObject = new MyClass();
RunControl runControl;
runControl.onStartOfRun().connect(usrObject, &MyClass::onStartOfRun);
runControl.onEndOfRun().connect(usrObject, &MyClass::onEndOfRun);
runControl.startNewRun(42); // onStartOfRun method called
// ..
runControl.endCurrentRun(); // onEndOfRun method called
Definition at line 51 of file RunControl.h.
Constructor & Destructor Documentation
dqm4hep::online::RunControl::RunControl () default
Default constructor.
dqm4hep::online::RunControl::RunControl (const std::string & name)
Constructor.
Parameters
name the run control name
Definition at line 25 of file RunControl.cc.
                                                   :
         m_name(rcname) {
       /* nop */
     }
dqm4hep::online::RunControl::~RunControl ()
Destructor.
Definition at line 32 of file RunControl.cc.
{
       /* nop */
     }
Member Function Documentation
bool dqm4hep::online::RunControl::checkPassword (const std::string & password)
Check the run control password.
Definition at line 133 of file RunControl.cc.
References m_password.
Referenced by endCurrentRun(), and startNewRun().
{
       if( m_password.empty() ) {
         return true;
       }
       if( m_password == password ) {
         return true;
       }
       return false;
     }
const Run & dqm4hep::online::RunControl::currentRun () const
Get the current run.
Definition at line 109 of file RunControl.cc.
References m_run.
Referenced by dqm4hep::online::ModuleApplication::processEndOfRun().
{
       return m_run;
     }
Run & dqm4hep::online::RunControl::currentRun ()
Get the current run.
Definition at line 115 of file RunControl.cc.
References m_run.
{
       return m_run;
     }
StatusCode dqm4hep::online::RunControl::endCurrentRun (const dqm4hep::core::StringMap & parameters = dqm4hep::core::StringMap(), const std::string & password = "")
End the current run.
Parameters
parameters optional parameters to end the run
password the password to handle the run control, if any
Definition at line 91 of file RunControl.cc.
References checkPassword(), dqm4hep::core::Signal< Args >::emit(), isRunning(), m_eorSignal, m_run, m_running, dqm4hep::core::Run::reset(), and dqm4hep::core::Run::setParameter().
Referenced by dqm4hep::online::ModuleApplication::onEvent(), and startNewRun().
{
       if( ! this->checkPassword(password) )
         return STATUS_CODE_NOT_ALLOWED;
       if( ! this->isRunning() )
         return STATUS_CODE_SUCCESS;
       for(auto &parameter : parameters)
         m_run.setParameter(parameter.first, parameter.second);
       m_eorSignal.emit(m_run);
       m_running = false;
       m_run.reset();
       return STATUS_CODE_SUCCESS;
     }
bool dqm4hep::online::RunControl::isRunning () const
Whether a run has been started.
Definition at line 121 of file RunControl.cc.
References m_running.
Referenced by endCurrentRun(), dqm4hep::online::ModuleApplication::onEvent(), dqm4hep::online::ModuleApplication::onStart(), setName(), and startNewRun().
{
       return m_running;
     }
const std::string & dqm4hep::online::RunControl::name () const
Get the run control name.
Definition at line 51 of file RunControl.cc.
References m_name.
Referenced by dqm4hep::online::ModuleApplication::onEvent(), dqm4hep::online::ModuleApplication::onInit(), and dqm4hep::online::ModuleApplication::onStart().
{
       return m_name;
     }
EndOfRunSignal & dqm4hep::online::RunControl::onEndOfRun ()
Get the end of run signal.
Definition at line 151 of file RunControl.cc.
References m_eorSignal.
Referenced by dqm4hep::online::ModuleApplication::onInit().
{
       return m_eorSignal;
     }
StartOfRunSignal & dqm4hep::online::RunControl::onStartOfRun ()
Get the start of run signal.
Definition at line 145 of file RunControl.cc.
References m_sorSignal.
Referenced by dqm4hep::online::ModuleApplication::onInit().
{
       return m_sorSignal;
     }
StatusCode dqm4hep::online::RunControl::setName (const std::string & name)
Set the run control name.
Parameters
name the run control name
Definition at line 38 of file RunControl.cc.
References isRunning(), and m_name.
Referenced by dqm4hep::online::ModuleApplication::configureNetwork().
{
       if(rcname == m_name)
         return STATUS_CODE_SUCCESS;
       if(this->isRunning())
         return STATUS_CODE_NOT_ALLOWED;
       m_name = rcname;
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::online::RunControl::setPassword (const std::string & password)
Set the password needed to start/stop runs Throw exception if a run has already been started.
Definition at line 127 of file RunControl.cc.
References m_password.
{
       m_password = password;
     }
StatusCode dqm4hep::online::RunControl::startNewRun (const dqm4hep::core::Run & run, const std::string & password = "")
Start a new run.
Parameters
run the run description
password the password to handle the run control, if any
Definition at line 57 of file RunControl.cc.
References checkPassword(), dqm4hep::core::Signal< Args >::emit(), endCurrentRun(), isRunning(), m_run, m_running, m_sorSignal, and RETURN_RESULT_IF.
Referenced by dqm4hep::online::ModuleApplication::onStart(), and dqm4hep::online::ModuleApplication::processStartOfRun().
{
       if( ! this->checkPassword(password) )
         return STATUS_CODE_NOT_ALLOWED;
       if(this->isRunning())
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->endCurrentRun(dqm4hep::core::StringMap(), password));
       m_run = run;
       m_running = true;
       m_sorSignal.emit(m_run);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::online::RunControl::startNewRun (int runNumber, const std::string & description = "", const std::string & detectorName = "", const dqm4hep::core::StringMap & parameters = dqm4hep::core::StringMap(), const std::string & password = "")
Start a new run.
End the current run if already running
Parameters
runNumber the run number
description the run description
detectorName the run detector name
parameters additional run parameters
password the password to handle the run control, if any
Definition at line 72 of file RunControl.cc.
References checkPassword(), dqm4hep::core::Signal< Args >::emit(), endCurrentRun(), isRunning(), m_run, m_running, m_sorSignal, RETURN_RESULT_IF, and dqm4hep::core::Run::setParameter().
{
       if( ! this->checkPassword(password) )
         return STATUS_CODE_NOT_ALLOWED;
       if(this->isRunning())
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->endCurrentRun(dqm4hep::core::StringMap(), password));
       m_run = Run(runNumber, description, detectorName);
       for(auto &parameter : parameters)
         m_run.setParameter(parameter.first, parameter.second);
       m_sorSignal.emit(m_run);
       m_running = true;
       return STATUS_CODE_SUCCESS;
     }
Member Data Documentation
EndOfRunSignal dqm4hep::online::RunControl::m_eorSignal = {EndOfRunSignal()} protected
The end of run signal.
Definition at line 152 of file RunControl.h.
Referenced by endCurrentRun(), and onEndOfRun().
std::string dqm4hep::online::RunControl::m_name = {"Global"} protected
The run control name.
Definition at line 149 of file RunControl.h.
Referenced by name(), and setName().
std::string dqm4hep::online::RunControl::m_password = {""} protected
An optional password to access the run control.
Definition at line 150 of file RunControl.h.
Referenced by checkPassword(), and setPassword().
dqm4hep::core::Run dqm4hep::online::RunControl::m_run = {dqm4hep::core::Run()} protected
The main run object.
Definition at line 148 of file RunControl.h.
Referenced by currentRun(), endCurrentRun(), and startNewRun().
bool dqm4hep::online::RunControl::m_running = {false} protected
Whether a run has been started.
Definition at line 147 of file RunControl.h.
Referenced by endCurrentRun(), isRunning(), and startNewRun().
StartOfRunSignal dqm4hep::online::RunControl::m_sorSignal = {StartOfRunSignal()} protected
The start of run signal.
Definition at line 151 of file RunControl.h.
Referenced by onStartOfRun(), and startNewRun().
The documentation for this class was generated from the following files:
RunControl.h
RunControl.cc