DQM4hep: dqm4hep::online::EventCollectorClient::SourceInfo Struct Reference
dqm4hep::online::EventCollectorClient::SourceInfo Struct Reference
SourceInfo struct.
Public Member Functions
void receiveEvent (const net::Buffer &buffer)
Public Attributes
EventUpdateSignal m_eventUpdateSignal = {}
The signal to process on event update.
EventCollectorClient * m_collectorClient = {nullptr}
Detailed Description
SourceInfo struct.
Definition at line 92 of file EventCollectorClient.h.
Member Function Documentation
void dqm4hep::online::EventCollectorClient::SourceInfo::receiveEvent (const net::Buffer & buffer)
Definition at line 21 of file EventCollectorClient.cc.
References dqm4hep::core::Signal< Args >::emit(), m_collectorClient, m_eventUpdateSignal, and dqm4hep::online::EventCollectorClient::readEvent().
Referenced by dqm4hep::online::EventCollectorClient::setUpdateMode().
{
       core::EventPtr event = m_collectorClient->readEvent(buffer);
       m_eventUpdateSignal.emit(event);
     }
Member Data Documentation
EventCollectorClient* dqm4hep::online::EventCollectorClient::SourceInfo::m_collectorClient = {nullptr}
Definition at line 94 of file EventCollectorClient.h.
Referenced by receiveEvent().
EventUpdateSignal dqm4hep::online::EventCollectorClient::SourceInfo::m_eventUpdateSignal = {}
The signal to process on event update.
Definition at line 93 of file EventCollectorClient.h.
Referenced by receiveEvent().
The documentation for this struct was generated from the following files:
EventCollectorClient.h
EventCollectorClient.cc