DQMOnline: dqm4hep::core::AnalysisModuleApplication Class Reference
dqm4hep::core::AnalysisModuleApplication Class Reference
AnalysisModuleApplication class.
#include <AnalysisModuleApplication.h>
Classes
class Settings
Settings class.
Public Member Functions
AnalysisModuleApplication ()
Constructor.
~AnalysisModuleApplication ()
Destructor.
const std::string & getType () const
Get the application type ("AnalysisModule")
const std::string & getName () const
Get the application name ("ModuleType/ModuleName")
StatusCode readSettings (const std::string &settingsFile)
Read settings from a xml file.
void setReplacementParameters (const ParameterMap &parametersMap)
Set the parameters to replace while reading settings.
StatusCode run ()
Run the application.
Run * getCurrentRun () const
Get the current run if any.
Cycle * getCycle () const
Get the cycle if any.
Public Member Functions inherited from dqm4hep::core::ModuleApplication
ModuleApplication ()
Constructor.
virtual ~ModuleApplication ()
Destructor.
virtual StatusCode exit (int returnCode)
Stop the application.
Module * getModule () const
Get the module for this application.
bool shouldStopApplication () const
Whether the module application should stop.
void setStopApplication (bool stopApplication)
Set the application stop flag.
StatusCode setModuleName (const std::string &name)
Set the module name in used.
StatusCode setModuleType (const std::string &type)
Set the module type to look for (before calling readSettings())
const std::string & getModuleName () const
Get the module name in used.
const std::string & getModuleType () const
Get the module type in used.
bool isInitialized () const
Whether the application is initialized.
StatusCode getReturnCode () const
Get the return code when application ends.
Public Member Functions inherited from dqm4hep::core::Application
virtual ~Application ()
Destructor.
Public Member Functions inherited from dqm4hep::core::CycleListener
virtual ~CycleListener ()
Destructor.
Private Member Functions
StatusCode configureModule (const TiXmlHandle xmlHandle)
Configure the module.
StatusCode configureNetwork (const TiXmlHandle xmlHandle)
Configure network interface.
StatusCode configureCycle (const TiXmlHandle xmlHandle)
Configure the workflow cycle.
StatusCode configureArchiver (const TiXmlHandle xmlHandle)
Configure the archiver.
StatusCode startServices ()
Start all services.
StatusCode stopServices ()
Stop all services.
int getCurrentRunNumber () const
Get the current run number that was started (not from run control)
void onEventProcessed (const Cycle *const pCycle, const Event *const pEvent)
Call back function when an event is processed by the framework.
void onCycleStarted (const Cycle *const pCycle)
Call back function when the cycle is started by the framework.
void onCycleStopped (const Cycle *const pCycle)
Call back function when the cycle is stopped by the framework.
Private Attributes
Settings m_settings
ParameterMap m_replacementParameters
EventClient * m_pEventClient
RunControlClient * m_pRunControlClient
Cycle * m_pCycle
Archiver * m_pArchiver
std::string m_applicationType
std::string m_applicationName
std::string m_moduleLogStr
int m_runNumber
Additional Inherited Members
Protected Member Functions inherited from dqm4hep::core::ModuleApplication
void setInitialized (bool initialized)
Set the application has initialized.
MonitorElementManager * getMonitorElementManager () const
Get the monitor element manager.
MonitorElementSender * getMonitorElementSender () const
Get the monitor element sender.
AlertNotifier * getAlertNotifier () const
Get the alert notifier.
StatusCode setModule (Module *pModule)
Set the module in use in this application.
StatusCode createAlertNotifier (const std::string moduleName)
Create the alert notifier with the module name.
Protected Attributes inherited from dqm4hep::core::ModuleApplication
StatusCode m_returnCode
Module * m_pModule
Detailed Description
AnalysisModuleApplication class.
Definition at line 51 of file AnalysisModuleApplication.h.
Constructor & Destructor Documentation
dqm4hep::core::AnalysisModuleApplication::AnalysisModuleApplication ()
Constructor.
Definition at line 61 of file AnalysisModuleApplication.cc.
References dqm4hep::core::ModuleApplication::Archiver, and m_pArchiver.
                                                          :
         ModuleApplication(),
         m_pEventClient(NULL),
         m_pRunControlClient(NULL),
         m_pCycle(NULL),
         m_applicationType("AnalysisModule"),
         m_applicationName("UNKNOWN"),
         m_moduleLogStr("[Analysis Module]"),
         m_runNumber(-1)
     {
       m_pArchiver = new Archiver();
     }
dqm4hep::core::AnalysisModuleApplication::~AnalysisModuleApplication ()
Destructor.
Definition at line 76 of file AnalysisModuleApplication.cc.
References m_pArchiver, m_pCycle, m_pEventClient, and m_pRunControlClient.
     {
       delete m_pArchiver;
       if(m_pEventClient)
         delete m_pEventClient;
       if(m_pRunControlClient)
         delete m_pRunControlClient;
       if(m_pCycle)
         delete m_pCycle;
     }
Member Function Documentation
StatusCode dqm4hep::core::AnalysisModuleApplication::configureArchiver (const TiXmlHandle xmlHandle) private
Configure the archiver.
Definition at line 570 of file AnalysisModuleApplication.cc.
References dqm4hep::core::AnalysisModuleApplication::Settings::m_archiveDirectory, m_moduleLogStr, m_settings, and dqm4hep::core::AnalysisModuleApplication::Settings::m_shouldOpenArchive.
Referenced by readSettings().
     {
       try
       {
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Configuring archiver ...");
         const TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("archiver").Element();
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "open", m_settings.m_shouldOpenArchive));
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "directory", m_settings.m_archiveDirectory));
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Configuring archiver ... OK");
       }
       catch(const StatusCodeException &exception)
       {
         return exception.getStatusCode();
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::AnalysisModuleApplication::configureCycle (const TiXmlHandle xmlHandle) private
Configure the workflow cycle.
Definition at line 466 of file AnalysisModuleApplication.cc.
References dqm4hep::core::Cycle::addListener(), dqm4hep::core::AnalysisModuleApplication::Settings::m_cycleTimeout, dqm4hep::core::AnalysisModuleApplication::Settings::m_cycleType, dqm4hep::core::AnalysisModuleApplication::Settings::m_cycleValue, m_moduleLogStr, m_pCycle, m_settings, dqm4hep::core::Cycle::setCycleValue(), and dqm4hep::core::Cycle::setTimeout().
Referenced by readSettings().
     {
       try
       {
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Configuring cycle ...");
         const TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("cycle").Element();
         // default values
         m_settings.m_cycleType = "TimerCycle";
         m_settings.m_cycleValue = 10; // 10 seconds
         m_settings.m_cycleTimeout = 3; // 3 seconds
         if(pXmlElement)
         {
           THROW_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(pXmlElement, "type", m_settings.m_cycleType));
           THROW_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(pXmlElement, "value", m_settings.m_cycleValue));
           THROW_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(pXmlElement, "timeout", m_settings.m_cycleTimeout));
         }
         // find the cycle plug-in
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Creating cycle of type " << m_settings.m_cycleType <<  "...");
         m_pCycle = PluginManager::instance()->createPluginClass<Cycle>(m_settings.m_cycleType);
         if( ! m_pCycle )
         {
           LOG4CXX_FATAL( dqmMainLogger , m_moduleLogStr << " , Cycle of type " << m_settings.m_cycleType << " not found !");
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Creating cycle of type " << m_settings.m_cycleType <<  "... OK");
         m_pCycle->setCycleValue(m_settings.m_cycleValue);
         m_pCycle->setTimeout(m_settings.m_cycleTimeout);
         m_pCycle->addListener(this);
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Configuring cycle ... OK");
       }
       catch(const StatusCodeException &exception)
       {
         LOG4CXX_FATAL( dqmMainLogger , m_moduleLogStr << " , Couldn't configure cycle !");
         return exception.getStatusCode();
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::AnalysisModuleApplication::configureModule (const TiXmlHandle xmlHandle) private
Configure the module.
Definition at line 515 of file AnalysisModuleApplication.cc.
References dqm4hep::core::ModuleApplication::getModule(), dqm4hep::core::ModuleApplication::getModuleName(), dqm4hep::core::ModuleApplication::getModuleType(), dqm4hep::core::Module::getName(), getName(), m_applicationName, m_moduleLogStr, readSettings(), dqm4hep::core::ModuleApplication::setModule(), dqm4hep::core::ModuleApplication::setModuleName(), and dqm4hep::core::ModuleApplication::setModuleType().
Referenced by readSettings().
     {
       try
       {
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Configuring module ...");
         TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("module").Element();
         std::string type;
         std::string name;
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "type", type));
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "name", name));
         if(this->getModuleType().empty())
           this->setModuleType(type);
         if(this->getModuleName().empty())
           this->setModuleName(name);
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Querying analysis module to plugin manager ...");
         AnalysisModule *pAnalysisModule = PluginManager::instance()->createPluginClass<AnalysisModule>(this->getModuleType());
         if(!pAnalysisModule)
           throw StatusCodeException(STATUS_CODE_FAILURE);
         this->setModule(pAnalysisModule);
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Querying analysis module to plugin manager ... OK");
         TiXmlHandle moduleHandle(pXmlElement);
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Reading settings of active module '" << this->getModule()->getName() << "' ...");
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->readSettings(moduleHandle));
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Reading settings of active module '" << this->getModule()->getName() << "' ... OK");
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Initializing active module '" << this->getModule()->getName() << "' ...");
         THROW_RESULT_IF( STATUS_CODE_SUCCESS, !=, this->getModule()->initModule() );
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Initializing active module '" << this->getModule()->getName() << "' ... OK");
         m_applicationName = this->getModule()->getName();
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Configuring module ... OK");
       }
       catch(const StatusCodeException &exception)
       {
         return exception.getStatusCode();
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::AnalysisModuleApplication::configureNetwork (const TiXmlHandle xmlHandle) private
Configure network interface.
Definition at line 390 of file AnalysisModuleApplication.cc.
References dqm4hep::core::ModuleApplication::getMonitorElementSender(), dqm4hep::core::AnalysisModuleApplication::Settings::m_eventClientType, m_moduleLogStr, dqm4hep::core::AnalysisModuleApplication::Settings::m_monitorElementCollector, m_pEventClient, m_pRunControlClient, dqm4hep::core::AnalysisModuleApplication::Settings::m_runControlName, dqm4hep::core::AnalysisModuleApplication::Settings::m_runControlType, m_settings, dqm4hep::core::EventClient::readSettings(), and dqm4hep::core::EventClient::setUpdateMode().
Referenced by readSettings().
     {
       try
       {
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Configuring network ...");
         //
         // Get all xml attributes needed to configure network options !
         //
         TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("network").Element();
         if(NULL == pXmlElement)
         {
           LOG4CXX_FATAL( dqmMainLogger , m_moduleLogStr << " , <network> element not found !");
           return STATUS_CODE_NOT_FOUND;
         }
         const TiXmlHandle networkHandle(pXmlElement);
         TiXmlElement *const pRunControlXmlElement = networkHandle.FirstChildElement("runcontrol").Element();
         TiXmlElement *const pEventCollectorXmlElement = networkHandle.FirstChildElement("eventcollector").Element();
         TiXmlElement *const pMonitorElementCollectorXmlElement = networkHandle.FirstChildElement("monitorelementcollector").Element();
         if(NULL == pRunControlXmlElement
             || NULL == pEventCollectorXmlElement
             || NULL == pMonitorElementCollectorXmlElement)
         {
           LOG4CXX_FATAL( dqmMainLogger , m_moduleLogStr << " , incomplete network xml element !");
           return STATUS_CODE_NOT_FOUND;
         }
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pRunControlXmlElement, "name", m_settings.m_runControlName));
         THROW_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(pRunControlXmlElement, "type", m_settings.m_runControlType));
         THROW_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::getAttribute(pEventCollectorXmlElement, "type", m_settings.m_eventClientType));
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pMonitorElementCollectorXmlElement, "name", m_settings.m_monitorElementCollector));
         //
         // Configure network form the extracted xml values
         //
         // monitor element collector name
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->setCollectorName(m_settings.m_monitorElementCollector));
         // event client
         EventClient *pEventClient = PluginManager::instance()->createPluginClass<EventClient>(m_settings.m_eventClientType);
         if( ! pEventClient )
           throw StatusCodeException(STATUS_CODE_FAILURE);
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pEventClient->readSettings( TiXmlHandle(pEventCollectorXmlElement) ));
         // force update mode to false for the moment
         pEventClient->setUpdateMode(false);
         m_pEventClient = pEventClient;
         // configure run control
         RunControlClient *pRunControlClient = PluginManager::instance()->createPluginClass<RunControlClient>(m_settings.m_runControlType);
         if(NULL == pRunControlClient)
           throw StatusCodeException(STATUS_CODE_NOT_FOUND);
         pRunControlClient->setRunControlName( m_settings.m_runControlName );
         m_pRunControlClient = pRunControlClient;
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Configuring network ... OK");
       }
       catch(const StatusCodeException &exception)
       {
         return exception.getStatusCode();
       }
       return STATUS_CODE_SUCCESS;
     }
Run * dqm4hep::core::AnalysisModuleApplication::getCurrentRun () const
Get the current run if any.
Definition at line 362 of file AnalysisModuleApplication.cc.
References m_pRunControlClient.
Referenced by dqm4hep::core::ModuleApi::getTimeSinceStartOfRun().
     {
       return m_pRunControlClient->getCurrentRun();
     }
int dqm4hep::core::AnalysisModuleApplication::getCurrentRunNumber () const private
Get the current run number that was started (not from run control)
Definition at line 622 of file AnalysisModuleApplication.cc.
References m_runNumber.
Referenced by run().
     {
       return m_runNumber;
     }
Cycle * dqm4hep::core::AnalysisModuleApplication::getCycle () const
Get the cycle if any.
Definition at line 369 of file AnalysisModuleApplication.cc.
References m_pCycle.
Referenced by dqm4hep::core::ModuleApi::getTimeSinceStartOfCycle().
     {
       return m_pCycle;
     }
const std::string & dqm4hep::core::AnalysisModuleApplication::getName () const virtual
Get the application name ("ModuleType/ModuleName")
Implements dqm4hep::core::ModuleApplication.
Definition at line 383 of file AnalysisModuleApplication.cc.
References m_applicationName.
Referenced by configureModule().
     {
       return m_applicationName;
     }
const std::string & dqm4hep::core::AnalysisModuleApplication::getType () const virtual
Get the application type ("AnalysisModule")
Implements dqm4hep::core::ModuleApplication.
Definition at line 376 of file AnalysisModuleApplication.cc.
References m_applicationType.
     {
       return m_applicationType;
     }
void dqm4hep::core::AnalysisModuleApplication::onCycleStarted (const Cycle *const pCycle) private virtual
Call back function when the cycle is started by the framework.
Implements dqm4hep::core::CycleListener.
Definition at line 629 of file AnalysisModuleApplication.cc.
References dqm4hep::core::ModuleApplication::getModule().
     {
       THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->startOfCycle());
     }
void dqm4hep::core::AnalysisModuleApplication::onCycleStopped (const Cycle *const pCycle) private virtual
Call back function when the cycle is stopped by the framework.
Implements dqm4hep::core::CycleListener.
Definition at line 636 of file AnalysisModuleApplication.cc.
References dqm4hep::core::ModuleApplication::getModule().
     {
       THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->endOfCycle());
     }
void dqm4hep::core::AnalysisModuleApplication::onEventProcessed (const Cycle *const pCycle, const Event *const pEvent) inline private virtual
Call back function when an event is processed by the framework.
Implements dqm4hep::core::CycleListener.
Definition at line 149 of file AnalysisModuleApplication.h.
 { /* nop */ }
StatusCode dqm4hep::core::AnalysisModuleApplication::readSettings (const std::string & settingsFile) virtual
Read settings from a xml file.
Initialize the application. Declare all the services, load the shared libraries, configure the active module
Implements dqm4hep::core::ModuleApplication.
Definition at line 92 of file AnalysisModuleApplication.cc.
References configureArchiver(), configureCycle(), configureModule(), configureNetwork(), dqm4hep::core::ModuleApplication::getModule(), dqm4hep::core::Module::getName(), dqm4hep::core::ModuleApplication::isInitialized(), m_moduleLogStr, m_replacementParameters, m_settings, dqm4hep::core::AnalysisModuleApplication::Settings::m_settingsFileName, dqm4hep::core::AnalysisModuleApplication::Settings::print(), and dqm4hep::core::ModuleApplication::setInitialized().
Referenced by configureModule().
     {
       if(this->isInitialized())
         return STATUS_CODE_ALREADY_INITIALIZED;
       size_t splitterPosition = settingsFileName.find(":");
       std::string fileHandlerType;
       std::string filePattern;
       if(splitterPosition != std::string::npos)
       {
         fileHandlerType = settingsFileName.substr(0, splitterPosition);
         filePattern = settingsFileName.substr(splitterPosition+1);
       }
       else
       {
         fileHandlerType = "";
         filePattern = settingsFileName;
       }
       LOG4CXX_INFO( dqmMainLogger , "Starting analysis module application with file handler type " << fileHandlerType );
       FileHandlerFactory fileHandlerFactory;
       FileHandler *pFileHandler = fileHandlerFactory.createFileHandler(fileHandlerType);
       if(!pFileHandler)
         return STATUS_CODE_FAILURE;
       StatusCode statusCode = pFileHandler->download(filePattern);
       if(statusCode != STATUS_CODE_SUCCESS)
       {
         delete pFileHandler;
         return statusCode;
       }
       std::string localSettingsFile = pFileHandler->getLocalFileName();
       delete pFileHandler;
       TiXmlDocument xmlDocument(localSettingsFile);
       if (!xmlDocument.LoadFile())
       {
         LOG4CXX_FATAL( dqmMainLogger , "AnalysisModuleApplication::readSettings - Invalid xml file." );
         return STATUS_CODE_FAILURE;
       }
       const TiXmlHandle xmlDocumentHandle(&xmlDocument);
       if( ! m_replacementParameters.empty() )
       {
         TiXmlElement *pXmlElement = xmlDocumentHandle.FirstChildElement().Element();
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::replaceAllXmlAttributes(pXmlElement, m_replacementParameters));
       }
       const TiXmlHandle xmlHandle = TiXmlHandle(xmlDocumentHandle.FirstChildElement().Element());
       // configure module
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, configureModule(xmlHandle));
       DimBrowser browser;
       int nServers = browser.getServers();
       std::string moduleServerName = "DQM4HEP/Module/" + this->getModule()->getName();
       m_moduleLogStr = "[" + this->getModule()->getName() + "]";
       if(nServers)
       {
         char *serverName;
         char *node;
         while(browser.getNextServer(serverName, node))
         {
           if(moduleServerName == serverName)
           {
             LOG4CXX_FATAL( dqmMainLogger , m_moduleLogStr << " already registered over the network.\n"
                 << "Please, change the module name or stop the other module application with the same name !" );
             return STATUS_CODE_ALREADY_PRESENT;
           }
         }
       }
       DimServer::start( moduleServerName.c_str() );
       // configure remaining part of the application
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->configureCycle(xmlHandle));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->configureArchiver(xmlHandle));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->configureNetwork(xmlHandle));
       m_settings.m_settingsFileName = settingsFileName;
       m_settings.print(m_moduleLogStr);
       setInitialized(true);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::AnalysisModuleApplication::run () virtual
Run the application.
Implements dqm4hep::core::ModuleApplication.
Definition at line 199 of file AnalysisModuleApplication.cc.
References dqm4hep::core::EventClient::clearQueue(), dqm4hep::core::AnalysisModule::endOfRun(), dqm4hep::core::Cycle::eventProcessed(), getCurrentRunNumber(), dqm4hep::core::ModuleApplication::getModule(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), dqm4hep::core::Module::getName(), dqm4hep::core::Cycle::getNProcessedEvents(), dqm4hep::core::Cycle::getProcessingRate(), dqm4hep::core::ModuleApplication::getReturnCode(), dqm4hep::core::Cycle::getTotalCycleTime(), dqm4hep::core::Cycle::isEndOfCycleReached(), dqm4hep::core::ModuleApplication::isInitialized(), dqm4hep::core::Cycle::isTimeoutReached(), dqm4hep::core::AnalysisModuleApplication::Settings::m_archiveDirectory, m_moduleLogStr, m_pArchiver, m_pCycle, m_pEventClient, m_pRunControlClient, m_runNumber, m_settings, dqm4hep::core::AnalysisModuleApplication::Settings::m_shouldOpenArchive, dqm4hep::core::AnalysisModule::processEvent(), dqm4hep::core::EventClient::setUpdateMode(), dqm4hep::core::ModuleApplication::shouldStopApplication(), dqm4hep::core::Cycle::startCycle(), dqm4hep::core::AnalysisModule::startOfRun(), startServices(), dqm4hep::core::Cycle::stopCycle(), stopServices(), and dqm4hep::core::EventClient::takeEvent().
     {
       if(!this->isInitialized())
         return STATUS_CODE_NOT_INITIALIZED;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->startServices());
       // get casted module for easier manipulation
       AnalysisModule *pAnalysisModule = dynamic_cast<AnalysisModule *>(this->getModule());
       std::string moduleName = pAnalysisModule->getName();
       // infinite loop
       while(!this->shouldStopApplication())
       {
         // wait for a start of run
         bool firstMessage = true;
         while(!m_pRunControlClient->isRunning() && !this->shouldStopApplication())
         {
           if(firstMessage)
           {
             LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , waiting for next run ..." );
             firstMessage = false;
           }
           CoreTool::sleep(std::chrono::seconds(1));
         }
         if(this->shouldStopApplication())
           break;
         Run *pRun = m_pRunControlClient->getCurrentRun();
         if(NULL == pRun)
           continue;
         m_runNumber = pRun->getRunNumber();
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Starting new run no " << m_runNumber );
         // open an archive
         if(m_settings.m_shouldOpenArchive)
         {
           std::stringstream archiveFileName;
           std::string directory =
               m_settings.m_archiveDirectory.at(m_settings.m_archiveDirectory.size() - 1) == '/' ?
                   m_settings.m_archiveDirectory : m_settings.m_archiveDirectory + "/";
           archiveFileName << directory
               << "DQMArchive"
               << "_M" << moduleName
               <<  "_I" << pRun->getRunNumber();
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->open(archiveFileName.str(), "RECREATE"));
           LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Archive '" << m_pArchiver->getFileName() << "' opened" );
         }
         // start of run !
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pAnalysisModule->startOfRun(pRun));
         // start receiving data
         m_pEventClient->setUpdateMode(true);
         // while run has not ended, process cycles
         while( m_pRunControlClient->isRunning() && !this->shouldStopApplication() )
         {
           // process a cycle
           LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Start of cycle");
           m_pCycle->startCycle();
           while(1)
           {
             if( m_pCycle->isEndOfCycleReached() )
               break;
             if( m_pCycle->isTimeoutReached() )
               break;
             if( this->shouldStopApplication() )
               break;
             EventPtr event;
             m_pEventClient->takeEvent(event);
             if(NULL == event)
               continue;
             try
             {
               StatusCode statusCode = pAnalysisModule->processEvent(event.get());
               m_pCycle->eventProcessed(event.get());
             }
             catch(StatusCodeException &exception)
             {
               LOG4CXX_ERROR( dqmMainLogger , m_moduleLogStr << " , Module::processEvent(evt) returned " << exception.toString() << " !");
             }
             catch(...)
             {
               LOG4CXX_ERROR( dqmMainLogger , m_moduleLogStr << " , Module::processEvent(evt) caught unknown exception !");
             }
           }
           m_pCycle->stopCycle();
           LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , End of cycle reached !");
           LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Printing statistics :");
           LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , *** N processed events : " << m_pCycle->getNProcessedEvents());
           LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , *** Event rate         : " << m_pCycle->getProcessingRate() << " evts/s");
           LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , *** Processing time    : " << m_pCycle->getTotalCycleTime().count() << " s");
           // archive publication if user asked for
           if(m_settings.m_shouldOpenArchive)
             RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->archive(pAnalysisModule));
           //      MonitorElementList monitorElementListToPublish;
           //      RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementManager()
           //          ->getMonitorElementListToPublish(monitorElementListToPublish));
           // TODO find a way to update the run number in monitor elements
           //      // set monitor elements infos
           //      for(MonitorElementList::iterator iter = monitorElementListToPublish.begin(), endIter = monitorElementListToPublish.end() ;
           //          endIter != iter ; ++iter)
           //        (*iter)->setRunNumber(this->getCurrentRunNumber());
           // send monitor elements to collector
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->sendMonitorElements());
           // reset the monitor elements with end of run reset policy
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementManager()
               ->resetMonitorElements(END_OF_CYCLE_RESET_POLICY));
           // stop current run if run number has changed or run stopped
           if(m_pRunControlClient->getCurrentRunNumber() != this->getCurrentRunNumber())
             break;
         }
         // stop receive data and clear contents
         m_pEventClient->setUpdateMode(false);
         m_pEventClient->clearQueue();
         // fill the run end time
         pRun->setEndTime(CoreTool::now());
         // process the end of run module stuff
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pAnalysisModule->endOfRun(pRun));
         // reset the monitor elements that have been reset at end of run
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementManager()
             ->resetMonitorElements(END_OF_RUN_RESET_POLICY));
         // archive the monitor element if archive is opened
         if(m_settings.m_shouldOpenArchive)
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->close());
       }
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, stopServices());
       LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Exiting application !");
       return this->getReturnCode();
     }
void dqm4hep::core::AnalysisModuleApplication::setReplacementParameters (const ParameterMap & parametersMap)
Set the parameters to replace while reading settings.
Definition at line 192 of file AnalysisModuleApplication.cc.
References m_replacementParameters.
     {
       m_replacementParameters = parametersMap;
     }
StatusCode dqm4hep::core::AnalysisModuleApplication::startServices () private
Start all services.
Called just at beginning of run()
Definition at line 593 of file AnalysisModuleApplication.cc.
References dqm4hep::core::RunControlClient::connectToService(), dqm4hep::core::EventClient::connectToService(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), m_pEventClient, and m_pRunControlClient.
Referenced by run().
     {
       // start clients
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pEventClient->connectToService());
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControlClient->connectToService());
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->connectToService());
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::AnalysisModuleApplication::stopServices () private
Stop all services.
Called at the end of run() before exit
Definition at line 605 of file AnalysisModuleApplication.cc.
References dqm4hep::core::RunControlClient::connectToService(), dqm4hep::core::MonitorElementSender::connectToService(), dqm4hep::core::EventClient::connectToService(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), dqm4hep::core::RunControlClient::isConnectedToService(), dqm4hep::core::MonitorElementSender::isConnectedToService(), dqm4hep::core::EventClient::isConnectedToService(), m_pEventClient, and m_pRunControlClient.
Referenced by run().
     {
       // start clients
       if(m_pEventClient && m_pEventClient->isConnectedToService())
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pEventClient->connectToService());
       if(m_pRunControlClient && m_pRunControlClient->isConnectedToService())
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControlClient->connectToService());
       if(this->getMonitorElementSender() && this->getMonitorElementSender()->isConnectedToService())
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->connectToService());
       return STATUS_CODE_SUCCESS;
     }
Member Data Documentation
std::string dqm4hep::core::AnalysisModuleApplication::m_applicationName private
Definition at line 164 of file AnalysisModuleApplication.h.
Referenced by configureModule(), and getName().
std::string dqm4hep::core::AnalysisModuleApplication::m_applicationType private
Definition at line 163 of file AnalysisModuleApplication.h.
Referenced by getType().
std::string dqm4hep::core::AnalysisModuleApplication::m_moduleLogStr private
Definition at line 165 of file AnalysisModuleApplication.h.
Referenced by configureArchiver(), configureCycle(), configureModule(), configureNetwork(), readSettings(), and run().
Archiver* dqm4hep::core::AnalysisModuleApplication::m_pArchiver private
Definition at line 161 of file AnalysisModuleApplication.h.
Referenced by AnalysisModuleApplication(), run(), and ~AnalysisModuleApplication().
Cycle* dqm4hep::core::AnalysisModuleApplication::m_pCycle private
Definition at line 160 of file AnalysisModuleApplication.h.
Referenced by configureCycle(), getCycle(), run(), and ~AnalysisModuleApplication().
EventClient* dqm4hep::core::AnalysisModuleApplication::m_pEventClient private
Definition at line 158 of file AnalysisModuleApplication.h.
Referenced by configureNetwork(), run(), startServices(), stopServices(), and ~AnalysisModuleApplication().
RunControlClient* dqm4hep::core::AnalysisModuleApplication::m_pRunControlClient private
Definition at line 159 of file AnalysisModuleApplication.h.
Referenced by configureNetwork(), getCurrentRun(), run(), startServices(), stopServices(), and ~AnalysisModuleApplication().
ParameterMap dqm4hep::core::AnalysisModuleApplication::m_replacementParameters private
Definition at line 156 of file AnalysisModuleApplication.h.
Referenced by readSettings(), and setReplacementParameters().
int dqm4hep::core::AnalysisModuleApplication::m_runNumber private
Definition at line 167 of file AnalysisModuleApplication.h.
Referenced by getCurrentRunNumber(), and run().
Settings dqm4hep::core::AnalysisModuleApplication::m_settings private
Definition at line 155 of file AnalysisModuleApplication.h.
Referenced by configureArchiver(), configureCycle(), configureNetwork(), readSettings(), and run().
The documentation for this class was generated from the following files:
AnalysisModuleApplication.h
AnalysisModuleApplication.cc