DQMOnline: dqm4hep::core::DimRunControlClient Class Reference
dqm4hep::core::DimRunControlClient Class Reference
RunControlClient class.
#include <DimRunControlClient.h>
Public Member Functions
DimRunControlClient ()
Constructor.
~DimRunControlClient ()
Destructor.
StatusCode connectToService ()
Connect to the service.
StatusCode disconnectFromService ()
Disconnect from the service.
bool isConnectedToService () const
Whether the client is connected to the service.
StatusCode sendStartNewRun (Run *pRun, const std::string &password="")
Create a new run from a Run The run control is the owner the run.
StatusCode sendStartNewRun (int runNumber, const std::string &description="", const std::string &detectorName="", const std::string &password="")
Create a new run.
StatusCode sendEndCurrentRun (const std::string &password="")
End the current run.
Public Member Functions inherited from dqm4hep::core::RunControlClient
RunControlClient ()
Constructor.
virtual ~RunControlClient ()
Destructor.
Private Member Functions
void infoHandler ()
Dim info handler.
void handleCurrentRunRpcInfo (DimRpcInfo *pRpcInfo)
Handle the dim current run rpc info.
void configureInBuffer (char *pBuffer, uint32_t bufferSize)
Configure the xdrstream buffer with the input socket buffer.
Private Attributes
bool m_isConnected
Whether the client is connected to the server instance.
xdrstream::BufferDevice * m_pInBuffer
The xdr buffer to deserialize the run at start of run.
xdrstream::BufferDevice * m_pOutBuffer
The xdr buffer to serialize data.
DimInfo * m_pStartOfRunInfo
The dim start of run info.
DimInfo * m_pEndOfRunInfo
The dim end of run info.
DimRpcInfo * m_pCurrentRunRpcInfo
The dim current run rpc info.
DimRpcInfo * m_pStartNewRunRpcInfo
The dim start new run rpc info.
DimRpcInfo * m_pEndRunRpcInfo
The dim end current run rpc info.
Friends
class CurrentRunRpcInfo
class StartNewRunRpcInfo
class EndCurrentRunRpcInfo
Detailed Description
RunControlClient class.
Definition at line 72 of file DimRunControlClient.h.
Constructor & Destructor Documentation
dqm4hep::core::DimRunControlClient::DimRunControlClient ()
Constructor.
Definition at line 59 of file DimRunControlClient.cc.
References m_pOutBuffer.
                                              :
         RunControlClient(),
         m_isConnected(false),
         m_pStartOfRunInfo(NULL),
         m_pEndOfRunInfo(NULL),
         m_pInBuffer(0)
     {
       m_pOutBuffer = new xdrstream::BufferDevice( 10*1024 );
     }
dqm4hep::core::DimRunControlClient::~DimRunControlClient ()
Destructor.
Definition at line 71 of file DimRunControlClient.cc.
References disconnectFromService(), isConnectedToService(), m_pInBuffer, and m_pOutBuffer.
     {
       if( this->isConnectedToService() )
         this->disconnectFromService();
       if( m_pInBuffer )
         delete m_pInBuffer;
       delete m_pOutBuffer;
     }
Member Function Documentation
void dqm4hep::core::DimRunControlClient::configureInBuffer (char * pBuffer, uint32_t bufferSize) private
Configure the xdrstream buffer with the input socket buffer.
Definition at line 373 of file DimRunControlClient.cc.
References m_pInBuffer.
Referenced by handleCurrentRunRpcInfo(), and infoHandler().
     {
       if( ! m_pInBuffer )
         m_pInBuffer = new xdrstream::BufferDevice( pBuffer , bufferSize , false );
       else
         m_pInBuffer->setBuffer( pBuffer , bufferSize , false );
       m_pInBuffer->setOwner( false );
     }
StatusCode dqm4hep::core::DimRunControlClient::connectToService () virtual
Connect to the service.
Implements dqm4hep::core::RunControlClient.
Definition at line 84 of file DimRunControlClient.cc.
References CurrentRunRpcInfo, isConnectedToService(), m_isConnected, m_pCurrentRunRpcInfo, m_pEndOfRunInfo, and m_pStartOfRunInfo.
     {
       if(isConnectedToService())
         return STATUS_CODE_SUCCESS;
       std::string sorServiceName = "DQM4HEP/RunControl/" + this->getRunControlName() + "/START_OF_RUN";
       std::string eorServiceName = "DQM4HEP/RunControl/" + this->getRunControlName() + "/END_OF_RUN";
       std::string currentRunRpcName = "DQM4HEP/RunControl/" + this->getRunControlName() + "/CURRENT_RUN";
       m_pStartOfRunInfo = new DimUpdatedInfo(sorServiceName.c_str(), (void*) NULL, 0, this);
       m_pEndOfRunInfo = new DimUpdatedInfo(eorServiceName.c_str(), (void*) NULL, 0, this);
       m_pCurrentRunRpcInfo = new CurrentRunRpcInfo( (char *) currentRunRpcName.c_str() , this );
       m_isConnected = true;
       sleep(1);
       int dummy = 0;
       m_pCurrentRunRpcInfo->setData(dummy);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimRunControlClient::disconnectFromService () virtual
Disconnect from the service.
Implements dqm4hep::core::RunControlClient.
Definition at line 108 of file DimRunControlClient.cc.
References isConnectedToService(), m_isConnected, m_pCurrentRunRpcInfo, m_pEndOfRunInfo, and m_pStartOfRunInfo.
Referenced by ~DimRunControlClient().
     {
       if(!isConnectedToService())
         return STATUS_CODE_SUCCESS;
       delete m_pStartOfRunInfo; m_pStartOfRunInfo = NULL;
       delete m_pEndOfRunInfo; m_pEndOfRunInfo = NULL;
       delete m_pCurrentRunRpcInfo; m_pCurrentRunRpcInfo = NULL;
       m_isConnected = false;
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::DimRunControlClient::handleCurrentRunRpcInfo (DimRpcInfo * pRpcInfo) private
Handle the dim current run rpc info.
Definition at line 331 of file DimRunControlClient.cc.
References configureInBuffer(), isConnectedToService(), and m_pInBuffer.
Referenced by dqm4hep::core::CurrentRunRpcInfo::rpcInfoHandler().
     {
       if( ! this->isConnectedToService() )
         return;
       Run *pRun = new Run();
       try
       {
         dqm_char *pBuffer = static_cast<dqm_char*>(pRpcInfo->getData());
         dqm_uint  bufferSize = pRpcInfo->getSize();
         if(NULL == pBuffer || 0 == bufferSize)
           throw StatusCodeException(STATUS_CODE_FAILURE);
         this->configureInBuffer( pBuffer, bufferSize );
         if( xdrstream::XDR_SUCCESS != pRun->stream( xdrstream::XDR_READ_STREAM , m_pInBuffer ) )
           throw StatusCodeException(STATUS_CODE_FAILURE);
         // run number is invalid, meaning not running
         if(pRun->getRunNumber() <= 0)
           throw StatusCodeException(STATUS_CODE_SUCCESS);
         // run is adopted here by the run control. No need to delete
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->startNewRun(pRun));
         LOG4CXX_INFO( dqmMainLogger , "Starting new run " << this->getCurrentRun()->getRunNumber() );
         // return avoids run deletion
         return;
       }
       catch(StatusCodeException &exception)
       {
       }
       if(pRun)
         delete pRun;
     }
void dqm4hep::core::DimRunControlClient::infoHandler () private
Dim info handler.
Definition at line 255 of file DimRunControlClient.cc.
References configureInBuffer(), isConnectedToService(), m_pEndOfRunInfo, m_pInBuffer, and m_pStartOfRunInfo.
     {
       std::cout << "received info " << getInfo()->getName() << std::endl;
       DimInfo *pCurrentDimInfo = getInfo();
       if(m_pStartOfRunInfo == pCurrentDimInfo)
       {
         if(this->isRunning() || !this->isConnectedToService())
         {
           std::cout << "pouette 1 !" << std::endl;
           return;
         }
         dqm_char *pBuffer = static_cast<dqm_char*>(pCurrentDimInfo->getData());
         dqm_uint  bufferSize = pCurrentDimInfo->getSize();
         if(pBuffer == NULL || bufferSize == 0)
         {
           std::cout << "pouette 2 !" << std::endl;
           return;
         }
         this->configureInBuffer( pBuffer, bufferSize );
         Run *pRun = new Run();
         try
         {
           std::cout << "pouette stream !" << std::endl;
           if( xdrstream::XDR_SUCCESS != pRun->stream( xdrstream::XDR_READ_STREAM , m_pInBuffer ) )
             throw StatusCodeException(STATUS_CODE_FAILURE);
           std::cout << "pouette run number !" << std::endl;
           if(pRun->getRunNumber() < 0)
             throw StatusCodeException(STATUS_CODE_INVALID_PARAMETER);
           std::cout << "pouette start !" << std::endl;
           // run is adopted here by the run control. No need to delete
           THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->startNewRun(pRun));
           std::cout << "pouette 1 after " << std::endl;
           LOG4CXX_INFO( dqmMainLogger , "Starting new run " << this->getCurrentRun()->getRunNumber() );
         }
         catch(StatusCodeException &exception)
         {
           std::cout << "pouette catch !" << std::endl;
           if(pRun)
             delete pRun;
         }
       }
       else if(m_pEndOfRunInfo == pCurrentDimInfo)
       {
         if(!this->isRunning() || !this->isConnectedToService())
           return;
         try
         {
           int currentRunNumber = this->getCurrentRun()->getRunNumber();
           THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->endCurrentRun());
           LOG4CXX_INFO( dqmMainLogger , "Ending run " << currentRunNumber );
         }
         catch(StatusCodeException &exception)
         {
           LOG4CXX_WARN( dqmMainLogger , "Couldn't stop the run (at stop) : " << exception.toString() );
           return;
         }
       }
       else
       {
         LOG4CXX_WARN( dqmMainLogger , "Unknown info handled by the run control client : " << pCurrentDimInfo->getName() );
       }
     }
bool dqm4hep::core::DimRunControlClient::isConnectedToService () const virtual
Whether the client is connected to the service.
Implements dqm4hep::core::RunControlClient.
Definition at line 124 of file DimRunControlClient.cc.
References m_isConnected.
Referenced by connectToService(), disconnectFromService(), handleCurrentRunRpcInfo(), infoHandler(), and ~DimRunControlClient().
     {
       return m_isConnected;
     }
StatusCode dqm4hep::core::DimRunControlClient::sendEndCurrentRun (const std::string & password = "")
End the current run.
Definition at line 216 of file DimRunControlClient.cc.
References m_pOutBuffer.
     {
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != m_pOutBuffer->write( &password ))
         return STATUS_CODE_FAILURE;
       if( xdrstream::XDR_SUCCESS != m_pOutBuffer->write( &password ) )
         return STATUS_CODE_FAILURE;
       DimRpcInfo rpc( (char *)("DQM4HEP/RunControl/" + this->getRunControlName() + "/END_CURRENT_RUN").c_str(), (void *) NULL , 0 );
       // send end current run signal and wait for response
       rpc.setData( (void *) m_pOutBuffer->getBuffer() , m_pOutBuffer->getPosition() );
       RpcResponse *response = (RpcResponse *) rpc.getData();
       if( ! response )
       {
         LOG4CXX_ERROR( dqmMainLogger, "FAILURE  ----> No response from server !");
         return STATUS_CODE_FAILURE;
       }
       if( response->m_ok )
       {
         LOG4CXX_INFO( dqmMainLogger, "OK  ----> " << response->m_pMessage );
       }
       else
       {
         LOG4CXX_ERROR( dqmMainLogger, "FAILURE  ----> " << response->m_pMessage );
         return STATUS_CODE_FAILURE;
       }
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, RunControl::endCurrentRun( password ));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimRunControlClient::sendStartNewRun (Run * pRun, const std::string & password = "")
Create a new run from a Run The run control is the owner the run.
Definition at line 131 of file DimRunControlClient.cc.
References m_pOutBuffer.
     {
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != m_pOutBuffer->write( &password ))
         return STATUS_CODE_FAILURE;
       if( xdrstream::XDR_SUCCESS != pRun->stream( xdrstream::XDR_WRITE_STREAM , m_pOutBuffer ) )
         return STATUS_CODE_FAILURE;
       DimRpcInfo rpc( (char *)("DQM4HEP/RunControl/" + this->getRunControlName() + "/START_NEW_RUN").c_str(), (void *) NULL , 0 );
       // send new run signal and wait for response
       rpc.setData( (void *) m_pOutBuffer->getBuffer() , m_pOutBuffer->getPosition() );
       RpcResponse *response = (RpcResponse *) rpc.getData();
       if( ! response )
       {
         LOG4CXX_ERROR( dqmMainLogger, "FAILURE  ----> No response from server !");
         return STATUS_CODE_FAILURE;
       }
       if( response->m_ok )
       {
         LOG4CXX_INFO( dqmMainLogger, "OK  ----> " << response->m_pMessage );
       }
       else
       {
         LOG4CXX_ERROR( dqmMainLogger, "FAILURE  ----> " << response->m_pMessage );
         return STATUS_CODE_FAILURE;
       }
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, RunControl::startNewRun( pRun, password ));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimRunControlClient::sendStartNewRun (int runNumber, const std::string & description = "", const std::string & detectorName = "", const std::string & password = "")
Create a new run.
End the current run if running
Definition at line 170 of file DimRunControlClient.cc.
References m_pOutBuffer.
     {
       Run *pRun = new Run( runNumber, description, detectorName );
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != m_pOutBuffer->write( &password ))
         return STATUS_CODE_FAILURE;
       if( xdrstream::XDR_SUCCESS != pRun->stream( xdrstream::XDR_WRITE_STREAM , m_pOutBuffer ) )
       {
         delete pRun;
         return STATUS_CODE_FAILURE;
       }
       DimRpcInfo rpc( (char *)("DQM4HEP/RunControl/" + this->getRunControlName() + "/START_NEW_RUN").c_str(), (void *) NULL , 0 );
       // send new run signal and wait for response
       rpc.setData( (void *) m_pOutBuffer->getBuffer() , m_pOutBuffer->getPosition() );
       RpcResponse *response = (RpcResponse *) rpc.getData();
       if( ! response )
       {
         delete pRun;
         LOG4CXX_ERROR( dqmMainLogger, "FAILURE  ----> No response from server !");
         return STATUS_CODE_FAILURE;
       }
       if( response->m_ok )
       {
         LOG4CXX_INFO( dqmMainLogger, "OK  ----> " << response->m_pMessage );
       }
       else
       {
         LOG4CXX_ERROR( dqmMainLogger, "FAILURE  ----> " << response->m_pMessage );
         delete pRun;
         return STATUS_CODE_FAILURE;
       }
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, RunControl::startNewRun( pRun, password ));
       return STATUS_CODE_SUCCESS;
     }
Friends And Related Function Documentation
friend class CurrentRunRpcInfo friend
Definition at line 134 of file DimRunControlClient.h.
Referenced by connectToService().
friend class EndCurrentRunRpcInfo friend
Definition at line 136 of file DimRunControlClient.h.
friend class StartNewRunRpcInfo friend
Definition at line 135 of file DimRunControlClient.h.
Member Data Documentation
bool dqm4hep::core::DimRunControlClient::m_isConnected private
Whether the client is connected to the server instance.
Definition at line 124 of file DimRunControlClient.h.
Referenced by connectToService(), disconnectFromService(), and isConnectedToService().
DimRpcInfo* dqm4hep::core::DimRunControlClient::m_pCurrentRunRpcInfo private
The dim current run rpc info.
Definition at line 130 of file DimRunControlClient.h.
Referenced by connectToService(), and disconnectFromService().
DimInfo* dqm4hep::core::DimRunControlClient::m_pEndOfRunInfo private
The dim end of run info.
Definition at line 129 of file DimRunControlClient.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
DimRpcInfo* dqm4hep::core::DimRunControlClient::m_pEndRunRpcInfo private
The dim end current run rpc info.
Definition at line 132 of file DimRunControlClient.h.
xdrstream::BufferDevice* dqm4hep::core::DimRunControlClient::m_pInBuffer private
The xdr buffer to deserialize the run at start of run.
Definition at line 125 of file DimRunControlClient.h.
Referenced by configureInBuffer(), handleCurrentRunRpcInfo(), infoHandler(), and ~DimRunControlClient().
xdrstream::BufferDevice* dqm4hep::core::DimRunControlClient::m_pOutBuffer private
The xdr buffer to serialize data.
Definition at line 126 of file DimRunControlClient.h.
Referenced by DimRunControlClient(), sendEndCurrentRun(), sendStartNewRun(), and ~DimRunControlClient().
DimRpcInfo* dqm4hep::core::DimRunControlClient::m_pStartNewRunRpcInfo private
The dim start new run rpc info.
Definition at line 131 of file DimRunControlClient.h.
DimInfo* dqm4hep::core::DimRunControlClient::m_pStartOfRunInfo private
The dim start of run info.
Definition at line 128 of file DimRunControlClient.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
The documentation for this class was generated from the following files:
DimRunControlClient.h
DimRunControlClient.cc