DQMOnline: dqm4hep::core::EventCollectorImp Class Reference
dqm4hep::core::EventCollectorImp Class Reference abstract
EventCollectorImp class.
#include <EventCollectorImp.h>
Public Member Functions
virtual ~EventCollectorImp ()
Destructor.
virtual StatusCode setCollectorName (const std::string &collectorName)=0
Set the collector name.
virtual const std::string & getCollectorName () const =0
Get the collector name.
virtual bool isRunning () const =0
Whether the collector server is running.
virtual StatusCode startCollector ()=0
Start the collector server.
virtual StatusCode stopCollector ()=0
Stop the collector server.
virtual void setEventStreamer (EventStreamer *pEventStreamer)=0
Set the event streamer to serialize/deserialize the in/out-coming events.
virtual EventStreamer * getEventStreamer () const =0
Get the event streamer.
Detailed Description
EventCollectorImp class.
Definition at line 40 of file EventCollectorImp.h.
Constructor & Destructor Documentation
virtual dqm4hep::core::EventCollectorImp::~EventCollectorImp () inline virtual
Destructor.
Definition at line 45 of file EventCollectorImp.h.
 {}
Member Function Documentation
virtual const std::string& dqm4hep::core::EventCollectorImp::getCollectorName () const pure virtual
Get the collector name.
Implemented in dqm4hep::core::DimEventCollector.
Referenced by dqm4hep::core::EventCollector::getCollectorName().
virtual EventStreamer* dqm4hep::core::EventCollectorImp::getEventStreamer () const pure virtual
Get the event streamer.
Implemented in dqm4hep::core::DimEventCollector.
Referenced by dqm4hep::core::EventCollector::getEventStreamer().
virtual bool dqm4hep::core::EventCollectorImp::isRunning () const pure virtual
Whether the collector server is running.
Implemented in dqm4hep::core::DimEventCollector.
Referenced by dqm4hep::core::EventCollector::isRunning().
virtual StatusCode dqm4hep::core::EventCollectorImp::setCollectorName (const std::string & collectorName) pure virtual
Set the collector name.
Implemented in dqm4hep::core::DimEventCollector.
Referenced by dqm4hep::core::EventCollector::setCollectorName().
virtual void dqm4hep::core::EventCollectorImp::setEventStreamer (EventStreamer * pEventStreamer) pure virtual
Set the event streamer to serialize/deserialize the in/out-coming events.
Implemented in dqm4hep::core::DimEventCollector.
Referenced by dqm4hep::core::EventCollector::setEventStreamer().
virtual StatusCode dqm4hep::core::EventCollectorImp::startCollector () pure virtual
Start the collector server.
Implemented in dqm4hep::core::DimEventCollector.
Referenced by dqm4hep::core::EventCollector::startCollector().
virtual StatusCode dqm4hep::core::EventCollectorImp::stopCollector () pure virtual
Stop the collector server.
Implemented in dqm4hep::core::DimEventCollector.
Referenced by dqm4hep::core::EventCollector::stopCollector().
The documentation for this class was generated from the following file:
EventCollectorImp.h