DQMOnline: dqm4hep::online::HttpRunControl Class Reference
dqm4hep::online::HttpRunControl Class Reference
Public Member Functions
HttpRunControl ()
~HttpRunControl ()
void readSettings (const dqm4hep::core::StringMap &parameters)
Read settings from map.
bool runBlocking () const
Whether calling the run() method is blocking.
void run ()
Run the user run control.
void stop ()
Stop the user run control.
void setup ()
Public Member Functions inherited from dqm4hep::online::RunControlInterface
virtual ~RunControlInterface ()
Destructor.
Private Member Functions
void receiveStartOfRunPost (Mongoose::Request &request, Mongoose::StreamResponse &response)
void receiveEndOfRunPost (Mongoose::Request &request, Mongoose::StreamResponse &response)
void getRunStatus (Mongoose::Request &request, Mongoose::StreamResponse &response)
void printEor (const dqm4hep::core::Run &run)
Private Attributes
int m_port
bool m_stopFlag
Additional Inherited Members
Protected Member Functions inherited from dqm4hep::online::RunControlInterface
void startNewRun (const dqm4hep::core::Run &run, const std::string &password="")
Start a new run (dqm4hep::online::RunControl class).
void endCurrentRun (const dqm4hep::core::StringMap &parameters=dqm4hep::core::StringMap(), const std::string &password="")
End the current run A passwork may be specified if the run control application has been started with a password.
const RunControl & runControl () const
Get the run control.
StartOfRunSignal & onStartOfRun ()
Get the run control start of run signal.
EndOfRunSignal & onEndOfRun ()
Get the run control end of run signal.
Detailed Description
Definition at line 50 of file HttpRunControlPlugin.cc.
Constructor & Destructor Documentation
dqm4hep::online::HttpRunControl::HttpRunControl ()
Definition at line 76 of file HttpRunControlPlugin.cc.
                                    :
       m_port(8000),
       m_stopFlag(false)
     {
     }
dqm4hep::online::HttpRunControl::~HttpRunControl ()
Definition at line 84 of file HttpRunControlPlugin.cc.
     {
     }
Member Function Documentation
void dqm4hep::online::HttpRunControl::getRunStatus (Mongoose::Request & request, Mongoose::StreamResponse & response) private
Definition at line 255 of file HttpRunControlPlugin.cc.
References dqm4hep::online::RunControl::currentRun(), dqm4hep::online::RunControl::isRunning(), and dqm4hep::online::RunControlInterface::runControl().
Referenced by setup().
     {
       dqm_info("Received GET: /{0}/STATUS", this->runControl().name());
       Json::Value jsonRun;
       this->runControl().currentRun().toJson(jsonRun);
       jsonRun["running"] = this->runControl().isRunning();
       Json::StreamWriterBuilder builder;
       builder["indentation"] = "  ";
       std::unique_ptr<Json::StreamWriter> writer(builder.newStreamWriter());
       writer->write(jsonRun, &response);
     }
void dqm4hep::online::HttpRunControl::printEor (const dqm4hep::core::Run & run) private
Definition at line 245 of file HttpRunControlPlugin.cc.
References run().
Referenced by readSettings().
     {
       std::stringstream ss; ss << run;
       dqm_info( "****** Ended run ******" );
       dqm_info( "{0}", ss.str() );
       dqm_info( "***********************" );
     }
void dqm4hep::online::HttpRunControl::readSettings (const dqm4hep::core::StringMap & parameters) virtual
Read settings from map.
Parameters
parameters a key/value map with user settings (string to string)
Implements dqm4hep::online::RunControlInterface.
Definition at line 90 of file HttpRunControlPlugin.cc.
References m_port, dqm4hep::online::RunControlInterface::onEndOfRun(), and printEor().
     {
       auto portIter = parameters.find("port");
       if(portIter != parameters.end())
       {
         dqm4hep::core::stringToType(portIter->second, m_port);
       }
       this->onEndOfRun().connect(this, &HttpRunControl::printEor);
     }
void dqm4hep::online::HttpRunControl::receiveEndOfRunPost (Mongoose::Request & request, Mongoose::StreamResponse & response) private
Definition at line 204 of file HttpRunControlPlugin.cc.
References dqm4hep::online::RunControlInterface::endCurrentRun(), and dqm4hep::online::RunControlInterface::runControl().
Referenced by setup().
     {
       dqm_info("Received POST: /{0}/EOR", this->runControl().name());
       if(! this->runControl().isRunning())
       {
         response << "ERROR: Not running ! Couldn't end current run !";
         return;
       }
       std::map<std::string, std::string> variables(request.getAllVariable());
       std::string password;
       dqm4hep::core::StringMap parameters;
       for(auto iter = variables.begin(), endIter = variables.end() ; endIter != iter ; ++iter)
       {
         if( iter->first == "password" )
         {
           password = iter->second;
           continue;
         }
         parameters[iter->first] = iter->second;
       }
       try
       {
         this->endCurrentRun(parameters, password);
       }
       catch( dqm4hep::core::StatusCodeException &exception )
       {
         response << "ERROR: Couldn't stop current run ! Exception: " << exception.toString() << std::endl;
         return;
       }
       response << "SUCCESS";
     }
void dqm4hep::online::HttpRunControl::receiveStartOfRunPost (Mongoose::Request & request, Mongoose::StreamResponse & response) private
Definition at line 135 of file HttpRunControlPlugin.cc.
References run(), dqm4hep::online::RunControlInterface::runControl(), and dqm4hep::online::RunControlInterface::startNewRun().
Referenced by setup().
     {
       dqm_info("Received POST: /{0}/SOR", this->runControl().name() );
       std::map<std::string, std::string> variables(request.getAllVariable());
       std::map<std::string, std::string> urlVariables;
       request.getVars(urlVariables);
       dqm4hep::core::Run run;
       std::string password;
       bool consistent = false;
       for(auto iter = variables.begin(), endIter = variables.end() ; endIter != iter ; ++iter)
       {
         if(iter->first == "run")
         {
           int runNumber = 0;
           dqm4hep::core::stringToType(iter->second, runNumber);
           run.setRunNumber(runNumber);
           consistent = true;
           continue;
         }
         if(iter->first == "description")
         {
           run.setDescription(iter->second);
           continue;
         }
         if(iter->first == "detectorName")
         {
           run.setDetectorName(iter->second);
           continue;
         }
         if(iter->first == "password")
         {
           password = iter->second;
           continue;
         }
         run.setParameter(iter->first, iter->second);
       }
       if(! consistent)
       {
         response << "ERROR: Run number required to start a new run !!"<< std::endl;
         return;
       }
       try
       {
         this->startNewRun(run, password);
         std::stringstream ss; ss << run;
         dqm_info( "*** Started new run ***" );
         dqm_info( "{0}", ss.str() );
         dqm_info( "***********************" );
       }
       catch( dqm4hep::core::StatusCodeException &exception )
       {
         response << "ERROR: Couldn't start new run ! What :" << exception.toString()<< std::endl;
         return;
       }
       response << "SUCCESS";
     }
void dqm4hep::online::HttpRunControl::run () virtual
Run the user run control.
Implements dqm4hep::online::RunControlInterface.
Definition at line 113 of file HttpRunControlPlugin.cc.
References m_port, and m_stopFlag.
Referenced by printEor(), and receiveStartOfRunPost().
     {
       Server server(m_port);
       server.registerController(this);
       server.start();
       this->dumpRoutes();
       while(!m_stopFlag)
         dqm4hep::core::sleep(dqm4hep::core::TimeDuration(1));
       server.stop();
     }
bool dqm4hep::online::HttpRunControl::runBlocking () const inline virtual
Whether calling the run() method is blocking.
This mainly depends on whether the external interface is implemented in a separated thread. In this case, return false.
Implements dqm4hep::online::RunControlInterface.
Definition at line 56 of file HttpRunControlPlugin.cc.
 { return true; }
void dqm4hep::online::HttpRunControl::setup ()
Definition at line 104 of file HttpRunControlPlugin.cc.
References getRunStatus(), receiveEndOfRunPost(), receiveStartOfRunPost(), and dqm4hep::online::RunControlInterface::runControl().
     {
       addRoute("POST", "/" + this->runControl().name() + "/SOR", HttpRunControl, receiveStartOfRunPost);
       addRoute("POST", "/" + this->runControl().name() + "/EOR", HttpRunControl, receiveEndOfRunPost);
       addRoute("GET",  "/" + this->runControl().name() + "/STATUS", HttpRunControl , getRunStatus );
     }
void dqm4hep::online::HttpRunControl::stop () virtual
Stop the user run control.
Implements dqm4hep::online::RunControlInterface.
Definition at line 128 of file HttpRunControlPlugin.cc.
References m_stopFlag.
     {
       m_stopFlag = true;
     }
Member Data Documentation
int dqm4hep::online::HttpRunControl::m_port private
Definition at line 69 of file HttpRunControlPlugin.cc.
Referenced by readSettings(), and run().
bool dqm4hep::online::HttpRunControl::m_stopFlag private
Definition at line 70 of file HttpRunControlPlugin.cc.
Referenced by run(), and stop().
The documentation for this class was generated from the following file:
HttpRunControlPlugin.cc