DQMOnline: dqm4hep::core::MonitorElementCollectorApplication Class Reference
dqm4hep::core::MonitorElementCollectorApplication Class Reference
MonitorElementCollectorApplication class.
#include <MonitorElementCollectorApplication.h>
Public Member Functions
MonitorElementCollectorApplication ()
Constructor with collector name.
~MonitorElementCollectorApplication ()
Destructor.
StatusCode run ()
Run the application.
StatusCode exit (int returnCode)
Stop the application.
const std::string & getName () const
Get the application name.
const std::string & getType () const
Get the application type.
StatusCode setCollectorName (const std::string &collectorName)
Set the monitor element collector name.
Protected Member Functions
StatusCode readSettings (const std::string &settingsFile="")
No settings to read.
Protected Attributes
bool m_shouldExit
std::string m_type
State m_applicationState
MonitorElementCollector * m_pMonitorElementCollector
Detailed Description
MonitorElementCollectorApplication class.
Definition at line 42 of file MonitorElementCollectorApplication.h.
Constructor & Destructor Documentation
dqm4hep::core::MonitorElementCollectorApplication::MonitorElementCollectorApplication ()
Constructor with collector name.
Definition at line 41 of file MonitorElementCollectorApplication.cc.
References m_pMonitorElementCollector.
                                                                            :
         m_applicationState(STOPPED_STATE),
         m_shouldExit(false),
         m_type("MonitorElementCollector")
     {
       m_pMonitorElementCollector = new MonitorElementCollector();
     }
dqm4hep::core::MonitorElementCollectorApplication::~MonitorElementCollectorApplication ()
Destructor.
Definition at line 51 of file MonitorElementCollectorApplication.cc.
References dqm4hep::core::MonitorElementCollector::isRunning(), m_pMonitorElementCollector, and dqm4hep::core::MonitorElementCollector::stop().
     {
       if(m_pMonitorElementCollector->isRunning())
         m_pMonitorElementCollector->stop();
       delete m_pMonitorElementCollector;
     }
Member Function Documentation
StatusCode dqm4hep::core::MonitorElementCollectorApplication::exit (int returnCode)
Stop the application.
Definition at line 81 of file MonitorElementCollectorApplication.cc.
References m_applicationState, m_pMonitorElementCollector, m_shouldExit, and dqm4hep::core::MonitorElementCollector::stop().
     {
       if(m_applicationState == STOPPED_STATE)
         return STATUS_CODE_FAILURE;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementCollector->stop());
       m_shouldExit = true;
       m_applicationState = STOPPED_STATE;
       StatusCode returnStatusCode;
       if(returnCode >= 0 && returnCode < NUMBER_OF_STATUS_CODES)
         returnStatusCode = static_cast<StatusCode>(returnCode);
       else
         returnStatusCode = STATUS_CODE_FAILURE;
       return returnStatusCode;
     }
const std::string & dqm4hep::core::MonitorElementCollectorApplication::getName () const
Get the application name.
Definition at line 103 of file MonitorElementCollectorApplication.cc.
References dqm4hep::core::MonitorElementCollector::getCollectorName(), and m_pMonitorElementCollector.
Referenced by run().
     {
       return m_pMonitorElementCollector->getCollectorName();
     }
const std::string & dqm4hep::core::MonitorElementCollectorApplication::getType () const
Get the application type.
Definition at line 110 of file MonitorElementCollectorApplication.cc.
References m_type.
Referenced by run().
     {
       return m_type;
     }
StatusCode dqm4hep::core::MonitorElementCollectorApplication::readSettings (const std::string & settingsFile = "") inline protected
No settings to read.
Definition at line 76 of file MonitorElementCollectorApplication.h.
 { return STATUS_CODE_SUCCESS; }
StatusCode dqm4hep::core::MonitorElementCollectorApplication::run ()
Run the application.
Definition at line 61 of file MonitorElementCollectorApplication.cc.
References getName(), getType(), m_applicationState, m_pMonitorElementCollector, m_shouldExit, and dqm4hep::core::MonitorElementCollector::start().
     {
       if(m_applicationState == RUNNING_STATE)
         return STATUS_CODE_FAILURE;
       m_applicationState = RUNNING_STATE;
       DimServer::addClientExitHandler(m_pMonitorElementCollector);
       DimServer::start( ("DQM4HEP/" + getType() + "/" + getName()).c_str() );
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pMonitorElementCollector->start());
       while( ! m_shouldExit )
         CoreTool::sleep(std::chrono::seconds(1));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementCollectorApplication::setCollectorName (const std::string & collectorName)
Set the monitor element collector name.
Definition at line 117 of file MonitorElementCollectorApplication.cc.
References m_pMonitorElementCollector, and dqm4hep::core::MonitorElementCollector::setCollectorName().
     {
       return m_pMonitorElementCollector->setCollectorName(collectorName);
     }
Member Data Documentation
State dqm4hep::core::MonitorElementCollectorApplication::m_applicationState protected
Definition at line 80 of file MonitorElementCollectorApplication.h.
Referenced by exit(), and run().
MonitorElementCollector* dqm4hep::core::MonitorElementCollectorApplication::m_pMonitorElementCollector protected
Definition at line 81 of file MonitorElementCollectorApplication.h.
Referenced by exit(), getName(), MonitorElementCollectorApplication(), run(), setCollectorName(), and ~MonitorElementCollectorApplication().
bool dqm4hep::core::MonitorElementCollectorApplication::m_shouldExit protected
Definition at line 78 of file MonitorElementCollectorApplication.h.
Referenced by exit(), and run().
std::string dqm4hep::core::MonitorElementCollectorApplication::m_type protected
Definition at line 79 of file MonitorElementCollectorApplication.h.
Referenced by getType().
The documentation for this class was generated from the following files:
MonitorElementCollectorApplication.h
MonitorElementCollectorApplication.cc