DQMOnline: dqm4hep::online::AppEventLoop::Timer Class Reference
dqm4hep::online::AppEventLoop::Timer Class Reference
Timer class.
Public Member Functions
Timer (const std::string &name, AppEventLoop &loop)
const std::string & name () const
void setTimeout (int nSeconds)
int timeout () const
void startTimer ()
void stopTimer ()
void setSingleShot (bool single)
bool singleShot () const
core::Signal< void > & onTimeout ()
Private Member Functions
void timerHandler ()
Private Attributes
std::string m_name = {""}
core::Signal< void > m_timeoutSignal = {}
bool m_singleShot = {true}
int m_timeout = {10}
AppEventLoop & m_appEventLoop
Detailed Description
Timer class.
Definition at line 192 of file AppEventLoop.h.
Constructor & Destructor Documentation
dqm4hep::online::AppEventLoop::Timer::Timer (const std::string & name, AppEventLoop & loop)
Definition at line 39 of file AppEventLoop.cc.
                                                                    :
       DimTimer(),
       m_name(n),
       m_appEventLoop(loop)
     {
       /* nop */
     }
Member Function Documentation
const std::string & dqm4hep::online::AppEventLoop::Timer::name () const
Definition at line 49 of file AppEventLoop.cc.
Referenced by dqm4hep::online::AppEventLoop::removeTimer().
{
       return m_name;
     }
core::Signal< void > & dqm4hep::online::AppEventLoop::Timer::onTimeout ()
Definition at line 91 of file AppEventLoop.cc.
Referenced by dqm4hep::online::AppEventLoop::createTimer().
{
       return m_timeoutSignal;
     }
void dqm4hep::online::AppEventLoop::Timer::setSingleShot (bool single)
Definition at line 79 of file AppEventLoop.cc.
Referenced by dqm4hep::online::AppEventLoop::createTimer().
{
       m_singleShot = single;
     }
void dqm4hep::online::AppEventLoop::Timer::setTimeout (int nSeconds)
Definition at line 55 of file AppEventLoop.cc.
Referenced by dqm4hep::online::AppEventLoop::createTimer().
{
       m_timeout = nSeconds;
     }
bool dqm4hep::online::AppEventLoop::Timer::singleShot () const
Definition at line 85 of file AppEventLoop.cc.
{
       return m_singleShot;
     }
void dqm4hep::online::AppEventLoop::Timer::startTimer ()
Definition at line 67 of file AppEventLoop.cc.
Referenced by dqm4hep::online::AppEventLoop::createTimer().
{
       DimTimer::start(m_timeout);
     }
void dqm4hep::online::AppEventLoop::Timer::stopTimer ()
Definition at line 73 of file AppEventLoop.cc.
{
       DimTimer::stop();
     }
int dqm4hep::online::AppEventLoop::Timer::timeout () const
Definition at line 61 of file AppEventLoop.cc.
{
       return m_timeout;
     }
void dqm4hep::online::AppEventLoop::Timer::timerHandler () private
Definition at line 97 of file AppEventLoop.cc.
{
       // process the timeout in the event loop
       m_appEventLoop.processFunction([this](){
         this->m_timeoutSignal.process();
       });
       // restart in not single shot
       if(!singleShot()) {
         startTimer();
       }
       else {
         m_appEventLoop.removeTimer(this);
       }
     }
Member Data Documentation
AppEventLoop& dqm4hep::online::AppEventLoop::Timer::m_appEventLoop private
Definition at line 213 of file AppEventLoop.h.
std::string dqm4hep::online::AppEventLoop::Timer::m_name = {""} private
Definition at line 209 of file AppEventLoop.h.
bool dqm4hep::online::AppEventLoop::Timer::m_singleShot = {true} private
Definition at line 211 of file AppEventLoop.h.
int dqm4hep::online::AppEventLoop::Timer::m_timeout = {10} private
Definition at line 212 of file AppEventLoop.h.
core::Signal<void> dqm4hep::online::AppEventLoop::Timer::m_timeoutSignal = {} private
Definition at line 210 of file AppEventLoop.h.
The documentation for this class was generated from the following files:
AppEventLoop.h
AppEventLoop.cc