DQMOnline: dqm4hep::core::AlertNotifier Class Reference
dqm4hep::core::AlertNotifier Class Reference abstract
AlertNotifier class.
#include <AlertSystem.h>
Public Member Functions
AlertNotifier (const std::string &emitter)
Constructor with emitter name.
virtual ~AlertNotifier ()
const std::string & getEmitter () const
StatusCode notify (AlertType type, const std::string &message, const MonitorElementPtr &monitorElement=nullptr)
void setMinAlertInterval (int nSeconds)
virtual StatusCode startService ()=0
virtual StatusCode stopService ()=0
virtual bool isRunning () const =0
Protected Member Functions
virtual StatusCode userNotify (AlertType type, const std::string &message, const MonitorElementPtr &monitorElement=nullptr)=0
Send alert notification to clients.
Private Attributes
std::string m_emitter
int m_minAlertInterval
time_t m_lastNotificationTime
Detailed Description
AlertNotifier class.
Definition at line 105 of file AlertSystem.h.
Constructor & Destructor Documentation
dqm4hep::core::AlertNotifier::AlertNotifier (const std::string & emitter)
Constructor with emitter name.
Definition at line 162 of file AlertSystem.cc.
                                                          :
         m_emitter(emitter),
         m_minAlertInterval(-1),
         m_lastNotificationTime(0)
     {
       /* nop */
     }
dqm4hep::core::AlertNotifier::~AlertNotifier () virtual
Definition at line 172 of file AlertSystem.cc.
     {
       /* nop */
     }
Member Function Documentation
const std::string & dqm4hep::core::AlertNotifier::getEmitter () const
Definition at line 179 of file AlertSystem.cc.
References m_emitter.
Referenced by dqm4hep::core::DimAlertNotifier::startService(), and dqm4hep::core::DimAlertNotifier::userNotify().
     {
       return m_emitter;
     }
virtual bool dqm4hep::core::AlertNotifier::isRunning () const pure virtual
Implemented in dqm4hep::core::DimAlertNotifier.
Referenced by notify().
StatusCode dqm4hep::core::AlertNotifier::notify (AlertType type, const std::string & message, const MonitorElementPtr & monitorElement = nullptr)
Definition at line 186 of file AlertSystem.cc.
References isRunning(), m_lastNotificationTime, and m_minAlertInterval.
Referenced by dqm4hep::core::ModuleApi::sendAlert().
     {
       if( ! this->isRunning() )
         return STATUS_CODE_NOT_INITIALIZED;
       time_t currentTime = time(0);
       if( m_minAlertInterval > 0 && currentTime - m_lastNotificationTime < m_minAlertInterval )
         return STATUS_CODE_UNCHANGED;
       m_lastNotificationTime = currentTime;
       return this->notify(type, message, monitorElement);
     }
void dqm4hep::core::AlertNotifier::setMinAlertInterval (int nSeconds)
Definition at line 203 of file AlertSystem.cc.
References m_minAlertInterval.
     {
       m_minAlertInterval = nSeconds;
     }
virtual StatusCode dqm4hep::core::AlertNotifier::startService () pure virtual
Implemented in dqm4hep::core::DimAlertNotifier.
virtual StatusCode dqm4hep::core::AlertNotifier::stopService () pure virtual
Implemented in dqm4hep::core::DimAlertNotifier.
virtual StatusCode dqm4hep::core::AlertNotifier::userNotify (AlertType type, const std::string & message, const MonitorElementPtr & monitorElement = nullptr) protected pure virtual
Send alert notification to clients.
Implemented in dqm4hep::core::DimAlertNotifier.
Member Data Documentation
std::string dqm4hep::core::AlertNotifier::m_emitter private
Definition at line 148 of file AlertSystem.h.
Referenced by getEmitter().
time_t dqm4hep::core::AlertNotifier::m_lastNotificationTime private
Definition at line 150 of file AlertSystem.h.
Referenced by notify().
int dqm4hep::core::AlertNotifier::m_minAlertInterval private
Definition at line 149 of file AlertSystem.h.
Referenced by notify(), and setMinAlertInterval().
The documentation for this class was generated from the following files:
AlertSystem.h
AlertSystem.cc