DQMOnline: dqm4hep::core::TimerCycle Class Reference
dqm4hep::core::TimerCycle Class Reference
TimerCycle class.
#include <TimerCycle.h>
Public Member Functions
TimerCycle ()
Constructor.
~TimerCycle ()
Destructor.
void onCycleStarted ()
Specific call back function when a cycle is stopped.
void onCycleStopped ()
Specific call back function when a cycle is stopped.
void onEventProcessed (const Event *const)
Specific call back function when an event is processed, depends on cycle type.
bool isEndOfCycleReached () const
Specific function to tell the application to know whether the cycle has reached the end.
Public Member Functions inherited from dqm4hep::core::Cycle
Cycle ()
Constructor.
virtual ~Cycle ()
Destructor.
float getCycleValue () const
Get the cycle value (time, nb of events, event size)
void setCycleValue (float value)
Set the cycle value.
unsigned int getTimeout () const
Get the cycle timeout (in seconds) Maximum time between two processEvent(evt) call.
void setTimeout (unsigned int timeout)
Set the timeout.
float getProcessingRate () const
Get the processing rate.
unsigned int getNProcessedEvents () const
Get the number of processed events at the end of cycle.
TimeDuration getTotalCycleTime () const
Get the total time spent to process the last cycle.
void eventProcessed (const Event *const pEvent)
Called back when the application has processed an event.
const TimePoint & getStartTime () const
Get the start time of the current cycle.
const TimePoint & getEndTime () const
Get the end time of the last cycle.
void startCycle ()
Start the cycle.
void stopCycle ()
Stop the cycle.
State getState () const
Get the cycle state (running, stopped)
bool isTimeoutReached () const
Whether the timeout is reached.
void addListener (CycleListener *pListener)
Add a cycle listener.
void removeListener (CycleListener *pListener)
Remove a cycle listener.
Detailed Description
TimerCycle class.
Cycle based on a time cycle in seconds. processCycle() called during n seconds
Definition at line 43 of file TimerCycle.h.
Constructor & Destructor Documentation
dqm4hep::core::TimerCycle::TimerCycle ()
Constructor.
Definition at line 42 of file TimerCycle.cc.
                            :
     Cycle()
     {
       setCycleValue(30.f); // default set to 30 seconds
     }
dqm4hep::core::TimerCycle::~TimerCycle ()
Destructor.
Definition at line 50 of file TimerCycle.cc.
     {
       /* nop */
     }
Member Function Documentation
bool dqm4hep::core::TimerCycle::isEndOfCycleReached () const virtual
Specific function to tell the application to know whether the cycle has reached the end.
Implements dqm4hep::core::Cycle.
Definition at line 57 of file TimerCycle.cc.
References dqm4hep::core::Cycle::getCycleValue(), and dqm4hep::core::Cycle::getStartTime().
Referenced by dqm4hep::core::StandaloneModuleApplication::run().
     {
       if( CoreTool::now() > this->getStartTime() + std::chrono::seconds(static_cast<unsigned int>(this->getCycleValue())) )
         return true;
       return false;
     }
void dqm4hep::core::TimerCycle::onCycleStarted () inline virtual
Specific call back function when a cycle is stopped.
Implements dqm4hep::core::Cycle.
Definition at line 54 of file TimerCycle.h.
 { /* nop */ }
void dqm4hep::core::TimerCycle::onCycleStopped () inline virtual
Specific call back function when a cycle is stopped.
Implements dqm4hep::core::Cycle.
Definition at line 55 of file TimerCycle.h.
 { /* nop */ }
void dqm4hep::core::TimerCycle::onEventProcessed (const Event * pEvent) inline virtual
Specific call back function when an event is processed, depends on cycle type.
Implements dqm4hep::core::Cycle.
Definition at line 56 of file TimerCycle.h.
 { /* nop */ }
The documentation for this class was generated from the following files:
TimerCycle.h
TimerCycle.cc