DQMOnline: dqm4hep::core::Module Class Reference
dqm4hep::core::Module Class Reference abstract
Module base class.
#include <Module.h>
Public Member Functions
Module ()
Constructor.
virtual ~Module ()
Destructor.
const std::string & getName () const
Get the module name.
const std::string & getDetectorName () const
Get the detector name associated to this module.
const Version & getVersion () const
Get the module version.
virtual StatusCode initModule ()=0
Initialize the module.
virtual StatusCode readSettings (const TiXmlHandle handle)=0
Read the input settings from a xml handle.
virtual StatusCode startOfCycle ()=0
Called at start of cycle.
virtual StatusCode endOfCycle ()=0
Called at end of cycle before publishing monitor elements.
virtual StatusCode endModule ()=0
End the module.
Protected Member Functions
void setDetectorName (const std::string &detectorName)
Set the detector name for this module.
void setName (const std::string &name)
Set the module name.
void setVersion (unsigned int major, unsigned int minor, unsigned int patch)
Set the module version.
Private Member Functions
ModuleApplication * getModuleApplication () const
Get the module application in which the module is registered.
void setModuleApplication (ModuleApplication *pModuleApplication)
Set the module application in which the module is registered.
Private Attributes
std::string m_name
The module name.
std::string m_detectorName
The detector name for this module.
Version m_version
The module version.
ModuleApplication * m_pModuleApplication
The monitor element manager.
Friends
class ModuleApi
class Archiver
class ModuleApplication
Detailed Description
Module base class.
Base class for monitor element booking modules. See daughter classes for specific implementations.
Author
R.Ete
Definition at line 52 of file Module.h.
Constructor & Destructor Documentation
dqm4hep::core::Module::Module ()
Constructor.
Definition at line 36 of file Module.cc.
                    :
         m_name( "" ),
         m_pModuleApplication(NULL)
     {
       /* nop */
     }
dqm4hep::core::Module::~Module () virtual
Destructor.
Definition at line 45 of file Module.cc.
     {
       /* nop */
     }
Member Function Documentation
virtual StatusCode dqm4hep::core::Module::endModule () pure virtual
End the module.
Called at termination of the process.
Referenced by dqm4hep::core::StandaloneModuleApplication::run().
virtual StatusCode dqm4hep::core::Module::endOfCycle () pure virtual
Called at end of cycle before publishing monitor elements.
User should not reset monitor elements in this method. Generally used to set the quality of monitor elements or set some of them to do not be published.
const std::string & dqm4hep::core::Module::getDetectorName () const
Get the detector name associated to this module.
Definition at line 66 of file Module.cc.
References m_detectorName.
     {
       return m_detectorName;
     }
ModuleApplication * dqm4hep::core::Module::getModuleApplication () const private
Get the module application in which the module is registered.
Definition at line 94 of file Module.cc.
References m_pModuleApplication.
Referenced by dqm4hep::core::ModuleApi::addQualityTest(), dqm4hep::core::ModuleApi::bookCharHistogram1D(), dqm4hep::core::ModuleApi::bookCharHistogram2D(), dqm4hep::core::ModuleApi::bookFloat(), dqm4hep::core::ModuleApi::bookInt(), dqm4hep::core::ModuleApi::bookIntHistogram1D(), dqm4hep::core::ModuleApi::bookIntHistogram2D(), dqm4hep::core::ModuleApi::bookIntHistogram3D(), dqm4hep::core::ModuleApi::bookMonitorElement(), dqm4hep::core::ModuleApi::bookObject(), dqm4hep::core::ModuleApi::bookProfile1D(), dqm4hep::core::ModuleApi::bookProfile2D(), dqm4hep::core::ModuleApi::bookRealHistogram1D(), dqm4hep::core::ModuleApi::bookRealHistogram2D(), dqm4hep::core::ModuleApi::bookRealHistogram3D(), dqm4hep::core::ModuleApi::bookShort(), dqm4hep::core::ModuleApi::bookShortHistogram1D(), dqm4hep::core::ModuleApi::bookShortHistogram2D(), dqm4hep::core::ModuleApi::bookString(), dqm4hep::core::ModuleApi::cd(), dqm4hep::core::ModuleApi::createQualityTest(), dqm4hep::core::ModuleApi::deleteMonitorElement(), dqm4hep::core::ModuleApi::dirExists(), dqm4hep::core::ModuleApi::getAllMonitorElements(), dqm4hep::core::ModuleApi::getMonitorElement(), dqm4hep::core::ModuleApi::goUp(), dqm4hep::core::ModuleApi::ls(), dqm4hep::core::ModuleApi::mkdir(), dqm4hep::core::ModuleApi::pwd(), dqm4hep::core::ModuleApi::registerQualityTestFactory(), dqm4hep::core::ModuleApi::resetMonitorElements(), dqm4hep::core::ModuleApi::rmdir(), dqm4hep::core::ModuleApi::runQualityTest(), dqm4hep::core::ModuleApi::runQualityTests(), and dqm4hep::core::ModuleApi::sendAlert().
     {
       return m_pModuleApplication;
     }
const std::string & dqm4hep::core::Module::getName () const
Get the module name.
Definition at line 59 of file Module.cc.
References m_name.
Referenced by dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::ModuleApi::bookCharHistogram1D(), dqm4hep::core::ModuleApi::bookCharHistogram2D(), dqm4hep::core::ModuleApi::bookFloat(), dqm4hep::core::ModuleApi::bookInt(), dqm4hep::core::ModuleApi::bookIntHistogram1D(), dqm4hep::core::ModuleApi::bookIntHistogram2D(), dqm4hep::core::ModuleApi::bookIntHistogram3D(), dqm4hep::core::ModuleApi::bookMonitorElement(), dqm4hep::core::ModuleApi::bookObject(), dqm4hep::core::ModuleApi::bookProfile1D(), dqm4hep::core::ModuleApi::bookProfile2D(), dqm4hep::core::ModuleApi::bookRealHistogram1D(), dqm4hep::core::ModuleApi::bookRealHistogram2D(), dqm4hep::core::ModuleApi::bookRealHistogram3D(), dqm4hep::core::ModuleApi::bookShort(), dqm4hep::core::ModuleApi::bookShortHistogram1D(), dqm4hep::core::ModuleApi::bookShortHistogram2D(), dqm4hep::core::ModuleApi::bookString(), dqm4hep::core::AnalysisModuleApplication::configureModule(), dqm4hep::core::ModuleApplication::getModuleName(), dqm4hep::core::StandaloneModuleApplication::readSettings(), dqm4hep::core::AnalysisModuleApplication::readSettings(), dqm4hep::core::AnalysisModuleApplication::run(), dqm4hep::core::MonitorElementSender::sendAvailableMonitorElementList(), and dqm4hep::core::MonitorElementSender::sendMonitorElements().
     {
       return m_name;
     }
const Version & dqm4hep::core::Module::getVersion () const
Get the module version.
Definition at line 80 of file Module.cc.
References m_version.
     {
       return m_version;
     }
virtual StatusCode dqm4hep::core::Module::initModule () pure virtual
Initialize the module.
It is generally in this method that monitor elements are booked.
virtual StatusCode dqm4hep::core::Module::readSettings (const TiXmlHandle handle) pure virtual
Read the input settings from a xml handle.
void dqm4hep::core::Module::setDetectorName (const std::string & detectorName) protected
Set the detector name for this module.
Definition at line 73 of file Module.cc.
References m_detectorName.
     {
       m_detectorName = detectorName;
     }
void dqm4hep::core::Module::setModuleApplication (ModuleApplication * pModuleApplication) private
Set the module application in which the module is registered.
Definition at line 101 of file Module.cc.
References m_pModuleApplication.
Referenced by dqm4hep::core::ModuleApplication::setModule().
     {
       m_pModuleApplication = pModuleApplication;
     }
void dqm4hep::core::Module::setName (const std::string & name) protected
Set the module name.
Definition at line 52 of file Module.cc.
References m_name.
Referenced by dqm4hep::core::ModuleApplication::setModule(), and dqm4hep::core::ModuleApplication::setModuleName().
     {
       m_name = name;
     }
void dqm4hep::core::Module::setVersion (unsigned int major, unsigned int minor, unsigned int patch) protected
Set the module version.
Definition at line 87 of file Module.cc.
References m_version.
     {
       m_version.set(major, minor, patch);
     }
virtual StatusCode dqm4hep::core::Module::startOfCycle () pure virtual
Called at start of cycle.
User can reset the monitor elements if needed in this method.
Friends And Related Function Documentation
friend class Archiver friend
Definition at line 55 of file Module.h.
friend class ModuleApi friend
Definition at line 54 of file Module.h.
friend class ModuleApplication friend
Definition at line 56 of file Module.h.
Member Data Documentation
std::string dqm4hep::core::Module::m_detectorName private
The detector name for this module.
Definition at line 132 of file Module.h.
Referenced by getDetectorName(), and setDetectorName().
std::string dqm4hep::core::Module::m_name private
The module name.
Definition at line 131 of file Module.h.
Referenced by getName(), and setName().
ModuleApplication* dqm4hep::core::Module::m_pModuleApplication private
The monitor element manager.
Definition at line 134 of file Module.h.
Referenced by getModuleApplication(), and setModuleApplication().
Version dqm4hep::core::Module::m_version private
The module version.
Definition at line 133 of file Module.h.
Referenced by getVersion(), and setVersion().
The documentation for this class was generated from the following files:
Module.h
Module.cc