DQMOnline: dqm4hep::core::AnalysisModule Class Reference
dqm4hep::core::AnalysisModule Class Reference abstract
AnalysisModule class.
#include <AnalysisModule.h>
Public Member Functions
AnalysisModule ()
Constructor.
virtual ~AnalysisModule ()
Destructor.
virtual StatusCode processEvent (const Event *const pEvent)=0
Process an event.
virtual StatusCode startOfRun (const Run *const pRun)=0
Called at start of run.
virtual StatusCode endOfRun (const Run *const pRun)=0
Called at end of run.
Public Member Functions inherited from dqm4hep::core::Module
Module ()
Constructor.
virtual ~Module ()
Destructor.
const std::string & getName () const
Get the module name.
const std::string & getDetectorName () const
Get the detector name associated to this module.
const Version & getVersion () const
Get the module version.
virtual StatusCode initModule ()=0
Initialize the module.
virtual StatusCode readSettings (const TiXmlHandle handle)=0
Read the input settings from a xml handle.
virtual StatusCode startOfCycle ()=0
Called at start of cycle.
virtual StatusCode endOfCycle ()=0
Called at end of cycle before publishing monitor elements.
virtual StatusCode endModule ()=0
End the module.
Friends
class AnalysisModuleApplication
Additional Inherited Members
Protected Member Functions inherited from dqm4hep::core::Module
void setDetectorName (const std::string &detectorName)
Set the detector name for this module.
void setName (const std::string &name)
Set the module name.
void setVersion (unsigned int major, unsigned int minor, unsigned int patch)
Set the module version.
Detailed Description
AnalysisModule class.
Definition at line 45 of file AnalysisModule.h.
Constructor & Destructor Documentation
dqm4hep::core::AnalysisModule::AnalysisModule () inline
Constructor.
Definition at line 76 of file AnalysisModule.h.
                                           :
         Module()
     {
     }
virtual dqm4hep::core::AnalysisModule::~AnalysisModule () inline virtual
Destructor.
Definition at line 56 of file AnalysisModule.h.
 {}
Member Function Documentation
virtual StatusCode dqm4hep::core::AnalysisModule::endOfRun (const Run *const pRun) pure virtual
Called at end of run.
Referenced by dqm4hep::core::AnalysisModuleApplication::run().
virtual StatusCode dqm4hep::core::AnalysisModule::processEvent (const Event *const pEvent) pure virtual
Process an event.
Fill histograms in this method
Referenced by dqm4hep::core::AnalysisModuleApplication::run().
virtual StatusCode dqm4hep::core::AnalysisModule::startOfRun (const Run *const pRun) pure virtual
Called at start of run.
Referenced by dqm4hep::core::AnalysisModuleApplication::run().
Friends And Related Function Documentation
friend class AnalysisModuleApplication friend
Definition at line 47 of file AnalysisModule.h.
The documentation for this class was generated from the following file:
AnalysisModule.h