DQMOnline: dqm4hep::core::MonitorElementClient Class Reference
dqm4hep::core::MonitorElementClient Class Reference
MonitorElementClient class.
#include <MonitorElementClient.h>
Public Member Functions
MonitorElementClient ()
Constructor.
~MonitorElementClient ()
Destructor.
StatusCode setCollectorName (const std::string &collectorName)
Set the collector name.
const std::string & getCollectorName () const
Get the collector name.
StatusCode connectToService ()
Connect the client to the service.
StatusCode disconnectFromService ()
Disconnect the client from the service.
bool isConnectedToService () const
Whether the client is connected to the service.
StatusCode queryCollectorInfo ()
Sent a request to the collector to get back the collector informations.
StatusCode queryAvailableMonitorElements (const MonitorElementListNameRequest &request)
Send a request to get back monitor element list name (small packet info)
StatusCode subscribe (const MonitorElementRequest &request)
Unsubscribe to monitor elements.
StatusCode unsubscribe (const MonitorElementRequest &request)
Subscribe to monitor elements.
StatusCode replaceSubscription (const MonitorElementRequest &request)
Unsubscribe to all monitor elements the client has already subscribed and subscribe to monitor elements.
StatusCode querySubscribedMonitorElements (const MonitorElementRequest &request)
Send a command to query the monitor element list.
StatusCode querySubscribedMonitorElements ()
Send a command to query the monitor element list that the client subscribed.
void setUpdateMode (bool updateMode)
Set the update mode.
bool getUpdateMode () const
Get the update mode.
bool isCollectorRunning () const
Whether the collector is running.
bool addListener (MonitorElementClientListener *pListener)
Add a listener to this client (observer pattern).
void removeListener (MonitorElementClientListener *pListener)
Remove a listener from this client.
Static Public Attributes
static const std::string m_emptyBufferStr = "EMPTY"
Private Member Functions
void handleMeCollectorInfoRpcInfo (DimRpcInfo *pRpcInfo)
Handle the collector info rpc callback.
void handleMeListNameRpcInfo (DimRpcInfo *pRpcInfo)
Handle the me name list rpc callback.
void infoHandler ()
Dim info handler.
void clearPublication (Publication &publication)
Deep clear of publication.
void configureInBuffer (char *pBuffer, uint32_t size)
Private Attributes
DimRpcInfo * m_pMeCollectorInfoRpcInfo
DimRpcInfo * m_pMeListNameRpcInfo
DimUpdatedInfo * m_pMeUpdateInfo
DimInfo * m_pCollectorStateInfo
DimInfo * m_pAvailableMeInfo
xdrstream::BufferDevice * m_pInBuffer
xdrstream::BufferDevice * m_pOutBuffer
std::string m_collectorName
bool m_isConnected
bool m_updateMode
bool m_isCollectorRunning
std::vector
< MonitorElementClientListener * > m_listeners
Friends
class MeCollectorInfoRpcInfo
class MeListNameRpcInfo
Detailed Description
MonitorElementClient class.
Definition at line 122 of file MonitorElementClient.h.
Constructor & Destructor Documentation
dqm4hep::core::MonitorElementClient::MonitorElementClient ()
Constructor.
Definition at line 78 of file MonitorElementClient.cc.
References m_pOutBuffer.
                                                :
         m_isConnected(false),
         m_pMeCollectorInfoRpcInfo(NULL),
         m_pMeListNameRpcInfo(NULL),
         m_pInBuffer(0),
         m_pOutBuffer(0),
         m_updateMode(false),
         m_isCollectorRunning(false)
     {
       m_pOutBuffer = new xdrstream::BufferDevice(1024*1024);
     }
dqm4hep::core::MonitorElementClient::~MonitorElementClient ()
Destructor.
Definition at line 92 of file MonitorElementClient.cc.
References disconnectFromService(), isConnectedToService(), m_pInBuffer, and m_pOutBuffer.
     {
       if(isConnectedToService())
         disconnectFromService();
       delete m_pOutBuffer;
       if( m_pInBuffer )
         delete m_pInBuffer;
     }
Member Function Documentation
bool dqm4hep::core::MonitorElementClient::addListener (MonitorElementClientListener * pListener)
Add a listener to this client (observer pattern).
Definition at line 349 of file MonitorElementClient.cc.
References m_listeners.
     {
       if(NULL == pListener)
         return false;
       std::vector<MonitorElementClientListener *>::iterator findIter = std::find( m_listeners.begin(), m_listeners.end(), pListener );
       // if already added, return ok
       if(m_listeners.end() != findIter)
         return true;
       m_listeners.push_back(pListener);
       return true;
     }
void dqm4hep::core::MonitorElementClient::clearPublication (Publication & publication) private
Deep clear of publication.
void dqm4hep::core::MonitorElementClient::configureInBuffer (char * pBuffer, uint32_t size) private
Definition at line 565 of file MonitorElementClient.cc.
References m_pInBuffer.
Referenced by handleMeCollectorInfoRpcInfo(), handleMeListNameRpcInfo(), and infoHandler().
     {
       if( ! m_pInBuffer )
         m_pInBuffer = new xdrstream::BufferDevice( pBuffer , bufferSize , false );
       else
         m_pInBuffer->setBuffer( pBuffer , bufferSize , false );
       m_pInBuffer->setOwner( false );
     }
StatusCode dqm4hep::core::MonitorElementClient::connectToService ()
Connect the client to the service.
Definition at line 127 of file MonitorElementClient.cc.
References getUpdateMode(), isConnectedToService(), m_collectorName, m_isConnected, m_listeners, m_pAvailableMeInfo, m_pCollectorStateInfo, m_pMeCollectorInfoRpcInfo, m_pMeListNameRpcInfo, m_pMeUpdateInfo, MeCollectorInfoRpcInfo, MeListNameRpcInfo, and setUpdateMode().
     {
       if(isConnectedToService())
         return STATUS_CODE_SUCCESS;
       std::string collectorName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/";
       std::stringstream ss;
       ss << collectorName << "COLLECTOR_INFO_RPC";
       m_pMeCollectorInfoRpcInfo = new MeCollectorInfoRpcInfo((char*) ss.str().c_str(), this);
       ss.str("");
       ss << collectorName << "MONITOR_ELEMENT_NAME_LIST_RPC";
       m_pMeListNameRpcInfo = new MeListNameRpcInfo((char*) ss.str().c_str(), this);
       ss.str("");
       ss << collectorName << "ME_UPDATE_SVC";
       m_pMeUpdateInfo = new DimUpdatedInfo( (char*) ss.str().c_str() , (void *) NULL , 0, this );
       ss.str("");
       ss << collectorName << "COLLECTOR_STATE_SVC";
       m_pCollectorStateInfo = new DimInfo( (char*) ss.str().c_str() , static_cast<int>(STOPPED_STATE) , this );
       ss.str("");
       ss << collectorName << "AVAILABLE_ME_SVC";
       m_pAvailableMeInfo = new DimUpdatedInfo( (char*) ss.str().c_str() , (void *) NULL , 0, this );
       m_isConnected = true;
       this->setUpdateMode(this->getUpdateMode());
       for(std::vector<MonitorElementClientListener *>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
           endIter != iter ; ++iter)
         (*iter)->onMonitorElementClientConnect(this);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementClient::disconnectFromService ()
Disconnect the client from the service.
Definition at line 167 of file MonitorElementClient.cc.
References isConnectedToService(), m_isConnected, m_listeners, m_pAvailableMeInfo, m_pCollectorStateInfo, m_pMeCollectorInfoRpcInfo, m_pMeListNameRpcInfo, and m_pMeUpdateInfo.
Referenced by ~MonitorElementClient().
     {
       if(!isConnectedToService())
         return STATUS_CODE_SUCCESS;
       delete m_pMeCollectorInfoRpcInfo; m_pMeCollectorInfoRpcInfo = NULL;
       delete m_pMeListNameRpcInfo; m_pMeListNameRpcInfo = NULL;
       delete m_pMeUpdateInfo; m_pMeUpdateInfo = NULL;
       delete m_pCollectorStateInfo; m_pCollectorStateInfo = NULL;
       delete m_pAvailableMeInfo; m_pAvailableMeInfo = NULL;
       m_isConnected = false;
       for(std::vector<MonitorElementClientListener *>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
           endIter != iter ; ++iter)
         (*iter)->onMonitorElementClientDisconnect(this);
       return STATUS_CODE_SUCCESS;
     }
const std::string & dqm4hep::core::MonitorElementClient::getCollectorName () const
Get the collector name.
Definition at line 120 of file MonitorElementClient.cc.
References m_collectorName.
     {
       return m_collectorName;
     }
bool dqm4hep::core::MonitorElementClient::getUpdateMode () const
Get the update mode.
Definition at line 342 of file MonitorElementClient.cc.
References m_updateMode.
Referenced by connectToService(), and infoHandler().
     {
       return m_updateMode;
     }
void dqm4hep::core::MonitorElementClient::handleMeCollectorInfoRpcInfo (DimRpcInfo * pRpcInfo) private
Handle the collector info rpc callback.
Definition at line 382 of file MonitorElementClient.cc.
References configureInBuffer(), m_listeners, and m_pInBuffer.
Referenced by dqm4hep::core::MeCollectorInfoRpcInfo::rpcInfoHandler().
     {
       try
       {
         if(m_listeners.empty())
           return;
         dqm_char *pBuffer = static_cast<dqm_char *>(pRpcInfo->getData());
         dqm_uint bufferSize = pRpcInfo->getSize();
         if(NULL == pBuffer || 0 == bufferSize)
           return;
         this->configureInBuffer( pBuffer , bufferSize );
         // deserialize and notify
         HostInfo collectorInfo;
         if( xdrstream::XDR_SUCCESS != StreamingHelper::read( m_pInBuffer , collectorInfo ) )
           return;
         for(std::vector<MonitorElementClientListener *>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
             endIter != iter ; ++iter)
           (*iter)->monitorElementCollectorInfoReceived(this, collectorInfo);
       }
       catch(StatusCodeException &exception)
       {
       }
       catch(...)
       {
       }
     }
void dqm4hep::core::MonitorElementClient::handleMeListNameRpcInfo (DimRpcInfo * pRpcInfo) private
Handle the me name list rpc callback.
Definition at line 417 of file MonitorElementClient.cc.
References configureInBuffer(), m_listeners, and m_pInBuffer.
Referenced by dqm4hep::core::MeListNameRpcInfo::rpcInfoHandler().
     {
       try
       {
         if(m_listeners.empty())
           return;
         dqm_char *pBuffer = static_cast<dqm_char*>(pRpcInfo->getData());
         dqm_uint bufferSize = pRpcInfo->getSize();
         if(NULL == pBuffer || 0 == bufferSize)
           throw StatusCodeException(STATUS_CODE_FAILURE);
         this->configureInBuffer( pBuffer , bufferSize );
         // deserialize and notify
         MonitorElementInfoList monitorElementInfoList;
         if( xdrstream::XDR_SUCCESS != StreamingHelper::read( m_pInBuffer , monitorElementInfoList ) )
           throw StatusCodeException(STATUS_CODE_FAILURE);
         for(std::vector<MonitorElementClientListener *>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
             endIter != iter ; ++iter)
           (*iter)->availableMonitorElementListReceived(this, monitorElementInfoList);
       }
       catch(StatusCodeException &exception)
       {
         LOG4CXX_ERROR( dqmMainLogger , "handleMeListNameRpcInfo(): Exception caught : " << exception.toString() );
       }
       catch(...)
       {
       }
     }
void dqm4hep::core::MonitorElementClient::infoHandler () private
Dim info handler.
Definition at line 453 of file MonitorElementClient.cc.
References configureInBuffer(), getUpdateMode(), isCollectorRunning(), m_isCollectorRunning, m_listeners, m_pAvailableMeInfo, m_pCollectorStateInfo, m_pInBuffer, m_pMeUpdateInfo, and setUpdateMode().
     {
       DimInfo *pInfo = getInfo();
       LOG4CXX_DEBUG( dqmMainLogger , "Received info : " << pInfo->getName() );
       if(pInfo == m_pMeUpdateInfo)
       {
         Publication monitorElementPublication;
         try
         {
           if(m_listeners.empty())
             return;
           dqm_char *pBuffer = static_cast<dqm_char *>(m_pMeUpdateInfo->getData());
           dqm_uint bufferSize = m_pMeUpdateInfo->getSize();
           if(NULL == pBuffer || 0 == bufferSize)
             throw StatusCodeException(STATUS_CODE_FAILURE);
           this->configureInBuffer( pBuffer , bufferSize );
           // deserialize and call the user call back function
           if( xdrstream::XDR_SUCCESS != StreamingHelper::read( m_pInBuffer , monitorElementPublication ) )
             throw StatusCodeException(STATUS_CODE_FAILURE);
           for(std::vector<MonitorElementClientListener *>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
               endIter != iter ; ++iter)
             (*iter)->monitorElementsReceived(this, monitorElementPublication);
         }
         catch(StatusCodeException &exception)
         {
           LOG4CXX_WARN( dqmMainLogger , "Couldn't receive monitor element publication: " << exception.toString() );
         }
         catch(...)
         {
         }
       }
       else if(pInfo == m_pCollectorStateInfo)
       {
         bool isCollectorRunning = static_cast<bool>(m_pCollectorStateInfo->getInt());
         LOG4CXX_INFO( dqmMainLogger , "Received collector state : " << isCollectorRunning );
         if(isCollectorRunning == m_isCollectorRunning)
           return;
         m_isCollectorRunning = isCollectorRunning;
         if(m_isCollectorRunning)
         {
           // send back update mode info to collector
           this->setUpdateMode(this->getUpdateMode());
           // notify server state !
           for(std::vector<MonitorElementClientListener *>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
               endIter != iter ; ++iter)
             (*iter)->onServerStartup(this);
         }
         else
         {
           // notify server state !
           for(std::vector<MonitorElementClientListener *>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
               endIter != iter ; ++iter)
             (*iter)->onServerShutdown(this);
         }
       }
       else if(pInfo == m_pAvailableMeInfo)
       {
         MonitorElementInfoList availableMeList;
         try
         {
           if(m_listeners.empty())
             return;
           dqm_char *pBuffer = static_cast<dqm_char *>(m_pAvailableMeInfo->getData());
           dqm_uint bufferSize = m_pAvailableMeInfo->getSize();
           if(NULL == pBuffer || 0 == bufferSize)
             throw StatusCodeException(STATUS_CODE_FAILURE);
           this->configureInBuffer( pBuffer , bufferSize );
           // deserialize and call the user call back function
           if( xdrstream::XDR_SUCCESS != StreamingHelper::read( m_pInBuffer , availableMeList ) )
             throw StatusCodeException(STATUS_CODE_FAILURE);
           for(std::vector<MonitorElementClientListener *>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
               endIter != iter ; ++iter)
             (*iter)->monitorElementsAvailable(this, availableMeList);
         }
         catch(StatusCodeException &exception)
         {
           LOG4CXX_WARN( dqmMainLogger , "Couldn't receive available me: " << exception.toString() );
         }
         catch(...)
         {
         }
       }
     }
bool dqm4hep::core::MonitorElementClient::isCollectorRunning () const
Whether the collector is running.
Definition at line 558 of file MonitorElementClient.cc.
References m_isCollectorRunning.
Referenced by infoHandler().
     {
       return m_isCollectorRunning;
     }
bool dqm4hep::core::MonitorElementClient::isConnectedToService () const
Whether the client is connected to the service.
Definition at line 189 of file MonitorElementClient.cc.
References m_isConnected.
Referenced by connectToService(), disconnectFromService(), queryAvailableMonitorElements(), queryCollectorInfo(), querySubscribedMonitorElements(), replaceSubscription(), setCollectorName(), setUpdateMode(), subscribe(), unsubscribe(), and ~MonitorElementClient().
     {
       return m_isConnected;
     }
StatusCode dqm4hep::core::MonitorElementClient::queryAvailableMonitorElements (const MonitorElementListNameRequest & request)
Send a request to get back monitor element list name (small packet info)
Definition at line 209 of file MonitorElementClient.cc.
References isConnectedToService(), m_pMeListNameRpcInfo, and m_pOutBuffer.
     {
       if(!isConnectedToService())
         return STATUS_CODE_NOT_ALLOWED;
       // serialize the list
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != StreamingHelper::write( m_pOutBuffer , request ) )
       {
         LOG4CXX_WARN( dqmMainLogger , "Couldn't write available list request" );
         return STATUS_CODE_FAILURE;
       }
       // send query
       m_pMeListNameRpcInfo->setData((void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition());
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementClient::queryCollectorInfo ()
Sent a request to the collector to get back the collector informations.
Definition at line 196 of file MonitorElementClient.cc.
References isConnectedToService(), and m_pMeCollectorInfoRpcInfo.
     {
       if(!isConnectedToService())
         return STATUS_CODE_NOT_ALLOWED;
       char buf[] = "\0";
       m_pMeCollectorInfoRpcInfo->setData((void *) &buf[0], 1);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementClient::querySubscribedMonitorElements (const MonitorElementRequest & request)
Send a command to query the monitor element list.
The element in the list are first subscribed. Then a query is sent to update only the element in the request
Definition at line 231 of file MonitorElementClient.cc.
References isConnectedToService(), m_collectorName, and m_pOutBuffer.
     {
       if(!isConnectedToService())
         return STATUS_CODE_NOT_ALLOWED;
       // serialize the request
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != StreamingHelper::write( m_pOutBuffer , request ) )
       {
         LOG4CXX_WARN( dqmMainLogger , "Couldn't write subscribed list request" );
         return STATUS_CODE_FAILURE;
       }
       // send the request
       std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/QUERY_ME_CMD";
       DimClient::sendCommandNB( commandName.c_str() , (void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition() );
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementClient::querySubscribedMonitorElements ()
Send a command to query the monitor element list that the client subscribed.
Definition at line 254 of file MonitorElementClient.cc.
     {
       // send empty request.
       MonitorElementRequest request;
       return this->querySubscribedMonitorElements(request);
     }
void dqm4hep::core::MonitorElementClient::removeListener (MonitorElementClientListener * pListener)
Remove a listener from this client.
Definition at line 367 of file MonitorElementClient.cc.
References m_listeners.
     {
       if(NULL == pListener)
         return;
       std::vector<MonitorElementClientListener *>::iterator findIter = std::find( m_listeners.begin(), m_listeners.end(), pListener );
       if(m_listeners.end() == findIter)
         return;
       m_listeners.erase(findIter);
     }
StatusCode dqm4hep::core::MonitorElementClient::replaceSubscription (const MonitorElementRequest & request)
Unsubscribe to all monitor elements the client has already subscribed and subscribe to monitor elements.
Definition at line 309 of file MonitorElementClient.cc.
References isConnectedToService(), m_collectorName, and m_pOutBuffer.
     {
       if(!isConnectedToService())
         return STATUS_CODE_NOT_ALLOWED;
       // serialize the request
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != StreamingHelper::write( m_pOutBuffer , request ) )
         return STATUS_CODE_FAILURE;
       // send the request
       std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/SET_SUBSCRIPTION_CMD";
       DimClient::sendCommandNB( commandName.c_str() , (void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition() );
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementClient::setCollectorName (const std::string & collectorName)
Set the collector name.
Can be done only if the client is not yet connected to collector service
Definition at line 105 of file MonitorElementClient.cc.
References isConnectedToService(), and m_collectorName.
     {
       if(collectorName.empty())
         return STATUS_CODE_INVALID_PARAMETER;
       if(isConnectedToService())
         return STATUS_CODE_NOT_ALLOWED;
       m_collectorName = collectorName;
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::MonitorElementClient::setUpdateMode (bool updateMode)
Set the update mode.
If set to true, subscribed monitor elements will be received when an update is performed on the collector server side
Definition at line 329 of file MonitorElementClient.cc.
References isConnectedToService(), m_collectorName, and m_updateMode.
Referenced by connectToService(), and infoHandler().
     {
       if(this->isConnectedToService())
       {
         std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/SET_UPDATE_MODE_CMD";
         DimClient::sendCommandNB( commandName.c_str() , static_cast<int>(updateMode) );
       }
       m_updateMode = updateMode;
     }
StatusCode dqm4hep::core::MonitorElementClient::subscribe (const MonitorElementRequest & request)
Unsubscribe to monitor elements.
Definition at line 263 of file MonitorElementClient.cc.
References isConnectedToService(), m_collectorName, and m_pOutBuffer.
     {
       if(!isConnectedToService())
         return STATUS_CODE_NOT_ALLOWED;
       // serialize the request
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != StreamingHelper::write( m_pOutBuffer , request ) )
       {
         LOG4CXX_WARN( dqmMainLogger , "Couldn't write me subscription request" );
         return STATUS_CODE_FAILURE;
       }
       // send the request
       std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/SUBSCRIBE_CMD";
       DimClient::sendCommandNB( commandName.c_str() , (void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition() );
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementClient::unsubscribe (const MonitorElementRequest & request)
Subscribe to monitor elements.
Definition at line 286 of file MonitorElementClient.cc.
References isConnectedToService(), m_collectorName, and m_pOutBuffer.
     {
       if(!isConnectedToService())
         return STATUS_CODE_NOT_ALLOWED;
       // serialize the request
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != StreamingHelper::write( m_pOutBuffer , request ) )
       {
         LOG4CXX_WARN( dqmMainLogger , "Couldn't write me un-subscription request" );
         return STATUS_CODE_FAILURE;
       }
       // send the request
       std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/UNSUBSCRIBE_CMD";
       DimClient::sendCommandNB( commandName.c_str() , (void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition() );
       return STATUS_CODE_SUCCESS;
     }
Friends And Related Function Documentation
friend class MeCollectorInfoRpcInfo friend
Definition at line 248 of file MonitorElementClient.h.
Referenced by connectToService().
friend class MeListNameRpcInfo friend
Definition at line 249 of file MonitorElementClient.h.
Referenced by connectToService().
Member Data Documentation
std::string dqm4hep::core::MonitorElementClient::m_collectorName private
Definition at line 240 of file MonitorElementClient.h.
Referenced by connectToService(), getCollectorName(), querySubscribedMonitorElements(), replaceSubscription(), setCollectorName(), setUpdateMode(), subscribe(), and unsubscribe().
const std::string dqm4hep::core::MonitorElementClient::m_emptyBufferStr = "EMPTY" static
Definition at line 207 of file MonitorElementClient.h.
bool dqm4hep::core::MonitorElementClient::m_isCollectorRunning private
Definition at line 243 of file MonitorElementClient.h.
Referenced by infoHandler(), and isCollectorRunning().
bool dqm4hep::core::MonitorElementClient::m_isConnected private
Definition at line 241 of file MonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and isConnectedToService().
std::vector<MonitorElementClientListener *> dqm4hep::core::MonitorElementClient::m_listeners private
Definition at line 246 of file MonitorElementClient.h.
Referenced by addListener(), connectToService(), disconnectFromService(), handleMeCollectorInfoRpcInfo(), handleMeListNameRpcInfo(), infoHandler(), and removeListener().
DimInfo* dqm4hep::core::MonitorElementClient::m_pAvailableMeInfo private
Definition at line 235 of file MonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
DimInfo* dqm4hep::core::MonitorElementClient::m_pCollectorStateInfo private
Definition at line 234 of file MonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
xdrstream::BufferDevice* dqm4hep::core::MonitorElementClient::m_pInBuffer private
Definition at line 237 of file MonitorElementClient.h.
Referenced by configureInBuffer(), handleMeCollectorInfoRpcInfo(), handleMeListNameRpcInfo(), infoHandler(), and ~MonitorElementClient().
DimRpcInfo* dqm4hep::core::MonitorElementClient::m_pMeCollectorInfoRpcInfo private
Definition at line 231 of file MonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and queryCollectorInfo().
DimRpcInfo* dqm4hep::core::MonitorElementClient::m_pMeListNameRpcInfo private
Definition at line 232 of file MonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and queryAvailableMonitorElements().
DimUpdatedInfo* dqm4hep::core::MonitorElementClient::m_pMeUpdateInfo private
Definition at line 233 of file MonitorElementClient.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
xdrstream::BufferDevice* dqm4hep::core::MonitorElementClient::m_pOutBuffer private
Definition at line 238 of file MonitorElementClient.h.
Referenced by MonitorElementClient(), queryAvailableMonitorElements(), querySubscribedMonitorElements(), replaceSubscription(), subscribe(), unsubscribe(), and ~MonitorElementClient().
bool dqm4hep::core::MonitorElementClient::m_updateMode private
Definition at line 242 of file MonitorElementClient.h.
Referenced by getUpdateMode(), and setUpdateMode().
The documentation for this class was generated from the following files:
MonitorElementClient.h
MonitorElementClient.cc