DQMOnline: dqm4hep::core::DimEventClient Class Reference
dqm4hep::core::DimEventClient Class Reference
DimEventClient class.
#include <DimEventClient.h>
Public Member Functions
DimEventClient ()
Constructor.
~DimEventClient ()
Destructor.
StatusCode performServiceConnection ()
Workhorse of the service connection.
StatusCode performServiceDisconnection ()
Workhorse of the service connection.
bool isConnectedToService () const
Whether the client is connected to the collector (server)
StatusCode sendEvent (const Event *pEvent)
Send an event to the collector (server).
StatusCode queryEvent (Event *&pEvent, int timeout)
Query an event to the collector (server) with a timeout and handle it without pushing it into the internal queue.
StatusCode queryEvent ()
Query an event to the collector.
void setUpdateMode (bool updateMode)
Set the update mode.
bool getUpdateMode () const
Whether the update mode is set.
Public Member Functions inherited from dqm4hep::core::EventClient
EventClient ()
Constructor.
virtual ~EventClient ()
Destructor.
virtual void setCollectorName (const std::string &collectorName)
Set the collector to connect to.
const std::string & getCollectorName () const
Get the collector name.
virtual void setEventStreamer (EventStreamer *pEventStreamer, bool owner=true)
Set the streamer that will stream in/out the sent/received event(s).
EventStreamer * getEventStreamer () const
Get the event streamer.
virtual void setMaximumQueueSize (unsigned int queueSize)
Set the queue size that stores the received events.
virtual unsigned int getMaximumQueueSize () const
Get the maximum number of events that the client can store in its event queue.
virtual void clearQueue ()
Clear the event queue.
const std::string & getSubEventIdentifier () const
Get the sub event identifier.
void takeEvent (EventPtr &event)
Take an event from the event queue (pop front) and return the pointer to the caller.
void addListener (EventClientListener *pListener)
Add a listener to this event client.
void removeListener (EventClientListener *pListener)
Remove a listener from this event client.
StatusCode connectToService ()
Connect to the collector service (server)
StatusCode disconnectFromService ()
Disconnect the client from the collector (server)
Private Member Functions
void infoHandler ()
Dim info handler.
StatusCode eventReception (dqm_char *pBuffer, dqm_uint bufferSize)
Handle the event reception as a buffer an its buffer size.
void setSubEventIdentifier (const std::string &identifier)
Set the sub event identifier.
StatusCode readSettings (const TiXmlHandle &xmlHandle)
Read settings from the xml handle.
Private Attributes
bool m_isConnected
DimEventRpcInfo * m_pDimEventRpcInfo
DimUpdatedInfo * m_pClientIdInfo
to receive the client id stored on server
DimUpdatedInfo * m_pServerStateInfo
Server state. 0 for stopped : 1 for running.
DimUpdatedInfo * m_pEventUpdateInfo
For event reception.
int m_serverClientId
bool m_updateMode
xdrstream::BufferDevice * m_pWriteBuffer
xdrstream::BufferDevice * m_pReadBuffer
pthread_mutex_t m_mutex
Friends
class DimEventRpcInfo
Additional Inherited Members
Protected Member Functions inherited from dqm4hep::core::EventClient
void pushEvent (Event *pEvent)
Push a new event in the event queue.
Detailed Description
DimEventClient class.
Definition at line 73 of file DimEventClient.h.
Constructor & Destructor Documentation
dqm4hep::core::DimEventClient::DimEventClient ()
Constructor.
Definition at line 59 of file DimEventClient.cc.
                                    :
     m_isConnected(false),
     m_pDimEventRpcInfo(NULL),
     m_updateMode(false),
     m_serverClientId(0),
     m_pReadBuffer(0),
     m_pWriteBuffer(0)
     {
       pthread_mutex_init(&m_mutex, NULL);
       m_pWriteBuffer = new xdrstream::BufferDevice(5*1024*1024);
     }
dqm4hep::core::DimEventClient::~DimEventClient ()
Destructor.
Definition at line 74 of file DimEventClient.cc.
References dqm4hep::core::EventClient::disconnectFromService(), isConnectedToService(), m_mutex, m_pReadBuffer, and m_pWriteBuffer.
     {
       if( this->isConnectedToService() )
         this->disconnectFromService();
       pthread_mutex_destroy(&m_mutex);
       if(m_pReadBuffer)
         delete m_pReadBuffer;
       if(m_pWriteBuffer)
         delete m_pWriteBuffer;
     }
Member Function Documentation
StatusCode dqm4hep::core::DimEventClient::eventReception (dqm_char * pBuffer, dqm_uint bufferSize) private
Handle the event reception as a buffer an its buffer size.
Definition at line 353 of file DimEventClient.cc.
References dqm4hep::core::EventClient::getEventStreamer(), m_mutex, m_pReadBuffer, and dqm4hep::core::EventClient::pushEvent().
Referenced by infoHandler(), and dqm4hep::core::DimEventRpcInfo::rpcInfoHandler().
     {
       if(NULL == pBuffer || 0 == bufferSize)
         return STATUS_CODE_INVALID_PARAMETER;
       if(strcmp(pBuffer, "EMPTY") == 0)
         return STATUS_CODE_SUCCESS;
       // set buffer
       scoped_lock( & this->m_mutex);
       if( ! m_pReadBuffer )
         m_pReadBuffer = new xdrstream::BufferDevice(pBuffer, bufferSize, false);
       else
         m_pReadBuffer->setBuffer(pBuffer, bufferSize, false);
       m_pReadBuffer->setOwner(false);
       // read event
       Event *pEvent = NULL;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getEventStreamer()->read(pEvent, m_pReadBuffer));
       pEvent->setEventSize(bufferSize);
       LOG4CXX_DEBUG( dqmMainLogger , "DimEventClient : Event received !" );
       // add it to event queue
       this->pushEvent(pEvent);
       return STATUS_CODE_SUCCESS;
     }
bool dqm4hep::core::DimEventClient::getUpdateMode () const virtual
Whether the update mode is set.
Implements dqm4hep::core::EventClient.
Definition at line 270 of file DimEventClient.cc.
References m_updateMode.
Referenced by readSettings().
     {
       return m_updateMode;
     }
void dqm4hep::core::DimEventClient::infoHandler () private
Dim info handler.
Definition at line 277 of file DimEventClient.cc.
References eventReception(), dqm4hep::core::EventClient::getCollectorName(), dqm4hep::core::EventClient::getSubEventIdentifier(), m_pClientIdInfo, m_pEventUpdateInfo, m_pServerStateInfo, m_serverClientId, and m_updateMode.
     {
       DimInfo *pInfo = getInfo();
       if(!pInfo)
         return;
       // client has just been registered
       if(pInfo == m_pClientIdInfo)
       {
         int clientId = pInfo->getInt();
         LOG4CXX_INFO( dqmMainLogger , "Client id on server : " << clientId );
         if(clientId <= 0)
           return;
         m_serverClientId = clientId;
         std::string subEventIdentifierCommandName = "DQM4HEP/EventCollector/" + this->getCollectorName() + "/SUB_EVENT_IDENTIFIER";
         std::string updateModeCommandName = "DQM4HEP/EventCollector/" + this->getCollectorName() + "/UPDATE_MODE";
         // send to server the client parameters
         DimClient::sendCommandNB((char*) updateModeCommandName.c_str(), static_cast<int>(m_updateMode));
         DimClient::sendCommandNB((char*) subEventIdentifierCommandName.c_str(), (char *) this->getSubEventIdentifier().c_str());
         return;
       }
       if(pInfo == m_pServerStateInfo)
       {
         int serverRunning = pInfo->getInt();
         // server is running
         if(serverRunning > 0)
         {
           // client is already registered, so nothing to do ...
           if(m_serverClientId > 0)
             return;
           // client is not registered yet, we need to do it !
           else
           {
             LOG4CXX_INFO( dqmMainLogger , "Registering client into event collector server application !" );
             DimClient::sendCommandNB(("DQM4HEP/EventCollector/" + this->getCollectorName() + "/CLIENT_REGISTRATION").c_str(), 1);
             return;
           }
         }
         // server is shutting down.
         // client is no longer connected and client id is no longer valid.
         else if(m_serverClientId > 0)
         {
           m_serverClientId = 0;
           LOG4CXX_INFO( dqmMainLogger , "Unregistered from event collector server application !" );
           return;
         }
       }
       if(pInfo == m_pEventUpdateInfo)
       {
         if(m_serverClientId == 0)
           return;
         char *pBuffer = (char*) pInfo->getData();
         unsigned int bufferSize = pInfo->getSize();
         if(NULL == pBuffer || 0 == bufferSize)
           return;
         this->eventReception(pBuffer, bufferSize);
         return;
       }
     }
bool dqm4hep::core::DimEventClient::isConnectedToService () const virtual
Whether the client is connected to the collector (server)
Implements dqm4hep::core::EventClient.
Definition at line 147 of file DimEventClient.cc.
References m_isConnected.
Referenced by performServiceConnection(), performServiceDisconnection(), queryEvent(), readSettings(), setSubEventIdentifier(), setUpdateMode(), and ~DimEventClient().
     {
       return m_isConnected;
     }
StatusCode dqm4hep::core::DimEventClient::performServiceConnection () virtual
Workhorse of the service connection.
Implements dqm4hep::core::EventClient.
Definition at line 90 of file DimEventClient.cc.
References DimEventRpcInfo, dqm4hep::core::EventClient::getCollectorName(), isConnectedToService(), m_isConnected, m_pClientIdInfo, m_pDimEventRpcInfo, m_pEventUpdateInfo, and m_pServerStateInfo.
     {
       if(isConnectedToService())
         return STATUS_CODE_SUCCESS;
       DimClient::setExitHandler( ("DQM4HEP/EventCollector/" + this->getCollectorName() ).c_str() );
       m_pDimEventRpcInfo = new DimEventRpcInfo(this);
       m_pClientIdInfo    = new DimUpdatedInfo(("DQM4HEP/EventCollector/" + this->getCollectorName() + "/CLIENT_REGISTERED").c_str(), static_cast<int>(0), this);
       m_pServerStateInfo = new DimUpdatedInfo(("DQM4HEP/EventCollector/" + this->getCollectorName() + "/SERVER_STATE").c_str(), static_cast<int>(0), this);
       m_pEventUpdateInfo = new DimUpdatedInfo(("DQM4HEP/EventCollector/" + this->getCollectorName() + "/EVENT_RAW_UPDATE").c_str(), (void*) NULL, 0, this);
       m_isConnected = true;
       DimCurrentInfo serverStateInfo(("DQM4HEP/EventCollector/" + this->getCollectorName() + "/SERVER_STATE").c_str(), static_cast<int>(0));
       int serverRunning = serverStateInfo.getInt();
       if(!serverRunning)
       {
         LOG4CXX_WARN( dqmMainLogger , "Server collector application not running yet" );
         return STATUS_CODE_SUCCESS;
       }
       // send command to register the client on the server
       // the server is expected to update m_pClientIdInfo info with the client id
       LOG4CXX_INFO( dqmMainLogger , "Registering client into server collector application !" );
       DimClient::sendCommandNB(("DQM4HEP/EventCollector/" + this->getCollectorName() + "/CLIENT_REGISTRATION").c_str(), 1);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimEventClient::performServiceDisconnection () virtual
Workhorse of the service connection.
Implements dqm4hep::core::EventClient.
Definition at line 124 of file DimEventClient.cc.
References dqm4hep::core::EventClient::getCollectorName(), isConnectedToService(), m_isConnected, m_pClientIdInfo, m_pDimEventRpcInfo, m_pEventUpdateInfo, m_pServerStateInfo, and m_serverClientId.
     {
       if(!isConnectedToService())
         return STATUS_CODE_SUCCESS;
       delete m_pDimEventRpcInfo;
       delete m_pClientIdInfo;
       delete m_pServerStateInfo;
       delete m_pEventUpdateInfo;
       m_isConnected = false;
       // un-register client on the server
       if(m_serverClientId > 0)
       {
         DimClient::sendCommandNB(("DQM4HEP/EventCollector/" + this->getCollectorName() + "/CLIENT_REGISTRATION").c_str(), 0);
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimEventClient::queryEvent (Event *& pEvent, int timeout) virtual
Query an event to the collector (server) with a timeout and handle it without pushing it into the internal queue.
Implements dqm4hep::core::EventClient.
Definition at line 194 of file DimEventClient.cc.
References dqm4hep::core::EventClient::getCollectorName(), dqm4hep::core::EventClient::getEventStreamer(), dqm4hep::core::EventClient::getSubEventIdentifier(), isConnectedToService(), m_mutex, and m_pReadBuffer.
     {
       scoped_lock( & this->m_mutex);
       if( ! this->isConnectedToService() )
         return STATUS_CODE_NOT_INITIALIZED;
       if( NULL == this->getEventStreamer() )
         return STATUS_CODE_NOT_INITIALIZED;
       // check for valid parameters
       if(timeout <= 0)
         return STATUS_CODE_INVALID_PARAMETER;
       // rpc service name
       std::string serviceName = "DQM4HEP/EventCollector/" + this->getCollectorName() + "/EVENT_RAW_REQUEST";
       pEvent = NULL;
       // declare the rpc service info
       DimRpcInfo eventDimRpcInfo((char*) serviceName.c_str(), timeout, (void*) NULL, 0);
       // send the query
       eventDimRpcInfo.setData((char*) this->getSubEventIdentifier().c_str());
       // receive the query result
       char *pEventRawBuffer = static_cast<char*>(eventDimRpcInfo.getData());
       int bufferSize = eventDimRpcInfo.getSize();
       // check for message validity
       if(NULL == pEventRawBuffer || 0 == bufferSize)
         return STATUS_CODE_FAILURE;
       if( ! m_pReadBuffer )
         m_pReadBuffer = new xdrstream::BufferDevice(pEventRawBuffer, bufferSize, false);
       else
         m_pReadBuffer->setBuffer(pEventRawBuffer, bufferSize, false);
       m_pReadBuffer->setOwner(false);
       // deserialize the event raw buffer
       return this->getEventStreamer()->read(pEvent, m_pReadBuffer);
     }
StatusCode dqm4hep::core::DimEventClient::queryEvent () virtual
Query an event to the collector.
A command is send to the collector in order to send back an event. This method does not wait for the event reception.
To query a single event that is directly handled by the caller, use queryEvent(evt, timeout).
The received event is pushed in an internal event queue.
Implements dqm4hep::core::EventClient.
Definition at line 239 of file DimEventClient.cc.
References dqm4hep::core::EventClient::getEventStreamer(), dqm4hep::core::EventClient::getSubEventIdentifier(), isConnectedToService(), m_mutex, and m_pDimEventRpcInfo.
     {
       scoped_lock( & this->m_mutex);
       if( ! this->isConnectedToService() )
         return STATUS_CODE_NOT_INITIALIZED;
       if( NULL == this->getEventStreamer() )
         return STATUS_CODE_NOT_INITIALIZED;
       // send the query
       m_pDimEventRpcInfo->setData((char*) this->getSubEventIdentifier().c_str());
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimEventClient::readSettings (const TiXmlHandle & xmlHandle) private virtual
Read settings from the xml handle.
Implements dqm4hep::core::EventClient.
Definition at line 386 of file DimEventClient.cc.
References dqm4hep::core::EventClient::connectToService(), dqm4hep::core::EventClient::disconnectFromService(), dqm4hep::core::EventClient::getCollectorName(), dqm4hep::core::EventClient::getMaximumQueueSize(), dqm4hep::core::EventClient::getSubEventIdentifier(), getUpdateMode(), isConnectedToService(), dqm4hep::core::EventClient::setCollectorName(), dqm4hep::core::EventClient::setEventStreamer(), dqm4hep::core::EventClient::setMaximumQueueSize(), setSubEventIdentifier(), and setUpdateMode().
     {
       bool reconnect = this->isConnectedToService();
       // first disconnect
       if( reconnect )
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->disconnectFromService());
       // read all xml values first
       std::string collectorName = this->getCollectorName();
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameterValue(xmlHandle,
           "collectorName", collectorName));
       std::string subEventIdentifier = this->getSubEventIdentifier();
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameterValue(xmlHandle,
           "subEventIdentifier", subEventIdentifier));
       unsigned int maxEventQueueSize = this->getMaximumQueueSize();
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameterValue(xmlHandle,
           "maxQueueSize", maxEventQueueSize));
       bool updateMode = this->getUpdateMode();
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameterValue(xmlHandle,
           "updateMode", updateMode));
       std::string eventStreamerName;
       RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::readParameterValue(xmlHandle,
           "streamerName", eventStreamerName));
       // configure the client
       // connection to service will come afterward
       this->setCollectorName(collectorName);
       this->setSubEventIdentifier(subEventIdentifier);
       this->setMaximumQueueSize(maxEventQueueSize);
       this->setUpdateMode(updateMode);
       if( ! eventStreamerName.empty() )
       {
         EventStreamer *pEventStreamer = PluginManager::instance()->createPluginClass<EventStreamer>(eventStreamerName);
         if( ! pEventStreamer )
           return STATUS_CODE_FAILURE;
         this->setEventStreamer(pEventStreamer, true);
       }
       // reconnect only if connected before configuration
       if( reconnect )
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->connectToService());
       LOG4CXX_INFO( dqmMainLogger , "Collector name : " << collectorName );
       LOG4CXX_INFO( dqmMainLogger , "Sub event identifier : " << subEventIdentifier );
       LOG4CXX_INFO( dqmMainLogger , "Streamer name : " << eventStreamerName );
       LOG4CXX_INFO( dqmMainLogger , "Update mode : " << updateMode );
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimEventClient::sendEvent (const Event * pEvent) virtual
Send an event to the collector (server).
Possible only if a connection has been created (connectToService()) and an event streamer set.
Implements dqm4hep::core::EventClient.
Definition at line 154 of file DimEventClient.cc.
References dqm4hep::core::EventClient::getCollectorName(), dqm4hep::core::EventClient::getEventStreamer(), m_mutex, and m_pWriteBuffer.
     {
       scoped_lock( & this->m_mutex);
       if( NULL == this->getEventStreamer() )
         return STATUS_CODE_NOT_INITIALIZED;
       if(NULL == pEvent)
         return STATUS_CODE_INVALID_PARAMETER;
       m_pWriteBuffer->reset();
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getEventStreamer()->write(pEvent, m_pWriteBuffer));
       char *pBuffer = m_pWriteBuffer->getBuffer();
       unsigned int bufferSize = m_pWriteBuffer->getPosition();
       if(NULL == pBuffer || 0 == bufferSize)
         return STATUS_CODE_FAILURE;
       std::string commandName = "DQM4HEP/EventCollector/" + this->getCollectorName() + "/COLLECT_RAW_EVENT";
       DimClient::sendCommandNB((char*) commandName.c_str(), (void *) pBuffer, bufferSize);
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::DimEventClient::setSubEventIdentifier (const std::string & identifier) private virtual
Set the sub event identifier.
This string is sent while querying events. The received event will be a sub event matching this identifier
The event sub identifier is sent the the collector is the client is connected to the service
Reimplemented from dqm4hep::core::EventClient.
Definition at line 181 of file DimEventClient.cc.
References dqm4hep::core::EventClient::getCollectorName(), isConnectedToService(), and dqm4hep::core::EventClient::setSubEventIdentifier().
Referenced by readSettings().
     {
       EventClient::setSubEventIdentifier(identifier);
       if( ! this->isConnectedToService() )
         return;
       std::string subEventIdentifierCommandName = "DQM4HEP/EventCollector/" + this->getCollectorName() + "/SUB_EVENT_IDENTIFIER";
       DimClient::sendCommandNB((char*) subEventIdentifierCommandName.c_str(), (char *) identifier.c_str());
     }
void dqm4hep::core::DimEventClient::setUpdateMode (bool updateMode) virtual
Set the update mode.
If the update mode is set to true, a command is sent to the server in order to update the client as soon as an event is received in the collector server.
Implements dqm4hep::core::EventClient.
Definition at line 257 of file DimEventClient.cc.
References dqm4hep::core::EventClient::getCollectorName(), isConnectedToService(), and m_updateMode.
Referenced by readSettings().
     {
       m_updateMode = updateMode;
       if( ! this->isConnectedToService() )
         return;
       // send command to server
       DimClient::sendCommandNB((char*) (std::string("DQM4HEP/EventCollector/") + this->getCollectorName() + "/UPDATE_MODE" ).c_str(), static_cast<int>(m_updateMode));
     }
Friends And Related Function Documentation
friend class DimEventRpcInfo friend
Definition at line 75 of file DimEventClient.h.
Referenced by performServiceConnection().
Member Data Documentation
bool dqm4hep::core::DimEventClient::m_isConnected private
Definition at line 155 of file DimEventClient.h.
Referenced by isConnectedToService(), performServiceConnection(), and performServiceDisconnection().
pthread_mutex_t dqm4hep::core::DimEventClient::m_mutex mutable private
Definition at line 166 of file DimEventClient.h.
Referenced by eventReception(), queryEvent(), sendEvent(), and ~DimEventClient().
DimUpdatedInfo* dqm4hep::core::DimEventClient::m_pClientIdInfo private
to receive the client id stored on server
Definition at line 157 of file DimEventClient.h.
Referenced by infoHandler(), performServiceConnection(), and performServiceDisconnection().
DimEventRpcInfo* dqm4hep::core::DimEventClient::m_pDimEventRpcInfo private
Definition at line 156 of file DimEventClient.h.
Referenced by performServiceConnection(), performServiceDisconnection(), and queryEvent().
DimUpdatedInfo* dqm4hep::core::DimEventClient::m_pEventUpdateInfo private
For event reception.
Definition at line 159 of file DimEventClient.h.
Referenced by infoHandler(), performServiceConnection(), and performServiceDisconnection().
xdrstream::BufferDevice* dqm4hep::core::DimEventClient::m_pReadBuffer private
Definition at line 165 of file DimEventClient.h.
Referenced by eventReception(), queryEvent(), and ~DimEventClient().
DimUpdatedInfo* dqm4hep::core::DimEventClient::m_pServerStateInfo private
Server state. 0 for stopped : 1 for running.
Definition at line 158 of file DimEventClient.h.
Referenced by infoHandler(), performServiceConnection(), and performServiceDisconnection().
xdrstream::BufferDevice* dqm4hep::core::DimEventClient::m_pWriteBuffer private
Definition at line 164 of file DimEventClient.h.
Referenced by sendEvent(), and ~DimEventClient().
int dqm4hep::core::DimEventClient::m_serverClientId private
Definition at line 161 of file DimEventClient.h.
Referenced by infoHandler(), and performServiceDisconnection().
bool dqm4hep::core::DimEventClient::m_updateMode private
Definition at line 162 of file DimEventClient.h.
Referenced by getUpdateMode(), infoHandler(), and setUpdateMode().
The documentation for this class was generated from the following files:
DimEventClient.h
DimEventClient.cc