DQMOnline: dqm4hep::core::DimAlertInterface Class Reference
dqm4hep::core::DimAlertInterface Class Reference
#include <AlertSystem.h>
Public Member Functions
DimAlertInterface ()
virtual ~DimAlertInterface ()
virtual void newEmitterRegistered (const std::string &emitter)
virtual void emitterUnregistered (const std::string &emitter)
void setUpdateTime (int updateTime)
StatusCode connectToService ()
StatusCode disconnectFromService ()
bool isConnected () const
Public Member Functions inherited from dqm4hep::core::AlertHandler
virtual ~AlertHandler ()
void addListener (AlertListener *pListener)
void removeListener (AlertListener *pListener)
Private Types
typedef std::map< std::string,
DimInfo * > EmitterInfoMap
Private Member Functions
void infoHandler ()
void timerHandler ()
StringVector browse ()
void configureInBuffer (char *pBuffer, xdrstream::xdr_size_t bufferSize)
Private Attributes
EmitterInfoMap m_emitterInfoMap
xdrstream::BufferDevice * m_pBuffer
int m_updateTime
bool m_isConnected
Additional Inherited Members
Protected Member Functions inherited from dqm4hep::core::AlertHandler
void notifyListeners (AlertPtr alert)
Detailed Description
Definition at line 292 of file AlertSystem.h.
Member Typedef Documentation
typedef std::map<std::string, DimInfo *> dqm4hep::core::DimAlertInterface::EmitterInfoMap private
Definition at line 340 of file AlertSystem.h.
Constructor & Destructor Documentation
dqm4hep::core::DimAlertInterface::DimAlertInterface ()
Definition at line 414 of file AlertSystem.cc.
                                          :
         m_updateTime(5),
         m_isConnected(false),
         m_pBuffer(NULL)
     {
       /* nop */
     }
dqm4hep::core::DimAlertInterface::~DimAlertInterface () virtual
Definition at line 424 of file AlertSystem.cc.
References disconnectFromService(), and m_pBuffer.
     {
       if( m_pBuffer )
         delete m_pBuffer;
       this->disconnectFromService();
     }
Member Function Documentation
StringVector dqm4hep::core::DimAlertInterface::browse () private
Definition at line 592 of file AlertSystem.cc.
Referenced by connectToService(), and timerHandler().
     {
       StringVector emitters;
       DimBrowser browser;
       int nServices = browser.getServices("DQM4HEP/ALERT/*");
       if( 0 == nServices )
         return emitters;
       char *pServiceName, *pFormat;
       int serviceType;
       while( 1 )
       {
         serviceType = browser.getNextService(pServiceName, pFormat);
         if( 0 == serviceType )
           break;
         if( DimSERVICE != serviceType )
           continue;
         std::string emitter = std::string(pServiceName).substr( std::string("DQM4HEP/ALERT/").size() );
         LOG4CXX_DEBUG( dqmMainLogger, "Found emitter : " << emitter );
         emitters.push_back(emitter);
       }
       return emitters;
     }
void dqm4hep::core::DimAlertInterface::configureInBuffer (char * pBuffer, xdrstream::xdr_size_t bufferSize) private
Definition at line 627 of file AlertSystem.cc.
References m_pBuffer.
     {
       if(NULL == m_pBuffer)
         m_pBuffer = new xdrstream::BufferDevice(pBuffer, bufferSize, false);
       else
         m_pBuffer->setBuffer(pBuffer, bufferSize, false);
       m_pBuffer->setOwner(false);
     }
StatusCode dqm4hep::core::DimAlertInterface::connectToService () virtual
Implements dqm4hep::core::AlertHandler.
Definition at line 461 of file AlertSystem.cc.
References browse(), isConnected(), m_emitterInfoMap, m_isConnected, and m_updateTime.
     {
       if( this->isConnected() )
         return STATUS_CODE_SUCCESS;
       StringVector emitters = this->browse();
       for(StringVector::iterator iter = emitters.begin(), endIter = emitters.end() ;
           endIter != iter ; ++iter)
       {
         std::string infoName = "DQM4HEP/ALERT/" + *iter;
         DimInfo *pAlertInfo = new DimUpdatedInfo( infoName.c_str() , (void *) NULL, 0 , this );
         m_emitterInfoMap[*iter] = pAlertInfo;
       }
       m_isConnected = true;
       this->start(m_updateTime);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimAlertInterface::disconnectFromService () virtual
Implements dqm4hep::core::AlertHandler.
Definition at line 486 of file AlertSystem.cc.
References isConnected(), m_emitterInfoMap, and m_isConnected.
Referenced by ~DimAlertInterface().
     {
       if( ! this->isConnected() )
         return STATUS_CODE_SUCCESS;
       this->stop();
       for(EmitterInfoMap::iterator iter = m_emitterInfoMap.begin(), endIter = m_emitterInfoMap.end() ;
           endIter != iter ; ++iter)
       {
         delete iter->second;
       }
       m_emitterInfoMap.clear();
       m_isConnected = false;
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::DimAlertInterface::emitterUnregistered (const std::string & emitter) virtual
Definition at line 441 of file AlertSystem.cc.
Referenced by timerHandler().
     {
       /* nop */
     }
void dqm4hep::core::DimAlertInterface::infoHandler () private
Definition at line 514 of file AlertSystem.cc.
References m_pBuffer, and dqm4hep::core::AlertHandler::notifyListeners().
     {
       DimInfo *pInfo = getInfo();
       if( ! pInfo )
         return;
       char *pBuffer = static_cast<char *>(pInfo->getData());
       xdrstream::xdr_size_t bufferSize = pInfo->getSize();
       if( NULL == pBuffer || 0 == bufferSize )
         return;
       AlertPtr alert(new Alert());
       if( ! XDR_TESTBIT( alert->stream( xdrstream::XDR_READ_STREAM , m_pBuffer ) , xdrstream::XDR_SUCCESS ) )
         return;
       this->notifyListeners(alert);
     }
bool dqm4hep::core::DimAlertInterface::isConnected () const virtual
Implements dqm4hep::core::AlertHandler.
Definition at line 507 of file AlertSystem.cc.
References m_isConnected.
Referenced by connectToService(), disconnectFromService(), and setUpdateTime().
     {
       return m_isConnected;
     }
void dqm4hep::core::DimAlertInterface::newEmitterRegistered (const std::string & emitter) virtual
Definition at line 434 of file AlertSystem.cc.
Referenced by timerHandler().
     {
       /* nop */
     }
void dqm4hep::core::DimAlertInterface::setUpdateTime (int updateTime)
Definition at line 448 of file AlertSystem.cc.
References isConnected(), and m_updateTime.
     {
       if( updateTime <= 0 )
         return;
       m_updateTime = updateTime;
       if( this->isConnected() )
         this->start( m_updateTime );
     }
void dqm4hep::core::DimAlertInterface::timerHandler () private
Definition at line 537 of file AlertSystem.cc.
References browse(), emitterUnregistered(), m_emitterInfoMap, m_updateTime, and newEmitterRegistered().
     {
       StringVector emitters = this->browse();
       StringVector emittersToRemove;
       // find emitters to remove from info map
       for(EmitterInfoMap::iterator iter = m_emitterInfoMap.begin(), endIter = m_emitterInfoMap.end() ;
           endIter != iter ; ++iter)
       {
         if( std::find( emitters.begin() , emitters.end() , iter->first ) == emitters.end() )
           emittersToRemove.push_back(iter->first);
       }
       // remove emitters from map
       for(StringVector::iterator iter = emittersToRemove.begin(), endIter = emittersToRemove.end() ;
           endIter != iter ; ++iter)
       {
         EmitterInfoMap::iterator findIter = m_emitterInfoMap.find( *iter );
         if( findIter == m_emitterInfoMap.end() )
           continue;
         delete findIter->second;
         m_emitterInfoMap.erase( findIter );
         // notify !
         this->emitterUnregistered( *iter );
       }
       // find emitters to add to info map and add them on the fly
       for(StringVector::iterator iter = emitters.begin(), endIter = emitters.end() ;
           endIter != iter ; ++iter)
       {
         EmitterInfoMap::iterator findIter = m_emitterInfoMap.find( *iter );
         if( findIter != m_emitterInfoMap.end() )
           continue;
         std::string infoName = "DQM4HEP/ALERT/" + *iter;
         DimInfo *pAlertInfo = new DimUpdatedInfo( infoName.c_str() , (void *) NULL, 0 , this );
         m_emitterInfoMap[ *iter ] = pAlertInfo;
         // notify !
         this->newEmitterRegistered( *iter );
       }
       // restart timer
       this->start(m_updateTime);
     }
Member Data Documentation
EmitterInfoMap dqm4hep::core::DimAlertInterface::m_emitterInfoMap private
Definition at line 342 of file AlertSystem.h.
Referenced by connectToService(), disconnectFromService(), and timerHandler().
bool dqm4hep::core::DimAlertInterface::m_isConnected private
Definition at line 345 of file AlertSystem.h.
Referenced by connectToService(), disconnectFromService(), and isConnected().
xdrstream::BufferDevice* dqm4hep::core::DimAlertInterface::m_pBuffer private
Definition at line 343 of file AlertSystem.h.
Referenced by configureInBuffer(), infoHandler(), and ~DimAlertInterface().
int dqm4hep::core::DimAlertInterface::m_updateTime private
Definition at line 344 of file AlertSystem.h.
Referenced by connectToService(), setUpdateTime(), and timerHandler().
The documentation for this class was generated from the following files:
AlertSystem.h
AlertSystem.cc