DQMOnline: dqm4hep::online::EventSource Class Reference
dqm4hep::online::EventSource Class Reference
EventSource class.
#include <EventSource.h>
Classes
struct CollectorInfo
CollectorInfo struct.
Public Member Functions
~EventSource ()
Destructor.
const std::string & sourceName () const
Get the source name.
void setStreamerName (const std::string &name)
Set the event streamer name.
const std::string & streamerName () const
Get the event streamer name.
void addCollector (const std::string &name)
Add a new collector server to which events will be sent.
void start ()
Start the event source.
void sendEvent (const core::EventPtr &event)
Send a single event to all registered collectors.
void sendEvent (const std::string &collector, const core::EventPtr &event)
Send a single event to a single collector.
core::EventPtr createEvent () const
Static Public Member Functions
static EventSourcePtr make_shared (const std::string &sourceName)
Factory method to create a shared pointer of event source.
Private Types
typedef std::shared_ptr
< core::EventStreamer > EventStreamerPtr
typedef std::shared_ptr
< xdrstream::BufferDevice > BufferDevicePtr
typedef std::map< std::string,
CollectorInfo > CollectorInfoMap
Private Member Functions
void getSourceInfo (core::json &info)
Get the source info (host info + source info)
bool registerMe (const std::string &collector, const core::json &info)
Register the event source to the specified collector.
void unregisterMe (const std::string &collector)
Un-register the event source from the specified collector.
void sendEvent (const core::StringVector &collectors, const core::EventPtr &event)
Perform the actual event sending to the specified list of collectors.
EventSource (const std::string &sourceName)
Constructor.
Private Attributes
bool m_started = false
Whether the event source was started.
std::string m_sourceName = ""
The source name.
std::string m_streamerName = ""
The event streamer name (plugin name)
EventStreamerPtr m_eventStreamer = {nullptr}
The event streamer pointer.
CollectorInfoMap m_collectorInfos = {}
The map of event collector infos.
net::Client m_client
The networking client interface.
BufferDevicePtr m_bufferDevice = {nullptr}
The serialized event raw buffer (from xdrstream)
Detailed Description
EventSource class.
Main interface for sending events to collectors (server process). Only one event source is allowed per process as the source is registered using the network client id on the collector server side. It is possible to send events to multiple event collectors. A typical usage could be:
EventSourcePtr source = EventSource::make_shared("EventBuilder");
source->setStreamerName("GenericEventStreamer");
source->addCollector("CentralCollector");
source->addCollector("PrivateCollector");
source->start();
// ...
core::EventPtr event = getLastEvent(); // hypothetical getter function
source->sendEvent(event); // send to all collectors
Definition at line 67 of file EventSource.h.
Member Typedef Documentation
typedef std::shared_ptr<xdrstream::BufferDevice> dqm4hep::online::EventSource::BufferDevicePtr private
Definition at line 188 of file EventSource.h.
typedef std::map<std::string, CollectorInfo> dqm4hep::online::EventSource::CollectorInfoMap private
Definition at line 189 of file EventSource.h.
typedef std::shared_ptr<core::EventStreamer> dqm4hep::online::EventSource::EventStreamerPtr private
Definition at line 187 of file EventSource.h.
Constructor & Destructor Documentation
dqm4hep::online::EventSource::~EventSource ()
Destructor.
Definition at line 53 of file EventSource.cc.
References m_collectorInfos, and unregisterMe().
     {
       for(auto colIter : m_collectorInfos)
         this->unregisterMe(colIter.first);
     }
dqm4hep::online::EventSource::EventSource (const std::string & sourceName) private
Constructor.
Parameters
sourceName the source name
Definition at line 45 of file EventSource.cc.
Referenced by make_shared().
                                                         :
         m_sourceName(sourceName)
     {
       /* nop */
     }
Member Function Documentation
void dqm4hep::online::EventSource::addCollector (const std::string & name)
Add a new collector server to which events will be sent.
Can be used only before calling start(). Must be called at least one time before calling start().
Parameters
name the event collector name
Definition at line 85 of file EventSource.cc.
References m_collectorInfos, dqm4hep::online::EventSource::CollectorInfo::m_registered, and m_started.
     {
       if(m_started)
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       auto findIter = m_collectorInfos.find(name);
       if(m_collectorInfos.end() != findIter)
         throw core::StatusCodeException(core::STATUS_CODE_ALREADY_PRESENT);
       CollectorInfo info;
       info.m_registered = false;
       m_collectorInfos.insert(CollectorInfoMap::value_type(name, info));
     }
core::EventPtr dqm4hep::online::EventSource::createEvent () const
Definition at line 223 of file EventSource.cc.
References m_eventStreamer, and m_started.
     {
       if(!m_started)
         throw core::StatusCodeException(core::STATUS_CODE_NOT_INITIALIZED);
       return m_eventStreamer->createEvent();
     }
void dqm4hep::online::EventSource::getSourceInfo (core::json & info) private
Get the source info (host info + source info)
Parameters
info the json value to receive
Definition at line 233 of file EventSource.cc.
References m_collectorInfos, m_sourceName, and m_streamerName.
Referenced by sendEvent(), and start().
     {
       // host info
       core::StringMap hostInfo;
       core::fillHostInfo(hostInfo);
       // collectors
       core::json collectorsValue;
       for(auto colIter : m_collectorInfos)
         collectorsValue.push_back(colIter.first);
       info["source"] = m_sourceName;
       info["host"] = hostInfo;
       info["collectors"] = collectorsValue;
       info["streamer"] = m_streamerName;
     }
EventSourcePtr dqm4hep::online::EventSource::make_shared (const std::string & sourceName) static
Factory method to create a shared pointer of event source.
Parameters
sourceName the source name
Definition at line 38 of file EventSource.cc.
References EventSource().
     {
       return std::shared_ptr<EventSource>(new EventSource(sourceName));
     }
bool dqm4hep::online::EventSource::registerMe (const std::string & collector, const core::json & info) private
Register the event source to the specified collector.
Parameters
collector the collector name to register to
info the source info to send to the collector
Returns
bool whether the source was registered
Definition at line 252 of file EventSource.cc.
References m_client.
Referenced by sendEvent(), and start().
     {
       std::string requestName = "/dqm4hep/app/evtcol/" + collector + "/register";
       bool returnValue(false);
       net::Buffer requestBuffer;
       auto model = requestBuffer.createModel<std::string>();
       requestBuffer.setModel(model);
       model->move(std::move(info.dump()));
       m_client.sendRequest(requestName, requestBuffer, [&returnValue,&collector](const net::Buffer &buffer){
         core::json response({});
         if(0 != buffer.size()) {
           response = core::json::parse(buffer.begin(), buffer.end());
         }
         const bool registered(response.value<bool>("registered", false));
         if(!registered)
         {
           const std::string message(response.value<std::string>("message", "The event collector is maybe not available or is down !"));
           dqm_warning( "EventSource::registerMe(): Couldn't register source to collector '{0}': {1}", collector, message );
           returnValue = false;
         }
         else
         {
           dqm_info( "Event source registered to event collector '{0}' !", collector );
           returnValue = true;
         }
       });
       if(returnValue)
       {
         dqm_info( "Will notify server on exit" );
         m_client.notifyServerOnExit("/dqm4hep/app/evtcol/" + collector);
       }
       return returnValue;
     }
void dqm4hep::online::EventSource::sendEvent (const core::EventPtr & event)
Send a single event to all registered collectors.
The event must be serializable by using the allocated streamer (see setStreamerName()).
Parameters
event the event pointer to serialize and send
Definition at line 137 of file EventSource.cc.
References m_collectorInfos.
Referenced by sendEvent().
     {
       core::StringVector collectors;
       for(auto iter : m_collectorInfos)
         collectors.push_back(iter.first);
       this->sendEvent(collectors, event);
     }
void dqm4hep::online::EventSource::sendEvent (const std::string & collector, const core::EventPtr & event)
Send a single event to a single collector.
The collector must have been registered with the function addCollector() before calling this function The event must be serializable by using the allocated streamer (see setStreamerName()).
Parameters
collector the event collector to send
event the event pointer to serialize and send
Definition at line 149 of file EventSource.cc.
References m_collectorInfos, and sendEvent().
     {
       if(m_collectorInfos.end() == m_collectorInfos.find(collector))
       {
         dqm_error( "EventSource::sendEvent(col,evt): collector '{0}' not registered !", collector );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_FOUND);
       }
       this->sendEvent(core::StringVector({collector}), event);
     }
void dqm4hep::online::EventSource::sendEvent (const core::StringVector & collectors, const core::EventPtr & event) private
Perform the actual event sending to the specified list of collectors.
Parameters
collectors the list of collectors
event [description]
Definition at line 162 of file EventSource.cc.
References getSourceInfo(), m_bufferDevice, m_client, m_collectorInfos, m_eventStreamer, m_sourceName, m_started, and registerMe().
     {
       if(!m_started)
         throw core::StatusCodeException(core::STATUS_CODE_NOT_INITIALIZED);
       if(nullptr == event)
         throw core::StatusCodeException(core::STATUS_CODE_INVALID_PTR);
       (void)m_bufferDevice->reset();
       THROW_RESULT_IF(core::STATUS_CODE_SUCCESS, !=, m_eventStreamer->write(event, m_bufferDevice.get()));
       core::json sourceInfo;
       net::Buffer collectBuffer;
       auto model = collectBuffer.createModel();
       collectBuffer.setModel(model);
       model->handle(m_bufferDevice->getBuffer(), m_bufferDevice->getPosition());
       // send serialized event to all collectors
       for(auto collector : collectors)
       {
         auto iter = m_collectorInfos.find(collector);
         if(m_collectorInfos.end() == iter)
         {
           dqm_error( "EventSource::sendEvent(): Collector '{0}' not found... Something is wrong !!!", collector );
           throw core::StatusCodeException(core::STATUS_CODE_NOT_FOUND);
         }
         // Is the event collector server actually running ?
         if(!net::Server::isServerRunning("/dqm4hep/app/evtcol/" + iter->first))
         {
           // in case the server was stopped, we will need to send
           // back the source registration on wake up
           iter->second.m_registered = false;
           continue;
         }
         // if not yet registered to the collector, do it
         if(!iter->second.m_registered)
         {
           // get it once
           if(sourceInfo.empty())
             this->getSourceInfo(sourceInfo);
           iter->second.m_registered = this->registerMe(iter->first, sourceInfo);
         }
         if(!iter->second.m_registered)
         {
           dqm_warning( "EventSource::sendEvent(): Source '{0}' not registered yet to collector '{1}'. Skipping ...", m_sourceName, collector );
           continue;
         }
         std::string collectCommand = "/dqm4hep/app/evtcol/" + collector + "/collect";
         m_client.sendCommand(collectCommand, collectBuffer);
       }
     }
void dqm4hep::online::EventSource::setStreamerName (const std::string & name)
Set the event streamer name.
Must be set before calling start()
Parameters
name the event streamer name
Definition at line 68 of file EventSource.cc.
References m_started, and m_streamerName.
     {
       if(m_started)
         throw core::StatusCodeException(core::STATUS_CODE_NOT_ALLOWED);
       m_streamerName = name;
     }
const std::string & dqm4hep::online::EventSource::sourceName () const
Get the source name.
Definition at line 61 of file EventSource.cc.
References m_sourceName.
     {
       return m_sourceName;
     }
void dqm4hep::online::EventSource::start ()
Start the event source.
Setup raw buffers, event streamer (plugin) and register it to event collectors
Definition at line 102 of file EventSource.cc.
References getSourceInfo(), m_bufferDevice, m_collectorInfos, m_eventStreamer, m_sourceName, m_started, m_streamerName, and registerMe().
     {
       if(m_started)
         throw core::StatusCodeException(core::STATUS_CODE_ALREADY_INITIALIZED);
       m_eventStreamer = core::PluginManager::instance()->create<core::EventStreamer>(m_streamerName);
       if(!m_eventStreamer)
       {
         dqm_error( "EventSource::start(): Event streamer '{0}' not found in available streamers. Couldn't initialize!", m_streamerName );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_FOUND);
       }
       if(m_collectorInfos.empty())
       {
         dqm_error( "EventSource::start(): Event source '{0}' has no collector to send event. Couldn't initialize!", m_sourceName );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_INITIALIZED);
       }
       m_bufferDevice = std::make_shared<xdrstream::BufferDevice>(2*1024*1024);
       core::json sourceInfo;
       this->getSourceInfo(sourceInfo);
       for(auto colIter : m_collectorInfos)
       {
         bool registered = this->registerMe(colIter.first, sourceInfo);
         colIter.second.m_registered = registered;
       }
       m_started = true;
     }
const std::string & dqm4hep::online::EventSource::streamerName () const
Get the event streamer name.
Definition at line 78 of file EventSource.cc.
References m_streamerName.
     {
       return m_streamerName;
     }
void dqm4hep::online::EventSource::unregisterMe (const std::string & collector) private
Un-register the event source from the specified collector.
Parameters
collector the collector name to un-register to
Definition at line 294 of file EventSource.cc.
References m_client.
Referenced by ~EventSource().
     {
       std::string commandName = "/dqm4hep/app/evtcol/" + collector + "/unregister";
       m_client.sendCommand(commandName, std::string(""));
     }
Member Data Documentation
BufferDevicePtr dqm4hep::online::EventSource::m_bufferDevice = {nullptr} private
The serialized event raw buffer (from xdrstream)
Definition at line 197 of file EventSource.h.
Referenced by sendEvent(), and start().
net::Client dqm4hep::online::EventSource::m_client private
The networking client interface.
Definition at line 196 of file EventSource.h.
Referenced by registerMe(), sendEvent(), and unregisterMe().
CollectorInfoMap dqm4hep::online::EventSource::m_collectorInfos = {} private
The map of event collector infos.
Definition at line 195 of file EventSource.h.
Referenced by addCollector(), getSourceInfo(), sendEvent(), start(), and ~EventSource().
EventStreamerPtr dqm4hep::online::EventSource::m_eventStreamer = {nullptr} private
The event streamer pointer.
Definition at line 194 of file EventSource.h.
Referenced by createEvent(), sendEvent(), and start().
std::string dqm4hep::online::EventSource::m_sourceName = "" private
The source name.
Definition at line 192 of file EventSource.h.
Referenced by getSourceInfo(), sendEvent(), sourceName(), and start().
bool dqm4hep::online::EventSource::m_started = false private
Whether the event source was started.
Definition at line 191 of file EventSource.h.
Referenced by addCollector(), createEvent(), sendEvent(), setStreamerName(), and start().
std::string dqm4hep::online::EventSource::m_streamerName = "" private
The event streamer name (plugin name)
Definition at line 193 of file EventSource.h.
Referenced by getSourceInfo(), setStreamerName(), start(), and streamerName().
The documentation for this class was generated from the following files:
EventSource.h
EventSource.cc