DQMOnline: dqm4hep::core::EventCollector Class Reference
dqm4hep::core::EventCollector Class Reference
EventCollector class.
#include <EventCollector.h>
Public Member Functions
EventCollector ()
Constructor.
EventCollector (EventCollectorImp *pCollectorImp)
Constructor with collector implementation.
~EventCollector ()
Destructor.
StatusCode setCollectorName (const std::string &collectorName)
Set the collctor name.
const std::string & getCollectorName () const
Get the collector name.
bool isRunning () const
Whether the collector server is running.
StatusCode startCollector ()
Start the collector server.
StatusCode stopCollector ()
Stop the collector server.
void setEventCollectorImp (EventCollectorImp *pCollectorImp)
Set the event collector implementation.
void setEventStreamer (EventStreamer *pEventStreamer)
Set the event streamer to serialize/deserialize the in/out-coming events.
EventStreamer * getEventStreamer () const
Get the event streamer.
Private Attributes
EventCollectorImp * m_pCollectorImp
Detailed Description
EventCollector class.
Definition at line 42 of file EventCollector.h.
Constructor & Destructor Documentation
dqm4hep::core::EventCollector::EventCollector ()
Constructor.
Definition at line 35 of file EventCollector.cc.
References m_pCollectorImp.
     {
       // default implementation is the DIM one
       m_pCollectorImp = new DimEventCollector();
     }
dqm4hep::core::EventCollector::EventCollector (EventCollectorImp * pCollectorImp)
Constructor with collector implementation.
Definition at line 43 of file EventCollector.cc.
                                                                    :
             m_pCollectorImp(pCollectorImp)
     {
       /* nop */
     }
dqm4hep::core::EventCollector::~EventCollector ()
Destructor.
Definition at line 51 of file EventCollector.cc.
References m_pCollectorImp.
     {
       delete m_pCollectorImp;
     }
Member Function Documentation
const std::string & dqm4hep::core::EventCollector::getCollectorName () const
Get the collector name.
Definition at line 65 of file EventCollector.cc.
References dqm4hep::core::EventCollectorImp::getCollectorName(), and m_pCollectorImp.
Referenced by dqm4hep::core::EventCollectorApplication::getName().
     {
       return m_pCollectorImp->getCollectorName();
     }
EventStreamer * dqm4hep::core::EventCollector::getEventStreamer () const
Get the event streamer.
Definition at line 111 of file EventCollector.cc.
References dqm4hep::core::EventCollectorImp::getEventStreamer(), and m_pCollectorImp.
Referenced by dqm4hep::core::EventCollectorApplication::getEventStreamer().
     {
       return m_pCollectorImp->getEventStreamer();
     }
bool dqm4hep::core::EventCollector::isRunning () const
Whether the collector server is running.
Definition at line 72 of file EventCollector.cc.
References dqm4hep::core::EventCollectorImp::isRunning(), and m_pCollectorImp.
Referenced by dqm4hep::core::EventCollectorApplication::~EventCollectorApplication().
     {
       return m_pCollectorImp->isRunning();
     }
StatusCode dqm4hep::core::EventCollector::setCollectorName (const std::string & collectorName)
Set the collctor name.
Definition at line 58 of file EventCollector.cc.
References m_pCollectorImp, and dqm4hep::core::EventCollectorImp::setCollectorName().
Referenced by dqm4hep::core::EventCollectorApplication::setCollectorName().
     {
       return m_pCollectorImp->setCollectorName(collectorName);
     }
void dqm4hep::core::EventCollector::setEventCollectorImp (EventCollectorImp * pCollectorImp)
Set the event collector implementation.
Definition at line 93 of file EventCollector.cc.
References m_pCollectorImp.
Referenced by dqm4hep::core::EventCollectorApplication::setEventCollectorImp().
     {
       if(NULL == pCollectorImp)
         return;
       delete m_pCollectorImp;
       m_pCollectorImp = pCollectorImp;
     }
void dqm4hep::core::EventCollector::setEventStreamer (EventStreamer * pEventStreamer)
Set the event streamer to serialize/deserialize the in/out-coming events.
Definition at line 104 of file EventCollector.cc.
References m_pCollectorImp, and dqm4hep::core::EventCollectorImp::setEventStreamer().
Referenced by dqm4hep::core::EventCollectorApplication::setEventStreamer().
     {
       m_pCollectorImp->setEventStreamer(pEventStreamer);
     }
StatusCode dqm4hep::core::EventCollector::startCollector ()
Start the collector server.
Definition at line 79 of file EventCollector.cc.
References m_pCollectorImp, and dqm4hep::core::EventCollectorImp::startCollector().
Referenced by dqm4hep::core::EventCollectorApplication::run().
     {
       return m_pCollectorImp->startCollector();
     }
StatusCode dqm4hep::core::EventCollector::stopCollector ()
Stop the collector server.
Definition at line 86 of file EventCollector.cc.
References m_pCollectorImp, and dqm4hep::core::EventCollectorImp::stopCollector().
Referenced by dqm4hep::core::EventCollectorApplication::exit(), and dqm4hep::core::EventCollectorApplication::~EventCollectorApplication().
     {
       return m_pCollectorImp->stopCollector();
     }
Member Data Documentation
EventCollectorImp* dqm4hep::core::EventCollector::m_pCollectorImp private
Definition at line 91 of file EventCollector.h.
Referenced by EventCollector(), getCollectorName(), getEventStreamer(), isRunning(), setCollectorName(), setEventCollectorImp(), setEventStreamer(), startCollector(), stopCollector(), and ~EventCollector().
The documentation for this class was generated from the following files:
EventCollector.h
EventCollector.cc