DQMOnline: dqm4hep::core::RunControlClient Class Reference
dqm4hep::core::RunControlClient Class Reference abstract
RunControlClient interface.
#include <RunControlClient.h>
Public Member Functions
RunControlClient ()
Constructor.
virtual ~RunControlClient ()
Destructor.
virtual StatusCode connectToService ()=0
Connect to the service.
virtual StatusCode disconnectFromService ()=0
Disconnect from the service.
virtual bool isConnectedToService () const =0
Whether the client is connected to the service.
Detailed Description
RunControlClient interface.
Definition at line 47 of file RunControlClient.h.
Constructor & Destructor Documentation
dqm4hep::core::RunControlClient::RunControlClient () inline
Constructor.
Definition at line 52 of file RunControlClient.h.
 : RunControl () {}
virtual dqm4hep::core::RunControlClient::~RunControlClient () inline virtual
Destructor.
Definition at line 56 of file RunControlClient.h.
 {}
Member Function Documentation
virtual StatusCode dqm4hep::core::RunControlClient::connectToService () pure virtual
Connect to the service.
Referenced by dqm4hep::core::AnalysisModuleApplication::startServices(), and dqm4hep::core::AnalysisModuleApplication::stopServices().
virtual StatusCode dqm4hep::core::RunControlClient::disconnectFromService () pure virtual
Disconnect from the service.
virtual bool dqm4hep::core::RunControlClient::isConnectedToService () const pure virtual
Whether the client is connected to the service.
Referenced by dqm4hep::core::AnalysisModuleApplication::stopServices().
The documentation for this class was generated from the following file:
RunControlClient.h