DQMOnline: dqm4hep::core::MonitorElementCollector Class Reference
dqm4hep::core::MonitorElementCollector Class Reference
MonitorElementCollector class.
#include <MonitorElementCollector.h>
Public Types
typedef std::map< std::string,
ModuleMeInfo * > ModuleMeInfoMap
Module element storage.
typedef std::set
< MonitorElementPtr > MonitorElementPtrSet
typedef std::map< int,
MonitorElementPtrSet > ClientUpdateMap
Map of monitor element list to update.
Public Member Functions
MonitorElementCollector ()
Constructor.
~MonitorElementCollector ()
Destructor.
StatusCode setCollectorName (const std::string &collectorName)
Set the collector name.
const std::string & getCollectorName () const
Get the collector name.
StatusCode start ()
Start the collector.
StatusCode stop ()
Stop the collector.
State getState () const
Get the collector state.
bool isRunning () const
Whether the collector is running.
Static Public Attributes
static const std::string m_emptyBufferStr = "EMPTY"
Private Member Functions
void commandHandler ()
Dim command handler.
void clientExitHandler ()
Dim client exit handler.
void updateClients (const ClientUpdateMap &clientUpdateMap, bool forceUpdate=false)
Update client side with the monitor elements.
void handleMeCollectUpdate (DimCommand *pCommand)
Handle the monitor element packet reception from a module application.
void handleAvailableListUpdate (DimCommand *pCommand)
Handle the available list of monitor element on module side.
void handleClientSubscription (int clientID, DimCommand *pCommand)
Handle a client subscription.
void handleClientUnsubscription (int clientID, DimCommand *pCommand)
Handle a client unsubscription.
void handleClientUpdateMode (int clientId, bool updateMode)
Handle client automatic update mode.
void handleClientRequestList (int clientId, DimCommand *pCommand)
Handle client me name request list update.
void handleMeQuery (int clientId, DimCommand *pCommand)
Handle the me query of target client id.
void sendMeUpdate (int clientID)
Update the monitor element publication service for a specific client.
void notifyWatchedMe (const std::string &moduleName)
Notify the module that users are watching a different set of monitor elements provided by the module.
bool registerClient (int clientId)
Register a monitor element client.
bool registerClient (int clientId, const std::string moduleName)
Register a module client.
bool deregisterClient (int clientId)
De-register a client.
int getModuleClientID (const std::string &moduleName) const
Get the module client ID.
void configureInBuffer (char *pBuffer, uint32_t bufferSize)
Private Attributes
std::string m_collectorName
MonitorElementNameListRpc * m_pMonitorElementNameListRpc
MonitorElementCollectorInfoRpc * m_pMonitorElementCollectorInfoRpc
DimCommand * m_pCollectMeCommand
DimCommand * m_pAvailableMeListCommand
DimCommand * m_pMeQueryCommand
DimCommand * m_pSetUpdateModeCommand
DimCommand * m_pSubscribeCommand
DimCommand * m_pUnsubscribeCommand
DimCommand * m_pSetSubscriptionCommand
DimCommand * m_pQuerySubscribedCommand
DimService * m_pMeUpdateService
DimService * m_pNotifyWatchedMeService
DimService * m_pCollectorStateService
DimService * m_pAvailableMeService
StatisticsService * m_pStatisticsService
int m_collectorState
xdrstream::BufferDevice * m_pInBuffer
xdrstream::BufferDevice * m_pOutBuffer
ModuleMeInfoMap m_moduleMeInfoMap
ClientMap m_clientMap
Friends
class CollectorCommandHandler
class MonitorElementNameListRpc
class MonitorElementCollectorInfoRpc
Detailed Description
MonitorElementCollector class.
Definition at line 217 of file MonitorElementCollector.h.
Member Typedef Documentation
typedef std::map<int, MonitorElementPtrSet> dqm4hep::core::MonitorElementCollector::ClientUpdateMap
Map of monitor element list to update.
Definition at line 256 of file MonitorElementCollector.h.
typedef std::map<std::string, ModuleMeInfo *> dqm4hep::core::MonitorElementCollector::ModuleMeInfoMap
Module element storage.
Definition at line 254 of file MonitorElementCollector.h.
typedef std::set<MonitorElementPtr> dqm4hep::core::MonitorElementCollector::MonitorElementPtrSet
Definition at line 255 of file MonitorElementCollector.h.
Constructor & Destructor Documentation
dqm4hep::core::MonitorElementCollector::MonitorElementCollector ()
Constructor.
Definition at line 376 of file MonitorElementCollector.cc.
References m_pOutBuffer.
                                                      :
         m_collectorName("DEFAULT"),
         m_collectorState(STOPPED_STATE),
         m_pMonitorElementNameListRpc(NULL),
         m_pMonitorElementCollectorInfoRpc(NULL),
         m_pInBuffer(NULL)
     {
       m_pOutBuffer = new xdrstream::BufferDevice(5*1024*1024);
     }
dqm4hep::core::MonitorElementCollector::~MonitorElementCollector ()
Destructor.
Definition at line 388 of file MonitorElementCollector.cc.
References isRunning(), m_pInBuffer, m_pOutBuffer, and stop().
     {
       if(this->isRunning())
         this->stop();
       delete m_pOutBuffer;
       if(m_pInBuffer)
         delete m_pInBuffer;
     }
Member Function Documentation
void dqm4hep::core::MonitorElementCollector::clientExitHandler () private
Dim client exit handler.
Definition at line 614 of file MonitorElementCollector.cc.
References deregisterClient().
     {
       int clientId = getClientId();
       this->deregisterClient(clientId);
     }
void dqm4hep::core::MonitorElementCollector::commandHandler () private
Dim command handler.
Definition at line 574 of file MonitorElementCollector.cc.
References handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleClientUpdateMode(), handleMeCollectUpdate(), handleMeQuery(), m_pAvailableMeListCommand, m_pCollectMeCommand, m_pMeQueryCommand, m_pSetSubscriptionCommand, m_pSetUpdateModeCommand, m_pSubscribeCommand, and m_pUnsubscribeCommand.
     {
       DimCommand *pReceivedCommand = getCommand();
       LOG4CXX_DEBUG( dqmMainLogger , "Received command : " << pReceivedCommand->getName() );
       // from modules
       if(pReceivedCommand == m_pCollectMeCommand)
       {
         this->handleMeCollectUpdate(pReceivedCommand);
       }
       else if(pReceivedCommand == m_pAvailableMeListCommand)
       {
         this->handleAvailableListUpdate(pReceivedCommand);
       }
       // from client side
       else if(pReceivedCommand == m_pMeQueryCommand)
       {
         this->handleMeQuery(getClientId(), m_pMeQueryCommand);
       }
       else if(pReceivedCommand == m_pSetUpdateModeCommand)
       {
         this->handleClientUpdateMode(getClientId(), static_cast<bool>(pReceivedCommand->getInt()));
       }
       else if(pReceivedCommand == m_pSubscribeCommand)
       {
         this->handleClientSubscription(getClientId(), pReceivedCommand);
       }
       else if(pReceivedCommand == m_pUnsubscribeCommand)
       {
         this->handleClientUnsubscription(getClientId(), pReceivedCommand);
       }
       else if(pReceivedCommand == m_pSetSubscriptionCommand)
       {
         this->handleClientRequestList(getClientId(), pReceivedCommand);
       }
     }
void dqm4hep::core::MonitorElementCollector::configureInBuffer (char * pBuffer, uint32_t bufferSize) private
Definition at line 1258 of file MonitorElementCollector.cc.
References m_pInBuffer.
Referenced by handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleMeCollectUpdate(), handleMeQuery(), and dqm4hep::core::MonitorElementNameListRpc::rpcHandler().
     {
       if( ! m_pInBuffer )
         m_pInBuffer = new xdrstream::BufferDevice( pBuffer , bufferSize , false );
       else
         m_pInBuffer->setBuffer( pBuffer , bufferSize , false );
       m_pInBuffer->setOwner( false );
     }
bool dqm4hep::core::MonitorElementCollector::deregisterClient (int clientId) private
De-register a client.
Definition at line 1189 of file MonitorElementCollector.cc.
References m_clientMap, m_moduleMeInfoMap, and notifyWatchedMe().
Referenced by clientExitHandler().
     {
       ClientMap::iterator findIter = m_clientMap.find(clientId);
       if(findIter == m_clientMap.end())
         return false;
       DimServer::clearClientExitHandler(clientId);
       // module client case
       if(findIter->second.isModule())
       {
         std::string moduleName = findIter->second.getModuleName();
         ModuleMeInfoMap::iterator moduleFindIter = m_moduleMeInfoMap.find(moduleName);
         if(moduleFindIter != m_moduleMeInfoMap.end())
         {
           delete moduleFindIter->second;
           m_moduleMeInfoMap.erase(moduleFindIter);
         }
         LOG4CXX_DEBUG( dqmMainLogger , "Deregistering module " << moduleName << " with client id " << clientId );
       }
       // monitor element client case
       else
       {
         // unsubscribe to all element that the client subscribed
         // this will update the list of watched monitor elements
         // We then have to notify modules that watched elements are not the same
         for(ModuleMeInfoMap::iterator iter = m_moduleMeInfoMap.begin(), endIter = m_moduleMeInfoMap.end() ;
             endIter != iter ; ++iter)
         {
           // this returns if at least one element has been removed
           // from the watched list. Use it to trigger update if necessary
           bool updateService = iter->second->unsubscribe(clientId);
           if(updateService)
             this->notifyWatchedMe(iter->first);
         }
         LOG4CXX_DEBUG( dqmMainLogger , "Registering me client " << clientId );
       }
       // finally remove the client from the map
       m_clientMap.erase(findIter);
       return true;
     }
const std::string & dqm4hep::core::MonitorElementCollector::getCollectorName () const
Get the collector name.
Definition at line 413 of file MonitorElementCollector.cc.
References m_collectorName.
Referenced by dqm4hep::core::MonitorElementCollectorApplication::getName(), and handleMeCollectUpdate().
     {
       return m_collectorName;
     }
int dqm4hep::core::MonitorElementCollector::getModuleClientID (const std::string & moduleName) const private
Get the module client ID.
Return 0 is not found (invalid for dim)
Definition at line 1241 of file MonitorElementCollector.cc.
References m_clientMap.
Referenced by notifyWatchedMe().
     {
       for(ClientMap::const_iterator iter = m_clientMap.begin(), endIter = m_clientMap.end() ;
           endIter != iter ; ++iter)
       {
         if( ! iter->second.isModule() )
           continue;
         if( iter->second.getModuleName() == moduleName )
           return iter->first;
       }
       return 0;
     }
State dqm4hep::core::MonitorElementCollector::getState () const
Get the collector state.
See State enum (DQM4HEP.h)
Definition at line 534 of file MonitorElementCollector.cc.
References m_collectorState.
     {
       return static_cast<State>(m_collectorState);
     }
void dqm4hep::core::MonitorElementCollector::handleAvailableListUpdate (DimCommand * pCommand) private
Handle the available list of monitor element on module side.
Definition at line 705 of file MonitorElementCollector.cc.
References configureInBuffer(), isRunning(), m_moduleMeInfoMap, m_pAvailableMeService, m_pInBuffer, m_pOutBuffer, notifyWatchedMe(), and registerClient().
Referenced by commandHandler().
     {
       if(!this->isRunning())
         return;
       try
       {
         dqm_char *pBuffer = static_cast<dqm_char *>(pCommand->getData());
         dqm_uint bufferSize = pCommand->getSize();
         if(NULL == pBuffer || 0 == bufferSize)
         {
           LOG4CXX_WARN( dqmMainLogger , "handleAvailableListUpdate(): invalid buffer");
           return;
         }
         this->configureInBuffer( pBuffer , bufferSize );
         // read the buffer
         std::string moduleName;
         if( xdrstream::XDR_SUCCESS != m_pInBuffer->read( & moduleName ) )
           throw StatusCodeException(STATUS_CODE_FAILURE);
         LOG4CXX_DEBUG( dqmMainLogger , "handleAvailableListUpdate(): module name = " << moduleName );
         if(moduleName.empty())
           throw StatusCodeException(STATUS_CODE_FAILURE);
         MonitorElementInfoList availableMeList;
         if( xdrstream::XDR_SUCCESS != StreamingHelper::read( m_pInBuffer , availableMeList ) )
           throw StatusCodeException(STATUS_CODE_FAILURE);
         // register client, even if maybe already registered
         bool newClient = this->registerClient(getClientId(), moduleName);
         // look for module entry to update
         ModuleMeInfoMap::iterator findIter = m_moduleMeInfoMap.find(moduleName);
         // if not found, add the entry
         if(findIter == m_moduleMeInfoMap.end())
           findIter = m_moduleMeInfoMap.insert(ModuleMeInfoMap::value_type(moduleName, new ModuleMeInfo())).first;
         // update the entry
         findIter->second->setAvailableMeList(availableMeList);
         LOG4CXX_DEBUG( dqmMainLogger , "Received " << availableMeList.size() << " available element from module " << moduleName );
         if(newClient)
           this->notifyWatchedMe(moduleName);
         m_pOutBuffer->reset();
         if( xdrstream::XDR_SUCCESS != StreamingHelper::write( m_pOutBuffer , availableMeList ) )
           throw StatusCodeException(STATUS_CODE_FAILURE);
         LOG4CXX_DEBUG( dqmMainLogger , "Sending available me list from module '" << moduleName << "' to all clients " );
         m_pAvailableMeService->updateService((void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition() );
       }
       catch(const StatusCodeException &exception)
       {
         LOG4CXX_ERROR( dqmMainLogger , "handleAvailableListUpdate(): Exception caught : " << exception.toString() );
       }
     }
void dqm4hep::core::MonitorElementCollector::handleClientRequestList (int clientId, DimCommand * pCommand) private
Handle client me name request list update.
Definition at line 795 of file MonitorElementCollector.cc.
References configureInBuffer(), isRunning(), m_moduleMeInfoMap, m_pInBuffer, notifyWatchedMe(), and registerClient().
Referenced by commandHandler().
     {
       if(!this->isRunning())
         return;
       try
       {
         dqm_char *pBuffer = static_cast<dqm_char *>(pCommand->getData());
         dqm_uint bufferSize = pCommand->getSize();
         if(NULL == pBuffer || 0 == bufferSize)
           return;
         this->registerClient(clientId);
         this->configureInBuffer( pBuffer , bufferSize );
         MonitorElementRequest request;
         if( xdrstream::XDR_SUCCESS != StreamingHelper::read( m_pInBuffer , request ) )
           throw StatusCodeException(STATUS_CODE_FAILURE);
         std::map<std::string, MonitorElementRequest> moduleRequestList;
         for(MonitorElementRequest::iterator iter = request.begin(), endIter = request.end() ;
             endIter != iter ; ++iter)
         {
           ModuleMeInfoMap::iterator moduleIter = m_moduleMeInfoMap.find(iter->first);
           if(moduleIter == m_moduleMeInfoMap.end())
             continue;
           LOG4CXX_DEBUG( dqmMainLogger , "Found module : " << iter->first );
           moduleRequestList[ iter->first ].insert(*iter);
         }
         for(auto iter = moduleRequestList.begin(), endIter = moduleRequestList.end() ;
             endIter != iter ; ++iter)
         {
           std::string moduleName = iter->first;
           ModuleMeInfoMap::iterator moduleIter = m_moduleMeInfoMap.find(moduleName);
           // first unsubscribe to all
           moduleIter->second->unsubscribe(clientId);
           // subscribe to all requested elements
           for(MonitorElementRequest::iterator reqIter = iter->second.begin(), endReqIter = iter->second.end() ;
               endReqIter != reqIter ; ++reqIter)
             moduleIter->second->subscribe(clientId, reqIter->second);
           // notify module of watched elements
           this->notifyWatchedMe(moduleName);
         }
       }
       catch(const StatusCodeException &exception)
       {
         LOG4CXX_ERROR( dqmMainLogger , "Exception caught : " << exception.toString() );
       }
     }
void dqm4hep::core::MonitorElementCollector::handleClientSubscription (int clientID, DimCommand * pCommand) private
Handle a client subscription.
Definition at line 951 of file MonitorElementCollector.cc.
References configureInBuffer(), isRunning(), m_moduleMeInfoMap, m_pInBuffer, notifyWatchedMe(), and registerClient().
Referenced by commandHandler().
     {
       if(!this->isRunning())
         return;
       try
       {
         dqm_char *pBuffer = static_cast<dqm_char *>(pCommand->getData());
         dqm_uint bufferSize = pCommand->getSize();
         if(NULL == pBuffer || 0 == bufferSize)
           return;
         this->configureInBuffer( pBuffer , bufferSize );
         MonitorElementRequest request;
         if( xdrstream::XDR_SUCCESS != StreamingHelper::read( m_pInBuffer , request ) )
           throw StatusCodeException(STATUS_CODE_FAILURE);
         // if nothing specified in the request, return
         if(request.empty())
         {
           LOG4CXX_DEBUG( dqmMainLogger , "No element to subscribe !" );
           return;
         }
         this->registerClient(clientId);
         StringSet updateModuleList;
         for(MonitorElementRequest::iterator iter = request.begin(), endIter = request.end() ;
             endIter != iter ; ++iter)
         {
           ModuleMeInfoMap::iterator moduleIter = m_moduleMeInfoMap.find(iter->first);
           if(moduleIter == m_moduleMeInfoMap.end())
             continue;
           if( moduleIter->second->subscribe(clientId, iter->second).second )
           {
             LOG4CXX_DEBUG( dqmMainLogger , "New subscription for element : " << iter->second );
             updateModuleList.insert(iter->first);
           }
         }
         for(StringSet::iterator iter = updateModuleList.begin(), endIter = updateModuleList.end() ;
             endIter != iter ; ++iter)
         {
           LOG4CXX_DEBUG( dqmMainLogger , "Module " << *iter << " notified to send new me list !" );
           this->notifyWatchedMe(*iter);
         }
       }
       catch(const StatusCodeException &exception)
       {
         LOG4CXX_WARN( dqmMainLogger , "handleClientSubscription(): Exception caught : " << exception.toString() );
       }
     }
void dqm4hep::core::MonitorElementCollector::handleClientUnsubscription (int clientID, DimCommand * pCommand) private
Handle a client unsubscription.
Definition at line 1011 of file MonitorElementCollector.cc.
References configureInBuffer(), isRunning(), m_moduleMeInfoMap, m_pInBuffer, notifyWatchedMe(), and registerClient().
Referenced by commandHandler().
     {
       if(!this->isRunning())
         return;
       try
       {
         dqm_char *pBuffer = static_cast<dqm_char *>(pCommand->getData());
         dqm_uint bufferSize = pCommand->getSize();
         if(NULL == pBuffer || 0 == bufferSize)
           return;
         this->configureInBuffer( pBuffer , bufferSize );
         MonitorElementRequest request;
         if( xdrstream::XDR_SUCCESS != StreamingHelper::read( m_pInBuffer , request ) )
           throw StatusCodeException(STATUS_CODE_FAILURE);
         // if nothing specified in the request, return
         if(request.empty())
         {
           LOG4CXX_DEBUG( dqmMainLogger , "No element to unsubscribe !" );
           return;
         }
         this->registerClient(clientId);
         StringSet updateModuleList;
         for(MonitorElementRequest::iterator iter = request.begin(), endIter = request.end() ;
             endIter != iter ; ++iter)
         {
           ModuleMeInfoMap::iterator moduleIter = m_moduleMeInfoMap.find(iter->first);
           if(moduleIter == m_moduleMeInfoMap.end())
             continue;
           if( moduleIter->second->unsubscribe(clientId, iter->second).second )
           {
             LOG4CXX_DEBUG( dqmMainLogger , "Element un-subscribed : " << iter->second );
             updateModuleList.insert(iter->first);
           }
         }
         for(StringSet::iterator iter = updateModuleList.begin(), endIter = updateModuleList.end() ;
             endIter != iter ; ++iter)
         {
           LOG4CXX_DEBUG( dqmMainLogger , "Module " << *iter << " notified to send new me list !" );
           this->notifyWatchedMe(*iter);
         }
       }
       catch(const StatusCodeException &exception)
       {
         LOG4CXX_WARN( dqmMainLogger , "handleClientUnsubscription(): Exception caught : " << exception.toString() );
       }
     }
void dqm4hep::core::MonitorElementCollector::handleClientUpdateMode (int clientId, bool updateMode) private
Handle client automatic update mode.
Definition at line 772 of file MonitorElementCollector.cc.
References m_clientMap, and sendMeUpdate().
Referenced by commandHandler().
     {
       ClientMap::iterator findIter = m_clientMap.find(clientId);
       if(findIter != m_clientMap.end())
       {
         if( ! findIter->second.hasUpdateMode() && updateMode)
         {
           LOG4CXX_INFO( dqmMainLogger , "Client no " << clientId << " update mode switched ON. Sending updates !" );
           this->sendMeUpdate(clientId);
         }
         LOG4CXX_INFO( dqmMainLogger , "Client no " << clientId << " setting update mode to " << updateMode );
         findIter->second.setUpdateMode(updateMode);
         return;
       }
       LOG4CXX_WARN( dqmMainLogger , "Client no " << clientId << " not registered !" );
     }
void dqm4hep::core::MonitorElementCollector::handleMeCollectUpdate (DimCommand * pCommand) private
Handle the monitor element packet reception from a module application.
Definition at line 622 of file MonitorElementCollector.cc.
References configureInBuffer(), getCollectorName(), m_moduleMeInfoMap, m_pInBuffer, m_pStatisticsService, and updateClients().
Referenced by commandHandler().
     {
       try
       {
         char *pBuffer = static_cast<char *>(pCommand->getData());
         int bufferSize = pCommand->getSize();
         if(bufferSize == 0 || NULL == pBuffer)
         {
           LOG4CXX_WARN( dqmMainLogger , "Empty buffer, skipping packet ..." );
           throw StatusCodeException(STATUS_CODE_SUCCESS);
         }
         this->configureInBuffer( pBuffer , bufferSize );
         Publication publication;
         if( xdrstream::XDR_SUCCESS != StreamingHelper::read( m_pInBuffer , publication ) )
         {
           LOG4CXX_ERROR( dqmMainLogger , "Couldn't read publication" );
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         if(publication.empty())
         {
           LOG4CXX_ERROR( dqmMainLogger , "Empty publication, skipping packet ..." );
           throw StatusCodeException(STATUS_CODE_SUCCESS);
         }
         int nElements = 0;
         ClientUpdateMap clientUpdateMap;
         // update the monitor element with the ones received !
         // build the monitor element list to update for each client
         for(Publication::iterator iter = publication.begin(), endIter = publication.end() ;
             endIter != iter ; ++iter)
         {
           ModuleMeInfoMap::iterator findIter = m_moduleMeInfoMap.find(iter->first);
           if(findIter == m_moduleMeInfoMap.end())
             continue;
           // update monitor elements !
           for(MonitorElementPtrList::iterator meIter = iter->second.begin(), meEndIter = iter->second.end() ;
               meEndIter != meIter ; ++meIter)
           {
             bool updated = findIter->second->updateMonitorElement(*meIter);
             nElements++;
             (*meIter)->setCollectorName(this->getCollectorName());
             // get the client ids that have subscribed to these elements
             std::string meFullName = ( (*meIter)->getPath() + (*meIter)->getName() ).getPath();
             if(meFullName.at(0) != '/')
               meFullName = "/" + meFullName;
             LOG4CXX_DEBUG( dqmMainLogger , "meFullName on collect : " << meFullName );
             std::set<int> clientIdSet = findIter->second->getSubscribers(meFullName);
             // add the monitor element entry into the update map
             for(std::set<int>::iterator cliIter = clientIdSet.begin(), cliEndIter = clientIdSet.end() ;
                 cliEndIter != cliIter ; ++cliIter)
             {
               clientUpdateMap[*cliIter].insert(*meIter);
             }
           }
         }
         m_pStatisticsService->update(nElements);
         LOG4CXX_DEBUG( dqmMainLogger , "Received n elements : " << nElements << " from " << publication.size() << " modules" );
         this->updateClients(clientUpdateMap);
       }
       catch(StatusCodeException &exception)
       {
         LOG4CXX_ERROR( dqmMainLogger , "handleMeCollectUpdate(): Exception caught : " << exception.toString() );
       }
     }
void dqm4hep::core::MonitorElementCollector::handleMeQuery (int clientId, DimCommand * pCommand) private
Handle the me query of target client id.
Definition at line 856 of file MonitorElementCollector.cc.
References configureInBuffer(), isRunning(), m_moduleMeInfoMap, m_pInBuffer, m_pMeUpdateService, m_pOutBuffer, notifyWatchedMe(), registerClient(), and sendMeUpdate().
Referenced by commandHandler().
     {
       if(!this->isRunning())
         return;
       try
       {
         dqm_char *pBuffer = static_cast<dqm_char *>(pCommand->getData());
         dqm_uint bufferSize = pCommand->getSize();
         if(NULL == pBuffer || 0 == bufferSize)
           return;
         this->configureInBuffer( pBuffer , bufferSize );
         MonitorElementRequest request;
         if( xdrstream::XDR_SUCCESS != StreamingHelper::read( m_pInBuffer , request ) )
           throw StatusCodeException(STATUS_CODE_FAILURE);
         // if nothing specified in the request, just send updates
         if(request.empty())
         {
           LOG4CXX_INFO( dqmMainLogger , "Sending me updates from client query" );
           this->sendMeUpdate(clientId);
           return;
         }
         this->registerClient(clientId);
         StringSet updateModuleList;
         Publication monitorElementPublication;
         LOG4CXX_DEBUG( dqmMainLogger , "Request size : " << request.size() );
         for(MonitorElementRequest::iterator iter = request.begin(), endIter = request.end() ;
             endIter != iter ; ++iter)
         {
           ModuleMeInfoMap::iterator moduleIter = m_moduleMeInfoMap.find(iter->first);
           if(moduleIter == m_moduleMeInfoMap.end())
             continue;
           LOG4CXX_DEBUG( dqmMainLogger , "Found module : " << iter->first );
           // subscribe to me if not done yet
           if( moduleIter->second->subscribe(clientId, iter->second).second )
           {
             LOG4CXX_DEBUG( dqmMainLogger , "New subscription for element : " << iter->second );
             updateModuleList.insert(iter->first);
           }
           else
           {
             LOG4CXX_DEBUG( dqmMainLogger , "Element : " << iter->second << " already subscribed !" );
           }
           // find the monitor element
           MonitorElementPtr monitorElement = moduleIter->second->getMonitorElement(iter->second);
           if(NULL == monitorElement)
             continue;
           LOG4CXX_DEBUG( dqmMainLogger , "Element : " << iter->second << " found !" );
           monitorElementPublication[iter->first].push_back(monitorElement);
         }
         for(StringSet::iterator iter = updateModuleList.begin(), endIter = updateModuleList.end() ;
             endIter != iter ; ++iter)
         {
           LOG4CXX_DEBUG( dqmMainLogger , "Module " << *iter << " notified to send new me list !" );
           this->notifyWatchedMe(*iter);
         }
         if(monitorElementPublication.empty())
           return;
         m_pOutBuffer->reset();
         if( xdrstream::XDR_SUCCESS != StreamingHelper::write( m_pOutBuffer , monitorElementPublication ) )
           return;
         int clientIds[2];
         clientIds[0] = clientId;
         clientIds[1] = 0;
         LOG4CXX_DEBUG( dqmMainLogger , "Me update service called (on query) !" );
         m_pMeUpdateService->selectiveUpdateService((void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition() , &clientIds[0]);
       }
       catch(const StatusCodeException &exception)
       {
         LOG4CXX_WARN( dqmMainLogger , "handleMeQuery(): Exception caught : " << exception.toString() );
       }
     }
bool dqm4hep::core::MonitorElementCollector::isRunning () const
Whether the collector is running.
Definition at line 541 of file MonitorElementCollector.cc.
References m_collectorState.
Referenced by handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleMeQuery(), dqm4hep::core::MonitorElementNameListRpc::rpcHandler(), sendMeUpdate(), setCollectorName(), start(), stop(), ~MonitorElementCollector(), and dqm4hep::core::MonitorElementCollectorApplication::~MonitorElementCollectorApplication().
     {
       return (m_collectorState == RUNNING_STATE);
     }
void dqm4hep::core::MonitorElementCollector::notifyWatchedMe (const std::string & moduleName) private
Notify the module that users are watching a different set of monitor elements provided by the module.
Definition at line 1117 of file MonitorElementCollector.cc.
References getModuleClientID(), m_moduleMeInfoMap, m_pNotifyWatchedMeService, and m_pOutBuffer.
Referenced by deregisterClient(), handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), and handleMeQuery().
     {
       int clientId = this->getModuleClientID(moduleName);
       if(0 == clientId)
         return;
       LOG4CXX_DEBUG( dqmMainLogger , "Notify watch me begin" );
       ModuleMeInfoMap::iterator moduleFindIter = m_moduleMeInfoMap.find(moduleName);
       if(moduleFindIter == m_moduleMeInfoMap.end())
         return;
       StringSet watchedMeList = moduleFindIter->second->getSubscribedList();
       m_pOutBuffer->reset();
       if( ! XDR_TESTBIT( StreamingHelper::write( m_pOutBuffer , watchedMeList ) , xdrstream::XDR_SUCCESS ) )
       {
         LOG4CXX_DEBUG( dqmMainLogger , "Notify watch me. Couldn't write watched list" );
         return;
       }
       int clientIds[2];
       clientIds[0] = clientId;
       clientIds[1] = 0;
       LOG4CXX_DEBUG( dqmMainLogger , "Notify watch me. Client id " << clientId );
       m_pNotifyWatchedMeService->selectiveUpdateService( (void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition(), &clientIds[0] );
     }
bool dqm4hep::core::MonitorElementCollector::registerClient (int clientId) private
Register a monitor element client.
Definition at line 1151 of file MonitorElementCollector.cc.
References m_clientMap.
Referenced by handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleMeQuery(), and sendMeUpdate().
     {
       ClientMap::iterator findIter = m_clientMap.find(clientId);
       if(findIter != m_clientMap.end())
         return false;
       // just insert a new client
       m_clientMap.insert( ClientMap::value_type( clientId, ClientInfo(clientId) ) );
       DimServer::setClientExitHandler(clientId);
       return true;
     }
bool dqm4hep::core::MonitorElementCollector::registerClient (int clientId, const std::string moduleName) private
Register a module client.
Definition at line 1167 of file MonitorElementCollector.cc.
References m_clientMap, and m_moduleMeInfoMap.
     {
       ClientMap::iterator findIter = m_clientMap.find(clientId);
       if(findIter != m_clientMap.end())
         return false;
       LOG4CXX_DEBUG( dqmMainLogger , "Registering module " << moduleName << " with client id " << clientId );
       // insert a new client
       m_clientMap.insert( ClientMap::value_type( clientId, ClientInfo(clientId, moduleName) ) );
       // create monitor element storage
       m_moduleMeInfoMap.insert( ModuleMeInfoMap::value_type( moduleName, new ModuleMeInfo() ) );
       DimServer::setClientExitHandler(clientId);
       return true;
     }
void dqm4hep::core::MonitorElementCollector::sendMeUpdate (int clientID) private
Update the monitor element publication service for a specific client.
Definition at line 1071 of file MonitorElementCollector.cc.
References isRunning(), m_moduleMeInfoMap, m_pMeUpdateService, m_pOutBuffer, and registerClient().
Referenced by handleClientUpdateMode(), handleMeQuery(), and updateClients().
     {
       if(!this->isRunning())
         return;
       this->registerClient(clientId);
       Publication monitorElementPublication;
       LOG4CXX_DEBUG( dqmMainLogger , "Building publication to send to client" );
       for(ModuleMeInfoMap::const_iterator iter = m_moduleMeInfoMap.begin(), endIter = m_moduleMeInfoMap.end() ;
           endIter != iter ; ++iter)
       {
         std::string moduleName = iter->first;
         MonitorElementPtrList subscribedMeList = iter->second->getSubscribedMeList(clientId);
         if(subscribedMeList.empty())
           continue;
         LOG4CXX_DEBUG( dqmMainLogger , "Module " << moduleName << ", total me list = " << subscribedMeList.size() );
         monitorElementPublication.insert(Publication::value_type(moduleName, subscribedMeList));
       }
       if(monitorElementPublication.empty())
       {
         LOG4CXX_DEBUG( dqmMainLogger , "Empty publication ! Nothing will be sent !" );
         return;
       }
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != StreamingHelper::write( m_pOutBuffer , monitorElementPublication ) )
         return;
       int clientIds[2];
       clientIds[0] = clientId;
       clientIds[1] = 0;
       LOG4CXX_DEBUG( dqmMainLogger , "Me update service called (on update)!" );
       m_pMeUpdateService->selectiveUpdateService((void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition() , &clientIds[0]);
     }
StatusCode dqm4hep::core::MonitorElementCollector::setCollectorName (const std::string & collectorName)
Set the collector name.
Can be set only if the collector is not running. The collector name is used to build the service and command names over the network
Definition at line 401 of file MonitorElementCollector.cc.
References isRunning(), and m_collectorName.
Referenced by dqm4hep::core::MonitorElementCollectorApplication::setCollectorName().
     {
       if(isRunning())
         return STATUS_CODE_NOT_ALLOWED;
       m_collectorName = collectorName;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementCollector::start ()
Start the collector.
Allocate services and commands
Definition at line 420 of file MonitorElementCollector.cc.
References isRunning(), m_collectorName, m_collectorState, m_pAvailableMeListCommand, m_pAvailableMeService, m_pCollectMeCommand, m_pCollectorStateService, m_pMeQueryCommand, m_pMeUpdateService, m_pMonitorElementCollectorInfoRpc, m_pMonitorElementNameListRpc, m_pNotifyWatchedMeService, m_pSetSubscriptionCommand, m_pSetUpdateModeCommand, m_pStatisticsService, m_pSubscribeCommand, m_pUnsubscribeCommand, MonitorElementCollectorInfoRpc, MonitorElementNameListRpc, and dqm4hep::core::pMeCollectormptyBuffer.
Referenced by dqm4hep::core::MonitorElementCollectorApplication::run().
     {
       if(isRunning())
         return STATUS_CODE_SUCCESS;
       std::string baseName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/";
       std::stringstream ss;
       ss << baseName << "MONITOR_ELEMENT_NAME_LIST_RPC";
       m_pMonitorElementNameListRpc = new MonitorElementNameListRpc((char *)ss.str().c_str(), this);
       ss.str("");
       ss << baseName << "COLLECTOR_INFO_RPC";
       m_pMonitorElementCollectorInfoRpc = new MonitorElementCollectorInfoRpc((char *)ss.str().c_str(), this);
       // from modules
       ss.str("");
       ss << baseName << "COLLECT_ME_CMD";
       m_pCollectMeCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
       ss.str("");
       ss << baseName << "NOTIFY_WATCHED_ME_SVC";
       m_pNotifyWatchedMeService = new DimService((char *)ss.str().c_str(), "C",
           (void*) pMeCollectormptyBuffer, 5);
       // from clients
       ss.str("");
       ss << baseName << "AVAILABLE_ME_CMD";
       m_pAvailableMeListCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
       ss.str("");
       ss << baseName << "QUERY_ME_CMD";
       m_pMeQueryCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
       ss.str("");
       ss << baseName << "SET_UPDATE_MODE_CMD";
       m_pSetUpdateModeCommand = new DimCommand((char *)ss.str().c_str(), "I", this);
       ss.str("");
       ss << baseName << "SUBSCRIBE_CMD";
       m_pSubscribeCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
       ss.str("");
       ss << baseName << "UNSUBSCRIBE_CMD";
       m_pUnsubscribeCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
       ss.str("");
       ss << baseName << "SET_SUBSCRIPTION_CMD";
       m_pSetSubscriptionCommand = new DimCommand((char *)ss.str().c_str(), "C", this);
       ss.str("");
       ss << baseName << "STATS";
       m_pStatisticsService = new StatisticsService(ss.str());
       ss.str("");
       ss << baseName << "ME_UPDATE_SVC";
       m_pMeUpdateService = new DimService((char *)ss.str().c_str(), "C",
           (void*) pMeCollectormptyBuffer, 5);
       ss.str("");
       ss << baseName << "AVAILABLE_ME_SVC";
       m_pAvailableMeService = new DimService((char *)ss.str().c_str(), "C",
           (void*) pMeCollectormptyBuffer, 5);
       m_collectorState = RUNNING_STATE;
       ss.str("");
       ss << baseName << "COLLECTOR_STATE_SVC";
       m_pCollectorStateService = new DimService((char *)ss.str().c_str(), m_collectorState);
       // for registration on dns ...
       CoreTool::sleep(std::chrono::seconds(1));
       // notify server running !
       LOG4CXX_INFO( dqmMainLogger , "Monitor element collector server started !" );
       m_pCollectorStateService->updateService(m_collectorState);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementCollector::stop ()
Stop the collector.
Destroy the commands and services
Definition at line 505 of file MonitorElementCollector.cc.
References isRunning(), m_collectorState, m_pAvailableMeListCommand, m_pAvailableMeService, m_pCollectMeCommand, m_pCollectorStateService, m_pMeQueryCommand, m_pMeUpdateService, m_pMonitorElementCollectorInfoRpc, m_pMonitorElementNameListRpc, m_pNotifyWatchedMeService, m_pSetSubscriptionCommand, m_pSetUpdateModeCommand, m_pStatisticsService, m_pSubscribeCommand, and m_pUnsubscribeCommand.
Referenced by dqm4hep::core::MonitorElementCollectorApplication::exit(), ~MonitorElementCollector(), and dqm4hep::core::MonitorElementCollectorApplication::~MonitorElementCollectorApplication().
     {
       if(!isRunning())
         return STATUS_CODE_SUCCESS;
       delete m_pCollectMeCommand;
       delete m_pAvailableMeListCommand;
       delete m_pMeQueryCommand;
       delete m_pSetUpdateModeCommand;
       delete m_pSubscribeCommand;
       delete m_pUnsubscribeCommand;
       delete m_pSetSubscriptionCommand;
       delete m_pMonitorElementNameListRpc;
       delete m_pMonitorElementCollectorInfoRpc;
       delete m_pStatisticsService;
       delete m_pMeUpdateService;
       delete m_pNotifyWatchedMeService;
       delete m_pAvailableMeService;
       m_collectorState = STOPPED_STATE;
       m_pCollectorStateService->updateService(m_collectorState);
       delete m_pCollectorStateService;
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::MonitorElementCollector::updateClients (const ClientUpdateMap & clientUpdateMap, bool forceUpdate = false) private
Update client side with the monitor elements.
Definition at line 548 of file MonitorElementCollector.cc.
References m_clientMap, and sendMeUpdate().
Referenced by handleMeCollectUpdate().
     {
       for(ClientUpdateMap::const_iterator iter = clientUpdateMap.begin(), endIter = clientUpdateMap.end() ;
           endIter != iter ; ++iter)
       {
         ClientMap::iterator clientIter = m_clientMap.find(iter->first);
         if(clientIter == m_clientMap.end())
         {
           LOG4CXX_WARN( dqmMainLogger , "Client no " << iter->first << " not registered. Skipping ..." );
           continue;
         }
         if(!clientIter->second.hasUpdateMode() && !forceUpdate)
         {
           LOG4CXX_DEBUG( dqmMainLogger , "Client no " << iter->first << " is not in update mode. Skipping ..." );
           continue;
         }
         LOG4CXX_DEBUG( dqmMainLogger , "Sending updates to client no " << iter->first );
         this->sendMeUpdate(clientIter->first);
       }
     }
Friends And Related Function Documentation
friend class CollectorCommandHandler friend
Definition at line 364 of file MonitorElementCollector.h.
friend class MonitorElementCollectorInfoRpc friend
Definition at line 366 of file MonitorElementCollector.h.
Referenced by start().
friend class MonitorElementNameListRpc friend
Definition at line 365 of file MonitorElementCollector.h.
Referenced by start().
Member Data Documentation
ClientMap dqm4hep::core::MonitorElementCollector::m_clientMap private
Definition at line 362 of file MonitorElementCollector.h.
Referenced by deregisterClient(), getModuleClientID(), handleClientUpdateMode(), registerClient(), and updateClients().
std::string dqm4hep::core::MonitorElementCollector::m_collectorName private
Definition at line 334 of file MonitorElementCollector.h.
Referenced by getCollectorName(), setCollectorName(), and start().
int dqm4hep::core::MonitorElementCollector::m_collectorState private
Definition at line 356 of file MonitorElementCollector.h.
Referenced by getState(), isRunning(), start(), and stop().
const std::string dqm4hep::core::MonitorElementCollector::m_emptyBufferStr = "EMPTY" static
Definition at line 258 of file MonitorElementCollector.h.
ModuleMeInfoMap dqm4hep::core::MonitorElementCollector::m_moduleMeInfoMap private
Definition at line 361 of file MonitorElementCollector.h.
Referenced by deregisterClient(), handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleMeCollectUpdate(), handleMeQuery(), notifyWatchedMe(), registerClient(), dqm4hep::core::MonitorElementNameListRpc::rpcHandler(), and sendMeUpdate().
DimCommand* dqm4hep::core::MonitorElementCollector::m_pAvailableMeListCommand private
Definition at line 341 of file MonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DimService* dqm4hep::core::MonitorElementCollector::m_pAvailableMeService private
Definition at line 352 of file MonitorElementCollector.h.
Referenced by handleAvailableListUpdate(), start(), and stop().
DimCommand* dqm4hep::core::MonitorElementCollector::m_pCollectMeCommand private
Definition at line 340 of file MonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DimService* dqm4hep::core::MonitorElementCollector::m_pCollectorStateService private
Definition at line 351 of file MonitorElementCollector.h.
Referenced by start(), and stop().
xdrstream::BufferDevice* dqm4hep::core::MonitorElementCollector::m_pInBuffer private
Definition at line 357 of file MonitorElementCollector.h.
Referenced by configureInBuffer(), handleAvailableListUpdate(), handleClientRequestList(), handleClientSubscription(), handleClientUnsubscription(), handleMeCollectUpdate(), handleMeQuery(), dqm4hep::core::MonitorElementNameListRpc::rpcHandler(), and ~MonitorElementCollector().
DimCommand* dqm4hep::core::MonitorElementCollector::m_pMeQueryCommand private
Definition at line 342 of file MonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DimService* dqm4hep::core::MonitorElementCollector::m_pMeUpdateService private
Definition at line 349 of file MonitorElementCollector.h.
Referenced by handleMeQuery(), sendMeUpdate(), start(), and stop().
MonitorElementCollectorInfoRpc* dqm4hep::core::MonitorElementCollector::m_pMonitorElementCollectorInfoRpc private
Definition at line 338 of file MonitorElementCollector.h.
Referenced by start(), and stop().
MonitorElementNameListRpc* dqm4hep::core::MonitorElementCollector::m_pMonitorElementNameListRpc private
Definition at line 337 of file MonitorElementCollector.h.
Referenced by start(), and stop().
DimService* dqm4hep::core::MonitorElementCollector::m_pNotifyWatchedMeService private
Definition at line 350 of file MonitorElementCollector.h.
Referenced by notifyWatchedMe(), start(), and stop().
xdrstream::BufferDevice* dqm4hep::core::MonitorElementCollector::m_pOutBuffer private
Definition at line 358 of file MonitorElementCollector.h.
Referenced by handleAvailableListUpdate(), handleMeQuery(), MonitorElementCollector(), notifyWatchedMe(), dqm4hep::core::MonitorElementNameListRpc::rpcHandler(), dqm4hep::core::MonitorElementCollectorInfoRpc::rpcHandler(), sendMeUpdate(), and ~MonitorElementCollector().
DimCommand* dqm4hep::core::MonitorElementCollector::m_pQuerySubscribedCommand private
Definition at line 347 of file MonitorElementCollector.h.
DimCommand* dqm4hep::core::MonitorElementCollector::m_pSetSubscriptionCommand private
Definition at line 346 of file MonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DimCommand* dqm4hep::core::MonitorElementCollector::m_pSetUpdateModeCommand private
Definition at line 343 of file MonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
StatisticsService* dqm4hep::core::MonitorElementCollector::m_pStatisticsService private
Definition at line 353 of file MonitorElementCollector.h.
Referenced by handleMeCollectUpdate(), start(), and stop().
DimCommand* dqm4hep::core::MonitorElementCollector::m_pSubscribeCommand private
Definition at line 344 of file MonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
DimCommand* dqm4hep::core::MonitorElementCollector::m_pUnsubscribeCommand private
Definition at line 345 of file MonitorElementCollector.h.
Referenced by commandHandler(), start(), and stop().
The documentation for this class was generated from the following files:
MonitorElementCollector.h
MonitorElementCollector.cc