DQMOnline: dqm4hep::core::ModuleApplication Class Reference
dqm4hep::core::ModuleApplication Class Reference abstract
ModuleApplication class.
#include <ModuleApplication.h>
Public Member Functions
ModuleApplication ()
Constructor.
virtual ~ModuleApplication ()
Destructor.
virtual StatusCode run ()=0
Run the application.
virtual StatusCode exit (int returnCode)
Stop the application.
virtual StatusCode readSettings (const std::string &settingsFile)=0
Read the settings from file.
virtual const std::string & getType () const =0
Get the application type.
virtual const std::string & getName () const =0
Get the application name.
Module * getModule () const
Get the module for this application.
bool shouldStopApplication () const
Whether the module application should stop.
void setStopApplication (bool stopApplication)
Set the application stop flag.
StatusCode setModuleName (const std::string &name)
Set the module name in used.
StatusCode setModuleType (const std::string &type)
Set the module type to look for (before calling readSettings())
const std::string & getModuleName () const
Get the module name in used.
const std::string & getModuleType () const
Get the module type in used.
bool isInitialized () const
Whether the application is initialized.
StatusCode getReturnCode () const
Get the return code when application ends.
Public Member Functions inherited from dqm4hep::core::Application
virtual ~Application ()
Destructor.
Protected Member Functions
void setInitialized (bool initialized)
Set the application has initialized.
MonitorElementManager * getMonitorElementManager () const
Get the monitor element manager.
MonitorElementSender * getMonitorElementSender () const
Get the monitor element sender.
AlertNotifier * getAlertNotifier () const
Get the alert notifier.
StatusCode setModule (Module *pModule)
Set the module in use in this application.
StatusCode createAlertNotifier (const std::string moduleName)
Create the alert notifier with the module name.
Protected Attributes
StatusCode m_returnCode
Module * m_pModule
Private Attributes
bool m_isInitialized
bool m_shouldStop
std::string m_moduleType
std::string m_moduleName
MonitorElementManager * m_pMonitorElementManager
MonitorElementSender * m_pMonitorElementSender
AlertNotifier * m_pAlertNotifier
Friends
class Archiver
class ModuleApi
Detailed Description
ModuleApplication class.
Definition at line 49 of file ModuleApplication.h.
Constructor & Destructor Documentation
dqm4hep::core::ModuleApplication::ModuleApplication ()
Constructor.
Definition at line 37 of file ModuleApplication.cc.
References m_pMonitorElementManager, and m_pMonitorElementSender.
                                          :
         m_isInitialized(false),
         m_shouldStop(false),
         m_pModule(NULL),
         m_pMonitorElementManager(NULL),
         m_pMonitorElementSender(NULL),
         m_pAlertNotifier(NULL)
     {
       m_pMonitorElementManager = new MonitorElementManager();
       m_pMonitorElementSender = new MonitorElementSender(this);
     }
dqm4hep::core::ModuleApplication::~ModuleApplication () virtual
Destructor.
Definition at line 51 of file ModuleApplication.cc.
References m_pAlertNotifier, m_pModule, m_pMonitorElementManager, and m_pMonitorElementSender.
     {
       delete m_pMonitorElementManager;
       delete m_pMonitorElementSender;
       if(m_pModule)
         delete m_pModule;
       if(m_pAlertNotifier)
         delete m_pAlertNotifier;
     }
Member Function Documentation
StatusCode dqm4hep::core::ModuleApplication::createAlertNotifier (const std::string moduleName) protected
Create the alert notifier with the module name.
Definition at line 209 of file ModuleApplication.cc.
References m_pAlertNotifier.
Referenced by setModule().
     {
       if( m_pAlertNotifier )
         return STATUS_CODE_ALREADY_INITIALIZED;
       m_pAlertNotifier = new DimAlertNotifier(moduleName);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApplication::exit (int returnCode) virtual
Stop the application.
Implements dqm4hep::core::Application.
Definition at line 65 of file ModuleApplication.cc.
References isInitialized(), m_returnCode, and setStopApplication().
     {
       LOG4CXX_INFO( dqmMainLogger , "Exiting module application ..." );
       if(!this->isInitialized())
         return STATUS_CODE_NOT_INITIALIZED;
       if( returnCode >= 0 && returnCode < NUMBER_OF_STATUS_CODES )
         m_returnCode = static_cast< StatusCode >( returnCode );
       else
         m_returnCode = STATUS_CODE_FAILURE;
       this->setStopApplication(true);
       LOG4CXX_INFO( dqmMainLogger , "Exiting module application ... OK" );
       return m_returnCode;
     }
AlertNotifier * dqm4hep::core::ModuleApplication::getAlertNotifier () const protected
Get the alert notifier.
Definition at line 186 of file ModuleApplication.cc.
References m_pAlertNotifier.
Referenced by dqm4hep::core::ModuleApi::sendAlert().
     {
       return m_pAlertNotifier;
     }
Module * dqm4hep::core::ModuleApplication::getModule () const
Get the module for this application.
Definition at line 86 of file ModuleApplication.cc.
References m_pModule.
Referenced by dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::AnalysisModuleApplication::configureModule(), dqm4hep::core::StandaloneModuleApplication::onCycleStarted(), dqm4hep::core::AnalysisModuleApplication::onCycleStarted(), dqm4hep::core::StandaloneModuleApplication::onCycleStopped(), dqm4hep::core::AnalysisModuleApplication::onCycleStopped(), dqm4hep::core::StandaloneModuleApplication::readSettings(), dqm4hep::core::AnalysisModuleApplication::readSettings(), dqm4hep::core::StandaloneModuleApplication::run(), dqm4hep::core::AnalysisModuleApplication::run(), dqm4hep::core::MonitorElementSender::sendAvailableMonitorElementList(), and dqm4hep::core::MonitorElementSender::sendMonitorElements().
     {
       return m_pModule;
     }
const std::string & dqm4hep::core::ModuleApplication::getModuleName () const
Get the module name in used.
Definition at line 134 of file ModuleApplication.cc.
References dqm4hep::core::Module::getName(), m_moduleName, and m_pModule.
Referenced by dqm4hep::core::AnalysisModuleApplication::configureModule(), and dqm4hep::core::StandaloneModuleApplication::readSettings().
     {
       if(m_pModule)
         return m_pModule->getName();
       return m_moduleName;
     }
const std::string & dqm4hep::core::ModuleApplication::getModuleType () const
Get the module type in used.
Definition at line 144 of file ModuleApplication.cc.
References m_moduleType.
Referenced by dqm4hep::core::AnalysisModuleApplication::configureModule(), and dqm4hep::core::StandaloneModuleApplication::readSettings().
     {
       return m_moduleType;
     }
MonitorElementManager * dqm4hep::core::ModuleApplication::getMonitorElementManager () const protected
Get the monitor element manager.
Definition at line 172 of file ModuleApplication.cc.
References m_pMonitorElementManager.
Referenced by dqm4hep::core::ModuleApi::addQualityTest(), dqm4hep::core::ModuleApi::bookCharHistogram1D(), dqm4hep::core::ModuleApi::bookCharHistogram2D(), dqm4hep::core::ModuleApi::bookFloat(), dqm4hep::core::ModuleApi::bookInt(), dqm4hep::core::ModuleApi::bookIntHistogram1D(), dqm4hep::core::ModuleApi::bookIntHistogram2D(), dqm4hep::core::ModuleApi::bookIntHistogram3D(), dqm4hep::core::ModuleApi::bookMonitorElement(), dqm4hep::core::ModuleApi::bookObject(), dqm4hep::core::ModuleApi::bookProfile1D(), dqm4hep::core::ModuleApi::bookProfile2D(), dqm4hep::core::ModuleApi::bookRealHistogram1D(), dqm4hep::core::ModuleApi::bookRealHistogram2D(), dqm4hep::core::ModuleApi::bookRealHistogram3D(), dqm4hep::core::ModuleApi::bookShort(), dqm4hep::core::ModuleApi::bookShortHistogram1D(), dqm4hep::core::ModuleApi::bookShortHistogram2D(), dqm4hep::core::ModuleApi::bookString(), dqm4hep::core::ModuleApi::cd(), dqm4hep::core::ModuleApi::createQualityTest(), dqm4hep::core::ModuleApi::deleteMonitorElement(), dqm4hep::core::ModuleApi::dirExists(), dqm4hep::core::ModuleApi::getAllMonitorElements(), dqm4hep::core::ModuleApi::getMonitorElement(), dqm4hep::core::ModuleApi::goUp(), dqm4hep::core::ModuleApi::ls(), dqm4hep::core::ModuleApi::mkdir(), dqm4hep::core::ModuleApi::pwd(), dqm4hep::core::ModuleApi::registerQualityTestFactory(), dqm4hep::core::ModuleApi::resetMonitorElements(), dqm4hep::core::ModuleApi::rmdir(), dqm4hep::core::AnalysisModuleApplication::run(), dqm4hep::core::ModuleApi::runQualityTest(), and dqm4hep::core::ModuleApi::runQualityTests().
     {
       return m_pMonitorElementManager;
     }
MonitorElementSender * dqm4hep::core::ModuleApplication::getMonitorElementSender () const protected
Get the monitor element sender.
Definition at line 179 of file ModuleApplication.cc.
References m_pMonitorElementSender.
Referenced by dqm4hep::core::ModuleApi::bookCharHistogram1D(), dqm4hep::core::ModuleApi::bookCharHistogram2D(), dqm4hep::core::ModuleApi::bookFloat(), dqm4hep::core::ModuleApi::bookInt(), dqm4hep::core::ModuleApi::bookIntHistogram1D(), dqm4hep::core::ModuleApi::bookIntHistogram2D(), dqm4hep::core::ModuleApi::bookIntHistogram3D(), dqm4hep::core::ModuleApi::bookMonitorElement(), dqm4hep::core::ModuleApi::bookObject(), dqm4hep::core::ModuleApi::bookProfile1D(), dqm4hep::core::ModuleApi::bookProfile2D(), dqm4hep::core::ModuleApi::bookRealHistogram1D(), dqm4hep::core::ModuleApi::bookRealHistogram2D(), dqm4hep::core::ModuleApi::bookRealHistogram3D(), dqm4hep::core::ModuleApi::bookShort(), dqm4hep::core::ModuleApi::bookShortHistogram1D(), dqm4hep::core::ModuleApi::bookShortHistogram2D(), dqm4hep::core::ModuleApi::bookString(), dqm4hep::core::AnalysisModuleApplication::configureNetwork(), dqm4hep::core::ModuleApi::deleteMonitorElement(), dqm4hep::core::StandaloneModuleApplication::readSettings(), dqm4hep::core::StandaloneModuleApplication::run(), dqm4hep::core::AnalysisModuleApplication::run(), dqm4hep::core::AnalysisModuleApplication::startServices(), and dqm4hep::core::AnalysisModuleApplication::stopServices().
     {
       return m_pMonitorElementSender;
     }
virtual const std::string& dqm4hep::core::ModuleApplication::getName () const pure virtual
Get the application name.
Implements dqm4hep::core::Application.
Implemented in dqm4hep::core::AnalysisModuleApplication, and dqm4hep::core::StandaloneModuleApplication.
StatusCode dqm4hep::core::ModuleApplication::getReturnCode () const
Get the return code when application ends.
Definition at line 158 of file ModuleApplication.cc.
References m_returnCode.
Referenced by dqm4hep::core::AnalysisModuleApplication::run().
     {
       return m_returnCode;
     }
virtual const std::string& dqm4hep::core::ModuleApplication::getType () const pure virtual
Get the application type.
Implements dqm4hep::core::Application.
Implemented in dqm4hep::core::AnalysisModuleApplication, and dqm4hep::core::StandaloneModuleApplication.
bool dqm4hep::core::ModuleApplication::isInitialized () const
Whether the application is initialized.
Definition at line 151 of file ModuleApplication.cc.
References m_isInitialized.
Referenced by exit(), dqm4hep::core::StandaloneModuleApplication::readSettings(), dqm4hep::core::AnalysisModuleApplication::readSettings(), dqm4hep::core::StandaloneModuleApplication::run(), dqm4hep::core::AnalysisModuleApplication::run(), setModuleName(), and setModuleType().
     {
       return m_isInitialized;
     }
virtual StatusCode dqm4hep::core::ModuleApplication::readSettings (const std::string & settingsFile) pure virtual
Read the settings from file.
Implements dqm4hep::core::Application.
Implemented in dqm4hep::core::AnalysisModuleApplication, and dqm4hep::core::StandaloneModuleApplication.
virtual StatusCode dqm4hep::core::ModuleApplication::run () pure virtual
Run the application.
Implements dqm4hep::core::Application.
Implemented in dqm4hep::core::AnalysisModuleApplication, and dqm4hep::core::StandaloneModuleApplication.
void dqm4hep::core::ModuleApplication::setInitialized (bool initialized) protected
Set the application has initialized.
Definition at line 165 of file ModuleApplication.cc.
References m_isInitialized.
Referenced by dqm4hep::core::StandaloneModuleApplication::readSettings(), and dqm4hep::core::AnalysisModuleApplication::readSettings().
     {
       m_isInitialized = initialized;
     }
StatusCode dqm4hep::core::ModuleApplication::setModule (Module * pModule) protected
Set the module in use in this application.
Definition at line 193 of file ModuleApplication.cc.
References createAlertNotifier(), m_moduleName, m_pModule, dqm4hep::core::Module::setModuleApplication(), and dqm4hep::core::Module::setName().
Referenced by dqm4hep::core::AnalysisModuleApplication::configureModule(), and dqm4hep::core::StandaloneModuleApplication::readSettings().
     {
       if(!pModule)
         return STATUS_CODE_INVALID_PTR;
       m_pModule = pModule;
       m_pModule->setName(m_moduleName);
       m_pModule->setModuleApplication(this);
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->createAlertNotifier(m_moduleName))
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApplication::setModuleName (const std::string & name)
Set the module name in used.
Definition at line 107 of file ModuleApplication.cc.
References isInitialized(), m_moduleName, m_pModule, and dqm4hep::core::Module::setName().
Referenced by dqm4hep::core::AnalysisModuleApplication::configureModule(), and dqm4hep::core::StandaloneModuleApplication::readSettings().
     {
       if(this->isInitialized())
         return STATUS_CODE_ALREADY_INITIALIZED;
       m_moduleName = name;
       if(m_pModule)
         m_pModule->setName(name);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApplication::setModuleType (const std::string & type)
Set the module type to look for (before calling readSettings())
Definition at line 122 of file ModuleApplication.cc.
References isInitialized(), and m_moduleType.
Referenced by dqm4hep::core::AnalysisModuleApplication::configureModule(), and dqm4hep::core::StandaloneModuleApplication::readSettings().
     {
       if(this->isInitialized())
         return STATUS_CODE_ALREADY_INITIALIZED;
       m_moduleType = type;
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::ModuleApplication::setStopApplication (bool stopApplication)
Set the application stop flag.
Definition at line 100 of file ModuleApplication.cc.
References m_shouldStop.
Referenced by exit().
     {
       m_shouldStop = stopApplication;
     }
bool dqm4hep::core::ModuleApplication::shouldStopApplication () const
Whether the module application should stop.
Definition at line 93 of file ModuleApplication.cc.
References m_shouldStop.
Referenced by dqm4hep::core::StandaloneModuleApplication::run(), and dqm4hep::core::AnalysisModuleApplication::run().
     {
       return m_shouldStop;
     }
Friends And Related Function Documentation
friend class Archiver friend
Definition at line 51 of file ModuleApplication.h.
Referenced by dqm4hep::core::AnalysisModuleApplication::AnalysisModuleApplication(), and dqm4hep::core::StandaloneModuleApplication::StandaloneModuleApplication().
friend class ModuleApi friend
Definition at line 52 of file ModuleApplication.h.
Member Data Documentation
bool dqm4hep::core::ModuleApplication::m_isInitialized private
Definition at line 148 of file ModuleApplication.h.
Referenced by isInitialized(), and setInitialized().
std::string dqm4hep::core::ModuleApplication::m_moduleName private
Definition at line 151 of file ModuleApplication.h.
Referenced by getModuleName(), dqm4hep::core::StandaloneModuleApplication::Settings::print(), setModule(), and setModuleName().
std::string dqm4hep::core::ModuleApplication::m_moduleType private
Definition at line 150 of file ModuleApplication.h.
Referenced by getModuleType(), dqm4hep::core::StandaloneModuleApplication::Settings::print(), and setModuleType().
AlertNotifier* dqm4hep::core::ModuleApplication::m_pAlertNotifier private
Definition at line 155 of file ModuleApplication.h.
Referenced by createAlertNotifier(), getAlertNotifier(), and ~ModuleApplication().
Module* dqm4hep::core::ModuleApplication::m_pModule protected
Definition at line 145 of file ModuleApplication.h.
Referenced by getModule(), getModuleName(), setModule(), setModuleName(), and ~ModuleApplication().
MonitorElementManager* dqm4hep::core::ModuleApplication::m_pMonitorElementManager private
Definition at line 153 of file ModuleApplication.h.
Referenced by getMonitorElementManager(), ModuleApplication(), and ~ModuleApplication().
MonitorElementSender* dqm4hep::core::ModuleApplication::m_pMonitorElementSender private
Definition at line 154 of file ModuleApplication.h.
Referenced by getMonitorElementSender(), ModuleApplication(), and ~ModuleApplication().
StatusCode dqm4hep::core::ModuleApplication::m_returnCode protected
Definition at line 144 of file ModuleApplication.h.
Referenced by exit(), and getReturnCode().
bool dqm4hep::core::ModuleApplication::m_shouldStop private
Definition at line 149 of file ModuleApplication.h.
Referenced by setStopApplication(), and shouldStopApplication().
The documentation for this class was generated from the following files:
ModuleApplication.h
ModuleApplication.cc