DQMOnline: dqm4hep::core::RunControlService Class Reference
dqm4hep::core::RunControlService Class Reference
RunControlService class.
#include <RunControlService.h>
Public Member Functions
RunControlService ()
Constructor.
~RunControlService ()
Destructor.
StatusCode start ()
Start the service.
StatusCode stop ()
Stop the service.
StatusCode pause ()
Pause the service until restart is called.
StatusCode restart ()
Restart the service.
State getState () const
Get the service state.
bool isRunning () const
Whether the service is running.
StatusCode setRunControlName (const std::string &runControlName)
Set the run control name.
const std::string & getRunControlName () const
Get the run control name.
StatusCode startNewRun (unsigned int runNumber, const std::string &description="", const std::string &detectorName="", const std::string &password="")
Create a new run.
StatusCode startNewRun (Run *pRun, const std::string &password="")
Create a new run.
StatusCode endCurrentRun (const std::string &password="")
End the current run.
int getCurrentRunNumber () const
Get the current run number.
State getRunState () const
Get the run state (running or not)
Run * getCurrentRun () const
Get the current run.
StatusCode setPassword (const std::string &password)
Set the password for this run control service.
Private Member Functions
void handleCurrentRunRpc (DimRpc *pRpc)
Handle the received rpc to get the current run.
void handleStartNewRunRpc (DimRpc *pRpc)
Handle the received rpc to start a new run.
void handleEndCurrentRunRpc (DimRpc *pRpc)
Handle the received rpc to end the current run.
void configureInBuffer (char *pBuffer, xdrstream::xdr_size_t bufferSize)
Private Attributes
int m_currentRunNumber
State m_serviceState
RunControl * m_pRunControl
DimService * m_pStartOfRunService
DimService * m_pEndOfRunService
DimRpc * m_pCurrentRunRpc
DimRpc * m_pStartNewRunRpc
DimRpc * m_pEndCurrentRunRpc
xdrstream::BufferDevice * m_pInBuffer
xdrstream::BufferDevice * m_pOutBuffer
Friends
class CurrentRunRpc
class StartNewRunRpc
class EndCurrentRunRpc
Detailed Description
RunControlService class.
Definition at line 123 of file RunControlService.h.
Constructor & Destructor Documentation
dqm4hep::core::RunControlService::RunControlService ()
Constructor.
Definition at line 94 of file RunControlService.cc.
References m_pOutBuffer, and m_pRunControl.
                                          :
         m_currentRunNumber(-1),
         m_serviceState(STOPPED_STATE),
         m_pStartOfRunService(NULL),
         m_pEndOfRunService(NULL),
         m_pRunControl(NULL),
         m_pCurrentRunRpc(NULL),
         m_pStartNewRunRpc(NULL),
         m_pEndCurrentRunRpc(NULL),
         m_pOutBuffer(0),
         m_pInBuffer(0)
     {
       m_pRunControl = new RunControl();
       m_pOutBuffer = new xdrstream::BufferDevice(1024);
     }
dqm4hep::core::RunControlService::~RunControlService ()
Destructor.
Definition at line 112 of file RunControlService.cc.
References endCurrentRun(), isRunning(), m_pInBuffer, m_pOutBuffer, m_pRunControl, and stop().
     {
       if(this->isRunning())
       {
         if(RUNNING_STATE == m_pRunControl->getRunState())
           this->endCurrentRun();
         this->stop();
       }
       delete m_pRunControl;
       delete m_pOutBuffer;
       if( m_pInBuffer )
         delete m_pInBuffer;
     }
Member Function Documentation
void dqm4hep::core::RunControlService::configureInBuffer (char * pBuffer, xdrstream::xdr_size_t bufferSize) private
Definition at line 621 of file RunControlService.cc.
References m_pInBuffer.
Referenced by handleEndCurrentRunRpc(), and handleStartNewRunRpc().
     {
       if( ! m_pInBuffer )
         m_pInBuffer = new xdrstream::BufferDevice( pBuffer, bufferSize , false );
       else
         m_pInBuffer->setBuffer( pBuffer, bufferSize , false );
       m_pInBuffer->setOwner(false);
     }
StatusCode dqm4hep::core::RunControlService::endCurrentRun (const std::string & password = "")
End the current run.
Definition at line 244 of file RunControlService.cc.
References getRunState(), isRunning(), m_currentRunNumber, m_pEndOfRunService, m_pOutBuffer, and m_pRunControl.
Referenced by handleEndCurrentRunRpc(), startNewRun(), and ~RunControlService().
     {
       if(!isRunning())
         return STATUS_CODE_NOT_INITIALIZED;
       if(RUNNING_STATE != getRunState())
         return STATUS_CODE_SUCCESS;
       m_currentRunNumber = -1;
       m_pRunControl->getCurrentRun()->setEndTime(CoreTool::now());
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != m_pRunControl->getCurrentRun()->stream( xdrstream::XDR_WRITE_STREAM , m_pOutBuffer ) )
         return STATUS_CODE_FAILURE;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControl->endCurrentRun(password));
       m_pEndOfRunService->updateService((void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition());
       return STATUS_CODE_SUCCESS;
     }
Run * dqm4hep::core::RunControlService::getCurrentRun () const
Get the current run.
Return NULL if not running
Definition at line 315 of file RunControlService.cc.
References m_pRunControl.
Referenced by handleStartNewRunRpc().
     {
       return m_pRunControl->getCurrentRun();
     }
int dqm4hep::core::RunControlService::getCurrentRunNumber () const
Get the current run number.
Definition at line 268 of file RunControlService.cc.
References m_currentRunNumber.
     {
       return m_currentRunNumber;
     }
const std::string & dqm4hep::core::RunControlService::getRunControlName () const
Get the run control name.
Definition at line 308 of file RunControlService.cc.
References m_pRunControl.
     {
       return m_pRunControl->getRunControlName();
     }
State dqm4hep::core::RunControlService::getRunState () const
Get the run state (running or not)
Definition at line 275 of file RunControlService.cc.
References m_pRunControl.
Referenced by endCurrentRun(), and startNewRun().
     {
       return m_pRunControl->getRunState();
     }
State dqm4hep::core::RunControlService::getState () const
Get the service state.
See State enum (DQM4HEP.h)
Definition at line 289 of file RunControlService.cc.
References m_serviceState.
     {
       return m_serviceState;
     }
void dqm4hep::core::RunControlService::handleCurrentRunRpc (DimRpc * pRpc) private
Handle the received rpc to get the current run.
Definition at line 633 of file RunControlService.cc.
References isRunning(), m_pOutBuffer, and m_pRunControl.
Referenced by dqm4hep::core::CurrentRunRpc::rpcHandler().
     {
       if( ! this->isRunning() )
         return;
       try
       {
         // if running send the current run
         // else send back an empty run
         if(m_pRunControl->isRunning())
         {
           // stream
           m_pOutBuffer->reset();
           if( xdrstream::XDR_SUCCESS != m_pRunControl->getCurrentRun()->stream( xdrstream::XDR_WRITE_STREAM , m_pOutBuffer ) )
             throw StatusCodeException(STATUS_CODE_FAILURE);
           // send back current run
           pRpc->setData( (void *) m_pOutBuffer->getBuffer() , m_pOutBuffer->getPosition() );
         }
         else
         {
           Run emptyRun;
           // stream
           m_pOutBuffer->reset();
           if( xdrstream::XDR_SUCCESS != emptyRun.stream( xdrstream::XDR_WRITE_STREAM , m_pOutBuffer ) )
             throw StatusCodeException(STATUS_CODE_FAILURE);
           // send back current run
           pRpc->setData( (void *) m_pOutBuffer->getBuffer() , m_pOutBuffer->getPosition() );
         }
       }
       catch(StatusCodeException &exception)
       {
         LOG4CXX_ERROR( dqmMainLogger , "Couldn't send back current run : " << exception.toString() );
       }
     }
void dqm4hep::core::RunControlService::handleEndCurrentRunRpc (DimRpc * pRpc) private
Handle the received rpc to end the current run.
Definition at line 752 of file RunControlService.cc.
References configureInBuffer(), endCurrentRun(), isRunning(), m_pInBuffer, and m_pRunControl.
Referenced by dqm4hep::core::EndCurrentRunRpc::rpcHandler().
     {
       if( ! this->isRunning() )
         return;
       RpcResponse response;
       response.m_ok = false;
       if( ! m_pRunControl->isRunning() )
       {
         sprintf(response.m_pMessage, "Not running !");
         pRpc->setData( & response , sizeof(RpcResponse) );
         LOG4CXX_ERROR( dqmMainLogger , "Couldn't end current new run : Not running !");
         return;
       }
       try
       {
         char *pBuffer = (char *) pRpc->getData();
         xdrstream::xdr_size_t bufferSize = pRpc->getSize();
         if( NULL == pBuffer || 0 == bufferSize )
         {
           sprintf(response.m_pMessage, "Invalid incoming buffer to stop the current run !");
           pRpc->setData( & response , sizeof(RpcResponse) );
           LOG4CXX_ERROR( dqmMainLogger , "Couldn't end current new run : Invalid incoming buffer !");
           return;
         }
         this->configureInBuffer( pBuffer, bufferSize );
         std::string password;
         if( xdrstream::XDR_SUCCESS != m_pInBuffer->read( &password ) )
         {
           sprintf(response.m_pMessage, "Couldn't read password !");
           pRpc->setData( & response , sizeof(RpcResponse) );
           LOG4CXX_ERROR( dqmMainLogger , "Couldn't end current new run : Couldn't read password !");
           return;
         }
         if( ! m_pRunControl->checkPassword( password ) )
         {
           sprintf(response.m_pMessage, "Invalid password !");
           pRpc->setData( & response , sizeof(RpcResponse) );
           LOG4CXX_ERROR( dqmMainLogger , "Couldn't end current new run : Invalid password !");
           return;
         }
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->endCurrentRun(password));
         response.m_ok = true;
         sprintf(response.m_pMessage, "Stopped !");
         pRpc->setData( & response , sizeof(RpcResponse) );
         LOG4CXX_INFO( dqmMainLogger , "Current run stopped !");
       }
       catch(StatusCodeException &exception)
       {
         sprintf(response.m_pMessage, "Couldn't stop current run ! Invalid operation on server side !");
         pRpc->setData( & response , sizeof(RpcResponse) );
         LOG4CXX_ERROR( dqmMainLogger , "Couldn't stop current run from rpc : " << exception.toString() );
       }
     }
void dqm4hep::core::RunControlService::handleStartNewRunRpc (DimRpc * pRpc) private
Handle the received rpc to start a new run.
Definition at line 675 of file RunControlService.cc.
References configureInBuffer(), getCurrentRun(), isRunning(), m_pInBuffer, m_pRunControl, and startNewRun().
Referenced by dqm4hep::core::StartNewRunRpc::rpcHandler().
     {
       if( ! this->isRunning() )
         return;
       RpcResponse response;
       response.m_ok = false;
       if( m_pRunControl->isRunning() )
       {
         sprintf(response.m_pMessage, "Already running !");
         pRpc->setData( & response , sizeof(RpcResponse) );
         LOG4CXX_ERROR( dqmMainLogger , "Couldn't start a new run : Already running !");
         return;
       }
       try
       {
         char *pBuffer = (char *) pRpc->getData();
         xdrstream::xdr_size_t bufferSize = pRpc->getSize();
         if( NULL == pBuffer || 0 == bufferSize )
         {
           sprintf(response.m_pMessage, "Invalid incoming buffer to start a new run !");
           pRpc->setData( & response , sizeof(RpcResponse) );
           LOG4CXX_ERROR( dqmMainLogger , "Couldn't start a new run : Couldn't decode incoming buffer !");
           return;
         }
         this->configureInBuffer( pBuffer, bufferSize );
         std::string password;
         if( xdrstream::XDR_SUCCESS != m_pInBuffer->read( &password ) )
         {
           sprintf(response.m_pMessage, "Couldn't read password !");
           pRpc->setData( & response , sizeof(RpcResponse) );
           LOG4CXX_ERROR( dqmMainLogger , "Couldn't start a new run : Couldn't decode password !");
           return;
         }
         if( ! m_pRunControl->checkPassword( password ) )
         {
           sprintf(response.m_pMessage, "Invalid password !");
           pRpc->setData( & response , sizeof(RpcResponse) );
           LOG4CXX_ERROR( dqmMainLogger , "Couldn't start a new run : Invalid password !");
           return;
         }
         Run *pRun = new Run();
         if( xdrstream::XDR_SUCCESS != pRun->stream( xdrstream::XDR_READ_STREAM , m_pInBuffer ) )
         {
           delete pRun;
           sprintf(response.m_pMessage, "Couldn't read run info !");
           std::cout << sizeof(RpcResponse) << std::endl;
           pRpc->setData( & response , sizeof(RpcResponse) );
           LOG4CXX_ERROR( dqmMainLogger , "Couldn't start a new run : Couldn't decode incoming run info !");
           return;
         }
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->startNewRun(pRun, password));
         response.m_ok = true;
         sprintf(response.m_pMessage, "Started !");
         pRpc->setData( & response , sizeof(RpcResponse) );
         LOG4CXX_INFO( dqmMainLogger , "Starting new run : \n" << *this->getCurrentRun() );
       }
       catch(StatusCodeException &exception)
       {
         sprintf(response.m_pMessage, "Couldn't start new run ! Invalid operation on server side !");
         pRpc->setData( & response , sizeof(RpcResponse) );
         LOG4CXX_ERROR( dqmMainLogger , "Couldn't start new run from rpc : " << exception.toString() );
       }
     }
bool dqm4hep::core::RunControlService::isRunning () const
Whether the service is running.
Definition at line 282 of file RunControlService.cc.
References m_serviceState.
Referenced by endCurrentRun(), handleCurrentRunRpc(), handleEndCurrentRunRpc(), handleStartNewRunRpc(), restart(), setPassword(), setRunControlName(), start(), startNewRun(), stop(), and ~RunControlService().
     {
       return (m_serviceState == RUNNING_STATE);
     }
StatusCode dqm4hep::core::RunControlService::pause ()
Pause the service until restart is called.
Definition at line 173 of file RunControlService.cc.
References stop().
     {
       return stop();
     }
StatusCode dqm4hep::core::RunControlService::restart ()
Restart the service.
Definition at line 180 of file RunControlService.cc.
References isRunning(), start(), and stop().
     {
       if(isRunning())
       {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, stop());
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, start());
         return STATUS_CODE_SUCCESS;
       }
       else
       {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, start());
         return STATUS_CODE_SUCCESS;
       }
     }
StatusCode dqm4hep::core::RunControlService::setPassword (const std::string & password)
Set the password for this run control service.
Used when a user wants to start a new run using the dedicated RPC
Definition at line 322 of file RunControlService.cc.
References isRunning(), and m_pRunControl.
     {
       if( this->isRunning() )
         return STATUS_CODE_NOT_ALLOWED;
       m_pRunControl->setPassword(password);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::RunControlService::setRunControlName (const std::string & runControlName)
Set the run control name.
Definition at line 296 of file RunControlService.cc.
References isRunning(), and m_pRunControl.
     {
       if(isRunning())
         return STATUS_CODE_NOT_ALLOWED;
       m_pRunControl->setRunControlName(runControlName);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::RunControlService::start ()
Start the service.
Definition at line 131 of file RunControlService.cc.
References CurrentRunRpc, EndCurrentRunRpc, isRunning(), m_pCurrentRunRpc, m_pEndCurrentRunRpc, m_pEndOfRunService, m_pRunControl, m_pStartNewRunRpc, m_pStartOfRunService, m_serviceState, dqm4hep::core::RunControlService_emptyBuffer, and StartNewRunRpc.
Referenced by restart().
     {
       if(isRunning())
         return STATUS_CODE_ALREADY_INITIALIZED;
       std::string sorServiceName = "DQM4HEP/RunControl/" + m_pRunControl->getRunControlName() + "/START_OF_RUN";
       std::string eorServiceName = "DQM4HEP/RunControl/" + m_pRunControl->getRunControlName() + "/END_OF_RUN";
       std::string currentRunRpcName = "DQM4HEP/RunControl/" + m_pRunControl->getRunControlName() + "/CURRENT_RUN";
       std::string startNewRunRpcName = "DQM4HEP/RunControl/" + m_pRunControl->getRunControlName() + "/START_NEW_RUN";
       std::string endCurrentRunRpcName = "DQM4HEP/RunControl/" + m_pRunControl->getRunControlName() + "/END_CURRENT_RUN";
       m_pStartOfRunService = new DimService(sorServiceName.c_str(), "C", (void*) RunControlService_emptyBuffer, 5);
       m_pEndOfRunService   = new DimService(eorServiceName.c_str(), "C", (void*) RunControlService_emptyBuffer, 5);
       m_pCurrentRunRpc = new CurrentRunRpc( (char *) currentRunRpcName.c_str(), this);
       m_pStartNewRunRpc = new StartNewRunRpc( (char *) startNewRunRpcName.c_str(), this);
       m_pEndCurrentRunRpc = new EndCurrentRunRpc( (char *) endCurrentRunRpcName.c_str(), this);
       m_serviceState = RUNNING_STATE;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::RunControlService::startNewRun (unsigned int runNumber, const std::string & description = "", const std::string & detectorName = "", const std::string & password = "")
Create a new run.
End the current run if there is one.
Definition at line 199 of file RunControlService.cc.
References endCurrentRun(), getRunState(), isRunning(), m_currentRunNumber, m_pOutBuffer, m_pRunControl, and m_pStartOfRunService.
Referenced by handleStartNewRunRpc().
     {
       if(!isRunning())
         return STATUS_CODE_NOT_INITIALIZED;
       if(RUNNING_STATE == getRunState())
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, endCurrentRun(password));
       m_currentRunNumber = runNumber;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControl->startNewRun(m_currentRunNumber, description, detectorName, password));
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != m_pRunControl->getCurrentRun()->stream( xdrstream::XDR_WRITE_STREAM , m_pOutBuffer ) )
         return STATUS_CODE_FAILURE;
       m_pStartOfRunService->updateService( (void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition());
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::RunControlService::startNewRun (Run * pRun, const std::string & password = "")
Create a new run.
End the current run if there is one.
Definition at line 222 of file RunControlService.cc.
References endCurrentRun(), getRunState(), isRunning(), m_currentRunNumber, m_pOutBuffer, m_pRunControl, and m_pStartOfRunService.
     {
       if(!isRunning())
         return STATUS_CODE_NOT_INITIALIZED;
       if(RUNNING_STATE == getRunState())
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, endCurrentRun(password));
       m_currentRunNumber = pRun->getRunNumber();
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pRunControl->startNewRun(pRun, password));
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != m_pRunControl->getCurrentRun()->stream( xdrstream::XDR_WRITE_STREAM , m_pOutBuffer ) )
         return STATUS_CODE_FAILURE;
       m_pStartOfRunService->updateService( (void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition());
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::RunControlService::stop ()
Stop the service.
Remove all connections and clean up the service. Use pause to stop the service temporarily.
Definition at line 155 of file RunControlService.cc.
References isRunning(), m_pCurrentRunRpc, m_pEndCurrentRunRpc, m_pEndOfRunService, m_pStartNewRunRpc, m_pStartOfRunService, and m_serviceState.
Referenced by pause(), restart(), and ~RunControlService().
     {
       if(!isRunning())
         return STATUS_CODE_NOT_INITIALIZED;
       delete m_pStartOfRunService;     m_pStartOfRunService = NULL;
       delete m_pEndOfRunService;       m_pEndOfRunService = NULL;
       delete m_pCurrentRunRpc;         m_pCurrentRunRpc = NULL;
       delete m_pStartNewRunRpc;        m_pStartNewRunRpc = NULL;
       delete m_pEndCurrentRunRpc;      m_pEndCurrentRunRpc = NULL;
       m_serviceState = STOPPED_STATE;
       return STATUS_CODE_SUCCESS;
     }
Friends And Related Function Documentation
friend class CurrentRunRpc friend
Definition at line 251 of file RunControlService.h.
Referenced by start().
friend class EndCurrentRunRpc friend
Definition at line 253 of file RunControlService.h.
Referenced by start().
friend class StartNewRunRpc friend
Definition at line 252 of file RunControlService.h.
Referenced by start().
Member Data Documentation
int dqm4hep::core::RunControlService::m_currentRunNumber private
Definition at line 238 of file RunControlService.h.
Referenced by endCurrentRun(), getCurrentRunNumber(), and startNewRun().
DimRpc* dqm4hep::core::RunControlService::m_pCurrentRunRpc private
Definition at line 244 of file RunControlService.h.
Referenced by start(), and stop().
DimRpc* dqm4hep::core::RunControlService::m_pEndCurrentRunRpc private
Definition at line 246 of file RunControlService.h.
Referenced by start(), and stop().
DimService* dqm4hep::core::RunControlService::m_pEndOfRunService private
Definition at line 243 of file RunControlService.h.
Referenced by endCurrentRun(), start(), and stop().
xdrstream::BufferDevice* dqm4hep::core::RunControlService::m_pInBuffer private
Definition at line 248 of file RunControlService.h.
Referenced by configureInBuffer(), handleEndCurrentRunRpc(), handleStartNewRunRpc(), and ~RunControlService().
xdrstream::BufferDevice* dqm4hep::core::RunControlService::m_pOutBuffer private
Definition at line 249 of file RunControlService.h.
Referenced by endCurrentRun(), handleCurrentRunRpc(), RunControlService(), startNewRun(), and ~RunControlService().
RunControl* dqm4hep::core::RunControlService::m_pRunControl private
Definition at line 240 of file RunControlService.h.
Referenced by endCurrentRun(), getCurrentRun(), getRunControlName(), getRunState(), handleCurrentRunRpc(), handleEndCurrentRunRpc(), handleStartNewRunRpc(), RunControlService(), setPassword(), setRunControlName(), start(), startNewRun(), and ~RunControlService().
DimRpc* dqm4hep::core::RunControlService::m_pStartNewRunRpc private
Definition at line 245 of file RunControlService.h.
Referenced by start(), and stop().
DimService* dqm4hep::core::RunControlService::m_pStartOfRunService private
Definition at line 242 of file RunControlService.h.
Referenced by start(), startNewRun(), and stop().
State dqm4hep::core::RunControlService::m_serviceState private
Definition at line 239 of file RunControlService.h.
Referenced by getState(), isRunning(), start(), and stop().
The documentation for this class was generated from the following files:
RunControlService.h
RunControlService.cc