DQMOnline: dqm4hep::core::DimAlertNotifier Class Reference
dqm4hep::core::DimAlertNotifier Class Reference
DimAlertNotifier class.
#include <AlertSystem.h>
Public Member Functions
DimAlertNotifier (const std::string &emitter)
Constructor with emitter name.
~DimAlertNotifier ()
StatusCode startService ()
StatusCode stopService ()
bool isRunning () const
Public Member Functions inherited from dqm4hep::core::AlertNotifier
AlertNotifier (const std::string &emitter)
Constructor with emitter name.
virtual ~AlertNotifier ()
const std::string & getEmitter () const
StatusCode notify (AlertType type, const std::string &message, const MonitorElementPtr &monitorElement=nullptr)
void setMinAlertInterval (int nSeconds)
Protected Member Functions
StatusCode userNotify (AlertType type, const std::string &message, const MonitorElementPtr &monitorElement=nullptr)
Send alert notification to clients.
Private Attributes
DimService * m_pNotificationService
bool m_isRunning
xdrstream::BufferDevice * m_pBuffer
Detailed Description
DimAlertNotifier class.
Definition at line 158 of file AlertSystem.h.
Constructor & Destructor Documentation
dqm4hep::core::DimAlertNotifier::DimAlertNotifier (const std::string & emitter)
Constructor with emitter name.
Definition at line 213 of file AlertSystem.cc.
References m_pBuffer.
                                                                :
         AlertNotifier(emitter),
         m_isRunning(false),
         m_pNotificationService(NULL),
         m_pBuffer(NULL)
     {
       m_pBuffer = new xdrstream::BufferDevice(1024);
     }
dqm4hep::core::DimAlertNotifier::~DimAlertNotifier ()
Definition at line 224 of file AlertSystem.cc.
References m_pBuffer.
     {
       delete m_pBuffer;
     }
Member Function Documentation
bool dqm4hep::core::DimAlertNotifier::isRunning () const virtual
Implements dqm4hep::core::AlertNotifier.
Definition at line 258 of file AlertSystem.cc.
References m_isRunning.
Referenced by startService(), stopService(), and userNotify().
     {
       return m_isRunning;
     }
StatusCode dqm4hep::core::DimAlertNotifier::startService () virtual
Implements dqm4hep::core::AlertNotifier.
Definition at line 231 of file AlertSystem.cc.
References dqm4hep::core::AlertNotifier::getEmitter(), isRunning(), m_isRunning, and m_pNotificationService.
     {
       if( this->isRunning() )
         return STATUS_CODE_SUCCESS;
       std::string serviceName = "DQM4HEP/ALERT/" + this->getEmitter();
       m_pNotificationService = new DimService( serviceName.c_str() , "C" , (void*) DimAlertNotifier_emptyBuffer , 5 );
       m_isRunning = true;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimAlertNotifier::stopService () virtual
Implements dqm4hep::core::AlertNotifier.
Definition at line 245 of file AlertSystem.cc.
References isRunning(), m_isRunning, and m_pNotificationService.
     {
       if( ! this->isRunning() )
         return STATUS_CODE_SUCCESS;
       delete m_pNotificationService;
       m_isRunning = false;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimAlertNotifier::userNotify (AlertType type, const std::string & message, const MonitorElementPtr & monitorElement = nullptr) protected virtual
Send alert notification to clients.
Implements dqm4hep::core::AlertNotifier.
Definition at line 265 of file AlertSystem.cc.
References dqm4hep::core::AlertNotifier::getEmitter(), isRunning(), m_pBuffer, m_pNotificationService, and dqm4hep::core::Alert::stream().
     {
       if( this->isRunning() )
         return STATUS_CODE_NOT_INITIALIZED;
       Alert alert(this->getEmitter(), type, message, monitorElement);
       if( ! XDR_TESTBIT( alert.stream(xdrstream::XDR_WRITE_STREAM, m_pBuffer) , xdrstream::XDR_SUCCESS ) )
         return STATUS_CODE_FAILURE;
       m_pNotificationService->updateService( m_pBuffer->getBuffer() , m_pBuffer->getPosition() );
       return STATUS_CODE_SUCCESS;
     }
Member Data Documentation
bool dqm4hep::core::DimAlertNotifier::m_isRunning private
Definition at line 187 of file AlertSystem.h.
Referenced by isRunning(), startService(), and stopService().
xdrstream::BufferDevice* dqm4hep::core::DimAlertNotifier::m_pBuffer private
Definition at line 188 of file AlertSystem.h.
Referenced by DimAlertNotifier(), userNotify(), and ~DimAlertNotifier().
DimService* dqm4hep::core::DimAlertNotifier::m_pNotificationService private
Definition at line 186 of file AlertSystem.h.
Referenced by startService(), stopService(), and userNotify().
The documentation for this class was generated from the following files:
AlertSystem.h
AlertSystem.cc