DQMOnline: dqm4hep::core::EventCollectorApplication Class Reference
dqm4hep::core::EventCollectorApplication Class Reference
EventCollectorApplication class.
#include <EventCollectorApplication.h>
Public Member Functions
EventCollectorApplication ()
Constructor with collector name.
~EventCollectorApplication ()
Destructor.
StatusCode run ()
Run the application.
StatusCode exit (int returnCode)
Stop the application.
const std::string & getName () const
Get the application name.
const std::string & getType () const
Get the application type.
StatusCode setCollectorName (const std::string &collectorName)
Set the event collector name.
void setEventCollectorImp (EventCollectorImp *pCollectorImp)
Set the event collector implementation.
void setEventStreamer (EventStreamer *pEventStreamer)
Set the event streamer to serialize/deserialize the in/out-coming events.
EventStreamer * getEventStreamer () const
Get the event streamer.
Public Member Functions inherited from dqm4hep::core::Application
virtual ~Application ()
Destructor.
Protected Member Functions
StatusCode readSettings (const std::string &settingsFile="")
No settings to read.
Protected Attributes
bool m_shouldExit
std::string m_type
std::string m_networkName
State m_applicationState
EventCollector * m_pEventCollector
Detailed Description
EventCollectorApplication class.
Definition at line 45 of file EventCollectorApplication.h.
Constructor & Destructor Documentation
dqm4hep::core::EventCollectorApplication::EventCollectorApplication ()
Constructor with collector name.
Definition at line 39 of file EventCollectorApplication.cc.
References m_pEventCollector.
                                                          :
         m_applicationState(STOPPED_STATE),
         m_shouldExit(false),
         m_type("EventCollector"),
         m_pEventCollector(NULL)
     {
       m_pEventCollector = new EventCollector();
     }
dqm4hep::core::EventCollectorApplication::~EventCollectorApplication ()
Destructor.
Definition at line 50 of file EventCollectorApplication.cc.
References dqm4hep::core::EventCollector::isRunning(), m_pEventCollector, and dqm4hep::core::EventCollector::stopCollector().
     {
       if(m_pEventCollector->isRunning())
         m_pEventCollector->stopCollector();
       delete m_pEventCollector;
     }
Member Function Documentation
StatusCode dqm4hep::core::EventCollectorApplication::exit (int returnCode) virtual
Stop the application.
Implements dqm4hep::core::Application.
Definition at line 77 of file EventCollectorApplication.cc.
References m_applicationState, m_pEventCollector, m_shouldExit, and dqm4hep::core::EventCollector::stopCollector().
     {
       if(m_applicationState == STOPPED_STATE)
         return STATUS_CODE_FAILURE;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pEventCollector->stopCollector());
       m_shouldExit = true;
       m_applicationState = STOPPED_STATE;
       StatusCode returnStatusCode;
       if(returnCode >= 0 && returnCode < NUMBER_OF_STATUS_CODES)
         returnStatusCode = static_cast<StatusCode>(returnCode);
       else
         returnStatusCode = STATUS_CODE_FAILURE;
       return returnStatusCode;
     }
EventStreamer * dqm4hep::core::EventCollectorApplication::getEventStreamer () const
Get the event streamer.
Definition at line 137 of file EventCollectorApplication.cc.
References dqm4hep::core::EventCollector::getEventStreamer(), and m_pEventCollector.
     {
       return m_pEventCollector->getEventStreamer();
     }
const std::string & dqm4hep::core::EventCollectorApplication::getName () const virtual
Get the application name.
Implements dqm4hep::core::Application.
Definition at line 99 of file EventCollectorApplication.cc.
References dqm4hep::core::EventCollector::getCollectorName(), and m_pEventCollector.
     {
       return m_pEventCollector->getCollectorName();
     }
const std::string & dqm4hep::core::EventCollectorApplication::getType () const virtual
Get the application type.
Implements dqm4hep::core::Application.
Definition at line 106 of file EventCollectorApplication.cc.
References m_type.
     {
       return m_type;
     }
StatusCode dqm4hep::core::EventCollectorApplication::readSettings (const std::string & settingsFile = "") inline protected virtual
No settings to read.
Implements dqm4hep::core::Application.
Definition at line 91 of file EventCollectorApplication.h.
 { return STATUS_CODE_SUCCESS; }
StatusCode dqm4hep::core::EventCollectorApplication::run () virtual
Run the application.
Implements dqm4hep::core::Application.
Definition at line 60 of file EventCollectorApplication.cc.
References m_applicationState, m_pEventCollector, m_shouldExit, and dqm4hep::core::EventCollector::startCollector().
     {
       if(m_applicationState == RUNNING_STATE)
         return STATUS_CODE_FAILURE;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pEventCollector->startCollector());
       m_applicationState = RUNNING_STATE;
       while( ! m_shouldExit )
         CoreTool::sleep(std::chrono::seconds(1));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::EventCollectorApplication::setCollectorName (const std::string & collectorName)
Set the event collector name.
Definition at line 113 of file EventCollectorApplication.cc.
References m_pEventCollector, and dqm4hep::core::EventCollector::setCollectorName().
     {
       return m_pEventCollector->setCollectorName(collectorName);
     }
void dqm4hep::core::EventCollectorApplication::setEventCollectorImp (EventCollectorImp * pCollectorImp)
Set the event collector implementation.
Definition at line 120 of file EventCollectorApplication.cc.
References m_pEventCollector, and dqm4hep::core::EventCollector::setEventCollectorImp().
     {
       if(NULL == pCollectorImp)
         return;
       m_pEventCollector->setEventCollectorImp(pCollectorImp);
     }
void dqm4hep::core::EventCollectorApplication::setEventStreamer (EventStreamer * pEventStreamer)
Set the event streamer to serialize/deserialize the in/out-coming events.
Definition at line 130 of file EventCollectorApplication.cc.
References m_pEventCollector, and dqm4hep::core::EventCollector::setEventStreamer().
     {
       m_pEventCollector->setEventStreamer(pEventStreamer);
     }
Member Data Documentation
State dqm4hep::core::EventCollectorApplication::m_applicationState protected
Definition at line 96 of file EventCollectorApplication.h.
Referenced by exit(), and run().
std::string dqm4hep::core::EventCollectorApplication::m_networkName protected
Definition at line 95 of file EventCollectorApplication.h.
EventCollector* dqm4hep::core::EventCollectorApplication::m_pEventCollector protected
Definition at line 97 of file EventCollectorApplication.h.
Referenced by EventCollectorApplication(), exit(), getEventStreamer(), getName(), run(), setCollectorName(), setEventCollectorImp(), setEventStreamer(), and ~EventCollectorApplication().
bool dqm4hep::core::EventCollectorApplication::m_shouldExit protected
Definition at line 93 of file EventCollectorApplication.h.
Referenced by exit(), and run().
std::string dqm4hep::core::EventCollectorApplication::m_type protected
Definition at line 94 of file EventCollectorApplication.h.
Referenced by getType().
The documentation for this class was generated from the following files:
EventCollectorApplication.h
EventCollectorApplication.cc