DQMOnline: dqm4hep::core::MonitorElementSender Class Reference
dqm4hep::core::MonitorElementSender Class Reference
MonitorElementSender class.
#include <MonitorElementSender.h>
Public Member Functions
MonitorElementSender (ModuleApplication *pApplication)
Constructor.
~MonitorElementSender ()
Destructor.
StatusCode setCollectorName (const std::string &collectorName)
Set the collector name to which the elements will be sent.
StatusCode sendMonitorElements ()
Send the subscribed monitor element to the collector.
StatusCode connectToService ()
Connect the sender to the collector.
StatusCode disconnectFromService ()
Disconnect the sender to the collector.
bool isConnectedToService () const
Whether the sender is connected to the collector.
Private Types
typedef std::map< std::string,
MonitorElementInfo > MonitorElementInfoMap
Private Member Functions
void infoHandler ()
void addAvailableMonitorElement (const MonitorElementPtr &monitorElement)
void removeAvailableMonitorElement (const std::string &monitorElementName)
void sendAvailableMonitorElementList ()
Private Attributes
ModuleApplication * m_pApplication
The module application that sends elements to the collector.
std::string m_collectorName
The collector name to which the monitor elements will be sent.
xdrstream::BufferDevice * m_pOutBuffer
The xdr buffer used to serialize dim info.
xdrstream::BufferDevice * m_pInBuffer
The xdr buffer used to serialize the monitor elements.
StringSet m_subscribedMeList
The subscribed monitor element list.
MonitorElementInfoMap m_availableMeMap
The available monitor element list.
pthread_mutex_t m_mutex
Mutex to lock unlock on service update.
bool m_sendAvailableMeList
Whether the list of available me has to be re-sent to the collector.
bool m_isConnected
Whether the sender is connected to the collector.
DimUpdatedInfo * m_pSubscribedListInfo
The dim info to receive subscribed me list from collector.
DimUpdatedInfo * m_pCollectorStateInfo
The dim info to receive when the collector state changes.
Friends
class ModuleApi
Detailed Description
MonitorElementSender class.
Definition at line 46 of file MonitorElementSender.h.
Member Typedef Documentation
typedef std::map<std::string, MonitorElementInfo> dqm4hep::core::MonitorElementSender::MonitorElementInfoMap private
Definition at line 96 of file MonitorElementSender.h.
Constructor & Destructor Documentation
dqm4hep::core::MonitorElementSender::MonitorElementSender (ModuleApplication * pApplication)
Constructor.
Definition at line 40 of file MonitorElementSender.cc.
References m_mutex, and m_pOutBuffer.
                                                                               :
         m_pApplication(pApplication),
         m_collectorName("DEFAULT"),
         m_pOutBuffer(0),
         m_pInBuffer(0),
         m_sendAvailableMeList(true),
         m_isConnected(false)
     {
       pthread_mutex_init(&m_mutex, NULL);
       m_pOutBuffer = new xdrstream::BufferDevice(5*1024*1024);
     }
dqm4hep::core::MonitorElementSender::~MonitorElementSender ()
Destructor.
Definition at line 55 of file MonitorElementSender.cc.
References m_mutex, m_pInBuffer, and m_pOutBuffer.
     {
       pthread_mutex_destroy(&m_mutex);
       delete m_pOutBuffer;
       if(m_pInBuffer)
         delete m_pInBuffer;
     }
Member Function Documentation
void dqm4hep::core::MonitorElementSender::addAvailableMonitorElement (const MonitorElementPtr & monitorElement) private
Definition at line 273 of file MonitorElementSender.cc.
References dqm4hep::core::ModuleApplication::getModule(), dqm4hep::core::Module::getName(), m_availableMeMap, m_pApplication, and m_sendAvailableMeList.
Referenced by dqm4hep::core::ModuleApi::bookCharHistogram1D(), dqm4hep::core::ModuleApi::bookCharHistogram2D(), dqm4hep::core::ModuleApi::bookFloat(), dqm4hep::core::ModuleApi::bookInt(), dqm4hep::core::ModuleApi::bookIntHistogram1D(), dqm4hep::core::ModuleApi::bookIntHistogram2D(), dqm4hep::core::ModuleApi::bookIntHistogram3D(), dqm4hep::core::ModuleApi::bookMonitorElement(), dqm4hep::core::ModuleApi::bookObject(), dqm4hep::core::ModuleApi::bookProfile1D(), dqm4hep::core::ModuleApi::bookProfile2D(), dqm4hep::core::ModuleApi::bookRealHistogram1D(), dqm4hep::core::ModuleApi::bookRealHistogram2D(), dqm4hep::core::ModuleApi::bookRealHistogram3D(), dqm4hep::core::ModuleApi::bookShort(), dqm4hep::core::ModuleApi::bookShortHistogram1D(), dqm4hep::core::ModuleApi::bookShortHistogram2D(), and dqm4hep::core::ModuleApi::bookString().
     {
       std::string fullName = ( monitorElement->getPath() + monitorElement->getName() ).getPath();
       if(fullName.at(0) != '/')
         fullName = "/" + fullName;
       // prepare for insert
       MonitorElementInfoMap::value_type insertValue( fullName , MonitorElementInfo() );
       // insert it
       std::pair<MonitorElementInfoMap::iterator, bool> ret = m_availableMeMap.insert(insertValue);
       // return is already present
       if(!ret.second)
         return;
       // fill info
       ret.first->second[Key::MODULE_NAME] = m_pApplication->getModule()->getName();
       ret.first->second[Key::ME_PATH] = monitorElement->getPath().getPath();
       ret.first->second[Key::ME_TYPE] = monitorElementTypeToString(monitorElement->getType());
       ret.first->second[Key::ME_NAME] = monitorElement->getName();
       ret.first->second[Key::ME_DESCRIPTION] = monitorElement->getDescription();
       // for future update on the collector side
       m_sendAvailableMeList = true;
     }
StatusCode dqm4hep::core::MonitorElementSender::connectToService ()
Connect the sender to the collector.
Definition at line 174 of file MonitorElementSender.cc.
References isConnectedToService(), m_collectorName, m_isConnected, m_pCollectorStateInfo, and m_pSubscribedListInfo.
Referenced by dqm4hep::core::AnalysisModuleApplication::stopServices().
     {
       if(this->isConnectedToService())
         return STATUS_CODE_SUCCESS;
       std::string serviceName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/NOTIFY_WATCHED_ME_SVC";
       m_pSubscribedListInfo = new DimUpdatedInfo( (char *) serviceName.c_str() , (void *) 0 , 0 ,  this );
       serviceName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/COLLECTOR_STATE_SVC";
       m_pCollectorStateInfo = new DimUpdatedInfo( (char *) serviceName.c_str(), STOPPED_STATE , this );
       m_isConnected = true;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementSender::disconnectFromService ()
Disconnect the sender to the collector.
Definition at line 192 of file MonitorElementSender.cc.
References isConnectedToService(), m_isConnected, m_pCollectorStateInfo, and m_pSubscribedListInfo.
     {
       if( ! this->isConnectedToService() )
         return STATUS_CODE_SUCCESS;
       delete m_pSubscribedListInfo;
       delete m_pCollectorStateInfo;
       m_isConnected = false;
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::MonitorElementSender::infoHandler () private
Definition at line 214 of file MonitorElementSender.cc.
References m_mutex, m_pCollectorStateInfo, m_pInBuffer, m_pSubscribedListInfo, m_sendAvailableMeList, and m_subscribedMeList.
     {
       DimInfo *pInfo = getInfo();
       LOG4CXX_DEBUG( dqmMainLogger , "Received info : " << pInfo->getName() );
       if(pInfo == m_pSubscribedListInfo)
       {
         dqm_char *pBuffer = (dqm_char *) m_pSubscribedListInfo->getData();
         dqm_uint bufferSize = m_pSubscribedListInfo->getSize();
         if(!pBuffer || bufferSize == 0)
           return;
         if( ! m_pInBuffer )
           m_pInBuffer = new xdrstream::BufferDevice(pBuffer, bufferSize, false);
         else
           m_pInBuffer->setBuffer(pBuffer, bufferSize, false);
         m_pInBuffer->setOwner(false);
         StringVector subscribedMeList;
         if( ! XDR_TESTBIT( StreamingHelper::read( m_pInBuffer , subscribedMeList ) , xdrstream::XDR_SUCCESS ) )
         {
           LOG4CXX_ERROR( dqmMainLogger , "Couldn't read subscribed list" );
           return;
         }
         // update the list
         pthread_mutex_lock(&m_mutex);
         LOG4CXX_INFO( dqmMainLogger , "Received subscribed list size : " << subscribedMeList.size() );
         m_subscribedMeList.clear();
         m_subscribedMeList.insert( subscribedMeList.begin(), subscribedMeList.end() );
         pthread_mutex_unlock(&m_mutex);
       }
       else if(pInfo == m_pCollectorStateInfo)
       {
         if(m_pCollectorStateInfo->getInt() == RUNNING_STATE)
         {
           LOG4CXX_INFO( dqmMainLogger , "Force update available list on next EOC !" );
           pthread_mutex_lock(&m_mutex);
           m_sendAvailableMeList = true;
           pthread_mutex_unlock(&m_mutex);
         }
         else if(m_pCollectorStateInfo->getInt() == STOPPED_STATE)
         {
           LOG4CXX_WARN( dqmMainLogger , "Server is down -> Clearing subscribed me list !" );
           pthread_mutex_lock(&m_mutex);
           m_subscribedMeList.clear();
           pthread_mutex_unlock(&m_mutex);
         }
       }
     }
bool dqm4hep::core::MonitorElementSender::isConnectedToService () const
Whether the sender is connected to the collector.
Definition at line 207 of file MonitorElementSender.cc.
References m_isConnected.
Referenced by connectToService(), disconnectFromService(), setCollectorName(), and dqm4hep::core::AnalysisModuleApplication::stopServices().
     {
       return m_isConnected;
     }
void dqm4hep::core::MonitorElementSender::removeAvailableMonitorElement (const std::string & monitorElementName) private
Definition at line 303 of file MonitorElementSender.cc.
References m_availableMeMap, and m_sendAvailableMeList.
Referenced by dqm4hep::core::ModuleApi::deleteMonitorElement().
     {
       MonitorElementInfoMap::iterator findIter = m_availableMeMap.find(monitorElementName);
       if(findIter == m_availableMeMap.end())
         return;
       // do it baby !
       m_availableMeMap.erase(findIter);
       // for future update on the collector side
       m_sendAvailableMeList = true;
     }
void dqm4hep::core::MonitorElementSender::sendAvailableMonitorElementList () private
Definition at line 319 of file MonitorElementSender.cc.
References dqm4hep::core::ModuleApplication::getModule(), dqm4hep::core::Module::getName(), m_availableMeMap, m_collectorName, m_pApplication, and m_pOutBuffer.
Referenced by sendMonitorElements().
     {
       if(m_availableMeMap.empty())
         return;
       MonitorElementInfoList monitorElementInfoList;
       for(MonitorElementInfoMap::iterator iter = m_availableMeMap.begin(), endIter = m_availableMeMap.end() ;
           endIter != iter ; ++iter)
         monitorElementInfoList.push_back(iter->second);
       try
       {
         m_pOutBuffer->reset();
         // first write the module name
         std::string moduleName = m_pApplication->getModule()->getName();
         if( ! XDR_TESTBIT( xdrstream::XDR_SUCCESS , m_pOutBuffer->write( & moduleName ) ) )
           throw StatusCodeException( STATUS_CODE_FAILURE );
         // write the monitor element info list
         if( ! XDR_TESTBIT( xdrstream::XDR_SUCCESS , StreamingHelper::write( m_pOutBuffer , monitorElementInfoList ) ) )
           throw StatusCodeException( STATUS_CODE_FAILURE );
         // send the packet !
         std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/AVAILABLE_ME_CMD";
         DimClient::sendCommandNB( commandName.c_str() , (void *) m_pOutBuffer->getBuffer() , m_pOutBuffer->getPosition() );
       }
       catch(const StatusCodeException &exception)
       {
         LOG4CXX_ERROR( dqmMainLogger , "Couldn't send available monitor element info list : " << exception.toString() );
       }
     }
StatusCode dqm4hep::core::MonitorElementSender::sendMonitorElements ()
Send the subscribed monitor element to the collector.
Definition at line 82 of file MonitorElementSender.cc.
References dqm4hep::core::ModuleApplication::getModule(), dqm4hep::core::ModuleApi::getMonitorElement(), dqm4hep::core::Module::getName(), m_collectorName, m_mutex, m_pApplication, m_pOutBuffer, m_sendAvailableMeList, m_subscribedMeList, and sendAvailableMonitorElementList().
     {
       if(NULL == m_pApplication)
         return STATUS_CODE_NOT_INITIALIZED;
       if(m_sendAvailableMeList)
       {
         this->sendAvailableMonitorElementList();
         m_sendAvailableMeList = false;
       }
       std::string moduleName = m_pApplication->getModule()->getName();
       // get subscribed me list copy
       pthread_mutex_lock(&m_mutex);
       StringSet subscribedMeList = m_subscribedMeList;
       pthread_mutex_unlock(&m_mutex);
       // if nothing to send, log and return
       if(subscribedMeList.empty())
       {
         LOG4CXX_INFO( dqmMainLogger , "No monitor element sent !" );
         return STATUS_CODE_SUCCESS;
       }
       Publication publication;
       Publication::iterator publicationIter =
           publication.insert(
               Publication::value_type(moduleName, MonitorElementPtrList() ) ).first;
       // build the publication to send
       LOG4CXX_DEBUG( dqmMainLogger , "N subscribed me : " << subscribedMeList.size() );
       for(StringSet::iterator iter = subscribedMeList.begin(), endIter = subscribedMeList.end() ;
           endIter != iter ; ++iter)
       {
         size_t pos = iter->find_last_of('/');
         LOG4CXX_DEBUG( dqmMainLogger , "Full me name : " << *iter );
         LOG4CXX_DEBUG( dqmMainLogger , "Last of / pos : " << pos );
         std::string path;
         std::string meName;
         if(pos == std::string::npos)
         {
           path = "/";
           meName = *iter;
         }
         else
         {
           path = iter->substr(0, pos+1);
           meName = iter->substr(pos+1);
         }
         LOG4CXX_DEBUG( dqmMainLogger ,"Me path : " << path << " , name : " << meName );
         if(path.empty() || meName.empty())
           continue;
         MonitorElementPtr monitorElement = NULL;
         if(STATUS_CODE_SUCCESS !=  ModuleApi::getMonitorElement(m_pApplication->getModule(), path, meName, monitorElement))
           continue;
         publicationIter->second.push_back(monitorElement);
       }
       if(publication.empty())
         return STATUS_CODE_SUCCESS;
       LOG4CXX_INFO( dqmMainLogger , "Number of monitor element sent : " << publicationIter->second.size() );
       // write module name
       if( xdrstream::XDR_SUCCESS != m_pOutBuffer->write( & moduleName ) )
         return STATUS_CODE_FAILURE;
       // stream the whole publication
       m_pOutBuffer->reset();
       if( xdrstream::XDR_SUCCESS != StreamingHelper::write( m_pOutBuffer , publication ) )
         return STATUS_CODE_FAILURE;
       std::string commandName = "DQM4HEP/MonitorElementCollector/" + m_collectorName + "/COLLECT_ME_CMD";
       DimClient::sendCommandNB(commandName.c_str(), (void *) m_pOutBuffer->getBuffer(), m_pOutBuffer->getPosition());
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementSender::setCollectorName (const std::string & collectorName)
Set the collector name to which the elements will be sent.
Definition at line 67 of file MonitorElementSender.cc.
References isConnectedToService(), and m_collectorName.
Referenced by dqm4hep::core::StandaloneModuleApplication::readSettings().
     {
       if(collectorName.empty())
         return STATUS_CODE_INVALID_PARAMETER;
       if(this->isConnectedToService())
         return STATUS_CODE_NOT_ALLOWED;
       m_collectorName = collectorName;
       return STATUS_CODE_SUCCESS;
     }
Friends And Related Function Documentation
friend class ModuleApi friend
Definition at line 48 of file MonitorElementSender.h.
Member Data Documentation
MonitorElementInfoMap dqm4hep::core::MonitorElementSender::m_availableMeMap private
The available monitor element list.
Definition at line 107 of file MonitorElementSender.h.
Referenced by addAvailableMonitorElement(), removeAvailableMonitorElement(), and sendAvailableMonitorElementList().
std::string dqm4hep::core::MonitorElementSender::m_collectorName private
The collector name to which the monitor elements will be sent.
Definition at line 100 of file MonitorElementSender.h.
Referenced by connectToService(), sendAvailableMonitorElementList(), sendMonitorElements(), and setCollectorName().
bool dqm4hep::core::MonitorElementSender::m_isConnected private
Whether the sender is connected to the collector.
Definition at line 110 of file MonitorElementSender.h.
Referenced by connectToService(), disconnectFromService(), and isConnectedToService().
pthread_mutex_t dqm4hep::core::MonitorElementSender::m_mutex private
Mutex to lock unlock on service update.
Definition at line 108 of file MonitorElementSender.h.
Referenced by infoHandler(), MonitorElementSender(), sendMonitorElements(), and ~MonitorElementSender().
ModuleApplication* dqm4hep::core::MonitorElementSender::m_pApplication private
The module application that sends elements to the collector.
Definition at line 99 of file MonitorElementSender.h.
Referenced by addAvailableMonitorElement(), sendAvailableMonitorElementList(), and sendMonitorElements().
DimUpdatedInfo* dqm4hep::core::MonitorElementSender::m_pCollectorStateInfo private
The dim info to receive when the collector state changes.
Definition at line 113 of file MonitorElementSender.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
xdrstream::BufferDevice* dqm4hep::core::MonitorElementSender::m_pInBuffer private
The xdr buffer used to serialize the monitor elements.
Definition at line 103 of file MonitorElementSender.h.
Referenced by infoHandler(), and ~MonitorElementSender().
xdrstream::BufferDevice* dqm4hep::core::MonitorElementSender::m_pOutBuffer private
The xdr buffer used to serialize dim info.
Definition at line 102 of file MonitorElementSender.h.
Referenced by MonitorElementSender(), sendAvailableMonitorElementList(), sendMonitorElements(), and ~MonitorElementSender().
DimUpdatedInfo* dqm4hep::core::MonitorElementSender::m_pSubscribedListInfo private
The dim info to receive subscribed me list from collector.
Definition at line 112 of file MonitorElementSender.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
bool dqm4hep::core::MonitorElementSender::m_sendAvailableMeList private
Whether the list of available me has to be re-sent to the collector.
Definition at line 109 of file MonitorElementSender.h.
Referenced by addAvailableMonitorElement(), infoHandler(), removeAvailableMonitorElement(), and sendMonitorElements().
StringSet dqm4hep::core::MonitorElementSender::m_subscribedMeList private
The subscribed monitor element list.
Definition at line 106 of file MonitorElementSender.h.
Referenced by infoHandler(), and sendMonitorElements().
The documentation for this class was generated from the following files:
MonitorElementSender.h
MonitorElementSender.cc