DQMOnline: dqm4hep::online::AppTimer Class Reference
dqm4hep::online::AppTimer Class Reference
AppTimer class.
#include <AppTimer.h>
Public Member Functions
AppTimer (AppEventLoop &loop)
Constructor.
~AppTimer ()
Destructor.
void setSingleShot (bool single)
Set whether the timer is a single shot timer.
bool singleShot () const
Whether the timer is single shot.
void setInterval (unsigned int msec)
Set the timer interval (unit milliseconds)
unsigned int interval () const
Get the timer interval (unit milliseconds)
core::Signal< void > & onTimeout ()
Get the timeout signal.
void start ()
Start the timer.
void stop ()
Stop the timer.
bool active () const
Whether the timer is active.
Private Attributes
AppEventLoop & m_eventLoop
The application event loop.
std::atomic_bool m_singleShot = {true}
Whether the timer is single shot.
std::atomic_uint m_interval = {0}
The timer interval (unit milliseconds)
core::Signal< void > m_signal = {}
The timer timeout signal.
std::atomic_bool m_active = {false}
Whether the timer is active.
core::TimePoint m_startTime = {}
The time point when the timer was started.
Friends
class AppEventLoop
Detailed Description
AppTimer class.
Definition at line 47 of file AppTimer.h.
Constructor & Destructor Documentation
dqm4hep::online::AppTimer::AppTimer (AppEventLoop & loop)
Constructor.
Definition at line 36 of file AppTimer.cc.
                                          :
       m_eventLoop(loop) {
     }
dqm4hep::online::AppTimer::~AppTimer ()
Destructor.
Definition at line 42 of file AppTimer.cc.
{
     }
Member Function Documentation
bool dqm4hep::online::AppTimer::active () const
Whether the timer is active.
Definition at line 90 of file AppTimer.cc.
References m_active.
{
       return m_active.load();
     }
unsigned int dqm4hep::online::AppTimer::interval () const
Get the timer interval (unit milliseconds)
Definition at line 66 of file AppTimer.cc.
References m_interval.
{
       return m_interval.load();
     }
core::Signal< void > & dqm4hep::online::AppTimer::onTimeout ()
Get the timeout signal.
Definition at line 72 of file AppTimer.cc.
References m_signal.
Referenced by dqm4hep::online::Application::exec(), dqm4hep::online::EventCollector::onInit(), and dqm4hep::online::ModuleApplication::onInit().
{
       return m_signal;
     }
void dqm4hep::online::AppTimer::setInterval (unsigned int msec)
Set the timer interval (unit milliseconds)
Parameters
msec the timer interval (unit milliseconds)
Definition at line 59 of file AppTimer.cc.
References m_eventLoop, m_interval, and dqm4hep::online::AppEventLoop::startTimer().
Referenced by dqm4hep::online::Application::exec(), dqm4hep::online::EventCollector::onInit(), and dqm4hep::online::ModuleApplication::onInit().
{
       m_interval = msec;
       m_eventLoop.startTimer(this);
     }
void dqm4hep::online::AppTimer::setSingleShot (bool single)
Set whether the timer is a single shot timer.
After the timer reaches the timeout, if the timer is not single shot, it is automatically restarted
Parameters
single whether the timer is single shot
Definition at line 47 of file AppTimer.cc.
References m_singleShot.
Referenced by dqm4hep::online::Application::exec(), dqm4hep::online::EventCollector::onInit(), and dqm4hep::online::ModuleApplication::onInit().
{
       m_singleShot = single;
     }
bool dqm4hep::online::AppTimer::singleShot () const
Whether the timer is single shot.
Definition at line 53 of file AppTimer.cc.
References m_singleShot.
{
       return m_singleShot.load();
     }
void dqm4hep::online::AppTimer::start ()
Start the timer.
Definition at line 78 of file AppTimer.cc.
References m_eventLoop, and dqm4hep::online::AppEventLoop::startTimer().
Referenced by dqm4hep::online::Application::exec(), dqm4hep::online::ModuleApplication::onEvent(), dqm4hep::online::EventCollector::onInit(), and dqm4hep::online::ModuleApplication::onStart().
{
       m_eventLoop.startTimer(this);
     }
void dqm4hep::online::AppTimer::stop ()
Stop the timer.
Definition at line 84 of file AppTimer.cc.
References m_eventLoop, and dqm4hep::online::AppEventLoop::stopTimer().
Referenced by dqm4hep::online::ModuleApplication::onStop().
{
       m_eventLoop.stopTimer(this);
     }
Friends And Related Function Documentation
friend class AppEventLoop friend
Definition at line 48 of file AppTimer.h.
Member Data Documentation
std::atomic_bool dqm4hep::online::AppTimer::m_active = {false} private
Whether the timer is active.
Definition at line 116 of file AppTimer.h.
Referenced by active(), and dqm4hep::online::AppEventLoop::startTimer().
AppEventLoop& dqm4hep::online::AppTimer::m_eventLoop private
The application event loop.
Definition at line 108 of file AppTimer.h.
Referenced by setInterval(), start(), and stop().
std::atomic_uint dqm4hep::online::AppTimer::m_interval = {0} private
The timer interval (unit milliseconds)
Definition at line 112 of file AppTimer.h.
Referenced by interval(), and setInterval().
core::Signal<void> dqm4hep::online::AppTimer::m_signal = {} private
The timer timeout signal.
Definition at line 114 of file AppTimer.h.
Referenced by onTimeout().
std::atomic_bool dqm4hep::online::AppTimer::m_singleShot = {true} private
Whether the timer is single shot.
Definition at line 110 of file AppTimer.h.
Referenced by setSingleShot(), and singleShot().
core::TimePoint dqm4hep::online::AppTimer::m_startTime = {} private
The time point when the timer was started.
Definition at line 118 of file AppTimer.h.
Referenced by dqm4hep::online::AppEventLoop::startTimer().
The documentation for this class was generated from the following files:
AppTimer.h
AppTimer.cc