DQMOnline: dqm4hep::core::ModuleApi Class Reference
dqm4hep::core::ModuleApi Class Reference
ModuleApi class.
#include <ModuleApi.h>
Static Public Member Functions
static void cd (const Module *const pModule)
Go back to root directory.
static StatusCode cd (const Module *const pModule, const std::string &dirName)
Go to directory 'dirName'.
static StatusCode mkdir (const Module *const pModule, const std::string &dirName)
Create the directory 'dirName'.
static void ls (const Module *const pModule, bool recursive=false)
List the current directory content.
static const std::string & pwd (const Module *const pModule)
Get the current directory name.
static StatusCode goUp (const Module *const pModule)
Navigate backward in the directory structure.
static StatusCode rmdir (const Module *const pModule, const std::string &dirName)
Remove the directory 'dirName'.
static bool dirExists (const Module *const pModule, const std::string &dirName)
Whether the directory exists.
static StatusCode bookRealHistogram1D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D float histogram.
static StatusCode bookIntHistogram1D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D integer histogram.
static StatusCode bookCharHistogram1D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D char histogram.
static StatusCode bookShortHistogram1D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D short histogram.
static StatusCode bookRealHistogram2D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D float histogram.
static StatusCode bookIntHistogram2D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D integer histogram.
static StatusCode bookCharHistogram2D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D char histogram.
static StatusCode bookShortHistogram2D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D short histogram.
static StatusCode bookRealHistogram3D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, int nZBins, float zMin, float zMax)
Book a 3D real histogram.
static StatusCode bookIntHistogram3D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, int nZBins, float zMin, float zMax)
Book a 3D int histogram.
static StatusCode bookProfile1D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, float yMin, float yMax)
Book a 1D profile.
static StatusCode bookProfile2D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax)
Book a 2D profile.
static StatusCode bookInt (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, const int &value)
Book an integer scalar element.
static StatusCode bookFloat (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, const float &value)
Book a float scalar element.
static StatusCode bookShort (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, const short &value)
Book a short scalar element.
static StatusCode bookString (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, const std::string &value)
Book a std::string scalar element.
template<typename ObjectType , typename... Args>
static StatusCode bookObject (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &name, const std::string &title, allocator_helper< TObject, ObjectType, Args...> allocator, Args...args)
Book a generic TObject.
static StatusCode bookRealHistogram1D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D float histogram.
static StatusCode bookIntHistogram1D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D integer histogram.
static StatusCode bookCharHistogram1D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D char histogram.
static StatusCode bookShortHistogram1D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nBins, float minimum, float maximum)
Book a 1D short histogram.
static StatusCode bookRealHistogram2D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D float histogram.
static StatusCode bookIntHistogram2D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D integer histogram.
static StatusCode bookCharHistogram2D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D char histogram.
static StatusCode bookShortHistogram2D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax)
Book a 2D short histogram.
static StatusCode bookRealHistogram3D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, int nZBins, float zMin, float zMax)
Book a 3D real histogram.
static StatusCode bookIntHistogram3D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, int nZBins, float zMin, float zMax)
Book a 3D int histogram.
static StatusCode bookProfile1D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, float yMin, float yMax)
Book a 1D profile.
static StatusCode bookProfile2D (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax)
Book a 2D profile.
static StatusCode bookInt (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, const int &value)
Book an integer scalar element.
static StatusCode bookFloat (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, const float &value)
Book a float scalar element.
static StatusCode bookShort (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, const short &value)
Book a short scalar element.
static StatusCode bookString (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, const std::string &value)
Book a std::string scalar element.
template<typename ObjectType , typename... Args>
static StatusCode bookObject (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &directory, const std::string &name, const std::string &title, allocator_helper< TObject, ObjectType, Args...> allocator, Args...args)
Book a generic TObject.
static StatusCode getAllMonitorElements (const Module *const pModule, MonitorElementPtrList &monitorElementList)
Get all the monitor elements already booked by this module in all the directories.
static StatusCode getMonitorElement (const Module *const pModule, const std::string &monitorElementName, MonitorElementPtr &monitorElement)
Get the monitor element in the current directory (result by ptr reference)
static StatusCode getMonitorElement (const Module *const pModule, const std::string &dirName, const std::string &monitorElementName, MonitorElementPtr &monitorElement)
Get the monitor element in the given directory (result by ptr reference)
static MonitorElementPtr getMonitorElement (const Module *const pModule, const std::string &monitorElementName)
Get the monitor element in the current directory.
static MonitorElementPtr getMonitorElement (const Module *const pModule, const std::string &dirName, const std::string &monitorElementName)
Get the monitor element in the given directory.
static StatusCode deleteMonitorElement (const Module *const pModule, MonitorElementPtr &monitorElement)
Delete the monitor element (by element ptr)
static StatusCode registerQualityTestFactory (const Module *const pModule, const std::string &qualityTestFactoryName, const QualityTestFactory *const pQualityTestFactory)
Register a new quality test factory.
static StatusCode createQualityTest (const Module *const pModule, TiXmlElement *const pXmlElement)
Create a quality test from the xml element.
static StatusCode addQualityTest (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &qualityTestName)
Add a quality test to a given monitor element.
static StatusCode runQualityTests (const Module *const pModule, MonitorElementPtr &monitorElement)
Run all the quality test attached to this monitor element.
static StatusCode runQualityTest (const Module *const pModule, MonitorElementPtr &monitorElement, const std::string &qualityTestName)
Run a specific quality test attached to this monitor element.
static StatusCode runQualityTests (const Module *const pModule)
Run all the quality test of all the monitor elements of this module.
static StatusCode sendAlert (const Module *const pModule, AlertType type, const std::string &message)
Send an alert to all listeners - type and message.
static StatusCode sendAlert (const Module *const pModule, AlertType type, const std::string &message, const MonitorElementPtr &monitorElement)
Send an alert to all listeners - type, message and monitor element.
static StatusCode resetMonitorElements (const Module *const pModule, ResetPolicy policy)
Reset all the monitor elements that have the given reset policy.
static StatusCode resetMonitorElements (const Module *const pModule)
Reset all the monitor elements of this module.
static StatusCode getTimeSinceStartOfRun (const AnalysisModule *const pModule, TimeDuration &duration)
Archive the current state of this module.
static StatusCode getTimeSinceStartOfCycle (const AnalysisModule *const pModule, TimeDuration &duration)
Get the elapsed time since start of current cycle.
Static Private Member Functions
static StatusCode bookMonitorElement (const Module *const pModule, const TiXmlElement *const pXmlElement, const std::string &meName, MonitorElementPtr &monitorElement)
Book a monitor element from the xml element.
static StatusCode bookMonitorElement (const Module *const pModule, const TiXmlElement *const pXmlElement, MonitorElementPtr &monitorElement, const ParameterMap &parameters)
Book a monitor element from the xml element.
Friends
class XmlHelper
Detailed Description
ModuleApi class.
Responsible for direct operation on module application and modules such as monitor element booking and directory navigation. Monitor element booking should be done via a Module.
Example :
MonitorElement *pMyRealHistogram1DElement = NULL;
ModuleApi::bookRealHistogram1D(this, pMyRealHistogram1DElement, "MyHisto", "My histo title", 10, 1, 10);
Definition at line 62 of file ModuleApi.h.
Member Function Documentation
StatusCode dqm4hep::core::ModuleApi::addQualityTest (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & qualityTestName) static
Add a quality test to a given monitor element.
The quality test must have been registered in the framework before calling this method.
Definition at line 619 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->addQualityTest(monitorElement, qualityTestName);
     }
StatusCode dqm4hep::core::ModuleApi::bookCharHistogram1D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) static
Book a 1D char histogram.
The histogram is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 129 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           CHAR_HISTOGRAM_1D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TH1CAllocator(), nBins, minimum, maximum));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookCharHistogram1D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) static
Book a 1D char histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 340 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           CHAR_HISTOGRAM_1D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TH1CAllocator(), nBins, minimum, maximum));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookCharHistogram2D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) static
Book a 2D char histogram.
The histogram is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 181 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           CHAR_HISTOGRAM_2D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TH2CAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookCharHistogram2D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) static
Book a 2D char histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 392 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           CHAR_HISTOGRAM_2D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TH2CAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookFloat (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, const float & value) static
Book a float scalar element.
The scalar is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 279 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookObject(monitorElement,
           REAL_ELEMENT_TYPE, ".", name, title, pModule->getName(), TScalarFloatAllocator(), value));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookFloat (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, const float & value) static
Book a float scalar element.
The scalar is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 490 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookObject(monitorElement,
           REAL_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TScalarFloatAllocator(), value));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookInt (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, const int & value) static
Book an integer scalar element.
The scalar is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 267 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookObject(monitorElement,
           INT_ELEMENT_TYPE, ".", name, title, pModule->getName(), TScalarIntAllocator(), value));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookInt (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, const int & value) static
Book an integer scalar element.
The scalar is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 478 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookObject(monitorElement,
           INT_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TScalarIntAllocator(), value));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookIntHistogram1D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) static
Book a 1D integer histogram.
The histogram is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 117 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           INT_HISTOGRAM_1D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TH1IAllocator(), nBins, minimum, maximum));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookIntHistogram1D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) static
Book a 1D integer histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 328 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           INT_HISTOGRAM_1D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TH1IAllocator(), nBins, minimum, maximum));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookIntHistogram2D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) static
Book a 2D integer histogram.
The histogram is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 167 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           INT_HISTOGRAM_2D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TH2IAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookIntHistogram2D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) static
Book a 2D integer histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 378 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           INT_HISTOGRAM_2D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TH2IAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookIntHistogram3D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, int nZBins, float zMin, float zMax) static
Book a 3D int histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 224 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           INT_HISTOGRAM_3D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TH3IAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax, nZBins, zMin, zMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookIntHistogram3D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, int nZBins, float zMin, float zMax) static
Book a 3D int histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 435 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           INT_HISTOGRAM_3D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TH3IAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax, nZBins, zMin, zMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookMonitorElement (const Module *const pModule, const TiXmlElement *const pXmlElement, const std::string & meName, MonitorElementPtr & monitorElement) static private
Book a monitor element from the xml element.
Definition at line 685 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookMonitorElement(pXmlElement, pModule->getName(), meName, monitorElement));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookMonitorElement (const Module *const pModule, const TiXmlElement *const pXmlElement, MonitorElementPtr & monitorElement, const ParameterMap & parameters) static private
Book a monitor element from the xml element.
Definition at line 696 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookMonitorElement(pXmlElement, pModule->getName(), monitorElement, parameters));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
template<typename ObjectType , typename... Args> StatusCode dqm4hep::core::ModuleApi::bookObject (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, allocator_helper< TObject, ObjectType, Args...> allocator, Args... args) inline static
Book a generic TObject.
The class name must be a valid built-in ROOT one or a user defined class inheriting from TObject and providing a dictionary.
Definition at line 476 of file ModuleApi.h.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookObject(monitorElement,
           USER_DEFINED_ELEMENT_TYPE, ".", name, title, pModule->getName(), allocator, args...));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
template<typename ObjectType , typename... Args> StatusCode dqm4hep::core::ModuleApi::bookObject (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, allocator_helper< TObject, ObjectType, Args...> allocator, Args... args) inline static
Book a generic TObject.
The class name must be a valid built-in ROOT one or a user defined class inheriting from TObject and providing a dictionary.
Definition at line 490 of file ModuleApi.h.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookObject(monitorElement,
           USER_DEFINED_ELEMENT_TYPE, dirName, name, title, pModule->getName(), allocator, args...));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookProfile1D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, float yMin, float yMax) static
Book a 1D profile.
The profile is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 239 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           PROFILE_1D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TProfileAllocator(), nXBins, xMin, xMax, yMin, yMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookProfile1D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, float yMin, float yMax) static
Book a 1D profile.
The profile is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 450 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           PROFILE_1D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TProfileAllocator(), nXBins, xMin, xMax, yMin, yMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookProfile2D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax) static
Book a 2D profile.
The profile is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 252 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           PROFILE_2D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TProfile2DAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax, zMin, zMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookProfile2D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, float zMin, float zMax) static
Book a 2D profile.
The profile is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 463 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           PROFILE_2D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TProfile2DAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax, zMin, zMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookRealHistogram1D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) static
Book a 1D float histogram.
The histogram is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 105 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           REAL_HISTOGRAM_1D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TH1FAllocator(), nBins, minimum, maximum));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookRealHistogram1D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) static
Book a 1D float histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 316 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           REAL_HISTOGRAM_1D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TH1FAllocator(), nBins, minimum, maximum));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookRealHistogram2D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) static
Book a 2D float histogram.
The histogram is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 153 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           REAL_HISTOGRAM_2D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TH2FAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookRealHistogram2D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) static
Book a 2D float histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 364 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           REAL_HISTOGRAM_2D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TH2FAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookRealHistogram3D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, int nZBins, float zMin, float zMax) static
Book a 3D real histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 209 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           REAL_HISTOGRAM_3D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TH3FAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax, nZBins, zMin, zMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookRealHistogram3D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax, int nZBins, float zMin, float zMax) static
Book a 3D real histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 420 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           REAL_HISTOGRAM_3D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TH3FAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax, nZBins, zMin, zMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookShort (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, const short & value) static
Book a short scalar element.
The scalar is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 291 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookObject(monitorElement,
           SHORT_ELEMENT_TYPE, ".", name, title, pModule->getName(), TScalarShortAllocator(), value));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookShort (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, const short & value) static
Book a short scalar element.
The scalar is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 502 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookObject(monitorElement,
           SHORT_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TScalarShortAllocator(), value));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookShortHistogram1D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) static
Book a 1D short histogram.
The histogram is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 141 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           SHORT_HISTOGRAM_1D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TH1SAllocator(), nBins, minimum, maximum));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookShortHistogram1D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nBins, float minimum, float maximum) static
Book a 1D short histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 352 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           SHORT_HISTOGRAM_1D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TH1SAllocator(), nBins, minimum, maximum));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookShortHistogram2D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) static
Book a 2D short histogram.
The histogram is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 195 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           SHORT_HISTOGRAM_2D_ELEMENT_TYPE, ".", name, title, pModule->getName(), TH2SAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookShortHistogram2D (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, int nXBins, float xMin, float xMax, int nYBins, float yMin, float yMax) static
Book a 2D short histogram.
The histogram is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 406 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookHistogram(monitorElement,
           SHORT_HISTOGRAM_2D_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TH2SAllocator(), nXBins, xMin, xMax, nYBins, yMin, yMax));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookString (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & name, const std::string & title, const std::string & value) static
Book a std::string scalar element.
The scalar is encapsulated in the MonitorElement and added to monitor element list of the module. Such a function should be used in Module implementation by passing 'this' as first argument
Definition at line 303 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookObject(monitorElement,
           STRING_ELEMENT_TYPE, ".", name, title, pModule->getName(), TScalarStringAllocator(), value));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::ModuleApi::bookString (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & directory, const std::string & name, const std::string & title, const std::string & value) static
Book a std::string scalar element.
The scalar is encapsulated in the MonitorElement Such a function should be used in Module implementation
Definition at line 514 of file ModuleApi.cc.
References dqm4hep::core::MonitorElementSender::addAvailableMonitorElement(), dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::Module::getName().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->bookObject(monitorElement,
           STRING_ELEMENT_TYPE, dirName, name, title, pModule->getName(), TScalarStringAllocator(), value));
       pModule->getModuleApplication()->getMonitorElementSender()->addAvailableMonitorElement(monitorElement);
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::ModuleApi::cd (const Module *const pModule) static
Go back to root directory.
Definition at line 48 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       pModule->getModuleApplication()->getMonitorElementManager()->cd();
     }
StatusCode dqm4hep::core::ModuleApi::cd (const Module *const pModule, const std::string & dirName) static
Go to directory 'dirName'.
Definition at line 55 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->cd(dirName);
     }
StatusCode dqm4hep::core::ModuleApi::createQualityTest (const Module *const pModule, TiXmlElement *const pXmlElement) static
Create a quality test from the xml element.
The xml element must contain the attribute 'type' and 'name'
Definition at line 612 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->createQualityTest(pXmlElement);
     }
StatusCode dqm4hep::core::ModuleApi::deleteMonitorElement (const Module *const pModule, MonitorElementPtr & monitorElement) static
Delete the monitor element (by element ptr)
Definition at line 563 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), dqm4hep::core::ModuleApplication::getMonitorElementManager(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), and dqm4hep::core::MonitorElementSender::removeAvailableMonitorElement().
     {
       std::string fullName = (monitorElement->getPath() + monitorElement->getName()).getPath();
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pModule->getModuleApplication()->getMonitorElementManager()->deleteMonitorElement(monitorElement));
       pModule->getModuleApplication()->getMonitorElementSender()->removeAvailableMonitorElement(fullName);
       return STATUS_CODE_SUCCESS;
     }
bool dqm4hep::core::ModuleApi::dirExists (const Module *const pModule, const std::string & dirName) static
Whether the directory exists.
Definition at line 97 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->dirExists(dirName);
     }
StatusCode dqm4hep::core::ModuleApi::getAllMonitorElements (const Module *const pModule, MonitorElementPtrList & monitorElementList) static
Get all the monitor elements already booked by this module in all the directories.
Definition at line 527 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->getAllMonitorElements(monitorElementList);
     }
StatusCode dqm4hep::core::ModuleApi::getMonitorElement (const Module *const pModule, const std::string & monitorElementName, MonitorElementPtr & monitorElement) static
Get the monitor element in the current directory (result by ptr reference)
Definition at line 534 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
Referenced by dqm4hep::core::MonitorElementSender::sendMonitorElements().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->getMonitorElement(monitorElementName, monitorElement);
     }
StatusCode dqm4hep::core::ModuleApi::getMonitorElement (const Module *const pModule, const std::string & dirName, const std::string & monitorElementName, MonitorElementPtr & monitorElement) static
Get the monitor element in the given directory (result by ptr reference)
Definition at line 541 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->getMonitorElement(dirName, monitorElementName, monitorElement);
     }
MonitorElementPtr dqm4hep::core::ModuleApi::getMonitorElement (const Module *const pModule, const std::string & monitorElementName) static
Get the monitor element in the current directory.
The element is directly returned without any ptr check
Definition at line 548 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->getMonitorElement(monitorElementName);
     }
MonitorElementPtr dqm4hep::core::ModuleApi::getMonitorElement (const Module *const pModule, const std::string & dirName, const std::string & monitorElementName) static
Get the monitor element in the given directory.
The element is directly returned without any ptr check
Definition at line 555 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->getMonitorElement(dirName, monitorElementName);
     }
StatusCode dqm4hep::core::ModuleApi::getTimeSinceStartOfCycle (const AnalysisModule *const pModule, TimeDuration & duration) static
Get the elapsed time since start of current cycle.
Valid only within cycle
Definition at line 666 of file ModuleApi.cc.
References dqm4hep::core::AnalysisModuleApplication::getCycle(), and dqm4hep::core::Cycle::getStartTime().
     {
       AnalysisModuleApplication *pApplication = dynamic_cast<AnalysisModuleApplication *>(pModule->getModuleApplication());
       if( ! pApplication )
         return STATUS_CODE_INVALID_PARAMETER;
       Cycle *pCycle = pApplication->getCycle();
       if( ! pCycle )
         return STATUS_CODE_FAILURE;
       duration = pCycle->getStartTime() - CoreTool::now();
       return STATUS_CODE_FAILURE;
     }
StatusCode dqm4hep::core::ModuleApi::getTimeSinceStartOfRun (const AnalysisModule *const pModule, TimeDuration & duration) static
Archive the current state of this module.
Simply write the directory structure with the monitor elements in a root fileGet the elapsed time since start of current run. Valid only within run
Definition at line 647 of file ModuleApi.cc.
References dqm4hep::core::AnalysisModuleApplication::getCurrentRun().
     {
       AnalysisModuleApplication *pApplication = dynamic_cast<AnalysisModuleApplication *>(pModule->getModuleApplication());
       if( ! pApplication )
         return STATUS_CODE_INVALID_PARAMETER;
       Run *pRun = pApplication->getCurrentRun();
       if( ! pRun )
         return STATUS_CODE_FAILURE;
       duration = pRun->getStartTime() - CoreTool::now();
       return STATUS_CODE_FAILURE;
     }
StatusCode dqm4hep::core::ModuleApi::goUp (const Module *const pModule) static
Navigate backward in the directory structure.
Definition at line 83 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->goUp();
     }
void dqm4hep::core::ModuleApi::ls (const Module *const pModule, bool recursive = false) static
List the current directory content.
Definition at line 69 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       pModule->getModuleApplication()->getMonitorElementManager()->ls(recursive);
     }
StatusCode dqm4hep::core::ModuleApi::mkdir (const Module *const pModule, const std::string & dirName) static
Create the directory 'dirName'.
Definition at line 62 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->mkdir(dirName);
     }
const std::string & dqm4hep::core::ModuleApi::pwd (const Module *const pModule) static
Get the current directory name.
Definition at line 76 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->pwd();
     }
StatusCode dqm4hep::core::ModuleApi::registerQualityTestFactory (const Module *const pModule, const std::string & qualityTestFactoryName, const QualityTestFactory *const pQualityTestFactory) static
Register a new quality test factory.
Must be called while reading module settings and before calling ModuleApi::createQualityTest()
Definition at line 605 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->registerQualityTestFactory(qualityTestFactoryName, pQualityTestFactory);
     }
StatusCode dqm4hep::core::ModuleApi::resetMonitorElements (const Module *const pModule, ResetPolicy policy) static
Reset all the monitor elements that have the given reset policy.
Definition at line 590 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->resetMonitorElements(policy);
     }
StatusCode dqm4hep::core::ModuleApi::resetMonitorElements (const Module *const pModule) static
Reset all the monitor elements of this module.
Definition at line 597 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->resetMonitorElements();
     }
StatusCode dqm4hep::core::ModuleApi::rmdir (const Module *const pModule, const std::string & dirName) static
Remove the directory 'dirName'.
Definition at line 90 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->rmdir(dirName);
     }
StatusCode dqm4hep::core::ModuleApi::runQualityTest (const Module *const pModule, MonitorElementPtr & monitorElement, const std::string & qualityTestName) static
Run a specific quality test attached to this monitor element.
Definition at line 633 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->runQualityTest(monitorElement, qualityTestName);
     }
StatusCode dqm4hep::core::ModuleApi::runQualityTests (const Module *const pModule, MonitorElementPtr & monitorElement) static
Run all the quality test attached to this monitor element.
Definition at line 626 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->runQualityTests(monitorElement);
     }
StatusCode dqm4hep::core::ModuleApi::runQualityTests (const Module *const pModule) static
Run all the quality test of all the monitor elements of this module.
Definition at line 640 of file ModuleApi.cc.
References dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::ModuleApplication::getMonitorElementManager().
     {
       return pModule->getModuleApplication()->getMonitorElementManager()->runQualityTests();
     }
StatusCode dqm4hep::core::ModuleApi::sendAlert (const Module *const pModule, AlertType type, const std::string & message) static
Send an alert to all listeners - type and message.
Definition at line 575 of file ModuleApi.cc.
References dqm4hep::core::ModuleApplication::getAlertNotifier(), dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::AlertNotifier::notify().
     {
       return pModule->getModuleApplication()->getAlertNotifier()->notify(type, message);
     }
StatusCode dqm4hep::core::ModuleApi::sendAlert (const Module *const pModule, AlertType type, const std::string & message, const MonitorElementPtr & monitorElement) static
Send an alert to all listeners - type, message and monitor element.
Definition at line 582 of file ModuleApi.cc.
References dqm4hep::core::ModuleApplication::getAlertNotifier(), dqm4hep::core::Module::getModuleApplication(), and dqm4hep::core::AlertNotifier::notify().
     {
       return pModule->getModuleApplication()->getAlertNotifier()->notify(type, message, monitorElement);
     }
Friends And Related Function Documentation
friend class XmlHelper friend
Definition at line 470 of file ModuleApi.h.
The documentation for this class was generated from the following files:
ModuleApi.h
ModuleApi.cc