DQMOnline: dqm4hep::core::StandaloneModuleApplication Class Reference
dqm4hep::core::StandaloneModuleApplication Class Reference
StandaloneModuleApplication class.
#include <StandaloneModuleApplication.h>
Classes
class Settings
Settings class.
Public Member Functions
StandaloneModuleApplication ()
Constructor.
~StandaloneModuleApplication ()
Destructor.
const std::string & getType () const
Get the application type ("StandaloneModule")
const std::string & getName () const
Get the application name (module name)
void setReplacementParameters (const ParameterMap &parametersMap)
Set the parameters to replace while reading settings.
StatusCode readSettings (const std::string &settingsFile)
Read settings from a xml file.
StatusCode run ()
Run the application.
Public Member Functions inherited from dqm4hep::core::ModuleApplication
ModuleApplication ()
Constructor.
virtual ~ModuleApplication ()
Destructor.
virtual StatusCode exit (int returnCode)
Stop the application.
Module * getModule () const
Get the module for this application.
bool shouldStopApplication () const
Whether the module application should stop.
void setStopApplication (bool stopApplication)
Set the application stop flag.
StatusCode setModuleName (const std::string &name)
Set the module name in used.
StatusCode setModuleType (const std::string &type)
Set the module type to look for (before calling readSettings())
const std::string & getModuleName () const
Get the module name in used.
const std::string & getModuleType () const
Get the module type in used.
bool isInitialized () const
Whether the application is initialized.
StatusCode getReturnCode () const
Get the return code when application ends.
Public Member Functions inherited from dqm4hep::core::Application
virtual ~Application ()
Destructor.
Public Member Functions inherited from dqm4hep::core::CycleListener
virtual ~CycleListener ()
Destructor.
Private Member Functions
void onEventProcessed (const Cycle *const pCycle, const Event *const pEvent)
Call back function when an event is processed by the framework.
void onCycleStarted (const Cycle *const pCycle)
Call back function when the cycle is started by the framework.
void onCycleStopped (const Cycle *const pCycle)
Call back function when the cycle is stopped by the framework.
Private Attributes
bool m_stopFlag
bool m_isInitialized
TimerCycle * m_pTimerCycle
Archiver * m_pArchiver
Settings m_settings
ParameterMap m_replacementParameters
std::string m_name
std::string m_type
std::string m_moduleLogStr
StatusCode m_returnStatusCode
Additional Inherited Members
Protected Member Functions inherited from dqm4hep::core::ModuleApplication
void setInitialized (bool initialized)
Set the application has initialized.
MonitorElementManager * getMonitorElementManager () const
Get the monitor element manager.
MonitorElementSender * getMonitorElementSender () const
Get the monitor element sender.
AlertNotifier * getAlertNotifier () const
Get the alert notifier.
StatusCode setModule (Module *pModule)
Set the module in use in this application.
StatusCode createAlertNotifier (const std::string moduleName)
Create the alert notifier with the module name.
Protected Attributes inherited from dqm4hep::core::ModuleApplication
StatusCode m_returnCode
Module * m_pModule
Detailed Description
StandaloneModuleApplication class.
Definition at line 46 of file StandaloneModuleApplication.h.
Constructor & Destructor Documentation
dqm4hep::core::StandaloneModuleApplication::StandaloneModuleApplication ()
Constructor.
Definition at line 54 of file StandaloneModuleApplication.cc.
References dqm4hep::core::ModuleApplication::Archiver, and m_pArchiver.
                                                              :
         ModuleApplication(),
         m_pTimerCycle(NULL),
         m_type("StandaloneModule"),
         m_name("Unknown"),
         m_moduleLogStr("[Standalone Module]"),
         m_returnStatusCode(STATUS_CODE_SUCCESS)
     {
       m_pArchiver = new Archiver();
     }
dqm4hep::core::StandaloneModuleApplication::~StandaloneModuleApplication ()
Destructor.
Definition at line 67 of file StandaloneModuleApplication.cc.
References m_pArchiver, and m_pTimerCycle.
     {
       if(m_pTimerCycle)
         delete m_pTimerCycle;
       delete m_pArchiver;
     }
Member Function Documentation
const std::string & dqm4hep::core::StandaloneModuleApplication::getName () const virtual
Get the application name (module name)
Implements dqm4hep::core::ModuleApplication.
Definition at line 84 of file StandaloneModuleApplication.cc.
References m_name.
Referenced by readSettings().
     {
       return m_name;
     }
const std::string & dqm4hep::core::StandaloneModuleApplication::getType () const virtual
Get the application type ("StandaloneModule")
Implements dqm4hep::core::ModuleApplication.
Definition at line 77 of file StandaloneModuleApplication.cc.
References m_type.
     {
       return m_type;
     }
void dqm4hep::core::StandaloneModuleApplication::onCycleStarted (const Cycle *const pCycle) private virtual
Call back function when the cycle is started by the framework.
Implements dqm4hep::core::CycleListener.
Definition at line 347 of file StandaloneModuleApplication.cc.
References dqm4hep::core::ModuleApplication::getModule().
     {
       THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->startOfCycle());
     }
void dqm4hep::core::StandaloneModuleApplication::onCycleStopped (const Cycle *const pCycle) private virtual
Call back function when the cycle is stopped by the framework.
Implements dqm4hep::core::CycleListener.
Definition at line 354 of file StandaloneModuleApplication.cc.
References dqm4hep::core::ModuleApplication::getModule().
     {
       THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->endOfCycle());
     }
void dqm4hep::core::StandaloneModuleApplication::onEventProcessed (const Cycle *const pCycle, const Event *const pEvent) inline private virtual
Call back function when an event is processed by the framework.
Implements dqm4hep::core::CycleListener.
Definition at line 108 of file StandaloneModuleApplication.h.
 { /* nop */ }
StatusCode dqm4hep::core::StandaloneModuleApplication::readSettings (const std::string & settingsFile) virtual
Read settings from a xml file.
Initialize the application. Declare all the services, load the shared libraries, configure the active module
Implements dqm4hep::core::ModuleApplication.
Definition at line 91 of file StandaloneModuleApplication.cc.
References dqm4hep::core::Cycle::addListener(), dqm4hep::core::ModuleApplication::getModule(), dqm4hep::core::ModuleApplication::getModuleName(), dqm4hep::core::ModuleApplication::getModuleType(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), dqm4hep::core::Module::getName(), getName(), dqm4hep::core::ModuleApplication::isInitialized(), dqm4hep::core::StandaloneModuleApplication::Settings::m_archiveDirectory, dqm4hep::core::StandaloneModuleApplication::Settings::m_cyclePeriod, m_moduleLogStr, dqm4hep::core::StandaloneModuleApplication::Settings::m_moduleName, dqm4hep::core::StandaloneModuleApplication::Settings::m_moduleType, dqm4hep::core::StandaloneModuleApplication::Settings::m_monitorElementCollector, m_name, dqm4hep::core::StandaloneModuleApplication::Settings::m_openArchive, m_pTimerCycle, m_replacementParameters, m_settings, dqm4hep::core::StandaloneModuleApplication::Settings::m_settingsFileName, dqm4hep::core::StandaloneModuleApplication::Settings::m_sleepTime, dqm4hep::core::StandaloneModuleApplication::Settings::print(), dqm4hep::core::MonitorElementSender::setCollectorName(), dqm4hep::core::Cycle::setCycleValue(), dqm4hep::core::ModuleApplication::setInitialized(), dqm4hep::core::ModuleApplication::setModule(), dqm4hep::core::ModuleApplication::setModuleName(), dqm4hep::core::ModuleApplication::setModuleType(), and dqm4hep::core::Cycle::setTimeout().
     {
       if(this->isInitialized())
         return STATUS_CODE_ALREADY_INITIALIZED;
       size_t splitterPosition = settingsFileName.find(":");
       std::string fileHandlerType;
       std::string filePattern;
       if(splitterPosition != std::string::npos)
       {
         fileHandlerType = settingsFileName.substr(0, splitterPosition);
         filePattern = settingsFileName.substr(splitterPosition+1);
       }
       else
       {
         fileHandlerType = "";
         filePattern = settingsFileName;
       }
       LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << ", Starting standalone module application with file handler type " << fileHandlerType );
       FileHandlerFactory fileHandlerFactory;
       FileHandler *pFileHandler = fileHandlerFactory.createFileHandler(fileHandlerType);
       if(!pFileHandler)
         return STATUS_CODE_FAILURE;
       StatusCode statusCode = pFileHandler->download(filePattern);
       if(statusCode != STATUS_CODE_SUCCESS)
       {
         delete pFileHandler;
         return statusCode;
       }
       m_settings.m_settingsFileName = pFileHandler->getLocalFileName();
       delete pFileHandler;
       TiXmlDocument xmlDocument(m_settings.m_settingsFileName);
       if (!xmlDocument.LoadFile())
       {
         LOG4CXX_FATAL( dqmMainLogger , m_moduleLogStr << ", AnalysisModuleApplication::readSettings - Invalid xml file." );
         return STATUS_CODE_FAILURE;
       }
       const TiXmlHandle xmlDocumentHandle(&xmlDocument);
       if( ! m_replacementParameters.empty() )
       {
         TiXmlElement *pXmlElement = xmlDocumentHandle.FirstChildElement().Element();
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::replaceAllXmlAttributes(pXmlElement, m_replacementParameters));
       }
       const TiXmlHandle xmlHandle = TiXmlHandle(xmlDocumentHandle.FirstChildElement().Element());
       // monitor element sender
       TiXmlElement *const pMeCollectorElement = xmlHandle.FirstChildElement("monitorelementcollector").Element();
       if(NULL == pMeCollectorElement)
       {
         LOG4CXX_FATAL( dqmMainLogger , m_moduleLogStr << ", <monitorelementcollector> element not found !" );
         return STATUS_CODE_NOT_FOUND;
       }
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pMeCollectorElement, "name", m_settings.m_monitorElementCollector));
       this->getMonitorElementSender()->setCollectorName(m_settings.m_monitorElementCollector);
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->connectToService());
       // cycle
       TiXmlElement *const pCycleElement = xmlHandle.FirstChildElement("cycle").Element();
       if(pCycleElement)
       {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pCycleElement, "sleep", m_settings.m_sleepTime));
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pCycleElement, "period", m_settings.m_cyclePeriod));
       }
       m_pTimerCycle = new TimerCycle();
       m_pTimerCycle->setCycleValue(m_settings.m_cyclePeriod);
       m_pTimerCycle->setTimeout(0);
       m_pTimerCycle->addListener(this);
       // module
       TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("module").Element();
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "type", m_settings.m_moduleType));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "name", m_settings.m_moduleName));
       if(this->getModuleType().empty())
         this->setModuleType(m_settings.m_moduleType);
       if(this->getModuleName().empty())
         this->setModuleName(m_settings.m_moduleName);
       LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << ", Query standalone module to PluginManager ... " );
       StandaloneModule *pStandaloneModule = PluginManager::instance()->createPluginClass<StandaloneModule>(this->getModuleType());
       if(!pStandaloneModule)
         return STATUS_CODE_FAILURE;
       this->setModule(pStandaloneModule);
       m_moduleLogStr = "[" + pStandaloneModule->getName() + "]";
       LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << ", Query standalone module to PluginManager ... OK" );
       TiXmlHandle moduleHandle(pXmlElement);
       LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << ", Reading settings of active module '" << this->getModule()->getName() << "' ..." );
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getModule()->readSettings(moduleHandle));
       LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << ", Reading settings of active module '" << this->getModule()->getName() << "' ... OK" );
       LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << ", Initializing active module '" << this->getModule()->getName() << "' ..." );
       RETURN_RESULT_IF( STATUS_CODE_SUCCESS, !=, this->getModule()->initModule() );
       LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << ", Initializing active module '" << this->getModule()->getName() << "' ... OK" );
       try
       {
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << ", Configuring archiver ..." );
         const TiXmlElement *const pXmlElement = xmlHandle.FirstChildElement("archiver").Element();
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "open", m_settings.m_openArchive));
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "directory", m_settings.m_archiveDirectory));
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << ", Configuring archiver ... OK" );
       }
       catch(const StatusCodeException &exception)
       {
         return exception.getStatusCode();
       }
       m_name = this->getModule()->getName();
       DimBrowser browser;
       int nServers = browser.getServers();
       std::string moduleServerName = "DQM4HEP/Module/" + this->getModule()->getName();
       if(nServers)
       {
         char *serverName;
         char *node;
         while(browser.getNextServer(serverName, node))
         {
           if(moduleServerName == serverName)
           {
             LOG4CXX_ERROR( dqmMainLogger , m_moduleLogStr << ", Module already registered over the network.\n"
                 << "Please, change the module name or stop the other module application with the same name !" );
             return STATUS_CODE_ALREADY_PRESENT;
           }
         }
       }
       DimServer::start( moduleServerName.c_str() );
       RETURN_RESULT_IF( STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->connectToService() );
       this->setInitialized(true);
       m_settings.print(m_moduleLogStr);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::StandaloneModuleApplication::run () virtual
Run the application.
Implements dqm4hep::core::ModuleApplication.
Definition at line 277 of file StandaloneModuleApplication.cc.
References dqm4hep::core::Module::endModule(), dqm4hep::core::ModuleApplication::getModule(), dqm4hep::core::ModuleApplication::getMonitorElementSender(), dqm4hep::core::TimerCycle::isEndOfCycleReached(), dqm4hep::core::ModuleApplication::isInitialized(), dqm4hep::core::StandaloneModuleApplication::Settings::m_archiveDirectory, m_moduleLogStr, dqm4hep::core::StandaloneModuleApplication::Settings::m_moduleName, dqm4hep::core::StandaloneModuleApplication::Settings::m_openArchive, m_pArchiver, m_pTimerCycle, m_settings, dqm4hep::core::StandaloneModuleApplication::Settings::m_sleepTime, dqm4hep::core::StandaloneModule::process(), dqm4hep::core::ModuleApplication::shouldStopApplication(), dqm4hep::core::Cycle::startCycle(), and dqm4hep::core::Cycle::stopCycle().
     {
       if(!this->isInitialized())
         return STATUS_CODE_NOT_INITIALIZED;
       bool callStartOfCycle = true;
       // get casted module for easier manipulation
       StandaloneModule *pStandaloneModule = dynamic_cast<StandaloneModule *>(this->getModule());
       // open an archive
       if(m_settings.m_openArchive)
       {
         std::stringstream archiveFileName;
         std::string directory =
             m_settings.m_archiveDirectory.at(m_settings.m_archiveDirectory.size() - 1) == '/' ?
                 m_settings.m_archiveDirectory : m_settings.m_archiveDirectory + "/";
         archiveFileName << directory
             << "DQMArchive"
             << "_M" << m_settings.m_moduleName;
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->open(archiveFileName.str(), "RECREATE"));
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Archive '" << m_pArchiver->getFileName() << "' opened" );
       }
       while(!this->shouldStopApplication())
       {
         // process a cycle
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Start of cycle");
         m_pTimerCycle->startCycle();
         while(1)
         {
           if( m_pTimerCycle->isEndOfCycleReached() )
             break;
           if( this->shouldStopApplication() )
             break;
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pStandaloneModule->process());
           CoreTool::sleep(std::chrono::microseconds(m_settings.m_sleepTime));
         }
         m_pTimerCycle->stopCycle();
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , End of cycle reached");
         LOG4CXX_INFO( dqmMainLogger , m_moduleLogStr << " , Sending monitor elements to collector" );
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElementSender()->sendMonitorElements());
         // archive publication if user asked for
         if(m_settings.m_openArchive)
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->archive(pStandaloneModule));
       }
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pStandaloneModule->endModule());
       // archive the monitor element if archive is opened
       if(m_settings.m_openArchive)
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_pArchiver->close());
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::StandaloneModuleApplication::setReplacementParameters (const ParameterMap & parametersMap)
Set the parameters to replace while reading settings.
Definition at line 270 of file StandaloneModuleApplication.cc.
References m_replacementParameters.
     {
       m_replacementParameters = parametersMap;
     }
Member Data Documentation
bool dqm4hep::core::StandaloneModuleApplication::m_isInitialized private
Definition at line 114 of file StandaloneModuleApplication.h.
std::string dqm4hep::core::StandaloneModuleApplication::m_moduleLogStr private
Definition at line 126 of file StandaloneModuleApplication.h.
Referenced by readSettings(), and run().
std::string dqm4hep::core::StandaloneModuleApplication::m_name private
Definition at line 124 of file StandaloneModuleApplication.h.
Referenced by getName(), and readSettings().
Archiver* dqm4hep::core::StandaloneModuleApplication::m_pArchiver private
Definition at line 118 of file StandaloneModuleApplication.h.
Referenced by run(), StandaloneModuleApplication(), and ~StandaloneModuleApplication().
TimerCycle* dqm4hep::core::StandaloneModuleApplication::m_pTimerCycle private
Definition at line 117 of file StandaloneModuleApplication.h.
Referenced by readSettings(), run(), and ~StandaloneModuleApplication().
ParameterMap dqm4hep::core::StandaloneModuleApplication::m_replacementParameters private
Definition at line 122 of file StandaloneModuleApplication.h.
Referenced by readSettings(), and setReplacementParameters().
StatusCode dqm4hep::core::StandaloneModuleApplication::m_returnStatusCode private
Definition at line 128 of file StandaloneModuleApplication.h.
Settings dqm4hep::core::StandaloneModuleApplication::m_settings private
Definition at line 121 of file StandaloneModuleApplication.h.
Referenced by readSettings(), and run().
bool dqm4hep::core::StandaloneModuleApplication::m_stopFlag private
Definition at line 113 of file StandaloneModuleApplication.h.
std::string dqm4hep::core::StandaloneModuleApplication::m_type private
Definition at line 125 of file StandaloneModuleApplication.h.
Referenced by getType().
The documentation for this class was generated from the following files:
StandaloneModuleApplication.h
StandaloneModuleApplication.cc