DQMOnline: dqm4hep::core::Cycle Class Reference
dqm4hep::core::Cycle Class Reference abstract
Cycle class.
#include <Cycle.h>
Public Member Functions
Cycle ()
Constructor.
virtual ~Cycle ()
Destructor.
float getCycleValue () const
Get the cycle value (time, nb of events, event size)
void setCycleValue (float value)
Set the cycle value.
unsigned int getTimeout () const
Get the cycle timeout (in seconds) Maximum time between two processEvent(evt) call.
void setTimeout (unsigned int timeout)
Set the timeout.
float getProcessingRate () const
Get the processing rate.
unsigned int getNProcessedEvents () const
Get the number of processed events at the end of cycle.
TimeDuration getTotalCycleTime () const
Get the total time spent to process the last cycle.
void eventProcessed (const Event *const pEvent)
Called back when the application has processed an event.
const TimePoint & getStartTime () const
Get the start time of the current cycle.
const TimePoint & getEndTime () const
Get the end time of the last cycle.
void startCycle ()
Start the cycle.
void stopCycle ()
Stop the cycle.
State getState () const
Get the cycle state (running, stopped)
bool isTimeoutReached () const
Whether the timeout is reached.
void addListener (CycleListener *pListener)
Add a cycle listener.
void removeListener (CycleListener *pListener)
Remove a cycle listener.
virtual void onCycleStarted ()=0
Specific call back function when a cycle is stopped.
virtual void onCycleStopped ()=0
Specific call back function when a cycle is stopped.
virtual void onEventProcessed (const Event *const pEvent)=0
Specific call back function when an event is processed, depends on cycle type.
virtual bool isEndOfCycleReached () const =0
Specific function to tell the application to know whether the cycle has reached the end.
Private Attributes
float m_processingRate
float m_cycleValue
unsigned int m_cycleTimeout
unsigned int m_nProcessedEvents
TimePoint m_startTime
TimePoint m_endTime
TimePoint m_lastEventProcessedTime
std::set< CycleListener * > m_listeners
State m_state
Detailed Description
Cycle class.
Process a cycle of processEvent(evt) call for a AnalysisModule. See implementation for cycle types.
The cycle value is the value for which the cycle should normally ends.
The timeout value is the maximum time between two processEvent(evt) call When the timeout is reached, the cycle ends. The default timeout value is 10 seconds and can be changed via the method setTimeout(secs)
Definition at line 77 of file Cycle.h.
Constructor & Destructor Documentation
dqm4hep::core::Cycle::Cycle ()
Constructor.
Definition at line 36 of file Cycle.cc.
                  :
         m_processingRate(0.f),
         m_cycleValue(0.f),
         m_cycleTimeout(10), // 10 seconds is the default value
         m_nProcessedEvents(0)
     {
       /* nop */
     }
dqm4hep::core::Cycle::~Cycle () virtual
Destructor.
Definition at line 47 of file Cycle.cc.
     {
       /* nop */
     }
Member Function Documentation
void dqm4hep::core::Cycle::addListener (CycleListener * pListener)
Add a cycle listener.
Definition at line 197 of file Cycle.cc.
References m_listeners.
Referenced by dqm4hep::core::AnalysisModuleApplication::configureCycle(), and dqm4hep::core::StandaloneModuleApplication::readSettings().
     {
       if(NULL != pListener)
         m_listeners.insert(pListener);
     }
void dqm4hep::core::Cycle::eventProcessed (const Event *const pEvent)
Called back when the application has processed an event.
Definition at line 103 of file Cycle.cc.
References getState(), m_lastEventProcessedTime, m_listeners, m_nProcessedEvents, and onEventProcessed().
Referenced by dqm4hep::core::AnalysisModuleApplication::run().
     {
       if(this->getState() != RUNNING_STATE)
         return;
       if(NULL == pEvent)
         return;
       m_nProcessedEvents++;
       m_lastEventProcessedTime = CoreTool::now();
       // call back for daughter class
       this->onEventProcessed(pEvent);
       // call back from listeners
       for(std::set<CycleListener*>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
           endIter != iter ; ++iter)
         (*iter)->onEventProcessed(this, pEvent);
     }
float dqm4hep::core::Cycle::getCycleValue () const
Get the cycle value (time, nb of events, event size)
Definition at line 54 of file Cycle.cc.
References m_cycleValue.
Referenced by dqm4hep::core::EventCounterCycle::isEndOfCycleReached(), and dqm4hep::core::TimerCycle::isEndOfCycleReached().
     {
       return m_cycleValue;
     }
const TimePoint & dqm4hep::core::Cycle::getEndTime () const
Get the end time of the last cycle.
Valid only between two cycle after stopCycle() call
Definition at line 132 of file Cycle.cc.
References m_endTime.
     {
       return m_endTime;
     }
unsigned int dqm4hep::core::Cycle::getNProcessedEvents () const
Get the number of processed events at the end of cycle.
Definition at line 89 of file Cycle.cc.
References m_nProcessedEvents.
Referenced by dqm4hep::core::EventCounterCycle::isEndOfCycleReached(), and dqm4hep::core::AnalysisModuleApplication::run().
     {
       return m_nProcessedEvents;
     }
float dqm4hep::core::Cycle::getProcessingRate () const
Get the processing rate.
May be called after stopCycle() to get the correct value
Definition at line 82 of file Cycle.cc.
References m_processingRate.
Referenced by dqm4hep::core::AnalysisModuleApplication::run().
     {
       return m_processingRate;
     }
const TimePoint & dqm4hep::core::Cycle::getStartTime () const
Get the start time of the current cycle.
Definition at line 125 of file Cycle.cc.
References m_startTime.
Referenced by dqm4hep::core::ModuleApi::getTimeSinceStartOfCycle(), and dqm4hep::core::TimerCycle::isEndOfCycleReached().
     {
       return m_startTime;
     }
State dqm4hep::core::Cycle::getState () const
Get the cycle state (running, stopped)
Definition at line 180 of file Cycle.cc.
References m_state.
Referenced by eventProcessed().
     {
       return m_state;
     }
unsigned int dqm4hep::core::Cycle::getTimeout () const
Get the cycle timeout (in seconds) Maximum time between two processEvent(evt) call.
When the timeout is reached, the cycle ends
Definition at line 68 of file Cycle.cc.
References m_cycleTimeout.
Referenced by isTimeoutReached().
     {
       return m_cycleTimeout;
     }
TimeDuration dqm4hep::core::Cycle::getTotalCycleTime () const
Get the total time spent to process the last cycle.
Definition at line 96 of file Cycle.cc.
References m_endTime, and m_startTime.
Referenced by dqm4hep::core::AnalysisModuleApplication::run(), and stopCycle().
     {
       return (m_endTime - m_startTime);
     }
virtual bool dqm4hep::core::Cycle::isEndOfCycleReached () const pure virtual
Specific function to tell the application to know whether the cycle has reached the end.
Implemented in dqm4hep::core::TimerCycle, and dqm4hep::core::EventCounterCycle.
Referenced by dqm4hep::core::AnalysisModuleApplication::run().
bool dqm4hep::core::Cycle::isTimeoutReached () const
Whether the timeout is reached.
Definition at line 187 of file Cycle.cc.
References getTimeout(), and m_lastEventProcessedTime.
Referenced by dqm4hep::core::AnalysisModuleApplication::run().
     {
       if( CoreTool::now() > m_lastEventProcessedTime + std::chrono::seconds(this->getTimeout()) )
         return true;
       return false;
     }
virtual void dqm4hep::core::Cycle::onCycleStarted () pure virtual
Specific call back function when a cycle is stopped.
Implemented in dqm4hep::core::TimerCycle, and dqm4hep::core::EventCounterCycle.
Referenced by startCycle().
virtual void dqm4hep::core::Cycle::onCycleStopped () pure virtual
Specific call back function when a cycle is stopped.
Implemented in dqm4hep::core::TimerCycle, and dqm4hep::core::EventCounterCycle.
Referenced by stopCycle().
virtual void dqm4hep::core::Cycle::onEventProcessed (const Event *const pEvent) pure virtual
Specific call back function when an event is processed, depends on cycle type.
Implemented in dqm4hep::core::TimerCycle, and dqm4hep::core::EventCounterCycle.
Referenced by eventProcessed().
void dqm4hep::core::Cycle::removeListener (CycleListener * pListener)
Remove a cycle listener.
Definition at line 205 of file Cycle.cc.
References m_listeners.
     {
       m_listeners.erase(pListener);
     }
void dqm4hep::core::Cycle::setCycleValue (float value)
Set the cycle value.
Definition at line 61 of file Cycle.cc.
References m_cycleValue.
Referenced by dqm4hep::core::AnalysisModuleApplication::configureCycle(), and dqm4hep::core::StandaloneModuleApplication::readSettings().
     {
       m_cycleValue = value;
     }
void dqm4hep::core::Cycle::setTimeout (unsigned int timeout)
Set the timeout.
Definition at line 75 of file Cycle.cc.
References m_cycleTimeout.
Referenced by dqm4hep::core::AnalysisModuleApplication::configureCycle(), and dqm4hep::core::StandaloneModuleApplication::readSettings().
     {
       m_cycleTimeout = timeout;
     }
void dqm4hep::core::Cycle::startCycle ()
Start the cycle.
Definition at line 139 of file Cycle.cc.
References m_endTime, m_lastEventProcessedTime, m_listeners, m_nProcessedEvents, m_processingRate, m_startTime, m_state, and onCycleStarted().
Referenced by dqm4hep::core::StandaloneModuleApplication::run(), and dqm4hep::core::AnalysisModuleApplication::run().
     {
       m_startTime = CoreTool::now();
       m_lastEventProcessedTime = m_startTime;
       m_endTime = TimePoint();
       m_nProcessedEvents = 0;
       m_processingRate = 0.f;
       m_state = RUNNING_STATE;
       // call back for daughter class
       this->onCycleStarted();
       // call back from listeners
       for(std::set<CycleListener*>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
           endIter != iter ; ++iter)
         (*iter)->onCycleStarted(this);
     }
void dqm4hep::core::Cycle::stopCycle ()
Stop the cycle.
Definition at line 160 of file Cycle.cc.
References getTotalCycleTime(), m_endTime, m_listeners, m_nProcessedEvents, m_processingRate, m_state, and onCycleStopped().
Referenced by dqm4hep::core::StandaloneModuleApplication::run(), and dqm4hep::core::AnalysisModuleApplication::run().
     {
       m_endTime = CoreTool::now();
       m_state = STOPPED_STATE;
       TimeDuration timeDifference = this->getTotalCycleTime();
       m_processingRate = (static_cast<float>(m_nProcessedEvents) / timeDifference.count());
       // call back for daughter class
       this->onCycleStopped();
       // call back from listeners
       for(std::set<CycleListener*>::iterator iter = m_listeners.begin(), endIter = m_listeners.end() ;
           endIter != iter ; ++iter)
         (*iter)->onCycleStopped(this);
     }
Member Data Documentation
unsigned int dqm4hep::core::Cycle::m_cycleTimeout private
Definition at line 176 of file Cycle.h.
Referenced by getTimeout(), and setTimeout().
float dqm4hep::core::Cycle::m_cycleValue private
Definition at line 175 of file Cycle.h.
Referenced by getCycleValue(), and setCycleValue().
TimePoint dqm4hep::core::Cycle::m_endTime private
Definition at line 179 of file Cycle.h.
Referenced by getEndTime(), getTotalCycleTime(), startCycle(), and stopCycle().
TimePoint dqm4hep::core::Cycle::m_lastEventProcessedTime private
Definition at line 180 of file Cycle.h.
Referenced by eventProcessed(), isTimeoutReached(), and startCycle().
std::set<CycleListener*> dqm4hep::core::Cycle::m_listeners private
Definition at line 181 of file Cycle.h.
Referenced by addListener(), eventProcessed(), removeListener(), startCycle(), and stopCycle().
unsigned int dqm4hep::core::Cycle::m_nProcessedEvents private
Definition at line 177 of file Cycle.h.
Referenced by eventProcessed(), getNProcessedEvents(), startCycle(), and stopCycle().
float dqm4hep::core::Cycle::m_processingRate private
Definition at line 174 of file Cycle.h.
Referenced by getProcessingRate(), startCycle(), and stopCycle().
TimePoint dqm4hep::core::Cycle::m_startTime private
Definition at line 178 of file Cycle.h.
Referenced by getStartTime(), getTotalCycleTime(), and startCycle().
State dqm4hep::core::Cycle::m_state private
Definition at line 182 of file Cycle.h.
Referenced by getState(), startCycle(), and stopCycle().
The documentation for this class was generated from the following files:
Cycle.h
Cycle.cc