DQMOnline: dqm4hep::core::DimAlertHandler Class Reference
dqm4hep::core::DimAlertHandler Class Reference
#include <AlertSystem.h>
Public Member Functions
DimAlertHandler (const std::string &emitter)
~DimAlertHandler ()
const std::string & getEmitter () const
StatusCode connectToService ()
StatusCode disconnectFromService ()
bool isConnected () const
Public Member Functions inherited from dqm4hep::core::AlertHandler
virtual ~AlertHandler ()
void addListener (AlertListener *pListener)
void removeListener (AlertListener *pListener)
Private Member Functions
void configureInBuffer (char *pBuffer, xdrstream::xdr_size_t bufferSize)
void infoHandler ()
Private Attributes
bool m_isConnected
std::string m_emitter
DimUpdatedInfo * m_pAlertInfo
xdrstream::BufferDevice * m_pBuffer
Additional Inherited Members
Protected Member Functions inherited from dqm4hep::core::AlertHandler
void notifyListeners (AlertPtr alert)
Detailed Description
Definition at line 254 of file AlertSystem.h.
Constructor & Destructor Documentation
dqm4hep::core::DimAlertHandler::DimAlertHandler (const std::string & emitter)
Definition at line 322 of file AlertSystem.cc.
                                                              :
         m_emitter(emitter),
         m_isConnected(false),
         m_pBuffer(NULL)
     {
       /* nop */
     }
dqm4hep::core::DimAlertHandler::~DimAlertHandler ()
Definition at line 332 of file AlertSystem.cc.
References m_pBuffer.
     {
       if( m_pBuffer )
         delete m_pBuffer;
     }
Member Function Documentation
void dqm4hep::core::DimAlertHandler::configureInBuffer (char * pBuffer, xdrstream::xdr_size_t bufferSize) private
Definition at line 381 of file AlertSystem.cc.
References m_pBuffer.
Referenced by infoHandler().
     {
       if(NULL == m_pBuffer)
         m_pBuffer = new xdrstream::BufferDevice(pBuffer, bufferSize, false);
       else
         m_pBuffer->setBuffer(pBuffer, bufferSize, false);
       m_pBuffer->setOwner(false);
     }
StatusCode dqm4hep::core::DimAlertHandler::connectToService () virtual
Implements dqm4hep::core::AlertHandler.
Definition at line 347 of file AlertSystem.cc.
References getEmitter(), isConnected(), m_isConnected, and m_pAlertInfo.
     {
       if( this->isConnected() )
         return STATUS_CODE_SUCCESS;
       std::string infoName = "DQM4HEP/ALERT/" + this->getEmitter();
       m_pAlertInfo = new DimUpdatedInfo( infoName.c_str(), (void*) NULL, 0 , this );
       m_isConnected = true;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DimAlertHandler::disconnectFromService () virtual
Implements dqm4hep::core::AlertHandler.
Definition at line 361 of file AlertSystem.cc.
References isConnected(), m_isConnected, and m_pAlertInfo.
     {
       if( ! this->isConnected() )
         return STATUS_CODE_SUCCESS;
       delete m_pAlertInfo;
       m_isConnected = false;
       return STATUS_CODE_SUCCESS;
     }
const std::string & dqm4hep::core::DimAlertHandler::getEmitter () const
Definition at line 340 of file AlertSystem.cc.
References m_emitter.
Referenced by connectToService().
     {
       return m_emitter;
     }
void dqm4hep::core::DimAlertHandler::infoHandler () private
Definition at line 393 of file AlertSystem.cc.
References configureInBuffer(), m_pAlertInfo, m_pBuffer, and dqm4hep::core::AlertHandler::notifyListeners().
     {
       char *pBuffer = static_cast<char *>(m_pAlertInfo->getData());
       xdrstream::xdr_size_t bufferSize = m_pAlertInfo->getSize();
       if(NULL == pBuffer || 0 == bufferSize)
         return;
       this->configureInBuffer( pBuffer, bufferSize );
       AlertPtr alert(new Alert());
       if( ! XDR_TESTBIT( alert->stream( xdrstream::XDR_READ_STREAM , m_pBuffer ) , xdrstream::XDR_SUCCESS ) )
         return;
       this->notifyListeners(alert);
     }
bool dqm4hep::core::DimAlertHandler::isConnected () const virtual
Implements dqm4hep::core::AlertHandler.
Definition at line 374 of file AlertSystem.cc.
References m_isConnected.
Referenced by connectToService(), and disconnectFromService().
     {
       return m_isConnected;
     }
Member Data Documentation
std::string dqm4hep::core::DimAlertHandler::m_emitter private
Definition at line 282 of file AlertSystem.h.
Referenced by getEmitter().
bool dqm4hep::core::DimAlertHandler::m_isConnected private
Definition at line 281 of file AlertSystem.h.
Referenced by connectToService(), disconnectFromService(), and isConnected().
DimUpdatedInfo* dqm4hep::core::DimAlertHandler::m_pAlertInfo private
Definition at line 283 of file AlertSystem.h.
Referenced by connectToService(), disconnectFromService(), and infoHandler().
xdrstream::BufferDevice* dqm4hep::core::DimAlertHandler::m_pBuffer private
Definition at line 284 of file AlertSystem.h.
Referenced by configureInBuffer(), infoHandler(), and ~DimAlertHandler().
The documentation for this class was generated from the following files:
AlertSystem.h
AlertSystem.cc