DQMOnline: dqm4hep::online::OnlineRoutes::OnlineManager Class Reference
dqm4hep::online::OnlineRoutes::OnlineManager Class Reference
OnlineManager class Defines routes related to the online manager server.
#include <OnlineRoutes.h>
Static Public Member Functions
static const std::string serverName ()
Get the online manager server name.
static const std::string logs ()
Get the name of the service that sends (server) or receives (client) logs.
static const std::string appStats ()
Get the name of the service that sends (server) or receive (client) app statistics.
static const std::string collectLog ()
Get the name of the commmand to send (client) or collect (server) a log message.
static const std::string collectAppStat ()
Get the name of the commmand to send (client) or collect (server) an app statistics.
Detailed Description
OnlineManager class Defines routes related to the online manager server.
Definition at line 85 of file OnlineRoutes.h.
Member Function Documentation
const std::string dqm4hep::online::OnlineRoutes::OnlineManager::appStats () static
Get the name of the service that sends (server) or receive (client) app statistics.
Definition at line 66 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::OnlineManagerServer::run().
{
       return std::string("/dqm4hep/onlineMgr/appStats");
     }
const std::string dqm4hep::online::OnlineRoutes::OnlineManager::collectAppStat () static
Get the name of the commmand to send (client) or collect (server) an app statistics.
Definition at line 78 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::OnlineManagerServer::run().
{
       return std::string("/dqm4hep/onlineMgr/collectAppStat");
     }
const std::string dqm4hep::online::OnlineRoutes::OnlineManager::collectLog () static
Get the name of the commmand to send (client) or collect (server) a log message.
Definition at line 72 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::RemoteLogger::log(), and dqm4hep::online::OnlineManagerServer::run().
{
       return std::string("/dqm4hep/onlineMgr/collectLog");
     }
const std::string dqm4hep::online::OnlineRoutes::OnlineManager::logs () static
Get the name of the service that sends (server) or receives (client) logs.
Definition at line 60 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::OnlineManagerServer::run().
{
       return std::string("/dqm4hep/onlineMgr/logs");
     }
const std::string dqm4hep::online::OnlineRoutes::OnlineManager::serverName () static
Get the online manager server name.
Definition at line 54 of file OnlineRoutes.cc.
Referenced by dqm4hep::online::OnlineManagerServer::run().
{
       return std::string("/dqm4hep/onlineMgr");
     }
The documentation for this class was generated from the following files:
OnlineRoutes.h
OnlineRoutes.cc