DQMOnline: dqm4hep::online::EventCollectorClient Class Reference
dqm4hep::online::EventCollectorClient Class Reference
EventCollectorClient class.
#include <EventCollectorClient.h>
Classes
struct SourceInfo
SourceInfo struct.
Public Member Functions
~EventCollectorClient ()=default
EventCollectorClient (const std::string &collectorName)
Default constructor.
core::EventPtr queryEvent (const std::string &source)
Request the last collected event in the collector.
template<typename Controller >
void onEventUpdate (const std::string &source, Controller *controller, void(Controller::*function)(core::EventPtr event))
Get the signal for event updates for a given source If the source is not yet registered internally here, it is created and returned in any case.
void startEventUpdates (const std::string &source)
Instruct the event collector to send the latest received event when a new one is available for a given source.
void stopEventUpdates (const std::string &source)
Instruct the event collector to stop sending event.
bool receivingEventUpdates (const std::string &source) const
Whether the client is currently receiving event updates from the collector.
void startEventUpdates ()
void stopEventUpdates ()
Private Types
using BufferDevicePtr = std::shared_ptr< xdrstream::BufferDevice >
using EventUpdateSignal = core::Signal< core::EventPtr >
using SourceInfoMap = std::map< std::string, SourceInfo >
Private Member Functions
void setUpdateMode (const std::string &source, bool receiveUpdates)
core::EventPtr readEvent (const net::Buffer &buffer)
Private Attributes
std::string m_collectorName = {""}
SourceInfoMap m_sourceInfoMap = {}
net::Client m_client = {}
std::recursive_mutex m_mutex = {}
core::EventStreamer m_eventStreamer = {}
BufferDevicePtr m_bufferDevice = {nullptr}
Friends
struct SourceInfo
Detailed Description
EventCollectorClient class.
Definition at line 50 of file EventCollectorClient.h.
Member Typedef Documentation
using dqm4hep::online::EventCollectorClient::BufferDevicePtr = std::shared_ptr<xdrstream::BufferDevice> private
Definition at line 105 of file EventCollectorClient.h.
using dqm4hep::online::EventCollectorClient::EventUpdateSignal = core::Signal<core::EventPtr> private
Definition at line 106 of file EventCollectorClient.h.
using dqm4hep::online::EventCollectorClient::SourceInfoMap = std::map<std::string, SourceInfo> private
Definition at line 117 of file EventCollectorClient.h.
Constructor & Destructor Documentation
dqm4hep::online::EventCollectorClient::~EventCollectorClient () default
dqm4hep::online::EventCollectorClient::EventCollectorClient (const std::string & collectorName)
Default constructor.
Parameters
collectorName the collector name to connect to
Definition at line 45 of file EventCollectorClient.cc.
                                                                              :
       m_collectorName(collectorName) {
         /* nop */
     }
Member Function Documentation
template<typename Controller > void dqm4hep::online::EventCollectorClient::onEventUpdate (const std::string & source, Controller * controller, void(Controller::*)(core::EventPtr event) function) inline
Get the signal for event updates for a given source If the source is not yet registered internally here, it is created and returned in any case.
Parameters
source the source name
controller the object receiving the event
function the object function receiving the event
Definition at line 132 of file EventCollectorClient.h.
References m_mutex, and m_sourceInfoMap.
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       auto &info = m_sourceInfoMap[source];
       info.m_collectorClient = this;
       info.m_eventUpdateSignal.connect(controller, function);
     }
core::EventPtr dqm4hep::online::EventCollectorClient::queryEvent (const std::string & source)
Request the last collected event in the collector.
Definition at line 52 of file EventCollectorClient.cc.
References dqm4hep::online::OnlineRoutes::EventCollector::eventRequest(), m_client, m_collectorName, and readEvent().
{
       core::EventPtr event = nullptr;
       net::Buffer buffer;
       auto model = buffer.createModel<std::string>();
       buffer.setModel(model);
       model->copy(source);
       m_client.sendRequest(
         OnlineRoutes::EventCollector::eventRequest(m_collectorName),
         buffer,
         [&event,this](const net::Buffer &response){
           event = this->readEvent(response);
       });
       return event;
     }
core::EventPtr dqm4hep::online::EventCollectorClient::readEvent (const net::Buffer & buffer) private
Definition at line 143 of file EventCollectorClient.cc.
References m_bufferDevice, m_eventStreamer, and m_mutex.
Referenced by queryEvent(), and dqm4hep::online::EventCollectorClient::SourceInfo::receiveEvent().
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       try {
         if(not m_bufferDevice) {
           m_bufferDevice = std::make_shared<xdrstream::BufferDevice>((char*)buffer.begin(), buffer.size(), false);
           m_bufferDevice->setOwner(false);
         }
         else {
           m_bufferDevice->setBuffer((char*)buffer.begin(), buffer.size(), false);
         }
       }
       catch(...) {
         dqm_error( "EventCollectorClient::readEvent: couldn't setup buffer device !" );
         return nullptr;
       }
       // read event using event streamer
       core::EventPtr event(nullptr);
       core::StatusCode statusCode = m_eventStreamer.readEvent(event, m_bufferDevice.get());
       if(core::STATUS_CODE_SUCCESS != statusCode) {
         dqm_error( "EventCollectorClient::readEvent: streamer couldn't read event: {0}", core::statusCodeToString(statusCode) );
         return nullptr;
       }
       return event;
     }
bool dqm4hep::online::EventCollectorClient::receivingEventUpdates (const std::string & source) const
Whether the client is currently receiving event updates from the collector.
Definition at line 113 of file EventCollectorClient.cc.
References dqm4hep::online::OnlineRoutes::EventCollector::eventUpdate(), m_client, m_collectorName, m_mutex, and m_sourceInfoMap.
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       auto findIter = m_sourceInfoMap.find(source);
       if(m_sourceInfoMap.end() == findIter) {
         dqm_error( "EventCollectorClient::receivingEventUpdates: no source with '{0}' registered !", source );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_FOUND);
       }
       return m_client.hasSubscribed(OnlineRoutes::EventCollector::eventUpdate(m_collectorName, source));
     }
void dqm4hep::online::EventCollectorClient::setUpdateMode (const std::string & source, bool receiveUpdates) private
Definition at line 83 of file EventCollectorClient.cc.
References dqm4hep::online::OnlineRoutes::EventCollector::eventUpdate(), m_client, m_collectorName, m_sourceInfoMap, and dqm4hep::online::EventCollectorClient::SourceInfo::receiveEvent().
Referenced by startEventUpdates(), and stopEventUpdates().
{
       auto findIter = m_sourceInfoMap.find(source);
       if(m_sourceInfoMap.end() == findIter) {
         dqm_error( "EventCollectorClient::setUpdateMode: no source with '{0}' registered !", source );
         throw core::StatusCodeException(core::STATUS_CODE_NOT_FOUND);
       }
       bool subscribed = m_client.hasSubscribed(OnlineRoutes::EventCollector::eventUpdate(m_collectorName, source));
       // two cases:
       // 1) already subscribed and don't want to receive updates anymore
       // 2) not subscribed and want to receive updates
       if(subscribed != receiveUpdates) {
         if(receiveUpdates) {
           m_client.subscribe(
             OnlineRoutes::EventCollector::eventUpdate(m_collectorName, source),
             &findIter->second,
             &EventCollectorClient::SourceInfo::receiveEvent
           );
         }
         else {
           m_client.unsubscribe(
             OnlineRoutes::EventCollector::eventUpdate(m_collectorName, source),
             &findIter->second
           );
         }
       }
     }
void dqm4hep::online::EventCollectorClient::startEventUpdates (const std::string & source)
Instruct the event collector to send the latest received event when a new one is available for a given source.
Parameters
source the source name
Definition at line 69 of file EventCollectorClient.cc.
References m_mutex, and setUpdateMode().
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       setUpdateMode(source, true);
     }
void dqm4hep::online::EventCollectorClient::startEventUpdates ()
Definition at line 125 of file EventCollectorClient.cc.
References m_mutex, m_sourceInfoMap, and setUpdateMode().
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       for(auto &source : m_sourceInfoMap) {
         setUpdateMode(source.first, true);
       }
     }
void dqm4hep::online::EventCollectorClient::stopEventUpdates (const std::string & source)
Instruct the event collector to stop sending event.
Definition at line 76 of file EventCollectorClient.cc.
References m_mutex, and setUpdateMode().
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       setUpdateMode(source, false);
     }
void dqm4hep::online::EventCollectorClient::stopEventUpdates ()
Definition at line 134 of file EventCollectorClient.cc.
References m_mutex, m_sourceInfoMap, and setUpdateMode().
{
       std::lock_guard<std::recursive_mutex> lock(m_mutex);
       for(auto &source : m_sourceInfoMap) {
         setUpdateMode(source.first, false);
       }
     }
Friends And Related Function Documentation
friend struct SourceInfo friend
Definition at line 116 of file EventCollectorClient.h.
Member Data Documentation
BufferDevicePtr dqm4hep::online::EventCollectorClient::m_bufferDevice = {nullptr} private
Definition at line 125 of file EventCollectorClient.h.
Referenced by readEvent().
net::Client dqm4hep::online::EventCollectorClient::m_client = {} private
Definition at line 122 of file EventCollectorClient.h.
Referenced by queryEvent(), receivingEventUpdates(), and setUpdateMode().
std::string dqm4hep::online::EventCollectorClient::m_collectorName = {""} private
Definition at line 120 of file EventCollectorClient.h.
Referenced by queryEvent(), receivingEventUpdates(), and setUpdateMode().
core::EventStreamer dqm4hep::online::EventCollectorClient::m_eventStreamer = {} private
Definition at line 124 of file EventCollectorClient.h.
Referenced by readEvent().
std::recursive_mutex dqm4hep::online::EventCollectorClient::m_mutex = {} mutable private
Definition at line 123 of file EventCollectorClient.h.
Referenced by onEventUpdate(), readEvent(), receivingEventUpdates(), startEventUpdates(), and stopEventUpdates().
SourceInfoMap dqm4hep::online::EventCollectorClient::m_sourceInfoMap = {} private
Definition at line 121 of file EventCollectorClient.h.
Referenced by onEventUpdate(), receivingEventUpdates(), setUpdateMode(), startEventUpdates(), and stopEventUpdates().
The documentation for this class was generated from the following files:
EventCollectorClient.h
EventCollectorClient.cc