DQMOnline: dqm4hep::core::NetworkTool Class Reference
dqm4hep::core::NetworkTool Class Reference
NetworkTool class.
#include <NetworkTool.h>
Static Public Member Functions
static StringVector getEventCollectors ()
Returns the event collector list currently running on the network.
static StringVector getMonitorElementCollectors ()
Returns the monitor element collector list currently running on the network.
static bool eventCollectorExists (const std::string &collectorName)
Whether the data collector is currently running on the network.
static bool monitorElementCollectorExists (const std::string &collectorName)
Whether the monitor element collector is currently running on the network.
Detailed Description
NetworkTool class.
Definition at line 41 of file NetworkTool.h.
Member Function Documentation
bool dqm4hep::core::NetworkTool::eventCollectorExists (const std::string & collectorName) static
Whether the data collector is currently running on the network.
Definition at line 109 of file NetworkTool.cc.
References getEventCollectors().
     {
       // get the whole list
       StringVector eventCollectorList = NetworkTool::getEventCollectors();
       // and find the specific one
       return ( std::find(eventCollectorList.begin(), eventCollectorList.end(), collectorName) != eventCollectorList.end() );
     }
StringVector dqm4hep::core::NetworkTool::getEventCollectors () static
Returns the event collector list currently running on the network.
Definition at line 41 of file NetworkTool.cc.
Referenced by eventCollectorExists().
     {
       DimBrowser browser;
       std::string collectorBase = "DQM4HEP/EventCollector/";
       int nServers = browser.getServers();
       if(nServers == 0)
         return StringVector();
       char *pServer;
       char *pNode;
       StringVector collectorNameList;
       // iterates one servers
       while(browser.getNextServer(pServer, pNode))
       {
         std::string server = pServer;
         if(server.size() < collectorBase.size())
           continue;
         if(server.substr(0, collectorBase.size()) == collectorBase)
         {
           std::string collectorName = server.substr(collectorBase.size());
           collectorNameList.push_back(collectorName);
         }
       }
       return collectorNameList;
     }
StringVector dqm4hep::core::NetworkTool::getMonitorElementCollectors () static
Returns the monitor element collector list currently running on the network.
Definition at line 75 of file NetworkTool.cc.
Referenced by monitorElementCollectorExists().
     {
       DimBrowser browser;
       std::string collectorBase = "DQM4HEP/MonitorElementCollector/";
       int nServers = browser.getServers();
       if(nServers == 0)
         return StringVector();
       char *pServer;
       char *pNode;
       StringVector collectorNameList;
       // iterates one servers
       while(browser.getNextServer(pServer, pNode))
       {
         std::string server = pServer;
         if(server.size() < collectorBase.size())
           continue;
         if(server.substr(0, collectorBase.size()) == collectorBase)
         {
           std::string collectorName = server.substr(collectorBase.size());
           collectorNameList.push_back(collectorName);
         }
       }
       return collectorNameList;
     }
bool dqm4hep::core::NetworkTool::monitorElementCollectorExists (const std::string & collectorName) static
Whether the monitor element collector is currently running on the network.
Definition at line 120 of file NetworkTool.cc.
References getMonitorElementCollectors().
     {
       // get the whole list
       StringVector monitorElementCollectorList = NetworkTool::getMonitorElementCollectors();
       // and find the specific one
       return ( std::find(monitorElementCollectorList.begin(), monitorElementCollectorList.end(), collectorName) != monitorElementCollectorList.end() );
     }
The documentation for this class was generated from the following files:
NetworkTool.h
NetworkTool.cc