DQMNet: dqm4hep::net::SocketServerBase< socket_type > Class Template Reference
dqm4hep::net::SocketServerBase< socket_type > Class Template Reference abstract
#include <WsServer.h>
Classes
class Config
class Connection
class Endpoint
class Message
class regex_orderable
class SendStream
class streambuffer
Public Member Functions
virtual ~SocketServerBase ()
virtual void start ()
void stop ()
std::shared_ptr< SendStream > prepareHeader (const std::shared_ptr< SendStream > &message_stream, unsigned char fin_rsv_opcode) const
void forward (const std::unordered_set< std::shared_ptr< Connection >> &connections, const std::shared_ptr< SendStream > &message_stream, const std::function< void(const boost::system::error_code &)> &callback=nullptr, unsigned char fin_rsv_opcode=129) const
void send (const std::shared_ptr< Connection > &connection, const std::shared_ptr< SendStream > &message_stream, const std::function< void(const boost::system::error_code &)> &callback=nullptr, unsigned char fin_rsv_opcode=129) const
fin_rsv_opcode: 129=one fragment, text, 130=one fragment, binary, 136=close connection.
void send_close (const std::shared_ptr< Connection > &connection, int status, const std::string &reason="", const std::function< void(const boost::system::error_code &)> &callback=nullptr) const
std::unordered_set
< std::shared_ptr< Connection > > get_connections ()
void upgrade (const std::shared_ptr< Connection > &connection)
Upgrades a request, from for instance Simple-Web-Server, to a WebSocket connection.
Public Attributes
Config config
Set before calling start().
std::map< regex_orderable,
Endpoint > endpoint
Warning: do not add or remove endpoints after start() is called.
std::shared_ptr
< boost::asio::io_service > io_service
If you have your own boost::asio::io_service, store its pointer here before running start().
Protected Member Functions
SocketServerBase (unsigned short port)
virtual void accept ()=0
std::shared_ptr
< boost::asio::deadline_timer > get_timeout_timer (const std::shared_ptr< Connection > &connection, size_t seconds)
void read_handshake (const std::shared_ptr< Connection > &connection)
void parse_handshake (const std::shared_ptr< Connection > &connection, std::istream &stream) const
void write_handshake (const std::shared_ptr< Connection > &connection, const std::shared_ptr< boost::asio::streambuf > &read_buffer)
bool generate_handshake (const std::shared_ptr< Connection > &connection, std::ostream &handshake) const
void read_message (const std::shared_ptr< Connection > &connection, const std::shared_ptr< boost::asio::streambuf > &read_buffer, Endpoint &endpoint) const
void read_message_content (const std::shared_ptr< Connection > &connection, const std::shared_ptr< boost::asio::streambuf > &read_buffer, size_t length, Endpoint &endpoint, unsigned char fin_rsv_opcode) const
void connection_open (const std::shared_ptr< Connection > &connection, Endpoint &endpoint)
void connection_close (const std::shared_ptr< Connection > &connection, Endpoint &endpoint, int status, const std::string &reason) const
void connection_error (const std::shared_ptr< Connection > &connection, Endpoint &endpoint, const boost::system::error_code &ec) const
void timer_idle_init (const std::shared_ptr< Connection > &connection)
void timer_idle_reset (const std::shared_ptr< Connection > &connection) const
void timer_idle_cancel (const std::shared_ptr< Connection > &connection) const
void timer_idle_expired_function (const std::shared_ptr< Connection > &connection) const
Protected Attributes
const std::string ws_magic_string = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
std::unique_ptr
< boost::asio::ip::tcp::acceptor > acceptor
std::vector< std::thread > threads
Detailed Description
template<class socket_type>
class dqm4hep::net::SocketServerBase< socket_type >
Definition at line 301 of file WsServer.h.
Constructor & Destructor Documentation
template<class socket_type> virtual dqm4hep::net::SocketServerBase< socket_type >::~SocketServerBase () inline virtual
Definition at line 303 of file WsServer.h.
{
       }
template<class socket_type> dqm4hep::net::SocketServerBase< socket_type >::SocketServerBase (unsigned short port) inline protected
Definition at line 697 of file WsServer.h.
                                             : config(port) {
       }
Member Function Documentation
template<class socket_type> virtual void dqm4hep::net::SocketServerBase< socket_type >::accept () protected pure virtual
Implemented in dqm4hep::net::SocketServer< WS >.
Referenced by dqm4hep::net::SocketServerBase< WS >::start().
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::connection_close (const std::shared_ptr< Connection > & connection, Endpoint & endpoint, int status, const std::string & reason) const inline protected
Definition at line 966 of file WsServer.h.
{
         timer_idle_cancel(connection);
         {
           std::lock_guard<std::mutex> lock(endpoint.connections_mutex);
           endpoint.connections.erase(connection);
         }
         if (endpoint.on_close)
           endpoint.on_close(connection, status, reason);
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::connection_error (const std::shared_ptr< Connection > & connection, Endpoint & endpoint, const boost::system::error_code & ec) const inline protected
Definition at line 979 of file WsServer.h.
{
         timer_idle_cancel(connection);
         {
           std::lock_guard<std::mutex> lock(endpoint.connections_mutex);
           endpoint.connections.erase(connection);
         }
         if (endpoint.on_error)
           endpoint.on_error(connection, ec);
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::connection_open (const std::shared_ptr< Connection > & connection, Endpoint & endpoint) inline protected
Definition at line 954 of file WsServer.h.
{
         timer_idle_init(connection);
         {
           std::lock_guard<std::mutex> lock(endpoint.connections_mutex);
           endpoint.connections.insert(connection);
         }
         if (endpoint.on_open)
           endpoint.on_open(connection);
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::forward (const std::unordered_set< std::shared_ptr< Connection >> & connections, const std::shared_ptr< SendStream > & message_stream, const std::function< void(const boost::system::error_code &)> & callback = nullptr, unsigned char fin_rsv_opcode = 129) const inline
Definition at line 600 of file WsServer.h.
{
         auto header_stream = prepareHeader(message_stream, fin_rsv_opcode);
         for (auto connection : connections) {
           if (fin_rsv_opcode != 136)
             timer_idle_reset(connection);
           connection->strand.post([this, connection, header_stream, message_stream, callback]() {
             connection->send_queue.emplace_back(header_stream, message_stream, callback);
             if (connection->send_queue.size() == 1)
               connection->send_from_queue(connection);
           });
         }
       }
template<class socket_type> bool dqm4hep::net::SocketServerBase< socket_type >::generate_handshake (const std::shared_ptr< Connection > & connection, std::ostream & handshake) const inline protected
Definition at line 803 of file WsServer.h.
{
         auto header_it = connection->header.find("Sec-WebSocket-Key");
         if (header_it == connection->header.end())
           return false;
         auto sha1 = Crypto::sha1(header_it->second + ws_magic_string);
         handshake << "HTTP/1.1 101 Web Socket Protocol Handshake\r\n";
         handshake << "Upgrade: websocket\r\n";
         handshake << "Connection: Upgrade\r\n";
         handshake << "Sec-WebSocket-Accept: " << Crypto::Base64::encode(sha1) << "\r\n";
         handshake << "\r\n";
         return true;
       }
template<class socket_type> std::unordered_set<std::shared_ptr<Connection> > dqm4hep::net::SocketServerBase< socket_type >::get_connections () inline
Definition at line 654 of file WsServer.h.
{
         std::unordered_set<std::shared_ptr<Connection>> all_connections;
         for (auto &e : endpoint) {
           std::lock_guard<std::mutex> lock(e.second.connections_mutex);
           all_connections.insert(e.second.connections.begin(), e.second.connections.end());
         }
         return all_connections;
       }
template<class socket_type> std::shared_ptr<boost::asio::deadline_timer> dqm4hep::net::SocketServerBase< socket_type >::get_timeout_timer (const std::shared_ptr< Connection > & connection, size_t seconds) inline protected
Definition at line 702 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::read_handshake().
{
         if (seconds == 0)
           return nullptr;
         auto timer = std::make_shared<boost::asio::deadline_timer>(connection->socket->get_io_service());
         timer->expires_from_now(boost::posix_time::seconds(static_cast<long>(seconds)));
         timer->async_wait([connection](const boost::system::error_code &ec) {
           if (!ec) {
             connection->socket->lowest_layer().shutdown(boost::asio::ip::tcp::socket::shutdown_both);
             connection->socket->lowest_layer().close();
           }
         });
         return timer;
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::parse_handshake (const std::shared_ptr< Connection > & connection, std::istream & stream) const inline protected
Definition at line 744 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::read_handshake().
{
         std::string line;
         getline(stream, line);
         size_t method_end;
         if ((method_end = line.find(' ')) != std::string::npos) {
           size_t path_end;
           if ((path_end = line.find(' ', method_end + 1)) != std::string::npos) {
             connection->method = line.substr(0, method_end);
             connection->path = line.substr(method_end + 1, path_end - method_end - 1);
             if ((path_end + 6) < line.size())
               connection->http_version = line.substr(path_end + 6, line.size() - (path_end + 6) - 1);
             else
               connection->http_version = "1.1";
             getline(stream, line);
             size_t param_end;
             while ((param_end = line.find(':')) != std::string::npos) {
               size_t value_start = param_end + 1;
               if ((value_start) < line.size()) {
                 if (line[value_start] == ' ')
                   value_start++;
                 if (value_start < line.size())
                   connection->header.emplace(line.substr(0, param_end),
                                              line.substr(value_start, line.size() - value_start - 1));
               }
               getline(stream, line);
             }
           }
         }
       }
template<class socket_type> std::shared_ptr<SendStream> dqm4hep::net::SocketServerBase< socket_type >::prepareHeader (const std::shared_ptr< SendStream > & message_stream, unsigned char fin_rsv_opcode) const inline
Definition at line 573 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::forward(), and dqm4hep::net::SocketServerBase< WS >::send().
{
         auto header_stream = std::make_shared<SendStream>();
         size_t length = message_stream->size();
         header_stream->put(fin_rsv_opcode);
         // unmasked (first length byte<128)
         if (length >= 126) {
           int num_bytes;
           if (length > 0xffff) {
             num_bytes = 8;
             header_stream->put(127);
           } else {
             num_bytes = 2;
             header_stream->put(126);
           }
           for (int c = num_bytes - 1; c >= 0; c--) {
             header_stream->put((static_cast<unsigned long long>(length) >> (8 * c)) % 256);
           }
         } else
           header_stream->put(static_cast<unsigned char>(length));
         return header_stream;
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::read_handshake (const std::shared_ptr< Connection > & connection) inline protected
Definition at line 718 of file WsServer.h.
{
         connection->read_remote_endpoint_data();
         // Create new read_buffer for async_read_until()
         // Shared_ptr is used to pass temporary objects to the asynchronous functions
         auto read_buffer = std::make_shared<boost::asio::streambuf>();
         // Set timeout on the following boost::asio::async-read or write function
         auto timer = get_timeout_timer(connection, config.timeout_request);
         boost::asio::async_read_until(
             *connection->socket, *read_buffer, "\r\n\r\n",
             [this, connection, read_buffer, timer](const boost::system::error_code &ec, size_t /*bytes_transferred*/) {
               if (timer)
                 timer->cancel();
               if (!ec) {
                 // Convert to istream to extract string-lines
                 std::istream stream(read_buffer.get());
                 parse_handshake(connection, stream);
                 write_handshake(connection, read_buffer);
               }
             });
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::read_message (const std::shared_ptr< Connection > & connection, const std::shared_ptr< boost::asio::streambuf > & read_buffer, Endpoint & endpoint) const inline protected
Definition at line 819 of file WsServer.h.
{
         boost::asio::async_read(
             *connection->socket, *read_buffer, boost::asio::transfer_exactly(2),
             [this, connection, read_buffer, &endpoint](const boost::system::error_code &ec, size_t bytes_transferred) {
               if (!ec) {
                 if (bytes_transferred == 0) { // TODO: why does this happen sometimes?
                   read_message(connection, read_buffer, endpoint);
                   return;
                 }
                 std::istream stream(read_buffer.get());
                 std::vector<unsigned char> first_bytes;
                 first_bytes.resize(2);
                 stream.read((char *)&first_bytes[0], 2);
                 unsigned char fin_rsv_opcode = first_bytes[0];
                 // Close connection if unmasked message from client (protocol error)
                 if (first_bytes[1] < 128) {
                   const std::string reason("message from client not masked");
                   send_close(connection, 1002, reason, [this, connection](const boost::system::error_code & /*ec*/) {});
                   connection_close(connection, endpoint, 1002, reason);
                   return;
                 }
                 size_t length = (first_bytes[1] & 127);
                 if (length == 126) {
                   // 2 next bytes is the size of content
                   boost::asio::async_read(*connection->socket, *read_buffer, boost::asio::transfer_exactly(2),
                                           [this, connection, read_buffer, &endpoint, fin_rsv_opcode](
                                               const boost::system::error_code &ec, size_t /*bytes_transferred*/) {
                                             if (!ec) {
                                               std::istream stream(read_buffer.get());
                                               std::vector<unsigned char> length_bytes;
                                               length_bytes.resize(2);
                                               stream.read((char *)&length_bytes[0], 2);
                                               size_t length = 0;
                                               int num_bytes = 2;
                                               for (int c = 0; c < num_bytes; c++)
                                                 length += length_bytes[c] << (8 * (num_bytes - 1 - c));
                                               read_message_content(connection, read_buffer, length, endpoint,
                                                                    fin_rsv_opcode);
                                             } else
                                               connection_error(connection, endpoint, ec);
                                           });
                 } else if (length == 127) {
                   // 8 next bytes is the size of content
                   boost::asio::async_read(*connection->socket, *read_buffer, boost::asio::transfer_exactly(8),
                                           [this, connection, read_buffer, &endpoint, fin_rsv_opcode](
                                               const boost::system::error_code &ec, size_t /*bytes_transferred*/) {
                                             if (!ec) {
                                               std::istream stream(read_buffer.get());
                                               std::vector<unsigned char> length_bytes;
                                               length_bytes.resize(8);
                                               stream.read((char *)&length_bytes[0], 8);
                                               size_t length = 0;
                                               int num_bytes = 8;
                                               for (int c = 0; c < num_bytes; c++)
                                                 length += length_bytes[c] << (8 * (num_bytes - 1 - c));
                                               read_message_content(connection, read_buffer, length, endpoint,
                                                                    fin_rsv_opcode);
                                             } else
                                               connection_error(connection, endpoint, ec);
                                           });
                 } else
                   read_message_content(connection, read_buffer, length, endpoint, fin_rsv_opcode);
               } else
                 connection_error(connection, endpoint, ec);
             });
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::read_message_content (const std::shared_ptr< Connection > & connection, const std::shared_ptr< boost::asio::streambuf > & read_buffer, size_t length, Endpoint & endpoint, unsigned char fin_rsv_opcode) const inline protected
Definition at line 898 of file WsServer.h.
{
         boost::asio::async_read(*connection->socket, *read_buffer, boost::asio::transfer_exactly(4 + length),
                                 [this, connection, read_buffer, length, &endpoint,
                                  fin_rsv_opcode](const boost::system::error_code &ec, size_t /*bytes_transferred*/) {
                                   if (!ec) {
                                     std::istream raw_message_data(read_buffer.get());
                                     // Read mask
                                     std::vector<unsigned char> mask;
                                     mask.resize(4);
                                     raw_message_data.read((char *)&mask[0], 4);
                                     std::shared_ptr<Message> message(new Message());
                                     message->length = length;
                                     message->fin_rsv_opcode = fin_rsv_opcode;
                                     std::ostream message_data_out_stream(&message->streambuf);
                                     for (size_t c = 0; c < length; c++) {
                                       message_data_out_stream.put(raw_message_data.get() ^ mask[c % 4]);
                                     }
                                     // If connection close
                                     if ((fin_rsv_opcode & 0x0f) == 8) {
                                       int status = 0;
                                       if (length >= 2) {
                                         unsigned char byte1 = message->get();
                                         unsigned char byte2 = message->get();
                                         status = (byte1 << 8) + byte2;
                                       }
                                       auto reason = message->string();
                                       send_close(connection, status, reason,
                                                  [this, connection](const boost::system::error_code & /*ec*/) {});
                                       connection_close(connection, endpoint, status, reason);
                                       return;
                                     } else {
                                       // If ping
                                       if ((fin_rsv_opcode & 0x0f) == 9) {
                                         // send pong
                                         auto empty_send_stream = std::make_shared<SendStream>();
                                         send(connection, empty_send_stream, nullptr, fin_rsv_opcode + 1);
                                       } else if (endpoint.on_message) {
                                         timer_idle_reset(connection);
                                         endpoint.on_message(connection, message);
                                       }
                                       // Next message
                                       read_message(connection, read_buffer, endpoint);
                                     }
                                   } else
                                     connection_error(connection, endpoint, ec);
                                 });
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::send (const std::shared_ptr< Connection > & connection, const std::shared_ptr< SendStream > & message_stream, const std::function< void(const boost::system::error_code &)> & callback = nullptr, unsigned char fin_rsv_opcode = 129) const inline
fin_rsv_opcode: 129=one fragment, text, 130=one fragment, binary, 136=close connection.
See http://tools.ietf.org/html/rfc6455#section-5.2 for more information
Definition at line 620 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::send_close().
{
         if (fin_rsv_opcode != 136)
           timer_idle_reset(connection);
         auto header_stream = prepareHeader(message_stream, fin_rsv_opcode);
         connection->strand.post([this, connection, header_stream, message_stream, callback]() {
           connection->send_queue.emplace_back(header_stream, message_stream, callback);
           if (connection->send_queue.size() == 1)
             connection->send_from_queue(connection);
         });
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::send_close (const std::shared_ptr< Connection > & connection, int status, const std::string & reason = "", const std::function< void(const boost::system::error_code &)> & callback = nullptr) const inline
Definition at line 636 of file WsServer.h.
{
         // Send close only once (in case close is initiated by server)
         if (connection->closed)
           return;
         connection->closed = true;
         auto send_stream = std::make_shared<SendStream>();
         send_stream->put(status >> 8);
         send_stream->put(status % 256);
         *send_stream << reason;
         // fin_rsv_opcode=136: message close
         send(connection, send_stream, callback, 136);
       }
template<class socket_type> virtual void dqm4hep::net::SocketServerBase< socket_type >::start () inline virtual
Definition at line 515 of file WsServer.h.
{
         for (auto &endp : endpoint) {
           // TODO: remove when onopen, onmessage, etc is removed:
           if (endp.second.onopen)
             endp.second.on_open = endp.second.onopen;
           if (endp.second.onmessage)
             endp.second.on_message = endp.second.onmessage;
           if (endp.second.onclose)
             endp.second.on_close = endp.second.onclose;
           if (endp.second.onerror)
             endp.second.on_error = endp.second.onerror;
         }
         if (!io_service)
           io_service = std::make_shared<boost::asio::io_service>();
         if (io_service->stopped())
           io_service->reset();
         boost::asio::ip::tcp::endpoint endpoint;
         if (config.address.size() > 0)
           endpoint = boost::asio::ip::tcp::endpoint(boost::asio::ip::address::from_string(config.address), config.port);
         else
           endpoint = boost::asio::ip::tcp::endpoint(boost::asio::ip::tcp::v4(), config.port);
         if (!acceptor)
           acceptor = std::unique_ptr<boost::asio::ip::tcp::acceptor>(new boost::asio::ip::tcp::acceptor(*io_service));
         acceptor->open(endpoint.protocol());
         acceptor->set_option(boost::asio::socket_base::reuse_address(config.reuse_address));
         acceptor->bind(endpoint);
         acceptor->listen();
         accept();
         // If thread_pool_size>1, start m_io_service.run() in (thread_pool_size-1) threads for thread-pooling
         threads.clear();
         for (size_t c = 1; c < config.thread_pool_size; c++) {
           threads.emplace_back([this]() { io_service->run(); });
         }
         // Main thread
         if (config.thread_pool_size > 0)
           io_service->run();
         // Wait for the rest of the threads, if any, to finish as well
         for (auto &t : threads) {
           t.join();
         }
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::stop () inline
Definition at line 564 of file WsServer.h.
                   {
         acceptor->close();
         if (config.thread_pool_size > 0)
           io_service->stop();
         for (auto &p : endpoint)
           p.second.connections.clear();
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::timer_idle_cancel (const std::shared_ptr< Connection > & connection) const inline protected
Definition at line 1009 of file WsServer.h.
{
         if (config.timeout_idle > 0)
           connection->timer_idle->cancel();
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::timer_idle_expired_function (const std::shared_ptr< Connection > & connection) const inline protected
Definition at line 1014 of file WsServer.h.
{
         connection->timer_idle->async_wait([this, connection](const boost::system::error_code &ec) {
           if (!ec)
             send_close(connection, 1000, "idle timeout"); // 1000=normal closure
         });
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::timer_idle_init (const std::shared_ptr< Connection > & connection) inline protected
Definition at line 992 of file WsServer.h.
{
         if (config.timeout_idle > 0) {
           connection->timer_idle = std::unique_ptr<boost::asio::deadline_timer>(
               new boost::asio::deadline_timer(connection->socket->get_io_service()));
           connection->timer_idle->expires_from_now(
               boost::posix_time::seconds(static_cast<unsigned long>(config.timeout_idle)));
           timer_idle_expired_function(connection);
         }
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::timer_idle_reset (const std::shared_ptr< Connection > & connection) const inline protected
Definition at line 1002 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::forward(), and dqm4hep::net::SocketServerBase< WS >::send().
{
         if (config.timeout_idle > 0 &&
             connection->timer_idle->expires_from_now(
                 boost::posix_time::seconds(static_cast<unsigned long>(config.timeout_idle))) > 0)
           timer_idle_expired_function(connection);
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::upgrade (const std::shared_ptr< Connection > & connection) inline
Upgrades a request, from for instance Simple-Web-Server, to a WebSocket connection.
The parameters are moved to the Connection object. See also Server::on_upgrade in the Simple-Web-Server project. The socket's io_service is used, thus running start() is not needed.
Example use: server.on_upgrade=[&socket_server] (auto socket, auto request) { auto connection=std::make_shared<SimpleWeb::SocketServer<SimpleWeb::WS>::Connection>(socket); connection->method=std::move(request->method); connection->path=std::move(request->path); connection->http_version=std::move(request->http_version); connection->header=std::move(request->header); connection->remote_endpoint_address=std::move(request->remote_endpoint_address); connection->remote_endpoint_port=request->remote_endpoint_port; socket_server.upgrade(connection); }
Definition at line 681 of file WsServer.h.
{
         auto read_buffer = std::make_shared<boost::asio::streambuf>();
         write_handshake(connection, read_buffer);
       }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::write_handshake (const std::shared_ptr< Connection > & connection, const std::shared_ptr< boost::asio::streambuf > & read_buffer) inline protected
Definition at line 776 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::read_handshake(), and dqm4hep::net::SocketServerBase< WS >::upgrade().
{
         // Find path- and method-match, and generate response
         for (auto &regex_endpoint : endpoint) {
           REGEX_NS::smatch path_match;
           if (REGEX_NS::regex_match(connection->path, path_match, regex_endpoint.first)) {
             auto write_buffer = std::make_shared<boost::asio::streambuf>();
             std::ostream handshake(write_buffer.get());
             if (generate_handshake(connection, handshake)) {
               connection->path_match = std::move(path_match);
               // Capture write_buffer in lambda so it is not destroyed before async_write is finished
               boost::asio::async_write(*connection->socket, *write_buffer,
                                        [this, connection, write_buffer, read_buffer, &regex_endpoint](
                                            const boost::system::error_code &ec, size_t /*bytes_transferred*/) {
                                          if (!ec) {
                                            connection_open(connection, regex_endpoint.second);
                                            read_message(connection, read_buffer, regex_endpoint.second);
                                          } else
                                            connection_error(connection, regex_endpoint.second, ec);
                                        });
             }
             return;
           }
         }
       }
Member Data Documentation
template<class socket_type> std::unique_ptr<boost::asio::ip::tcp::acceptor> dqm4hep::net::SocketServerBase< socket_type >::acceptor protected
Definition at line 693 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::start(), and dqm4hep::net::SocketServerBase< WS >::stop().
template<class socket_type> Config dqm4hep::net::SocketServerBase< socket_type >::config
Set before calling start().
Definition at line 495 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::read_handshake(), dqm4hep::net::SocketServerBase< WS >::start(), and dqm4hep::net::SocketServerBase< WS >::stop().
template<class socket_type> std::map<regex_orderable, Endpoint> dqm4hep::net::SocketServerBase< socket_type >::endpoint
Warning: do not add or remove endpoints after start() is called.
Definition at line 513 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::get_connections(), dqm4hep::net::SocketServerBase< WS >::start(), and dqm4hep::net::SocketServerBase< WS >::stop().
template<class socket_type> std::shared_ptr<boost::asio::io_service> dqm4hep::net::SocketServerBase< socket_type >::io_service
If you have your own boost::asio::io_service, store its pointer here before running start().
You might also want to set config.thread_pool_size to 0.
Definition at line 688 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::start(), and dqm4hep::net::SocketServerBase< WS >::stop().
template<class socket_type> std::vector<std::thread> dqm4hep::net::SocketServerBase< socket_type >::threads protected
Definition at line 695 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< WS >::start().
template<class socket_type> const std::string dqm4hep::net::SocketServerBase< socket_type >::ws_magic_string = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11" protected
Definition at line 691 of file WsServer.h.
The documentation for this class was generated from the following file:
WsServer.h