DQMNet: dqm4hep::net::SignalT< T, void > Class Template Reference
dqm4hep::net::SignalT< T, void > Class Template Reference
SignalT specialization for void type (no arg)
#include <DQMNet.h>
Public Types
typedef void(T::* Function)()
Public Types inherited from dqm4hep::net::SignalBase< void >
typedef std::vector
< SignalBase< void > * > Vector
Public Member Functions
SignalT (T *pClass, Function function)
void process ()
Process the callback.
const T * getClass () const
const Function getFunction () const
Public Member Functions inherited from dqm4hep::net::SignalBase< void >
virtual ~SignalBase ()
Destructor.
Private Attributes
T * m_pClass
Function m_function
Detailed Description
template<typename T>
class dqm4hep::net::SignalT< T, void >
SignalT specialization for void type (no arg)
See Also
SignalT
Definition at line 268 of file DQMNet.h.
Member Typedef Documentation
template<typename T > typedef void(T::* dqm4hep::net::SignalT< T, void >::Function)()
Definition at line 271 of file DQMNet.h.
Constructor & Destructor Documentation
template<typename T > dqm4hep::net::SignalT< T, void >::SignalT (T * pClass, Function function) inline
Definition at line 735 of file DQMNet.h.
                                                                  :
       m_pClass(pClass),
       m_function(function)
     {
       /* nop */
     }
Member Function Documentation
template<typename T > const T * dqm4hep::net::SignalT< T, void >::getClass () const inline
Definition at line 753 of file DQMNet.h.
References dqm4hep::net::SignalT< T, Args >::m_pClass.
Referenced by dqm4hep::net::Signal< void >::disconnect(), and dqm4hep::net::Signal< void >::isConnected().
     {
       return m_pClass;
     }
template<typename T > const SignalT< T, void >::Function dqm4hep::net::SignalT< T, void >::getFunction () const inline
Definition at line 761 of file DQMNet.h.
References dqm4hep::net::SignalT< T, Args >::m_function.
Referenced by dqm4hep::net::Signal< void >::disconnect(), and dqm4hep::net::Signal< void >::isConnected().
     {
       return m_function;
     }
template<typename T > void dqm4hep::net::SignalT< T, void >::process () inline virtual
Process the callback.
Implements dqm4hep::net::SignalBase< void >.
Definition at line 745 of file DQMNet.h.
References dqm4hep::net::SignalT< T, Args >::m_function, and dqm4hep::net::SignalT< T, Args >::m_pClass.
     {
       (m_pClass->*m_function)();
     }
Member Data Documentation
template<typename T > Function dqm4hep::net::SignalT< T, void >::m_function private
Definition at line 279 of file DQMNet.h.
template<typename T > T* dqm4hep::net::SignalT< T, void >::m_pClass private
Definition at line 278 of file DQMNet.h.
The documentation for this class was generated from the following file:
DQMNet.h