DQMNet: dqm4hep::net::SocketServerBase< socket_type >::streambuffer Class Reference
dqm4hep::net::SocketServerBase< socket_type >::streambuffer Class Reference
#include <WsServer.h>
Public Member Functions
streambuffer ()
char * begin_iptr ()
char * current_iptr ()
char * last_iptr ()
void bump (int i)
void seek (int pos)
Detailed Description
template<class socket_type>
class dqm4hep::net::SocketServerBase< socket_type >::streambuffer
Definition at line 382 of file WsServer.h.
Constructor & Destructor Documentation
template<class socket_type> dqm4hep::net::SocketServerBase< socket_type >::streambuffer::streambuffer () inline
Definition at line 384 of file WsServer.h.
 : boost::asio::streambuf() {/* nop */}
Member Function Documentation
template<class socket_type> char* dqm4hep::net::SocketServerBase< socket_type >::streambuffer::begin_iptr () inline
Definition at line 385 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< socket_type >::streambuffer::seek().
 { return this->eback(); }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::streambuffer::bump (int i) inline
Definition at line 388 of file WsServer.h.
 { this->gbump(i); }
template<class socket_type> char* dqm4hep::net::SocketServerBase< socket_type >::streambuffer::current_iptr () inline
Definition at line 386 of file WsServer.h.
 { return this->gptr(); }
template<class socket_type> char* dqm4hep::net::SocketServerBase< socket_type >::streambuffer::last_iptr () inline
Definition at line 387 of file WsServer.h.
Referenced by dqm4hep::net::SocketServerBase< socket_type >::streambuffer::seek().
 { return this->egptr(); }
template<class socket_type> void dqm4hep::net::SocketServerBase< socket_type >::streambuffer::seek (int pos) inline
Definition at line 389 of file WsServer.h.
References dqm4hep::net::SocketServerBase< socket_type >::streambuffer::begin_iptr(), and dqm4hep::net::SocketServerBase< socket_type >::streambuffer::last_iptr().
{
           this->setg( this->begin_iptr(), this->begin_iptr()+pos, this->last_iptr());
           // this->pubseekpos(pos);
         }
The documentation for this class was generated from the following file:
WsServer.h