DQMNet: dqm4hep::net::Signal< Args > Class Template Reference
dqm4hep::net::Signal< Args > Class Template Reference
Signal class.
#include <DQMNet.h>
Public Member Functions
~Signal ()
Destructor.
void process (Args...args)
Process the signal.
template<typename T , typename S >
bool connect (T *pClass, S function)
Connect a class method to this signal.
template<typename T >
bool disconnect (T *pClass)
Disconnect all class methods for a target class instance.
template<typename T , typename S >
bool disconnect (T *pClass, S function)
Disconnect a target class instance method.
void disconnectAll ()
Disconnect all class methods.
template<typename T >
bool isConnected (T *pClass) const
Whether the class instance has at least one connection with this signal.
template<typename T , typename S >
bool isConnected (T *pClass, S function) const
Whether the target class method is connected to this signal.
bool hasConnection () const
Whether this signal has at least one registered class method.
Private Attributes
SignalBase< Args...>::Vector m_callbacks
Detailed Description
template<typename... Args>
class dqm4hep::net::Signal< Args >
Signal class.
User interface class to use signals
Definition at line 336 of file DQMNet.h.
Constructor & Destructor Documentation
template<typename... Args> dqm4hep::net::Signal< Args >::~Signal () inline
Destructor.
Definition at line 432 of file DQMNet.h.
     {
       this->disconnectAll();
     }
Member Function Documentation
template<typename... Args> template<typename T , typename S > bool dqm4hep::net::Signal< Args >::connect (T * pClass, S function) inline
Connect a class method to this signal.
Definition at line 450 of file DQMNet.h.
Referenced by dqm4hep::net::CommandHandler::CommandHandler(), dqm4hep::net::RequestHandler::RequestHandler(), and dqm4hep::net::ServiceHandler::ServiceHandler().
     {
       // check for existing connection
       if(this->isConnected(pClass))
         return false;
       // add the callback
       m_callbacks.push_back(new SignalT<T, Args...>(pClass, function));
       return true;
     }
template<typename... Args> template<typename T > bool dqm4hep::net::Signal< Args >::disconnect (T * pClass) inline
Disconnect all class methods for a target class instance.
Definition at line 466 of file DQMNet.h.
     {
       for(auto iter = m_callbacks.begin(), endIter = m_callbacks.end() ; endIter != iter ; ++iter)
       {
         SignalT<T, Args...> *pCallBackT(dynamic_cast<SignalT<T, Args...> *>(*iter));
         if(!pCallBackT)
           continue;
         if(pCallBackT->getClass() == pClass)
         {
           delete pCallBackT;
           m_callbacks.erase(iter);
           return true;
         }
       }
       return false;
     }
template<typename... Args> template<typename T , typename S > bool dqm4hep::net::Signal< Args >::disconnect (T * pClass, S function) inline
Disconnect a target class instance method.
Definition at line 490 of file DQMNet.h.
     {
       for(auto iter = m_callbacks.begin(), endIter = m_callbacks.end() ; endIter != iter ; ++iter)
       {
         SignalT<T, Args...> *pCallBackT(dynamic_cast<SignalT<T, Args...> *>(*iter));
         if(!pCallBackT)
           continue;
         if(pCallBackT->getClass() == pClass && pCallBackT->getFunction() == function)
         {
           delete pCallBackT;
           m_callbacks.erase(iter);
           return true;
         }
       }
       return false;
     }
template<typename... Args> void dqm4hep::net::Signal< Args >::disconnectAll () inline
Disconnect all class methods.
Definition at line 513 of file DQMNet.h.
Referenced by dqm4hep::net::Signal< void >::~Signal().
     {
       for(auto iter = m_callbacks.begin(), endIter = m_callbacks.end() ; endIter != iter ; ++iter)
         delete *iter;
       m_callbacks.clear();
     }
template<typename... Args> bool dqm4hep::net::Signal< Args >::hasConnection () const inline
Whether this signal has at least one registered class method.
Definition at line 564 of file DQMNet.h.
     {
       return (!m_callbacks.empty());
     }
template<typename... Args> template<typename T > bool dqm4hep::net::Signal< Args >::isConnected (T * pClass) const inline
Whether the class instance has at least one connection with this signal.
Definition at line 525 of file DQMNet.h.
Referenced by dqm4hep::net::Signal< void >::connect().
     {
       for(auto iter = m_callbacks.begin(), endIter = m_callbacks.end() ; endIter != iter ; ++iter)
       {
         const SignalT<T, Args...> *pCallBackT(dynamic_cast<const SignalT<T, Args...> *>(*iter));
         if(!pCallBackT)
           continue;
         if(pCallBackT->getClass() == pClass)
           return true;
       }
       return false;
     }
template<typename... Args> template<typename T , typename S > bool dqm4hep::net::Signal< Args >::isConnected (T * pClass, S function) const inline
Whether the target class method is connected to this signal.
Definition at line 545 of file DQMNet.h.
     {
       for(auto iter = m_callbacks.begin(), endIter = m_callbacks.end() ; endIter != iter ; ++iter)
       {
         const SignalT<T, Args...> *pCallBackT(dynamic_cast<const SignalT<T, Args...> *>(*iter));
         if(!pCallBackT)
           continue;
         if(pCallBackT->getClass() == pClass && pCallBackT->getFunction() == function)
           return true;
       }
       return false;
     }
template<typename... Args> void dqm4hep::net::Signal< Args >::process (Args... args) inline
Process the signal.
Calls all registered class->method(args...) signal handlers
Definition at line 440 of file DQMNet.h.
Referenced by dqm4hep::net::Server::clientExitHandler(), dqm4hep::net::CommandHandler::handleCommand(), dqm4hep::net::RequestHandler::handleRequest(), and dqm4hep::net::ServiceHandler::receiveServiceUpdated().
     {
       for(auto iter = m_callbacks.begin(), endIter = m_callbacks.end() ; endIter != iter ; ++iter)
         (*iter)->process(args...);
     }
Member Data Documentation
template<typename... Args> SignalBase<Args...>::Vector dqm4hep::net::Signal< Args >::m_callbacks private
Definition at line 391 of file DQMNet.h.
Referenced by dqm4hep::net::Signal< void >::connect(), dqm4hep::net::Signal< void >::disconnect(), dqm4hep::net::Signal< void >::disconnectAll(), dqm4hep::net::Signal< void >::hasConnection(), dqm4hep::net::Signal< void >::isConnected(), and dqm4hep::net::Signal< void >::process().
The documentation for this class was generated from the following file:
DQMNet.h